openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/access/bookmarks/{bookmark_id}:
    put:
      deprecated: true
      description: Updates a configured Bookmark application.
      operationId: access-bookmark-applications-(-deprecated)-update-a-bookmark-application
      parameters:
        - in: path
          name: bookmark_id
          required: true
          schema:
            description: UUID.
            example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
            maxLength: 36
            type: string
            x-auditable: true
        - in: path
          name: account_id
          required: true
          schema:
            example: 699d98642c564d2e855e9661899b7252
            type: string
            x-auditable: true
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                        type: object
                    type: object
                  - properties:
                      result:
                        properties:
                          app_launcher_visible:
                            description: Displays the application in the App Launcher.
                            example: true
                            type: boolean
                            x-auditable: true
                          created_at:
                            example: '2014-01-01T05:20:00.12345Z'
                            format: date-time
                            type: string
                            x-auditable: true
                          domain:
                            description: The domain of the Bookmark application.
                            example: example.com
                            type: string
                            x-auditable: true
                          id:
                            description: >-
                              The unique identifier for the Bookmark
                              application.
                            type: string
                          logo_url:
                            description: >-
                              The image URL for the logo shown in the App
                              Launcher dashboard.
                            example: >-
                              https://www.cloudflare.com/img/logo-web-badges/cf-logo-on-white-bg.svg
                            type: string
                            x-auditable: true
                          name:
                            description: The name of the Bookmark application.
                            example: My Website
                            type: string
                            x-auditable: true
                          updated_at:
                            example: '2014-01-01T05:20:00.12345Z'
                            format: date-time
                            type: string
                            x-auditable: true
                        type: object
                type: object
          description: Update a Bookmark application response
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    minLength: 1
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: Update a Bookmark application response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update a Bookmark application
      tags:
        - Access Bookmark applications (Deprecated)
      x-api-token-group:
        - 'Access: Apps and Policies Write'
      x-cfDeprecation:
        description: >-
          This endpoint is deprecated in favor of using a specialized Access
          Application App Type.
        display: true
        eol: '2023-03-19'
        id: bookmarks_deprecation
