openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/access/logs/access_requests:
    get:
      description: Gets a list of Access authentication audit logs for an account.
      operationId: access-authentication-logs-get-access-authentication-logs
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
            x-auditable: true
        - description: The maximum number of log entries to retrieve.
          example: 25
          in: query
          name: limit
          schema:
            default: 25
            type: integer
        - description: The chronological sorting order for the logs.
          example: desc
          in: query
          name: direction
          schema:
            default: desc
            enum:
              - desc
              - asc
        - description: The earliest event timestamp to query.
          in: query
          name: since
          schema:
            example: '2020-07-01T05:20:00Z'
            format: date-time
            type: string
        - description: The latest event timestamp to query.
          in: query
          name: until
          schema:
            example: '2020-10-01T05:20:00Z'
            format: date-time
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      messages:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - true
                        example: true
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                    type: object
                  - properties:
                      result:
                        items:
                          properties:
                            action:
                              description: >-
                                The event that occurred, such as a login
                                attempt.
                              example: login
                              type: string
                            allowed:
                              default: false
                              description: The result of the authentication event.
                              type: boolean
                            app_domain:
                              description: The URL of the Access application.
                              example: test.example.com/admin
                              type: string
                            app_uid:
                              description: >-
                                The unique identifier for the Access
                                application.
                              example: df7e2w5f-02b7-4d9d-af26-8d1988fca630
                              type: string
                            connection:
                              description: The IdP used to authenticate.
                              example: saml
                              type: string
                            created_at:
                              example: '2014-01-01T05:20:00.12345Z'
                              format: date-time
                              type: string
                              x-auditable: true
                            ip_address:
                              description: The IP address of the authenticating user.
                              example: 198.41.129.166
                              type: string
                            ray_id:
                              description: >-
                                The unique identifier for the request to
                                Cloudflare.
                              example: 187d944c61940c77
                              maxLength: 16
                              type: string
                            user_email:
                              description: The email address of the authenticating user.
                              example: user@example.com
                              format: email
                              type: string
                          type: object
                        type: array
          description: Get Access authentication logs response
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    minLength: 1
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: Get Access authentication logs response failure
      security:
        - api_email: []
          api_key: []
      summary: Get Access authentication logs
      tags:
        - Access authentication logs
      x-api-token-group:
        - 'Access: Audit Logs Read'
