openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/load_balancers/preview/{preview_id}:
    get:
      description: >-
        Get the result of a previous preview operation using the provided
        preview_id.
      operationId: account-load-balancer-monitors-preview-result
      parameters:
        - in: path
          name: preview_id
          required: true
          schema:
            example: p1aba936b94213e5b8dca0c0dbf1f9cc
            type: string
        - in: path
          name: account_id
          required: true
          schema:
            description: Identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
            x-auditable: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                          - result
                        type: object
                      - properties:
                          result:
                            anyOf:
                              - nullable: true
                                type: object
                              - nullable: true
                                type: string
                    type: object
                  - properties:
                      result:
                        additionalProperties:
                          properties:
                            healthy:
                              type: boolean
                              x-auditable: true
                            origins:
                              items:
                                additionalProperties:
                                  description: >-
                                    The origin ipv4/ipv6 address or domain name
                                    mapped to it's health data.
                                  example:
                                    failure_reason: No failures
                                    healthy: true
                                    response_code: 200
                                    rtt: 66ms
                                  properties:
                                    failure_reason:
                                      type: string
                                      x-auditable: true
                                    healthy:
                                      type: boolean
                                      x-auditable: true
                                    response_code:
                                      type: number
                                      x-auditable: true
                                    rtt:
                                      type: string
                                      x-auditable: true
                                  type: object
                                maxProperties: 1
                                minProperties: 1
                                type: object
                              type: array
                          type: object
                        description: Resulting health data from a preview operation.
                        example:
                          abwlnp5jbqn45ecgxd03erbgtxtqai0d:
                            healthy: true
                            origins:
                              - originone.example.com.:
                                  failure_reason: No failures
                                  healthy: true
                                  response_code: 200
                                  rtt: 66ms
                        type: object
          description: Preview Result response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - allOf:
                          - properties:
                              errors:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    message:
                                      type: string
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              messages:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    message:
                                      type: string
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              success:
                                description: Whether the API call was successful
                                enum:
                                  - true
                                example: true
                                type: boolean
                            required:
                              - success
                              - errors
                              - messages
                              - result
                            type: object
                          - properties:
                              result:
                                anyOf:
                                  - nullable: true
                                    type: object
                                  - nullable: true
                                    type: string
                        type: object
                      - properties:
                          result:
                            additionalProperties:
                              properties:
                                healthy:
                                  type: boolean
                                  x-auditable: true
                                origins:
                                  items:
                                    additionalProperties:
                                      description: >-
                                        The origin ipv4/ipv6 address or domain
                                        name mapped to it's health data.
                                      example:
                                        failure_reason: No failures
                                        healthy: true
                                        response_code: 200
                                        rtt: 66ms
                                      properties:
                                        failure_reason:
                                          type: string
                                          x-auditable: true
                                        healthy:
                                          type: boolean
                                          x-auditable: true
                                        response_code:
                                          type: number
                                          x-auditable: true
                                        rtt:
                                          type: string
                                          x-auditable: true
                                      type: object
                                    maxProperties: 1
                                    minProperties: 1
                                    type: object
                                  type: array
                              type: object
                            description: Resulting health data from a preview operation.
                            example:
                              abwlnp5jbqn45ecgxd03erbgtxtqai0d:
                                healthy: true
                                origins:
                                  - originone.example.com.:
                                      failure_reason: No failures
                                      healthy: true
                                      response_code: 200
                                      rtt: 66ms
                            type: object
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
          description: Preview Result response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Preview Result
      tags:
        - Account Load Balancer Monitors
      x-api-token-group:
        - 'Load Balancing: Monitors and Pools Write'
        - 'Load Balancing: Monitors and Pools Read'
