openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/ai-gateway/gateways/{gateway_id}/datasets:
    get:
      operationId: aig-config-list-dataset
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            example: 3ebbcb006d4d46d7bb6a8c7f14676cb0
            type: string
        - in: path
          name: gateway_id
          required: true
          schema:
            description: gateway id
            example: my-gateway
            maxLength: 64
            minLength: 1
            pattern: ^[a-z0-9_]+(?:-[a-z0-9_]+)*$
            type: string
            x-auditable: true
        - in: query
          name: page
          schema:
            default: 1
            minimum: 1
            type: integer
        - in: query
          name: per_page
          schema:
            default: 20
            maximum: 100
            minimum: 1
            type: integer
        - in: query
          name: name
          schema:
            type: string
            x-auditable: true
        - in: query
          name: enable
          schema:
            type: boolean
            x-auditable: true
        - in: query
          name: search
          schema:
            description: Search by id, name, filters
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  result:
                    items:
                      properties:
                        account_id:
                          type: string
                        account_tag:
                          type: string
                        created_at:
                          format: date-time
                          type: string
                        enable:
                          type: boolean
                          x-auditable: true
                        filters:
                          items:
                            properties:
                              key:
                                enum:
                                  - created_at
                                  - request_content_type
                                  - response_content_type
                                  - success
                                  - cached
                                  - provider
                                  - model
                                  - cost
                                  - tokens
                                  - tokens_in
                                  - tokens_out
                                  - duration
                                  - feedback
                                type: string
                                x-auditable: true
                              operator:
                                enum:
                                  - eq
                                  - contains
                                  - lt
                                  - gt
                                type: string
                                x-auditable: true
                              value:
                                items:
                                  anyOf:
                                    - type: string
                                    - type: number
                                    - type: boolean
                                type: array
                                x-auditable: true
                            required:
                              - key
                              - operator
                              - value
                            type: object
                          type: array
                        gateway_id:
                          description: gateway id
                          example: my-gateway
                          maxLength: 64
                          minLength: 1
                          pattern: ^[a-z0-9_]+(?:-[a-z0-9_]+)*$
                          type: string
                          x-auditable: true
                        id:
                          type: string
                          x-auditable: true
                        modified_at:
                          format: date-time
                          type: string
                        name:
                          type: string
                          x-auditable: true
                      required:
                        - gateway_id
                        - name
                        - filters
                        - enable
                        - id
                        - account_id
                        - account_tag
                        - created_at
                        - modified_at
                      type: object
                    type: array
                  success:
                    type: boolean
                required:
                  - success
                  - result
                type: object
          description: List objects
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  result:
                    type: object
                  success:
                    example: false
                    type: boolean
                required:
                  - result
                  - success
                  - errors
                type: object
          description: Bad Request
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: List Datasets
      tags:
        - AI Gateway Datasets
      x-api-token-group:
        - AI Gateway Write
        - AI Gateway Read
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.api.account.aig
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
