openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/ai-gateway/gateways/{gateway_id}/logs/{id}/request:
    get:
      operationId: aig-config-get-gateway-log-request
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: path
          name: gateway_id
          required: true
          schema:
            description: gateway id
            example: my-gateway
            maxLength: 64
            minLength: 1
            pattern: ^[a-z0-9_]+(?:-[a-z0-9_]+)*$
            type: string
            x-auditable: true
        - in: path
          name: account_id
          required: true
          schema:
            example: 0d37909e38d3e99c29fa2cd343ac421a
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: Returns the request body from a specific log
        '404':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        code:
                          example: 7002
                          type: number
                        message:
                          example: Not Found
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  success:
                    type: boolean
                required:
                  - success
                  - errors
                type: object
          description: Not Found
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get Gateway Log Request
      tags:
        - AI Gateway Logs
      x-api-token-group:
        - AI Gateway Write
        - AI Gateway Read
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.api.account.aig
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
