openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/ai-gateway/gateways/{gateway_id}/logs:
    get:
      operationId: aig-config-list-gateway-logs
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            example: 0d37909e38d3e99c29fa2cd343ac421a
            type: string
        - in: path
          name: gateway_id
          required: true
          schema:
            description: gateway id
            example: my-gateway
            maxLength: 64
            minLength: 1
            pattern: ^[a-z0-9_]+(?:-[a-z0-9_]+)*$
            type: string
            x-auditable: true
        - in: query
          name: search
          schema:
            type: string
        - in: query
          name: page
          schema:
            default: 1
            minimum: 1
            type: integer
        - in: query
          name: per_page
          schema:
            default: 20
            maximum: 50
            minimum: 1
            type: integer
        - in: query
          name: order_by
          schema:
            default: created_at
            enum:
              - created_at
              - provider
              - model
              - model_type
              - success
              - cached
            type: string
        - in: query
          name: order_by_direction
          schema:
            default: desc
            enum:
              - asc
              - desc
            type: string
        - in: query
          name: filters
          schema:
            items:
              properties:
                key:
                  enum:
                    - id
                    - created_at
                    - request_content_type
                    - response_content_type
                    - success
                    - cached
                    - provider
                    - model
                    - model_type
                    - cost
                    - tokens
                    - tokens_in
                    - tokens_out
                    - duration
                    - feedback
                    - event_id
                    - request_type
                    - metadata.key
                    - metadata.value
                    - prompts.prompt_id
                    - prompts.version_id
                  type: string
                operator:
                  enum:
                    - eq
                    - neq
                    - contains
                    - lt
                    - gt
                  type: string
                value:
                  items:
                    anyOf:
                      - nullable: true
                        type: string
                      - type: number
                      - type: boolean
                  type: array
              required:
                - key
                - operator
                - value
              type: object
            type: array
        - in: query
          name: meta_info
          schema:
            type: boolean
        - in: query
          name: direction
          schema:
            deprecated: true
            enum:
              - asc
              - desc
            type: string
        - in: query
          name: start_date
          schema:
            deprecated: true
            format: date-time
            type: string
        - in: query
          name: end_date
          schema:
            deprecated: true
            format: date-time
            type: string
        - in: query
          name: min_cost
          schema:
            deprecated: true
            type: number
        - in: query
          name: max_cost
          schema:
            deprecated: true
            type: number
        - in: query
          name: min_tokens_in
          schema:
            deprecated: true
            type: number
        - in: query
          name: max_tokens_in
          schema:
            deprecated: true
            type: number
        - in: query
          name: min_tokens_out
          schema:
            deprecated: true
            type: number
        - in: query
          name: max_tokens_out
          schema:
            deprecated: true
            type: number
        - in: query
          name: min_total_tokens
          schema:
            deprecated: true
            type: number
        - in: query
          name: max_total_tokens
          schema:
            deprecated: true
            type: number
        - in: query
          name: min_duration
          schema:
            deprecated: true
            type: number
        - in: query
          name: max_duration
          schema:
            deprecated: true
            type: number
        - in: query
          name: feedback
          schema:
            anyOf:
              - enum:
                  - -1
                type: number
              - enum:
                  - 0
                type: number
              - enum:
                  - 1
                type: number
            deprecated: true
        - in: query
          name: success
          schema:
            deprecated: true
            type: boolean
        - in: query
          name: cached
          schema:
            deprecated: true
            type: boolean
        - in: query
          name: model
          schema:
            deprecated: true
            type: string
        - in: query
          name: model_type
          schema:
            deprecated: true
            type: string
        - in: query
          name: provider
          schema:
            deprecated: true
            type: string
        - in: query
          name: request_content_type
          schema:
            deprecated: true
            type: string
        - in: query
          name: response_content_type
          schema:
            deprecated: true
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  result:
                    items:
                      properties:
                        cached:
                          type: boolean
                        cost:
                          type: number
                        created_at:
                          format: date-time
                          type: string
                        custom_cost:
                          type: boolean
                        duration:
                          type: integer
                        id:
                          type: string
                        metadata:
                          type: string
                        model:
                          type: string
                        model_type:
                          type: string
                        path:
                          type: string
                        provider:
                          type: string
                        request_content_type:
                          type: string
                        request_type:
                          type: string
                        response_content_type:
                          type: string
                        status_code:
                          type: integer
                        step:
                          type: integer
                        success:
                          type: boolean
                        tokens_in:
                          nullable: true
                          type: integer
                        tokens_out:
                          nullable: true
                          type: integer
                      required:
                        - id
                        - created_at
                        - provider
                        - model
                        - path
                        - duration
                        - success
                        - cached
                        - tokens_in
                        - tokens_out
                      type: object
                    type: array
                  result_info:
                    properties:
                      count:
                        type: number
                      max_cost:
                        type: number
                      max_duration:
                        type: number
                      max_tokens_in:
                        type: number
                      max_tokens_out:
                        type: number
                      max_total_tokens:
                        type: number
                      min_cost:
                        type: number
                      min_duration:
                        type: number
                      min_tokens_in:
                        type: number
                      min_tokens_out:
                        type: number
                      min_total_tokens:
                        type: number
                      page:
                        type: number
                      per_page:
                        type: number
                      total_count:
                        type: number
                    type: object
                  success:
                    type: boolean
                required:
                  - success
                  - result
                  - result_info
                type: object
          description: Returns a list of Gateway Logs
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  result:
                    type: object
                  success:
                    example: false
                    type: boolean
                required:
                  - result
                  - success
                  - errors
                type: object
          description: Bad Request
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: List Gateway Logs
      tags:
        - AI Gateway Logs
      x-api-token-group:
        - AI Gateway Write
        - AI Gateway Read
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.api.account.aig
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
