openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/api_gateway/configuration:
    put:
      operationId: api-shield-settings-set-configuration-properties
      requestBody:
        content:
          application/json:
            schema:
              properties:
                auth_id_characteristics:
                  items:
                    anyOf:
                      - description: Auth ID Characteristic
                        properties:
                          name:
                            description: >-
                              The name of the characteristic field, i.e., the
                              header or cookie name.
                            example: authorization
                            maxLength: 128
                            type: string
                            x-auditable: true
                          type:
                            description: The type of characteristic.
                            enum:
                              - header
                              - cookie
                            example: header
                            type: string
                            x-auditable: true
                        required:
                          - type
                          - name
                      - description: Auth ID Characteristic extracted from JWT Token Claims
                        properties:
                          name:
                            description: >
                              Claim location expressed as
                              `$(token_config_id):$(json_path)`, where
                              `token_config_id` 

                              is the ID of the token configuration used in
                              validating the JWT, and `json_path` is a RFC 9535 

                              JSONPath (https://goessner.net/articles/JsonPath/,
                              https://www.rfc-editor.org/rfc/rfc9535.html).

                              The JSONPath expression may be in dot or bracket
                              notation, may only specify literal keys

                              or array indexes, and must return a singleton
                              value, which will be interpreted as a string.
                            example: >-
                              e0de1a3a-8c2c-4f90-98d8-cbdf0a3f2cb5:$.foo.bar[0].baz
                            maxLength: 128
                            pattern: >-
                              ^(?<token_config_id>[a-z0-9\-]{32,36}):\$(?<json_path>.*?)$
                            type: string
                            x-auditable: true
                          type:
                            description: The type of characteristic.
                            enum:
                              - jwt
                            example: jwt
                            type: string
                            x-auditable: true
                        required:
                          - type
                          - name
                        type: object
                  maxItems: 10
                  type: array
                  uniqueItems: true
              required:
                - auth_id_characteristics
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    example: []
                    items:
                      properties:
                        code:
                          minimum: 1000
                          type: integer
                        documentation_url:
                          type: string
                        message:
                          type: string
                        source:
                          properties:
                            pointer:
                              type: string
                          type: object
                      required:
                        - code
                        - message
                      type: object
                      uniqueItems: true
                    type: array
                  messages:
                    example: []
                    items:
                      properties:
                        code:
                          minimum: 1000
                          type: integer
                        documentation_url:
                          type: string
                        message:
                          type: string
                        source:
                          properties:
                            pointer:
                              type: string
                          type: object
                      required:
                        - code
                        - message
                      type: object
                      uniqueItems: true
                    type: array
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - true
                    example: true
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                type: object
          description: Set configuration properties response
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    minLength: 1
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: Set configuration properties response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Set configuration properties
      tags:
        - API Shield Settings
      x-api-token-group:
        - Account API Gateway
        - Domain API Gateway
