openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/autorag/rags/{id}/sync:
    patch:
      operationId: autorag-config-sync
      parameters:
        - in: path
          name: id
          required: true
          schema:
            description: rag id
            example: my-rag
            maxLength: 32
            minLength: 1
            pattern: ^[a-z0-9_]+(?:-[a-z0-9_]+)*$
            type: string
        - in: path
          name: account_id
          required: true
          schema:
            example: c3dc5f0b34a14ff8e1b3ec04895e1b22
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  result:
                    properties:
                      job_id:
                        type: string
                    required:
                      - job_id
                    type: object
                  success:
                    type: boolean
                required:
                  - success
                  - result
                type: object
          description: Returns the autorag sync status
        '404':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        code:
                          example: 7002
                          type: number
                        message:
                          example: autorag_not_found
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  success:
                    enum:
                      - false
                    type: boolean
                required:
                  - success
                  - errors
                type: object
          description: autorag_not_found
        '429':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        code:
                          example: 7020
                          type: number
                        message:
                          example: sync_in_cooldown
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  success:
                    enum:
                      - false
                    type: boolean
                required:
                  - success
                  - errors
                type: object
          description: sync_in_cooldown
        '503':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        code:
                          example: 7017
                          type: number
                        message:
                          example: unable_to_connect_to_autorag
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  success:
                    enum:
                      - false
                    type: boolean
                required:
                  - success
                  - errors
                type: object
          description: unable_to_connect_to_autorag
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Sync
      tags:
        - AutoRAG
      x-api-token-group:
        - Auto Rag Write
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.api.account.rag
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
