openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/calls/turn_keys:
    post:
      description: Creates a new Cloudflare Calls TURN key.
      operationId: calls-turn-key-create
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: The account identifier tag.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
            x-auditable: true
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  default: ''
                  description: A short description of a TURN key, not shown to end users.
                  example: my-turn-key
                  type: string
                  x-auditable: true
              type: object
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                properties:
                  created:
                    description: The date and time the item was created.
                    example: '2014-01-02T02:20:00Z'
                    format: date-time
                    type: string
                  key:
                    description: Bearer token
                    example: >-
                      66bcf64aa8907b9f9d90ac17746a77ce394c393b92b3916633dc02846e608ad4
                    maxLength: 64
                    minLength: 64
                    type: string
                    x-sensitive: true
                  modified:
                    description: The date and time the item was last modified.
                    example: '2014-01-02T02:20:00Z'
                    format: date-time
                    type: string
                  name:
                    default: ''
                    description: A short description of a TURN key, not shown to end users.
                    example: my-turn-key
                    type: string
                    x-auditable: true
                  uid:
                    description: A Cloudflare-generated unique identifier for a item.
                    example: 2a95132c15732412d22c1476fa83f27a
                    maxLength: 32
                    minLength: 32
                    type: string
                    x-auditable: true
                type: object
          description: Created a new TURN key
      security:
        - api_token: []
      summary: Create a new TURN key
      tags:
        - Calls TURN Keys
      x-api-token-group:
        - Calls Write
