openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/client_certificates/{client_certificate_id}:
    delete:
      description: >-
        Set a API Shield mTLS Client Certificate to pending_revocation status
        for processing to revoked status.
      operationId: client-certificate-for-a-zone-delete-client-certificate
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            description: Identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
        - in: path
          name: client_certificate_id
          required: true
          schema:
            description: Identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                        type: object
                    type: object
                  - properties:
                      result:
                        properties:
                          certificate:
                            description: The Client Certificate PEM
                            example: >-
                              -----BEGIN
                              CERTIFICATE-----\nMIIDmDCCAoC...dhDDE\n-----END
                              CERTIFICATE-----
                            readOnly: true
                            type: string
                          certificate_authority:
                            description: >-
                              Certificate Authority used to issue the Client
                              Certificate
                            properties:
                              id:
                                example: 568b6b74-7b0c-4755-8840-4e3b8c24adeb
                                type: string
                                x-auditable: true
                              name:
                                example: Cloudflare Managed CA for account
                                type: string
                                x-auditable: true
                            type: object
                          common_name:
                            description: Common Name of the Client Certificate
                            example: Cloudflare
                            readOnly: true
                            type: string
                            x-auditable: true
                          country:
                            description: Country, provided by the CSR
                            example: US
                            readOnly: true
                            type: string
                            x-auditable: true
                          csr:
                            description: >-
                              The Certificate Signing Request (CSR). Must be
                              newline-encoded.
                            example: >-
                              -----BEGIN CERTIFICATE
                              REQUEST-----\nMIICY....\n-----END CERTIFICATE
                              REQUEST-----\n
                            type: string
                            x-auditable: true
                          expires_on:
                            description: Date that the Client Certificate expires
                            example: '2033-02-20T23:18:00Z'
                            readOnly: true
                            type: string
                            x-auditable: true
                          fingerprint_sha256:
                            description: Unique identifier of the Client Certificate
                            example: >-
                              256c24690243359fb8cf139a125bd05ebf1d968b71e4caf330718e9f5c8a89ea
                            readOnly: true
                            type: string
                            x-auditable: true
                          id:
                            description: Identifier.
                            example: 023e105f4ecef8ad9ca31a8372d0c353
                            maxLength: 32
                            type: string
                          issued_on:
                            description: >-
                              Date that the Client Certificate was issued by the
                              Certificate Authority
                            example: '2023-02-23T23:18:00Z'
                            readOnly: true
                            type: string
                            x-auditable: true
                          location:
                            description: Location, provided by the CSR
                            example: Somewhere
                            readOnly: true
                            type: string
                            x-auditable: true
                          organization:
                            description: Organization, provided by the CSR
                            example: Organization
                            readOnly: true
                            type: string
                            x-auditable: true
                          organizational_unit:
                            description: Organizational Unit, provided by the CSR
                            example: Organizational Unit
                            readOnly: true
                            type: string
                            x-auditable: true
                          serial_number:
                            description: >-
                              The serial number on the created Client
                              Certificate.
                            example: 3bb94ff144ac567b9f75ad664b6c55f8d5e48182
                            readOnly: true
                            type: string
                            x-auditable: true
                          signature:
                            description: The type of hash used for the Client Certificate..
                            example: SHA256WithRSA
                            readOnly: true
                            type: string
                            x-auditable: true
                          ski:
                            description: Subject Key Identifier
                            example: 8e375af1389a069a0f921f8cc8e1eb12d784b949
                            readOnly: true
                            type: string
                            x-auditable: true
                          state:
                            description: State, provided by the CSR
                            example: CA
                            readOnly: true
                            type: string
                            x-auditable: true
                          status:
                            description: >-
                              Client Certificates may be active or revoked, and
                              the pending_reactivation or pending_revocation
                              represent in-progress asynchronous transitions
                            enum:
                              - active
                              - pending_reactivation
                              - pending_revocation
                              - revoked
                            example: active
                            type: string
                            x-auditable: true
                          validity_days:
                            description: >-
                              The number of days the Client Certificate will be
                              valid after the issued_on date
                            example: 3650
                            type: integer
                            x-auditable: true
          description: Revoke Client Certificate Response
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    minLength: 1
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: Revoke Client Certificate Response Failure
      security:
        - api_email: []
          api_key: []
      summary: Revoke Client Certificate
      tags:
        - API Shield Client Certificates for a Zone
      x-api-token-group:
        - SSL and Certificates Write
      x-cfPermissionsRequired:
        enum:
          - '#ssl:edit'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
