openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/d1/database:
    get:
      description: Returns a list of D1 databases.
      operationId: cloudflare-d1-list-databases
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Account identifier tag.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
            x-auditable: true
        - in: query
          name: name
          schema:
            description: a database name to search for.
            type: string
        - in: query
          name: page
          schema:
            default: 1
            description: Page number of paginated results.
            minimum: 1
            type: number
        - in: query
          name: per_page
          schema:
            default: 1000
            description: Number of items per page.
            maximum: 10000
            minimum: 10
            type: number
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      messages:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      result:
                        type: object
                      success:
                        description: Whether the API call was successful
                        enum:
                          - true
                        example: true
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
                  - properties:
                      result:
                        items:
                          properties:
                            created_at:
                              description: >-
                                Specifies the timestamp the resource was created
                                as an ISO8601 string.
                              example: '2022-11-15T18:25:44.442097Z'
                              format: date-time
                              readOnly: true
                              type: string
                              x-auditable: true
                            name:
                              description: D1 database name.
                              example: my-database
                              pattern: ^[a-z0-9][a-z0-9-_]*$
                              type: string
                              x-auditable: true
                            uuid:
                              description: D1 database identifier (UUID).
                              example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
                              readOnly: true
                              type: string
                              x-auditable: true
                            version:
                              example: production
                              pattern: ^(alpha|beta|production)$
                              type: string
                              x-auditable: true
                          type: object
                        type: array
                      result_info:
                        properties:
                          count:
                            description: Total number of results for the requested service
                            example: 1
                            type: number
                          page:
                            description: Current page within paginated list of results
                            example: 1
                            type: number
                          per_page:
                            description: Number of results per page of results
                            example: 20
                            type: number
                          total_count:
                            description: >-
                              Total results available without any search
                              parameters
                            example: 2000
                            type: number
                        type: object
          description: List D1 databases response
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    minLength: 1
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: List D1 databases response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: List D1 Databases
      tags:
        - D1
      x-api-token-group:
        - D1 Read
        - D1 Write
