openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/images/v2/direct_upload:
    post:
      description: >-
        Direct uploads allow users to upload images without API keys. A common
        use case are web apps, client-side applications, or mobile devices where
        users upload content directly to Cloudflare Images. This method creates
        a draft record for a future image. It returns an upload URL and an image
        identifier. To verify if the image itself has been uploaded, send an
        image details request
        (accounts/:account_identifier/images/v1/:identifier), and check that the
        `draft: true` property is not present.
      operationId: cloudflare-images-create-authenticated-direct-upload-url-v-2
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Account identifier tag.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
            x-auditable: true
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                creator:
                  description: Can set the creator field with an internal user ID.
                  type: string
                expiry:
                  default: Now + 30 minutes
                  description: >-
                    The date after which the upload will not be accepted.
                    Minimum: Now + 2 minutes. Maximum: Now + 6 hours.
                  example: '2021-01-02T02:20:00Z'
                  format: date-time
                  type: string
                  x-auditable: true
                id:
                  description: >-
                    Optional Image Custom ID. Up to 1024 chars. Can include any
                    number of subpaths, and utf8 characters. Cannot start nor
                    end with a / (forward slash). Cannot be a UUID.
                  example: this/is/my-customid
                  maxLength: 1024
                  type: string
                  x-auditable: true
                metadata:
                  description: >-
                    User modifiable key-value store. Can be used for keeping
                    references to another system of record, for managing images.
                  type: object
                requireSignedURLs:
                  default: false
                  description: >-
                    Indicates whether the image requires a signature token to be
                    accessed.
                  example: true
                  type: boolean
                  x-auditable: true
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                  x-auditable: true
                                message:
                                  type: string
                                  x-auditable: true
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                  x-auditable: true
                                message:
                                  type: string
                                  x-auditable: true
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          result:
                            anyOf:
                              - type: object
                              - items: {}
                                type: array
                              - type: string
                          success:
                            description: Whether the API call was successful
                            enum:
                              - true
                            example: true
                            type: boolean
                            x-auditable: true
                        required:
                          - success
                          - errors
                          - messages
                          - result
                        type: object
                      - properties:
                          result:
                            anyOf:
                              - type: object
                              - type: string
                    type: object
                  - properties:
                      result:
                        properties:
                          id:
                            description: Image unique identifier.
                            example: e22e9e6b-c02b-42fd-c405-6c32af5fe600
                            maxLength: 32
                            readOnly: true
                            type: string
                            x-auditable: true
                          uploadURL:
                            description: >-
                              The URL the unauthenticated upload can be
                              performed to using a single HTTP POST
                              (multipart/form-data) request.
                            example: >-
                              https://upload.imagedelivery.net/FxUufywByo0m2v3xhKSiU8/e22e9e6b-c02b-42fd-c405-6c32af5fe600
                            type: string
                            x-auditable: true
          description: Create authenticated direct upload URL V2 response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - allOf:
                          - properties:
                              errors:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                      x-auditable: true
                                    message:
                                      type: string
                                      x-auditable: true
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              messages:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                      x-auditable: true
                                    message:
                                      type: string
                                      x-auditable: true
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              result:
                                anyOf:
                                  - type: object
                                  - items: {}
                                    type: array
                                  - type: string
                              success:
                                description: Whether the API call was successful
                                enum:
                                  - true
                                example: true
                                type: boolean
                                x-auditable: true
                            required:
                              - success
                              - errors
                              - messages
                              - result
                            type: object
                          - properties:
                              result:
                                anyOf:
                                  - type: object
                                  - type: string
                        type: object
                      - properties:
                          result:
                            properties:
                              id:
                                description: Image unique identifier.
                                example: e22e9e6b-c02b-42fd-c405-6c32af5fe600
                                maxLength: 32
                                readOnly: true
                                type: string
                                x-auditable: true
                              uploadURL:
                                description: >-
                                  The URL the unauthenticated upload can be
                                  performed to using a single HTTP POST
                                  (multipart/form-data) request.
                                example: >-
                                  https://upload.imagedelivery.net/FxUufywByo0m2v3xhKSiU8/e22e9e6b-c02b-42fd-c405-6c32af5fe600
                                type: string
                                x-auditable: true
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                  x-auditable: true
                                message:
                                  type: string
                                  x-auditable: true
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                  x-auditable: true
                                message:
                                  type: string
                                  x-auditable: true
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful
                        enum:
                          - false
                        example: false
                        type: boolean
                        x-auditable: true
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
          description: Create authenticated direct upload URL V2 response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Create authenticated direct upload URL V2
      tags:
        - Cloudflare Images
      x-api-token-group:
        - Images Write
