openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/cloudforce-one/requests:
    post:
      operationId: cloudforce-one-request-list
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                completed_after:
                  allOf:
                    - example: '2022-04-01T05:20:00Z'
                      format: date-time
                      type: string
                      x-auditable: true
                  description: Retrieve requests completed after this time.
                  example: '2022-01-01T00:00:00Z'
                completed_before:
                  allOf:
                    - example: '2022-04-01T05:20:00Z'
                      format: date-time
                      type: string
                      x-auditable: true
                  description: Retrieve requests completed before this time.
                  example: '2024-01-01T00:00:00Z'
                created_after:
                  allOf:
                    - example: '2022-04-01T05:20:00Z'
                      format: date-time
                      type: string
                      x-auditable: true
                  description: Retrieve requests created after this time.
                  example: '2022-01-01T00:00:00Z'
                created_before:
                  allOf:
                    - example: '2022-04-01T05:20:00Z'
                      format: date-time
                      type: string
                      x-auditable: true
                  description: Retrieve requests created before this time.
                  example: '2024-01-01T00:00:00Z'
                page:
                  description: Page number of results.
                  type: integer
                per_page:
                  description: Number of results per page.
                  example: 10
                  type: integer
                request_type:
                  description: Requested information from request.
                  example: Victomology
                  type: string
                  x-auditable: true
                sort_by:
                  description: Field to sort results by.
                  example: created
                  type: string
                sort_order:
                  description: Sort order (asc or desc).
                  enum:
                    - asc
                    - desc
                  type: string
                status:
                  description: Request Status.
                  enum:
                    - open
                    - accepted
                    - reported
                    - approved
                    - completed
                    - declined
                  title: Request Status
                  type: string
                  x-auditable: true
              required:
                - page
                - per_page
              title: Request List Parameters
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      messages:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - true
                        example: true
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                    type: object
                  - properties:
                      result:
                        items:
                          properties:
                            completed:
                              allOf:
                                - example: '2022-04-01T05:20:00Z'
                                  format: date-time
                                  type: string
                                  x-auditable: true
                              description: Request completion time.
                              example: '2024-01-01T00:00:00Z'
                            created:
                              allOf:
                                - example: '2022-04-01T05:20:00Z'
                                  format: date-time
                                  type: string
                                  x-auditable: true
                              description: Request creation time.
                              example: '2022-04-01T00:00:00Z'
                            id:
                              description: UUID.
                              example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
                              maxLength: 36
                              type: string
                            message_tokens:
                              description: Tokens for the request messages.
                              example: 16
                              type: integer
                              x-auditable: true
                            priority:
                              enum:
                                - routine
                                - high
                                - urgent
                              title: Request Priority
                              type: string
                              x-auditable: true
                            readable_id:
                              description: Readable Request ID.
                              example: RFI-2022-000001
                              title: Request Readable ID
                              type: string
                              x-auditable: true
                            request:
                              description: Requested information from request.
                              example: Victomology
                              type: string
                              x-auditable: true
                            status:
                              description: Request Status.
                              enum:
                                - open
                                - accepted
                                - reported
                                - approved
                                - completed
                                - declined
                              title: Request Status
                              type: string
                              x-auditable: true
                            summary:
                              description: Brief description of the request.
                              example: DoS attack
                              type: string
                              x-auditable: true
                            tlp:
                              description: The CISA defined Traffic Light Protocol (TLP).
                              enum:
                                - clear
                                - amber
                                - amber-strict
                                - green
                                - red
                              title: TLP
                              type: string
                              x-auditable: true
                            tokens:
                              description: Tokens for the request.
                              type: integer
                              x-auditable: true
                            updated:
                              allOf:
                                - example: '2022-04-01T05:20:00Z'
                                  format: date-time
                                  type: string
                                  x-auditable: true
                              description: Request last updated time.
                              example: '2022-04-01T00:00:00Z'
                          required:
                            - id
                            - created
                            - updated
                            - priority
                            - request
                            - summary
                            - tlp
                          title: Request List Item
                          type: object
                        type: array
                    type: object
          description: List requests response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      messages:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - true
                        example: true
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                    type: object
                  - properties:
                      errors:
                        properties:
                          code:
                            example: 10433
                            type: integer
                          message:
                            example: request error
                            type: string
                        type: object
                      success:
                        example: false
                        type: boolean
                    type: object
          description: Create response failure.
      security:
        - api_email: []
          api_key: []
      summary: List Requests
      tags:
        - Request for Information (RFI)
      x-api-token-group:
        - Cloudforce One Write
