openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/intel/indicator-feeds/{feed_id}:
    get:
      operationId: custom-indicator-feeds-get-indicator-feed-metadata
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
            x-auditable: true
        - in: path
          name: feed_id
          required: true
          schema:
            description: Indicator feed ID
            example: 12
            type: integer
            x-auditable: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                        type: object
                    type: object
                  - properties:
                      result:
                        example:
                          created_on: '2023-05-12T12:21:56.777653Z'
                          description: example feed description
                          id: 1
                          is_attributable: false
                          is_downloadable: false
                          is_public: false
                          latest_upload_status: Complete
                          modified_on: '2023-06-18T03:13:34.123321Z'
                          name: example_feed_1
                        properties:
                          created_on:
                            description: The date and time when the data entry was created
                            format: date-time
                            type: string
                            x-auditable: true
                          description:
                            description: The description of the example test
                            type: string
                            x-auditable: true
                          id:
                            description: The unique identifier for the indicator feed
                            type: integer
                            x-auditable: true
                          is_attributable:
                            description: >-
                              Whether the indicator feed can be attributed to a
                              provider
                            type: boolean
                            x-auditable: true
                          is_downloadable:
                            description: Whether the indicator feed can be downloaded
                            type: boolean
                            x-auditable: true
                          is_public:
                            description: Whether the indicator feed is exposed to customers
                            type: boolean
                            x-auditable: true
                          latest_upload_status:
                            description: Status of the latest snapshot uploaded
                            enum:
                              - Mirroring
                              - Unifying
                              - Loading
                              - Provisioning
                              - Complete
                              - Error
                            type: string
                            x-auditable: true
                          modified_on:
                            description: >-
                              The date and time when the data entry was last
                              modified
                            format: date-time
                            type: string
                            x-auditable: true
                          name:
                            description: The name of the indicator feed
                            type: string
                            x-auditable: true
                          provider_id:
                            description: The unique identifier for the provider
                            type: string
                            x-auditable: true
                          provider_name:
                            description: The provider of the indicator feed
                            type: string
                            x-auditable: true
          description: Get indicator feed metadata
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - allOf:
                          - properties:
                              errors:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    documentation_url:
                                      type: string
                                    message:
                                      type: string
                                    source:
                                      properties:
                                        pointer:
                                          type: string
                                      type: object
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              messages:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    documentation_url:
                                      type: string
                                    message:
                                      type: string
                                    source:
                                      properties:
                                        pointer:
                                          type: string
                                      type: object
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              success:
                                description: Whether the API call was successful.
                                enum:
                                  - true
                                example: true
                                type: boolean
                            required:
                              - success
                              - errors
                              - messages
                            type: object
                        type: object
                      - properties:
                          result:
                            example:
                              created_on: '2023-05-12T12:21:56.777653Z'
                              description: example feed description
                              id: 1
                              is_attributable: false
                              is_downloadable: false
                              is_public: false
                              latest_upload_status: Complete
                              modified_on: '2023-06-18T03:13:34.123321Z'
                              name: example_feed_1
                            properties:
                              created_on:
                                description: >-
                                  The date and time when the data entry was
                                  created
                                format: date-time
                                type: string
                                x-auditable: true
                              description:
                                description: The description of the example test
                                type: string
                                x-auditable: true
                              id:
                                description: The unique identifier for the indicator feed
                                type: integer
                                x-auditable: true
                              is_attributable:
                                description: >-
                                  Whether the indicator feed can be attributed
                                  to a provider
                                type: boolean
                                x-auditable: true
                              is_downloadable:
                                description: Whether the indicator feed can be downloaded
                                type: boolean
                                x-auditable: true
                              is_public:
                                description: >-
                                  Whether the indicator feed is exposed to
                                  customers
                                type: boolean
                                x-auditable: true
                              latest_upload_status:
                                description: Status of the latest snapshot uploaded
                                enum:
                                  - Mirroring
                                  - Unifying
                                  - Loading
                                  - Provisioning
                                  - Complete
                                  - Error
                                type: string
                                x-auditable: true
                              modified_on:
                                description: >-
                                  The date and time when the data entry was last
                                  modified
                                format: date-time
                                type: string
                                x-auditable: true
                              name:
                                description: The name of the indicator feed
                                type: string
                                x-auditable: true
                              provider_id:
                                description: The unique identifier for the provider
                                type: string
                                x-auditable: true
                              provider_name:
                                description: The provider of the indicator feed
                                type: string
                                x-auditable: true
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
          description: Get indicator feeds response failure
      security:
        - api_email: []
          api_key: []
      summary: Get indicator feed metadata
      tags:
        - Custom Indicator Feeds
      x-api-token-group:
        - Intel Write
        - Intel Read
