openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/rulesets/{ruleset_id}/versions/{ruleset_version}:
    delete:
      description: Deletes an existing version of a zone ruleset.
      operationId: deleteZoneRulesetVersion
      parameters:
        - in: path
          name: ruleset_version
          required: true
          schema:
            description: The version of the ruleset.
            example: '1'
            pattern: ^[0-9]+$
            readOnly: true
            title: Version
            type: string
        - in: path
          name: ruleset_id
          required: true
          schema:
            description: The unique ID of the ruleset.
            example: 2f2feab2026849078ba485f918791bdc
            pattern: ^[0-9a-f]{32}$
            title: ID
            type: string
        - in: path
          name: zone_id
          required: true
          schema:
            description: The unique ID of the zone.
            example: 9f1839b6152d298aca64c4e906b6d074
            pattern: ^[0-9a-f]{32}$
            title: ID
            type: string
      responses:
        '204':
          description: An empty response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - description: A response object.
                    properties:
                      errors:
                        description: A list of error messages.
                        items:
                          description: A message.
                          properties:
                            code:
                              description: A unique code for this message.
                              example: 10000
                              title: Code
                              type: integer
                            message:
                              description: A text description of this message.
                              example: something bad happened
                              minLength: 1
                              title: Description
                              type: string
                            source:
                              description: The source of this message.
                              properties:
                                pointer:
                                  description: >-
                                    A JSON pointer to the field that is the
                                    source of the message.
                                  example: /rules/0/action
                                  minLength: 1
                                  title: Pointer
                                  type: string
                              required:
                                - pointer
                              title: Source
                              type: object
                          required:
                            - message
                          title: Message
                          type: object
                        title: Errors
                        type: array
                      messages:
                        description: A list of warning messages.
                        items:
                          description: A message.
                          properties:
                            code:
                              description: A unique code for this message.
                              example: 10000
                              title: Code
                              type: integer
                            message:
                              description: A text description of this message.
                              example: something bad happened
                              minLength: 1
                              title: Description
                              type: string
                            source:
                              description: The source of this message.
                              properties:
                                pointer:
                                  description: >-
                                    A JSON pointer to the field that is the
                                    source of the message.
                                  example: /rules/0/action
                                  minLength: 1
                                  title: Pointer
                                  type: string
                              required:
                                - pointer
                              title: Source
                              type: object
                          required:
                            - message
                          title: Message
                          type: object
                        title: Messages
                        type: array
                      result:
                        description: A result.
                        title: Result
                      success:
                        description: Whether the API call was successful.
                        title: Success
                        type: boolean
                    required:
                      - result
                      - success
                      - errors
                      - messages
                    title: Response
                    type: object
                  - properties:
                      result:
                        enum:
                          - null
                      success:
                        enum:
                          - false
          description: A failure response.
      security:
        - api_token: []
        - api_email: []
          api_key: []
        - api_email: []
          api_key: []
      summary: Delete a zone ruleset version
      tags:
        - Zone Rulesets
      x-api-token-group:
        - Response Compression Write
        - Config Settings Write
        - Dynamic URL Redirects Write
        - Cache Settings Write
        - Custom Errors Write
        - Origin Write
        - Managed headers Write
        - Zone Transform Rules Write
        - Mass URL Redirects Write
        - Magic Firewall Write
        - L4 DDoS Managed Ruleset Write
        - HTTP DDoS Managed Ruleset Write
        - Sanitize Write
        - Transform Rules Write
        - Select Configuration Write
        - Bot Management Write
        - Zone WAF Write
        - Account WAF Write
        - Account Rulesets Write
        - Logs Write
        - Logs Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
