openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/devices/networks/{network_id}:
    get:
      description: Fetches details for a single managed network.
      operationId: device-managed-networks-device-managed-network-details
      parameters:
        - in: path
          name: network_id
          required: true
          schema:
            description: API UUID.
            example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
            maxLength: 36
            type: string
            x-auditable: true
        - in: path
          name: account_id
          required: true
          schema:
            example: 699d98642c564d2e855e9661899b7252
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          result:
                            anyOf:
                              - type: object
                              - items:
                                  type: object
                                type: array
                              - type: string
                          success:
                            description: Whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                          - result
                        type: object
                      - properties:
                          result:
                            anyOf:
                              - type: object
                              - type: string
                            nullable: true
                            type: object
                        type: object
                    type: object
                  - properties:
                      result:
                        properties:
                          config:
                            description: >-
                              The configuration object containing information
                              for the WARP client to detect the managed network.
                            example:
                              sha256: >-
                                b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
                              tls_sockaddr: foo.bar:1234
                            oneOf:
                              - description: The Managed Network TLS Config Response.
                                properties:
                                  sha256:
                                    description: >-
                                      The SHA-256 hash of the TLS certificate
                                      presented by the host found at
                                      tls_sockaddr. If absent, regular
                                      certificate verification (trusted roots,
                                      valid timestamp, etc) will be used to
                                      validate the certificate.
                                    example: >-
                                      b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
                                    type: string
                                  tls_sockaddr:
                                    description: >-
                                      A network address of the form "host:port"
                                      that the WARP client will use to detect
                                      the presence of a TLS host.
                                    example: foobar:1234
                                    type: string
                                    x-auditable: true
                                required:
                                  - tls_sockaddr
                                type: object
                            type: object
                          name:
                            description: >-
                              The name of the device managed network. This name
                              must be unique.
                            example: managed-network-1
                            type: string
                            x-auditable: true
                          network_id:
                            description: API UUID.
                            example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
                            maxLength: 36
                            type: string
                            x-auditable: true
                          type:
                            description: The type of device managed network.
                            enum:
                              - tls
                            example: tls
                            type: string
                            x-auditable: true
                        type: object
                    type: object
          description: Get device managed network details response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - allOf:
                          - properties:
                              errors:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    message:
                                      type: string
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              messages:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    message:
                                      type: string
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              result:
                                anyOf:
                                  - type: object
                                  - items:
                                      type: object
                                    type: array
                                  - type: string
                              success:
                                description: Whether the API call was successful.
                                enum:
                                  - true
                                example: true
                                type: boolean
                            required:
                              - success
                              - errors
                              - messages
                              - result
                            type: object
                          - properties:
                              result:
                                anyOf:
                                  - type: object
                                  - type: string
                                nullable: true
                                type: object
                            type: object
                        type: object
                      - properties:
                          result:
                            properties:
                              config:
                                description: >-
                                  The configuration object containing
                                  information for the WARP client to detect the
                                  managed network.
                                example:
                                  sha256: >-
                                    b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
                                  tls_sockaddr: foo.bar:1234
                                oneOf:
                                  - description: The Managed Network TLS Config Response.
                                    properties:
                                      sha256:
                                        description: >-
                                          The SHA-256 hash of the TLS certificate
                                          presented by the host found at
                                          tls_sockaddr. If absent, regular
                                          certificate verification (trusted roots,
                                          valid timestamp, etc) will be used to
                                          validate the certificate.
                                        example: >-
                                          b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
                                        type: string
                                      tls_sockaddr:
                                        description: >-
                                          A network address of the form
                                          "host:port" that the WARP client will
                                          use to detect the presence of a TLS
                                          host.
                                        example: foobar:1234
                                        type: string
                                        x-auditable: true
                                    required:
                                      - tls_sockaddr
                                    type: object
                                type: object
                              name:
                                description: >-
                                  The name of the device managed network. This
                                  name must be unique.
                                example: managed-network-1
                                type: string
                                x-auditable: true
                              network_id:
                                description: API UUID.
                                example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
                                maxLength: 36
                                type: string
                                x-auditable: true
                              type:
                                description: The type of device managed network.
                                enum:
                                  - tls
                                example: tls
                                type: string
                                x-auditable: true
                            type: object
                        type: object
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
          description: Get device managed network details response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get device managed network details
      tags:
        - Device Managed Networks
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
