openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/devices/policy/{policy_id}/fallback_domains:
    get:
      description: >-
        Fetches the list of domains to bypass Gateway DNS resolution from a
        specified device settings profile. These domains will use the specified
        local DNS resolver instead.
      operationId: devices-get-local-domain-fallback-list-for-a-device-settings-policy
      parameters:
        - in: path
          name: policy_id
          required: true
          schema:
            example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
            maxLength: 36
            type: string
            x-auditable: true
        - in: path
          name: account_id
          required: true
          schema:
            example: 699d98642c564d2e855e9661899b7252
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          result:
                            anyOf:
                              - type: object
                              - items:
                                  type: object
                                type: array
                              - type: string
                          success:
                            description: Whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                          - result
                        type: object
                      - properties:
                          result:
                            items:
                              type: object
                            nullable: true
                            type: array
                          result_info:
                            properties:
                              count:
                                description: >-
                                  Total number of results for the requested
                                  service.
                                example: 1
                                type: number
                              page:
                                description: Current page within paginated list of results.
                                example: 1
                                type: number
                              per_page:
                                description: Number of results per page of results.
                                example: 20
                                type: number
                              total_count:
                                description: >-
                                  Total results available without any search
                                  parameters.
                                example: 2000
                                type: number
                            type: object
                        type: object
                    type: object
                  - properties:
                      result:
                        items:
                          properties:
                            description:
                              description: >-
                                A description of the fallback domain, displayed
                                in the client UI.
                              example: Domain bypass for local development
                              maxLength: 100
                              type: string
                              x-auditable: true
                            dns_server:
                              description: >-
                                A list of IP addresses to handle domain
                                resolution.
                              items:
                                description: IPv4 or IPv6 address.
                                example: 1.1.1.1
                                type: string
                                x-auditable: true
                              type: array
                            suffix:
                              description: >-
                                The domain suffix to match when resolving
                                locally.
                              example: example.com
                              type: string
                              x-auditable: true
                          required:
                            - suffix
                          type: object
                        type: array
                    type: object
          description: >-
            Get the Local Domain Fallback list for a device settings profile
            response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - allOf:
                          - properties:
                              errors:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    message:
                                      type: string
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              messages:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    message:
                                      type: string
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              result:
                                anyOf:
                                  - type: object
                                  - items:
                                      type: object
                                    type: array
                                  - type: string
                              success:
                                description: Whether the API call was successful.
                                enum:
                                  - true
                                example: true
                                type: boolean
                            required:
                              - success
                              - errors
                              - messages
                              - result
                            type: object
                          - properties:
                              result:
                                items:
                                  type: object
                                nullable: true
                                type: array
                              result_info:
                                properties:
                                  count:
                                    description: >-
                                      Total number of results for the requested
                                      service.
                                    example: 1
                                    type: number
                                  page:
                                    description: >-
                                      Current page within paginated list of
                                      results.
                                    example: 1
                                    type: number
                                  per_page:
                                    description: Number of results per page of results.
                                    example: 20
                                    type: number
                                  total_count:
                                    description: >-
                                      Total results available without any search
                                      parameters.
                                    example: 2000
                                    type: number
                                type: object
                            type: object
                        type: object
                      - properties:
                          result:
                            items:
                              properties:
                                description:
                                  description: >-
                                    A description of the fallback domain,
                                    displayed in the client UI.
                                  example: Domain bypass for local development
                                  maxLength: 100
                                  type: string
                                  x-auditable: true
                                dns_server:
                                  description: >-
                                    A list of IP addresses to handle domain
                                    resolution.
                                  items:
                                    description: IPv4 or IPv6 address.
                                    example: 1.1.1.1
                                    type: string
                                    x-auditable: true
                                  type: array
                                suffix:
                                  description: >-
                                    The domain suffix to match when resolving
                                    locally.
                                  example: example.com
                                  type: string
                                  x-auditable: true
                              required:
                                - suffix
                              type: object
                            type: array
                        type: object
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
          description: >-
            Get the Local Domain Fallback list for a device settings profile
            response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get the Local Domain Fallback list for a device settings profile
      tags:
        - Devices
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
