openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/dex/devices/dex_tests/{dex_test_id}:
    delete:
      description: >-
        Delete a Device DEX test. Returns the remaining device dex tests for the
        account.
      operationId: device-dex-test-delete-device-dex-test
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            example: 01a7362d577a6c3019a474fd6f485823
            maxLength: 32
            readOnly: true
            type: string
        - in: path
          name: dex_test_id
          required: true
          schema:
            description: API Resource UUID tag.
            example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
            maxLength: 36
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      messages:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - true
                        example: true
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                    type: object
                  - properties:
                      result:
                        properties:
                          dex_tests:
                            items:
                              properties:
                                data:
                                  description: >-
                                    The configuration object which contains the
                                    details for the WARP client to conduct the
                                    test.
                                  example:
                                    host: https://dash.cloudflare.com
                                    kind: http
                                    method: GET
                                  properties:
                                    host:
                                      description: The desired endpoint to test.
                                      example: https://dash.cloudflare.com
                                      type: string
                                    kind:
                                      description: The type of test.
                                      example: http
                                      type: string
                                    method:
                                      description: The HTTP request method type.
                                      example: GET
                                      type: string
                                  type: object
                                description:
                                  description: Additional details about the test.
                                  example: Checks the dash endpoint every 30 minutes
                                  type: string
                                enabled:
                                  description: >-
                                    Determines whether or not the test is
                                    active.
                                  example: true
                                  type: boolean
                                interval:
                                  description: How often the test will run.
                                  example: 30m
                                  type: string
                                name:
                                  description: The name of the DEX test. Must be unique.
                                  example: HTTP dash health check
                                  type: string
                                target_policies:
                                  description: DEX rules targeted by this test
                                  items:
                                    properties:
                                      default:
                                        description: >-
                                          Whether the DEX rule is the account
                                          default
                                        type: boolean
                                      id:
                                        description: The id of the DEX rule
                                        type: string
                                      name:
                                        description: The name of the DEX rule
                                        type: string
                                    type: object
                                  type: array
                                targeted:
                                  type: boolean
                                test_id:
                                  description: The unique identifier for the test.
                                  example: 372e67954025e0ba6aaa6d586b9e0b59
                                  maxLength: 32
                                  readOnly: true
                                  type: string
                              required:
                                - name
                                - interval
                                - enabled
                                - data
                              type: object
                            type: array
                        type: object
          description: Delete Device DEX test response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - allOf:
                          - properties:
                              errors:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    documentation_url:
                                      type: string
                                    message:
                                      type: string
                                    source:
                                      properties:
                                        pointer:
                                          type: string
                                      type: object
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              messages:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    documentation_url:
                                      type: string
                                    message:
                                      type: string
                                    source:
                                      properties:
                                        pointer:
                                          type: string
                                      type: object
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              success:
                                description: Whether the API call was successful.
                                enum:
                                  - true
                                example: true
                                type: boolean
                            required:
                              - success
                              - errors
                              - messages
                            type: object
                          - properties:
                              result:
                                items: {}
                                nullable: true
                                type: array
                        type: object
                      - properties:
                          result:
                            items:
                              properties:
                                data:
                                  description: >-
                                    The configuration object which contains the
                                    details for the WARP client to conduct the
                                    test.
                                  example:
                                    host: https://dash.cloudflare.com
                                    kind: http
                                    method: GET
                                  properties:
                                    host:
                                      description: The desired endpoint to test.
                                      example: https://dash.cloudflare.com
                                      type: string
                                    kind:
                                      description: The type of test.
                                      example: http
                                      type: string
                                    method:
                                      description: The HTTP request method type.
                                      example: GET
                                      type: string
                                  type: object
                                description:
                                  description: Additional details about the test.
                                  example: Checks the dash endpoint every 30 minutes
                                  type: string
                                enabled:
                                  description: >-
                                    Determines whether or not the test is
                                    active.
                                  example: true
                                  type: boolean
                                interval:
                                  description: How often the test will run.
                                  example: 30m
                                  type: string
                                name:
                                  description: The name of the DEX test. Must be unique.
                                  example: HTTP dash health check
                                  type: string
                                target_policies:
                                  description: DEX rules targeted by this test
                                  items:
                                    properties:
                                      default:
                                        description: >-
                                          Whether the DEX rule is the account
                                          default
                                        type: boolean
                                      id:
                                        description: The id of the DEX rule
                                        type: string
                                      name:
                                        description: The name of the DEX rule
                                        type: string
                                    type: object
                                  type: array
                                targeted:
                                  type: boolean
                                test_id:
                                  description: The unique identifier for the test.
                                  example: 372e67954025e0ba6aaa6d586b9e0b59
                                  maxLength: 32
                                  readOnly: true
                                  type: string
                              required:
                                - name
                                - interval
                                - enabled
                                - data
                              type: object
                            type: array
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
          description: Delete DEX test response failure
      security:
        - api_email: []
          api_key: []
      summary: Delete Device DEX test
      tags:
        - Device DEX Tests
      x-api-token-group:
        - Cloudflare DEX Write
