openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/dlp/email/rules:
    get:
      description: Lists all email scanner rules for an account.
      operationId: dlp-email-scanner-list-all-rules
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                        type: object
                    type: object
                  - properties:
                      result:
                        items:
                          properties:
                            action:
                              oneOf:
                                - properties:
                                    action:
                                      enum:
                                        - Block
                                      type: string
                                    message:
                                      nullable: true
                                      type: string
                                  required:
                                    - action
                                  type: object
                            conditions:
                              description: Rule is triggered if all conditions match.
                              items:
                                properties:
                                  operator:
                                    enum:
                                      - InList
                                      - NotInList
                                      - MatchRegex
                                      - NotMatchRegex
                                    type: string
                                  selector:
                                    enum:
                                      - Recipients
                                      - Sender
                                      - DLPProfiles
                                    type: string
                                  value:
                                    oneOf:
                                      - items:
                                          type: string
                                        type: array
                                      - type: string
                                required:
                                  - selector
                                  - operator
                                  - value
                                type: object
                              type: array
                            created_at:
                              format: date-time
                              type: string
                            description:
                              nullable: true
                              type: string
                            enabled:
                              type: boolean
                            name:
                              type: string
                            priority:
                              format: int32
                              minimum: 0
                              type: integer
                            rule_id:
                              format: uuid
                              type: string
                            updated_at:
                              format: date-time
                              type: string
                          required:
                            - rule_id
                            - name
                            - priority
                            - enabled
                            - conditions
                            - action
                            - created_at
                            - updated_at
                          type: object
                        type: array
                    type: object
          description: List all email scanner rules response.
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    minLength: 1
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: List all email scanner rules failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List all email scanner rules
      tags:
        - DLP Email
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
