openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/dns_settings/views/{view_id}:
    patch:
      description: Update an existing Internal DNS View
      operationId: dns-views-for-an-account-update-internal-dns-view
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
            x-auditable: true
        - in: path
          name: view_id
          required: true
          schema:
            description: Identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
            x-auditable: true
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - properties:
                    created_time:
                      description: When the view was created.
                      example: '2014-01-01T05:20:00.12345Z'
                      format: date-time
                      readOnly: true
                      type: string
                      x-auditable: true
                    modified_time:
                      description: When the view was last modified.
                      example: '2014-01-01T05:20:00.12345Z'
                      format: date-time
                      readOnly: true
                      type: string
                      x-auditable: true
                    name:
                      description: The name of the view.
                      example: my view
                      maxLength: 255
                      minLength: 1
                      type: string
                      x-auditable: true
                    zones:
                      description: The list of zones linked to this view.
                      items:
                        description: zone id
                        example: 372e67954025e0ba6aaa6d586b9e0b59
                        maxLength: 32
                        minLength: 32
                        type: string
                        x-auditable: true
                      type: array
                  type: object
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                        type: object
                    type: object
                  - properties:
                      result:
                        allOf:
                          - properties:
                              created_time:
                                description: When the view was created.
                                example: '2014-01-01T05:20:00.12345Z'
                                format: date-time
                                readOnly: true
                                type: string
                                x-auditable: true
                              modified_time:
                                description: When the view was last modified.
                                example: '2014-01-01T05:20:00.12345Z'
                                format: date-time
                                readOnly: true
                                type: string
                                x-auditable: true
                              name:
                                description: The name of the view.
                                example: my view
                                maxLength: 255
                                minLength: 1
                                type: string
                                x-auditable: true
                              zones:
                                description: The list of zones linked to this view.
                                items:
                                  description: zone id
                                  example: 372e67954025e0ba6aaa6d586b9e0b59
                                  maxLength: 32
                                  minLength: 32
                                  type: string
                                  x-auditable: true
                                type: array
                            type: object
                          - properties:
                              id:
                                description: Identifier.
                                example: 023e105f4ecef8ad9ca31a8372d0c353
                                maxLength: 32
                                type: string
                                x-auditable: true
                            required:
                              - id
                            type: object
                        required:
                          - id
                          - name
                          - zones
                          - created_time
                          - modified_time
                        type: object
                    type: object
          description: Update Internal DNS View response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - allOf:
                          - properties:
                              errors:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    documentation_url:
                                      type: string
                                    message:
                                      type: string
                                    source:
                                      properties:
                                        pointer:
                                          type: string
                                      type: object
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              messages:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    documentation_url:
                                      type: string
                                    message:
                                      type: string
                                    source:
                                      properties:
                                        pointer:
                                          type: string
                                      type: object
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              success:
                                description: Whether the API call was successful.
                                enum:
                                  - true
                                example: true
                                type: boolean
                            required:
                              - success
                              - errors
                              - messages
                            type: object
                        type: object
                      - properties:
                          result:
                            allOf:
                              - properties:
                                  created_time:
                                    description: When the view was created.
                                    example: '2014-01-01T05:20:00.12345Z'
                                    format: date-time
                                    readOnly: true
                                    type: string
                                    x-auditable: true
                                  modified_time:
                                    description: When the view was last modified.
                                    example: '2014-01-01T05:20:00.12345Z'
                                    format: date-time
                                    readOnly: true
                                    type: string
                                    x-auditable: true
                                  name:
                                    description: The name of the view.
                                    example: my view
                                    maxLength: 255
                                    minLength: 1
                                    type: string
                                    x-auditable: true
                                  zones:
                                    description: The list of zones linked to this view.
                                    items:
                                      description: zone id
                                      example: 372e67954025e0ba6aaa6d586b9e0b59
                                      maxLength: 32
                                      minLength: 32
                                      type: string
                                      x-auditable: true
                                    type: array
                                type: object
                              - properties:
                                  id:
                                    description: Identifier.
                                    example: 023e105f4ecef8ad9ca31a8372d0c353
                                    maxLength: 32
                                    type: string
                                    x-auditable: true
                                required:
                                  - id
                                type: object
                            required:
                              - id
                              - name
                              - zones
                              - created_time
                              - modified_time
                            type: object
                        type: object
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
          description: Update Internal DNS View response failure
      security:
        - api_email: []
          api_key: []
      summary: Update Internal DNS View
      tags:
        - DNS Internal Views for an Account
      x-api-token-group:
        - DNS View Write
      x-cfPermissionsRequired:
        enum:
          - '#dns.view:update'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
