openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/workers/durable_objects/namespaces/{id}/objects:
    get:
      description: Returns the Durable Objects in a given namespace.
      operationId: durable-objects-namespace-list-objects
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
            x-auditable: true
        - in: path
          name: id
          required: true
          schema:
            description: ID of the namespace.
            example: 5fd1cafff895419c8bcc647fc64ab8f0
            type: string
        - in: query
          name: limit
          schema:
            default: 1000
            description: >-
              The number of objects to return. The cursor attribute may be used
              to iterate over the next batch of objects if there are more than
              the limit.
            maximum: 10000
            minimum: 10
            type: number
        - in: query
          name: cursor
          schema:
            description: >-
              Opaque token indicating the position from which to continue when
              requesting the next set of records. A valid value for the cursor
              can be obtained from the cursors object in the result_info
              structure.
            example: >-
              AAAAANuhDN7SjacTnSVsDu3WW1Lvst6dxJGTjRY5BhxPXdf6L6uTcpd_NVtjhn11OUYRsVEykxoUwF-JQU4dn6QylZSKTOJuG0indrdn_MlHpMRtsxgXjs-RPdHYIVm3odE_uvEQ_dTQGFm8oikZMohns34DLBgrQpc
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                        type: object
                      - properties:
                          result_info:
                            properties:
                              count:
                                description: >-
                                  Total number of results for the requested
                                  service.
                                example: 1
                                type: number
                              page:
                                description: Current page within paginated list of results.
                                example: 1
                                type: number
                              per_page:
                                description: Number of results per page of results.
                                example: 20
                                type: number
                              total_count:
                                description: >-
                                  Total results available without any search
                                  parameters.
                                example: 2000
                                type: number
                            type: object
                        type: object
                    type: object
                  - properties:
                      result:
                        items:
                          properties:
                            hasStoredData:
                              description: Whether the Durable Object has stored data.
                              example: true
                              readOnly: true
                              type: boolean
                            id:
                              description: ID of the Durable Object.
                              example: >-
                                fe7803fc55b964e09d94666545aab688d360c6bda69ba349ced1e5f28d2fc2c8
                              readOnly: true
                              type: string
                          type: object
                        type: array
                      result_info:
                        properties:
                          count:
                            description: >-
                              Total results returned based on your list
                              parameters.
                            example: 1
                            type: number
                          cursor:
                            description: >-
                              Opaque token indicating the position from which to
                              continue when requesting the next set of records.
                              A valid value for the cursor can be obtained from
                              the cursors object in the result_info structure.
                            example: >-
                              AAAAANuhDN7SjacTnSVsDu3WW1Lvst6dxJGTjRY5BhxPXdf6L6uTcpd_NVtjhn11OUYRsVEykxoUwF-JQU4dn6QylZSKTOJuG0indrdn_MlHpMRtsxgXjs-RPdHYIVm3odE_uvEQ_dTQGFm8oikZMohns34DLBgrQpc
                            type: string
                        type: object
                    type: object
          description: List Objects response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - allOf:
                          - properties:
                              errors:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    documentation_url:
                                      type: string
                                    message:
                                      type: string
                                    source:
                                      properties:
                                        pointer:
                                          type: string
                                      type: object
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              messages:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    documentation_url:
                                      type: string
                                    message:
                                      type: string
                                    source:
                                      properties:
                                        pointer:
                                          type: string
                                      type: object
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              success:
                                description: Whether the API call was successful.
                                enum:
                                  - true
                                example: true
                                type: boolean
                            required:
                              - success
                              - errors
                              - messages
                            type: object
                          - properties:
                              result_info:
                                properties:
                                  count:
                                    description: >-
                                      Total number of results for the requested
                                      service.
                                    example: 1
                                    type: number
                                  page:
                                    description: >-
                                      Current page within paginated list of
                                      results.
                                    example: 1
                                    type: number
                                  per_page:
                                    description: Number of results per page of results.
                                    example: 20
                                    type: number
                                  total_count:
                                    description: >-
                                      Total results available without any search
                                      parameters.
                                    example: 2000
                                    type: number
                                type: object
                            type: object
                        type: object
                      - properties:
                          result:
                            items:
                              properties:
                                hasStoredData:
                                  description: Whether the Durable Object has stored data.
                                  example: true
                                  readOnly: true
                                  type: boolean
                                id:
                                  description: ID of the Durable Object.
                                  example: >-
                                    fe7803fc55b964e09d94666545aab688d360c6bda69ba349ced1e5f28d2fc2c8
                                  readOnly: true
                                  type: string
                              type: object
                            type: array
                          result_info:
                            properties:
                              count:
                                description: >-
                                  Total results returned based on your list
                                  parameters.
                                example: 1
                                type: number
                              cursor:
                                description: >-
                                  Opaque token indicating the position from
                                  which to continue when requesting the next set
                                  of records. A valid value for the cursor can
                                  be obtained from the cursors object in the
                                  result_info structure.
                                example: >-
                                  AAAAANuhDN7SjacTnSVsDu3WW1Lvst6dxJGTjRY5BhxPXdf6L6uTcpd_NVtjhn11OUYRsVEykxoUwF-JQU4dn6QylZSKTOJuG0indrdn_MlHpMRtsxgXjs-RPdHYIVm3odE_uvEQ_dTQGFm8oikZMohns34DLBgrQpc
                                type: string
                            type: object
                        type: object
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
          description: List Objects response failure.
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: List Objects
      tags:
        - Durable Objects Namespace
      x-api-token-group:
        - Workers Scripts Write
        - Workers Scripts Read
