openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/email-security/settings/allow_policies/{policy_id}:
    get:
      operationId: email_security_get_allow_policy
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Account Identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            minLength: 32
            readOnly: true
            title: account_id
            type: string
        - in: path
          name: policy_id
          required: true
          schema:
            description: The unique identifier for the allow policy.
            example: 2401
            format: int32
            title: identifier
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        example: []
                        items:
                          properties:
                            code:
                              format: int32
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                        type: array
                      messages:
                        example: []
                        items:
                          properties:
                            code:
                              format: int32
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                        type: array
                      success:
                        example: true
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                    type: object
                  - properties:
                      result:
                        allOf:
                          - additionalProperties: false
                            example:
                              comments: Trust all messages send from test@example.com
                              is_acceptable_sender: false
                              is_exempt_recipient: false
                              is_recipient: false
                              is_regex: false
                              is_sender: true
                              is_spoof: false
                              is_trusted_sender: true
                              pattern: test@example.com
                              pattern_type: EMAIL
                              verify_sender: true
                            properties:
                              comments:
                                maxLength: 1024
                                nullable: true
                                type: string
                                x-auditable: true
                              is_acceptable_sender:
                                description: >-
                                  Messages from this sender will be exempted
                                  from Spam, Spoof and Bulk dispositions.

                                  Note: This will not exempt messages with
                                  Malicious or Suspicious dispositions.
                                type: boolean
                                x-auditable: true
                              is_exempt_recipient:
                                description: >-
                                  Messages to this recipient will bypass all
                                  detections.
                                type: boolean
                                x-auditable: true
                              is_recipient:
                                deprecated: true
                                type: boolean
                                x-auditable: true
                              is_regex:
                                type: boolean
                                x-auditable: true
                              is_sender:
                                deprecated: true
                                type: boolean
                                x-auditable: true
                              is_spoof:
                                deprecated: true
                                type: boolean
                                x-auditable: true
                              is_trusted_sender:
                                description: >-
                                  Messages from this sender will bypass all
                                  detections and link following.
                                type: boolean
                                x-auditable: true
                              pattern:
                                maxLength: 1024
                                minLength: 1
                                type: string
                                x-auditable: true
                              pattern_type:
                                enum:
                                  - EMAIL
                                  - DOMAIN
                                  - IP
                                  - UNKNOWN
                                type: string
                              verify_sender:
                                description: >-
                                  Enforce DMARC, SPF or DKIM authentication.

                                  When on, Email Security only honors policies
                                  that pass authentication.
                                type: boolean
                                x-auditable: true
                            required:
                              - is_exempt_recipient
                              - is_trusted_sender
                              - is_acceptable_sender
                              - pattern
                              - is_regex
                              - verify_sender
                              - pattern_type
                            type: object
                          - properties:
                              created_at:
                                format: date-time
                                type: string
                                x-auditable: true
                              id:
                                description: The unique identifier for the allow policy.
                                example: 2401
                                format: int32
                                title: identifier
                                type: integer
                              last_modified:
                                format: date-time
                                type: string
                                x-auditable: true
                            required:
                              - id
                              - created_at
                              - last_modified
                            type: object
                        example:
                          comments: Trust all messages send from test@example.com
                          created_at: '2023-11-14T22:13:20Z'
                          id: 2401
                          is_acceptable_sender: false
                          is_exempt_recipient: false
                          is_recipient: false
                          is_regex: false
                          is_sender: true
                          is_spoof: false
                          is_trusted_sender: true
                          last_modified: '2023-11-14T22:13:20Z'
                          pattern: test@example.com
                          pattern_type: EMAIL
                          verify_sender: true
                    required:
                      - result
                    type: object
          description: ''
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    example:
                      - code: 7003
                        message: No route for the URI
                    items:
                      properties:
                        code:
                          format: int32
                          minimum: 1000
                          type: integer
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  messages:
                    example: []
                    items:
                      properties:
                        code:
                          format: int32
                          minimum: 1000
                          type: integer
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  result:
                    nullable: true
                    type: object
                  success:
                    example: false
                    type: boolean
                required:
                  - result
                  - success
                  - errors
                  - messages
                type: object
          description: Client Error
      security:
        - api_email: []
          api_key: []
      summary: Get an email allow policy
      tags:
        - Email Security Settings
      x-api-token-group:
        - 'Cloud Email Security: Write'
        - 'Cloud Email Security: Read'
