openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/email/routing/rules/{rule_identifier}:
    get:
      description: Get information for a specific routing rule already created.
      operationId: email-routing-routing-rules-get-routing-rule
      parameters:
        - in: path
          name: rule_identifier
          required: true
          schema:
            description: Routing rule identifier.
            example: a7e6fb77503c41d8a7f3113c6918f10c
            maxLength: 32
            readOnly: true
            type: string
            x-auditable: true
        - in: path
          name: zone_id
          required: true
          schema:
            description: Identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
            x-auditable: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                        type: object
                    type: object
                  - properties:
                      result:
                        allOf:
                          - properties:
                              actions:
                                description: List actions patterns.
                                items:
                                  description: Actions pattern.
                                  properties:
                                    type:
                                      description: Type of supported action.
                                      enum:
                                        - drop
                                        - forward
                                        - worker
                                      example: forward
                                      type: string
                                      x-auditable: true
                                    value:
                                      items:
                                        description: Value for action.
                                        example: destinationaddress@example.net
                                        maxLength: 90
                                        type: string
                                        x-auditable: true
                                      type: array
                                  required:
                                    - type
                                  type: object
                                type: array
                              enabled:
                                default: true
                                description: Routing rule status.
                                enum:
                                  - true
                                  - false
                                example: true
                                type: boolean
                                x-auditable: true
                              id:
                                description: Routing rule identifier.
                                example: a7e6fb77503c41d8a7f3113c6918f10c
                                maxLength: 32
                                readOnly: true
                                type: string
                                x-auditable: true
                              matchers:
                                description: Matching patterns to forward to your actions.
                                items:
                                  description: Matching pattern to forward your actions.
                                  properties:
                                    field:
                                      description: Field for type matcher.
                                      enum:
                                        - to
                                      example: to
                                      type: string
                                      x-auditable: true
                                    type:
                                      description: Type of matcher.
                                      enum:
                                        - all
                                        - literal
                                      example: literal
                                      type: string
                                      x-auditable: true
                                    value:
                                      description: Value for matcher.
                                      example: test@example.com
                                      maxLength: 90
                                      type: string
                                      x-auditable: true
                                  required:
                                    - type
                                  type: object
                                type: array
                              name:
                                description: Routing rule name.
                                example: Send to user@example.net rule.
                                maxLength: 256
                                type: string
                                x-auditable: true
                              priority:
                                default: 0
                                description: Priority of the routing rule.
                                minimum: 0
                                type: number
                                x-auditable: true
                              tag:
                                deprecated: true
                                description: >-
                                  Routing rule tag. (Deprecated, replaced by
                                  routing rule identifier)
                                example: a7e6fb77503c41d8a7f3113c6918f10c
                                maxLength: 32
                                readOnly: true
                                type: string
                            type: object
                        type: object
          description: Get routing rule response
      security:
        - api_email: []
          api_key: []
      summary: Get routing rule
      tags:
        - Email Routing routing rules
      x-api-token-group:
        - Email Routing Rules Write
        - Email Routing Rules Read
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.api.account.zone.email.routing.rule.read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
