openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/email-security/settings/domains:
    get:
      description: Lists, searches, and sorts an account’s email domains.
      operationId: email_security_list_domains
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Account Identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            minLength: 32
            readOnly: true
            title: account_id
            type: string
        - description: The page number of paginated results.
          in: query
          name: page
          schema:
            default: 1
            format: int32
            minimum: 1
            type: integer
        - description: The number of results per page.
          in: query
          name: per_page
          schema:
            default: 20
            format: int32
            minimum: 1
            type: integer
        - description: The field to sort by.
          in: query
          name: order
          schema:
            enum:
              - domain
              - created_at
            type: string
        - description: The sorting direction.
          in: query
          name: direction
          schema:
            allOf:
              - enum:
                  - asc
                  - desc
                type: string
        - description: >-
            Allows searching in multiple properties of a record simultaneously.

            This parameter is intended for human users, not automation. Its
            exact

            behavior is intentionally left unspecified and is subject to change

            in the future.
          in: query
          name: search
          schema:
            type: string
        - description: Filters response to domains with the provided delivery mode.
          in: query
          name: allowed_delivery_mode
          schema:
            allOf:
              - enum:
                  - DIRECT
                  - BCC
                  - JOURNAL
                  - API
                  - RETRO_SCAN
                type: string
        - description: >-
            Filters results by the provided domains, allowing for multiple
            occurrences.
          example: domain=example.com&domain=example.xyz
          in: query
          name: domain
          schema:
            items:
              type: string
            type: array
        - description: Filters response to domains with the currently active delivery mode.
          in: query
          name: active_delivery_mode
          schema:
            allOf:
              - enum:
                  - DIRECT
                  - BCC
                  - JOURNAL
                  - API
                  - RETRO_SCAN
                type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        example: []
                        items:
                          properties:
                            code:
                              format: int32
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                        type: array
                      messages:
                        example: []
                        items:
                          properties:
                            code:
                              format: int32
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                        type: array
                      success:
                        example: true
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                    type: object
                  - properties:
                      result:
                        items:
                          example:
                            allowed_delivery_modes:
                              - API
                            authorization: null
                            created_at: '2023-11-14T22:13:20Z'
                            domain: example.com
                            drop_dispositions:
                              - MALICIOUS
                              - SPAM
                            emails_processed: null
                            folder: Inbox
                            id: 2400
                            inbox_provider: Microsoft
                            integration_id: a5dbb180-60ea-4578-84bb-d01a5d4e50c3
                            ip_restrictions: []
                            last_modified: '2023-11-14T22:13:20Z'
                            lookback_hops: 2
                            o365_tenant_id: c3c3239d-8858-47df-9618-0e2d9bdf6aa8
                            require_tls_inbound: false
                            require_tls_outbound: true
                            transport: example.com
                          properties:
                            allowed_delivery_modes:
                              items:
                                enum:
                                  - DIRECT
                                  - BCC
                                  - JOURNAL
                                  - API
                                  - RETRO_SCAN
                                type: string
                              type: array
                            authorization:
                              allOf:
                                - properties:
                                    authorized:
                                      type: boolean
                                    status_message:
                                      nullable: true
                                      type: string
                                    timestamp:
                                      format: date-time
                                      type: string
                                  required:
                                    - authorized
                                    - timestamp
                                  type: object
                                - nullable: true
                                  type: object
                            created_at:
                              format: date-time
                              type: string
                            domain:
                              type: string
                            drop_dispositions:
                              items:
                                enum:
                                  - MALICIOUS
                                  - MALICIOUS-BEC
                                  - SUSPICIOUS
                                  - SPOOF
                                  - SPAM
                                  - BULK
                                  - ENCRYPTED
                                  - EXTERNAL
                                  - UNKNOWN
                                  - NONE
                                type: string
                              type: array
                            emails_processed:
                              allOf:
                                - properties:
                                    timestamp:
                                      format: date-time
                                      type: string
                                    total_emails_processed:
                                      format: int32
                                      minimum: 0
                                      type: integer
                                    total_emails_processed_previous:
                                      format: int32
                                      minimum: 0
                                      type: integer
                                  required:
                                    - total_emails_processed
                                    - total_emails_processed_previous
                                    - timestamp
                                  type: object
                                - nullable: true
                                  type: object
                            folder:
                              allOf:
                                - enum:
                                    - AllItems
                                    - Inbox
                                  type: string
                                - nullable: true
                                  type: string
                            id:
                              description: The unique identifier for the domain.
                              example: 2400
                              format: int32
                              type: integer
                            inbox_provider:
                              allOf:
                                - enum:
                                    - Microsoft
                                    - Google
                                  type: string
                                - nullable: true
                                  type: string
                            integration_id:
                              format: uuid
                              nullable: true
                              type: string
                            ip_restrictions:
                              example:
                                - 192.0.2.0/24
                                - 2001:db8::/32
                              items:
                                type: string
                              type: array
                            last_modified:
                              format: date-time
                              type: string
                            lookback_hops:
                              format: int32
                              type: integer
                            o365_tenant_id:
                              nullable: true
                              type: string
                            require_tls_inbound:
                              nullable: true
                              type: boolean
                            require_tls_outbound:
                              nullable: true
                              type: boolean
                            transport:
                              type: string
                          required:
                            - id
                            - created_at
                            - last_modified
                            - domain
                            - allowed_delivery_modes
                            - lookback_hops
                            - ip_restrictions
                            - transport
                            - drop_dispositions
                          type: object
                        type: array
                      result_info:
                        properties:
                          count:
                            description: Total number of results for the requested service
                            example: 1
                            format: int32
                            type: integer
                          page:
                            description: Current page within paginated list of results
                            example: 1
                            format: int32
                            type: integer
                          per_page:
                            description: Number of results per page of results
                            example: 20
                            format: int32
                            type: integer
                          total_count:
                            description: >-
                              Total results available without any search
                              parameters
                            example: 2000
                            format: int32
                            type: integer
                        required:
                          - count
                          - page
                          - per_page
                          - total_count
                        type: object
                    required:
                      - result
                      - result_info
                    type: object
          description: Contains a list of domains for the account.
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    example:
                      - code: 7003
                        message: No route for the URI
                    items:
                      properties:
                        code:
                          format: int32
                          minimum: 1000
                          type: integer
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  messages:
                    example: []
                    items:
                      properties:
                        code:
                          format: int32
                          minimum: 1000
                          type: integer
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  result:
                    nullable: true
                    type: object
                  success:
                    example: false
                    type: boolean
                required:
                  - result
                  - success
                  - errors
                  - messages
                type: object
          description: Client Error
      security:
        - api_email: []
          api_key: []
      summary: List protected email domains
      tags:
        - Email Security Settings
      x-api-token-group:
        - 'Cloud Email Security: Write'
        - 'Cloud Email Security: Read'
