openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/email/routing/addresses/{destination_address_identifier}:
    get:
      description: Gets information for a specific destination email already created.
      operationId: email-routing-destination-addresses-get-a-destination-address
      parameters:
        - in: path
          name: destination_address_identifier
          required: true
          schema:
            description: Destination address identifier.
            example: ea95132c15732412d22c1476fa83f27a
            maxLength: 32
            readOnly: true
            type: string
            x-auditable: true
        - in: path
          name: account_id
          required: true
          schema:
            description: Identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
            x-auditable: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                        type: object
                    type: object
                  - properties:
                      result:
                        allOf:
                          - properties:
                              created:
                                description: >-
                                  The date and time the destination address has
                                  been created.
                                example: '2014-01-02T02:20:00Z'
                                format: date-time
                                readOnly: true
                                type: string
                              email:
                                description: The contact email address of the user.
                                example: user@example.com
                                maxLength: 90
                                type: string
                                x-auditable: true
                              id:
                                description: Destination address identifier.
                                example: ea95132c15732412d22c1476fa83f27a
                                maxLength: 32
                                readOnly: true
                                type: string
                                x-auditable: true
                              modified:
                                description: >-
                                  The date and time the destination address was
                                  last modified.
                                example: '2014-01-02T02:20:00Z'
                                format: date-time
                                readOnly: true
                                type: string
                              tag:
                                deprecated: true
                                description: >-
                                  Destination address tag. (Deprecated, replaced
                                  by destination address identifier)
                                example: ea95132c15732412d22c1476fa83f27a
                                maxLength: 32
                                readOnly: true
                                type: string
                              verified:
                                description: >-
                                  The date and time the destination address has
                                  been verified. Null means not verified yet.
                                example: '2014-01-02T02:20:00Z'
                                format: date-time
                                readOnly: true
                                type: string
                            type: object
                        type: object
          description: Get a destination address response
      security:
        - api_email: []
          api_key: []
      summary: Get a destination address
      tags:
        - Email Routing destination addresses
      x-api-token-group:
        - Email Routing Addresses Write
        - Email Routing Addresses Read
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.api.account.email.routing.address.read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
