openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/settings/zaraz/history:
    get:
      description: Lists a history of published Zaraz configuration records for a zone.
      operationId: get-zones-zone_identifier-zaraz-history
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            description: Identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
            x-auditable: true
        - description: >-
            Ordinal number to start listing the results with. Default value is
            0.
          example: 0
          in: query
          name: offset
          schema:
            minimum: 0
            type: integer
        - description: Maximum amount of results to list. Default value is 10.
          example: 10
          in: query
          name: limit
          schema:
            minimum: 1
            type: integer
        - description: The field to sort by. Default is updated_at.
          example: updated_at
          in: query
          name: sortField
          schema:
            enum:
              - id
              - user_id
              - description
              - created_at
              - updated_at
            type: string
        - description: Sorting order. Default is DESC.
          example: DESC
          in: query
          name: sortOrder
          schema:
            enum:
              - DESC
              - ASC
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      messages:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      success:
                        description: Whether the API call was successful
                        example: true
                        type: boolean
                        x-auditable: true
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
                  - properties:
                      result:
                        items:
                          allOf:
                            - properties:
                                createdAt:
                                  description: Date and time the configuration was created
                                  format: date-time
                                  type: string
                                  x-auditable: true
                                id:
                                  description: ID of the configuration
                                  type: integer
                                  x-auditable: true
                                updatedAt:
                                  description: >-
                                    Date and time the configuration was last
                                    updated
                                  format: date-time
                                  type: string
                                  x-auditable: true
                                userId:
                                  description: >-
                                    Alpha-numeric ID of the account user who
                                    published the configuration
                                  type: string
                                  x-auditable: true
                              required:
                                - id
                                - createdAt
                                - updatedAt
                                - userId
                            - example:
                                createdAt: '2023-02-23T05:05:55.155273Z'
                                description: Config with enabled ecommerce tracking
                                id: 12345
                                updatedAt: '2023-02-23T05:05:55.155273Z'
                                userId: 278d0d0g123cd8e49d45ea64f12faa37
                              properties:
                                description:
                                  description: >-
                                    Configuration description provided by the
                                    user who published this configuration
                                  type: string
                              required:
                                - description
                              type: object
                        type: array
          description: List Zaraz historical configuration records response
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    minLength: 1
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: List Zaraz historical configuration records failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: List Zaraz historical configuration records
      tags:
        - Zaraz
      x-api-token-group:
        - Zaraz Edit
        - Zaraz Read
        - Zaraz Admin
