openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/cni/interconnects/{icon}:
    get:
      operationId: get_interconnect
      parameters:
        - description: Interconnect name to retrieve information about
          in: path
          name: icon
          required: true
          schema:
            type: string
        - in: path
          name: account_id
          required: true
          schema:
            description: Customer account tag
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                discriminator:
                  mapping:
                    direct: '#/components/schemas/nsc_Interconnect_Physical_Body'
                    gcp_partner: '#/components/schemas/nsc_Interconnect_GcpPartner_Body'
                  propertyName: type
                oneOf:
                  - allOf:
                      - properties:
                          account:
                            type: string
                          name:
                            type: string
                          owner:
                            type: string
                          type:
                            type: string
                        required:
                          - type
                          - name
                          - account
                        type: object
                      - properties:
                          facility:
                            properties:
                              address:
                                items:
                                  type: string
                                type: array
                              name:
                                type: string
                            required:
                              - name
                              - address
                            type: object
                          site:
                            description: A Cloudflare site name.
                            type: string
                          slot_id:
                            format: uuid
                            type: string
                          speed:
                            type: string
                        required:
                          - slot_id
                          - site
                          - speed
                          - facility
                        type: object
                    title: Physical
                    type: object
                  - allOf:
                      - properties:
                          account:
                            type: string
                          name:
                            type: string
                          owner:
                            type: string
                          type:
                            type: string
                        required:
                          - type
                          - name
                          - account
                        type: object
                      - properties:
                          region:
                            type: string
                          speed:
                            description: >-
                              Bandwidth structure as visible through the
                              customer-facing API.
                            enum:
                              - 50M
                              - 100M
                              - 200M
                              - 300M
                              - 400M
                              - 500M
                              - 1G
                              - 2G
                              - 5G
                              - 10G
                              - 20G
                              - 50G
                            type: string
                        required:
                          - region
                        type: object
                    title: GcpPartner
                    type: object
                type: object
          description: Information about the specified interconnect
        '400':
          description: Bad request
        '404':
          description: Interconnect not found
        '500':
          description: Internal server error
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get information about an interconnect object
      tags:
        - Interconnects
      x-api-token-group:
        - Magic WAN Write
        - Magic WAN Read
        - Magic Transit Read
        - Magic Transit Write
