openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/devices/registrations/{registration_id}:
    get:
      description: Fetches a single WARP registration.
      operationId: get-registration
      parameters:
        - in: path
          name: registration_id
          required: true
          schema:
            type: string
        - in: path
          name: account_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      description: >-
                        A message which can be returned in either the 'errors'
                        or 'messages' fields in a v4 API response.
                      properties:
                        code:
                          type: integer
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  messages:
                    items:
                      description: >-
                        A message which can be returned in either the 'errors'
                        or 'messages' fields in a v4 API response.
                      properties:
                        code:
                          type: integer
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  result:
                    description: >-
                      A WARP configuration tied to a single user. Multiple
                      registrations can be created from a single WARP device.
                    properties:
                      created_at:
                        description: >-
                          The RFC3339 timestamp when the registration was
                          created.
                        example: '2025-02-14T13:17:00Z'
                        type: string
                        x-auditable: true
                      deleted_at:
                        description: >-
                          The RFC3339 timestamp when the registration was
                          deleted.
                        example: '2025-02-14T13:17:00Z'
                        nullable: true
                        type: string
                        x-auditable: true
                      device:
                        description: Device details embedded inside of a registration.
                        properties:
                          client_version:
                            description: Version of the WARP client.
                            example: 1.0.0
                            type: string
                            x-auditable: true
                          id:
                            description: The ID of the device.
                            example: 32aa0404-78f1-49a4-99e0-97f575081356
                            type: string
                            x-auditable: true
                          name:
                            description: The name of the device.
                            example: My Device
                            type: string
                            x-auditable: true
                        required:
                          - id
                          - name
                        type: object
                      id:
                        description: The ID of the registration.
                        example: 11ffb86f-3f0c-4306-b4a2-e62f872b166a
                        type: string
                        x-auditable: true
                      key:
                        description: >-
                          The public key used to connect to the Cloudflare
                          network.
                        example: >-
                          U+QTP50RsWfeLGHF4tlGDnmGeuwtsz46KCHr5OyhWq00Rsdfl45mgnQAuEJ6CO0YrkyTl9FUf5iB0bwYR3g4EEFEHhtu6jFaqfMrBMBSz6itv9HQXkaR9OieKQ==
                        type: string
                        x-auditable: true
                      key_type:
                        description: >-
                          The type of encryption key used by the WARP client for
                          the active key. Currently 'curve25519' for WireGuard
                          and 'secp256r1' for MASQUE.
                        example: secp256r1
                        nullable: true
                        type: string
                        x-auditable: true
                      last_seen_at:
                        description: >-
                          The RFC3339 timestamp when the registration was last
                          seen.
                        example: '2025-02-14T13:17:00Z'
                        type: string
                        x-auditable: true
                      revoked_at:
                        description: >-
                          The RFC3339 timestamp when the registration was
                          revoked.
                        example: '2025-02-14T13:17:00Z'
                        nullable: true
                        type: string
                        x-auditable: true
                      tunnel_type:
                        description: Type of the tunnel - wireguard or masque.
                        example: masque
                        nullable: true
                        type: string
                        x-auditable: true
                      updated_at:
                        description: >-
                          The RFC3339 timestamp when the registration was last
                          updated.
                        example: '2025-02-14T13:17:00Z'
                        type: string
                        x-auditable: true
                      user:
                        properties:
                          email:
                            description: The contact email address of the user.
                            example: user@example.com
                            maxLength: 90
                            type: string
                            x-auditable: true
                          id:
                            description: UUID.
                            example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
                            maxLength: 36
                            readOnly: true
                            type: string
                            x-auditable: true
                          name:
                            description: The enrolled device user's name.
                            example: John Appleseed
                            type: string
                        type: object
                    required:
                      - id
                      - key
                      - device
                      - created_at
                      - updated_at
                      - last_seen_at
                    type: object
                  success:
                    description: Whether the API call was successful.
                    type: boolean
                required:
                  - result
                  - success
                  - errors
                  - messages
                type: object
          description: Returns a Registration.
      security:
        - api_token: []
      summary: Get registration
      tags:
        - Registrations
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
