openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/dex/commands/{command_id}/downloads/{filename}:
    get:
      description: >-
        Downloads artifacts for an executed command. Bulk downloads are not
        supported
      operationId: get-commands-command-id-downloads-filename
      parameters:
        - description: unique identifier linked to an account in the API request path
          in: path
          name: account_id
          required: true
          schema:
            example: 01a7362d577a6c3019a474fd6f485823
            maxLength: 32
            readOnly: true
            type: string
        - description: Unique identifier for command
          in: path
          name: command_id
          required: true
          schema:
            description: Unique identifier for a command
            example: 5758fefe-ae7e-4538-a39b-1fef6abcb909
            type: string
        - description: >-
            The name of the file to be downloaded, including the `.zip`
            extension
          in: path
          name: filename
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/zip:
              schema:
                format: binary
                type: string
          description: Get command artifacts response
          headers:
            Accept-Ranges:
              description: Indicates that the file supports byte-range requests
              schema:
                example: bytes
                type: string
            Content-Disposition:
              description: >-
                Indicates that the file should be treated as an attachment for
                downloading
              schema:
                example: attachment; filename*=example.zip
                type: string
            Content-Encoding:
              description: Specifies the encoding of the file content, if any
              schema:
                example: gzip
                type: string
            Content-Length:
              description: The size of the file in bytes
              schema:
                type: integer
            Content-Type:
              description: Specifies the media type of the file
              schema:
                example: application/zip
                type: string
            ETag:
              description: The entity tag of the file for cache validation
              schema:
                example: 34f9b5e9c8a6
                type: string
            Last-Modified:
              description: The last modification date of the file
              schema:
                example: Wed, 21 Oct 2023 07:28:00 GMT
                format: date-time
                type: string
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    minLength: 1
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: Get downloaded commands failure response
      security:
        - api_email: []
          api_key: []
        - api_token: []
        - user_service_key: []
      summary: Download command output file
      tags:
        - DEX Remote Commands
      x-api-token-group:
        - Cloudflare DEX Write
        - Cloudflare DEX Read
        - Zero Trust Report
        - Zero Trust Read
