openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/security-center/insights:
    get:
      operationId: get-security-center-insights
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
            x-auditable: true
        - in: query
          name: dismissed
          schema:
            example: false
            type: boolean
            x-auditable: true
        - in: query
          name: issue_class
          schema:
            example:
              - a_record_dangling
              - always_use_https_not_enabled
            items:
              example: always_use_https_not_enabled
              type: string
              x-auditable: true
            type: array
        - in: query
          name: issue_type
          schema:
            example:
              - compliance_violation
              - email_security
            items:
              enum:
                - compliance_violation
                - email_security
                - exposed_infrastructure
                - insecure_configuration
                - weak_authentication
              type: string
              x-auditable: true
            type: array
        - in: query
          name: product
          schema:
            example:
              - access
              - dns
            items:
              type: string
              x-auditable: true
            type: array
        - in: query
          name: severity
          schema:
            example:
              - low
              - moderate
            items:
              enum:
                - low
                - moderate
                - critical
              type: string
              x-auditable: true
            type: array
        - in: query
          name: subject
          schema:
            items:
              example: example.com
              type: string
              x-auditable: true
            type: array
        - in: query
          name: issue_class~neq
          schema:
            example:
              - a_record_dangling
              - always_use_https_not_enabled
            items:
              example: always_use_https_not_enabled
              type: string
              x-auditable: true
            type: array
        - in: query
          name: issue_type~neq
          schema:
            example:
              - compliance_violation
              - email_security
            items:
              enum:
                - compliance_violation
                - email_security
                - exposed_infrastructure
                - insecure_configuration
                - weak_authentication
              type: string
              x-auditable: true
            type: array
        - in: query
          name: product~neq
          schema:
            example:
              - access
              - dns
            items:
              type: string
              x-auditable: true
            type: array
        - in: query
          name: severity~neq
          schema:
            example:
              - low
              - moderate
            items:
              enum:
                - low
                - moderate
                - critical
              type: string
              x-auditable: true
            type: array
        - in: query
          name: subject~neq
          schema:
            items:
              example: example.com
              type: string
              x-auditable: true
            type: array
        - in: query
          name: page
          schema:
            allOf:
              - description: Current page within paginated list of results
                example: 1
                type: integer
            default: 1
        - in: query
          name: per_page
          schema:
            allOf:
              - description: Number of results per page of results
                example: 25
                maximum: 1000
                minimum: 1
                type: integer
            default: 25
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      messages:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - true
                        example: true
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                    type: object
                  - properties:
                      result:
                        anyOf:
                          - properties:
                              count:
                                description: Total number of results
                                example: 1
                                type: integer
                                x-auditable: true
                              issues:
                                items:
                                  properties:
                                    dismissed:
                                      example: false
                                      type: boolean
                                      x-auditable: true
                                    id:
                                      type: string
                                      x-auditable: true
                                    issue_class:
                                      example: always_use_https_not_enabled
                                      type: string
                                      x-auditable: true
                                    issue_type:
                                      enum:
                                        - compliance_violation
                                        - email_security
                                        - exposed_infrastructure
                                        - insecure_configuration
                                        - weak_authentication
                                      type: string
                                      x-auditable: true
                                    payload:
                                      type: object
                                    resolve_link:
                                      type: string
                                      x-auditable: true
                                    resolve_text:
                                      type: string
                                      x-auditable: true
                                    severity:
                                      enum:
                                        - Low
                                        - Moderate
                                        - Critical
                                      type: string
                                      x-auditable: true
                                    since:
                                      format: date-time
                                      type: string
                                      x-auditable: true
                                    subject:
                                      example: example.com
                                      type: string
                                      x-auditable: true
                                    timestamp:
                                      format: date-time
                                      type: string
                                      x-auditable: true
                                  type: object
                                type: array
                              page:
                                description: Current page within paginated list of results
                                example: 1
                                type: integer
                              per_page:
                                description: Number of results per page of results
                                example: 25
                                maximum: 1000
                                minimum: 1
                                type: integer
                            type: object
          description: OK
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    minLength: 1
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: Client Error
      security:
        - api_email: []
          api_key: []
        - api_token: []
      summary: Get Security Center Insights
      tags:
        - Security Center Insights
