openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/pipelines/{pipeline_name}:
    get:
      description: Get configuration of a pipeline.
      operationId: getV4AccountsByAccount_idPipelinesByPipeline_name
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Specifies the public ID of the account.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            type: string
        - in: path
          name: pipeline_name
          required: true
          schema:
            description: Defines the name of the pipeline.
            example: sample_pipeline
            maxLength: 128
            minLength: 1
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  result:
                    description: Describes the configuration of a pipeline.
                    properties:
                      destination:
                        properties:
                          batch:
                            properties:
                              max_bytes:
                                default: 100000000
                                description: Specifies rough maximum size of files.
                                maximum: 100000000
                                minimum: 1000
                                type: integer
                              max_duration_s:
                                default: 300
                                description: >-
                                  Specifies duration to wait to aggregate
                                  batches files.
                                maximum: 300
                                minimum: 0.25
                                type: number
                              max_rows:
                                default: 10000000
                                description: >-
                                  Specifies rough maximum number of rows per
                                  file.
                                maximum: 10000000
                                minimum: 100
                                type: integer
                            required:
                              - max_rows
                              - max_bytes
                              - max_duration_s
                            type: object
                          compression:
                            properties:
                              type:
                                default: gzip
                                description: >-
                                  Specifies the desired compression algorithm
                                  and format.
                                enum:
                                  - none
                                  - gzip
                                  - deflate
                                example: gzip
                                type: string
                            required:
                              - type
                            type: object
                          format:
                            description: Specifies the format of data to deliver.
                            enum:
                              - json
                            type: string
                          path:
                            example:
                              bucket: bucket
                              prefix: base
                            properties:
                              bucket:
                                description: Specifies the R2 Bucket to store files.
                                example: bucket
                                type: string
                              filename:
                                allOf:
                                  - type: string
                                  - type: string
                                description: >-
                                  Specifies the name pattern to for individual
                                  data files.
                                example: ${slug}${extension}
                              filepath:
                                description: Specifies the name pattern for directory.
                                example: ${date}/${hour}
                                type: string
                              prefix:
                                description: >-
                                  Specifies the base directory within the
                                  bucket.
                                example: base
                                type: string
                            required:
                              - bucket
                            type: object
                          type:
                            description: Specifies the type of destination.
                            enum:
                              - r2
                            type: string
                        required:
                          - type
                          - format
                          - batch
                          - compression
                          - path
                        type: object
                      endpoint:
                        description: Indicates the endpoint URL to send traffic.
                        example: >-
                          https://123f8a8258064ed892a347f173372359.pipelines.cloudflare.com
                        type: string
                      id:
                        description: Specifies the pipeline identifier.
                        example: 123f8a8258064ed892a347f173372359
                        type: string
                      name:
                        description: Defines the name of the pipeline.
                        example: sample_pipeline
                        maxLength: 128
                        minLength: 1
                        type: string
                      source:
                        items:
                          discriminator:
                            mapping:
                              binding: >-
                                #/components/schemas/cloudflare-pipelines_workers_pipelines_binding_source
                              http: >-
                                #/components/schemas/cloudflare-pipelines_workers_pipelines_http_source
                            propertyName: type
                          oneOf:
                            - properties:
                                authentication:
                                  description: >-
                                    Specifies whether authentication is required
                                    to send to this pipeline via HTTP.
                                  type: boolean
                                cors:
                                  properties:
                                    origins:
                                      description: >-
                                        Specifies allowed origins to allow Cross
                                        Origin HTTP Requests.
                                      example:
                                        - '*'
                                      items:
                                        anyOf:
                                          - type: string
                                          - type: string
                                      maxItems: 5
                                      type: array
                                  type: object
                                format:
                                  description: Specifies the format of source data.
                                  enum:
                                    - json
                                  type: string
                                type:
                                  type: string
                              required:
                                - type
                                - format
                              type: object
                            - properties:
                                format:
                                  description: Specifies the format of source data.
                                  enum:
                                    - json
                                  type: string
                                type:
                                  type: string
                              required:
                                - type
                                - format
                              type: object
                        minItems: 1
                        type: array
                      version:
                        description: >-
                          Indicates the version number of last saved
                          configuration.
                        example: 2
                        type: number
                    required:
                      - name
                      - source
                      - destination
                      - id
                      - version
                      - endpoint
                    type: object
                  success:
                    description: Indicates whether the API call was successful.
                    example: true
                    type: boolean
                required:
                  - success
                  - result
                type: object
          description: Describes the configuration of a pipeline.
        '404':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    example: []
                    items:
                      properties:
                        code:
                          type: number
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  results:
                    nullable: true
                    type: object
                    x-stainless-empty-object: true
                  success:
                    allOf:
                      - description: Indicates whether the API call was successful.
                        example: true
                        type: boolean
                    example: false
                required:
                  - success
                  - results
                  - errors
                type: object
          description: Indicates that the pipeline was not found.
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get Pipeline
      tags:
        - workers_pipelines_other
      x-api-token-group:
        - Pipelines Write
        - Pipelines Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: true
