openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/infrastructure/targets:
    post:
      operationId: infra-targets-post
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Account identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            title: account_id
            type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                hostname:
                  description: >-
                    A non-unique field that refers to a target. Case
                    insensitive, maximum

                    length of 255 characters, supports the use of special
                    characters dash

                    and period, does not support spaces, and must start and end
                    with an

                    alphanumeric character.
                  example: infra-access-target
                  type: string
                ip:
                  description: >-
                    The IPv4/IPv6 address that identifies where to reach a
                    target
                  properties:
                    ipv4:
                      description: The target's IPv4 address
                      properties:
                        ip_addr:
                          description: IP address of the target
                          example: 187.26.29.249
                          type: string
                        virtual_network_id:
                          description: >-
                            (optional) Private virtual network identifier for
                            the target. If omitted, the default virtual network
                            ID will be used.
                          example: c77b744e-acc8-428f-9257-6878c046ed55
                          format: uuid
                          type: string
                      type: object
                    ipv6:
                      description: The target's IPv6 address
                      properties:
                        ip_addr:
                          description: IP address of the target
                          example: 64c0:64e8:f0b4:8dbf:7104:72b0:ec8f:f5e0
                          type: string
                        virtual_network_id:
                          description: >-
                            (optional) Private virtual network identifier for
                            the target. If omitted, the default virtual network
                            ID will be used.
                          example: c77b744e-acc8-428f-9257-6878c046ed55
                          format: uuid
                          type: string
                      type: object
                  type: object
              required:
                - hostname
                - ip
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                        type: object
                    type: object
                  - properties:
                      result:
                        properties:
                          created_at:
                            description: Date and time at which the target was created
                            example: '2019-08-24T14:15:22Z'
                            format: date-time
                            type: string
                          hostname:
                            description: A non-unique field that refers to a target
                            example: infra-access-target
                            type: string
                          id:
                            description: Target identifier
                            example: 0191dce4-9ab4-7fce-b660-8e5dec5172da
                            format: uuid
                            maxLength: 36
                            title: target_id
                            type: string
                          ip:
                            description: >-
                              The IPv4/IPv6 address that identifies where to
                              reach a target
                            properties:
                              ipv4:
                                description: The target's IPv4 address
                                properties:
                                  ip_addr:
                                    description: IP address of the target
                                    example: 187.26.29.249
                                    type: string
                                  virtual_network_id:
                                    description: >-
                                      (optional) Private virtual network
                                      identifier for the target. If omitted, the
                                      default virtual network ID will be used.
                                    example: c77b744e-acc8-428f-9257-6878c046ed55
                                    format: uuid
                                    type: string
                                type: object
                              ipv6:
                                description: The target's IPv6 address
                                properties:
                                  ip_addr:
                                    description: IP address of the target
                                    example: 64c0:64e8:f0b4:8dbf:7104:72b0:ec8f:f5e0
                                    type: string
                                  virtual_network_id:
                                    description: >-
                                      (optional) Private virtual network
                                      identifier for the target. If omitted, the
                                      default virtual network ID will be used.
                                    example: c77b744e-acc8-428f-9257-6878c046ed55
                                    format: uuid
                                    type: string
                                type: object
                            type: object
                          modified_at:
                            description: Date and time at which the target was modified
                            example: '2019-08-24T14:15:22Z'
                            format: date-time
                            type: string
                        required:
                          - id
                          - hostname
                          - ip
                          - created_at
                          - modified_at
                        type: object
                    type: object
          description: Successfully created the target
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    minLength: 1
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: Failed to create the target
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create new target
      tags:
        - Infrastructure Access Targets
      x-api-token-group:
        - Zero Trust Write
