openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/addressing/prefixes/{prefix_id}/bindings:
    post:
      description: >
        Creates a new Service Binding, routing traffic to IPs within the given
        CIDR to a service running on Cloudflare's network.

        **Note:** This API may only be used on prefixes currently configured
        with a Magic Transit/Cloudflare CDN/Cloudflare Spectrum service binding,
        and only allows creating upgrade service bindings for the Cloudflare CDN
        or Cloudflare Spectrum.
      operationId: ip-address-management-service-bindings-create-service-binding
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Identifier of a Cloudflare account.
            example: 258def64c72dae45f3e4c8516e2111f2
            maxLength: 32
            type: string
            x-auditable: true
        - in: path
          name: prefix_id
          required: true
          schema:
            description: Identifier of an IP Prefix.
            example: 2af39739cc4e3b5910c918468bb89828
            maxLength: 32
            type: string
            x-auditable: true
      requestBody:
        content:
          application/json:
            schema:
              properties:
                cidr:
                  description: IP Prefix in Classless Inter-Domain Routing format.
                  example: 192.0.2.0/24
                  type: string
                  x-auditable: true
                service_id:
                  description: >
                    Identifier of a Service on the Cloudflare network. Available
                    services and their IDs may be found in the

                    **List Services** endpoint.
                  example: 2db684ee7ca04e159946fd05b99e1bcd
                  maxLength: 32
                  type: string
                  x-auditable: true
              type: object
      responses:
        '201':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      messages:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - true
                        example: true
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                    type: object
                  - properties:
                      result:
                        properties:
                          cidr:
                            description: >-
                              IP Prefix in Classless Inter-Domain Routing
                              format.
                            example: 192.0.2.0/24
                            type: string
                            x-auditable: true
                          id:
                            description: Identifier of a Service Binding.
                            example: 0429b49b6a5155297b78e75a44b09e14
                            maxLength: 32
                            type: string
                            x-auditable: true
                          provisioning:
                            description: >-
                              Status of a Service Binding's deployment to the
                              Cloudflare network
                            properties:
                              state:
                                description: >
                                  When a binding has been deployed to a majority
                                  of Cloudflare datacenters, the binding will
                                  become active and can be used with its
                                  associated service.
                                enum:
                                  - provisioning
                                  - active
                                example: provisioning
                                type: string
                                x-auditable: true
                            type: object
                          service_id:
                            description: >
                              Identifier of a Service on the Cloudflare network.
                              Available services and their IDs may be found in
                              the

                              **List Services** endpoint.
                            example: 2db684ee7ca04e159946fd05b99e1bcd
                            maxLength: 32
                            type: string
                            x-auditable: true
                          service_name:
                            description: >-
                              Name of a service running on the Cloudflare
                              network
                            example: Magic Transit
                            type: string
                            x-auditable: true
                        type: object
          description: The created Service Binding
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    minLength: 1
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: Create Service Binding response failure
      security:
        - api_email: []
          api_key: []
      summary: Create Service Binding
      tags:
        - IP Address Management Service Bindings
      x-api-token-group:
        - 'IP Prefixes: Write'
