openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/addressing/loa_documents:
    post:
      description: Submit LOA document (pdf format) under the account.
      operationId: ip-address-management-prefixes-upload-loa-document
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Identifier of a Cloudflare account.
            example: 258def64c72dae45f3e4c8516e2111f2
            maxLength: 32
            type: string
            x-auditable: true
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                loa_document:
                  description: LOA document to upload.
                  example: '@document.pdf'
                  type: string
              required:
                - loa_document
              type: object
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                        type: object
                    type: object
                  - properties:
                      result:
                        properties:
                          account_id:
                            description: Identifier of a Cloudflare account.
                            example: 258def64c72dae45f3e4c8516e2111f2
                            maxLength: 32
                            type: string
                            x-auditable: true
                          created:
                            example: '2014-01-01T05:20:00.12345Z'
                            format: date-time
                            type: string
                            x-auditable: true
                          filename:
                            description: >-
                              Name of LOA document. Max file size 10MB, and
                              supported filetype is pdf.
                            example: site_loa_doc.pdf
                            type: string
                            x-auditable: true
                          id:
                            description: Identifier for the uploaded LOA document.
                            example: d933b1530bc56c9953cf8ce166da8004
                            maxLength: 32
                            nullable: true
                            type: string
                            x-auditable: true
                          size_bytes:
                            description: File size of the uploaded LOA document.
                            example: 444
                            type: integer
                            x-auditable: true
                          verified:
                            description: >-
                              Whether the LOA has been verified by Cloudflare
                              staff.
                            example: true
                            type: boolean
                            x-auditable: true
                          verified_at:
                            description: >-
                              Timestamp of the moment the LOA was marked as
                              validated.
                            format: date-time
                            nullable: true
                            type: string
                            x-auditable: true
                        type: object
          description: Upload LOA Document response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - allOf:
                          - properties:
                              errors:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    documentation_url:
                                      type: string
                                    message:
                                      type: string
                                    source:
                                      properties:
                                        pointer:
                                          type: string
                                      type: object
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              messages:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    documentation_url:
                                      type: string
                                    message:
                                      type: string
                                    source:
                                      properties:
                                        pointer:
                                          type: string
                                      type: object
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              success:
                                description: Whether the API call was successful.
                                enum:
                                  - true
                                example: true
                                type: boolean
                            required:
                              - success
                              - errors
                              - messages
                            type: object
                        type: object
                      - properties:
                          result:
                            properties:
                              account_id:
                                description: Identifier of a Cloudflare account.
                                example: 258def64c72dae45f3e4c8516e2111f2
                                maxLength: 32
                                type: string
                                x-auditable: true
                              created:
                                example: '2014-01-01T05:20:00.12345Z'
                                format: date-time
                                type: string
                                x-auditable: true
                              filename:
                                description: >-
                                  Name of LOA document. Max file size 10MB, and
                                  supported filetype is pdf.
                                example: site_loa_doc.pdf
                                type: string
                                x-auditable: true
                              id:
                                description: Identifier for the uploaded LOA document.
                                example: d933b1530bc56c9953cf8ce166da8004
                                maxLength: 32
                                nullable: true
                                type: string
                                x-auditable: true
                              size_bytes:
                                description: File size of the uploaded LOA document.
                                example: 444
                                type: integer
                                x-auditable: true
                              verified:
                                description: >-
                                  Whether the LOA has been verified by
                                  Cloudflare staff.
                                example: true
                                type: boolean
                                x-auditable: true
                              verified_at:
                                description: >-
                                  Timestamp of the moment the LOA was marked as
                                  validated.
                                format: date-time
                                nullable: true
                                type: string
                                x-auditable: true
                            type: object
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
          description: Upload LOA Document response failure
      security:
        - api_email: []
          api_key: []
      summary: Upload LOA Document
      tags:
        - IP Address Management Prefixes
      x-api-token-group:
        - Magic Transit Write
