openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/rulesets/{ruleset_id}/versions:
    get:
      description: Fetches the versions of a zone ruleset.
      operationId: listZoneRulesetVersions
      parameters:
        - in: path
          name: ruleset_id
          required: true
          schema:
            description: The unique ID of the ruleset.
            example: 2f2feab2026849078ba485f918791bdc
            pattern: ^[0-9a-f]{32}$
            title: ID
            type: string
        - in: path
          name: zone_id
          required: true
          schema:
            description: The unique ID of the zone.
            example: 9f1839b6152d298aca64c4e906b6d074
            pattern: ^[0-9a-f]{32}$
            title: ID
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - description: A response object.
                    properties:
                      errors:
                        description: A list of error messages.
                        items:
                          description: A message.
                          properties:
                            code:
                              description: A unique code for this message.
                              example: 10000
                              title: Code
                              type: integer
                            message:
                              description: A text description of this message.
                              example: something bad happened
                              minLength: 1
                              title: Description
                              type: string
                            source:
                              description: The source of this message.
                              properties:
                                pointer:
                                  description: >-
                                    A JSON pointer to the field that is the
                                    source of the message.
                                  example: /rules/0/action
                                  minLength: 1
                                  title: Pointer
                                  type: string
                              required:
                                - pointer
                              title: Source
                              type: object
                          required:
                            - message
                          title: Message
                          type: object
                        title: Errors
                        type: array
                      messages:
                        description: A list of warning messages.
                        items:
                          description: A message.
                          properties:
                            code:
                              description: A unique code for this message.
                              example: 10000
                              title: Code
                              type: integer
                            message:
                              description: A text description of this message.
                              example: something bad happened
                              minLength: 1
                              title: Description
                              type: string
                            source:
                              description: The source of this message.
                              properties:
                                pointer:
                                  description: >-
                                    A JSON pointer to the field that is the
                                    source of the message.
                                  example: /rules/0/action
                                  minLength: 1
                                  title: Pointer
                                  type: string
                              required:
                                - pointer
                              title: Source
                              type: object
                          required:
                            - message
                          title: Message
                          type: object
                        title: Messages
                        type: array
                      result:
                        description: A result.
                        title: Result
                      success:
                        description: Whether the API call was successful.
                        title: Success
                        type: boolean
                    required:
                      - result
                      - success
                      - errors
                      - messages
                    title: Response
                    type: object
                  - properties:
                      errors:
                        enum:
                          - []
                      result:
                        description: >-
                          A list of rulesets. The returned information will not
                          include the rules in each ruleset.
                        items:
                          allOf:
                            - description: A ruleset object.
                              properties:
                                description:
                                  default: ''
                                  description: An informative description of the ruleset.
                                  example: My ruleset to execute managed rulesets
                                  title: Description
                                  type: string
                                id:
                                  allOf:
                                    - description: The unique ID of the ruleset.
                                      example: 2f2feab2026849078ba485f918791bdc
                                      pattern: ^[0-9a-f]{32}$
                                      title: ID
                                      type: string
                                    - readOnly: true
                                last_updated:
                                  description: >-
                                    The timestamp of when the ruleset was last
                                    modified.
                                  example: '2000-01-01T00:00:00.000000Z'
                                  format: date-time
                                  readOnly: true
                                  title: Last updated
                                  type: string
                                  x-stainless-skip:
                                    - terraform
                                name:
                                  description: The human-readable name of the ruleset.
                                  example: My ruleset
                                  minLength: 1
                                  title: Name
                                  type: string
                                version:
                                  allOf:
                                    - description: The version of the ruleset.
                                      example: '1'
                                      pattern: ^[0-9]+$
                                      readOnly: true
                                      title: Version
                                      type: string
                                    - x-stainless-skip:
                                        - terraform
                              required:
                                - id
                                - version
                                - last_updated
                              title: Ruleset
                              type: object
                            - properties:
                                kind:
                                  description: The kind of the ruleset.
                                  enum:
                                    - managed
                                    - custom
                                    - root
                                    - zone
                                  example: root
                                  title: Kind
                                  type: string
                                phase:
                                  description: The phase of the ruleset.
                                  enum:
                                    - ddos_l4
                                    - ddos_l7
                                    - http_config_settings
                                    - http_custom_errors
                                    - http_log_custom_fields
                                    - http_ratelimit
                                    - http_request_cache_settings
                                    - http_request_dynamic_redirect
                                    - http_request_firewall_custom
                                    - http_request_firewall_managed
                                    - http_request_late_transform
                                    - http_request_origin
                                    - http_request_redirect
                                    - http_request_sanitize
                                    - http_request_sbfm
                                    - http_request_transform
                                    - http_response_compression
                                    - http_response_firewall_managed
                                    - http_response_headers_transform
                                    - magic_transit
                                    - magic_transit_ids_managed
                                    - magic_transit_managed
                                    - magic_transit_ratelimit
                                  example: http_request_firewall_custom
                                  title: Phase
                                  type: string
                              required:
                                - name
                                - kind
                                - phase
                        title: Rulesets
                        type: array
                      result_info:
                        description: Cursors information to navigate the results.
                        properties:
                          cursors:
                            description: Set of cursors.
                            properties:
                              after:
                                description: Cursor to use for the next page.
                                example: dGhpc2lzYW5leGFtcGxlCg
                                minLength: 1
                                title: Cursor
                                type: string
                            title: Cursors
                            type: object
                        title: Result Info
                        type: object
                      success:
                        enum:
                          - true
          description: A rulesets response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - description: A response object.
                    properties:
                      errors:
                        description: A list of error messages.
                        items:
                          description: A message.
                          properties:
                            code:
                              description: A unique code for this message.
                              example: 10000
                              title: Code
                              type: integer
                            message:
                              description: A text description of this message.
                              example: something bad happened
                              minLength: 1
                              title: Description
                              type: string
                            source:
                              description: The source of this message.
                              properties:
                                pointer:
                                  description: >-
                                    A JSON pointer to the field that is the
                                    source of the message.
                                  example: /rules/0/action
                                  minLength: 1
                                  title: Pointer
                                  type: string
                              required:
                                - pointer
                              title: Source
                              type: object
                          required:
                            - message
                          title: Message
                          type: object
                        title: Errors
                        type: array
                      messages:
                        description: A list of warning messages.
                        items:
                          description: A message.
                          properties:
                            code:
                              description: A unique code for this message.
                              example: 10000
                              title: Code
                              type: integer
                            message:
                              description: A text description of this message.
                              example: something bad happened
                              minLength: 1
                              title: Description
                              type: string
                            source:
                              description: The source of this message.
                              properties:
                                pointer:
                                  description: >-
                                    A JSON pointer to the field that is the
                                    source of the message.
                                  example: /rules/0/action
                                  minLength: 1
                                  title: Pointer
                                  type: string
                              required:
                                - pointer
                              title: Source
                              type: object
                          required:
                            - message
                          title: Message
                          type: object
                        title: Messages
                        type: array
                      result:
                        description: A result.
                        title: Result
                      success:
                        description: Whether the API call was successful.
                        title: Success
                        type: boolean
                    required:
                      - result
                      - success
                      - errors
                      - messages
                    title: Response
                    type: object
                  - properties:
                      result:
                        enum:
                          - null
                      success:
                        enum:
                          - false
          description: A failure response.
      security:
        - api_token: []
        - api_email: []
          api_key: []
        - api_email: []
          api_key: []
      summary: List a zone ruleset's versions
      tags:
        - Zone Rulesets
      x-api-token-group:
        - Response Compression Write
        - Response Compression Read
        - Config Settings Write
        - Config Settings Read
        - Dynamic URL Redirects Write
        - Dynamic URL Redirects Read
        - Cache Settings Write
        - Cache Settings Read
        - Custom Errors Write
        - Custom Errors Read
        - Origin Write
        - Origin Read
        - Managed headers Write
        - Managed headers Read
        - Zone Transform Rules Write
        - Zone Transform Rules Read
        - Mass URL Redirects Write
        - Mass URL Redirects Read
        - Magic Firewall Write
        - Magic Firewall Read
        - L4 DDoS Managed Ruleset Write
        - L4 DDoS Managed Ruleset Read
        - HTTP DDoS Managed Ruleset Write
        - HTTP DDoS Managed Ruleset Read
        - Sanitize Write
        - Sanitize Read
        - Transform Rules Write
        - Transform Rules Read
        - Select Configuration Write
        - Select Configuration Read
        - Bot Management Write
        - Bot Management Read
        - Zone WAF Write
        - Zone WAF Read
        - Account WAF Write
        - Account WAF Read
        - Account Rulesets Read
        - Account Rulesets Write
        - Logs Write
        - Logs Read
        - Logs Write
        - Logs Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
