openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/rules/lists:
    post:
      description: Creates a new list of the specified kind.
      operationId: lists-create-a-list
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: The Account ID for this resource.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            minLength: 32
            readOnly: true
            type: string
            x-auditable: true
      requestBody:
        content:
          application/json:
            schema:
              properties:
                description:
                  description: An informative summary of the list.
                  example: This is a note
                  maxLength: 500
                  type: string
                  x-auditable: true
                kind:
                  description: >-
                    The type of the list. Each type supports specific list items
                    (IP addresses, ASNs, hostnames or redirects).
                  enum:
                    - ip
                    - redirect
                    - hostname
                    - asn
                  example: ip
                name:
                  description: >-
                    An informative name for the list. Use this name in filter
                    and rule expressions.
                  example: list1
                  maxLength: 50
                  pattern: ^[a-zA-Z0-9_]+$
                  type: string
                  x-auditable: true
              required:
                - name
                - kind
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      result:
                        properties:
                          created_on:
                            description: >-
                              The RFC 3339 timestamp of when the list was
                              created.
                            example: '2020-01-01T08:00:00Z'
                            type: string
                            x-auditable: true
                          description:
                            description: An informative summary of the list.
                            example: This is a note
                            maxLength: 500
                            type: string
                            x-auditable: true
                          id:
                            description: The unique ID of the list.
                            example: 2c0fc9fa937b11eaa1b71c4d701ab86e
                            maxLength: 32
                            minLength: 32
                            readOnly: true
                            type: string
                            x-auditable: true
                          kind:
                            description: >-
                              The type of the list. Each type supports specific
                              list items (IP addresses, ASNs, hostnames or
                              redirects).
                            enum:
                              - ip
                              - redirect
                              - hostname
                              - asn
                            example: ip
                          modified_on:
                            description: >-
                              The RFC 3339 timestamp of when the list was last
                              modified.
                            example: '2020-01-10T14:00:00Z'
                            type: string
                            x-auditable: true
                          name:
                            description: >-
                              An informative name for the list. Use this name in
                              filter and rule expressions.
                            example: list1
                            maxLength: 50
                            pattern: ^[a-zA-Z0-9_]+$
                            type: string
                            x-auditable: true
                          num_items:
                            description: The number of items in the list.
                            example: 10
                            type: number
                            x-auditable: true
                          num_referencing_filters:
                            description: >-
                              The number of [filters](/api/resources/filters/)
                              referencing the list.
                            example: 2
                            type: number
                            x-auditable: true
                        required:
                          - id
                          - name
                          - kind
                          - num_items
                          - num_referencing_filters
                          - created_on
                          - modified_on
                        type: object
                    type: object
                  - properties:
                      errors:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      messages:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      result:
                        anyOf:
                          - type: object
                          - items:
                              type: object
                            type: array
                      success:
                        description: Defines whether the API call was successful.
                        enum:
                          - true
                        example: true
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
                type: object
          description: Create a list response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          result:
                            properties:
                              created_on:
                                description: >-
                                  The RFC 3339 timestamp of when the list was
                                  created.
                                example: '2020-01-01T08:00:00Z'
                                type: string
                                x-auditable: true
                              description:
                                description: An informative summary of the list.
                                example: This is a note
                                maxLength: 500
                                type: string
                                x-auditable: true
                              id:
                                description: The unique ID of the list.
                                example: 2c0fc9fa937b11eaa1b71c4d701ab86e
                                maxLength: 32
                                minLength: 32
                                readOnly: true
                                type: string
                                x-auditable: true
                              kind:
                                description: >-
                                  The type of the list. Each type supports
                                  specific list items (IP addresses, ASNs,
                                  hostnames or redirects).
                                enum:
                                  - ip
                                  - redirect
                                  - hostname
                                  - asn
                                example: ip
                              modified_on:
                                description: >-
                                  The RFC 3339 timestamp of when the list was
                                  last modified.
                                example: '2020-01-10T14:00:00Z'
                                type: string
                                x-auditable: true
                              name:
                                description: >-
                                  An informative name for the list. Use this
                                  name in filter and rule expressions.
                                example: list1
                                maxLength: 50
                                pattern: ^[a-zA-Z0-9_]+$
                                type: string
                                x-auditable: true
                              num_items:
                                description: The number of items in the list.
                                example: 10
                                type: number
                                x-auditable: true
                              num_referencing_filters:
                                description: >-
                                  The number of
                                  [filters](/api/resources/filters/) referencing
                                  the list.
                                example: 2
                                type: number
                                x-auditable: true
                            required:
                              - id
                              - name
                              - kind
                              - num_items
                              - num_referencing_filters
                              - created_on
                              - modified_on
                            type: object
                        type: object
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          result:
                            anyOf:
                              - type: object
                              - items:
                                  type: object
                                type: array
                          success:
                            description: Defines whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                          - result
                        type: object
                    type: object
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Defines whether the API call was successful.
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
          description: Create a list response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create a list
      tags:
        - Lists
      x-api-token-group:
        - Account Filter Lists Edit
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
