openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/snippets/snippet_rules:
    get:
      description: Fetches all snippet rules belonging to the zone.
      operationId: listZoneSnippetRules
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            description: The unique ID of the zone.
            example: 9f1839b6152d298aca64c4e906b6d074
            pattern: ^[0-9a-f]{32}$
            title: Zone ID
            type: string
            x-auditable: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - description: A response object.
                    properties:
                      errors:
                        description: A list of error messages.
                        items:
                          description: A message.
                          properties:
                            code:
                              description: A unique code for this message.
                              example: 10000
                              title: Code
                              type: integer
                              x-auditable: true
                            message:
                              description: A text description of this message.
                              example: something bad happened
                              minLength: 1
                              title: Description
                              type: string
                              x-auditable: true
                          required:
                            - message
                          title: Message
                          type: object
                        title: Errors
                        type: array
                      messages:
                        description: A list of warning messages.
                        items:
                          description: A message.
                          properties:
                            code:
                              description: A unique code for this message.
                              example: 10000
                              title: Code
                              type: integer
                              x-auditable: true
                            message:
                              description: A text description of this message.
                              example: something bad happened
                              minLength: 1
                              title: Description
                              type: string
                              x-auditable: true
                          required:
                            - message
                          title: Message
                          type: object
                        title: Messages
                        type: array
                      result:
                        description: A result.
                        title: Result
                      success:
                        description: Whether the API call was successful.
                        title: Success
                        type: boolean
                        x-auditable: true
                    required:
                      - result
                      - success
                      - errors
                      - messages
                    title: Response
                    type: object
                  - properties:
                      errors:
                        enum:
                          - []
                      result:
                        description: A list of snippet rules.
                        items:
                          description: A snippet rule.
                          properties:
                            description:
                              default: ''
                              description: An informative description of the rule.
                              example: Execute my_snippet when IP address is 1.1.1.1.
                              title: Description
                              type: string
                              x-auditable: true
                            enabled:
                              default: false
                              description: Whether the rule should be executed.
                              example: true
                              title: Enabled
                              type: boolean
                              x-auditable: true
                            expression:
                              description: >-
                                The expression defining which traffic will match
                                the rule.
                              example: ip.src ne 1.1.1.1
                              minLength: 1
                              title: Expression
                              type: string
                              x-auditable: true
                            id:
                              description: The unique ID of the rule.
                              example: 3a03d665bac047339bb530ecb439a90d
                              pattern: ^[0-9a-f]{32}$
                              readOnly: true
                              title: ID
                              type: string
                              x-auditable: true
                            last_updated:
                              description: >-
                                The timestamp of when the rule was last
                                modified.
                              example: '2000-01-01T00:00:00.000000Z'
                              format: date-time
                              readOnly: true
                              title: Last Updated
                              type: string
                              x-auditable: true
                            snippet_name:
                              description: The identifying name of the snippet.
                              example: my_snippet
                              pattern: ^[A-Za-z0-9_]+$
                              title: Snippet Name
                              type: string
                              x-auditable: true
                          required:
                            - id
                            - expression
                            - snippet_name
                            - last_updated
                          title: Snippet Rule
                          type: object
                        title: Snippet Rules
                        type: array
                      success:
                        enum:
                          - true
          description: A snippet rules response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - description: A response object.
                    properties:
                      errors:
                        description: A list of error messages.
                        items:
                          description: A message.
                          properties:
                            code:
                              description: A unique code for this message.
                              example: 10000
                              title: Code
                              type: integer
                              x-auditable: true
                            message:
                              description: A text description of this message.
                              example: something bad happened
                              minLength: 1
                              title: Description
                              type: string
                              x-auditable: true
                          required:
                            - message
                          title: Message
                          type: object
                        title: Errors
                        type: array
                      messages:
                        description: A list of warning messages.
                        items:
                          description: A message.
                          properties:
                            code:
                              description: A unique code for this message.
                              example: 10000
                              title: Code
                              type: integer
                              x-auditable: true
                            message:
                              description: A text description of this message.
                              example: something bad happened
                              minLength: 1
                              title: Description
                              type: string
                              x-auditable: true
                          required:
                            - message
                          title: Message
                          type: object
                        title: Messages
                        type: array
                      result:
                        description: A result.
                        title: Result
                      success:
                        description: Whether the API call was successful.
                        title: Success
                        type: boolean
                        x-auditable: true
                    required:
                      - result
                      - success
                      - errors
                      - messages
                    title: Response
                    type: object
                  - properties:
                      result:
                        enum:
                          - null
                        x-auditable: true
                      success:
                        enum:
                          - false
          description: A failure response.
        5XX:
          content:
            application/json:
              schema:
                allOf:
                  - description: A response object.
                    properties:
                      errors:
                        description: A list of error messages.
                        items:
                          description: A message.
                          properties:
                            code:
                              description: A unique code for this message.
                              example: 10000
                              title: Code
                              type: integer
                              x-auditable: true
                            message:
                              description: A text description of this message.
                              example: something bad happened
                              minLength: 1
                              title: Description
                              type: string
                              x-auditable: true
                          required:
                            - message
                          title: Message
                          type: object
                        title: Errors
                        type: array
                      messages:
                        description: A list of warning messages.
                        items:
                          description: A message.
                          properties:
                            code:
                              description: A unique code for this message.
                              example: 10000
                              title: Code
                              type: integer
                              x-auditable: true
                            message:
                              description: A text description of this message.
                              example: something bad happened
                              minLength: 1
                              title: Description
                              type: string
                              x-auditable: true
                          required:
                            - message
                          title: Message
                          type: object
                        title: Messages
                        type: array
                      result:
                        description: A result.
                        title: Result
                      success:
                        description: Whether the API call was successful.
                        title: Success
                        type: boolean
                        x-auditable: true
                    required:
                      - result
                      - success
                      - errors
                      - messages
                    title: Response
                    type: object
                  - properties:
                      result:
                        enum:
                          - null
                        x-auditable: true
                      success:
                        enum:
                          - false
          description: A failure response.
      security:
        - api_token: []
        - api_email: []
          api_key: []
        - api_email: []
          api_key: []
      summary: List zone snippet rules
      tags:
        - Zone Snippets
      x-api-token-group:
        - Snippets Write
        - Snippets Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
