openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/cni/cnis:
    get:
      operationId: list_cnis
      parameters:
        - description: If specified, only show CNIs associated with the specified slot
          in: query
          name: slot
          schema:
            nullable: true
            type: string
        - description: If specified, only show cnis associated with the specified tunnel id
          in: query
          name: tunnel_id
          schema:
            nullable: true
            type: string
        - in: query
          name: cursor
          schema:
            format: int32
            nullable: true
            type: integer
        - in: query
          name: limit
          schema:
            minimum: 0
            nullable: true
            type: integer
        - in: path
          name: account_id
          required: true
          schema:
            description: Customer account tag
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  items:
                    items:
                      properties:
                        account:
                          description: Customer account tag
                          type: string
                        bgp:
                          properties:
                            customer_asn:
                              description: ASN used on the customer end of the BGP session
                              format: int32
                              minimum: 0
                              type: integer
                            extra_prefixes:
                              description: >-
                                Extra set of static prefixes to advertise to the
                                customer's end of the session
                              example: 192.168.3.4/31
                              items:
                                format: A.B.C.D/N
                                type: string
                              type: array
                            md5_key:
                              description: >-
                                MD5 key to use for session authentication.


                                Note that *this is not a security measure*. MD5
                                is not a valid security mechanism, and the

                                key is not treated as a secret value. This is
                                *only* supported for preventing

                                misconfiguration, not for defending against
                                malicious attacks.


                                The MD5 key, if set, must be of non-zero length
                                and consist only of the following types of

                                character:


                                * ASCII alphanumerics: `[a-zA-Z0-9]`

                                * Special characters in the set
                                `'!@#$%^&*()+[]{}<>/.,;:_-~`= \|`


                                In other words, MD5 keys may contain any
                                printable ASCII character aside from newline
                                (0x0A),

                                quotation mark (`"`), vertical tab (0x0B),
                                carriage return (0x0D), tab (0x09), form feed

                                (0x0C), and the question mark (`?`). Requests
                                specifying an MD5 key with one or more of

                                these disallowed characters will be rejected.
                              nullable: true
                              type: string
                          required:
                            - customer_asn
                            - extra_prefixes
                          type: object
                        cust_ip:
                          description: >-
                            Customer end of the point-to-point link


                            This should always be inside the same prefix as
                            `p2p_ip`.
                          example: 192.168.3.4/31
                          format: A.B.C.D/N
                          type: string
                        id:
                          format: uuid
                          type: string
                        interconnect:
                          description: Interconnect identifier hosting this CNI
                          type: string
                        magic:
                          properties:
                            conduit_name:
                              type: string
                            description:
                              type: string
                            mtu:
                              format: int32
                              minimum: 0
                              type: integer
                          required:
                            - conduit_name
                            - description
                            - mtu
                          type: object
                        p2p_ip:
                          description: Cloudflare end of the point-to-point link
                          example: 192.168.3.4/31
                          format: A.B.C.D/N
                          type: string
                      required:
                        - id
                        - interconnect
                        - account
                        - p2p_ip
                        - cust_ip
                        - magic
                      type: object
                    type: array
                  next:
                    format: int32
                    nullable: true
                    type: integer
                required:
                  - items
                type: object
          description: List of matching CNI objects
        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List existing CNI objects
      tags:
        - CNIs
      x-api-token-group:
        - Magic WAN Write
        - Magic WAN Read
        - Magic Transit Read
        - Magic Transit Write
