openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /user/load_balancers/pools/{pool_id}/health:
    get:
      description: Fetch the latest pool health status for a single pool.
      operationId: load-balancer-pools-pool-health-details
      parameters:
        - in: path
          name: pool_id
          required: true
          schema:
            example: 17b5962d775c646f3f9725cbc7a53df4
            type: string
            x-auditable: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                          - result
                        type: object
                      - properties:
                          result:
                            anyOf:
                              - nullable: true
                                type: object
                              - nullable: true
                                type: string
                    type: object
                  - properties:
                      result:
                        description: >-
                          A list of regions from which to run health checks.
                          Null means every Cloudflare data center.
                        example:
                          pool_id: 17b5962d775c646f3f9725cbc7a53df4
                          pop_health:
                            Amsterdam, NL:
                              healthy: true
                              origins:
                                - 2001:DB8::5:
                                    failure_reason: No failures
                                    healthy: true
                                    response_code: 401
                                    rtt: 12.1ms
                        properties:
                          pool_id:
                            description: Pool ID
                            example: 17b5962d775c646f3f9725cbc7a53df4
                            type: string
                            x-auditable: true
                          pop_health:
                            description: List of regions and associated health status.
                            properties:
                              healthy:
                                description: Whether health check in region is healthy.
                                example: true
                                type: boolean
                                x-auditable: true
                              origins:
                                items:
                                  properties:
                                    ip:
                                      properties:
                                        failure_reason:
                                          description: Failure reason.
                                          example: No failure reasons
                                          type: string
                                          x-auditable: true
                                        healthy:
                                          description: Origin health status.
                                          example: true
                                          type: boolean
                                          x-auditable: true
                                        response_code:
                                          description: Response code from origin health check.
                                          example: 200
                                          type: number
                                          x-auditable: true
                                        rtt:
                                          description: Origin RTT (Round Trip Time) response.
                                          example: 201.5ms
                                          type: string
                                          x-auditable: true
                                      type: object
                                  type: object
                                type: array
                            type: object
                        type: object
          description: Pool Health Details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - allOf:
                          - properties:
                              errors:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    message:
                                      type: string
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              messages:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    message:
                                      type: string
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              success:
                                description: Whether the API call was successful
                                enum:
                                  - true
                                example: true
                                type: boolean
                            required:
                              - success
                              - errors
                              - messages
                              - result
                            type: object
                          - properties:
                              result:
                                anyOf:
                                  - nullable: true
                                    type: object
                                  - nullable: true
                                    type: string
                        type: object
                      - properties:
                          result:
                            description: >-
                              A list of regions from which to run health checks.
                              Null means every Cloudflare data center.
                            example:
                              pool_id: 17b5962d775c646f3f9725cbc7a53df4
                              pop_health:
                                Amsterdam, NL:
                                  healthy: true
                                  origins:
                                    - 2001:DB8::5:
                                        failure_reason: No failures
                                        healthy: true
                                        response_code: 401
                                        rtt: 12.1ms
                            properties:
                              pool_id:
                                description: Pool ID
                                example: 17b5962d775c646f3f9725cbc7a53df4
                                type: string
                                x-auditable: true
                              pop_health:
                                description: List of regions and associated health status.
                                properties:
                                  healthy:
                                    description: Whether health check in region is healthy.
                                    example: true
                                    type: boolean
                                    x-auditable: true
                                  origins:
                                    items:
                                      properties:
                                        ip:
                                          properties:
                                            failure_reason:
                                              description: Failure reason.
                                              example: No failure reasons
                                              type: string
                                              x-auditable: true
                                            healthy:
                                              description: Origin health status.
                                              example: true
                                              type: boolean
                                              x-auditable: true
                                            response_code:
                                              description: Response code from origin health check.
                                              example: 200
                                              type: number
                                              x-auditable: true
                                            rtt:
                                              description: Origin RTT (Round Trip Time) response.
                                              example: 201.5ms
                                              type: string
                                              x-auditable: true
                                          type: object
                                      type: object
                                    type: array
                                type: object
                            type: object
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
          description: Pool Health Details response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Pool Health Details
      tags:
        - Load Balancer Pools
      x-api-token-group:
        - 'Load Balancing: Monitors and Pools Write'
        - 'Load Balancing: Monitors and Pools Read'
