openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/mnm/config:
    patch:
      description: Update fields in an existing network monitoring configuration.
      operationId: >-
        magic-network-monitoring-configuration-update-account-configuration-fields
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            example: 6f91088a406011ed95aed352566e8d4c
            type: string
            x-auditable: true
      requestBody:
        content:
          application/json:
            schema:
              properties:
                default_sampling:
                  default: 1
                  description: >-
                    Fallback sampling rate of flow messages being sent in
                    packets per second. This should match the packet sampling
                    rate configured on the router.
                  minimum: 1
                  type: number
                  x-auditable: true
                name:
                  description: The account name.
                  example: cloudflare user's account
                  type: string
                  x-auditable: true
                router_ips:
                  items:
                    description: >-
                      IPv4 CIDR of the router sourcing flow data. Only /32
                      addresses are currently supported.
                    example: 203.0.113.1
                    type: string
                    x-auditable: true
                  type: array
                warp_devices:
                  items:
                    description: Object representing a warp device with an ID and name.
                    properties:
                      id:
                        description: Unique identifier for the warp device.
                        example: 5360368d-b351-4791-abe1-93550dabd351
                        type: string
                        x-auditable: true
                      name:
                        description: Name of the warp device.
                        example: My warp device
                        type: string
                        x-auditable: true
                      router_ip:
                        description: >-
                          IPv4 CIDR of the router sourcing flow data associated
                          with this warp device. Only /32 addresses are
                          currently supported.
                        example: 203.0.113.1
                        type: string
                        x-auditable: true
                    required:
                      - id
                      - name
                      - router_ip
                    type: object
                  type: array
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          result:
                            anyOf:
                              - type: object
                              - items: {}
                                type: array
                              - type: string
                          success:
                            description: Whether the API call was successful
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                          - result
                        type: object
                      - properties:
                          result:
                            anyOf:
                              - nullable: true
                                type: object
                              - nullable: true
                                type: string
                    type: object
                  - properties:
                      result:
                        properties:
                          default_sampling:
                            default: 1
                            description: >-
                              Fallback sampling rate of flow messages being sent
                              in packets per second. This should match the
                              packet sampling rate configured on the router.
                            minimum: 1
                            type: number
                            x-auditable: true
                          name:
                            description: The account name.
                            example: cloudflare user's account
                            type: string
                            x-auditable: true
                          router_ips:
                            items:
                              description: >-
                                IPv4 CIDR of the router sourcing flow data. Only
                                /32 addresses are currently supported.
                              example: 203.0.113.1
                              type: string
                              x-auditable: true
                            type: array
                          warp_devices:
                            items:
                              description: >-
                                Object representing a warp device with an ID and
                                name.
                              properties:
                                id:
                                  description: Unique identifier for the warp device.
                                  example: 5360368d-b351-4791-abe1-93550dabd351
                                  type: string
                                  x-auditable: true
                                name:
                                  description: Name of the warp device.
                                  example: My warp device
                                  type: string
                                  x-auditable: true
                                router_ip:
                                  description: >-
                                    IPv4 CIDR of the router sourcing flow data
                                    associated with this warp device. Only /32
                                    addresses are currently supported.
                                  example: 203.0.113.1
                                  type: string
                                  x-auditable: true
                              required:
                                - id
                                - name
                                - router_ip
                              type: object
                            type: array
                        required:
                          - name
                          - default_sampling
                          - router_ips
                          - warp_devices
                        type: object
                    type: object
          description: Update account configuration fields response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - allOf:
                          - properties:
                              errors:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    message:
                                      type: string
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              messages:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    message:
                                      type: string
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              result:
                                anyOf:
                                  - type: object
                                  - items: {}
                                    type: array
                                  - type: string
                              success:
                                description: Whether the API call was successful
                                enum:
                                  - true
                                example: true
                                type: boolean
                            required:
                              - success
                              - errors
                              - messages
                              - result
                            type: object
                          - properties:
                              result:
                                anyOf:
                                  - nullable: true
                                    type: object
                                  - nullable: true
                                    type: string
                        type: object
                      - properties:
                          result:
                            properties:
                              default_sampling:
                                default: 1
                                description: >-
                                  Fallback sampling rate of flow messages being
                                  sent in packets per second. This should match
                                  the packet sampling rate configured on the
                                  router.
                                minimum: 1
                                type: number
                                x-auditable: true
                              name:
                                description: The account name.
                                example: cloudflare user's account
                                type: string
                                x-auditable: true
                              router_ips:
                                items:
                                  description: >-
                                    IPv4 CIDR of the router sourcing flow data.
                                    Only /32 addresses are currently supported.
                                  example: 203.0.113.1
                                  type: string
                                  x-auditable: true
                                type: array
                              warp_devices:
                                items:
                                  description: >-
                                    Object representing a warp device with an ID
                                    and name.
                                  properties:
                                    id:
                                      description: Unique identifier for the warp device.
                                      example: 5360368d-b351-4791-abe1-93550dabd351
                                      type: string
                                      x-auditable: true
                                    name:
                                      description: Name of the warp device.
                                      example: My warp device
                                      type: string
                                      x-auditable: true
                                    router_ip:
                                      description: >-
                                        IPv4 CIDR of the router sourcing flow
                                        data associated with this warp device.
                                        Only /32 addresses are currently
                                        supported.
                                      example: 203.0.113.1
                                      type: string
                                      x-auditable: true
                                  required:
                                    - id
                                    - name
                                    - router_ip
                                  type: object
                                type: array
                            required:
                              - name
                              - default_sampling
                              - router_ips
                              - warp_devices
                            type: object
                        type: object
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
          description: Update account configuration fields response failure
      security:
        - api_email: []
          api_key: []
      summary: Update account configuration fields
      tags:
        - Magic Network Monitoring Configuration
      x-api-token-group:
        - Magic Network Monitoring Admin
        - Magic Network Monitoring Config Write
