openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/magic/sites/{site_id}/lans/{lan_id}:
    delete:
      description: Remove a specific Site LAN.
      operationId: magic-site-lans-delete-lan
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            description: Identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
        - in: path
          name: account_id
          required: true
          schema:
            description: Identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
        - in: path
          name: lan_id
          required: true
          schema:
            description: Identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          result:
                            anyOf:
                              - type: object
                              - items: {}
                                type: array
                              - type: string
                          success:
                            description: Whether the API call was successful
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                          - result
                        type: object
                      - properties:
                          result:
                            anyOf:
                              - nullable: true
                                type: object
                              - nullable: true
                                type: string
                    type: object
                  - properties:
                      result:
                        properties:
                          ha_link:
                            description: >-
                              mark true to use this LAN for HA probing. only
                              works for site with HA turned on. only one LAN can
                              be set as the ha_link.
                            type: boolean
                          id:
                            description: Identifier
                            example: 023e105f4ecef8ad9ca31a8372d0c353
                            maxLength: 32
                            readOnly: true
                            type: string
                          name:
                            type: string
                          nat:
                            properties:
                              static_prefix:
                                description: >-
                                  A valid CIDR notation representing an IP
                                  range.
                                example: 192.0.2.0/24
                                type: string
                            type: object
                          physport:
                            example: 1
                            type: integer
                          routed_subnets:
                            items:
                              properties:
                                nat:
                                  properties:
                                    static_prefix:
                                      description: >-
                                        A valid CIDR notation representing an IP
                                        range.
                                      example: 192.0.2.0/24
                                      type: string
                                  type: object
                                next_hop:
                                  description: A valid IPv4 address.
                                  example: 192.0.2.1
                                  type: string
                                prefix:
                                  description: >-
                                    A valid CIDR notation representing an IP
                                    range.
                                  example: 192.0.2.0/24
                                  type: string
                              required:
                                - prefix
                                - next_hop
                              type: object
                            type: array
                          site_id:
                            description: Identifier
                            example: 023e105f4ecef8ad9ca31a8372d0c353
                            maxLength: 32
                            readOnly: true
                            type: string
                          static_addressing:
                            description: >-
                              If the site is not configured in high availability
                              mode, this configuration is optional (if omitted,
                              use DHCP). However, if in high availability mode,
                              static_address is required along with secondary
                              and virtual address.
                            properties:
                              address:
                                description: >-
                                  A valid CIDR notation representing an IP
                                  range.
                                example: 192.0.2.0/24
                                type: string
                              dhcp_relay:
                                properties:
                                  server_addresses:
                                    description: List of DHCP server IPs.
                                    items:
                                      description: A valid IPv4 address.
                                      example: 192.0.2.1
                                      type: string
                                    type: array
                                type: object
                              dhcp_server:
                                properties:
                                  dhcp_pool_end:
                                    description: A valid IPv4 address.
                                    example: 192.0.2.1
                                    type: string
                                  dhcp_pool_start:
                                    description: A valid IPv4 address.
                                    example: 192.0.2.1
                                    type: string
                                  dns_server:
                                    description: A valid IPv4 address.
                                    example: 192.0.2.1
                                    type: string
                                  dns_servers:
                                    items:
                                      description: A valid IPv4 address.
                                      example: 192.0.2.1
                                      type: string
                                    type: array
                                  reservations:
                                    additionalProperties:
                                      description: >-
                                        IP address associated with the MAC
                                        address
                                      type: string
                                    description: Mapping of MAC addresses to IP addresses
                                    example:
                                      '00:11:22:33:44:55': 192.0.2.100
                                      AA:BB:CC:DD:EE:FF: 192.168.1.101
                                    type: object
                                type: object
                              secondary_address:
                                description: >-
                                  A valid CIDR notation representing an IP
                                  range.
                                example: 192.0.2.0/24
                                type: string
                              virtual_address:
                                description: >-
                                  A valid CIDR notation representing an IP
                                  range.
                                example: 192.0.2.0/24
                                type: string
                            required:
                              - address
                            type: object
                          vlan_tag:
                            description: VLAN ID. Use zero for untagged.
                            example: 42
                            type: integer
                            x-auditable: true
                        type: object
          description: Delete Site LAN response
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    minLength: 1
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: Delete Site LAN response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete Site LAN
      tags:
        - Magic Site LANs
      x-api-token-group:
        - Magic WAN Write
        - Magic Transit Write
      x-cfPermissionsRequired:
        enum:
          - '#organization:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
