openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/magic/sites/{site_id}/acls/{acl_id}:
    get:
      description: Get a specific Site ACL.
      operationId: magic-site-acls-acl-details
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            description: Identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
        - in: path
          name: account_id
          required: true
          schema:
            description: Identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
        - in: path
          name: acl_id
          required: true
          schema:
            description: Identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          result:
                            anyOf:
                              - type: object
                              - items: {}
                                type: array
                              - type: string
                          success:
                            description: Whether the API call was successful
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                          - result
                        type: object
                      - properties:
                          result:
                            anyOf:
                              - nullable: true
                                type: object
                              - nullable: true
                                type: string
                    type: object
                  - properties:
                      result:
                        description: >-
                          Bidirectional ACL policy for network traffic within a
                          site.
                        properties:
                          description:
                            description: Description for the ACL.
                            example: >-
                              Allows local traffic between PIN pads and cash
                              register.
                            type: string
                          forward_locally:
                            description: >-
                              The desired forwarding action for this ACL policy.
                              If set to "false", the policy will forward traffic
                              to Cloudflare. If set to "true", the policy will
                              forward traffic locally on the Magic Connector. If
                              not included in request, will default to false.
                            type: boolean
                          id:
                            description: Identifier
                            example: 023e105f4ecef8ad9ca31a8372d0c353
                            maxLength: 32
                            readOnly: true
                            type: string
                          lan_1:
                            properties:
                              lan_id:
                                description: >-
                                  The identifier for the LAN you want to create
                                  an ACL policy with.
                                type: string
                              lan_name:
                                description: >-
                                  The name of the LAN based on the provided
                                  lan_id.
                                type: string
                              port_ranges:
                                description: >-
                                  Array of port ranges on the provided LAN that
                                  will be included in the ACL. If no ports or
                                  port rangess are provided, communication on
                                  any port on this LAN is allowed.
                                items:
                                  description: A valid port range value.
                                  example: 8080-9000
                                  type: string
                                type: array
                              ports:
                                description: >-
                                  Array of ports on the provided LAN that will
                                  be included in the ACL. If no ports or port
                                  ranges are provided, communication on any port
                                  on this LAN is allowed.
                                items:
                                  example: 1
                                  type: integer
                                type: array
                              subnets:
                                description: >-
                                  Array of subnet IPs within the LAN that will
                                  be included in the ACL. If no subnets are
                                  provided, communication on any subnets on this
                                  LAN are allowed.
                                items:
                                  oneOf:
                                    - description: A valid IPv4 address.
                                      example: 192.0.2.1
                                      type: string
                                    - description: >-
                                        A valid CIDR notation representing an IP
                                        range.
                                      example: 192.0.2.0/24
                                      type: string
                                type: array
                            required:
                              - lan_id
                            type: object
                          lan_2:
                            properties:
                              lan_id:
                                description: >-
                                  The identifier for the LAN you want to create
                                  an ACL policy with.
                                type: string
                              lan_name:
                                description: >-
                                  The name of the LAN based on the provided
                                  lan_id.
                                type: string
                              port_ranges:
                                description: >-
                                  Array of port ranges on the provided LAN that
                                  will be included in the ACL. If no ports or
                                  port rangess are provided, communication on
                                  any port on this LAN is allowed.
                                items:
                                  description: A valid port range value.
                                  example: 8080-9000
                                  type: string
                                type: array
                              ports:
                                description: >-
                                  Array of ports on the provided LAN that will
                                  be included in the ACL. If no ports or port
                                  ranges are provided, communication on any port
                                  on this LAN is allowed.
                                items:
                                  example: 1
                                  type: integer
                                type: array
                              subnets:
                                description: >-
                                  Array of subnet IPs within the LAN that will
                                  be included in the ACL. If no subnets are
                                  provided, communication on any subnets on this
                                  LAN are allowed.
                                items:
                                  oneOf:
                                    - description: A valid IPv4 address.
                                      example: 192.0.2.1
                                      type: string
                                    - description: >-
                                        A valid CIDR notation representing an IP
                                        range.
                                      example: 192.0.2.0/24
                                      type: string
                                type: array
                            required:
                              - lan_id
                            type: object
                          name:
                            description: The name of the ACL.
                            example: PIN Pad - Cash Register
                            type: string
                          protocols:
                            items:
                              description: >-
                                Array of allowed communication protocols between
                                configured LANs. If no protocols are provided,
                                all protocols are allowed.
                              enum:
                                - tcp
                                - udp
                                - icmp
                              type: string
                            type: array
                          unidirectional:
                            description: >-
                              The desired traffic direction for this ACL policy.
                              If set to "false", the policy will allow
                              bidirectional traffic. If set to "true", the
                              policy will only allow traffic in one direction.
                              If not included in request, will default to false.
                            type: boolean
                        type: object
          description: Site ACL Details response
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    minLength: 1
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: Site ACL Details response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Site ACL Details
      tags:
        - Magic Site ACLs
      x-api-token-group:
        - Magic WAN Write
        - Magic WAN Read
        - Magic Transit Read
        - Magic Transit Write
      x-cfPermissionsRequired:
        enum:
          - '#organization:read'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
