openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/magic/sites/{site_id}:
    patch:
      description: Patch a specific Site.
      operationId: magic-sites-patch-site
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            description: Identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
        - in: path
          name: account_id
          required: true
          schema:
            description: Identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                connector_id:
                  description: Magic Connector identifier tag.
                  example: ac60d3d0435248289d446cedd870bcf4
                  type: string
                  x-auditable: true
                description:
                  type: string
                location:
                  description: Location of site in latitude and longitude.
                  properties:
                    lat:
                      description: Latitude
                      example: 37.6192
                      type: string
                      x-auditable: true
                    lon:
                      description: Longitude
                      example: 122.3816
                      type: string
                      x-auditable: true
                  type: object
                name:
                  description: The name of the site.
                  example: site_1
                  type: string
                  x-auditable: true
                secondary_connector_id:
                  description: >-
                    Magic Connector identifier tag. Used when high availability
                    mode is on.
                  example: 8d67040d3835dbcf46ce29da440dc482
                  type: string
                  x-auditable: true
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          result:
                            anyOf:
                              - type: object
                              - items: {}
                                type: array
                              - type: string
                          success:
                            description: Whether the API call was successful
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                          - result
                        type: object
                      - properties:
                          result:
                            anyOf:
                              - nullable: true
                                type: object
                              - nullable: true
                                type: string
                    type: object
                  - properties:
                      result:
                        properties:
                          connector_id:
                            description: Magic Connector identifier tag.
                            example: ac60d3d0435248289d446cedd870bcf4
                            type: string
                            x-auditable: true
                          description:
                            type: string
                          ha_mode:
                            description: >-
                              Site high availability mode. If set to true, the
                              site can have two connectors and runs in high
                              availability mode.
                            example: true
                            type: boolean
                          id:
                            description: Identifier
                            example: 023e105f4ecef8ad9ca31a8372d0c353
                            maxLength: 32
                            readOnly: true
                            type: string
                          location:
                            description: Location of site in latitude and longitude.
                            properties:
                              lat:
                                description: Latitude
                                example: 37.6192
                                type: string
                                x-auditable: true
                              lon:
                                description: Longitude
                                example: 122.3816
                                type: string
                                x-auditable: true
                            type: object
                          name:
                            description: The name of the site.
                            example: site_1
                            type: string
                            x-auditable: true
                          secondary_connector_id:
                            description: >-
                              Magic Connector identifier tag. Used when high
                              availability mode is on.
                            example: 8d67040d3835dbcf46ce29da440dc482
                            type: string
                            x-auditable: true
                        type: object
          description: Patch Site response
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    minLength: 1
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: Patch Site response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Patch Site
      tags:
        - Magic Sites
      x-api-token-group:
        - Magic WAN Write
        - Magic Transit Write
      x-cfPermissionsRequired:
        enum:
          - '#organization:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
