openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/magic/connectors/{connector_id}/telemetry/snapshots:
    get:
      operationId: mconn-connector-telemetry-snapshots-list
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Account identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
        - in: path
          name: connector_id
          required: true
          schema:
            type: string
        - in: query
          name: from
          required: true
          schema:
            type: number
        - in: query
          name: to
          required: true
          schema:
            type: number
        - in: query
          name: limit
          schema:
            type: number
        - in: query
          name: cursor
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        items:
                          properties:
                            code:
                              type: number
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                        type: array
                      messages:
                        items:
                          properties:
                            code:
                              type: number
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                        type: array
                      success:
                        type: boolean
                    required:
                      - success
                    type: object
                  - properties:
                      result:
                        properties:
                          count:
                            type: number
                          cursor:
                            type: string
                          items:
                            items:
                              properties:
                                a:
                                  description: >-
                                    Time the Snapshot was collected (seconds
                                    since the Unix epoch)
                                  type: number
                                t:
                                  description: >-
                                    Time the Snapshot was recorded (seconds
                                    since the Unix epoch)
                                  type: number
                              required:
                                - a
                                - t
                              type: object
                            type: array
                        required:
                          - items
                          - count
                        type: object
                    required:
                      - result
                    type: object
                type: object
          description: OK
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        code:
                          type: number
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  messages:
                    items:
                      properties:
                        code:
                          type: number
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  success:
                    type: boolean
                required:
                  - success
                type: object
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        code:
                          type: number
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  messages:
                    items:
                      properties:
                        code:
                          type: number
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  success:
                    type: boolean
                required:
                  - success
                type: object
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        code:
                          type: number
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  messages:
                    items:
                      properties:
                        code:
                          type: number
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  success:
                    type: boolean
                required:
                  - success
                type: object
          description: Forbidden
        '429':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        code:
                          type: number
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  messages:
                    items:
                      properties:
                        code:
                          type: number
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  success:
                    type: boolean
                required:
                  - success
                type: object
          description: Too Many Requests
        '500':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        code:
                          type: number
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  messages:
                    items:
                      properties:
                        code:
                          type: number
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  success:
                    type: boolean
                required:
                  - success
                type: object
          description: Internal Server Error
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List Snapshots
      tags:
        - Magic Connectors
      x-api-token-group:
        - Magic WAN Write
        - Magic WAN Read
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
