openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /organizations/{organization_id}/shares:
    get:
      description: Lists all organization shares.
      operationId: organization-shares-list
      parameters:
        - in: path
          name: organization_id
          required: true
          schema:
            description: Organization identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
        - description: Filter shares by status.
          in: query
          name: status
          schema:
            enum:
              - active
              - deleting
              - deleted
            type: string
        - description: Filter shares by kind.
          in: query
          name: kind
          schema:
            enum:
              - sent
              - received
            type: string
        - description: Filter shares by target_type.
          in: query
          name: target_type
          schema:
            enum:
              - account
              - organization
            type: string
        - description: Order shares by values in the given field.
          in: query
          name: order
          schema:
            default: created
            enum:
              - name
              - created
            type: string
        - description: Direction to sort objects.
          in: query
          name: direction
          schema:
            default: asc
            enum:
              - asc
              - desc
            type: string
        - description: Page number.
          in: query
          name: page
          schema:
            example: 2
            minimum: 0
            multipleOf: 1
            type: integer
        - description: Number of objects to return per page.
          in: query
          name: per_page
          schema:
            example: 20
            maximum: 100
            minimum: 0
            multipleOf: 1
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                            type: array
                          result:
                            anyOf:
                              - type: object
                              - items: {}
                                type: array
                              - type: string
                          success:
                            description: Whether the API call was successful.
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                        type: object
                      - properties:
                          result:
                            items: {}
                            nullable: true
                            type: array
                          result_info:
                            properties:
                              count:
                                description: >-
                                  Total number of results for the requested
                                  service.
                                example: 1
                                type: number
                              page:
                                description: Current page within paginated list of results.
                                example: 1
                                type: number
                              per_page:
                                description: Number of results per page of results.
                                example: 20
                                type: number
                              total_count:
                                description: >-
                                  Total results available without any search
                                  parameters.
                                example: 2000
                                type: number
                              total_pages:
                                description: >-
                                  Total number of pages using the given per
                                  page.
                                example: 50
                                type: number
                            type: object
                    type: object
                  - properties:
                      result:
                        items:
                          properties:
                            account_id:
                              description: Account identifier.
                              example: 023e105f4ecef8ad9ca31a8372d0c353
                              maxLength: 32
                              type: string
                            account_name:
                              description: The display name of an account.
                              example: Account A
                              type: string
                            created:
                              description: When the share was created.
                              example: '2023-09-21T18:56:32.624632Z'
                              format: date-time
                              type: string
                            id:
                              description: Share identifier tag.
                              example: 3fd85f74b32742f1bff64a85009dda07
                              maxLength: 32
                              type: string
                            kind:
                              enum:
                                - sent
                                - received
                              type: string
                            modified:
                              description: When the share was modified.
                              example: '2023-09-21T18:56:32.624632Z'
                              format: date-time
                              type: string
                            name:
                              description: The name of the share.
                              example: My Shared WAF Managed Rule
                              type: string
                            organization_id:
                              description: Organization identifier.
                              example: 023e105f4ecef8ad9ca31a8372d0c353
                              maxLength: 32
                              type: string
                            status:
                              enum:
                                - active
                                - deleting
                                - deleted
                              type: string
                            target_type:
                              enum:
                                - account
                                - organization
                              type: string
                          required:
                            - id
                            - name
                            - account_id
                            - account_name
                            - organization_id
                            - created
                            - modified
                            - status
                            - target_type
                        type: array
                type: object
          description: List organization shares response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful.
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - result
                    type: object
          description: List organization shares response failure.
        5XX:
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful.
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - result
                    type: object
          description: List organization shares response failure.
      security:
        - api_email: []
          api_key: []
      summary: List organization shares
      tags:
        - Resource Sharing
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
