openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/page_shield/cookies/{cookie_id}:
    get:
      description: Fetches a cookie collected by Page Shield by cookie ID.
      operationId: page-shield-get-cookie
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            description: Identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
            x-auditable: true
        - in: path
          name: cookie_id
          required: true
          schema:
            description: Identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
            x-auditable: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                        type: object
                      - properties:
                          result:
                            nullable: true
                            type: object
                    type: object
                  - properties:
                      result:
                        properties:
                          domain_attribute:
                            example: cloudflare.com
                            type: string
                          expires_attribute:
                            example: '2021-10-02T09:57:54Z'
                            format: date-time
                            type: string
                          first_seen_at:
                            example: '2021-08-18T10:51:08Z'
                            format: date-time
                            type: string
                          host:
                            example: blog.cloudflare.com
                            type: string
                          http_only_attribute:
                            example: true
                            type: boolean
                          id:
                            description: Identifier
                            example: 023e105f4ecef8ad9ca31a8372d0c353
                            maxLength: 32
                            readOnly: true
                            type: string
                            x-auditable: true
                          last_seen_at:
                            example: '2021-09-02T09:57:54Z'
                            format: date-time
                            type: string
                          max_age_attribute:
                            example: 3600
                            type: integer
                          name:
                            example: session_id
                            type: string
                          page_urls:
                            example:
                              - blog.cloudflare.com/page1
                              - blog.cloudflare.com/page2
                            items:
                              type: string
                            type: array
                          path_attribute:
                            example: /
                            type: string
                          same_site_attribute:
                            enum:
                              - lax
                              - strict
                              - none
                            example: strict
                            type: string
                          secure_attribute:
                            example: true
                            type: boolean
                          type:
                            enum:
                              - first_party
                              - unknown
                            example: first_party
                            type: string
                        required:
                          - id
                          - type
                          - name
                          - host
                          - first_seen_at
                          - last_seen_at
                    required:
                      - result
          description: Get a Page Shield cookie response
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    example: []
                    items:
                      properties:
                        code:
                          minimum: 1000
                          type: integer
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                      uniqueItems: true
                    type: array
                  messages:
                    example: []
                    items:
                      properties:
                        code:
                          minimum: 1000
                          type: integer
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                      uniqueItems: true
                    type: array
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                type: object
          description: Get a Page Shield cookie response failure
      security:
        - api_email: []
          api_key: []
      summary: Get a Page Shield cookie
      tags:
        - Page Shield
      x-api-token-group:
        - Page Shield
        - Domain Page Shield Read
        - Domain Page Shield
        - Page Shield Read
        - Zone Settings Write
        - Zone Settings Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: false
