openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/page_shield/scripts/{script_id}:
    get:
      description: Fetches a script detected by Page Shield by script ID.
      operationId: page-shield-get-script
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            description: Identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
            x-auditable: true
        - in: path
          name: script_id
          required: true
          schema:
            description: Identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
            x-auditable: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                        type: object
                      - properties:
                          result:
                            nullable: true
                            type: object
                    type: object
                  - properties:
                      result:
                        allOf:
                          - properties:
                              added_at:
                                example: '2021-08-18T10:51:10.09615Z'
                                format: date-time
                                type: string
                              cryptomining_score:
                                description: >-
                                  The cryptomining score of the JavaScript
                                  content.
                                maximum: 99
                                minimum: 1
                                nullable: true
                                type: integer
                              dataflow_score:
                                description: The dataflow score of the JavaScript content.
                                maximum: 99
                                minimum: 1
                                nullable: true
                                type: integer
                              domain_reported_malicious:
                                example: false
                                type: boolean
                              fetched_at:
                                description: >-
                                  The timestamp of when the script was last
                                  fetched.
                                nullable: true
                                type: string
                              first_page_url:
                                example: blog.cloudflare.com/page
                                type: string
                              first_seen_at:
                                example: '2021-08-18T10:51:08Z'
                                format: date-time
                                type: string
                              hash:
                                description: The computed hash of the analyzed script.
                                maxLength: 64
                                minLength: 64
                                nullable: true
                                type: string
                              host:
                                example: blog.cloudflare.com
                                type: string
                              id:
                                description: Identifier
                                example: 023e105f4ecef8ad9ca31a8372d0c353
                                maxLength: 32
                                readOnly: true
                                type: string
                                x-auditable: true
                              js_integrity_score:
                                description: The integrity score of the JavaScript content.
                                maximum: 99
                                minimum: 1
                                nullable: true
                                type: integer
                              last_seen_at:
                                example: '2021-09-02T09:57:54Z'
                                format: date-time
                                type: string
                              magecart_score:
                                description: The magecart score of the JavaScript content.
                                maximum: 99
                                minimum: 1
                                nullable: true
                                type: integer
                              malicious_domain_categories:
                                example:
                                  - Malware
                                items:
                                  type: string
                                type: array
                              malicious_url_categories:
                                example:
                                  - Malware
                                items:
                                  type: string
                                type: array
                              malware_score:
                                description: The malware score of the JavaScript content.
                                maximum: 99
                                minimum: 1
                                nullable: true
                                type: integer
                              obfuscation_score:
                                description: >-
                                  The obfuscation score of the JavaScript
                                  content.
                                maximum: 99
                                minimum: 1
                                nullable: true
                                type: integer
                              page_urls:
                                example:
                                  - blog.cloudflare.com/page1
                                  - blog.cloudflare.com/page2
                                items:
                                  type: string
                                type: array
                              url:
                                example: >-
                                  https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js
                                type: string
                              url_contains_cdn_cgi_path:
                                example: false
                                type: boolean
                              url_reported_malicious:
                                example: false
                                type: boolean
                            required:
                              - id
                              - url
                              - added_at
                              - first_seen_at
                              - last_seen_at
                              - host
                              - url_contains_cdn_cgi_path
                          - properties:
                              versions:
                                example:
                                  - cryptomining_score: 20
                                    dataflow_score: 2
                                    fetched_at: '2021-08-18T10:51:08Z'
                                    hash: >-
                                      e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b423
                                    js_integrity_score: 2
                                    magecart_score: 10
                                    malware_score: 5
                                    obfuscation_score: 10
                                items:
                                  description: The version of the analyzed script.
                                  properties:
                                    cryptomining_score:
                                      description: >-
                                        The cryptomining score of the JavaScript
                                        content.
                                      maximum: 99
                                      minimum: 1
                                      nullable: true
                                      type: integer
                                    dataflow_score:
                                      description: >-
                                        The dataflow score of the JavaScript
                                        content.
                                      maximum: 99
                                      minimum: 1
                                      nullable: true
                                      type: integer
                                    fetched_at:
                                      description: >-
                                        The timestamp of when the script was
                                        last fetched.
                                      nullable: true
                                      type: string
                                    hash:
                                      description: >-
                                        The computed hash of the analyzed
                                        script.
                                      maxLength: 64
                                      minLength: 64
                                      nullable: true
                                      type: string
                                    js_integrity_score:
                                      description: >-
                                        The integrity score of the JavaScript
                                        content.
                                      maximum: 99
                                      minimum: 1
                                      nullable: true
                                      type: integer
                                    magecart_score:
                                      description: >-
                                        The magecart score of the JavaScript
                                        content.
                                      maximum: 99
                                      minimum: 1
                                      nullable: true
                                      type: integer
                                    malware_score:
                                      description: >-
                                        The malware score of the JavaScript
                                        content.
                                      maximum: 99
                                      minimum: 1
                                      nullable: true
                                      type: integer
                                    obfuscation_score:
                                      description: >-
                                        The obfuscation score of the JavaScript
                                        content.
                                      maximum: 99
                                      minimum: 1
                                      nullable: true
                                      type: integer
                                  type: object
                                nullable: true
                                type: array
                    required:
                      - result
          description: Get a Page Shield script response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      messages:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                    type: object
          description: Get a Page Shield script response failure
      security:
        - api_email: []
          api_key: []
      summary: Get a Page Shield script
      tags:
        - Page Shield
      x-api-token-group:
        - Page Shield
        - Domain Page Shield Read
        - Domain Page Shield
        - Page Shield Read
        - Zone Settings Write
        - Zone Settings Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: true
