openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/cloudforce-one/events/{event_id}:
    post:
      operationId: post_EventUpdate
      parameters:
        - description: Account ID.
          in: path
          name: account_id
          required: true
          schema:
            description: Account ID.
            type: number
        - description: Event UUID.
          in: path
          name: event_id
          required: true
          schema:
            description: Event UUID.
            type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                attacker:
                  example: Flying Yeti
                  type: string
                attackerCountry:
                  example: CN
                  type: string
                category:
                  example: Domain Resolution
                  type: string
                date:
                  example: '2022-04-01T00:00:00Z'
                  format: date-time
                  type: string
                event:
                  example: An attacker registered the domain domain.com
                  type: string
                indicator:
                  example: domain2.com
                  type: string
                indicatorType:
                  example: sha256
                  type: string
                insight:
                  example: new insight
                  type: string
                raw:
                  properties:
                    data:
                      additionalProperties: true
                      nullable: true
                      type: object
                    source:
                      example: example.com
                      type: string
                    tlp:
                      example: amber
                      type: string
                  type: object
                targetCountry:
                  example: US
                  type: string
                targetIndustry:
                  example: Insurance
                  type: string
                tlp:
                  example: amber
                  type: string
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  accountId:
                    example: 1234
                    type: number
                  attacker:
                    example: Flying Yeti
                    type: string
                  attackerCountry:
                    example: CN
                    type: string
                  category:
                    example: Domain Resolution
                    type: string
                  date:
                    example: '2022-04-01T00:00:00Z'
                    type: string
                  event:
                    example: An attacker registered the domain domain.com
                    type: string
                  id:
                    example: 1223
                    type: number
                  indicator:
                    example: domain
                    type: string
                  indicatorType:
                    example: domain
                    type: string
                  indicatorTypeId:
                    example: 5
                    type: number
                  insight:
                    type: string
                  killChain:
                    type: number
                  mitreAttack:
                    items:
                      example: ' '
                      type: string
                    type: array
                  numReferenced:
                    type: number
                  numReferences:
                    type: number
                  rawId:
                    example: 453gw34w3
                    type: string
                  referenced:
                    items:
                      example: ' '
                      type: string
                    type: array
                  referencedIds:
                    items:
                      type: number
                    type: array
                  references:
                    items:
                      example: ' '
                      type: string
                    type: array
                  referencesIds:
                    items:
                      type: number
                    type: array
                  releasabilityId:
                    type: string
                  tags:
                    items:
                      example: malware
                      type: string
                    type: array
                  targetCountry:
                    example: US
                    type: string
                  targetIndustry:
                    example: Agriculture
                    type: string
                  tlp:
                    example: amber
                    type: string
                  uuid:
                    example: 12345678-1234-1234-1234-1234567890ab
                    type: string
                required:
                  - id
                  - uuid
                  - accountId
                  - date
                  - targetCountry
                  - attacker
                  - attackerCountry
                  - targetIndustry
                  - rawId
                  - indicatorTypeId
                  - indicator
                  - event
                  - numReferenced
                  - numReferences
                  - tlp
                  - category
                  - indicatorType
                  - referenced
                  - references
                  - tags
                  - killChain
                  - mitreAttack
                  - referencedIds
                  - referencesIds
                type: object
          description: Returns the updated event.
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          example: An error occurred.
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  result:
                    type: object
                  success:
                    type: boolean
                required:
                  - result
                  - success
                  - errors
                type: object
          description: Bad Request.
      security:
        - api_token: []
      summary: Updates an event
      tags:
        - Event
      x-api-token-group:
        - Cloudforce One Write
        - Cloudforce One Read
