openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/queues/{queue_id}/messages/pull:
    post:
      description: Pull a batch of messages from a Queue
      operationId: queues-pull-messages
      parameters:
        - in: path
          name: queue_id
          required: true
          schema:
            description: A Resource identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
            x-auditable: true
        - in: path
          name: account_id
          required: true
          schema:
            description: A Resource identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
            x-auditable: true
      requestBody:
        content:
          application/json:
            schema:
              properties:
                batch_size:
                  description: The maximum number of messages to include in a batch.
                  example: 50
                  type: number
                  x-auditable: true
                visibility_timeout_ms:
                  description: >-
                    The number of milliseconds that a message is exclusively
                    leased. After the timeout, the message becomes available for
                    another attempt.
                  example: 6000
                  type: number
                  x-auditable: true
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        example:
                          - code: 7003
                            message: No route for the URI
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                              x-auditable: true
                            message:
                              type: string
                              x-auditable: true
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        minLength: 1
                        type: array
                      messages:
                        example: []
                        items:
                          type: string
                          x-auditable: true
                        type: array
                      success:
                        description: Indicates if the API call was successful or not.
                        enum:
                          - true
                        type: boolean
                        x-auditable: true
                    type: object
                  - properties:
                      result:
                        properties:
                          message_backlog_count:
                            description: The number of unacknowledged messages in the queue
                            example: 5
                            type: number
                          messages:
                            items:
                              properties:
                                attempts:
                                  example: 1
                                  readOnly: true
                                  type: number
                                  x-auditable: true
                                body:
                                  example: hello world
                                  readOnly: true
                                  type: string
                                id:
                                  example: b01b5594f784d0165c2985833f5660dd
                                  readOnly: true
                                  type: string
                                  x-auditable: true
                                lease_id:
                                  description: >-
                                    An ID that represents an "in-flight" message
                                    that has been pulled from a Queue. You must
                                    hold on to this ID and use it to acknowledge
                                    this message.
                                  example: >-
                                    eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIn0..Q8p21d7dceR6vUfwftONdQ.JVqZgAS-Zk7MqmqccYtTHeeMElNHaOMigeWdb8LyMOg.T2_HV99CYzGaQuhTyW8RsgbnpTRZHRM6N7UoSaAKeK0
                                  type: string
                                  x-auditable: true
                                metadata:
                                  example:
                                    CF-Content-Type: text
                                    CF-sourceMessageSource: dash
                                  readOnly: true
                                  type: object
                                timestamp_ms:
                                  example: 1710950954154
                                  readOnly: true
                                  type: number
                                  x-auditable: true
                              type: object
                            type: array
                        type: object
                    type: object
                type: object
          description: A batch of messages in the Queue
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    example:
                      - code: 7003
                        message: No route for the URI
                    items:
                      properties:
                        code:
                          minimum: 1000
                          type: integer
                          x-auditable: true
                        message:
                          type: string
                          x-auditable: true
                      required:
                        - code
                        - message
                      type: object
                      uniqueItems: true
                    minLength: 1
                    type: array
                  messages:
                    example: []
                    items:
                      type: string
                      x-auditable: true
                    type: array
                  success:
                    description: Indicates if the API call was successful or not.
                    enum:
                      - false
                    example: false
                    type: boolean
                    x-auditable: true
                type: object
          description: Failure response
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Pull Queue Messages
      tags:
        - Queue
      x-api-token-group:
        - Queues Write
        - Workers Scripts Write
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.edge.worker.queue.update
