openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/queues/{queue_id}:
    get:
      description: Get details about a specific queue.
      operationId: queues-get
      parameters:
        - in: path
          name: queue_id
          required: true
          schema:
            description: A Resource identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
            x-auditable: true
        - in: path
          name: account_id
          required: true
          schema:
            description: A Resource identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
            x-auditable: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        example:
                          - code: 7003
                            message: No route for the URI
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                              x-auditable: true
                            message:
                              type: string
                              x-auditable: true
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        minLength: 1
                        type: array
                      messages:
                        example: []
                        items:
                          type: string
                          x-auditable: true
                        type: array
                      success:
                        description: Indicates if the API call was successful or not.
                        enum:
                          - true
                        type: boolean
                        x-auditable: true
                    type: object
                  - properties:
                      result:
                        properties:
                          consumers:
                            items:
                              oneOf:
                                - properties:
                                    consumer_id:
                                      description: A Resource identifier.
                                      example: 023e105f4ecef8ad9ca31a8372d0c353
                                      maxLength: 32
                                      readOnly: true
                                      type: string
                                      x-auditable: true
                                    created_on:
                                      readOnly: true
                                      type: string
                                      x-auditable: true
                                    queue_id:
                                      description: A Resource identifier.
                                      example: 023e105f4ecef8ad9ca31a8372d0c353
                                      maxLength: 32
                                      readOnly: true
                                      type: string
                                      x-auditable: true
                                    script:
                                      allOf:
                                        - description: Name of a Worker
                                          example: my-consumer-worker
                                          type: string
                                          x-auditable: true
                                        - readOnly: true
                                          type: string
                                      type: object
                                    script_name:
                                      allOf:
                                        - description: Name of a Worker
                                          example: my-consumer-worker
                                          type: string
                                          x-auditable: true
                                        - type: string
                                          writeOnly: true
                                      type: object
                                      x-auditable: true
                                    settings:
                                      properties:
                                        batch_size:
                                          description: >-
                                            The maximum number of messages to
                                            include in a batch.
                                          example: 50
                                          type: number
                                          x-auditable: true
                                        max_concurrency:
                                          description: >-
                                            Maximum number of concurrent consumers
                                            that may consume from this Queue. Set to
                                            `null` to automatically opt in to the
                                            platform's maximum (recommended).
                                          example: 10
                                          type: number
                                          x-auditable: true
                                        max_retries:
                                          description: The maximum number of retries
                                          example: 3
                                          type: number
                                          x-auditable: true
                                        max_wait_time_ms:
                                          description: >-
                                            The number of milliseconds to wait for a
                                            batch to fill up before attempting to
                                            deliver it
                                          example: 5000
                                          type: number
                                          x-auditable: true
                                        retry_delay:
                                          description: >-
                                            The number of seconds to delay before
                                            making the message available for another
                                            attempt.
                                          example: 10
                                          type: number
                                          x-auditable: true
                                      type: object
                                    type:
                                      enum:
                                        - worker
                                      type: string
                                      x-auditable: true
                                  type: object
                                - properties:
                                    consumer_id:
                                      description: A Resource identifier.
                                      example: 023e105f4ecef8ad9ca31a8372d0c353
                                      maxLength: 32
                                      readOnly: true
                                      type: string
                                      x-auditable: true
                                    created_on:
                                      readOnly: true
                                      type: string
                                      x-auditable: true
                                    queue_id:
                                      description: A Resource identifier.
                                      example: 023e105f4ecef8ad9ca31a8372d0c353
                                      maxLength: 32
                                      readOnly: true
                                      type: string
                                      x-auditable: true
                                    settings:
                                      properties:
                                        batch_size:
                                          description: >-
                                            The maximum number of messages to
                                            include in a batch.
                                          example: 50
                                          type: number
                                          x-auditable: true
                                        max_retries:
                                          description: The maximum number of retries
                                          example: 3
                                          type: number
                                          x-auditable: true
                                        retry_delay:
                                          description: >-
                                            The number of seconds to delay before
                                            making the message available for another
                                            attempt.
                                          example: 10
                                          type: number
                                          x-auditable: true
                                        visibility_timeout_ms:
                                          description: >-
                                            The number of milliseconds that a
                                            message is exclusively leased. After the
                                            timeout, the message becomes available
                                            for another attempt.
                                          example: 6000
                                          type: number
                                          x-auditable: true
                                      type: object
                                    type:
                                      enum:
                                        - http_pull
                                      type: string
                                      x-auditable: true
                                  type: object
                              type: object
                            readOnly: true
                            type: array
                          consumers_total_count:
                            readOnly: true
                            type: number
                          created_on:
                            readOnly: true
                            type: string
                            x-auditable: true
                          modified_on:
                            readOnly: true
                            type: string
                            x-auditable: true
                          producers:
                            items:
                              oneOf:
                                - properties:
                                    script:
                                      type: string
                                      x-auditable: true
                                    type:
                                      enum:
                                        - worker
                                      type: string
                                      x-auditable: true
                                  type: object
                                - properties:
                                    bucket_name:
                                      type: string
                                      x-auditable: true
                                    type:
                                      enum:
                                        - r2_bucket
                                      type: string
                                      x-auditable: true
                                  type: object
                              type: object
                            readOnly: true
                            type: array
                          producers_total_count:
                            readOnly: true
                            type: number
                            x-auditable: true
                          queue_id:
                            readOnly: true
                            type: string
                            x-auditable: true
                          queue_name:
                            example: example-queue
                            type: string
                            x-auditable: true
                          settings:
                            properties:
                              delivery_delay:
                                description: >-
                                  Number of seconds to delay delivery of all
                                  messages to consumers.
                                example: 5
                                type: number
                                x-auditable: true
                              delivery_paused:
                                description: >-
                                  Indicates if message delivery to consumers is
                                  currently paused.
                                example: true
                                type: boolean
                                x-auditable: true
                              message_retention_period:
                                description: >-
                                  Number of seconds after which an unconsumed
                                  message will be delayed.
                                example: 345600
                                type: number
                                x-auditable: true
                            type: object
                        type: object
                    type: object
                type: object
          description: Details of the requested Queue
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    example:
                      - code: 7003
                        message: No route for the URI
                    items:
                      properties:
                        code:
                          minimum: 1000
                          type: integer
                          x-auditable: true
                        message:
                          type: string
                          x-auditable: true
                      required:
                        - code
                        - message
                      type: object
                      uniqueItems: true
                    minLength: 1
                    type: array
                  messages:
                    example: []
                    items:
                      type: string
                      x-auditable: true
                    type: array
                  success:
                    description: Indicates if the API call was successful or not.
                    enum:
                      - false
                    example: false
                    type: boolean
                    x-auditable: true
                type: object
          description: Failure response
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get Queue
      tags:
        - Queue
      x-api-token-group:
        - Queues Write
        - Queues Read
        - Workers Scripts Write
        - Workers Scripts Read
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.edge.worker.queue.read
