openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/r2/temp-access-credentials:
    post:
      description: >-
        Creates temporary access credentials on a bucket that can be optionally
        scoped to prefixes or objects.
      operationId: r2-create-temp-access-credentials
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Account ID.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
      requestBody:
        content:
          application/json:
            schema:
              example:
                bucket: example-bucket
                objects:
                  - example-object
                parentAccessKeyId: example-access-key-id
                permission: object-read-write
                prefixes:
                  - example-prefix/
                ttlSeconds: 3600
              properties:
                bucket:
                  description: Name of the R2 bucket.
                  type: string
                  x-auditable: true
                objects:
                  description: Optional object paths to scope the credentials to.
                  items:
                    type: string
                    x-auditable: true
                  type: array
                parentAccessKeyId:
                  description: The parent access key id to use for signing.
                  type: string
                permission:
                  description: Permissions allowed on the credentials.
                  enum:
                    - admin-read-write
                    - admin-read-only
                    - object-read-write
                    - object-read-only
                  type: string
                  x-auditable: true
                prefixes:
                  description: Optional prefix paths to scope the credentials to.
                  items:
                    type: string
                    x-auditable: true
                  type: array
                ttlSeconds:
                  default: 900
                  description: How long the credentials will live for in seconds.
                  maximum: 604800
                  type: number
                  x-auditable: true
              required:
                - bucket
                - permission
                - ttlSeconds
                - parentAccessKeyId
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      messages:
                        items:
                          type: string
                        type: array
                      result:
                        type: object
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - true
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
                  - properties:
                      result:
                        example:
                          accessKeyId: example-access-key-id
                          secretAccessKey: example-secret-key
                          sessionToken: example-session-token
                        properties:
                          accessKeyId:
                            description: ID for new access key.
                            type: string
                          secretAccessKey:
                            description: Secret access key.
                            type: string
                            x-sensitive: true
                          sessionToken:
                            description: Security token.
                            type: string
                            x-sensitive: true
                        type: object
                    type: object
          description: Create temporary access credentials response.
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        code:
                          minimum: 1000
                          type: integer
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                      uniqueItems: true
                    type: array
                  messages:
                    items:
                      type: string
                    type: array
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: Create temporary access credentials response failure.
      security:
        - api_token: []
      summary: Create Temporary Access Credentials
      tags:
        - R2 Bucket
