openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/r2/buckets/{bucket_name}/domains/custom/{domain}:
    put:
      description: Edit the configuration for a custom domain on an existing R2 bucket.
      operationId: r2-edit-custom-domain-settings
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Account ID.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
        - in: path
          name: bucket_name
          required: true
          schema:
            description: Name of the bucket.
            example: example-bucket
            maxLength: 64
            minLength: 3
            pattern: ^[a-z0-9][a-z0-9-]*[a-z0-9]
            type: string
            x-auditable: true
        - in: path
          name: domain
          required: true
          schema:
            description: Name of the custom domain.
            example: example-domain/custom-domain.com
            type: string
            x-auditable: true
        - in: header
          name: cf-r2-jurisdiction
          schema:
            default: default
            description: >-
              Jurisdiction where objects in this bucket are guaranteed to be
              stored.
            enum:
              - default
              - eu
              - fedramp
            type: string
            x-auditable: true
            x-stainless-param: jurisdiction
      requestBody:
        content:
          application/json:
            schema:
              example:
                enabled: true
                minTLS: '1.2'
              properties:
                enabled:
                  description: >-
                    Whether to enable public bucket access at the specified
                    custom domain.
                  type: boolean
                  x-auditable: true
                minTLS:
                  description: >-
                    Minimum TLS Version the custom domain will accept for
                    incoming connections. If not set, defaults to previous
                    value.
                  enum:
                    - '1.0'
                    - '1.1'
                    - '1.2'
                    - '1.3'
                  type: string
                  x-auditable: true
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      messages:
                        items:
                          type: string
                        type: array
                      result:
                        type: object
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - true
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
                  - properties:
                      result:
                        allOf:
                          - example:
                              domain: example-domain.com
                              enabled: true
                            properties:
                              domain:
                                description: Domain name of the affected custom domain.
                                type: string
                                x-auditable: true
                              enabled:
                                description: >-
                                  Whether this bucket is publicly accessible at
                                  the specified custom domain.
                                type: boolean
                                x-auditable: true
                              minTLS:
                                description: >-
                                  Minimum TLS Version the custom domain will
                                  accept for incoming connections. If not set,
                                  defaults to 1.0.
                                enum:
                                  - '1.0'
                                  - '1.1'
                                  - '1.2'
                                  - '1.3'
                                type: string
                                x-auditable: true
                            required:
                              - domain
                            type: object
                    type: object
          description: Edit Custom Domain Configuration response.
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        code:
                          minimum: 1000
                          type: integer
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                      uniqueItems: true
                    type: array
                  messages:
                    items:
                      type: string
                    type: array
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: Edit Custom Domain Configuration response failure.
      security:
        - api_token: []
      summary: Configure Custom Domain Settings
      tags:
        - R2 Bucket
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.edge.r2.bucket.write
