openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/r2/buckets:
    get:
      description: Lists all R2 buckets on your account.
      operationId: r2-list-buckets
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Account ID.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
        - in: query
          name: name_contains
          schema:
            description: >-
              Bucket names to filter by. Only buckets with this phrase in their
              name will be returned.
            example: my-bucket
            type: string
        - in: query
          name: start_after
          schema:
            description: >-
              Bucket name to start searching after. Buckets are ordered
              lexicographically.
            example: my-bucket
            type: string
        - in: query
          name: per_page
          schema:
            default: 20
            description: Maximum number of buckets to return in a single call.
            maximum: 1000
            minimum: 1
            type: number
        - in: query
          name: order
          schema:
            description: Field to order buckets by.
            enum:
              - name
            type: string
        - in: query
          name: direction
          schema:
            description: Direction to order buckets.
            enum:
              - asc
              - desc
            example: desc
            type: string
        - in: query
          name: cursor
          schema:
            description: >-
              Pagination cursor received during the last List Buckets call. R2
              buckets are paginated using cursors instead of page numbers.
            type: string
        - in: header
          name: cf-r2-jurisdiction
          schema:
            default: default
            description: >-
              Jurisdiction where objects in this bucket are guaranteed to be
              stored.
            enum:
              - default
              - eu
              - fedramp
            type: string
            x-auditable: true
            x-stainless-param: jurisdiction
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            items:
                              type: string
                            type: array
                          result:
                            type: object
                          success:
                            description: Whether the API call was successful.
                            enum:
                              - true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                          - result
                        type: object
                      - properties:
                          result_info:
                            properties:
                              cursor:
                                description: >-
                                  A continuation token that should be used to
                                  fetch the next page of results.
                                example: >-
                                  1-JTdCJTIydiUyMiUzQTElMkMlMjJzdGFydEFmdGVyJTIyJTNBJTIyZGF2aWRwdWJsaWMlMjIlN0Q=
                                type: string
                              per_page:
                                description: Maximum number of results on this page.
                                example: 20
                                type: number
                            type: object
                        type: object
                  - properties:
                      result:
                        properties:
                          buckets:
                            items:
                              description: A single R2 bucket.
                              properties:
                                creation_date:
                                  description: Creation timestamp.
                                  type: string
                                jurisdiction:
                                  default: default
                                  description: >-
                                    Jurisdiction where objects in this bucket
                                    are guaranteed to be stored.
                                  enum:
                                    - default
                                    - eu
                                    - fedramp
                                  type: string
                                  x-auditable: true
                                  x-stainless-param: jurisdiction
                                location:
                                  description: Location of the bucket.
                                  enum:
                                    - apac
                                    - eeur
                                    - enam
                                    - weur
                                    - wnam
                                    - oc
                                  type: string
                                  x-auditable: true
                                  x-stainless-terraform-configurability: computed_optional
                                name:
                                  description: Name of the bucket.
                                  example: example-bucket
                                  maxLength: 64
                                  minLength: 3
                                  pattern: ^[a-z0-9][a-z0-9-]*[a-z0-9]
                                  type: string
                                  x-auditable: true
                                storage_class:
                                  default: Standard
                                  description: >-
                                    Storage class for newly uploaded objects,
                                    unless specified otherwise.
                                  enum:
                                    - Standard
                                    - InfrequentAccess
                                  type: string
                                  x-auditable: true
                              type: object
                            type: array
                        type: object
                    type: object
          description: List Buckets response.
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        code:
                          minimum: 1000
                          type: integer
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                      uniqueItems: true
                    type: array
                  messages:
                    items:
                      type: string
                    type: array
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: List Buckets response failure.
      security:
        - api_token: []
      summary: List Buckets
      tags:
        - R2 Bucket
      x-api-token-group:
        - Workers R2 Storage Write
        - Workers R2 Storage Read
