openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /radar/email/routing/timeseries_groups/ip_version:
    get:
      description: Retrieves the distribution of emails by IP version over time.
      operationId: radar-get-email-routing-timeseries-group-by-ip-version
      parameters:
        - description: >-
            Aggregation interval of the results (e.g., in 15 minutes or 1 hour
            intervals). Refer to [Aggregation
            intervals](https://developers.cloudflare.com/radar/concepts/aggregation-intervals/).
          in: query
          name: aggInterval
          schema:
            description: >-
              Aggregation interval of the results (e.g., in 15 minutes or 1 hour
              intervals). Refer to [Aggregation
              intervals](https://developers.cloudflare.com/radar/concepts/aggregation-intervals/).
            enum:
              - 15m
              - 1h
              - 1d
              - 1w
            example: 1h
            type: string
        - description: Array of names used to label the series in the response.
          in: query
          name: name
          schema:
            description: Array of names used to label the series in the response.
            items:
              example: main_series
              type: string
            type: array
        - description: >-
            Filters results by date range. For example, use `7d` and `7dcontrol`
            to compare this week with the previous week. Use this parameter or
            set specific start and end dates (`dateStart` and `dateEnd`
            parameters).
          in: query
          name: dateRange
          schema:
            description: >-
              Filters results by date range. For example, use `7d` and
              `7dcontrol` to compare this week with the previous week. Use this
              parameter or set specific start and end dates (`dateStart` and
              `dateEnd` parameters).
            example: 7d
            items:
              example: 7d
              pattern: >-
                ^((([1-9]|[1-9][0-9]|[1-2][0-9][0-9]|3[0-5][0-9]|36[0-4])[d](control)?)|(([1-9]|[1-4][0-9]|5[0-2])[w](control)?))$
              type: string
            type: array
        - description: Start of the date range.
          in: query
          name: dateStart
          schema:
            description: Start of the date range.
            example: '2023-09-01T11:41:33.782Z'
            items:
              format: date-time
              type: string
            type: array
        - description: End of the date range (inclusive).
          in: query
          name: dateEnd
          schema:
            description: End of the date range (inclusive).
            example: '2023-09-01T11:41:33.782Z'
            items:
              format: date-time
              type: string
            type: array
        - description: Filters results by ARC (Authenticated Received Chain) validation.
          in: query
          name: arc
          schema:
            description: Filters results by ARC (Authenticated Received Chain) validation.
            example: PASS
            items:
              enum:
                - PASS
                - NONE
                - FAIL
              type: string
            type: array
        - description: >-
            Filters results by DKIM (DomainKeys Identified Mail) validation
            status.
          in: query
          name: dkim
          schema:
            description: >-
              Filters results by DKIM (DomainKeys Identified Mail) validation
              status.
            example: PASS
            items:
              enum:
                - PASS
                - NONE
                - FAIL
              type: string
            type: array
        - description: >-
            Filters results by DMARC (Domain-based Message Authentication,
            Reporting and Conformance) validation status.
          in: query
          name: dmarc
          schema:
            description: >-
              Filters results by DMARC (Domain-based Message Authentication,
              Reporting and Conformance) validation status.
            example: PASS
            items:
              enum:
                - PASS
                - NONE
                - FAIL
              type: string
            type: array
        - description: Filters results by SPF (Sender Policy Framework) validation status.
          in: query
          name: spf
          schema:
            description: >-
              Filters results by SPF (Sender Policy Framework) validation
              status.
            example: PASS
            items:
              enum:
                - PASS
                - NONE
                - FAIL
              type: string
            type: array
        - description: Filters results by encryption status (encrypted vs. not-encrypted).
          in: query
          name: encrypted
          schema:
            description: >-
              Filters results by encryption status (encrypted vs.
              not-encrypted).
            example: ENCRYPTED
            items:
              enum:
                - ENCRYPTED
                - NOT_ENCRYPTED
              type: string
            type: array
        - description: Format in which results will be returned.
          in: query
          name: format
          schema:
            description: Format in which results will be returned.
            enum:
              - JSON
              - CSV
            example: json
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  result:
                    properties:
                      meta:
                        description: Metadata for the results.
                        properties:
                          aggInterval:
                            description: >-
                              Aggregation interval of the results (e.g., in 15
                              minutes or 1 hour intervals). Refer to
                              [Aggregation
                              intervals](https://developers.cloudflare.com/radar/concepts/aggregation-intervals/).
                            enum:
                              - FIFTEEN_MINUTES
                              - ONE_HOUR
                              - ONE_DAY
                              - ONE_WEEK
                              - ONE_MONTH
                            type: string
                          confidenceInfo:
                            properties:
                              annotations:
                                items:
                                  description: >-
                                    Annotation associated with the result (e.g.
                                    outage or other type of event).
                                  properties:
                                    dataSource:
                                      example: ALL
                                      type: string
                                    description:
                                      example: Cable cut in Tonga
                                      type: string
                                    endDate:
                                      format: date-time
                                      type: string
                                    eventType:
                                      example: OUTAGE
                                      type: string
                                    isInstantaneous:
                                      description: >-
                                        Whether event is a single point in time
                                        or a time range.
                                      type: boolean
                                    linkedUrl:
                                      format: uri
                                      type: string
                                    startDate:
                                      format: date-time
                                      type: string
                                  required:
                                    - dataSource
                                    - eventType
                                    - description
                                    - startDate
                                    - endDate
                                    - linkedUrl
                                    - isInstantaneous
                                  type: object
                                type: array
                              level:
                                description: >-
                                  Provides an indication of how much confidence
                                  Cloudflare has in the data.
                                type: integer
                            required:
                              - level
                              - annotations
                            type: object
                          dateRange:
                            items:
                              properties:
                                endTime:
                                  description: Adjusted end of date range.
                                  example: '2022-09-17T10:22:57.555Z'
                                  format: date-time
                                  type: string
                                startTime:
                                  description: Adjusted start of date range.
                                  example: '2022-09-16T10:22:57.555Z'
                                  format: date-time
                                  type: string
                              required:
                                - startTime
                                - endTime
                              type: object
                            type: array
                          lastUpdated:
                            description: Timestamp of the last dataset update.
                            format: date-time
                            type: string
                          normalization:
                            description: >-
                              Normalization method applied to the results. Refer
                              to [Normalization
                              methods](https://developers.cloudflare.com/radar/concepts/normalization/).
                            enum:
                              - PERCENTAGE
                              - MIN0_MAX
                              - MIN_MAX
                              - RAW_VALUES
                              - PERCENTAGE_CHANGE
                              - ROLLING_AVERAGE
                              - OVERLAPPED_PERCENTAGE
                              - RATIO
                            type: string
                          units:
                            description: Measurement units for the results.
                            items:
                              properties:
                                name:
                                  example: '*'
                                  type: string
                                value:
                                  example: requests
                                  type: string
                              required:
                                - name
                                - value
                              type: object
                            type: array
                        required:
                          - dateRange
                          - confidenceInfo
                          - normalization
                          - lastUpdated
                          - units
                          - aggInterval
                        type: object
                      serie_0:
                        properties:
                          IPv4:
                            items:
                              description: A numeric string.
                              example: '10'
                              pattern: ^\d+$
                              type: string
                            type: array
                          IPv6:
                            items:
                              description: A numeric string.
                              example: '10'
                              pattern: ^\d+$
                              type: string
                            type: array
                        required:
                          - IPv4
                          - IPv6
                        type: object
                    required:
                      - serie_0
                      - meta
                    type: object
                  success:
                    example: true
                    type: boolean
                required:
                  - result
                  - success
                type: object
          description: Successful response.
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  result:
                    type: object
                  success:
                    example: false
                    type: boolean
                required:
                  - result
                  - success
                  - errors
                type: object
          description: Bad request.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get email IP version time series
      tags:
        - Radar Email Routing
      x-api-token-group:
        - User Details Write
        - User Details Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
