openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /radar/bots/{bot_slug}:
    get:
      description: Retrieves the requested bot information.
      operationId: radar-get-bot-details
      parameters:
        - description: Bot slug.
          in: path
          name: bot_slug
          required: true
          schema:
            description: Bot slug.
            example: gptbot
            type: string
        - description: Format in which results will be returned.
          in: query
          name: format
          schema:
            description: Format in which results will be returned.
            enum:
              - JSON
              - CSV
            example: json
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  result:
                    properties:
                      bot:
                        properties:
                          category:
                            description: The category of the bot.
                            example: AI_CRAWLER
                            type: string
                          description:
                            description: A summary for the bot (e.g., purpose).
                            example: OpenAI/ChatGPT's web crawler
                            type: string
                          name:
                            description: The name of the bot.
                            example: GPTBot
                            type: string
                          operator:
                            description: The organization that owns and operates the bot.
                            example: OpenAI
                            type: string
                          operatorUrl:
                            description: The link to the bot documentation.
                            example: https://platform.openai.com/docs/bots
                            type: string
                          slug:
                            description: A kebab-case identifier derived from the bot name.
                            example: gptbot
                            type: string
                          userAgentPatterns:
                            items:
                              description: >-
                                User agent patterns that identify the bot in web
                                traffic.
                              example: GPTBot
                              type: string
                            type: array
                          userAgents:
                            items:
                              description: >-
                                User agent strings used by this bot in HTTP
                                requests.
                              example: GPTBot
                              type: string
                            type: array
                        required:
                          - slug
                          - name
                          - description
                          - operator
                          - operatorUrl
                          - category
                          - userAgents
                          - userAgentPatterns
                        type: object
                    required:
                      - bot
                    type: object
                  success:
                    example: true
                    type: boolean
                required:
                  - result
                  - success
                type: object
          description: Successful response.
        '404':
          content:
            application/json:
              schema:
                properties:
                  error:
                    example: Not Found.
                    type: string
                required:
                  - error
                type: object
          description: Not found.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get bot details
      tags:
        - Radar Bots
      x-api-token-group:
        - User Details Write
        - User Details Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
