openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /radar/bgp/routes/ases:
    get:
      description: >-
        Retrieves all ASes in the current global routing tables with routing
        statistics.
      operationId: radar-get-bgp-routes-asns
      parameters:
        - description: Filters results by location. Specify an alpha-2 location code.
          in: query
          name: location
          schema:
            description: Filters results by location. Specify an alpha-2 location code.
            example: US
            type: string
        - description: Limits the number of objects returned in the response.
          in: query
          name: limit
          schema:
            description: Limits the number of objects returned in the response.
            example: 5
            type: integer
        - description: Sorts results by the specified field.
          in: query
          name: sortBy
          schema:
            description: Sorts results by the specified field.
            enum:
              - cone
              - pfxs
              - ipv4
              - ipv6
              - rpki_valid
              - rpki_invalid
              - rpki_unknown
            example: ipv4
            type: string
        - description: Sort order.
          in: query
          name: sortOrder
          schema:
            description: Sort order.
            enum:
              - ASC
              - DESC
            example: desc
            type: string
        - description: Format in which results will be returned.
          in: query
          name: format
          schema:
            description: Format in which results will be returned.
            enum:
              - JSON
              - CSV
            example: json
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  result:
                    properties:
                      asns:
                        items:
                          properties:
                            asn:
                              type: integer
                            coneSize:
                              description: AS's customer cone size.
                              type: integer
                            country:
                              description: Alpha-2 code for the AS's registration country.
                              example: US
                              type: string
                            ipv4Count:
                              description: Number of IPv4 addresses originated by the AS.
                              type: integer
                            ipv6Count:
                              description: Number of IPv6 addresses originated by the AS.
                              example: '1.21e24'
                              type: string
                            name:
                              description: Name of the AS.
                              type: string
                            pfxsCount:
                              description: >-
                                Number of total IP prefixes originated by the
                                AS.
                              type: integer
                            rpkiInvalid:
                              description: >-
                                Number of RPKI invalid prefixes originated by
                                the AS.
                              type: integer
                            rpkiUnknown:
                              description: >-
                                Number of RPKI unknown prefixes originated by
                                the AS.
                              type: integer
                            rpkiValid:
                              description: >-
                                Number of RPKI valid prefixes originated by the
                                AS.
                              type: integer
                          required:
                            - asn
                            - name
                            - coneSize
                            - country
                            - ipv4Count
                            - ipv6Count
                            - pfxsCount
                            - rpkiValid
                            - rpkiInvalid
                            - rpkiUnknown
                          type: object
                        type: array
                      meta:
                        properties:
                          dataTime:
                            description: The timestamp of when the data is generated.
                            example: '2024-06-03T14:00:00'
                            type: string
                          queryTime:
                            description: The timestamp of the query.
                            example: '2024-06-03T14:00:00'
                            type: string
                          totalPeers:
                            description: >-
                              Total number of route collector peers used to
                              generate this data.
                            type: integer
                        required:
                          - dataTime
                          - queryTime
                          - totalPeers
                        type: object
                    required:
                      - asns
                      - meta
                    type: object
                  success:
                    example: true
                    type: boolean
                required:
                  - result
                  - success
                type: object
          description: Successful response.
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  result:
                    type: object
                  success:
                    example: false
                    type: boolean
                required:
                  - result
                  - success
                  - errors
                type: object
          description: Bad request.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List ASes from global routing tables
      tags:
        - Radar BGP
      x-api-token-group:
        - User Details Write
        - User Details Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
