openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /radar/ranking/domain/{domain}:
    get:
      description: >-
        Retrieves domain rank details. Cloudflare provides an ordered rank for
        the top 100 domains, but for the remainder it only provides ranking
        buckets like top 200 thousand, top one million, etc.. These are
        available through Radar datasets endpoints.
      operationId: radar-get-ranking-domain-details
      parameters:
        - description: Domain name.
          in: path
          name: domain
          required: true
          schema:
            description: Domain name.
            example: google.com
            pattern: >-
              ^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9-]*[A-Za-z0-9])$
            type: string
        - description: Limits the number of objects returned in the response.
          in: query
          name: limit
          schema:
            description: Limits the number of objects returned in the response.
            example: 5
            type: integer
        - description: The ranking type.
          in: query
          name: rankingType
          schema:
            default: POPULAR
            description: The ranking type.
            enum:
              - POPULAR
              - TRENDING_RISE
              - TRENDING_STEADY
            example: POPULAR
            type: string
        - description: Array of names used to label the series in the response.
          in: query
          name: name
          schema:
            description: Array of names used to label the series in the response.
            items:
              example: main_series
              type: string
            type: array
        - description: Includes top locations in the response.
          in: query
          name: includeTopLocations
          schema:
            description: Includes top locations in the response.
            type: boolean
        - description: Filters results by the specified array of dates.
          in: query
          name: date
          schema:
            description: Filters results by the specified array of dates.
            example: '2022-09-19'
            items:
              format: date
              type: string
            type: array
        - description: Format in which results will be returned.
          in: query
          name: format
          schema:
            description: Format in which results will be returned.
            enum:
              - JSON
              - CSV
            example: json
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  result:
                    properties:
                      details_0:
                        properties:
                          bucket:
                            description: >-
                              Only available in POPULAR ranking for the most
                              recent ranking.
                            example: '2000'
                            type: string
                          categories:
                            items:
                              properties:
                                id:
                                  example: 81
                                  type: integer
                                name:
                                  example: Content Servers
                                  type: string
                                superCategoryId:
                                  example: 26
                                  type: integer
                              required:
                                - superCategoryId
                                - name
                                - id
                              type: object
                            type: array
                          rank:
                            example: 3
                            type: integer
                          top_locations:
                            items:
                              properties:
                                locationCode:
                                  example: US
                                  type: string
                                locationName:
                                  example: United States
                                  type: string
                                rank:
                                  example: 1
                                  type: integer
                              required:
                                - rank
                                - locationName
                                - locationCode
                              type: object
                            type: array
                        required:
                          - categories
                        type: object
                      meta:
                        properties:
                          dateRange:
                            items:
                              properties:
                                endTime:
                                  description: Adjusted end of date range.
                                  example: '2022-09-17T10:22:57.555Z'
                                  format: date-time
                                  type: string
                                startTime:
                                  description: Adjusted start of date range.
                                  example: '2022-09-16T10:22:57.555Z'
                                  format: date-time
                                  type: string
                              required:
                                - startTime
                                - endTime
                              type: object
                            type: array
                        required:
                          - dateRange
                        type: object
                    required:
                      - details_0
                      - meta
                    type: object
                  success:
                    example: true
                    type: boolean
                required:
                  - result
                  - success
                type: object
          description: Successful response.
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  result:
                    type: object
                  success:
                    example: false
                    type: boolean
                required:
                  - result
                  - success
                  - errors
                type: object
          description: Bad request.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get domain rank details
      tags:
        - Radar Domains Ranking
      x-api-token-group:
        - User Details Write
        - User Details Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
