openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /radar/entities/asns/{asn}:
    get:
      description: >-
        Retrieves the requested autonomous system information. (A confidence
        level below `5` indicates a low level of confidence in the traffic data
        - normally this happens because Cloudflare has a small amount of traffic
        from/to this AS). Population estimates come from APNIC (refer to
        https://labs.apnic.net/?p=526).
      operationId: radar-get-entities-asn-by-id
      parameters:
        - description: Single Autonomous System Number (ASN) as integer.
          in: path
          name: asn
          required: true
          schema:
            description: Single Autonomous System Number (ASN) as integer.
            example: 174
            type: integer
        - description: Format in which results will be returned.
          in: query
          name: format
          schema:
            description: Format in which results will be returned.
            enum:
              - JSON
              - CSV
            example: json
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  result:
                    properties:
                      asn:
                        properties:
                          aka:
                            type: string
                          asn:
                            example: 714
                            type: integer
                          confidenceLevel:
                            example: 5
                            type: integer
                          country:
                            example: GB
                            type: string
                          countryName:
                            example: United Kingdom
                            type: string
                          estimatedUsers:
                            properties:
                              estimatedUsers:
                                description: Total estimated users.
                                example: 86099
                                type: integer
                              locations:
                                items:
                                  properties:
                                    estimatedUsers:
                                      description: Estimated users per location.
                                      example: 16710
                                      type: integer
                                    locationAlpha2:
                                      example: US
                                      type: string
                                    locationName:
                                      example: United States
                                      type: string
                                  required:
                                    - locationName
                                    - locationAlpha2
                                  type: object
                                type: array
                            required:
                              - locations
                            type: object
                          name:
                            example: Apple Inc.
                            type: string
                          orgName:
                            type: string
                          related:
                            items:
                              properties:
                                aka:
                                  type: string
                                asn:
                                  example: 174
                                  type: integer
                                estimatedUsers:
                                  description: Total estimated users.
                                  example: 65345
                                  type: integer
                                name:
                                  example: Cogent-174
                                  type: string
                              required:
                                - name
                                - asn
                              type: object
                            type: array
                          source:
                            description: Regional Internet Registry.
                            example: RIPE
                            type: string
                          website:
                            example: https://www.apple.com/support/systemstatus/
                            type: string
                        required:
                          - name
                          - country
                          - countryName
                          - confidenceLevel
                          - related
                          - source
                          - asn
                          - website
                          - orgName
                          - estimatedUsers
                        type: object
                    required:
                      - asn
                    type: object
                  success:
                    example: true
                    type: boolean
                required:
                  - result
                  - success
                type: object
          description: Successful response.
        '404':
          content:
            application/json:
              schema:
                properties:
                  error:
                    example: Not Found.
                    type: string
                required:
                  - error
                type: object
          description: Not found.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get AS details by ASN
      tags:
        - Radar Entities
      x-api-token-group:
        - User Details Write
        - User Details Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
