openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /radar/entities/asns:
    get:
      description: Retrieves a list of autonomous systems.
      operationId: radar-get-entities-asn-list
      parameters:
        - description: Limits the number of objects returned in the response.
          in: query
          name: limit
          schema:
            description: Limits the number of objects returned in the response.
            example: 5
            type: integer
        - description: Skips the specified number of objects before fetching the results.
          in: query
          name: offset
          schema:
            description: Skips the specified number of objects before fetching the results.
            type: integer
        - description: >-
            Filters results by Autonomous System. Specify one or more Autonomous
            System Numbers (ASNs) as a comma-separated list.
          in: query
          name: asn
          schema:
            description: >-
              Filters results by Autonomous System. Specify one or more
              Autonomous System Numbers (ASNs) as a comma-separated list.
            example: 174,7922
            type: string
        - description: Filters results by location. Specify an alpha-2 location code.
          in: query
          name: location
          schema:
            description: Filters results by location. Specify an alpha-2 location code.
            example: US
            type: string
        - description: Specifies the metric to order the ASNs by.
          in: query
          name: orderBy
          schema:
            default: ASN
            description: Specifies the metric to order the ASNs by.
            enum:
              - ASN
              - POPULATION
            type: string
        - description: Format in which results will be returned.
          in: query
          name: format
          schema:
            description: Format in which results will be returned.
            enum:
              - JSON
              - CSV
            example: json
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  result:
                    properties:
                      asns:
                        items:
                          properties:
                            aka:
                              type: string
                            asn:
                              example: 714
                              type: integer
                            country:
                              example: GB
                              type: string
                            countryName:
                              example: United Kingdom
                              type: string
                            name:
                              example: Apple Inc.
                              type: string
                            orgName:
                              type: string
                            website:
                              example: https://www.apple.com/support/systemstatus/
                              type: string
                          required:
                            - name
                            - asn
                            - country
                            - countryName
                          type: object
                        type: array
                    required:
                      - asns
                    type: object
                  success:
                    example: true
                    type: boolean
                required:
                  - result
                  - success
                type: object
          description: Successful response.
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  result:
                    type: object
                  success:
                    example: false
                    type: boolean
                required:
                  - result
                  - success
                  - errors
                type: object
          description: Bad request.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List autonomous systems
      tags:
        - Radar Entities
      x-api-token-group:
        - User Details Write
        - User Details Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
