openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /radar/http/timeseries_groups/browser_family:
    get:
      description: >-
        Retrieves the distribution of HTTP requests by user agent family over
        time.
      operationId: radar-get-http-timeseries-group-by-browser-families
      parameters:
        - description: >-
            Aggregation interval of the results (e.g., in 15 minutes or 1 hour
            intervals). Refer to [Aggregation
            intervals](https://developers.cloudflare.com/radar/concepts/aggregation-intervals/).
          in: query
          name: aggInterval
          schema:
            description: >-
              Aggregation interval of the results (e.g., in 15 minutes or 1 hour
              intervals). Refer to [Aggregation
              intervals](https://developers.cloudflare.com/radar/concepts/aggregation-intervals/).
            enum:
              - 15m
              - 1h
              - 1d
              - 1w
            example: 1h
            type: string
        - description: Array of names used to label the series in the response.
          in: query
          name: name
          schema:
            description: Array of names used to label the series in the response.
            items:
              example: main_series
              type: string
            type: array
        - description: >-
            Filters results by date range. For example, use `7d` and `7dcontrol`
            to compare this week with the previous week. Use this parameter or
            set specific start and end dates (`dateStart` and `dateEnd`
            parameters).
          in: query
          name: dateRange
          schema:
            description: >-
              Filters results by date range. For example, use `7d` and
              `7dcontrol` to compare this week with the previous week. Use this
              parameter or set specific start and end dates (`dateStart` and
              `dateEnd` parameters).
            example: 7d
            items:
              example: 7d
              pattern: >-
                ^((([1-9]|[1-9][0-9]|[1-2][0-9][0-9]|3[0-5][0-9]|36[0-4])[d](control)?)|(([1-9]|[1-4][0-9]|5[0-2])[w](control)?))$
              type: string
            type: array
        - description: Start of the date range.
          in: query
          name: dateStart
          schema:
            description: Start of the date range.
            example: '2023-09-01T11:41:33.782Z'
            items:
              format: date-time
              type: string
            type: array
        - description: End of the date range (inclusive).
          in: query
          name: dateEnd
          schema:
            description: End of the date range (inclusive).
            example: '2023-09-01T11:41:33.782Z'
            items:
              format: date-time
              type: string
            type: array
        - description: >-
            Filters results by Autonomous System. Specify one or more Autonomous
            System Numbers (ASNs) as a comma-separated list. Prefix with `-` to
            exclude ASNs from results. For example, `-174, 3356` excludes
            results from AS174, but includes results from AS3356.
          in: query
          name: asn
          schema:
            description: >-
              Filters results by Autonomous System. Specify one or more
              Autonomous System Numbers (ASNs) as a comma-separated list. Prefix
              with `-` to exclude ASNs from results. For example, `-174, 3356`
              excludes results from AS174, but includes results from AS3356.
            example: '15169'
            items:
              type: string
            type: array
        - description: >-
            Filters results by location. Specify a comma-separated list of
            alpha-2 codes. Prefix with `-` to exclude locations from results.
            For example, `-US,PT` excludes results from the US, but includes
            results from PT.
          in: query
          name: location
          schema:
            description: >-
              Filters results by location. Specify a comma-separated list of
              alpha-2 codes. Prefix with `-` to exclude locations from results.
              For example, `-US,PT` excludes results from the US, but includes
              results from PT.
            example: US,CA
            items:
              type: string
            type: array
        - description: >-
            Filters results by continent. Specify a comma-separated list of
            alpha-2 codes. Prefix with `-` to exclude continents from results.
            For example, `-EU,NA` excludes results from EU, but includes results
            from NA.
          in: query
          name: continent
          schema:
            description: >-
              Filters results by continent. Specify a comma-separated list of
              alpha-2 codes. Prefix with `-` to exclude continents from results.
              For example, `-EU,NA` excludes results from EU, but includes
              results from NA.
            example: EU,NA
            items:
              type: string
            type: array
        - description: >-
            Filters results by bot class. Refer to [Bot
            classes](https://developers.cloudflare.com/radar/concepts/bot-classes/).
          in: query
          name: botClass
          schema:
            description: >-
              Filters results by bot class. Refer to [Bot
              classes](https://developers.cloudflare.com/radar/concepts/bot-classes/).
            example: LIKELY_AUTOMATED
            items:
              enum:
                - LIKELY_AUTOMATED
                - LIKELY_HUMAN
              type: string
            type: array
        - description: Filters results by device type.
          in: query
          name: deviceType
          schema:
            description: Filters results by device type.
            example: DESKTOP
            items:
              enum:
                - DESKTOP
                - MOBILE
                - OTHER
              type: string
            type: array
        - description: Filters results by HTTP protocol (HTTP vs. HTTPS).
          in: query
          name: httpProtocol
          schema:
            description: Filters results by HTTP protocol (HTTP vs. HTTPS).
            example: HTTPS
            items:
              enum:
                - HTTP
                - HTTPS
              type: string
            type: array
        - description: Filters results by HTTP version.
          in: query
          name: httpVersion
          schema:
            description: Filters results by HTTP version.
            example: HTTPv1
            items:
              enum:
                - HTTPv1
                - HTTPv2
                - HTTPv3
              type: string
            type: array
        - description: Filters results by IP version (Ipv4 vs. IPv6).
          in: query
          name: ipVersion
          schema:
            description: Filters results by IP version (Ipv4 vs. IPv6).
            example: IPv4
            items:
              enum:
                - IPv4
                - IPv6
              type: string
            type: array
        - description: Filters results by operating system.
          in: query
          name: os
          schema:
            description: Filters results by operating system.
            example: WINDOWS
            items:
              enum:
                - WINDOWS
                - MACOSX
                - IOS
                - ANDROID
                - CHROMEOS
                - LINUX
                - SMART_TV
              type: string
            type: array
        - description: Filters results by TLS version.
          in: query
          name: tlsVersion
          schema:
            description: Filters results by TLS version.
            example: TLSv1_2
            items:
              enum:
                - TLSv1_0
                - TLSv1_1
                - TLSv1_2
                - TLSv1_3
                - TLSvQUIC
              type: string
            type: array
        - description: >-
            Limits the number of objects per group to the top items within the
            specified time range. When item count exceeds the limit, extra items
            appear grouped under an "other" category.
          in: query
          name: limitPerGroup
          schema:
            description: >-
              Limits the number of objects per group to the top items within the
              specified time range. When item count exceeds the limit, extra
              items appear grouped under an "other" category.
            example: 10
            type: integer
        - description: Format in which results will be returned.
          in: query
          name: format
          schema:
            description: Format in which results will be returned.
            enum:
              - JSON
              - CSV
            example: json
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  result:
                    properties:
                      meta:
                        description: Metadata for the results.
                        properties:
                          aggInterval:
                            description: >-
                              Aggregation interval of the results (e.g., in 15
                              minutes or 1 hour intervals). Refer to
                              [Aggregation
                              intervals](https://developers.cloudflare.com/radar/concepts/aggregation-intervals/).
                            enum:
                              - FIFTEEN_MINUTES
                              - ONE_HOUR
                              - ONE_DAY
                              - ONE_WEEK
                              - ONE_MONTH
                            type: string
                          confidenceInfo:
                            properties:
                              annotations:
                                items:
                                  description: >-
                                    Annotation associated with the result (e.g.
                                    outage or other type of event).
                                  properties:
                                    dataSource:
                                      example: ALL
                                      type: string
                                    description:
                                      example: Cable cut in Tonga
                                      type: string
                                    endDate:
                                      format: date-time
                                      type: string
                                    eventType:
                                      example: OUTAGE
                                      type: string
                                    isInstantaneous:
                                      description: >-
                                        Whether event is a single point in time
                                        or a time range.
                                      type: boolean
                                    linkedUrl:
                                      format: uri
                                      type: string
                                    startDate:
                                      format: date-time
                                      type: string
                                  required:
                                    - dataSource
                                    - eventType
                                    - description
                                    - startDate
                                    - endDate
                                    - linkedUrl
                                    - isInstantaneous
                                  type: object
                                type: array
                              level:
                                description: >-
                                  Provides an indication of how much confidence
                                  Cloudflare has in the data.
                                type: integer
                            required:
                              - level
                              - annotations
                            type: object
                          dateRange:
                            items:
                              properties:
                                endTime:
                                  description: Adjusted end of date range.
                                  example: '2022-09-17T10:22:57.555Z'
                                  format: date-time
                                  type: string
                                startTime:
                                  description: Adjusted start of date range.
                                  example: '2022-09-16T10:22:57.555Z'
                                  format: date-time
                                  type: string
                              required:
                                - startTime
                                - endTime
                              type: object
                            type: array
                          lastUpdated:
                            description: Timestamp of the last dataset update.
                            format: date-time
                            type: string
                          normalization:
                            description: >-
                              Normalization method applied to the results. Refer
                              to [Normalization
                              methods](https://developers.cloudflare.com/radar/concepts/normalization/).
                            enum:
                              - PERCENTAGE
                              - MIN0_MAX
                              - MIN_MAX
                              - RAW_VALUES
                              - PERCENTAGE_CHANGE
                              - ROLLING_AVERAGE
                              - OVERLAPPED_PERCENTAGE
                              - RATIO
                            type: string
                          units:
                            description: Measurement units for the results.
                            items:
                              properties:
                                name:
                                  example: '*'
                                  type: string
                                value:
                                  example: requests
                                  type: string
                              required:
                                - name
                                - value
                              type: object
                            type: array
                        required:
                          - dateRange
                          - confidenceInfo
                          - normalization
                          - lastUpdated
                          - units
                          - aggInterval
                        type: object
                      serie_0:
                        additionalProperties:
                          items:
                            description: A numeric string.
                            example: '10'
                            pattern: ^\d+$
                            type: string
                          type: array
                        example:
                          Chrome:
                            - '50.168733'
                          timestamps:
                            - '2023-08-08T10:15:00Z'
                        properties:
                          timestamps:
                            items:
                              format: date-time
                              type: string
                            type: array
                        required:
                          - timestamps
                        type: object
                    required:
                      - serie_0
                      - meta
                    type: object
                  success:
                    example: true
                    type: boolean
                required:
                  - result
                  - success
                type: object
          description: Successful response.
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  result:
                    type: object
                  success:
                    example: false
                    type: boolean
                required:
                  - result
                  - success
                  - errors
                type: object
          description: Bad request.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get HTTP requests by user agent family time series
      tags:
        - Radar HTTP
      x-api-token-group:
        - User Details Write
        - User Details Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
