openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/secondary_dns/incoming:
    get:
      description: Get secondary zone configuration for incoming zone transfers.
      operationId: secondary-dns-(-secondary-zone)-secondary-zone-configuration-details
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            example: 269d8f4853475ca241c4e730be286b20
            readOnly: true
            type: string
            x-auditable: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                        type: object
                    type: object
                  - properties:
                      result:
                        properties:
                          auto_refresh_seconds:
                            description: >-
                              How often should a secondary zone auto refresh
                              regardless of DNS NOTIFY.

                              Not applicable for primary zones.
                            example: 86400
                            type: number
                            x-auditable: true
                          checked_time:
                            description: The time for a specific event.
                            example: '2019-10-24T17:09:42.883908+01:00'
                            type: string
                            x-auditable: true
                          created_time:
                            description: The time for a specific event.
                            example: '2019-10-24T17:09:42.883908+01:00'
                            type: string
                            x-auditable: true
                          id:
                            example: 269d8f4853475ca241c4e730be286b20
                            readOnly: true
                            type: string
                            x-auditable: true
                          modified_time:
                            description: The time for a specific event.
                            example: '2019-10-24T17:09:42.883908+01:00'
                            type: string
                            x-auditable: true
                          name:
                            description: Zone name.
                            example: www.example.com.
                            type: string
                            x-auditable: true
                          peers:
                            description: A list of peer tags.
                            example:
                              - 23ff594956f20c2a721606e94745a8aa
                              - 00920f38ce07c2e2f4df50b1f61d4194
                            items:
                              example: 269d8f4853475ca241c4e730be286b20
                              readOnly: true
                              type: string
                              x-auditable: true
                            type: array
                          soa_serial:
                            description: The serial number of the SOA for the given zone.
                            example: 2019102400
                            type: number
                            x-auditable: true
                        type: object
          description: Secondary Zone Configuration Details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - allOf:
                          - properties:
                              errors:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    documentation_url:
                                      type: string
                                    message:
                                      type: string
                                    source:
                                      properties:
                                        pointer:
                                          type: string
                                      type: object
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              messages:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    documentation_url:
                                      type: string
                                    message:
                                      type: string
                                    source:
                                      properties:
                                        pointer:
                                          type: string
                                      type: object
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              success:
                                description: Whether the API call was successful.
                                enum:
                                  - true
                                example: true
                                type: boolean
                            required:
                              - success
                              - errors
                              - messages
                            type: object
                        type: object
                      - properties:
                          result:
                            properties:
                              auto_refresh_seconds:
                                description: >-
                                  How often should a secondary zone auto refresh
                                  regardless of DNS NOTIFY.

                                  Not applicable for primary zones.
                                example: 86400
                                type: number
                                x-auditable: true
                              checked_time:
                                description: The time for a specific event.
                                example: '2019-10-24T17:09:42.883908+01:00'
                                type: string
                                x-auditable: true
                              created_time:
                                description: The time for a specific event.
                                example: '2019-10-24T17:09:42.883908+01:00'
                                type: string
                                x-auditable: true
                              id:
                                example: 269d8f4853475ca241c4e730be286b20
                                readOnly: true
                                type: string
                                x-auditable: true
                              modified_time:
                                description: The time for a specific event.
                                example: '2019-10-24T17:09:42.883908+01:00'
                                type: string
                                x-auditable: true
                              name:
                                description: Zone name.
                                example: www.example.com.
                                type: string
                                x-auditable: true
                              peers:
                                description: A list of peer tags.
                                example:
                                  - 23ff594956f20c2a721606e94745a8aa
                                  - 00920f38ce07c2e2f4df50b1f61d4194
                                items:
                                  example: 269d8f4853475ca241c4e730be286b20
                                  readOnly: true
                                  type: string
                                  x-auditable: true
                                type: array
                              soa_serial:
                                description: >-
                                  The serial number of the SOA for the given
                                  zone.
                                example: 2019102400
                                type: number
                                x-auditable: true
                            type: object
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
          description: Secondary Zone Configuration Details response failure
      security:
        - api_email: []
          api_key: []
      summary: Secondary Zone Configuration Details
      tags:
        - Secondary DNS (Secondary Zone)
      x-api-token-group:
        - Zone Settings Write
        - Zone Settings Read
        - DNS Read
        - Zone Write
        - DNS Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
