openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/secondary_dns/tsigs:
    get:
      description: List TSIGs.
      operationId: secondary-dns-(-tsig)-list-tsi-gs
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            example: 01a7362d577a6c3019a474fd6f485823
            readOnly: true
            type: string
            x-auditable: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                        type: object
                      - properties:
                          result_info:
                            properties:
                              count:
                                description: >-
                                  Total number of results for the requested
                                  service.
                                example: 1
                                type: number
                              page:
                                description: Current page within paginated list of results.
                                example: 1
                                type: number
                              per_page:
                                description: Number of results per page of results.
                                example: 20
                                type: number
                              total_count:
                                description: >-
                                  Total results available without any search
                                  parameters.
                                example: 2000
                                type: number
                            type: object
                        type: object
                    type: object
                  - properties:
                      result:
                        items:
                          properties:
                            algo:
                              description: TSIG algorithm.
                              example: hmac-sha512.
                              type: string
                              x-auditable: true
                            id:
                              example: 69cd1e104af3e6ed3cb344f263fd0d5a
                              readOnly: true
                              type: string
                              x-auditable: true
                            name:
                              description: TSIG key name.
                              example: tsig.customer.cf.
                              type: string
                              x-auditable: true
                            secret:
                              description: TSIG secret.
                              example: >-
                                caf79a7804b04337c9c66ccd7bef9190a1e1679b5dd03d8aa10f7ad45e1a9dab92b417896c15d4d007c7c14194538d2a5d0feffdecc5a7f0e1c570cfa700837c
                              type: string
                              x-sensitive: true
                          required:
                            - id
                            - name
                            - secret
                            - algo
                          type: object
                        type: array
          description: List TSIGs response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - allOf:
                          - properties:
                              errors:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    documentation_url:
                                      type: string
                                    message:
                                      type: string
                                    source:
                                      properties:
                                        pointer:
                                          type: string
                                      type: object
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              messages:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    documentation_url:
                                      type: string
                                    message:
                                      type: string
                                    source:
                                      properties:
                                        pointer:
                                          type: string
                                      type: object
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              success:
                                description: Whether the API call was successful.
                                enum:
                                  - true
                                example: true
                                type: boolean
                            required:
                              - success
                              - errors
                              - messages
                            type: object
                          - properties:
                              result_info:
                                properties:
                                  count:
                                    description: >-
                                      Total number of results for the requested
                                      service.
                                    example: 1
                                    type: number
                                  page:
                                    description: >-
                                      Current page within paginated list of
                                      results.
                                    example: 1
                                    type: number
                                  per_page:
                                    description: Number of results per page of results.
                                    example: 20
                                    type: number
                                  total_count:
                                    description: >-
                                      Total results available without any search
                                      parameters.
                                    example: 2000
                                    type: number
                                type: object
                            type: object
                        type: object
                      - properties:
                          result:
                            items:
                              properties:
                                algo:
                                  description: TSIG algorithm.
                                  example: hmac-sha512.
                                  type: string
                                  x-auditable: true
                                id:
                                  example: 69cd1e104af3e6ed3cb344f263fd0d5a
                                  readOnly: true
                                  type: string
                                  x-auditable: true
                                name:
                                  description: TSIG key name.
                                  example: tsig.customer.cf.
                                  type: string
                                  x-auditable: true
                                secret:
                                  description: TSIG secret.
                                  example: >-
                                    caf79a7804b04337c9c66ccd7bef9190a1e1679b5dd03d8aa10f7ad45e1a9dab92b417896c15d4d007c7c14194538d2a5d0feffdecc5a7f0e1c570cfa700837c
                                  type: string
                                  x-sensitive: true
                              required:
                                - id
                                - name
                                - secret
                                - algo
                              type: object
                            type: array
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
          description: List TSIGs response failure
      security:
        - api_email: []
          api_key: []
      summary: List TSIGs
      tags:
        - Secondary DNS (TSIG)
      x-api-token-group:
        - Account Settings Write
        - Account Settings Read
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
