openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/secrets_store/stores/{store_id}/secrets/{secret_id}:
    get:
      description: Returns details of a single secret
      operationId: secrets-store-get-by-id
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Account Identifier
            example: 985e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
        - in: path
          name: store_id
          required: true
          schema:
            description: Store Identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
            x-auditable: true
        - in: path
          name: secret_id
          required: true
          schema:
            description: Secret identifier tag.
            example: 3fd85f74b32742f1bff64a85009dda07
            maxLength: 32
            readOnly: true
            type: string
            x-auditable: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                        type: object
                      - properties:
                          result_info:
                            properties:
                              count:
                                description: >-
                                  Total number of results for the requested
                                  service.
                                example: 1
                                type: number
                              page:
                                description: Current page within paginated list of results.
                                example: 1
                                type: number
                              per_page:
                                description: Number of results per page of results.
                                example: 20
                                type: number
                              total_count:
                                description: >-
                                  Total results available without any search
                                  parameters.
                                example: 2000
                                type: number
                            type: object
                        type: object
                    type: object
                  - properties:
                      result:
                        properties:
                          comment:
                            description: Freeform text describing the secret
                            example: info about my secret
                            type: string
                            x-auditable: true
                          created:
                            description: Whenthe secret was created.
                            example: '2023-09-21T18:56:32.624632Z'
                            format: date-time
                            readOnly: true
                            type: string
                            x-auditable: true
                          id:
                            description: Secret identifier tag.
                            example: 3fd85f74b32742f1bff64a85009dda07
                            maxLength: 32
                            readOnly: true
                            type: string
                            x-auditable: true
                          modified:
                            description: When the secret was modified.
                            example: '2023-09-21T18:56:32.624632Z'
                            format: date-time
                            readOnly: true
                            type: string
                            x-auditable: true
                          name:
                            description: The name of the secret
                            example: MY_API_KEY
                            type: string
                          status:
                            enum:
                              - pending
                              - active
                              - deleted
                            type: string
                            x-auditable: true
                          store_id:
                            description: Store Identifier
                            example: 023e105f4ecef8ad9ca31a8372d0c353
                            maxLength: 32
                            readOnly: true
                            type: string
                            x-auditable: true
                        required:
                          - id
                          - name
                          - store_id
                          - created
                          - modified
                          - status
          description: secret detail
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
          description: failure
      security:
        - api_email: []
          api_key: []
      summary: Get a secret by ID
      tags:
        - Secrets Store
      x-api-token-group:
        - Secrets Store Write
        - Secrets Store Read
      x-cfPermissionsRequired:
        enum:
          - '#com.cloudflare.api.account.secrets-store.secret.read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
