openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/shares/{share_id}/resources:
    post:
      operationId: share-resource-create
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Account identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
        - in: path
          name: share_id
          required: true
          schema:
            description: Share identifier tag.
            example: 3fd85f74b32742f1bff64a85009dda07
            maxLength: 32
            type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                meta:
                  description: Resource Metadata.
                  type: object
                resource_account_id:
                  description: Account identifier.
                  example: 023e105f4ecef8ad9ca31a8372d0c353
                  maxLength: 32
                  type: string
                resource_id:
                  description: Share Resource identifier.
                  example: 023e105f4ecef8ad9ca31a8372d0c353
                  maxLength: 32
                  type: string
                resource_type:
                  description: Resource Type.
                  enum:
                    - custom-ruleset
                    - widget
                  type: string
              required:
                - resource_id
                - resource_type
                - resource_account_id
                - meta
              type: object
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                        type: array
                      result:
                        anyOf:
                          - type: object
                          - items: {}
                            type: array
                          - type: string
                      success:
                        description: Whether the API call was successful.
                        example: true
                        type: boolean
                    required:
                      - success
                      - errors
                    type: object
                  - properties:
                      result:
                        properties:
                          created:
                            description: When the share was created.
                            example: '2023-09-21T18:56:32.624632Z'
                            format: date-time
                            type: string
                          id:
                            description: Share Resource identifier.
                            example: 023e105f4ecef8ad9ca31a8372d0c353
                            maxLength: 32
                            type: string
                          meta:
                            description: Resource Metadata.
                            type: object
                          modified:
                            description: When the share was modified.
                            example: '2023-09-21T18:56:32.624632Z'
                            format: date-time
                            type: string
                          resource_account_id:
                            description: Account identifier.
                            example: 023e105f4ecef8ad9ca31a8372d0c353
                            maxLength: 32
                            type: string
                          resource_id:
                            description: Share Resource identifier.
                            example: 023e105f4ecef8ad9ca31a8372d0c353
                            maxLength: 32
                            type: string
                          resource_type:
                            description: Resource Type.
                            enum:
                              - custom-ruleset
                              - widget
                            type: string
                          resource_version:
                            description: Resource Version.
                            type: integer
                          status:
                            description: Resource Status.
                            enum:
                              - active
                              - deleting
                              - deleted
                            type: string
                        required:
                          - id
                          - resource_id
                          - resource_type
                          - resource_account_id
                          - meta
                          - status
                          - created
                          - modified
                          - resource_version
                type: object
          description: Share resource created.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful.
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - result
                    type: object
          description: Create share resource failure.
        5XX:
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful.
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - result
                    type: object
          description: Create share resource failure.
      security:
        - api_email: []
          api_key: []
      summary: Create a new share resource
      tags:
        - Resource Sharing
      x-api-token-group: null
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
