openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/slurper/jobs/{job_id}/logs:
    get:
      operationId: slurper-get-job-logs
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
        - in: path
          name: job_id
          required: true
          schema:
            type: string
        - in: query
          name: limit
          schema:
            maximum: 50
            type: integer
        - in: query
          name: offset
          schema:
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        example:
                          - code: 7003
                            message: No route for the URI
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                              x-auditable: true
                            message:
                              type: string
                              x-auditable: true
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        minLength: 1
                        type: array
                      messages:
                        example: []
                        items:
                          type: string
                          x-auditable: true
                        type: array
                      success:
                        description: Indicates if the API call was successful or not.
                        enum:
                          - true
                        type: boolean
                        x-auditable: true
                    type: object
                  - properties:
                      result:
                        items:
                          properties:
                            createdAt:
                              type: string
                            job:
                              type: string
                            logType:
                              enum:
                                - migrationStart
                                - migrationComplete
                                - migrationAbort
                                - migrationError
                                - migrationPause
                                - migrationResume
                                - migrationErrorFailedContinuation
                                - importErrorRetryExhaustion
                                - importSkippedStorageClass
                                - importSkippedOversized
                                - importSkippedEmptyObject
                                - importSkippedUnsupportedContentType
                                - importSkippedExcludedContentType
                                - importSkippedInvalidMedia
                                - importSkippedRequiresRetrieval
                              type: string
                            message:
                              nullable: true
                              type: string
                            objectKey:
                              nullable: true
                              type: string
                          type: object
                        type: array
                    type: object
                type: object
          description: Job logs
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    example:
                      - code: 7003
                        message: No route for the URI
                    items:
                      properties:
                        code:
                          minimum: 1000
                          type: integer
                          x-auditable: true
                        message:
                          type: string
                          x-auditable: true
                      required:
                        - code
                        - message
                      type: object
                      uniqueItems: true
                    minLength: 1
                    type: array
                  messages:
                    example: []
                    items:
                      type: string
                      x-auditable: true
                    type: array
                  success:
                    description: Indicates if the API call was successful or not.
                    enum:
                      - false
                    example: false
                    type: boolean
                    x-auditable: true
                type: object
          description: Failure response
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get job logs
      tags:
        - R2 Super Slurper
