openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/ssl/recommendation:
    get:
      deprecated: true
      description: Retrieve the SSL/TLS Recommender's recommendation for a zone.
      operationId: ssl/-tls-mode-recommendation-ssl/-tls-recommendation
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    example: []
                    items:
                      properties:
                        code:
                          minimum: 1000
                          type: integer
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                      uniqueItems: true
                    type: array
                  messages:
                    example: []
                    items:
                      properties:
                        code:
                          minimum: 1000
                          type: integer
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                      uniqueItems: true
                    type: array
                  result:
                    properties:
                      editable:
                        description: Whether this setting can be updated or not.
                        readOnly: true
                        type: boolean
                      id:
                        example: ssl_automatic_mode
                        readOnly: true
                        type: string
                      modified_on:
                        description: Last time this setting was modified.
                        example: '2014-01-01T05:20:00.12345Z'
                        format: date-time
                        readOnly: true
                        type: string
                      next_scheduled_scan:
                        description: >-
                          Next time this zone will be scanned by the Automatic
                          SSL/TLS.
                        example: '2014-01-01T05:20:00.12345Z'
                        format: date-time
                        nullable: true
                        readOnly: true
                        type: string
                      value:
                        description: Current setting of the automatic SSL/TLS.
                        enum:
                          - auto
                          - custom
                        example: auto
                        readOnly: true
                        type: string
                    required:
                      - id
                      - modified_on
                      - value
                      - editable
                    type: object
                  success:
                    description: Indicates the API call's success or failure.
                    example: true
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: SSL/TLS Recommendation response.
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    minLength: 1
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                  result:
                    properties:
                      editable:
                        description: Whether this setting can be updated or not.
                        readOnly: true
                        type: boolean
                      id:
                        example: ssl_automatic_mode
                        readOnly: true
                        type: string
                      modified_on:
                        description: Last time this setting was modified.
                        example: '2014-01-01T05:20:00.12345Z'
                        format: date-time
                        readOnly: true
                        type: string
                      next_scheduled_scan:
                        description: >-
                          Next time this zone will be scanned by the Automatic
                          SSL/TLS.
                        example: '2014-01-01T05:20:00.12345Z'
                        format: date-time
                        nullable: true
                        readOnly: true
                        type: string
                      value:
                        description: Current setting of the automatic SSL/TLS.
                        enum:
                          - auto
                          - custom
                        example: auto
                        readOnly: true
                        type: string
                    required:
                      - id
                      - modified_on
                      - value
                      - editable
                    type: object
                  success:
                    description: Indicates the API call's success or failure.
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: SSL/TLS Recommendation response failure.
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: SSL/TLS Recommendation
      tags:
        - SSL/TLS Mode Recommendation
      x-api-token-group:
        - Zone Settings Write
        - Zone Settings Read
        - SSL and Certificates Write
        - SSL and Certificates Read
      x-cfPermissionsRequired:
        enum:
          - '#ssl:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
      x-stainless-deprecation-message: >-
        SSL/TLS Recommender has been decommissioned in favor of Automatic
        SSL/TLS
