openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/stream:
    post:
      description: >-
        Initiates a video upload using the TUS protocol. On success, the server
        responds with a status code 201 (created) and includes a `location`
        header to indicate where the content should be uploaded. Refer to
        https://tus.io for protocol details.
      operationId: stream-videos-initiate-video-uploads-using-tus
      parameters:
        - in: header
          name: Tus-Resumable
          required: true
          schema:
            description: >-
              Specifies the TUS protocol version. This value must be included in
              every upload request.

              Notes: The only supported version of TUS protocol is 1.0.0.
            enum:
              - 1.0.0
            example: 1.0.0
            type: string
            x-auditable: true
        - in: header
          name: Upload-Creator
          schema:
            description: A user-defined identifier for the media creator.
            example: creator-id_abcde12345
            maxLength: 64
            type: string
            x-auditable: true
        - in: header
          name: Upload-Length
          required: true
          schema:
            description: >-
              Indicates the size of the entire upload in bytes. The value must
              be a non-negative integer.
            minimum: 0
            type: integer
            x-auditable: true
        - in: header
          name: Upload-Metadata
          schema:
            description: >-
              Comma-separated key-value pairs following the TUS protocol
              specification. Values are Base-64 encoded.

              Supported keys: `name`, `requiresignedurls`, `allowedorigins`,
              `thumbnailtimestamppct`, `watermark`, `scheduleddeletion`,
              `maxdurationseconds`.
            example: >-
              name aGVsbG8gd29ybGQ=, requiresignedurls, allowedorigins
              ZXhhbXBsZS5jb20sdGVzdC5jb20=
            type: string
            x-auditable: true
        - in: path
          name: account_id
          required: true
          schema:
            description: The account identifier tag.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
            x-auditable: true
        - in: query
          name: direct_user
          schema:
            default: false
            description: >-
              Provisions a URL to let your end users upload videos directly to
              Cloudflare Stream without exposing your API token to clients.
            example: true
            type: boolean
            x-auditable: true
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json: {}
          description: Initiate video uploads using TUS response.
        4XX:
          content:
            application/json: {}
          description: Initiate video uploads using TUS response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Initiate video uploads using TUS
      tags:
        - Stream Videos
      x-api-token-group:
        - Stream Write
