openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/ssl/universal/settings:
    patch:
      description: Patch Universal SSL Settings for a Zone.
      operationId: universal-ssl-settings-for-a-zone-edit-universal-ssl-settings
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            description: Identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                enabled:
                  description: >-
                    Disabling Universal SSL removes any currently active
                    Universal SSL certificates for your zone from the edge and
                    prevents any future Universal SSL certificates from being
                    ordered. If there are no advanced certificates or custom
                    certificates uploaded for the domain, visitors will be
                    unable to access the domain over HTTPS.


                    By disabling Universal SSL, you understand that the
                    following Cloudflare settings and preferences will result in
                    visitors being unable to visit your domain unless you have
                    uploaded a custom certificate or purchased an advanced
                    certificate.


                    * HSTS

                    * Always Use HTTPS

                    * Opportunistic Encryption

                    * Onion Routing

                    * Any Page Rules redirecting traffic to HTTPS


                    Similarly, any HTTP redirect to HTTPS at the origin while
                    the Cloudflare proxy is enabled will result in users being
                    unable to visit your site without a valid certificate at
                    Cloudflare's edge.


                    If you do not have a valid custom or advanced certificate at
                    Cloudflare's edge and are unsure if any of the above
                    Cloudflare settings are enabled, or if any HTTP redirects
                    exist at your origin, we advise leaving Universal SSL
                    enabled for your domain.
                  example: true
                  type: boolean
                  x-auditable: true
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                        type: object
                    type: object
                  - properties:
                      result:
                        properties:
                          enabled:
                            description: >-
                              Disabling Universal SSL removes any currently
                              active Universal SSL certificates for your zone
                              from the edge and prevents any future Universal
                              SSL certificates from being ordered. If there are
                              no advanced certificates or custom certificates
                              uploaded for the domain, visitors will be unable
                              to access the domain over HTTPS.


                              By disabling Universal SSL, you understand that
                              the following Cloudflare settings and preferences
                              will result in visitors being unable to visit your
                              domain unless you have uploaded a custom
                              certificate or purchased an advanced certificate.


                              * HSTS

                              * Always Use HTTPS

                              * Opportunistic Encryption

                              * Onion Routing

                              * Any Page Rules redirecting traffic to HTTPS


                              Similarly, any HTTP redirect to HTTPS at the
                              origin while the Cloudflare proxy is enabled will
                              result in users being unable to visit your site
                              without a valid certificate at Cloudflare's edge.


                              If you do not have a valid custom or advanced
                              certificate at Cloudflare's edge and are unsure if
                              any of the above Cloudflare settings are enabled,
                              or if any HTTP redirects exist at your origin, we
                              advise leaving Universal SSL enabled for your
                              domain.
                            example: true
                            type: boolean
                            x-auditable: true
                        type: object
          description: Edit Universal SSL Settings response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - allOf:
                          - properties:
                              errors:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    documentation_url:
                                      type: string
                                    message:
                                      type: string
                                    source:
                                      properties:
                                        pointer:
                                          type: string
                                      type: object
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              messages:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    documentation_url:
                                      type: string
                                    message:
                                      type: string
                                    source:
                                      properties:
                                        pointer:
                                          type: string
                                      type: object
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              success:
                                description: Whether the API call was successful.
                                enum:
                                  - true
                                example: true
                                type: boolean
                            required:
                              - success
                              - errors
                              - messages
                            type: object
                        type: object
                      - properties:
                          result:
                            properties:
                              enabled:
                                description: >-
                                  Disabling Universal SSL removes any currently
                                  active Universal SSL certificates for your
                                  zone from the edge and prevents any future
                                  Universal SSL certificates from being ordered.
                                  If there are no advanced certificates or
                                  custom certificates uploaded for the domain,
                                  visitors will be unable to access the domain
                                  over HTTPS.


                                  By disabling Universal SSL, you understand
                                  that the following Cloudflare settings and
                                  preferences will result in visitors being
                                  unable to visit your domain unless you have
                                  uploaded a custom certificate or purchased an
                                  advanced certificate.


                                  * HSTS

                                  * Always Use HTTPS

                                  * Opportunistic Encryption

                                  * Onion Routing

                                  * Any Page Rules redirecting traffic to HTTPS


                                  Similarly, any HTTP redirect to HTTPS at the
                                  origin while the Cloudflare proxy is enabled
                                  will result in users being unable to visit
                                  your site without a valid certificate at
                                  Cloudflare's edge.


                                  If you do not have a valid custom or advanced
                                  certificate at Cloudflare's edge and are
                                  unsure if any of the above Cloudflare settings
                                  are enabled, or if any HTTP redirects exist at
                                  your origin, we advise leaving Universal SSL
                                  enabled for your domain.
                                example: true
                                type: boolean
                                x-auditable: true
                            type: object
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
          description: Edit Universal SSL Settings response failure
      security:
        - api_email: []
          api_key: []
      summary: Edit Universal SSL Settings
      tags:
        - Universal SSL Settings for a Zone
      x-api-token-group:
        - SSL and Certificates Write
      x-cfPermissionsRequired:
        enum:
          - '#ssl:read'
          - '#ssl:edit'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
