openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/snippets/{snippet_name}:
    put:
      description: Creates or updates a snippet belonging to the zone.
      operationId: updateZoneSnippet
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            description: The unique ID of the zone.
            example: 9f1839b6152d298aca64c4e906b6d074
            pattern: ^[0-9a-f]{32}$
            title: Zone ID
            type: string
            x-auditable: true
        - in: path
          name: snippet_name
          required: true
          schema:
            description: The identifying name of the snippet.
            example: my_snippet
            pattern: ^[A-Za-z0-9_]+$
            title: Snippet Name
            type: string
            x-auditable: true
      requestBody:
        content:
          multipart/form-data:
            schema:
              description: A snippet object.
              properties:
                files:
                  description: The list of files belonging to the snippet.
                  items:
                    description: A file belonging to the snippet.
                    format: binary
                    title: File
                    type: string
                    x-auditable: true
                  minItems: 1
                  title: Files
                  type: array
                metadata:
                  description: Metadata about the snippet.
                  properties:
                    main_module:
                      description: >-
                        Name of the file that contains the main module of the
                        snippet.
                      example: main.js
                      minLength: 1
                      title: Main Module
                      type: string
                      x-auditable: true
                  required:
                    - main_module
                  title: Metadata
                  type: object
              required:
                - metadata
                - files
              title: Snippet
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - description: A response object.
                    properties:
                      errors:
                        description: A list of error messages.
                        items:
                          description: A message.
                          properties:
                            code:
                              description: A unique code for this message.
                              example: 10000
                              title: Code
                              type: integer
                              x-auditable: true
                            message:
                              description: A text description of this message.
                              example: something bad happened
                              minLength: 1
                              title: Description
                              type: string
                              x-auditable: true
                          required:
                            - message
                          title: Message
                          type: object
                        title: Errors
                        type: array
                      messages:
                        description: A list of warning messages.
                        items:
                          description: A message.
                          properties:
                            code:
                              description: A unique code for this message.
                              example: 10000
                              title: Code
                              type: integer
                              x-auditable: true
                            message:
                              description: A text description of this message.
                              example: something bad happened
                              minLength: 1
                              title: Description
                              type: string
                              x-auditable: true
                          required:
                            - message
                          title: Message
                          type: object
                        title: Messages
                        type: array
                      result:
                        description: A result.
                        title: Result
                      success:
                        description: Whether the API call was successful.
                        title: Success
                        type: boolean
                        x-auditable: true
                    required:
                      - result
                      - success
                      - errors
                      - messages
                    title: Response
                    type: object
                  - properties:
                      errors:
                        enum:
                          - []
                      result:
                        description: A snippet object.
                        properties:
                          created_on:
                            description: The timestamp of when the snippet was created.
                            example: '2000-01-01T00:00:00.000000Z'
                            format: date-time
                            title: Created On
                            type: string
                            x-auditable: true
                          modified_on:
                            description: >-
                              The timestamp of when the snippet was last
                              modified.
                            example: '2000-01-01T00:00:00.000000Z'
                            format: date-time
                            title: Modified On
                            type: string
                            x-auditable: true
                          snippet_name:
                            description: The identifying name of the snippet.
                            example: my_snippet
                            pattern: ^[A-Za-z0-9_]+$
                            title: Snippet Name
                            type: string
                            x-auditable: true
                        required:
                          - created_on
                          - modified_one
                          - snippet_name
                        title: Snippet
                        type: object
                      success:
                        enum:
                          - true
          description: A snippet response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - description: A response object.
                    properties:
                      errors:
                        description: A list of error messages.
                        items:
                          description: A message.
                          properties:
                            code:
                              description: A unique code for this message.
                              example: 10000
                              title: Code
                              type: integer
                              x-auditable: true
                            message:
                              description: A text description of this message.
                              example: something bad happened
                              minLength: 1
                              title: Description
                              type: string
                              x-auditable: true
                          required:
                            - message
                          title: Message
                          type: object
                        title: Errors
                        type: array
                      messages:
                        description: A list of warning messages.
                        items:
                          description: A message.
                          properties:
                            code:
                              description: A unique code for this message.
                              example: 10000
                              title: Code
                              type: integer
                              x-auditable: true
                            message:
                              description: A text description of this message.
                              example: something bad happened
                              minLength: 1
                              title: Description
                              type: string
                              x-auditable: true
                          required:
                            - message
                          title: Message
                          type: object
                        title: Messages
                        type: array
                      result:
                        description: A result.
                        title: Result
                      success:
                        description: Whether the API call was successful.
                        title: Success
                        type: boolean
                        x-auditable: true
                    required:
                      - result
                      - success
                      - errors
                      - messages
                    title: Response
                    type: object
                  - properties:
                      result:
                        enum:
                          - null
                        x-auditable: true
                      success:
                        enum:
                          - false
          description: A failure response.
        5XX:
          content:
            application/json:
              schema:
                allOf:
                  - description: A response object.
                    properties:
                      errors:
                        description: A list of error messages.
                        items:
                          description: A message.
                          properties:
                            code:
                              description: A unique code for this message.
                              example: 10000
                              title: Code
                              type: integer
                              x-auditable: true
                            message:
                              description: A text description of this message.
                              example: something bad happened
                              minLength: 1
                              title: Description
                              type: string
                              x-auditable: true
                          required:
                            - message
                          title: Message
                          type: object
                        title: Errors
                        type: array
                      messages:
                        description: A list of warning messages.
                        items:
                          description: A message.
                          properties:
                            code:
                              description: A unique code for this message.
                              example: 10000
                              title: Code
                              type: integer
                              x-auditable: true
                            message:
                              description: A text description of this message.
                              example: something bad happened
                              minLength: 1
                              title: Description
                              type: string
                              x-auditable: true
                          required:
                            - message
                          title: Message
                          type: object
                        title: Messages
                        type: array
                      result:
                        description: A result.
                        title: Result
                      success:
                        description: Whether the API call was successful.
                        title: Success
                        type: boolean
                        x-auditable: true
                    required:
                      - result
                      - success
                      - errors
                      - messages
                    title: Response
                    type: object
                  - properties:
                      result:
                        enum:
                          - null
                        x-auditable: true
                      success:
                        enum:
                          - false
          description: A failure response.
      security:
        - api_token: []
        - api_email: []
          api_key: []
        - api_email: []
          api_key: []
      summary: Update a zone snippet
      tags:
        - Zone Snippets
      x-api-token-group:
        - Snippets Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
