openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/urlscanner/scan:
    get:
      deprecated: true
      description: >-
        Search scans by date and webpages' requests, including full URL (after
        redirects), hostname, and path. <br/> A successful scan will appear in
        search results a few minutes after finishing but may take much longer if
        the system in under load. By default, only successfully completed scans
        will appear in search results, unless searching by `scanId`. Please take
        into account that older scans may be removed from the search index at an
        unspecified time.
      operationId: urlscanner-search-scans
      parameters:
        - description: Account ID.
          in: path
          name: account_id
          required: true
          schema:
            description: Account ID.
            type: string
        - description: Scan UUID.
          in: query
          name: scan_id
          schema:
            description: Scan UUID.
            format: uuid
            type: string
        - description: Limit the number of objects in the response.
          in: query
          name: limit
          schema:
            description: Limit the number of objects in the response.
            example: 100
            type: integer
        - description: Pagination cursor to get the next set of results.
          in: query
          name: next_cursor
          schema:
            description: Pagination cursor to get the next set of results.
            type: string
        - description: Filter scans requested after date (inclusive).
          in: query
          name: date_start
          schema:
            description: Filter scans requested after date (inclusive).
            format: date-time
            type: string
        - description: Filter scans requested before date (inclusive).
          in: query
          name: date_end
          schema:
            description: Filter scans requested before date (inclusive).
            format: date-time
            type: string
        - description: Filter scans by URL of _any_ request made by the webpage
          in: query
          name: url
          schema:
            description: Filter scans by URL of _any_ request made by the webpage
            example: https://example.com/?hello
            type: string
        - description: Filter scans by hostname of _any_ request made by the webpage.
          in: query
          name: hostname
          schema:
            description: Filter scans by hostname of _any_ request made by the webpage.
            example: example.com
            type: string
        - description: Filter scans by url path of _any_ request made by the webpage.
          in: query
          name: path
          schema:
            description: Filter scans by url path of _any_ request made by the webpage.
            example: /samples/subresource-integrity/
            type: string
        - description: >-
            Filter scans by IP address (IPv4 or IPv6) of _any_ request made by
            the webpage.
          in: query
          name: ip
          schema:
            description: >-
              Filter scans by IP address (IPv4 or IPv6) of _any_ request made by
              the webpage.
            example: 1.1.1.1
            type: string
        - description: Filter scans by hash of any html/js/css request made by the webpage.
          in: query
          name: hash
          schema:
            description: >-
              Filter scans by hash of any html/js/css request made by the
              webpage.
            type: string
        - description: Filter scans by submitted or scanned URL
          in: query
          name: page_url
          schema:
            description: Filter scans by submitted or scanned URL
            type: string
        - description: Filter scans by main page hostname (domain of effective URL).
          in: query
          name: page_hostname
          schema:
            description: Filter scans by main page hostname (domain of effective URL).
            type: string
        - description: >-
            Filter scans by exact match of effective URL path (also supports
            suffix search).
          in: query
          name: page_path
          schema:
            description: >-
              Filter scans by exact match of effective URL path (also supports
              suffix search).
            type: string
        - description: Filter scans by main page Autonomous System Number (ASN).
          in: query
          name: page_asn
          schema:
            description: Filter scans by main page Autonomous System Number (ASN).
            type: string
        - description: Filter scans by  main page IP address (IPv4 or IPv6).
          in: query
          name: page_ip
          schema:
            description: Filter scans by  main page IP address (IPv4 or IPv6).
            type: string
        - description: Return only scans created by account.
          in: query
          name: account_scans
          schema:
            description: Return only scans created by account.
            type: boolean
        - description: Filter scans by malicious verdict.
          in: query
          name: is_malicious
          schema:
            description: Filter scans by malicious verdict.
            type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          example: Error
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  messages:
                    items:
                      properties:
                        message:
                          example: OK
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  result:
                    properties:
                      tasks:
                        items:
                          properties:
                            country:
                              description: Alpha-2 country code
                              type: string
                            success:
                              description: Whether scan was successful or not
                              type: boolean
                            time:
                              description: When scan was submitted (UTC)
                              format: date-time
                              type: string
                            url:
                              description: Scan url (after redirects)
                              example: https://www.example.com/
                              type: string
                            uuid:
                              description: Scan id
                              format: uuid
                              type: string
                            visibility:
                              description: Submitted visibility status.
                              enum:
                                - public
                                - unlisted
                              example: public
                              type: string
                          required:
                            - uuid
                            - url
                            - success
                            - time
                            - country
                            - visibility
                          type: object
                        type: array
                    required:
                      - tasks
                    type: object
                  success:
                    description: Whether search request was successful or not
                    type: boolean
                required:
                  - messages
                  - errors
                  - success
                  - result
                type: object
          description: Search results
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          example: Scan ID is not a valid UUID.
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  messages:
                    items:
                      properties:
                        message:
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  success:
                    description: Whether request was successful or not
                    type: boolean
                required:
                  - messages
                  - errors
                  - success
                type: object
          description: Invalid params.
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Search URL scans
      tags:
        - URL Scanner (Deprecated)
      x-api-token-group:
        - URL Scanner Write
        - URL Scanner Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
      x-stainless-deprecation-message: >-
        Use
        [V2](https://developers.cloudflare.com/api/resources/url_scanner/subresources/scans/methods/list/)
        instead.
