openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/urlscanner/v2/screenshots/{scan_id}.png:
    get:
      description: Get scan's screenshot by resolution (desktop/mobile/tablet).
      operationId: urlscanner-get-scan-screenshot-v2
      parameters:
        - description: Scan UUID.
          in: path
          name: scan_id
          required: true
          schema:
            description: Scan UUID.
            format: uuid
            type: string
        - description: Account ID.
          in: path
          name: account_id
          required: true
          schema:
            description: Account ID.
            type: string
        - description: Target device type.
          in: query
          name: resolution
          schema:
            default: desktop
            description: Target device type.
            enum:
              - desktop
              - mobile
              - tablet
            type: string
      responses:
        '200':
          content:
            image/png:
              schema:
                description: PNG Image.
                type: string
          description: Returns the scan's requested screenshot.
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        detail:
                          type: string
                        status:
                          description: Status code.
                          example: 400
                          type: integer
                        title:
                          example: Invalid url
                          type: string
                      required:
                        - title
                        - detail
                        - status
                      type: object
                    type: array
                  message:
                    type: string
                  status:
                    description: Status code.
                    example: 400
                    type: integer
                required:
                  - message
                  - status
                  - errors
                type: object
          description: Invalid input.
        '404':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        detail:
                          example: Queued
                          type: string
                        status:
                          description: Status code.
                          example: 404
                          type: integer
                        title:
                          example: Scan is not finished yet.
                          type: string
                      required:
                        - title
                        - detail
                        - status
                      type: object
                    type: array
                  message:
                    description: Scan not found or in progress.
                    example: Scan is not finished yet.
                    type: string
                  status:
                    description: Status code.
                    example: 404
                    type: integer
                  task:
                    properties:
                      status:
                        example: Queued
                        type: string
                      time:
                        type: string
                      url:
                        type: string
                      uuid:
                        type: string
                      visibility:
                        example: public
                        type: string
                    required:
                      - uuid
                      - url
                      - time
                      - status
                      - visibility
                    type: object
                required:
                  - message
                  - status
                  - errors
                  - task
                type: object
          description: Scan not found or in progress.
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get screenshot
      tags:
        - URL Scanner
      x-api-token-group:
        - URL Scanner Write
        - URL Scanner Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
