openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/urlscanner/scan:
    post:
      deprecated: true
      description: >-
        Submit a URL to scan. You can also set some options, like the visibility
        level and custom headers. Check limits at
        https://developers.cloudflare.com/security-center/investigate/scan-limits/.
      operationId: urlscanner-create-scan
      parameters:
        - description: Account ID.
          in: path
          name: account_id
          required: true
          schema:
            description: Account ID.
            type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                country:
                  description: Country to geo egress from
                  enum:
                    - AF
                    - AL
                    - DZ
                    - AD
                    - AO
                    - AG
                    - AR
                    - AM
                    - AU
                    - AT
                    - AZ
                    - BH
                    - BD
                    - BB
                    - BY
                    - BE
                    - BZ
                    - BJ
                    - BM
                    - BT
                    - BO
                    - BA
                    - BW
                    - BR
                    - BN
                    - BG
                    - BF
                    - BI
                    - KH
                    - CM
                    - CA
                    - CV
                    - KY
                    - CF
                    - TD
                    - CL
                    - CN
                    - CO
                    - KM
                    - CG
                    - CR
                    - CI
                    - HR
                    - CU
                    - CY
                    - CZ
                    - CD
                    - DK
                    - DJ
                    - DM
                    - DO
                    - EC
                    - EG
                    - SV
                    - GQ
                    - ER
                    - EE
                    - SZ
                    - ET
                    - FJ
                    - FI
                    - FR
                    - GA
                    - GE
                    - DE
                    - GH
                    - GR
                    - GL
                    - GD
                    - GT
                    - GN
                    - GW
                    - GY
                    - HT
                    - HN
                    - HU
                    - IS
                    - IN
                    - ID
                    - IR
                    - IQ
                    - IE
                    - IL
                    - IT
                    - JM
                    - JP
                    - JO
                    - KZ
                    - KE
                    - KI
                    - KW
                    - KG
                    - LA
                    - LV
                    - LB
                    - LS
                    - LR
                    - LY
                    - LI
                    - LT
                    - LU
                    - MO
                    - MG
                    - MW
                    - MY
                    - MV
                    - ML
                    - MR
                    - MU
                    - MX
                    - FM
                    - MD
                    - MC
                    - MN
                    - MS
                    - MA
                    - MZ
                    - MM
                    - NA
                    - NR
                    - NP
                    - NL
                    - NZ
                    - NI
                    - NE
                    - NG
                    - KP
                    - MK
                    - 'NO'
                    - OM
                    - PK
                    - PS
                    - PA
                    - PG
                    - PY
                    - PE
                    - PH
                    - PL
                    - PT
                    - QA
                    - RO
                    - RU
                    - RW
                    - SH
                    - KN
                    - LC
                    - VC
                    - WS
                    - SM
                    - ST
                    - SA
                    - SN
                    - RS
                    - SC
                    - SL
                    - SK
                    - SI
                    - SB
                    - SO
                    - ZA
                    - KR
                    - SS
                    - ES
                    - LK
                    - SD
                    - SR
                    - SE
                    - CH
                    - SY
                    - TW
                    - TJ
                    - TZ
                    - TH
                    - BS
                    - GM
                    - TL
                    - TG
                    - TO
                    - TT
                    - TN
                    - TR
                    - TM
                    - UG
                    - UA
                    - AE
                    - GB
                    - US
                    - UY
                    - UZ
                    - VU
                    - VE
                    - VN
                    - YE
                    - ZM
                    - ZW
                  type: string
                customHeaders:
                  additionalProperties:
                    type: string
                  description: Set custom headers.
                  type: object
                screenshotsResolutions:
                  default:
                    - desktop
                  description: Take multiple screenshots targeting different device types.
                  items:
                    default: desktop
                    description: Device resolutions.
                    enum:
                      - desktop
                      - mobile
                      - tablet
                    type: string
                  type: array
                url:
                  example: https://www.example.com
                  type: string
                visibility:
                  default: Public
                  description: >-
                    The option `Public` means it will be included in listings
                    like recent scans and search results. `Unlisted` means it
                    will not be included in the aforementioned listings, users
                    will need to have the scan's ID to access it. A a scan will
                    be automatically marked as unlisted if it fails, if it
                    contains potential PII or other sensitive material.
                  enum:
                    - Public
                    - Unlisted
                  type: string
              required:
                - url
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          example: Submission unsuccessful
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  messages:
                    items:
                      properties:
                        message:
                          example: Submission successful
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  result:
                    properties:
                      time:
                        description: Time when url was submitted for scanning.
                        format: date-time
                        type: string
                      url:
                        description: >-
                          Canonical form of submitted URL. Use this if you want
                          to later search by URL.
                        type: string
                      uuid:
                        description: Scan ID.
                        format: uuid
                        type: string
                      visibility:
                        description: Submitted visibility status.
                        enum:
                          - public
                          - unlisted
                        example: public
                        type: string
                    required:
                      - visibility
                      - uuid
                      - url
                      - time
                    type: object
                  success:
                    type: boolean
                required:
                  - messages
                  - errors
                  - success
                  - result
                type: object
          description: Scan request accepted successfully.
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          example: Scan ID is not a valid UUID.
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  messages:
                    items:
                      properties:
                        message:
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  success:
                    description: Whether request was successful or not
                    type: boolean
                required:
                  - messages
                  - errors
                  - success
                type: object
          description: Invalid params.
        '409':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          example: Submission unsuccessful
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  messages:
                    items:
                      properties:
                        message:
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  result:
                    properties:
                      tasks:
                        items:
                          properties:
                            clientLocation:
                              description: Submitter location
                              example: PT
                              type: string
                            clientType:
                              enum:
                                - Site
                                - Automatic
                                - Api
                              type: string
                            effectiveUrl:
                              description: >-
                                URL of the primary request, after all HTTP
                                redirects
                              example: http://example.com/
                              type: string
                            errors:
                              items:
                                properties:
                                  message:
                                    type: string
                                required:
                                  - message
                                type: object
                              type: array
                            scannedFrom:
                              properties:
                                colo:
                                  description: IATA code of Cloudflare datacenter
                                  example: MAD
                                  type: string
                              required:
                                - colo
                              type: object
                            status:
                              enum:
                                - Queued
                                - InProgress
                                - InPostProcessing
                                - Finished
                              type: string
                            success:
                              example: true
                              type: boolean
                            time:
                              example: '2023-05-03T17:05:04.843Z'
                              type: string
                            timeEnd:
                              example: '2023-05-03T17:05:19.374Z'
                              type: string
                            url:
                              description: Submitted URL
                              example: http://example.com
                              type: string
                            uuid:
                              description: Scan ID
                              example: 2ee568d0-bf70-4827-b922-b7088c0f056f
                              type: string
                            visibility:
                              enum:
                                - Public
                                - Unlisted
                              type: string
                          required:
                            - uuid
                            - url
                            - status
                            - success
                            - errors
                            - time
                            - timeEnd
                            - visibility
                            - clientLocation
                            - clientType
                            - effectiveUrl
                            - scannedFrom
                          type: object
                        type: array
                    required:
                      - tasks
                    type: object
                  success:
                    example: true
                    type: boolean
                required:
                  - messages
                  - errors
                  - success
                  - result
                type: object
          description: 'Scan request denied: hostname was recently scanned.'
        '429':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          example: Submission unsuccessful
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  messages:
                    items:
                      properties:
                        message:
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  success:
                    example: true
                    type: boolean
                required:
                  - messages
                  - errors
                  - success
                type: object
          description: 'Scan request denied: rate limited.'
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Create URL Scan
      tags:
        - URL Scanner (Deprecated)
      x-api-token-group:
        - URL Scanner Write
        - URL Scanner Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
      x-stainless-deprecation-message: >-
        Use
        [V2](https://developers.cloudflare.com/api/resources/url_scanner/subresources/scans/methods/create/)
        instead.
