openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/urlscanner/v2/scan:
    post:
      description: >-
        Submit a URL to scan. Check limits at
        https://developers.cloudflare.com/security-center/investigate/scan-limits/.
      operationId: urlscanner-create-scan-v2
      parameters:
        - description: Account ID.
          in: path
          name: account_id
          required: true
          schema:
            description: Account ID.
            type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                country:
                  description: Country to geo egress from
                  enum:
                    - AF
                    - AL
                    - DZ
                    - AD
                    - AO
                    - AG
                    - AR
                    - AM
                    - AU
                    - AT
                    - AZ
                    - BH
                    - BD
                    - BB
                    - BY
                    - BE
                    - BZ
                    - BJ
                    - BM
                    - BT
                    - BO
                    - BA
                    - BW
                    - BR
                    - BN
                    - BG
                    - BF
                    - BI
                    - KH
                    - CM
                    - CA
                    - CV
                    - KY
                    - CF
                    - TD
                    - CL
                    - CN
                    - CO
                    - KM
                    - CG
                    - CR
                    - CI
                    - HR
                    - CU
                    - CY
                    - CZ
                    - CD
                    - DK
                    - DJ
                    - DM
                    - DO
                    - EC
                    - EG
                    - SV
                    - GQ
                    - ER
                    - EE
                    - SZ
                    - ET
                    - FJ
                    - FI
                    - FR
                    - GA
                    - GE
                    - DE
                    - GH
                    - GR
                    - GL
                    - GD
                    - GT
                    - GN
                    - GW
                    - GY
                    - HT
                    - HN
                    - HU
                    - IS
                    - IN
                    - ID
                    - IR
                    - IQ
                    - IE
                    - IL
                    - IT
                    - JM
                    - JP
                    - JO
                    - KZ
                    - KE
                    - KI
                    - KW
                    - KG
                    - LA
                    - LV
                    - LB
                    - LS
                    - LR
                    - LY
                    - LI
                    - LT
                    - LU
                    - MO
                    - MG
                    - MW
                    - MY
                    - MV
                    - ML
                    - MR
                    - MU
                    - MX
                    - FM
                    - MD
                    - MC
                    - MN
                    - MS
                    - MA
                    - MZ
                    - MM
                    - NA
                    - NR
                    - NP
                    - NL
                    - NZ
                    - NI
                    - NE
                    - NG
                    - KP
                    - MK
                    - 'NO'
                    - OM
                    - PK
                    - PS
                    - PA
                    - PG
                    - PY
                    - PE
                    - PH
                    - PL
                    - PT
                    - QA
                    - RO
                    - RU
                    - RW
                    - SH
                    - KN
                    - LC
                    - VC
                    - WS
                    - SM
                    - ST
                    - SA
                    - SN
                    - RS
                    - SC
                    - SL
                    - SK
                    - SI
                    - SB
                    - SO
                    - ZA
                    - KR
                    - SS
                    - ES
                    - LK
                    - SD
                    - SR
                    - SE
                    - CH
                    - SY
                    - TW
                    - TJ
                    - TZ
                    - TH
                    - BS
                    - GM
                    - TL
                    - TG
                    - TO
                    - TT
                    - TN
                    - TR
                    - TM
                    - UG
                    - UA
                    - AE
                    - GB
                    - US
                    - UY
                    - UZ
                    - VU
                    - VE
                    - VN
                    - YE
                    - ZM
                    - ZW
                  type: string
                customHeaders:
                  additionalProperties:
                    type: string
                  description: Set custom headers.
                  type: object
                customagent:
                  maxLength: 4096
                  type: string
                referer:
                  maxLength: 4096
                  type: string
                screenshotsResolutions:
                  default:
                    - desktop
                  description: Take multiple screenshots targeting different device types.
                  items:
                    default: desktop
                    description: Device resolutions.
                    enum:
                      - desktop
                      - mobile
                      - tablet
                    type: string
                  type: array
                url:
                  example: https://www.example.com
                  type: string
                visibility:
                  default: Public
                  description: >-
                    The option `Public` means it will be included in listings
                    like recent scans and search results. `Unlisted` means it
                    will not be included in the aforementioned listings, users
                    will need to have the scan's ID to access it. A a scan will
                    be automatically marked as unlisted if it fails, if it
                    contains potential PII or other sensitive material.
                  enum:
                    - Public
                    - Unlisted
                  type: string
              required:
                - url
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  api:
                    description: URL to api report.
                    type: string
                  message:
                    example: Submission successful
                    type: string
                  options:
                    properties:
                      useragent:
                        type: string
                    type: object
                  result:
                    description: Public URL to report.
                    type: string
                  url:
                    description: >-
                      Canonical form of submitted URL. Use this if you want to
                      later search by URL.
                    type: string
                    x-auditable: true
                  uuid:
                    description: Scan ID.
                    format: uuid
                    type: string
                    x-auditable: true
                  visibility:
                    description: Submitted visibility status.
                    enum:
                      - public
                      - unlisted
                    example: public
                    type: string
                required:
                  - message
                  - uuid
                  - result
                  - api
                  - visibility
                  - url
                type: object
          description: Scan request accepted successfully.
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        detail:
                          type: string
                        status:
                          description: Status code.
                          example: 400
                          type: integer
                        title:
                          example: Invalid url
                          type: string
                      required:
                        - title
                        - detail
                        - status
                      type: object
                    type: array
                  message:
                    type: string
                  status:
                    description: Status code.
                    example: 400
                    type: integer
                required:
                  - message
                  - status
                  - errors
                type: object
          description: Invalid input.
        '409':
          content:
            application/json:
              schema:
                properties:
                  description:
                    example: 'Scan request denied: hostname was recently scanned'
                    type: string
                  errors:
                    items:
                      properties:
                        detail:
                          example: DNS Error - Could not resolve domain.
                          type: string
                        status:
                          example: 400
                          type: number
                        title:
                          example: DNS Error - Could not resolve domain.
                          type: string
                      required:
                        - title
                        - detail
                        - status
                      type: object
                    type: array
                  message:
                    example: Scan prevented ...
                    type: string
                  status:
                    example: 409
                    type: number
                required:
                  - message
                  - status
                  - errors
                type: object
          description: 'Scan request denied: hostname was recently scanned.'
        '429':
          content:
            application/json:
              schema:
                properties:
                  description:
                    type: string
                  errors:
                    items:
                      properties:
                        detail:
                          example: DNS Error - Could not resolve domain.
                          type: string
                        status:
                          example: 400
                          type: number
                        title:
                          example: DNS Error - Could not resolve domain.
                          type: string
                      required:
                        - title
                        - detail
                        - status
                      type: object
                    type: array
                  message:
                    type: string
                  status:
                    example: 429
                    type: number
                required:
                  - message
                  - status
                  - errors
                type: object
          description: 'Scan request denied: rate limited.'
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Create URL Scan
      tags:
        - URL Scanner
      x-api-token-group:
        - URL Scanner Write
        - URL Scanner Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
