openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/firewall/ua_rules:
    post:
      description: Creates a new User Agent Blocking rule in a zone.
      operationId: user-agent-blocking-rules-create-a-user-agent-blocking-rule
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            description: Defines an identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                configuration:
                  properties:
                    target:
                      description: >-
                        The configuration target. You must set the target to
                        `ua` when specifying a user agent in the rule.
                      enum:
                        - ua
                      example: ua
                      type: string
                    value:
                      description: the user agent to exactly match
                      example: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)
                      type: string
                      x-auditable: true
                  title: A user agent configuration.
                  type: object
                description:
                  description: >-
                    An informative summary of the rule. This value is sanitized
                    and any tags will be removed.
                  example: >-
                    Prevent multiple login failures to mitigate brute force
                    attacks
                  maxLength: 1024
                  type: string
                  x-auditable: true
                mode:
                  description: The action to apply to a matched request.
                  enum:
                    - block
                    - challenge
                    - whitelist
                    - js_challenge
                    - managed_challenge
                  example: challenge
                  type: string
                  x-auditable: true
                paused:
                  description: When true, indicates that the rule is currently paused.
                  example: false
                  type: boolean
                  x-auditable: true
              required:
                - mode
                - configuration
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      result:
                        properties:
                          configuration:
                            description: The configuration object for the current rule.
                            properties:
                              target:
                                description: >-
                                  The configuration target for this rule. You
                                  must set the target to `ua` for User Agent
                                  Blocking rules.
                                example: ua
                                type: string
                              value:
                                description: >-
                                  The exact user agent string to match. This
                                  value will be compared to the received
                                  `User-Agent` HTTP header value.
                                example: >-
                                  Mozilla/5.0 (Macintosh; Intel Mac OS X
                                  10_12_5) AppleWebKit/603.2.4 (KHTML, like
                                  Gecko) Version/10.1.1 Safari/603.2.4
                                type: string
                            type: object
                          description:
                            description: An informative summary of the rule.
                            example: >-
                              Prevent access from abusive clients identified by
                              this User Agent to mitigate a DDoS attack
                            maxLength: 1024
                            type: string
                          id:
                            description: >-
                              The unique identifier of the User Agent Blocking
                              rule.
                            example: 372e67954025e0ba6aaa6d586b9e0b59
                            maxLength: 32
                            readOnly: true
                            type: string
                            x-auditable: true
                          mode:
                            description: The action to apply to a matched request.
                            enum:
                              - block
                              - challenge
                              - js_challenge
                              - managed_challenge
                            example: js_challenge
                            maxLength: 12
                          paused:
                            description: >-
                              When true, indicates that the rule is currently
                              paused.
                            example: false
                            type: boolean
                            x-auditable: true
                        type: object
                    type: object
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          result:
                            anyOf:
                              - type: object
                              - items:
                                  type: object
                                type: array
                              - type: string
                          success:
                            description: Defines whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                          - result
                        type: object
                      - properties:
                          result:
                            anyOf:
                              - nullable: true
                                type: object
                              - nullable: true
                                type: string
                        type: object
                    type: object
          description: Create a User Agent Blocking rule response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          result:
                            properties:
                              configuration:
                                description: The configuration object for the current rule.
                                properties:
                                  target:
                                    description: >-
                                      The configuration target for this rule.
                                      You must set the target to `ua` for User
                                      Agent Blocking rules.
                                    example: ua
                                    type: string
                                  value:
                                    description: >-
                                      The exact user agent string to match. This
                                      value will be compared to the received
                                      `User-Agent` HTTP header value.
                                    example: >-
                                      Mozilla/5.0 (Macintosh; Intel Mac OS X
                                      10_12_5) AppleWebKit/603.2.4 (KHTML, like
                                      Gecko) Version/10.1.1 Safari/603.2.4
                                    type: string
                                type: object
                              description:
                                description: An informative summary of the rule.
                                example: >-
                                  Prevent access from abusive clients identified
                                  by this User Agent to mitigate a DDoS attack
                                maxLength: 1024
                                type: string
                              id:
                                description: >-
                                  The unique identifier of the User Agent
                                  Blocking rule.
                                example: 372e67954025e0ba6aaa6d586b9e0b59
                                maxLength: 32
                                readOnly: true
                                type: string
                                x-auditable: true
                              mode:
                                description: The action to apply to a matched request.
                                enum:
                                  - block
                                  - challenge
                                  - js_challenge
                                  - managed_challenge
                                example: js_challenge
                                maxLength: 12
                              paused:
                                description: >-
                                  When true, indicates that the rule is
                                  currently paused.
                                example: false
                                type: boolean
                                x-auditable: true
                            type: object
                        type: object
                      - allOf:
                          - properties:
                              errors:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    message:
                                      type: string
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              messages:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    message:
                                      type: string
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              result:
                                anyOf:
                                  - type: object
                                  - items:
                                      type: object
                                    type: array
                                  - type: string
                              success:
                                description: Defines whether the API call was successful.
                                enum:
                                  - true
                                example: true
                                type: boolean
                            required:
                              - success
                              - errors
                              - messages
                              - result
                            type: object
                          - properties:
                              result:
                                anyOf:
                                  - nullable: true
                                    type: object
                                  - nullable: true
                                    type: string
                            type: object
                        type: object
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Defines whether the API call was successful.
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
          description: Create a User Agent Blocking rule response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create a User Agent Blocking rule
      tags:
        - User Agent Blocking rules
      x-api-token-group:
        - Firewall Services Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
