openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /user/invites/{invite_id}:
    get:
      description: Gets the details of an invitation.
      operationId: user'-s-invites-invitation-details
      parameters:
        - in: path
          name: invite_id
          required: true
          schema:
            description: Invite identifier tag.
            example: 4f5f0c14a2a41d5063dd301b2f829f04
            maxLength: 32
            readOnly: true
            type: string
            x-auditable: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                        type: object
                    type: object
                  - properties:
                      result:
                        properties:
                          expires_on:
                            description: When the invite is no longer active.
                            example: '2014-01-01T05:20:00Z'
                            format: date-time
                            readOnly: true
                            type: string
                            x-auditable: true
                          id:
                            description: Invite identifier tag.
                            example: 4f5f0c14a2a41d5063dd301b2f829f04
                            maxLength: 32
                            readOnly: true
                            type: string
                            x-auditable: true
                          invited_by:
                            description: >-
                              The email address of the user who created the
                              invite.
                            example: user@example.com
                            maxLength: 90
                            type: string
                            x-auditable: true
                          invited_member_email:
                            description: >-
                              Email address of the user to add to the
                              organization.
                            example: user@example.com
                            maxLength: 90
                            type: string
                            x-auditable: true
                          invited_member_id:
                            description: ID of the user to add to the organization.
                            example: 5a7805061c76ada191ed06f989cc3dac
                            maxLength: 32
                            nullable: true
                            readOnly: true
                            type: string
                            x-auditable: true
                          invited_on:
                            description: When the invite was sent.
                            example: '2014-01-01T05:20:00Z'
                            format: date-time
                            readOnly: true
                            type: string
                            x-auditable: true
                          organization_id:
                            description: ID of the organization the user will be added to.
                            example: 5a7805061c76ada191ed06f989cc3dac
                            maxLength: 32
                            readOnly: true
                            type: string
                            x-auditable: true
                          organization_is_enforcing_twofactor:
                            example: true
                            type: boolean
                            x-auditable: true
                          organization_name:
                            description: Organization name.
                            example: Cloudflare, Inc.
                            maxLength: 100
                            readOnly: true
                            type: string
                            x-auditable: true
                          roles:
                            description: >-
                              List of role names the membership has for this
                              account.
                            items:
                              example: Account Administrator
                              maxLength: 120
                              type: string
                              x-auditable: true
                            readOnly: true
                            type: array
                          status:
                            description: Current status of the invitation.
                            enum:
                              - pending
                              - accepted
                              - rejected
                              - expired
                            example: accepted
                            x-auditable: true
                        required:
                          - invited_member_id
                          - organization_id
                        type: object
                    type: object
          description: Invitation Details response
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    minLength: 1
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: Invitation Details response failure
      security:
        - api_email: []
          api_key: []
      summary: Invitation Details
      tags:
        - User's Invites
      x-api-token-group:
        - Memberships Write
        - Memberships Read
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
