openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /user:
    get:
      operationId: user-user-details
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                        type: object
                    type: object
                  - properties:
                      result:
                        properties:
                          betas:
                            description: Lists the betas that the user is participating in.
                            items:
                              description: User feature flag
                              example: zone_level_access_beta
                              type: string
                            readOnly: true
                            type: array
                          country:
                            description: The country in which the user lives.
                            example: US
                            maxLength: 30
                            nullable: true
                            type: string
                          first_name:
                            description: User's first name
                            example: John
                            maxLength: 60
                            nullable: true
                            type: string
                            x-auditable: true
                          has_business_zones:
                            default: false
                            description: Indicates whether user has any business zones
                            readOnly: true
                            type: boolean
                          has_enterprise_zones:
                            default: false
                            description: Indicates whether user has any enterprise zones
                            readOnly: true
                            type: boolean
                          has_pro_zones:
                            default: false
                            description: Indicates whether user has any pro zones
                            readOnly: true
                            type: boolean
                          id:
                            description: Identifier of the user.
                            example: 6d7f2f5f5b1d4a0e9081fdc98d432fd1
                            readOnly: true
                            type: string
                          last_name:
                            description: User's last name
                            example: Appleseed
                            maxLength: 60
                            nullable: true
                            type: string
                            x-auditable: true
                          organizations:
                            items:
                              properties:
                                id:
                                  description: Identifier
                                  example: 023e105f4ecef8ad9ca31a8372d0c353
                                  maxLength: 32
                                  minLength: 32
                                  type: string
                                  x-auditable: true
                                name:
                                  description: Organization name.
                                  example: Cloudflare, Inc.
                                  maxLength: 100
                                  type: string
                                  x-auditable: true
                                permissions:
                                  description: Access permissions for this User.
                                  items:
                                    example: '#zones:read'
                                    maxLength: 160
                                    type: string
                                    x-auditable: true
                                  readOnly: true
                                  type: array
                                roles:
                                  description: >-
                                    List of roles that a user has within an
                                    organization.
                                  items:
                                    example: All Privileges - Super Administrator
                                    maxLength: 120
                                    type: string
                                    x-auditable: true
                                  readOnly: true
                                  type: array
                                status:
                                  description: >-
                                    Whether the user is a member of the
                                    organization or has an invitation pending.
                                  enum:
                                    - member
                                    - invited
                                  example: member
                                  type: string
                                  x-auditable: true
                              type: object
                            type: array
                          suspended:
                            default: false
                            description: Indicates whether user has been suspended
                            readOnly: true
                            type: boolean
                          telephone:
                            description: User's telephone number
                            example: +1 123-123-1234
                            maxLength: 20
                            nullable: true
                            type: string
                          two_factor_authentication_enabled:
                            default: false
                            description: >-
                              Indicates whether two-factor authentication is
                              enabled for the user account. Does not apply to
                              API authentication.
                            readOnly: true
                            type: boolean
                          two_factor_authentication_locked:
                            default: false
                            description: >-
                              Indicates whether two-factor authentication is
                              required by one of the accounts that the user is a
                              member of.
                            readOnly: true
                            type: boolean
                          zipcode:
                            description: The zipcode or postal code where the user lives.
                            example: '12345'
                            maxLength: 20
                            nullable: true
                            type: string
                        type: object
                    type: object
          description: User Details response
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    minLength: 1
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: User Details response failure
      security:
        - api_email: []
          api_key: []
      summary: User Details
      tags:
        - User
      x-api-token-group:
        - User Details Write
        - User Details Read
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.api.user.read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
