openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/waiting_rooms/preview:
    post:
      description: "Creates a waiting room page preview. Upload a custom waiting room page for preview. You will receive a preview URL in the form `http://waitingrooms.dev/preview/<uuid>`. You can use the following query parameters to change the state of the preview:\n1. `force_queue`: Boolean indicating if all users will be queued in the waiting room and no one will be let into the origin website (also known as queueAll).\n2. `queue_is_full`: Boolean indicating if the waiting room's queue is currently full and not accepting new users at the moment.\n3. `queueing_method`: The queueing method currently used by the waiting room.\n\t- **fifo** indicates a FIFO queue.\n\t- **random** indicates a Random queue.\n\t- **passthrough** indicates a Passthrough queue. Keep in mind that the waiting room page will only be displayed if `force_queue=true` or `event=prequeueing` — for other cases the request will pass through to the origin. For our preview, this will be a fake origin website returning \\\"Welcome\\\". \n\t- **reject** indicates a Reject queue.\n4. `event`: Used to preview a waiting room event.\n\t- **none** indicates no event is occurring.\n\t- **prequeueing** indicates that an event is prequeueing (between `prequeue_start_time` and `event_start_time`).\n\t- **started** indicates that an event has started (between `event_start_time` and `event_end_time`).\n5. `shuffle_at_event_start`: Boolean indicating if the event will shuffle users in the prequeue when it starts. This can only be set to **true** if an event is active (`event` is not **none**).\n\nFor example, you can make a request to `http://waitingrooms.dev/preview/<uuid>?force_queue=false&queue_is_full=false&queueing_method=random&event=started&shuffle_at_event_start=true`\n6. `waitTime`: Non-zero, positive integer indicating the estimated wait time in minutes. The default value is 10 minutes.\n\nFor example, you can make a request to `http://waitingrooms.dev/preview/<uuid>?waitTime=50` to configure the estimated wait time as 50 minutes."
      operationId: waiting-room-create-a-custom-waiting-room-page-preview
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            description: Identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
            x-auditable: true
      requestBody:
        content:
          application/json:
            schema:
              properties:
                custom_html:
                  default: ''
                  description: >-
                    Only available for the Waiting Room Advanced subscription.
                    This is a template html file that will be rendered at the
                    edge. If no custom_page_html is provided, the default
                    waiting room will be used. The template is based on mustache
                    ( https://mustache.github.io/ ). There are several variables
                    that are evaluated by the Cloudflare edge:

                    1. {{`waitTimeKnown`}} Acts like a boolean value that
                    indicates the behavior to take when wait time is not
                    available, for instance when queue_all is **true**.

                    2. {{`waitTimeFormatted`}} Estimated wait time for the user.
                    For example, five minutes. Alternatively, you can use:

                    3. {{`waitTime`}} Number of minutes of estimated wait for a
                    user.

                    4. {{`waitTimeHours`}} Number of hours of estimated wait for
                    a user (`Math.floor(waitTime/60)`).

                    5. {{`waitTimeHourMinutes`}} Number of minutes above the
                    `waitTimeHours` value (`waitTime%60`).

                    6. {{`queueIsFull`}} Changes to **true** when no more people
                    can be added to the queue.


                    To view the full list of variables, look at the
                    `cfWaitingRoom` object described under the
                    `json_response_enabled` property in other Waiting Room API
                    calls.
                  example: >-
                    {{#waitTimeKnown}} {{waitTime}} mins {{/waitTimeKnown}}
                    {{^waitTimeKnown}} Queue all enabled {{/waitTimeKnown}}
                  type: string
                  x-auditable: true
              required:
                - custom_html
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - required:
                          - success
                          - errors
                          - messages
                          - result
                        type: object
                      - properties:
                          result:
                            oneOf:
                              - type: object
                              - type: string
                            type: object
                        type: object
                    type: object
                  - properties:
                      result:
                        properties:
                          preview_url:
                            description: >-
                              URL where the custom waiting room page can
                              temporarily be previewed.
                            example: >-
                              http://waitingrooms.dev/preview/35af8c12-6d68-4608-babb-b53435a5ddfb
                            type: string
                            x-auditable: true
                        type: object
                    type: object
                type: object
          description: Create a custom waiting room page preview response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - allOf:
                          - required:
                              - success
                              - errors
                              - messages
                              - result
                            type: object
                          - properties:
                              result:
                                oneOf:
                                  - type: object
                                  - type: string
                                type: object
                            type: object
                        type: object
                      - properties:
                          result:
                            properties:
                              preview_url:
                                description: >-
                                  URL where the custom waiting room page can
                                  temporarily be previewed.
                                example: >-
                                  http://waitingrooms.dev/preview/35af8c12-6d68-4608-babb-b53435a5ddfb
                                type: string
                                x-auditable: true
                            type: object
                        type: object
                    type: object
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
                type: object
          description: Create a custom waiting room page preview response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Create a custom waiting room page preview
      tags:
        - Waiting Room
      x-api-token-group:
        - Waiting Rooms Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
