openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/waiting_rooms/{waiting_room_id}/status:
    get:
      description: "Fetches the status of a configured waiting room. Response fields include:\n1. `status`: String indicating the status of the waiting room. The possible status are:\n\t- **not_queueing** indicates that the configured thresholds have not been met and all users are going through to the origin.\n\t- **queueing** indicates that the thresholds have been met and some users are held in the waiting room.\n\t- **event_prequeueing** indicates that an event is active and is currently prequeueing users before it starts.\n\t- **suspended** indicates that the room is suspended.\n2. `event_id`: String of the current event's `id` if an event is active, otherwise an empty string.\n3. `estimated_queued_users`: Integer of the estimated number of users currently waiting in the queue.\n4. `estimated_total_active_users`: Integer of the estimated number of users currently active on the origin.\n5. `max_estimated_time_minutes`: Integer of the maximum estimated time currently presented to the users."
      operationId: waiting-room-get-waiting-room-status
      parameters:
        - in: path
          name: waiting_room_id
          required: true
          schema:
            example: 699d98642c564d2e855e9661899b7252
            type: string
            x-auditable: true
        - in: path
          name: zone_id
          required: true
          schema:
            description: Identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
            x-auditable: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - required:
                          - success
                          - errors
                          - messages
                          - result
                        type: object
                      - properties:
                          result:
                            oneOf:
                              - type: object
                              - type: string
                            type: object
                        type: object
                    type: object
                  - properties:
                      result:
                        properties:
                          estimated_queued_users:
                            type: integer
                            x-auditable: true
                          estimated_total_active_users:
                            type: integer
                            x-auditable: true
                          event_id:
                            example: 25756b2dfe6e378a06b033b670413757
                            type: string
                            x-auditable: true
                          max_estimated_time_minutes:
                            type: integer
                            x-auditable: true
                          status:
                            enum:
                              - event_prequeueing
                              - not_queueing
                              - queueing
                              - suspended
                            example: queueing
                            type: string
                            x-auditable: true
                        type: object
                    type: object
                type: object
          description: Get waiting room status response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - allOf:
                          - required:
                              - success
                              - errors
                              - messages
                              - result
                            type: object
                          - properties:
                              result:
                                oneOf:
                                  - type: object
                                  - type: string
                                type: object
                            type: object
                        type: object
                      - properties:
                          result:
                            properties:
                              estimated_queued_users:
                                type: integer
                                x-auditable: true
                              estimated_total_active_users:
                                type: integer
                                x-auditable: true
                              event_id:
                                example: 25756b2dfe6e378a06b033b670413757
                                type: string
                                x-auditable: true
                              max_estimated_time_minutes:
                                type: integer
                                x-auditable: true
                              status:
                                enum:
                                  - event_prequeueing
                                  - not_queueing
                                  - queueing
                                  - suspended
                                example: queueing
                                type: string
                                x-auditable: true
                            type: object
                        type: object
                    type: object
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
                type: object
          description: Get waiting room status response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get waiting room status
      tags:
        - Waiting Room
      x-api-token-group:
        - Waiting Rooms Read
        - Waiting Rooms Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: false
