openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/rum/site_info:
    post:
      description: Creates a new Web Analytics site.
      operationId: web-analytics-create-site
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
            x-auditable: true
      requestBody:
        content:
          application/json:
            schema:
              properties:
                auto_install:
                  description: >-
                    If enabled, the JavaScript snippet is automatically injected
                    for orange-clouded sites.
                  example: true
                  type: boolean
                  x-auditable: true
                host:
                  description: The hostname to use for gray-clouded sites.
                  example: example.com
                  type: string
                  x-auditable: true
                zone_tag:
                  description: The zone identifier.
                  example: 023e105f4ecef8ad9ca31a8372d0c353
                  type: string
                  x-auditable: true
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      messages:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      success:
                        description: Whether the API call was successful.
                        example: true
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                    type: object
                  - properties:
                      result:
                        properties:
                          auto_install:
                            description: >-
                              If enabled, the JavaScript snippet is
                              automatically injected for orange-clouded sites.
                            example: true
                            type: boolean
                            x-auditable: true
                          created:
                            example: '2014-01-01T05:20:00.12345Z'
                            format: date-time
                            readOnly: true
                            type: string
                            x-auditable: true
                          rules:
                            description: A list of rules.
                            items:
                              properties:
                                created:
                                  example: '2014-01-01T05:20:00.12345Z'
                                  format: date-time
                                  readOnly: true
                                  type: string
                                  x-auditable: true
                                host:
                                  description: The hostname the rule will be applied to.
                                  example: example.com
                                  type: string
                                  x-auditable: true
                                id:
                                  description: The Web Analytics rule identifier.
                                  example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
                                  type: string
                                  x-auditable: true
                                inclusive:
                                  description: >-
                                    Whether the rule includes or excludes
                                    traffic from being measured.
                                  example: true
                                  type: boolean
                                  x-auditable: true
                                is_paused:
                                  description: Whether the rule is paused or not.
                                  example: false
                                  type: boolean
                                  x-auditable: true
                                paths:
                                  description: The paths the rule will be applied to.
                                  example:
                                    - '*'
                                  items:
                                    type: string
                                    x-auditable: true
                                  type: array
                                priority:
                                  example: 1000
                                  type: number
                                  x-auditable: true
                              type: object
                            type: array
                          ruleset:
                            properties:
                              enabled:
                                description: Whether the ruleset is enabled.
                                example: true
                                type: boolean
                              id:
                                description: The Web Analytics ruleset identifier.
                                example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
                                type: string
                                x-auditable: true
                              zone_name:
                                example: example.com
                                type: string
                              zone_tag:
                                description: The zone identifier.
                                example: 023e105f4ecef8ad9ca31a8372d0c353
                                type: string
                                x-auditable: true
                            type: object
                          site_tag:
                            description: The Web Analytics site identifier.
                            example: 023e105f4ecef8ad9ca31a8372d0c353
                            type: string
                            x-auditable: true
                          site_token:
                            description: The Web Analytics site token.
                            example: 023e105f4ecef8ad9ca31a8372d0c353
                            type: string
                            x-auditable: true
                          snippet:
                            description: Encoded JavaScript snippet.
                            example: >-
                              <!-- Cloudflare Web Analytics --><script defer
                              src='https://static.cloudflareinsights.com/beacon.min.js'
                              data-cf-beacon='{"token":
                              "bc40a2d1b5834453aba85c1b9a3054da"}'></script><!--
                              End Cloudflare Web Analytics -->
                            type: string
                            x-auditable: true
                        type: object
                    type: object
          description: Created Web Analytics site.
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    minLength: 1
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: Failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create a Web Analytics site
      tags:
        - Web Analytics
      x-api-token-group:
        - Account Settings Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
