openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/workers/domains:
    get:
      description: Lists all Worker Domains for an account.
      operationId: worker-domain-list-domains
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            description: Identifer of the account.
            example: 9a7806061c88ada191ed06f989cc3dac
            type: string
            x-auditable: true
        - in: query
          name: zone_name
          schema:
            description: Name of the zone.
            example: example.com
            type: string
            x-auditable: true
        - in: query
          name: service
          schema:
            description: Worker service associated with the zone and hostname.
            example: foo
            type: string
            x-auditable: true
        - in: query
          name: zone_id
          schema:
            description: Identifier of the zone.
            example: 593c9c94de529bbbfaac7c53ced0447d
            type: string
            x-auditable: true
        - in: query
          name: hostname
          schema:
            description: Hostname of the Worker Domain.
            example: foo.example.com
            type: string
        - in: query
          name: environment
          schema:
            description: Worker environment associated with the zone and hostname.
            example: production
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      messages:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - true
                        example: true
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                    type: object
                  - properties:
                      result:
                        items:
                          properties:
                            environment:
                              description: >-
                                Worker environment associated with the zone and
                                hostname.
                              example: production
                              type: string
                              x-auditable: true
                            hostname:
                              description: Hostname of the Worker Domain.
                              example: foo.example.com
                              type: string
                              x-auditable: true
                            id:
                              description: Identifer of the Worker Domain.
                              example: dbe10b4bc17c295377eabd600e1787fd
                              type: string
                              x-auditable: true
                            service:
                              description: >-
                                Worker service associated with the zone and
                                hostname.
                              example: foo
                              type: string
                              x-auditable: true
                            zone_id:
                              description: Identifier of the zone.
                              example: 593c9c94de529bbbfaac7c53ced0447d
                              type: string
                              x-auditable: true
                            zone_name:
                              description: Name of the zone.
                              example: example.com
                              type: string
                              x-auditable: true
                          type: object
                        type: array
                    type: object
          description: List Domains response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                        type: object
                      - properties:
                          result:
                            items:
                              properties:
                                environment:
                                  description: >-
                                    Worker environment associated with the zone
                                    and hostname.
                                  example: production
                                  type: string
                                  x-auditable: true
                                hostname:
                                  description: Hostname of the Worker Domain.
                                  example: foo.example.com
                                  type: string
                                  x-auditable: true
                                id:
                                  description: Identifer of the Worker Domain.
                                  example: dbe10b4bc17c295377eabd600e1787fd
                                  type: string
                                  x-auditable: true
                                service:
                                  description: >-
                                    Worker service associated with the zone and
                                    hostname.
                                  example: foo
                                  type: string
                                  x-auditable: true
                                zone_id:
                                  description: Identifier of the zone.
                                  example: 593c9c94de529bbbfaac7c53ced0447d
                                  type: string
                                  x-auditable: true
                                zone_name:
                                  description: Name of the zone.
                                  example: example.com
                                  type: string
                                  x-auditable: true
                              type: object
                            type: array
                        type: object
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
          description: List Domains response failure.
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: List Domains
      tags:
        - Worker Domain
      x-api-token-group:
        - Workers Scripts Write
        - Workers Scripts Read
