openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/storage/kv/namespaces/{namespace_id}/keys:
    get:
      description: Lists a namespace's keys.
      operationId: workers-kv-namespace-list-a-namespace'-s-keys
      parameters:
        - in: path
          name: namespace_id
          required: true
          schema:
            description: Namespace identifier tag.
            example: 0f2ac74b498b48028cb68387c421e279
            maxLength: 32
            readOnly: true
            type: string
            x-auditable: true
        - in: path
          name: account_id
          required: true
          schema:
            description: Identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
            x-auditable: true
        - in: query
          name: limit
          schema:
            default: 1000
            description: >-
              Limits the number of keys returned in the response. The cursor
              attribute may be used to iterate over the next batch of keys if
              there are more than the limit.
            maximum: 1000
            minimum: 10
            type: number
        - in: query
          name: prefix
          schema:
            description: >-
              Filters returned keys by a name prefix. Exact matches and any key
              names that begin with the prefix will be returned.
            example: My-Prefix
            type: string
        - in: query
          name: cursor
          schema:
            description: >-
              Opaque token indicating the position from which to continue when
              requesting the next set of records if the amount of list results
              was limited by the limit parameter. A valid value for the cursor
              can be obtained from the `cursors` object in the `result_info`
              structure.
            example: >-
              6Ck1la0VxJ0djhidm1MdX2FyDGxLKVeeHZZmORS_8XeSuhz9SjIJRaSa2lnsF01tQOHrfTGAP3R5X1Kv5iVUuMbNKhWNAXHOl6ePB0TUL8nw
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                        type: array
                        uniqueItems: true
                      messages:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                        type: array
                        uniqueItems: true
                      success:
                        description: Whether the API call was successful.
                        enum:
                          - true
                        example: true
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                    type: object
                  - properties:
                      result:
                        items:
                          description: >-
                            A name for a value. A value stored under a given key
                            may be retrieved via the same key.
                          properties:
                            expiration:
                              description: >-
                                The time, measured in number of seconds since
                                the UNIX epoch, at which the key will expire.
                                This property is omitted for keys that will not
                                expire.
                              example: 1577836800
                              type: number
                            metadata:
                              allOf:
                                - anyOf:
                                    - type: string
                                    - type: number
                                    - type: integer
                                    - type: boolean
                                    - additionalProperties: true
                                      nullable: true
                                      type: object
                                    - items:
                                        $ref: '#/components/schemas/workers-kv_any'
                                      type: array
                                  x-stainless-override-schema:
                                    type: unknown
                                - description: >-
                                    Arbitrary JSON that is associated with a
                                    key.
                                  example:
                                    someMetadataKey: someMetadataValue
                            name:
                              description: >-
                                A key's name. The name may be at most 512 bytes.
                                All printable, non-whitespace characters are
                                valid. Use percent-encoding to define key names
                                as part of a URL.
                              example: My-Key
                              maxLength: 512
                              type: string
                          required:
                            - name
                          type: object
                        type: array
                      result_info:
                        properties:
                          count:
                            description: >-
                              Total results returned based on your list
                              parameters.
                            example: 1
                            type: number
                          cursor:
                            description: >-
                              Opaque token indicating the position from which to
                              continue when requesting the next set of records
                              if the amount of list results was limited by the
                              limit parameter. A valid value for the cursor can
                              be obtained from the cursors object in the
                              result_info structure.
                            example: >-
                              6Ck1la0VxJ0djhidm1MdX2FyDGxLKVeeHZZmORS_8XeSuhz9SjIJRaSa2lnsF01tQOHrfTGAP3R5X1Kv5iVUuMbNKhWNAXHOl6ePB0TUL8nw
                            type: string
                        type: object
                    type: object
          description: List a Namespace's Keys response.
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                        type: array
                        uniqueItems: true
                    example:
                      - code: 7003
                        message: No route for the URI
                    minLength: 1
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                        type: array
                        uniqueItems: true
                    example: []
                  result:
                    nullable: true
                    type: object
                    x-stainless-empty-object: true
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: List a Namespace's Keys response failure.
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: List a Namespace's Keys
      tags:
        - Workers KV Namespace
      x-api-token-group:
        - Workers KV Storage Write
        - Workers KV Storage Read
components:
  schemas:
    workers-kv_any:
      anyOf:
        - type: string
        - type: number
        - type: integer
        - type: boolean
        - additionalProperties: true
          nullable: true
          type: object
        - items:
            $ref: '#/components/schemas/workers-kv_any'
          type: array
      x-stainless-override-schema:
        type: unknown
