openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/ai/run/@cf/deepseek-ai/deepseek-r1-distill-qwen-32b:
    post:
      operationId: workers-ai-post-run-cf-deepseek-ai-deepseek-r1-distill-qwen-32b
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            example: 023e105f4ecef8ad9ca31a8372d0c353
            type: string
            x-auditable: true
        - in: query
          name: queueRequest
          schema:
            example: 'true'
            type: string
            x-auditable: true
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - properties:
                    frequency_penalty:
                      description: >-
                        Decreases the likelihood of the model repeating the same
                        lines verbatim.
                      maximum: 2
                      minimum: -2
                      type: number
                    lora:
                      description: >-
                        Name of the LoRA (Low-Rank Adaptation) model to
                        fine-tune the base model.
                      type: string
                    max_tokens:
                      default: 256
                      description: >-
                        The maximum number of tokens to generate in the
                        response.
                      type: integer
                    presence_penalty:
                      description: >-
                        Increases the likelihood of the model introducing new
                        topics.
                      maximum: 2
                      minimum: -2
                      type: number
                    prompt:
                      description: >-
                        The input text prompt for the model to generate a
                        response.
                      minLength: 1
                      type: string
                    raw:
                      default: false
                      description: >-
                        If true, a chat template is not applied and you must
                        adhere to the specific model's expected formatting.
                      type: boolean
                    repetition_penalty:
                      description: >-
                        Penalty for repeated tokens; higher values discourage
                        repetition.
                      maximum: 2
                      minimum: 0
                      type: number
                    response_format:
                      properties:
                        json_schema: {}
                        type:
                          enum:
                            - json_object
                            - json_schema
                          type: string
                      title: JSON Mode
                      type: object
                    seed:
                      description: Random seed for reproducibility of the generation.
                      maximum: 9999999999
                      minimum: 1
                      type: integer
                    stream:
                      default: false
                      description: >-
                        If true, the response will be streamed back
                        incrementally using SSE, Server Sent Events.
                      type: boolean
                    temperature:
                      default: 0.6
                      description: >-
                        Controls the randomness of the output; higher values
                        produce more random results.
                      maximum: 5
                      minimum: 0
                      type: number
                    top_k:
                      description: >-
                        Limits the AI to choose from the top 'k' most probable
                        words. Lower values make responses more focused; higher
                        values introduce more variety and potential surprises.
                      maximum: 50
                      minimum: 1
                      type: integer
                    top_p:
                      description: >-
                        Adjusts the creativity of the AI's responses by
                        controlling how many possible words it considers. Lower
                        values make outputs more predictable; higher values
                        allow for more varied and creative responses.
                      maximum: 1
                      minimum: 0.001
                      type: number
                  required:
                    - prompt
                  title: Prompt
                - properties:
                    frequency_penalty:
                      description: >-
                        Decreases the likelihood of the model repeating the same
                        lines verbatim.
                      maximum: 2
                      minimum: -2
                      type: number
                    functions:
                      items:
                        properties:
                          code:
                            type: string
                          name:
                            type: string
                        required:
                          - name
                          - code
                        type: object
                      type: array
                    max_tokens:
                      default: 256
                      description: >-
                        The maximum number of tokens to generate in the
                        response.
                      type: integer
                    messages:
                      description: >-
                        An array of message objects representing the
                        conversation history.
                      items:
                        properties:
                          content:
                            description: The content of the message as a string.
                            type: string
                          role:
                            description: >-
                              The role of the message sender (e.g., 'user',
                              'assistant', 'system', 'tool').
                            type: string
                        required:
                          - role
                          - content
                        type: object
                      type: array
                    presence_penalty:
                      description: >-
                        Increases the likelihood of the model introducing new
                        topics.
                      maximum: 2
                      minimum: -2
                      type: number
                    raw:
                      default: false
                      description: >-
                        If true, a chat template is not applied and you must
                        adhere to the specific model's expected formatting.
                      type: boolean
                    repetition_penalty:
                      description: >-
                        Penalty for repeated tokens; higher values discourage
                        repetition.
                      maximum: 2
                      minimum: 0
                      type: number
                    response_format:
                      properties:
                        json_schema: {}
                        type:
                          enum:
                            - json_object
                            - json_schema
                          type: string
                      title: JSON Mode
                      type: object
                    seed:
                      description: Random seed for reproducibility of the generation.
                      maximum: 9999999999
                      minimum: 1
                      type: integer
                    stream:
                      default: false
                      description: >-
                        If true, the response will be streamed back
                        incrementally using SSE, Server Sent Events.
                      type: boolean
                    temperature:
                      default: 0.6
                      description: >-
                        Controls the randomness of the output; higher values
                        produce more random results.
                      maximum: 5
                      minimum: 0
                      type: number
                    tools:
                      description: A list of tools available for the assistant to use.
                      items:
                        oneOf:
                          - properties:
                              description:
                                description: A brief description of what the tool does.
                                type: string
                              name:
                                description: >-
                                  The name of the tool. More descriptive the
                                  better.
                                type: string
                              parameters:
                                description: >-
                                  Schema defining the parameters accepted by the
                                  tool.
                                properties:
                                  properties:
                                    additionalProperties:
                                      properties:
                                        description:
                                          description: A description of the expected parameter.
                                          type: string
                                        type:
                                          description: The data type of the parameter.
                                          type: string
                                      required:
                                        - type
                                        - description
                                      type: object
                                    description: Definitions of each parameter.
                                    type: object
                                  required:
                                    description: List of required parameter names.
                                    items:
                                      type: string
                                    type: array
                                  type:
                                    description: >-
                                      The type of the parameters object (usually
                                      'object').
                                    type: string
                                required:
                                  - type
                                  - properties
                                type: object
                            required:
                              - name
                              - description
                              - parameters
                          - properties:
                              function:
                                description: Details of the function tool.
                                properties:
                                  description:
                                    description: >-
                                      A brief description of what the function
                                      does.
                                    type: string
                                  name:
                                    description: The name of the function.
                                    type: string
                                  parameters:
                                    description: >-
                                      Schema defining the parameters accepted by
                                      the function.
                                    properties:
                                      properties:
                                        additionalProperties:
                                          properties:
                                            description:
                                              description: A description of the expected parameter.
                                              type: string
                                            type:
                                              description: The data type of the parameter.
                                              type: string
                                          required:
                                            - type
                                            - description
                                          type: object
                                        description: Definitions of each parameter.
                                        type: object
                                      required:
                                        description: List of required parameter names.
                                        items:
                                          type: string
                                        type: array
                                      type:
                                        description: >-
                                          The type of the parameters object
                                          (usually 'object').
                                        type: string
                                    required:
                                      - type
                                      - properties
                                    type: object
                                required:
                                  - name
                                  - description
                                  - parameters
                                type: object
                              type:
                                description: Specifies the type of tool (e.g., 'function').
                                type: string
                            required:
                              - type
                              - function
                        type: object
                      type: array
                    top_k:
                      description: >-
                        Limits the AI to choose from the top 'k' most probable
                        words. Lower values make responses more focused; higher
                        values introduce more variety and potential surprises.
                      maximum: 50
                      minimum: 1
                      type: integer
                    top_p:
                      description: >-
                        Adjusts the creativity of the AI's responses by
                        controlling how many possible words it considers. Lower
                        values make outputs more predictable; higher values
                        allow for more varied and creative responses.
                      maximum: 1
                      minimum: 0.001
                      type: number
                  required:
                    - messages
                  title: Messages
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
            text/event-stream:
              schema:
                type: object
          description: Object with user data.
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        code:
                          type: string
                        message:
                          type: string
                      required:
                        - code
                        - message
                      type: object
                    type: array
                  result:
                    type: object
                  success:
                    type: boolean
                required:
                  - errors
                  - success
                  - result
                type: object
          description: Bad request
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Execute @cf/deepseek-ai/deepseek-r1-distill-qwen-32b model.
      tags:
        - Workers AI Text Generation
      x-api-token-group:
        - Workers AI Write
        - Workers AI Read
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.api.account.ai
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
