openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/ai/finetunes:
    post:
      operationId: workers-ai-create-finetune
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            example: 023e105f4ecef8ad9ca31a8372d0c353
            type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                description:
                  type: string
                model:
                  type: string
                  x-auditable: true
                name:
                  type: string
                  x-auditable: true
                public:
                  default: false
                  type: boolean
                  x-auditable: true
              required:
                - model
                - name
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  result:
                    properties:
                      created_at:
                        format: date-time
                        type: string
                      description:
                        type: string
                      id:
                        format: uuid
                        type: string
                        x-auditable: true
                      model:
                        type: string
                        x-auditable: true
                      modified_at:
                        format: date-time
                        type: string
                      name:
                        type: string
                        x-auditable: true
                      public:
                        type: boolean
                        x-auditable: true
                    required:
                      - id
                      - created_at
                      - modified_at
                      - public
                      - name
                      - model
                    type: object
                  success:
                    type: boolean
                required:
                  - success
                  - result
                type: object
          description: Returns the created finetune
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      type: object
                    type: array
                  success:
                    type: boolean
                required:
                  - errors
                  - success
                type: object
          description: Finetune creation failed
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Create a new Finetune
      tags:
        - Workers AI Finetune
      x-api-token-group:
        - Workers AI Write
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.api.account.ai
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
