openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/gateway/configuration/custom_certificate:
    get:
      deprecated: true
      description: Fetches the current Zero Trust certificate configuration.
      operationId: zero-trust-accounts-get-zero-trust-certificate-configuration
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            example: 699d98642c564d2e855e9661899b7252
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                deprecated: true
                description: >-
                  Custom certificate settings for BYO-PKI. (deprecated and
                  replaced by `certificate`)
                nullable: true
                properties:
                  binding_status:
                    description: Certificate status (internal).
                    example: pending_deployment
                    readOnly: true
                    type: string
                    x-auditable: true
                  enabled:
                    description: >-
                      Enable use of custom certificate authority for signing
                      Gateway traffic.
                    example: true
                    nullable: true
                    type: boolean
                    x-auditable: true
                  id:
                    description: UUID of certificate (ID from MTLS certificate store).
                    example: d1b364c5-1311-466e-a194-f0e943e0799f
                    type: string
                    x-auditable: true
                  updated_at:
                    format: date-time
                    readOnly: true
                    type: string
                required:
                  - enabled
                type: object
                x-stainless-terraform-configurability: optional
          description: Get Zero Trust account configuration response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - deprecated: true
                    description: >-
                      Custom certificate settings for BYO-PKI. (deprecated and
                      replaced by `certificate`)
                    nullable: true
                    properties:
                      binding_status:
                        description: Certificate status (internal).
                        example: pending_deployment
                        readOnly: true
                        type: string
                        x-auditable: true
                      enabled:
                        description: >-
                          Enable use of custom certificate authority for signing
                          Gateway traffic.
                        example: true
                        nullable: true
                        type: boolean
                        x-auditable: true
                      id:
                        description: UUID of certificate (ID from MTLS certificate store).
                        example: d1b364c5-1311-466e-a194-f0e943e0799f
                        type: string
                        x-auditable: true
                      updated_at:
                        format: date-time
                        readOnly: true
                        type: string
                    required:
                      - enabled
                    type: object
                    x-stainless-terraform-configurability: optional
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                        type: object
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                        type: object
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
          description: Get Zero Trust account configuration response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get Zero Trust certificate configuration
      tags:
        - Zero Trust accounts
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
