openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/gateway/logging:
    put:
      description: Updates logging settings for the current Zero Trust account.
      operationId: zero-trust-accounts-update-logging-settings-for-the-zero-trust-account
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            example: 699d98642c564d2e855e9661899b7252
            type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                redact_pii:
                  default: false
                  description: >-
                    Redact personally identifiable information from activity
                    logging (PII fields are: source IP, user email, user ID,
                    device ID, URL, referrer, user agent).
                  example: true
                  type: boolean
                  x-auditable: true
                settings_by_rule_type:
                  description: Logging settings by rule type.
                  properties:
                    dns:
                      properties:
                        log_all:
                          default: false
                          description: Log all requests to this service.
                          example: false
                          type: boolean
                          x-auditable: true
                        log_blocks:
                          default: false
                          description: Log only blocking requests to this service.
                          example: true
                          type: boolean
                          x-auditable: true
                      type: object
                    http:
                      properties:
                        log_all:
                          default: false
                          description: Log all requests to this service.
                          example: false
                          type: boolean
                          x-auditable: true
                        log_blocks:
                          default: false
                          description: Log only blocking requests to this service.
                          example: true
                          type: boolean
                          x-auditable: true
                      type: object
                    l4:
                      properties:
                        log_all:
                          default: false
                          description: Log all requests to this service.
                          example: false
                          type: boolean
                          x-auditable: true
                        log_blocks:
                          default: false
                          description: Log only blocking requests to this service.
                          example: true
                          type: boolean
                          x-auditable: true
                      type: object
                  type: object
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                        type: object
                    type: object
                  - properties:
                      result:
                        properties:
                          redact_pii:
                            default: false
                            description: >-
                              Redact personally identifiable information from
                              activity logging (PII fields are: source IP, user
                              email, user ID, device ID, URL, referrer, user
                              agent).
                            example: true
                            type: boolean
                            x-auditable: true
                          settings_by_rule_type:
                            description: Logging settings by rule type.
                            properties:
                              dns:
                                properties:
                                  log_all:
                                    default: false
                                    description: Log all requests to this service.
                                    example: false
                                    type: boolean
                                    x-auditable: true
                                  log_blocks:
                                    default: false
                                    description: >-
                                      Log only blocking requests to this
                                      service.
                                    example: true
                                    type: boolean
                                    x-auditable: true
                                type: object
                              http:
                                properties:
                                  log_all:
                                    default: false
                                    description: Log all requests to this service.
                                    example: false
                                    type: boolean
                                    x-auditable: true
                                  log_blocks:
                                    default: false
                                    description: >-
                                      Log only blocking requests to this
                                      service.
                                    example: true
                                    type: boolean
                                    x-auditable: true
                                type: object
                              l4:
                                properties:
                                  log_all:
                                    default: false
                                    description: Log all requests to this service.
                                    example: false
                                    type: boolean
                                    x-auditable: true
                                  log_blocks:
                                    default: false
                                    description: >-
                                      Log only blocking requests to this
                                      service.
                                    example: true
                                    type: boolean
                                    x-auditable: true
                                type: object
                            type: object
                        type: object
          description: Update logging settings for the Zero Trust account response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - allOf:
                          - properties:
                              errors:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    message:
                                      type: string
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              messages:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    message:
                                      type: string
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              success:
                                description: Whether the API call was successful
                                enum:
                                  - true
                                example: true
                                type: boolean
                            required:
                              - success
                              - errors
                              - messages
                            type: object
                        type: object
                      - properties:
                          result:
                            properties:
                              redact_pii:
                                default: false
                                description: >-
                                  Redact personally identifiable information
                                  from activity logging (PII fields are: source
                                  IP, user email, user ID, device ID, URL,
                                  referrer, user agent).
                                example: true
                                type: boolean
                                x-auditable: true
                              settings_by_rule_type:
                                description: Logging settings by rule type.
                                properties:
                                  dns:
                                    properties:
                                      log_all:
                                        default: false
                                        description: Log all requests to this service.
                                        example: false
                                        type: boolean
                                        x-auditable: true
                                      log_blocks:
                                        default: false
                                        description: >-
                                          Log only blocking requests to this
                                          service.
                                        example: true
                                        type: boolean
                                        x-auditable: true
                                    type: object
                                  http:
                                    properties:
                                      log_all:
                                        default: false
                                        description: Log all requests to this service.
                                        example: false
                                        type: boolean
                                        x-auditable: true
                                      log_blocks:
                                        default: false
                                        description: >-
                                          Log only blocking requests to this
                                          service.
                                        example: true
                                        type: boolean
                                        x-auditable: true
                                    type: object
                                  l4:
                                    properties:
                                      log_all:
                                        default: false
                                        description: Log all requests to this service.
                                        example: false
                                        type: boolean
                                        x-auditable: true
                                      log_blocks:
                                        default: false
                                        description: >-
                                          Log only blocking requests to this
                                          service.
                                        example: true
                                        type: boolean
                                        x-auditable: true
                                    type: object
                                type: object
                            type: object
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                        type: object
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                        type: object
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
          description: Update logging settings for the Zero Trust account response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update Zero Trust account logging settings
      tags:
        - Zero Trust accounts
      x-api-token-group:
        - Zero Trust Write
