openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/access/apps/{app_id}/user_policy_checks:
    get:
      description: Tests if a specific user has permission to access an application.
      operationId: zone-level-access-applications-test-access-policies
      parameters:
        - in: path
          name: app_id
          required: true
          schema:
            oneOf:
              - description: Identifier.
                example: 023e105f4ecef8ad9ca31a8372d0c353
                maxLength: 32
                type: string
                x-auditable: true
              - description: UUID.
                example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
                maxLength: 36
                type: string
                x-auditable: true
        - in: path
          name: zone_id
          required: true
          schema:
            description: Identifier.
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
            x-auditable: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                documentation_url:
                                  type: string
                                message:
                                  type: string
                                source:
                                  properties:
                                    pointer:
                                      type: string
                                  type: object
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful.
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                        type: object
                    type: object
                  - properties:
                      result:
                        properties:
                          app_state:
                            properties:
                              app_uid:
                                description: UUID.
                                example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
                                maxLength: 36
                                type: string
                                x-auditable: true
                              aud:
                                example: >-
                                  737646a56ab1df6ec9bddc7e5ca84eaf3b0768850f3ffb5d74f1534911fe389
                                type: string
                              hostname:
                                example: test.com
                                type: string
                              name:
                                example: Test App
                                type: string
                              policies:
                                example:
                                  - decision: allow
                                    exclude: []
                                    include:
                                      - _type: email
                                        email: testuser@gmail.com
                                    precedence: 0
                                    require: []
                                    status: Success
                                items: {}
                                type: array
                              status:
                                example: Success
                                type: string
                            type: object
                          user_identity:
                            properties:
                              account_id:
                                example: 41ecfbb341f033e52b46742756aabb8b
                                type: string
                              device_sessions:
                                example: {}
                                type: object
                              email:
                                example: testuser@gmail.com
                                type: string
                              geo:
                                properties:
                                  country:
                                    example: US
                                    type: string
                                type: object
                              iat:
                                type: integer
                              id:
                                example: '1164449231815010287495'
                                type: string
                              is_gateway:
                                example: false
                                type: boolean
                              is_warp:
                                example: false
                                type: boolean
                              name:
                                example: Test User
                                type: string
                              user_uuid:
                                description: UUID.
                                example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
                                maxLength: 36
                                type: string
                                x-auditable: true
                              version:
                                type: integer
                            type: object
                        type: object
                type: object
          description: Test Access policies response
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    minLength: 1
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            documentation_url:
                              type: string
                            message:
                              type: string
                            source:
                              properties:
                                pointer:
                                  type: string
                              type: object
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: Test Access policies response failure
      security:
        - api_email: []
          api_key: []
      summary: Test Access policies
      tags:
        - Zone-Level Access applications
      x-api-token-group:
        - 'Access: Apps and Policies Write'
        - 'Access: Apps and Policies Read'
        - 'Access: Apps and Policies Write'
        - 'Access: Apps and Policies Read'
