openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/settings/origin_max_http_version:
    get:
      description: >-
        Origin Max HTTP Setting Version sets the highest HTTP version Cloudflare
        will attempt to use with your origin. This setting allows Cloudflare to
        make HTTP/2 requests to your origin. (Refer to [Enable HTTP/2 to
        Origin](https://developers.cloudflare.com/cache/how-to/enable-http2-to-origin/),
        for more information.). The default value is "2" for all plan types
        except Enterprise where it is "1"
      operationId: zone-cache-settings-get-origin-max-http-version-setting
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            description: Identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
            x-auditable: true
      responses:
        '200':
          content:
            application/json:
              examples:
                max_http_version_2:
                  value:
                    errors: []
                    messages: []
                    result:
                      editable: true
                      id: origin_max_http_version
                      value: '2'
                    success: true
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                        type: object
                      - properties:
                          result:
                            properties:
                              editable:
                                description: Whether the setting is editable
                                type: boolean
                                x-auditable: true
                              id:
                                description: The identifier of the caching setting
                                type: string
                                x-auditable: true
                              modified_on:
                                description: The time when the setting was last modified
                                format: date-time
                                type: string
                                x-auditable: true
                              value:
                                description: The value of the feature
                                type: string
                                x-auditable: true
                            required:
                              - id
                              - value
                              - editable
                            type: object
                        type: object
                    type: object
                  - properties:
                      result:
                        allOf:
                          - properties:
                              id:
                                description: Identifier of the zone setting.
                                type: string
                                x-auditable: true
                              modified_on:
                                description: Last time this setting was modified.
                                example: '2014-01-01T05:20:00.12345Z'
                                format: date-time
                                nullable: true
                                readOnly: true
                                type: string
                                x-auditable: true
                            required:
                              - id
                            type: object
                          - properties:
                              id:
                                description: Value of the zone setting.
                                enum:
                                  - origin_max_http_version
                                example: origin_max_http_version
                                type: string
                                x-auditable: true
                              value:
                                description: Value of the Origin Max HTTP Version Setting.
                                enum:
                                  - '2'
                                  - '1'
                                type: string
                                x-auditable: true
                            type: object
                        description: >-
                          Origin Max HTTP Setting Version sets the highest HTTP
                          version Cloudflare will attempt to use with your
                          origin. This setting allows Cloudflare to make HTTP/2
                          requests to your origin. (Refer to [Enable HTTP/2 to
                          Origin](https://developers.cloudflare.com/cache/how-to/enable-http2-to-origin/),
                          for more information.). The default value is "2" for
                          all plan types except Enterprise where it is "1"
                        title: Origin Max HTTP Version
                        type: object
                    type: object
                type: object
          description: Get Origin Max HTTP Version Setting Response
        4XX:
          content:
            application/json:
              examples:
                Error:
                  value:
                    errors:
                      - code: 12345
                        message: Some error message
                    messages: []
                    result: null
                    success: false
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    items:
                      type: object
                    minLength: 1
                    type: array
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                    items:
                      type: object
                    type: array
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: Get Origin Max HTTP Version Setting Response Failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get Origin Max HTTP Version Setting
      tags:
        - Zone Settings
      x-api-token-group:
        - Zone Settings Write
        - Zone Settings Read
        - Zone Read
        - Zone Write
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
