openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/available_rate_plans:
    get:
      description: Lists all rate plans the zone can subscribe to.
      operationId: zone-rate-plan-list-available-rate-plans
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            description: Identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          result:
                            anyOf:
                              - type: object
                              - items: {}
                                type: array
                              - type: string
                          success:
                            description: Whether the API call was successful
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                          - result
                        type: object
                      - properties:
                          result:
                            items: {}
                            nullable: true
                            type: array
                          result_info:
                            properties:
                              count:
                                description: >-
                                  Total number of results for the requested
                                  service
                                example: 1
                                type: number
                              page:
                                description: Current page within paginated list of results
                                example: 1
                                type: number
                              per_page:
                                description: Number of results per page of results
                                example: 20
                                type: number
                              total_count:
                                description: >-
                                  Total results available without any search
                                  parameters
                                example: 2000
                                type: number
                            type: object
                    type: object
                  - properties:
                      result:
                        items:
                          allOf:
                            - properties:
                                components:
                                  description: >-
                                    Array of available components values for the
                                    plan.
                                  items:
                                    properties:
                                      default:
                                        description: The default amount allocated.
                                        example: 5
                                        type: number
                                      name:
                                        description: The unique component.
                                        enum:
                                          - zones
                                          - page_rules
                                          - dedicated_certificates
                                          - dedicated_certificates_custom
                                        example: page_rules
                                      unit_price:
                                        description: The unit price of the addon.
                                        example: 1
                                        readOnly: true
                                        type: number
                                    type: object
                                  type: array
                                currency:
                                  description: >-
                                    The monetary unit in which pricing
                                    information is displayed.
                                  example: USD
                                  readOnly: true
                                  type: string
                                duration:
                                  description: The duration of the plan subscription.
                                  example: 1
                                  type: number
                                frequency:
                                  description: >-
                                    The frequency at which you will be billed
                                    for this plan.
                                  enum:
                                    - weekly
                                    - monthly
                                    - quarterly
                                    - yearly
                                  example: monthly
                                  readOnly: true
                                  type: string
                                id:
                                  description: Plan identifier tag.
                                  example: free
                                  readOnly: true
                                  type: string
                                name:
                                  description: The plan name.
                                  example: Free Plan
                                  maxLength: 80
                                  readOnly: true
                                  type: string
                              type: object
                          type: object
                        type: array
                    type: object
          description: List Available Rate Plans response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - allOf:
                          - properties:
                              errors:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    message:
                                      type: string
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              messages:
                                example: []
                                items:
                                  properties:
                                    code:
                                      minimum: 1000
                                      type: integer
                                    message:
                                      type: string
                                  required:
                                    - code
                                    - message
                                  type: object
                                  uniqueItems: true
                                type: array
                              result:
                                anyOf:
                                  - type: object
                                  - items: {}
                                    type: array
                                  - type: string
                              success:
                                description: Whether the API call was successful
                                enum:
                                  - true
                                example: true
                                type: boolean
                            required:
                              - success
                              - errors
                              - messages
                              - result
                            type: object
                          - properties:
                              result:
                                items: {}
                                nullable: true
                                type: array
                              result_info:
                                properties:
                                  count:
                                    description: >-
                                      Total number of results for the requested
                                      service
                                    example: 1
                                    type: number
                                  page:
                                    description: >-
                                      Current page within paginated list of
                                      results
                                    example: 1
                                    type: number
                                  per_page:
                                    description: Number of results per page of results
                                    example: 20
                                    type: number
                                  total_count:
                                    description: >-
                                      Total results available without any search
                                      parameters
                                    example: 2000
                                    type: number
                                type: object
                        type: object
                      - properties:
                          result:
                            items:
                              allOf:
                                - properties:
                                    components:
                                      description: >-
                                        Array of available components values for
                                        the plan.
                                      items:
                                        properties:
                                          default:
                                            description: The default amount allocated.
                                            example: 5
                                            type: number
                                          name:
                                            description: The unique component.
                                            enum:
                                              - zones
                                              - page_rules
                                              - dedicated_certificates
                                              - dedicated_certificates_custom
                                            example: page_rules
                                          unit_price:
                                            description: The unit price of the addon.
                                            example: 1
                                            readOnly: true
                                            type: number
                                        type: object
                                      type: array
                                    currency:
                                      description: >-
                                        The monetary unit in which pricing
                                        information is displayed.
                                      example: USD
                                      readOnly: true
                                      type: string
                                    duration:
                                      description: The duration of the plan subscription.
                                      example: 1
                                      type: number
                                    frequency:
                                      description: >-
                                        The frequency at which you will be
                                        billed for this plan.
                                      enum:
                                        - weekly
                                        - monthly
                                        - quarterly
                                        - yearly
                                      example: monthly
                                      readOnly: true
                                      type: string
                                    id:
                                      description: Plan identifier tag.
                                      example: free
                                      readOnly: true
                                      type: string
                                    name:
                                      description: The plan name.
                                      example: Free Plan
                                      maxLength: 80
                                      readOnly: true
                                      type: string
                                  type: object
                              type: object
                            type: array
                        type: object
                  - properties:
                      errors:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example:
                          - code: 7003
                            message: No route for the URI
                        minLength: 1
                      messages:
                        allOf:
                          - example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                        example: []
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
                      success:
                        description: Whether the API call was successful
                        enum:
                          - false
                        example: false
                        type: boolean
                    required:
                      - success
                      - errors
                      - messages
                      - result
                    type: object
          description: List Available Rate Plans response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List Available Rate Plans
      tags:
        - Zone Rate Plan
      x-api-token-group:
        - Billing Write
        - Billing Read
      x-cfPermissionsRequired:
        enum:
          - '#billing:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
