openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/settings/origin_h2_max_streams:
    patch:
      description: >-
        Origin H2 Max Streams configures the max number of concurrent requests
        that Cloudflare will send within the same connection when communicating
        with the origin server, if the origin supports it. Note that if your
        origin does not support H2 multiplexing, 5xx errors may be observed,
        particularly 520s. Also note that the default value is `100` for all
        plan types except Enterprise where it is `1`. `1` means that H2
        multiplexing is disabled.
      operationId: zone-cache-settings-change-origin-h2-max-streams-setting
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            description: Identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            readOnly: true
            type: string
            x-auditable: true
      requestBody:
        content:
          application/json:
            schema:
              properties:
                value:
                  description: Value of the Origin H2 Max Streams Setting.
                  example: 50
                  maximum: 1000
                  minimum: 1
                  type: integer
                  x-auditable: true
              required:
                - value
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              examples:
                origin_h2_max_streams_50:
                  value:
                    errors: []
                    messages: []
                    result:
                      editable: true
                      id: origin_h2_max_streams
                      value: 50
                    success: true
              schema:
                allOf:
                  - allOf:
                      - properties:
                          errors:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          messages:
                            example: []
                            items:
                              properties:
                                code:
                                  minimum: 1000
                                  type: integer
                                message:
                                  type: string
                              required:
                                - code
                                - message
                              type: object
                              uniqueItems: true
                            type: array
                          success:
                            description: Whether the API call was successful
                            enum:
                              - true
                            example: true
                            type: boolean
                        required:
                          - success
                          - errors
                          - messages
                        type: object
                      - properties:
                          result:
                            properties:
                              editable:
                                description: Whether the setting is editable
                                type: boolean
                                x-auditable: true
                              id:
                                description: The identifier of the caching setting
                                type: string
                                x-auditable: true
                              modified_on:
                                description: The time when the setting was last modified
                                format: date-time
                                type: string
                                x-auditable: true
                              value:
                                description: The value of the feature
                                type: string
                                x-auditable: true
                            required:
                              - id
                              - value
                              - editable
                            type: object
                        type: object
                    type: object
                  - properties:
                      result:
                        allOf:
                          - properties:
                              id:
                                description: Identifier of the zone setting.
                                type: string
                                x-auditable: true
                              modified_on:
                                description: Last time this setting was modified.
                                example: '2014-01-01T05:20:00.12345Z'
                                format: date-time
                                nullable: true
                                readOnly: true
                                type: string
                                x-auditable: true
                            required:
                              - id
                            type: object
                          - properties:
                              id:
                                description: Value of the zone setting.
                                enum:
                                  - origin_h2_max_streams
                                example: origin_h2_max_streams
                                type: string
                                x-auditable: true
                              value:
                                description: Value of the Origin H2 Max Streams Setting.
                                example: 50
                                maximum: 1000
                                minimum: 1
                                type: integer
                                x-auditable: true
                            type: object
                        description: >-
                          Origin H2 Max Streams configures the max number of
                          concurrent requests that Cloudflare will send within
                          the same connection when communicating with the origin
                          server, if the origin supports it. Note that if your
                          origin does not support H2 multiplexing, 5xx errors
                          may be observed, particularly 520s. Also note that the
                          default value is `100` for all plan types except
                          Enterprise where it is `1`. `1` means that H2
                          multiplexing is disabled.
                        title: Origin H2 Max Streams
                        type: object
                    type: object
                type: object
          description: Change Origin H2 Max Streams Setting Response
        4XX:
          content:
            application/json:
              examples:
                Error:
                  value:
                    errors:
                      - code: 12345
                        message: Some error message
                    messages: []
                    result: null
                    success: false
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    items:
                      type: object
                    minLength: 1
                    type: array
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                            message:
                              type: string
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                    items:
                      type: object
                    type: array
                  result:
                    enum:
                      - null
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful
                    enum:
                      - false
                    example: false
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: Change Origin H2 Max Streams Response Failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Change Origin H2 Max Streams Setting
      tags:
        - Zone Settings
      x-api-token-group:
        - Zone Settings Write
        - Zone Write
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
