openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/settings/speed_brain:
    get:
      description: >
        Speed Brain lets compatible browsers speculate on content which can be
        prefetched or preloaded, making website

        navigation faster. Refer to the Cloudflare Speed Brain documentation for
        more information.
      operationId: zone-settings-get-speed-brain-setting
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            description: Identifier
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
            x-auditable: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      errors:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                              x-auditable: true
                            message:
                              type: string
                              x-auditable: true
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      messages:
                        example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                              x-auditable: true
                            message:
                              type: string
                              x-auditable: true
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                      success:
                        description: Whether the API call was successful
                        example: true
                        type: boolean
                        x-auditable: true
                    required:
                      - success
                      - errors
                      - messages
                    type: object
                  - properties:
                      result:
                        allOf:
                          - properties:
                              editable:
                                default: true
                                description: >-
                                  Whether or not this setting can be modified
                                  for this zone (based on your Cloudflare plan
                                  level).
                                enum:
                                  - true
                                  - false
                                readOnly: true
                                type: boolean
                                x-auditable: true
                              id:
                                description: Identifier of the zone setting.
                                example: development_mode
                                type: string
                                x-auditable: true
                              modified_on:
                                description: last time this setting was modified.
                                example: '2014-01-01T05:20:00.12345Z'
                                format: date-time
                                nullable: true
                                readOnly: true
                                type: string
                                x-auditable: true
                              value:
                                description: Current value of the zone setting.
                                enum:
                                  - 'on'
                                  - 'off'
                                example: 'on'
                                type: string
                                x-auditable: true
                        properties:
                          value:
                            description: >
                              Whether the feature is enabled or disabled.

                              Defaults to "on" for Free plans, otherwise
                              defaults to "off".
                        title: Cloudflare Speed Brain response
          description: Get Cloudflare Speed Brain setting response
        4XX:
          content:
            application/json:
              schema:
                properties:
                  errors:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                              x-auditable: true
                            message:
                              type: string
                              x-auditable: true
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example:
                      - code: 7003
                        message: No route for the URI
                    minLength: 1
                  messages:
                    allOf:
                      - example: []
                        items:
                          properties:
                            code:
                              minimum: 1000
                              type: integer
                              x-auditable: true
                            message:
                              type: string
                              x-auditable: true
                          required:
                            - code
                            - message
                          type: object
                          uniqueItems: true
                        type: array
                    example: []
                  result:
                    nullable: true
                    type: object
                  success:
                    description: Whether the API call was successful
                    example: false
                    type: boolean
                    x-auditable: true
                required:
                  - success
                  - errors
                  - messages
                  - result
                type: object
          description: Get Cloudflare Speed Brain setting response failure
      security:
        - api_email: []
          api_key: []
      summary: Get Cloudflare Speed Brain setting
      tags:
        - Zone Settings
      x-api-token-group:
        - Zone Settings Write
        - Zone Settings Read
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
