openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/access/bookmarks:
    get:
      deprecated: true
      description: Lists Bookmark applications.
      operationId: access-bookmark-applications-(-deprecated)-list-bookmark-applications
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/access_components-schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/access_bookmarks_components-schemas-response_collection
          description: List Bookmark applications response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: List Bookmark applications response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List Bookmark applications
      tags:
        - Access Bookmark applications (Deprecated)
      x-api-token-group:
        - 'Access: Apps and Policies Revoke'
        - 'Access: Apps and Policies Write'
        - 'Access: Apps and Policies Read'
      x-cfDeprecation:
        description: >-
          This endpoint is deprecated in favor of using a specialized Access
          Application App Type.
        display: true
        eol: '2023-03-19'
        id: bookmarks_deprecation
  /accounts/{account_id}/access/bookmarks/{bookmark_id}:
    get:
      deprecated: true
      description: Fetches a single Bookmark application.
      operationId: access-bookmark-applications-(-deprecated)-get-a-bookmark-application
      parameters:
        - in: path
          name: bookmark_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/access_components-schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/access_bookmarks_components-schemas-single_response
          description: Get a Bookmark application response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Get a Bookmark application response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get a Bookmark application
      tags:
        - Access Bookmark applications (Deprecated)
      x-api-token-group:
        - 'Access: Apps and Policies Write'
        - 'Access: Apps and Policies Read'
      x-cfDeprecation:
        description: >-
          This endpoint is deprecated in favor of using a specialized Access
          Application App Type.
        display: true
        eol: '2023-03-19'
        id: bookmarks_deprecation
    post:
      deprecated: true
      description: Create a new Bookmark application.
      operationId: access-bookmark-applications-(-deprecated)-create-a-bookmark-application
      parameters:
        - in: path
          name: bookmark_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/access_components-schemas-identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/access_bookmarks_components-schemas-single_response
          description: Create a Bookmark application response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Create a Bookmark application response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create a Bookmark application
      tags:
        - Access Bookmark applications (Deprecated)
      x-cfDeprecation:
        description: >-
          This endpoint is deprecated in favor of using a specialized Access
          Application App Type.
        display: true
        eol: '2023-03-19'
        id: bookmarks_deprecation
    put:
      deprecated: true
      description: Updates a configured Bookmark application.
      operationId: access-bookmark-applications-(-deprecated)-update-a-bookmark-application
      parameters:
        - in: path
          name: bookmark_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/access_components-schemas-identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/access_bookmarks_components-schemas-single_response
          description: Update a Bookmark application response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Update a Bookmark application response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update a Bookmark application
      tags:
        - Access Bookmark applications (Deprecated)
      x-api-token-group:
        - 'Access: Apps and Policies Write'
      x-cfDeprecation:
        description: >-
          This endpoint is deprecated in favor of using a specialized Access
          Application App Type.
        display: true
        eol: '2023-03-19'
        id: bookmarks_deprecation
    delete:
      deprecated: true
      description: Deletes a Bookmark application.
      operationId: access-bookmark-applications-(-deprecated)-delete-a-bookmark-application
      parameters:
        - in: path
          name: bookmark_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/access_components-schemas-identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_id_response'
          description: Delete a Bookmark application response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Delete a Bookmark application response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete a Bookmark application
      tags:
        - Access Bookmark applications (Deprecated)
      x-api-token-group:
        - 'Access: Apps and Policies Write'
      x-cfDeprecation:
        description: >-
          This endpoint is deprecated in favor of using a specialized Access
          Application App Type.
        display: true
        eol: '2023-03-19'
        id: bookmarks_deprecation
components:
  schemas:
    access_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/access_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/access_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    access_bookmarks_components-schemas-response_collection:
      allOf:
        - $ref: '#/components/schemas/access_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/access_bookmarks'
              type: array
      type: object
    access_bookmarks_components-schemas-single_response:
      allOf:
        - $ref: '#/components/schemas/access_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/access_bookmarks'
      type: object
    access_components-schemas-identifier:
      example: 699d98642c564d2e855e9661899b7252
      type: string
      x-auditable: true
    access_id_response:
      allOf:
        - $ref: '#/components/schemas/access_api-response-single'
        - properties:
            result:
              properties:
                id:
                  $ref: '#/components/schemas/access_uuid'
              type: object
      type: object
    access_uuid:
      description: UUID.
      example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      maxLength: 36
      type: string
      x-auditable: true
