openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/access/policy-tests:
    post:
      description: Starts an Access policy test.
      operationId: access-policy-tests
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/access_policy_init_req'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_policy_init_resp'
          description: Start Access policy test response.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Start Access policy test response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Start Access policy test
      tags:
        - Access policy tester
      x-api-token-group:
        - 'Access: Policy Test Write'
  /accounts/{account_id}/access/policy-tests/{policy_test_id}:
    get:
      description: Fetches the current status of a given Access policy test.
      operationId: access-policy-tests-get-an-update
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
        - in: path
          name: policy_test_id
          required: true
          schema:
            $ref: '#/components/schemas/access_policy_test_id'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_policy_update_resp'
          description: Get an Access policy test update response.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Get an Access policy test update response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get the current status of a given Access policy test
      tags:
        - Access policy tester
      x-api-token-group:
        - 'Access: Policy Test Write'
        - 'Access: Policy Test Read'
  /accounts/{account_id}/access/policy-tests/{policy_test_id}/users:
    get:
      description: Fetches a single page of user results from an Access policy test.
      operationId: access-policy-tests-get-a-user-page
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
        - in: path
          name: policy_test_id
          required: true
          schema:
            $ref: '#/components/schemas/access_policy_test_id'
        - in: query
          name: page
          schema:
            default: 1
            type: integer
        - in: query
          name: per_page
          schema:
            default: 25
            type: integer
        - description: Filter users by their policy evaluation status.
          in: query
          name: status
          schema:
            enum:
              - success
              - fail
              - error
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_policy_users_resp'
          description: Get an Access policy tester users page response.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Get an Access policy tester users page response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get an Access policy test users page
      tags:
        - Access policy tester
      x-api-token-group:
        - 'Access: Policy Test Write'
        - 'Access: Policy Test Read'
components:
  schemas:
    access_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/access_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/access_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    access_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
    access_policy_init_req:
      properties:
        policies:
          items:
            oneOf:
              - $ref: '#/components/schemas/access_policy_req'
              - description: The UUID of the reusable policy you wish to test
                example: >-
                  f1a8b3c9d4e5f6789a0b1c2d3e4f5678a9b0c1d2e3f4a5b67890c1d2e3f4b5a6
                type: string
          type: array
      type: object
    access_policy_init_resp:
      allOf:
        - $ref: '#/components/schemas/access_api-response-single'
        - properties:
            result:
              properties:
                id:
                  $ref: '#/components/schemas/access_policy_test_id'
                status:
                  $ref: '#/components/schemas/access_status'
              type: object
      type: object
    access_policy_test_id:
      description: The UUID of the policy test.
      example: f1a8b3c9d4e5f6789a0b1c2d3e4f5678a9b0c1d2e3f4a5b67890c1d2e3f4b5a6
      maxLength: 64
      type: string
      x-auditable: true
    access_policy_update_resp:
      allOf:
        - $ref: '#/components/schemas/access_api-response-single'
        - properties:
            result:
              properties:
                id:
                  $ref: '#/components/schemas/access_policy_test_id'
                percent_approved:
                  $ref: '#/components/schemas/access_percent_approved'
                percent_blocked:
                  $ref: '#/components/schemas/access_percent_blocked'
                percent_errored:
                  $ref: '#/components/schemas/access_percent_errored'
                percent_users_processed:
                  $ref: '#/components/schemas/access_percent_users_processed'
                status:
                  $ref: '#/components/schemas/access_update_status'
                total_users:
                  $ref: '#/components/schemas/access_total_users'
                users_approved:
                  $ref: '#/components/schemas/access_users_approved'
                users_blocked:
                  $ref: '#/components/schemas/access_users_blocked'
                users_errored:
                  $ref: '#/components/schemas/access_users_errored'
              type: object
      type: object
    access_policy_users_resp:
      allOf:
        - $ref: '#/components/schemas/access_api-response-single'
        - properties:
            result:
              description: Page of processed users.
              items:
                $ref: '#/components/schemas/access_policy_users'
              type: array
      type: object
