openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/access/logs/scim/updates:
    get:
      description: >-
        Lists Access SCIM update logs that maintain a record of updates made to
        User and Group resources synced to Cloudflare via the System for
        Cross-domain Identity Management (SCIM).
      operationId: access-scim-update-logs-list-access-scim-update-logs
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
        - in: query
          name: limit
          schema:
            $ref: '#/components/schemas/access_limit'
        - example: desc
          in: query
          name: direction
          schema:
            $ref: '#/components/schemas/access_direction'
        - in: query
          name: since
          schema:
            $ref: '#/components/schemas/access_since'
        - in: query
          name: until
          schema:
            $ref: '#/components/schemas/access_until'
        - in: query
          name: idp_id
          required: true
          schema:
            $ref: '#/components/schemas/access_idp_id'
        - in: query
          name: status
          schema:
            $ref: '#/components/schemas/access_requests-status'
        - in: query
          name: resource_type
          schema:
            $ref: '#/components/schemas/access_resource_type'
        - in: query
          name: request_method
          schema:
            $ref: '#/components/schemas/access_request_method'
        - in: query
          name: resource_user_email
          schema:
            $ref: '#/components/schemas/access_resource_user_email'
        - in: query
          name: resource_group_name
          schema:
            $ref: '#/components/schemas/access_resource_group_name'
        - in: query
          name: cf_resource_id
          schema:
            $ref: '#/components/schemas/access_requests-cf_resource_id'
        - in: query
          name: idp_resource_id
          schema:
            $ref: '#/components/schemas/access_requests-idp_resource_id'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_scim_update_logs_response'
          description: Get Access SCIM update logs response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Get Access SCIM update logs response failure
      security:
        - api_email: []
          api_key: []
      summary: List Access SCIM update logs
      tags:
        - Access SCIM update logs
      x-api-token-group:
        - 'Access: SCIM logs read'
components:
  schemas:
    access_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/access_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/access_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    access_direction:
      default: desc
      description: The chronological order used to sort the logs.
      enum:
        - desc
        - asc
      example: desc
      type: string
    access_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
    access_idp_id:
      description: The unique Id of the IdP that has SCIM enabled.
      example:
        - df7e2w5f-02b7-4d9d-af26-8d1988fca630
        - 0194ae2c-efcf-7cfb-8884-055f1a161fa5
      items:
        type: string
      type: array
    access_limit:
      default: 20
      description: The maximum number of update logs to retrieve.
      example: 10
      type: integer
    access_request_method:
      description: The request method of the SCIM request.
      example:
        - DELETE
        - PATCH
      items:
        enum:
          - DELETE
          - PATCH
          - POST
          - PUT
        type: string
      type: array
    access_requests-cf_resource_id:
      description: The unique Cloudflare-generated Id of the SCIM resource.
      example: bd97ef8d-7986-43e3-9ee0-c25dda33e4b0
      type: string
    access_requests-idp_resource_id:
      description: The IdP-generated Id of the SCIM resource.
      type: string
    access_requests-status:
      description: The status of the SCIM request.
      example:
        - FAILURE
        - SUCCESS
      items:
        enum:
          - FAILURE
          - SUCCESS
        type: string
      type: array
    access_resource_group_name:
      description: The display name of the SCIM Group resource.
      example: ALL_EMPLOYEES
      type: string
    access_resource_type:
      description: The resource type of the SCIM request.
      example:
        - USER
        - GROUP
      items:
        enum:
          - USER
          - GROUP
        type: string
      type: array
    access_resource_user_email:
      description: The email address of the SCIM User resource.
      example: john.smith@example.com
      format: email
      type: string
    access_scim_update_logs_response:
      allOf:
        - $ref: '#/components/schemas/access_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/access_responses'
              type: array
          type: object
    access_since:
      description: the timestamp of the earliest update log.
      example: '2025-01-01T00:00:00Z'
      format: date-time
      type: string
    access_until:
      description: the timestamp of the most-recent update log.
      example: '2025-01-02T00:00:00Z'
      format: date-time
      type: string
