openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/access/identity_providers:
    get:
      description: Lists all configured identity providers.
      operationId: access-identity-providers-list-access-identity-providers
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
        - in: query
          name: scim_enabled
          schema:
            description: >-
              Indicates to Access to only retrieve identity providers that have
              the System for Cross-Domain Identity Management (SCIM) enabled.
            example: true
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_response_collection'
          description: List Access identity providers response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: List Access identity providers response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List Access identity providers
      tags:
        - Access identity providers
      x-api-token-group:
        - 'Access: Organizations, Identity Providers, and Groups Write'
        - 'Access: Organizations, Identity Providers, and Groups Read'
    post:
      description: Adds a new identity provider to Access.
      operationId: access-identity-providers-add-an-access-identity-provider
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/access_identity-providers'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_components-schemas-single_response'
          description: Add an Access identity provider response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Add an Access identity provider response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Add an Access identity provider
      tags:
        - Access identity providers
      x-api-token-group:
        - 'Access: Organizations, Identity Providers, and Groups Write'
  /accounts/{account_id}/access/identity_providers/{identity_provider_id}:
    get:
      description: Fetches a configured identity provider.
      operationId: access-identity-providers-get-an-access-identity-provider
      parameters:
        - in: path
          name: identity_provider_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_components-schemas-single_response'
          description: Get an Access identity provider response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Get an Access identity provider response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get an Access identity provider
      tags:
        - Access identity providers
      x-api-token-group:
        - 'Access: Organizations, Identity Providers, and Groups Write'
        - 'Access: Organizations, Identity Providers, and Groups Read'
    put:
      description: Updates a configured identity provider.
      operationId: access-identity-providers-update-an-access-identity-provider
      parameters:
        - in: path
          name: identity_provider_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/access_identity-providers'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_components-schemas-single_response'
          description: Update an Access identity provider response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Update an Access identity provider response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update an Access identity provider
      tags:
        - Access identity providers
      x-api-token-group:
        - 'Access: Organizations, Identity Providers, and Groups Write'
    delete:
      description: Deletes an identity provider from Access.
      operationId: access-identity-providers-delete-an-access-identity-provider
      parameters:
        - in: path
          name: identity_provider_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_id_response'
          description: Delete an Access identity provider response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Delete an Access identity provider response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete an Access identity provider
      tags:
        - Access identity providers
      x-api-token-group:
        - 'Access: Organizations, Identity Providers, and Groups Write'
  /accounts/{account_id}/access/identity_providers/{identity_provider_id}/scim/groups:
    get:
      description: >-
        Lists SCIM Group resources synced to Cloudflare via the System for
        Cross-domain Identity Management (SCIM).
      operationId: access-identity-providers-list-scim-group-resources
      parameters:
        - in: path
          name: identity_provider_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
        - in: query
          name: cf_resource_id
          schema:
            $ref: '#/components/schemas/access_cf_resource_id'
        - in: query
          name: idp_resource_id
          schema:
            $ref: '#/components/schemas/access_idp_resource_id'
        - in: query
          name: name
          schema:
            $ref: '#/components/schemas/access_groups-name'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_scim_groups_response'
          description: List SCIM Group resources response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: List SCIM Group resources response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List SCIM Group resources
      tags:
        - Access identity providers
      x-api-token-group:
        - 'Access: Organizations, Identity Providers, and Groups Write'
        - 'Access: Organizations, Identity Providers, and Groups Read'
  /accounts/{account_id}/access/identity_providers/{identity_provider_id}/scim/users:
    get:
      description: >-
        Lists SCIM User resources synced to Cloudflare via the System for
        Cross-domain Identity Management (SCIM).
      operationId: access-identity-providers-list-scim-user-resources
      parameters:
        - in: path
          name: identity_provider_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
        - in: query
          name: cf_resource_id
          schema:
            $ref: '#/components/schemas/access_users-cf_resource_id'
        - in: query
          name: idp_resource_id
          schema:
            $ref: '#/components/schemas/access_users-idp_resource_id'
        - in: query
          name: username
          schema:
            $ref: '#/components/schemas/access_username'
        - in: query
          name: email
          schema:
            $ref: '#/components/schemas/access_email'
        - in: query
          name: name
          schema:
            $ref: '#/components/schemas/access_users-name'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_scim_users_response'
          description: List SCIM User resources response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: List SCIM User resources response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List SCIM User resources
      tags:
        - Access identity providers
      x-api-token-group:
        - 'Access: Organizations, Identity Providers, and Groups Write'
        - 'Access: Organizations, Identity Providers, and Groups Read'
components:
  schemas:
    access_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/access_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/access_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    access_cf_resource_id:
      description: >-
        The unique Cloudflare-generated Id of the SCIM Group resource; also
        known as the "Id".
      example: a2abeb50-59c9-4c01-8c5c-963d3bf5700f
      type: string
    access_components-schemas-single_response:
      allOf:
        - $ref: '#/components/schemas/access_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/access_identity-providers'
      type: object
    access_email:
      description: The email address of the SCIM User resource.
      example: john.smith@example.com
      type: string
    access_groups-name:
      description: The display name of the SCIM Group resource.
      example: ALL_EMPLOYEES
      type: string
    access_id_response:
      allOf:
        - $ref: '#/components/schemas/access_api-response-single'
        - properties:
            result:
              properties:
                id:
                  $ref: '#/components/schemas/access_uuid'
              type: object
      type: object
    access_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
    access_identity-providers:
      anyOf:
        - $ref: '#/components/schemas/access_azureAD'
        - $ref: '#/components/schemas/access_centrify'
        - $ref: '#/components/schemas/access_facebook'
        - $ref: '#/components/schemas/access_github'
        - $ref: '#/components/schemas/access_google'
        - $ref: '#/components/schemas/access_google-apps'
        - $ref: '#/components/schemas/access_linkedin'
        - $ref: '#/components/schemas/access_oidc'
        - $ref: '#/components/schemas/access_okta'
        - $ref: '#/components/schemas/access_onelogin'
        - $ref: '#/components/schemas/access_pingone'
        - $ref: '#/components/schemas/access_saml'
        - $ref: '#/components/schemas/access_yandex'
        - $ref: '#/components/schemas/access_onetimepin'
      type: object
    access_idp_resource_id:
      description: >-
        The IdP-generated Id of the SCIM Group resource; also known as the
        "external Id".
      example: all_employees
      type: string
    access_response_collection:
      allOf:
        - $ref: '#/components/schemas/access_api-response-collection'
        - properties:
            result:
              items:
                anyOf:
                  - $ref: '#/components/schemas/access_azureAD'
                  - $ref: '#/components/schemas/access_centrify'
                  - $ref: '#/components/schemas/access_facebook'
                  - $ref: '#/components/schemas/access_github'
                  - $ref: '#/components/schemas/access_google'
                  - $ref: '#/components/schemas/access_google-apps'
                  - $ref: '#/components/schemas/access_linkedin'
                  - $ref: '#/components/schemas/access_oidc'
                  - $ref: '#/components/schemas/access_okta'
                  - $ref: '#/components/schemas/access_onelogin'
                  - $ref: '#/components/schemas/access_pingone'
                  - $ref: '#/components/schemas/access_saml'
                  - $ref: '#/components/schemas/access_yandex'
              type: array
          type: object
      type: object
    access_scim_groups_response:
      allOf:
        - $ref: '#/components/schemas/access_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/access_groups'
              type: array
          type: object
    access_scim_users_response:
      allOf:
        - $ref: '#/components/schemas/access_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/access_users'
              type: array
          type: object
    access_username:
      description: The username of the SCIM User resource.
      example: John Smith
      type: string
    access_users-cf_resource_id:
      description: >-
        The unique Cloudflare-generated Id of the SCIM User resource; also known
        as the "Id".
      example: bd97ef8d-7986-43e3-9ee0-c25dda33e4b0
      type: string
    access_users-idp_resource_id:
      description: >-
        The IdP-generated Id of the SCIM User resource; also known as the
        "external Id".
      example: john_smith_01
      type: string
    access_users-name:
      description: The name of the SCIM User resource.
      example: John Smith
      type: string
    access_uuid:
      description: UUID.
      example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      maxLength: 36
      type: string
      x-auditable: true
