openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/load_balancers/search:
    get:
      description: Search for Load Balancing resources.
      operationId: account-load-balancer-search-search-resources
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
        - in: query
          name: query
          schema:
            default: ''
            description: Search query term.
            example: primary
            type: string
        - in: query
          name: references
          schema:
            default: ''
            description: >-
              The type of references to include. "*" to include both referral
              and referrer references. "" to not include any reference
              information.
            enum:
              - ''
              - '*'
              - referral
              - referrer
            example: '*'
            type: string
        - in: query
          name: page
          schema:
            minimum: 1
            type: number
        - in: query
          name: per_page
          schema:
            default: 25
            maximum: 1000
            minimum: 1
            type: number
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/load-balancing_api-paginated-response-collection
                  - $ref: '#/components/schemas/load-balancing_search_result'
          description: Search Resources response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: >-
                          #/components/schemas/load-balancing_api-paginated-response-collection
                      - $ref: '#/components/schemas/load-balancing_search_result'
                  - $ref: >-
                      #/components/schemas/load-balancing_api-response-common-failure
          description: Search Resources response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Search Resources
      tags:
        - Account Load Balancer Search
      x-api-token-group:
        - 'Load Balancing: Monitors and Pools Write'
        - 'Load Balancing: Monitors and Pools Read'
components:
  schemas:
    load-balancing_api-paginated-response-collection:
      allOf:
        - $ref: '#/components/schemas/load-balancing_api-response-common'
        - properties:
            result_info:
              $ref: '#/components/schemas/load-balancing_result_info'
      required:
        - result_info
      type: object
    load-balancing_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/load-balancing_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/load-balancing_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    load-balancing_components-schemas-identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
    load-balancing_search_result:
      properties:
        result:
          $ref: '#/components/schemas/load-balancing_search'
      type: object
