openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/custom_ns:
    get:
      description: List an account's custom nameservers.
      operationId: account-level-custom-nameservers-list-account-custom-nameservers
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-custom-nameservers_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/dns-custom-nameservers_acns_response_collection
          description: List Account Custom Nameservers response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/dns-custom-nameservers_acns_response_collection
                  - $ref: >-
                      #/components/schemas/dns-custom-nameservers_api-response-common-failure
          description: List Account Custom Nameservers response failure
      security:
        - api_email: []
          api_key: []
      summary: List Account Custom Nameservers
      tags:
        - Account-Level Custom Nameservers
      x-api-token-group:
        - Account Settings Write
        - Account Settings Read
      x-cfPermissionsRequired:
        enum:
          - '#organization:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: false
    post:
      operationId: account-level-custom-nameservers-add-account-custom-nameserver
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-custom-nameservers_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dns-custom-nameservers_CustomNSInput'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/dns-custom-nameservers_acns_response_single
          description: Add Account Custom Nameserver response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/dns-custom-nameservers_acns_response_single
                  - $ref: >-
                      #/components/schemas/dns-custom-nameservers_api-response-common-failure
          description: Add Account Custom Nameserver response failure
      security:
        - api_email: []
          api_key: []
      summary: Add Account Custom Nameserver
      tags:
        - Account-Level Custom Nameservers
      x-api-token-group:
        - Account Settings Write
      x-cfPermissionsRequired:
        enum:
          - '#organization:edit'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/custom_ns/{custom_ns_id}:
    delete:
      operationId: account-level-custom-nameservers-delete-account-custom-nameserver
      parameters:
        - in: path
          name: custom_ns_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-custom-nameservers_ns_name'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-custom-nameservers_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dns-custom-nameservers_empty_response'
          description: Delete Account Custom Nameserver response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dns-custom-nameservers_empty_response'
                  - $ref: >-
                      #/components/schemas/dns-custom-nameservers_api-response-common-failure
          description: Delete Account Custom Nameserver response failure
      security:
        - api_email: []
          api_key: []
      summary: Delete Account Custom Nameserver
      tags:
        - Account-Level Custom Nameservers
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    dns-custom-nameservers_CustomNSInput:
      properties:
        ns_name:
          $ref: '#/components/schemas/dns-custom-nameservers_ns_name'
        ns_set:
          $ref: '#/components/schemas/dns-custom-nameservers_ns_set'
      required:
        - ns_name
      title: Custom NS Input
    dns-custom-nameservers_acns_response_collection:
      allOf:
        - $ref: '#/components/schemas/dns-custom-nameservers_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/dns-custom-nameservers_CustomNS'
              type: array
          type: object
    dns-custom-nameservers_acns_response_single:
      allOf:
        - $ref: '#/components/schemas/dns-custom-nameservers_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/dns-custom-nameservers_CustomNS'
          type: object
    dns-custom-nameservers_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/dns-custom-nameservers_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/dns-custom-nameservers_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    dns-custom-nameservers_empty_response:
      allOf:
        - $ref: '#/components/schemas/dns-custom-nameservers_api-response-collection'
        - properties:
            result:
              items:
                description: Unused
                type: string
                x-auditable: true
              maxItems: 0
              type: array
          type: object
    dns-custom-nameservers_identifier:
      description: Account identifier tag.
      example: 372e67954025e0ba6aaa6d586b9e0b59
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
    dns-custom-nameservers_ns_name:
      description: The FQDN of the name server.
      example: ns1.example.com
      format: hostname
      type: string
      x-auditable: true
