openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/roles:
    get:
      description: Get all available roles for an account.
      operationId: account-roles-list-roles
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/iam_account_identifier'
        - in: query
          name: page
          schema:
            default: 1
            description: Page number of paginated results.
            minimum: 1
            type: number
        - in: query
          name: per_page
          schema:
            default: 20
            description: Number of roles per page.
            maximum: 50
            minimum: 5
            type: number
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_collection_role_response'
          description: List Roles response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: List Roles response failure
      security:
        - api_email: []
          api_key: []
      summary: List Roles
      tags:
        - Account Roles
      x-api-token-group:
        - SCIM Provisioning
        - Account Settings Write
        - Account Settings Read
      x-cfPermissionsRequired:
        enum:
          - '#organization:read'
  /accounts/{account_id}/roles/{role_id}:
    get:
      description: Get information about a specific role for an account.
      operationId: account-roles-role-details
      parameters:
        - in: path
          name: role_id
          required: true
          schema:
            $ref: '#/components/schemas/iam_role_components-schemas-identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/iam_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_single_role_response'
          description: Role Details response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: Role Details response failure
      security:
        - api_email: []
          api_key: []
      summary: Role Details
      tags:
        - Account Roles
      x-api-token-group:
        - SCIM Provisioning
        - Account Settings Write
        - Account Settings Read
      x-cfPermissionsRequired:
        enum:
          - '#organization:read'
components:
  schemas:
    iam_account_identifier:
      allOf:
        - $ref: '#/components/schemas/iam_common_components-schemas-identifier'
      description: Account identifier tag.
      title: Account Identifier
    iam_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/iam_schemas-messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/iam_schemas-messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    iam_collection_role_response:
      allOf:
        - $ref: '#/components/schemas/iam_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/iam_role'
              type: array
          type: object
    iam_role_components-schemas-identifier:
      description: Role identifier tag.
      example: 3536bcfad5faccb999b47003c79917fb
      maxLength: 32
      type: string
      x-auditable: true
    iam_single_role_response:
      allOf:
        - $ref: '#/components/schemas/iam_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/iam_role'
          type: object
