openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/api_gateway/operations:
    get:
      operationId: >-
        api-shield-endpoint-management-retrieve-information-about-all-operations-on-a-zone
      parameters:
        - $ref: '#/components/parameters/api-shield_page'
        - $ref: '#/components/parameters/api-shield_per_page'
        - in: query
          name: order
          schema:
            description: >-
              Field to order by. When requesting a feature, the feature keys are
              available for ordering as well, e.g.,
              `thresholds.suggested_threshold`.
            enum:
              - method
              - host
              - endpoint
              - thresholds.$key
            example: method
            type: string
        - $ref: '#/components/parameters/api-shield_direction_parameter'
        - $ref: '#/components/parameters/api-shield_host_parameter'
        - $ref: '#/components/parameters/api-shield_method_parameter'
        - $ref: '#/components/parameters/api-shield_endpoint_parameter'
        - $ref: '#/components/parameters/api-shield_operation_feature_parameter'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/api-shield_multiple-operation-response-paginated
          description: Retrieve information about all operations on a zone response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-shield_api-response-common-failure'
          description: Retrieve information about all operations on a zone response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Retrieve information about all operations on a zone
      tags:
        - API Shield Endpoint Management
      x-api-token-group:
        - Account API Gateway
        - Account API Gateway Read
        - Domain API Gateway
        - Domain API Gateway Read
    post:
      description: >-
        Add one or more operations to a zone. Endpoints can contain path
        variables. Host, method, endpoint will be normalized to a canoncial form
        when creating an operation and must be unique on the zone. Inserting an
        operation that matches an existing one will return the record of the
        already existing operation and update its last_updated date.
      operationId: api-shield-endpoint-management-add-operations-to-a-zone
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/api-shield_basic_operation'
              type: array
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-shield_multiple-operation-response'
          description: Add operations to a zone response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-shield_api-response-common-failure'
          description: Add operations to a zone response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Add operations to a zone
      tags:
        - API Shield Endpoint Management
      x-api-token-group:
        - Account API Gateway
        - Domain API Gateway
    delete:
      operationId: api-shield-endpoint-management-delete-multiple-operations
      requestBody:
        content:
          application/json:
            schema:
              example:
                - operation_id: b17c8043-99a0-4202-b7d9-8f7cdbee02cd
                - operation_id: 3818d821-5901-4147-a474-f5f5aec1d54e
              items:
                $ref: '#/components/schemas/api-shield_object-with-operation-id'
              type: array
              uniqueItems: true
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-shield_api-response-common'
          description: Delete multiple operations response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-shield_api-response-common-failure'
          description: Delete multiple operations response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete multiple operations
      tags:
        - API Shield Endpoint Management
      x-api-token-group:
        - Account API Gateway
        - Domain API Gateway
  /zones/{zone_id}/api_gateway/operations/item:
    post:
      description: >-
        Add one operation to a zone. Endpoints can contain path variables. Host,
        method, endpoint will be normalized to a canoncial form when creating an
        operation and must be unique on the zone. Inserting an operation that
        matches an existing one will return the record of the already existing
        operation and update its last_updated date.
      operationId: api-shield-endpoint-management-add-operation-to-a-zone
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api-shield_basic_operation'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-shield_single-operation-response'
          description: Add one operation to a zone response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-shield_api-response-common-failure'
          description: Add one operation to a zone response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Add one operation to a zone
      tags:
        - API Shield Endpoint Management
      x-api-token-group:
        - Account API Gateway
        - Domain API Gateway
  /zones/{zone_id}/api_gateway/operations/{operation_id}:
    get:
      operationId: api-shield-endpoint-management-retrieve-information-about-an-operation
      parameters:
        - $ref: '#/components/parameters/api-shield_operation_feature_parameter'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-shield_single-operation-response'
          description: Retrieve information about an operation response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-shield_api-response-common-failure'
          description: Retrieve information about an operation response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Retrieve information about an operation
      tags:
        - API Shield Endpoint Management
      x-api-token-group:
        - Account API Gateway
        - Account API Gateway Read
        - Domain API Gateway
        - Domain API Gateway Read
    delete:
      operationId: api-shield-endpoint-management-delete-an-operation
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-shield_api-response-common'
          description: Delete an operation response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-shield_api-response-common-failure'
          description: Delete an operation response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete an operation
      tags:
        - API Shield Endpoint Management
      x-api-token-group:
        - Account API Gateway
        - Domain API Gateway
  /zones/{zone_id}/api_gateway/schemas:
    get:
      operationId: >-
        api-shield-endpoint-management-retrieve-operations-and-features-as-open-api-schemas
      parameters:
        - in: query
          name: host
          schema:
            description: Receive schema only for the given host(s).
            items:
              example: www.example.com
              type: string
            type: array
            uniqueItems: true
        - $ref: '#/components/parameters/api-shield_operation_feature_parameter'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/api-shield_schema-response-with-thresholds
          description: Retrieve operations and features as OpenAPI schemas response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-shield_api-response-common-failure'
          description: Retrieve operations and features as OpenAPI schemas response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Retrieve operations and features as OpenAPI schemas
      tags:
        - API Shield Endpoint Management
      x-api-token-group:
        - Account API Gateway
        - Account API Gateway Read
        - Domain API Gateway
        - Domain API Gateway Read
components:
  schemas:
    api-shield_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/api-shield_messages'
        messages:
          $ref: '#/components/schemas/api-shield_messages'
        success:
          description: Whether the API call was successful.
          enum:
            - true
          example: true
          type: boolean
      required:
        - success
        - errors
        - messages
      type: object
    api-shield_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/api-shield_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/api-shield_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    api-shield_basic_operation:
      properties:
        endpoint:
          $ref: '#/components/schemas/api-shield_endpoint'
        host:
          $ref: '#/components/schemas/api-shield_host'
        method:
          $ref: '#/components/schemas/api-shield_method'
      required:
        - method
        - host
        - endpoint
      type: object
    api-shield_multiple-operation-response:
      allOf:
        - $ref: '#/components/schemas/api-shield_api-response-common'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/api-shield_operation'
              type: array
          required:
            - result
          type: object
    api-shield_multiple-operation-response-paginated:
      allOf:
        - $ref: '#/components/schemas/api-shield_api-response-collection'
        - properties:
            result:
              items:
                allOf:
                  - $ref: '#/components/schemas/api-shield_operation'
              type: array
          required:
            - result
          type: object
    api-shield_object-with-operation-id:
      properties:
        operation_id:
          allOf:
            - description: The ID of the operation
              type: string
              x-auditable: true
            - $ref: '#/components/schemas/api-shield_schemas-uuid'
      required:
        - operation_id
      type: object
    api-shield_schema-response-with-thresholds:
      allOf:
        - $ref: '#/components/schemas/api-shield_api-response-common'
        - properties:
            result:
              properties:
                schemas:
                  items:
                    $ref: '#/components/schemas/api-shield_openapi-with-thresholds'
                  type: array
                timestamp:
                  type: string
                  x-auditable: true
              type: object
          required:
            - result
          type: object
    api-shield_single-operation-response:
      allOf:
        - $ref: '#/components/schemas/api-shield_api-response-common'
        - properties:
            result:
              allOf:
                - $ref: '#/components/schemas/api-shield_operation'
          required:
            - result
          type: object
  parameters:
    api-shield_direction_parameter:
      in: query
      name: direction
      schema:
        description: Direction to order results.
        enum:
          - asc
          - desc
        example: desc
        type: string
    api-shield_endpoint_parameter:
      in: query
      name: endpoint
      schema:
        description: Filter results to only include endpoints containing this pattern.
        example: /api/v1
        type: string
    api-shield_host_parameter:
      in: query
      name: host
      schema:
        description: Filter results to only include the specified hosts.
        items:
          example: api.cloudflare.com
          type: string
        type: array
        uniqueItems: true
    api-shield_method_parameter:
      in: query
      name: method
      schema:
        description: Filter results to only include the specified HTTP methods.
        items:
          example: GET
          type: string
        type: array
        uniqueItems: true
    api-shield_operation_feature_parameter:
      description: >-
        Add feature(s) to the results. The feature name that is given here
        corresponds to the resulting feature object. Have a look at the
        top-level object description for more details on the specific meaning.
      in: query
      name: feature
      schema:
        example:
          - thresholds
        items:
          enum:
            - thresholds
            - parameter_schemas
            - schema_info
          example: thresholds
          type: string
        type: array
        uniqueItems: true
    api-shield_page:
      description: Page number of paginated results.
      in: query
      name: page
      schema:
        default: 1
        minimum: 1
        type: integer
    api-shield_per_page:
      description: Maximum number of results per page.
      in: query
      name: per_page
      schema:
        default: 20
        maximum: 50
        minimum: 5
        type: integer
