openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/certificate_authorities/hostname_associations:
    get:
      description: List Hostname Associations
      operationId: client-certificate-for-a-zone-list-hostname-associations
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_identifier'
        - in: query
          name: mtls_certificate_id
          schema:
            description: >-
              The UUID to match against for a certificate that was uploaded to
              the mTLS Certificate Management endpoint. If no
              mtls_certificate_id is given, the results will be the hostnames
              associated to your active Cloudflare Managed CA.
            example: b2134436-2555-4acf-be5b-26c48136575e
            maxLength: 36
            minLength: 36
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_hostname_associations_response
          description: List Hostname Associations Response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_api-response-common-failure
          description: List Hostname Associations Response Failure
      security:
        - api_email: []
          api_key: []
      summary: List Hostname Associations
      tags:
        - API Shield Client Certificates for a Zone
      x-api-token-group:
        - SSL and Certificates Write
        - SSL and Certificates Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    put:
      description: Replace Hostname Associations
      operationId: client-certificate-for-a-zone-put-hostname-associations
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/tls-certificates-and-hostnames_hostname_association
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_hostname_associations_response
          description: Replace Hostname Associations Response
        4XX:
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_api-response-common-failure
          description: Replace Hostname Associations Response Failure
      security:
        - api_email: []
          api_key: []
      summary: Replace Hostname Associations
      tags:
        - API Shield Client Certificates for a Zone
      x-api-token-group:
        - SSL and Certificates Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /zones/{zone_id}/client_certificates:
    get:
      description: >-
        List all of your Zone's API Shield mTLS Client Certificates by Status
        and/or using Pagination
      operationId: client-certificate-for-a-zone-list-client-certificates
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_identifier'
        - in: query
          name: status
          schema:
            description: Client Certitifcate Status to filter results by.
            enum:
              - all
              - active
              - pending_reactivation
              - pending_revocation
              - revoked
            example: all
        - in: query
          name: page
          schema:
            default: 1
            description: Page number of paginated results.
            minimum: 1
            type: number
        - in: query
          name: per_page
          schema:
            default: 20
            description: Number of records per page.
            maximum: 50
            minimum: 5
            type: number
        - in: query
          name: limit
          schema:
            description: Limit to the number of records returned.
            example: 10
            type: integer
        - in: query
          name: offset
          schema:
            description: Offset the results
            example: 10
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_client_certificate_response_collection
          description: List Client Certificates Response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_api-response-common-failure
          description: List Client Certificates Response Failure
      security:
        - api_email: []
          api_key: []
      summary: List Client Certificates
      tags:
        - API Shield Client Certificates for a Zone
      x-api-token-group:
        - SSL and Certificates Write
        - SSL and Certificates Read
      x-cfPermissionsRequired:
        enum:
          - '#ssl:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    post:
      description: Create a new API Shield mTLS Client Certificate
      operationId: client-certificate-for-a-zone-create-client-certificate
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                csr:
                  $ref: >-
                    #/components/schemas/tls-certificates-and-hostnames_schemas-csr
                validity_days:
                  $ref: >-
                    #/components/schemas/tls-certificates-and-hostnames_schemas-validity_days
              required:
                - csr
                - validity_days
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_client_certificate_response_single
          description: Create Client Certificate Response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_client_certificate_response_single
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_api-response-common-failure
          description: Create Client Certificate Response Failure
      security:
        - api_email: []
          api_key: []
      summary: Create Client Certificate
      tags:
        - API Shield Client Certificates for a Zone
      x-api-token-group:
        - SSL and Certificates Write
      x-cfPermissionsRequired:
        enum:
          - '#ssl:edit'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /zones/{zone_id}/client_certificates/{client_certificate_id}:
    get:
      description: Get Details for a single mTLS API Shield Client Certificate
      operationId: client-certificate-for-a-zone-client-certificate-details
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_identifier'
        - in: path
          name: client_certificate_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_client_certificate_response_single
          description: Client Certificate Details Response
        4XX:
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_api-response-common-failure
          description: Client Certificate Details Response Failure
      security:
        - api_email: []
          api_key: []
      summary: Client Certificate Details
      tags:
        - API Shield Client Certificates for a Zone
      x-api-token-group:
        - SSL and Certificates Write
        - SSL and Certificates Read
      x-cfPermissionsRequired:
        enum:
          - '#ssl:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    patch:
      description: >-
        If a API Shield mTLS Client Certificate is in a pending_revocation
        state, you may reactivate it with this endpoint.
      operationId: client-certificate-for-a-zone-edit-client-certificate
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_identifier'
        - in: path
          name: client_certificate_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_client_certificate_response_single
          description: Reactivate Client Certificate Response
        4XX:
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_api-response-common-failure
          description: Reactivate Client Certificate Response Failure
      security:
        - api_email: []
          api_key: []
      summary: Reactivate Client Certificate
      tags:
        - API Shield Client Certificates for a Zone
      x-api-token-group:
        - SSL and Certificates Write
      x-cfPermissionsRequired:
        enum:
          - '#ssl:edit'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    delete:
      description: >-
        Set a API Shield mTLS Client Certificate to pending_revocation status
        for processing to revoked status.
      operationId: client-certificate-for-a-zone-delete-client-certificate
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_identifier'
        - in: path
          name: client_certificate_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_client_certificate_response_single
          description: Revoke Client Certificate Response
        4XX:
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_api-response-common-failure
          description: Revoke Client Certificate Response Failure
      security:
        - api_email: []
          api_key: []
      summary: Revoke Client Certificate
      tags:
        - API Shield Client Certificates for a Zone
      x-api-token-group:
        - SSL and Certificates Write
      x-cfPermissionsRequired:
        enum:
          - '#ssl:edit'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    tls-certificates-and-hostnames_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/tls-certificates-and-hostnames_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/tls-certificates-and-hostnames_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    tls-certificates-and-hostnames_client_certificate_response_collection:
      allOf:
        - $ref: >-
            #/components/schemas/tls-certificates-and-hostnames_api-response-collection
        - properties:
            result:
              items:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_client_certificate
              type: array
    tls-certificates-and-hostnames_client_certificate_response_single:
      allOf:
        - $ref: >-
            #/components/schemas/tls-certificates-and-hostnames_api-response-single
        - properties:
            result:
              $ref: >-
                #/components/schemas/tls-certificates-and-hostnames_client_certificate
    tls-certificates-and-hostnames_hostname_association:
      properties:
        hostnames:
          $ref: >-
            #/components/schemas/tls-certificates-and-hostnames_schemas-hostnames
        mtls_certificate_id:
          description: >-
            The UUID for a certificate that was uploaded to the mTLS Certificate
            Management endpoint. If no mtls_certificate_id is given, the
            hostnames will be associated to your active Cloudflare Managed CA.
          maxLength: 36
          minLength: 36
          type: string
          x-auditable: true
      type: object
    tls-certificates-and-hostnames_hostname_associations_response:
      allOf:
        - $ref: >-
            #/components/schemas/tls-certificates-and-hostnames_api-response-single
        - properties:
            result:
              properties:
                hostnames:
                  $ref: >-
                    #/components/schemas/tls-certificates-and-hostnames_schemas-hostnames
              type: object
    tls-certificates-and-hostnames_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    tls-certificates-and-hostnames_schemas-csr:
      description: The Certificate Signing Request (CSR). Must be newline-encoded.
      example: >-
        -----BEGIN CERTIFICATE REQUEST-----\nMIICY....\n-----END CERTIFICATE
        REQUEST-----\n
      type: string
      x-auditable: true
    tls-certificates-and-hostnames_schemas-validity_days:
      description: >-
        The number of days the Client Certificate will be valid after the
        issued_on date
      example: 3650
      type: integer
      x-auditable: true
