openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/api_gateway/discovery:
    get:
      description: >-
        Retrieve the most up to date view of discovered operations, rendered as
        OpenAPI schemas
      operationId: >-
        api-shield-api-discovery-retrieve-discovered-operations-on-a-zone-as-openapi
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-shield_schema_response_discovery'
          description: >-
            Retrieve discovered operations on a zone, rendered as OpenAPI
            schemas response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/api-shield_schema_response_discovery'
                  - $ref: >-
                      #/components/schemas/api-shield_api-response-common-failure
          description: >-
            Retrieve discovered operations on a zone, rendered as OpenAPI
            schemas response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Retrieve discovered operations on a zone rendered as OpenAPI schemas
      tags:
        - API Shield API Discovery
      x-api-token-group:
        - Account API Gateway
        - Account API Gateway Read
        - Domain API Gateway
        - Domain API Gateway Read
  /zones/{zone_id}/api_gateway/discovery/operations:
    get:
      description: Retrieve the most up to date view of discovered operations
      operationId: api-shield-api-discovery-retrieve-discovered-operations-on-a-zone
      parameters:
        - $ref: '#/components/parameters/api-shield_page'
        - $ref: '#/components/parameters/api-shield_per_page'
        - $ref: '#/components/parameters/api-shield_host_parameter'
        - $ref: '#/components/parameters/api-shield_method_parameter'
        - $ref: '#/components/parameters/api-shield_endpoint_parameter'
        - $ref: '#/components/parameters/api-shield_direction_parameter'
        - $ref: '#/components/parameters/api-shield_order_parameter'
        - $ref: '#/components/parameters/api-shield_diff_parameter'
        - $ref: '#/components/parameters/api-shield_api_discovery_origin_parameter'
        - $ref: '#/components/parameters/api-shield_api_discovery_state_parameter'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/api-shield_api-response-collection'
                  - properties:
                      result:
                        items:
                          $ref: '#/components/schemas/api-shield_discovery_operation'
                        type: array
                    required:
                      - result
                    type: object
          description: Retrieve discovered operations on a zone response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/api-shield_api-response-common-failure
          description: Retrieve discovered operations on a zone response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Retrieve discovered operations on a zone
      tags:
        - API Shield API Discovery
      x-api-token-group:
        - Account API Gateway
        - Account API Gateway Read
        - Domain API Gateway
        - Domain API Gateway Read
    patch:
      description: Update the `state` on one or more discovered operations
      operationId: api-shield-api-patch-discovered-operations
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/api-shield_api_discovery_patch_multiple_request
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-shield_patch_discoveries_response'
          description: Patch discovered operations response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-shield_api-response-common-failure'
          description: Patch discovered operations response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Patch discovered operations
      tags:
        - API Shield API Discovery
      x-api-token-group:
        - Account API Gateway
        - Domain API Gateway
  /zones/{zone_id}/api_gateway/discovery/operations/{operation_id}:
    patch:
      description: Update the `state` on a discovered operation
      operationId: api-shield-api-patch-discovered-operation
      requestBody:
        content:
          application/json:
            schema:
              properties:
                state:
                  allOf:
                    - $ref: >-
                        #/components/schemas/api-shield_api_discovery_state_patch
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-shield_patch_discovery_response'
          description: Patch discovered operation response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-shield_api-response-common-failure'
          description: Patch discovered operation response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Patch discovered operation
      tags:
        - API Shield API Discovery
      x-api-token-group:
        - Account API Gateway
        - Domain API Gateway
components:
  schemas:
    api-shield_api-response-collection:
      allOf:
        - $ref: '#/components/schemas/api-shield_api-response-common'
        - properties:
            result_info:
              properties:
                count:
                  description: Total number of results for the requested service.
                  example: 1
                  type: number
                page:
                  description: Current page within paginated list of results.
                  example: 1
                  type: number
                per_page:
                  description: Number of results per page of results.
                  example: 20
                  type: number
                total_count:
                  description: Total results available without any search parameters.
                  example: 2000
                  type: number
              type: object
          type: object
      type: object
    api-shield_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/api-shield_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/api-shield_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    api-shield_api_discovery_patch_multiple_request:
      additionalProperties:
        $ref: >-
          #/components/schemas/api-shield_api_discovery_patch_multiple_request_entry
      example:
        3818d821-5901-4147-a474-f5f5aec1d54e:
          state: ignored
        b17c8043-99a0-4202-b7d9-8f7cdbee02cd:
          state: review
      type: object
    api-shield_api_discovery_state_patch:
      description: |
        Mark state of operation in API Discovery
          * `review` - Mark operation as for review
          * `ignored` - Mark operation as ignored
      enum:
        - review
        - ignored
      type: string
      x-auditable: true
    api-shield_discovery_operation:
      allOf:
        - properties:
            features:
              $ref: '#/components/schemas/api-shield_traffic_stats'
            id:
              $ref: '#/components/schemas/api-shield_schemas-uuid'
            last_updated:
              $ref: '#/components/schemas/api-shield_schemas-timestamp'
            origin:
              description: API discovery engine(s) that discovered this operation
              items:
                $ref: '#/components/schemas/api-shield_api_discovery_origin'
              type: array
            state:
              $ref: '#/components/schemas/api-shield_api_discovery_state'
          required:
            - id
            - last_updated
            - state
            - origin
          type: object
        - $ref: '#/components/schemas/api-shield_basic_operation'
    api-shield_patch_discoveries_response:
      allOf:
        - $ref: '#/components/schemas/api-shield_api-response-common'
        - properties:
            result:
              $ref: >-
                #/components/schemas/api-shield_api_discovery_patch_multiple_request
          required:
            - result
          type: object
    api-shield_patch_discovery_response:
      allOf:
        - $ref: '#/components/schemas/api-shield_api-response-common'
        - properties:
            result:
              properties:
                state:
                  $ref: '#/components/schemas/api-shield_api_discovery_state'
              type: object
          required:
            - result
          type: object
    api-shield_schema_response_discovery:
      allOf:
        - $ref: '#/components/schemas/api-shield_api-response-common'
        - properties:
            result:
              properties:
                schemas:
                  items:
                    $ref: '#/components/schemas/api-shield_openapi'
                  type: array
                timestamp:
                  $ref: '#/components/schemas/api-shield_schemas-timestamp'
              required:
                - timestamp
                - schemas
              type: object
          required:
            - result
          type: object
  parameters:
    api-shield_api_discovery_origin_parameter:
      description: >
        Filter results to only include discovery results sourced from a
        particular discovery engine
          * `ML` - Discovered operations that were sourced using ML API Discovery
          * `SessionIdentifier` - Discovered operations that were sourced using Session Identifier API Discovery
      in: query
      name: origin
      schema:
        $ref: '#/components/schemas/api-shield_api_discovery_origin'
    api-shield_api_discovery_state_parameter:
      description: >
        Filter results to only include discovery results in a particular state.
        States are as follows
          * `review` - Discovered operations that are not saved into API Shield Endpoint Management
          * `saved` - Discovered operations that are already saved into API Shield Endpoint Management
          * `ignored` - Discovered operations that have been marked as ignored
      in: query
      name: state
      schema:
        $ref: '#/components/schemas/api-shield_api_discovery_state'
    api-shield_diff_parameter:
      in: query
      name: diff
      schema:
        description: >-
          When `true`, only return API Discovery results that are not saved into
          API Shield Endpoint Management
        type: boolean
    api-shield_direction_parameter:
      in: query
      name: direction
      schema:
        description: Direction to order results.
        enum:
          - asc
          - desc
        example: desc
        type: string
    api-shield_endpoint_parameter:
      in: query
      name: endpoint
      schema:
        description: Filter results to only include endpoints containing this pattern.
        example: /api/v1
        type: string
    api-shield_host_parameter:
      in: query
      name: host
      schema:
        description: Filter results to only include the specified hosts.
        items:
          example: api.cloudflare.com
          type: string
        type: array
        uniqueItems: true
    api-shield_method_parameter:
      in: query
      name: method
      schema:
        description: Filter results to only include the specified HTTP methods.
        items:
          example: GET
          type: string
        type: array
        uniqueItems: true
    api-shield_order_parameter:
      in: query
      name: order
      schema:
        description: Field to order by
        enum:
          - host
          - method
          - endpoint
          - traffic_stats.requests
          - traffic_stats.last_updated
        example: method
        type: string
    api-shield_page:
      description: Page number of paginated results.
      in: query
      name: page
      schema:
        default: 1
        minimum: 1
        type: integer
    api-shield_per_page:
      description: Maximum number of results per page.
      in: query
      name: per_page
      schema:
        default: 20
        maximum: 50
        minimum: 5
        type: integer
