openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/pagerules/settings:
    get:
      deprecated: true
      description: >-
        Returns a list of settings (and their details) that Page Rules can apply
        to matching requests.
      operationId: available-page-rules-settings-list-available-page-rules-settings
      parameters:
        - example: 023e105f4ecef8ad9ca31a8372d0c353
          in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/zones_schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/zones_schemas-api-response-common'
                  - properties:
                      result:
                        $ref: '#/components/schemas/zones_settings'
          description: List available Page Rules settings response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zones_schemas-api-response-common-failure'
          description: List available Page Rules settings response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: List available Page Rules settings
      tags:
        - Available Page Rules settings
      x-api-token-group:
        - Zone Read
        - Zone Write
        - Page Rules Write
        - Page Rules Read
components:
  schemas:
    zones_schemas-api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/zones_schemas-messages'
        messages:
          $ref: '#/components/schemas/zones_schemas-messages'
        success:
          description: Whether the API call was successful.
          enum:
            - true
          example: true
          type: boolean
      required:
        - success
        - errors
        - messages
      type: object
    zones_schemas-api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/zones_schemas-messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/zones_schemas-messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    zones_schemas-identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
    zones_settings:
      description: Settings available for the zone.
      example:
        - id: browser_check
          properties:
            - name: value
              type: toggle
        - id: browser_cache_ttl
          properties:
            - max: 31536000
              min: 1800
              name: value
              suggested_values:
                - 1800
                - 3600
                - 7200
                - 10800
                - 14400
                - 18000
                - 28800
                - 43200
                - 57600
                - 72000
                - 86400
                - 172800
                - 259200
                - 345600
                - 432000
                - 691200
                - 1382400
                - 2073600
                - 2678400
                - 5356800
                - 16070400
                - 31536000
              type: range
        - id: browser_check
          properties:
            - name: value
              type: toggle
        - id: cache_key_fields
          properties:
            - name: value
              properties:
                - allowEmpty: true
                  choices:
                    - include
                    - exclude
                  multiple: false
                  name: query_string
                  type: select
                - allowEmpty: true
                  choices:
                    - include
                    - exclude
                    - check_presence
                  multiple: true
                  name: header
                  type: select
                - allowEmpty: false
                  choices:
                    - resolved
                  multiple: true
                  name: host
                  type: select
                - allowEmpty: true
                  choices:
                    - include
                    - check_presence
                  multiple: true
                  name: cookie
                  type: select
                - allowEmpty: false
                  choices:
                    - device_type
                    - geo
                    - lang
                  multiple: true
                  name: user
                  type: select
              type: object
        - id: cache_deception_armor
          properties:
            - name: value
              type: toggle
        - id: cache_level
          properties:
            - choices:
                - bypass
                - basic
                - simplified
                - aggressive
                - cache_everything
              multiple: false
              name: value
              type: select
        - id: cache_ttl_by_status
          properties:
            - allowEmpty: false
              name: value
              type: object
        - id: disable_apps
          properties: []
        - id: disable_performance
          properties: []
        - id: disable_security
          properties: []
        - id: edge_cache_ttl
          properties:
            - max: 2419200
              min: 7200
              name: value
              suggested_values:
                - 7200
                - 10800
                - 14400
                - 18000
                - 28800
                - 43200
                - 57600
                - 72000
                - 86400
                - 172800
                - 259200
                - 345600
                - 432000
                - 518400
                - 604800
                - 1209600
                - 2419200
              type: range
        - id: email_obfuscation
          properties:
            - name: value
              type: toggle
        - id: forwarding_url
          properties:
            - choices:
                - 301
                - 302
              multiple: false
              name: status_code
              type: choice
            - name: url
              type: forwardingUrl
        - id: ip_geolocation
          properties:
            - name: value
              type: toggle
        - id: explicit_cache_control
          properties:
            - name: value
              type: toggle
        - id: rocket_loader
          properties:
            - name: value
              type: toggle
        - id: security_level
          properties:
            - choices:
                - essentially_off
                - low
                - medium
                - high
                - under_attack
              multiple: false
              name: value
              type: select
        - id: server_side_exclude
          properties:
            - name: value
              type: toggle
        - id: ssl
          properties:
            - choices:
                - 'off'
                - flexible
                - full
                - strict
              multiple: false
              name: value
              type: choice
      items:
        type: object
      type: array
