openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/cloudforce-one/binary:
    post:
      operationId: post_BinDBPost
      parameters:
        - description: Account ID.
          in: path
          name: account_id
          required: true
          schema:
            description: Account ID.
            type: number
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  description: The binary file content to upload.
                  format: binary
                  type: string
              required:
                - file
              type: object
        description: Binary file to be uploaded to the database.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  content_type:
                    example: text/plain
                    type: string
                  md5:
                    example: 5d84ade76d2a8387c81175bb0cbe6492
                    type: string
                  sha1:
                    example: 9aff6879626d957eafadda044e4f879aae1e7278
                    type: string
                  sha256:
                    example: >-
                      0000a7f2692ef479e2e3d02661568882cadec451cc8a64d4e7faca29810cd626
                    type: string
                required:
                  - md5
                  - sha1
                  - sha256
                  - content_type
                type: object
          description: Returns file information
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          example: An error occurred.
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  result:
                    type: object
                  success:
                    type: boolean
                required:
                  - result
                  - success
                  - errors
                type: object
          description: Bad Request.
      security:
        - api_token: []
      summary: Posts a file to Binary Storage
      tags:
        - BinDB
      x-api-token-group:
        - Cloudforce One Write
        - Cloudforce One Read
  /accounts/{account_id}/cloudforce-one/binary/{hash}:
    get:
      operationId: get_BinDBGetBinary
      parameters:
        - description: Account ID.
          in: path
          name: account_id
          required: true
          schema:
            description: Account ID.
            type: number
        - description: hash of the binary
          in: path
          name: hash
          required: true
          schema:
            description: hash of the binary
            type: string
      responses:
        '200':
          description: Returns file information
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          example: An error occurred.
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  result:
                    type: object
                  success:
                    type: boolean
                required:
                  - result
                  - success
                  - errors
                type: object
          description: Bad Request.
      security:
        - api_token: []
      summary: Retrieves a file from Binary Storage
      tags:
        - BinDB
      x-api-token-group:
        - Cloudforce One Write
        - Cloudforce One Read
