openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/botnet_feed/asn/{asn_id}/day_report:
    get:
      description: >-
        Gets all the data the botnet tracking database has for a given ASN
        registered to user account for given date. If no date is given, it will
        return results for the previous day.
      operationId: botnet-threat-feed-get-day-report
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/dos_identifier'
        - in: path
          name: asn_id
          required: true
          schema:
            $ref: '#/components/schemas/dos_asn'
        - in: query
          name: date
          schema:
            $ref: '#/components/schemas/dos_timestamp'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dos_api-response-common'
                  - properties:
                      result:
                        properties:
                          cidr:
                            example: 1.1.1.1/32
                            type: string
                          date:
                            example: '2014-01-01T05:20:00.12345Z'
                            format: date-time
                            type: string
                          offense_count:
                            example: 1000
                            type: integer
                        type: object
                    type: object
                type: object
          description: Get botnet feed report for day
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dos_api-response-common-failure'
          description: Get botnet feed report for day response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get daily report
      tags:
        - Botnet Threat Feed
      x-api-token-group:
        - DDoS Botnet Feed Write
        - DDoS Botnet Feed Read
  /accounts/{account_id}/botnet_feed/asn/{asn_id}/full_report:
    get:
      description: >-
        Gets all the data the botnet threat feed tracking database has for a
        given ASN registered to user account.
      operationId: botnet-threat-feed-get-full-report
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/dos_identifier'
        - in: path
          name: asn_id
          required: true
          schema:
            $ref: '#/components/schemas/dos_asn'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dos_api-response-common'
                  - properties:
                      result:
                        properties:
                          cidr:
                            example: 1.1.1.1/32
                            type: string
                          date:
                            example: '2014-01-01T05:20:00.12345Z'
                            format: date-time
                            type: string
                          offense_count:
                            example: 1000
                            type: integer
                        type: object
                    type: object
                type: object
          description: Get full botnet feed report
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dos_api-response-common-failure'
          description: Get full botnet feed report response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get full report
      tags:
        - Botnet Threat Feed
      x-api-token-group:
        - DDoS Botnet Feed Write
        - DDoS Botnet Feed Read
  /accounts/{account_id}/botnet_feed/configs/asn:
    get:
      description: >-
        Gets a list of all ASNs registered for a user for the DDoS Botnet Feed
        API.
      operationId: botnet-threat-feed-list-asn
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/dos_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dos_api-response-common'
                  - properties:
                      result:
                        properties:
                          asn:
                            example: 13335
                            type: integer
                        type: object
                    type: object
                type: object
          description: Get list of ASNs response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dos_api-response-common-failure'
          description: Get list of ASNs response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get list of ASNs
      tags:
        - Botnet Threat Feed
      x-api-token-group:
        - DDoS Botnet Feed Write
        - DDoS Botnet Feed Read
  /accounts/{account_id}/botnet_feed/configs/asn/{asn_id}:
    delete:
      description: Delete an ASN from botnet threat feed for a given user.
      operationId: botnet-threat-feed-delete-asn
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/dos_identifier'
        - in: path
          name: asn_id
          required: true
          schema:
            $ref: '#/components/schemas/dos_asn'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dos_api-response-common'
                  - properties:
                      result:
                        properties:
                          asn:
                            example: 13335
                            type: integer
                        type: object
                    type: object
                type: object
          description: Delete ASN response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dos_api-response-common-failure'
          description: Delete ASN response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete an ASN
      tags:
        - Botnet Threat Feed
      x-api-token-group:
        - DDoS Botnet Feed Write
components:
  schemas:
    dos_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/dos_messages'
        messages:
          $ref: '#/components/schemas/dos_messages'
        success:
          description: Whether the API call was successful.
          enum:
            - true
          example: true
          type: boolean
      required:
        - success
        - errors
        - messages
      type: object
    dos_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/dos_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/dos_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    dos_asn:
      type: integer
    dos_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    dos_timestamp:
      example: '2014-01-01T05:20:00.12345Z'
      format: date-time
      type: string
