openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/brand-protection/alerts:
    get:
      description: Return all alerts on submitted domains
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Read all alerts on submitted domains
      tags:
        - brand_protection
      x-api-token-group:
        - Intel Write
        - Intel Read
    patch:
      description: >-
        Return a success message after updating alerts on submitted domains by
        ID
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Update alerts on submitted domains by ID
      tags:
        - brand_protection
      x-api-token-group:
        - Intel Write
  /accounts/{account_id}/brand-protection/alerts/clear:
    patch:
      description: >-
        Return a success message after updating verification statuses of tracked
        URLs to awaiting by ID
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Update verification statuses of tracked URLs to awaiting by ID
      tags:
        - brand_protection
      x-api-token-group:
        - Intel Write
  /accounts/{account_id}/brand-protection/alerts/refute:
    patch:
      description: >-
        Return a success message after updating verification statuses of tracked
        URLs to disproven by ID
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Update verification statuses of tracked URLs to disproven by ID
      tags:
        - brand_protection
      x-api-token-group:
        - Intel Write
  /accounts/{account_id}/brand-protection/alerts/verify:
    patch:
      description: >-
        Return a success message after updating verification statuses of tracked
        URLs to confirmed by ID
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Update verification statuses of tracked URLs to confirmed by ID
      tags:
        - brand_protection
      x-api-token-group:
        - Intel Write
  /accounts/{account_id}/brand-protection/brands:
    get:
      description: Return all brands
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Read all brands
      tags:
        - brand_protection
      x-api-token-group:
        - Intel Write
        - Intel Read
    post:
      description: Return new brands
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Create new brands
      tags:
        - brand_protection
      x-api-token-group:
        - Intel Write
    delete:
      description: Return a success message after deleting brands by ID
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Delete brands by ID
      tags:
        - brand_protection
      x-api-token-group:
        - Intel Write
  /accounts/{account_id}/brand-protection/brands/patterns:
    get:
      description: Return patterns for brands based on ID
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Read patterns for brands by ID
      tags:
        - brand_protection
      x-api-token-group:
        - Intel Write
        - Intel Read
    post:
      description: Return a success message after creating new patterns for brands by ID
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Create new patterns for brands by ID
      tags:
        - brand_protection
      x-api-token-group:
        - Intel Write
    delete:
      description: Return a success message after deleting patterns for brands by ID
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Delete patterns for brands by ID
      tags:
        - brand_protection
      x-api-token-group:
        - Intel Write
  /accounts/{account_id}/brand-protection/clear:
    patch:
      description: >-
        Return a success message after updating verification statuses of
        submitted URLs to awaiting by ID
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Update verification statuses of submitted URLs to awaiting by ID
      tags:
        - brand_protection
      x-api-token-group:
        - Intel Write
  /accounts/{account_id}/brand-protection/domain-info:
    get:
      description: Return submitted domains based on ID
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Read submitted domains by ID
      tags:
        - brand_protection
      x-api-token-group:
        - Intel Write
        - Intel Read
  /accounts/{account_id}/brand-protection/recent-submissions:
    get:
      description: Return recent URL submissions
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Read recent URL submissions
      tags:
        - brand_protection
      x-api-token-group:
        - Intel Write
        - Intel Read
  /accounts/{account_id}/brand-protection/refute:
    patch:
      description: >-
        Return a success message after updating verification statuses of
        submitted URLs to disproven by ID
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Update verification statuses of submitted URLs to disproven by ID
      tags:
        - brand_protection
      x-api-token-group:
        - Intel Write
  /accounts/{account_id}/brand-protection/submission-info:
    get:
      description: Return URL submissions based on ID
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Read URL submissions by ID
      tags:
        - brand_protection
      x-api-token-group:
        - Intel Write
        - Intel Read
  /accounts/{account_id}/brand-protection/submit:
    post:
      description: Return new URL submissions
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/brand-protection-api_URLSubmit'
          description: Created
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Create new URL submissions
      tags:
        - brand_protection
      x-api-token-group:
        - Intel Write
  /accounts/{account_id}/brand-protection/tracked-domains:
    get:
      description: Return submitted domains based on pattern
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Read submitted domains by pattern
      tags:
        - brand_protection
      x-api-token-group:
        - Intel Write
        - Intel Read
  /accounts/{account_id}/brand-protection/url-info:
    get:
      description: Return submitted URLs based on ID
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/brand-protection-api_URLInfo'
          description: OK
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Read submitted URLs by ID
      tags:
        - brand_protection
      x-api-token-group:
        - Intel Write
        - Intel Read
  /accounts/{account_id}/brand-protection/verify:
    patch:
      description: >-
        Return a success message after updating verification statuses of
        submitted URLs to confirmed by ID
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Update verification statuses of submitted URLs to confirmed by ID
      tags:
        - brand_protection
      x-api-token-group:
        - Intel Write
  /internal/submit:
    post:
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Internal route for testing URL submissions
      tags:
        - brand_protection
  /live:
    get:
      description: Return a success message after running liveness checks
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Run liveness checks
      tags:
        - brand_protection
  /ready:
    get:
      description: Return a success message after running readiness checks
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Run readiness checks
      tags:
        - brand_protection
components:
  schemas:
    brand-protection-api_URLInfo:
      properties:
        result:
          items:
            additionalProperties: {}
            type: object
          type: array
      type: object
    brand-protection-api_URLSubmit:
      properties:
        skipped_urls:
          items:
            additionalProperties: {}
            type: object
          type: array
        submitted_urls:
          items:
            additionalProperties: {}
            type: object
          type: array
      type: object
  responses:
    brand-protection-api_DEFAULT_ERROR:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/brand-protection-api_Error'
      description: Default error response
