openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/calls/turn_keys:
    get:
      description: Lists all TURN keys in the Cloudflare account
      operationId: calls-turn-key-list
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/calls_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_turn_key_collection'
          description: List TURN key response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_api-response-common-failure'
          description: List TURN key response failure
      security:
        - api_token: []
      summary: List TURN Keys
      tags:
        - Calls TURN Keys
      x-api-token-group:
        - Calls Write
        - Calls Read
    post:
      description: Creates a new Cloudflare Calls TURN key.
      operationId: calls-turn-key-create
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/calls_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/calls_turn_key_editable_fields'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_turn_key_with_key'
          description: Created a new TURN key
      security:
        - api_token: []
      summary: Create a new TURN key
      tags:
        - Calls TURN Keys
      x-api-token-group:
        - Calls Write
  /accounts/{account_id}/calls/turn_keys/{key_id}:
    get:
      description: Fetches details for a single TURN key.
      operationId: calls-retrieve-turn-key-details
      parameters:
        - in: path
          name: key_id
          required: true
          schema:
            $ref: '#/components/schemas/calls_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/calls_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_turn_key_response_single'
          description: Retrieve TURN key details response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_api-response-common-failure'
          description: Retrieve TURN key details failure
      security:
        - api_token: []
      summary: Retrieve TURN key details
      tags:
        - Calls TURN Keys
      x-api-token-group:
        - Calls Write
        - Calls Read
    put:
      description: Edit details for a single TURN key.
      operationId: calls-update-turn-key
      parameters:
        - in: path
          name: key_id
          required: true
          schema:
            $ref: '#/components/schemas/calls_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/calls_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/calls_turn_key_editable_fields'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_turn_key_response_single'
          description: Edit TURN key details response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_api-response-common-failure'
          description: Edit TURN key details response failure
      security:
        - api_token: []
      summary: Edit TURN key details
      tags:
        - Calls TURN Keys
      x-api-token-group:
        - Calls Write
    delete:
      description: Deletes a TURN key from Cloudflare Calls
      operationId: calls-delete-turn-key
      parameters:
        - in: path
          name: key_id
          required: true
          schema:
            $ref: '#/components/schemas/calls_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/calls_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_turn_key_response_single'
          description: Delete TURN key response
        4XX:
          content:
            application/json: {}
          description: Delete TURN key response failure
      security:
        - api_token: []
      summary: Delete TURN key
      tags:
        - Calls TURN Keys
      x-api-token-group:
        - Calls Write
components:
  schemas:
    calls_account_identifier:
      description: The account identifier tag.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
    calls_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/calls_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/calls_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    calls_identifier:
      description: A Cloudflare-generated unique identifier for a item.
      example: 2a95132c15732412d22c1476fa83f27a
      maxLength: 32
      minLength: 32
      type: string
      x-auditable: true
    calls_turn_key_collection:
      allOf:
        - $ref: '#/components/schemas/calls_api-response-common'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/calls_turn_key_object'
              type: array
    calls_turn_key_editable_fields:
      properties:
        name:
          $ref: '#/components/schemas/calls_turn_key_name'
      type: object
    calls_turn_key_response_single:
      allOf:
        - $ref: '#/components/schemas/calls_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/calls_turn_key_object'
    calls_turn_key_with_key:
      properties:
        created:
          $ref: '#/components/schemas/calls_created'
        key:
          $ref: '#/components/schemas/calls_turn_key'
        modified:
          $ref: '#/components/schemas/calls_modified'
        name:
          $ref: '#/components/schemas/calls_turn_key_name'
        uid:
          $ref: '#/components/schemas/calls_identifier'
      type: object
