openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/calls/apps:
    get:
      description: Lists all apps in the Cloudflare account
      operationId: calls-apps-list
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/calls_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_app_response_collection'
          description: List apps response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_api-response-common-failure'
          description: List apps response failure
      security:
        - api_token: []
      summary: List apps
      tags:
        - Calls Apps
      x-api-token-group:
        - Calls Write
        - Calls Read
    post:
      description: >-
        Creates a new Cloudflare calls app. An app is an unique enviroment where
        each Session can access all Tracks within the app.
      operationId: calls-apps-create-a-new-app
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/calls_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/calls_app_editable_fields'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_app_response_single_with_secret'
          description: Created a new app
      security:
        - api_token: []
      summary: Create a new app
      tags:
        - Calls Apps
      x-api-token-group:
        - Calls Write
  /accounts/{account_id}/calls/apps/{app_id}:
    get:
      description: Fetches details for a single Calls app.
      operationId: calls-apps-retrieve-app-details
      parameters:
        - in: path
          name: app_id
          required: true
          schema:
            $ref: '#/components/schemas/calls_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/calls_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_app_response_single'
          description: Retrieve app details response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_api-response-common-failure'
          description: Retrieve app details response failure
      security:
        - api_token: []
      summary: Retrieve app details
      tags:
        - Calls Apps
      x-api-token-group:
        - Calls Write
        - Calls Read
    put:
      description: Edit details for a single app.
      operationId: calls-apps-update-app-details
      parameters:
        - in: path
          name: app_id
          required: true
          schema:
            $ref: '#/components/schemas/calls_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/calls_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/calls_app_editable_fields'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_app_response_single'
          description: Edit app details response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_api-response-common-failure'
          description: Edit app details response failure
      security:
        - api_token: []
      summary: Edit app details
      tags:
        - Calls Apps
      x-api-token-group:
        - Calls Write
    delete:
      description: Deletes an app from Cloudflare Calls
      operationId: calls-apps-delete-app
      parameters:
        - in: path
          name: app_id
          required: true
          schema:
            $ref: '#/components/schemas/calls_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/calls_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_app_response_single'
          description: Delete app response
        4XX:
          content:
            application/json: {}
          description: Delete app response failure
      security:
        - api_token: []
      summary: Delete app
      tags:
        - Calls Apps
      x-api-token-group:
        - Calls Write
components:
  schemas:
    calls_account_identifier:
      description: The account identifier tag.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
    calls_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/calls_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/calls_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    calls_app_editable_fields:
      properties:
        name:
          $ref: '#/components/schemas/calls_name'
      type: object
    calls_app_response_collection:
      allOf:
        - $ref: '#/components/schemas/calls_api-response-common'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/calls_app'
              type: array
    calls_app_response_single:
      allOf:
        - $ref: '#/components/schemas/calls_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/calls_app'
    calls_app_response_single_with_secret:
      allOf:
        - $ref: '#/components/schemas/calls_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/calls_app_with_secret'
    calls_identifier:
      description: A Cloudflare-generated unique identifier for a item.
      example: 2a95132c15732412d22c1476fa83f27a
      maxLength: 32
      minLength: 32
      type: string
      x-auditable: true
