openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /ips:
    get:
      description: >-
        Get IPs used on the Cloudflare/JD Cloud network, see
        https://www.cloudflare.com/ips for Cloudflare IPs or
        https://developers.cloudflare.com/china-network/reference/infrastructure/
        for JD Cloud IPs.
      operationId: cloudflare-ips-cloudflare-ip-details
      parameters:
        - description: Specified as `jdcloud` to list IPs used by JD Cloud data centers.
          in: query
          name: networks
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/public-ip_api-response-single'
                  - properties:
                      result:
                        oneOf:
                          - $ref: '#/components/schemas/public-ip_ips'
                          - $ref: '#/components/schemas/public-ip_ips_jdcloud'
          description: Cloudflare IP Details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: '#/components/schemas/public-ip_api-response-single'
                      - properties:
                          result:
                            oneOf:
                              - $ref: '#/components/schemas/public-ip_ips'
                              - $ref: '#/components/schemas/public-ip_ips_jdcloud'
                  - $ref: '#/components/schemas/public-ip_api-response-common-failure'
          description: Cloudflare IP Details response failure
      security:
        - {}
      summary: Cloudflare/JD Cloud IP Details
      tags:
        - Cloudflare IPs
components:
  schemas:
    public-ip_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/public-ip_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/public-ip_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    public-ip_api-response-single:
      allOf:
        - $ref: '#/components/schemas/public-ip_api-response-common'
      type: object
    public-ip_ips:
      properties:
        etag:
          $ref: '#/components/schemas/public-ip_etag'
        ipv4_cidrs:
          $ref: '#/components/schemas/public-ip_ipv4_cidrs'
        ipv6_cidrs:
          $ref: '#/components/schemas/public-ip_ipv6_cidrs'
      type: object
    public-ip_ips_jdcloud:
      properties:
        etag:
          $ref: '#/components/schemas/public-ip_etag'
        ipv4_cidrs:
          $ref: '#/components/schemas/public-ip_ipv4_cidrs'
        ipv6_cidrs:
          $ref: '#/components/schemas/public-ip_ipv6_cidrs'
        jdcloud_cidrs:
          $ref: '#/components/schemas/public-ip_jdcloud_cidrs'
      type: object
