openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/images/v1/keys:
    get:
      description: >-
        Lists your signing keys. These can be found on your Cloudflare Images
        dashboard.
      operationId: cloudflare-images-keys-list-signing-keys
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/images_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/images_image_key_response_collection'
          description: List Signing Keys response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/images_image_key_response_collection'
                  - $ref: '#/components/schemas/images_api-response-common-failure'
          description: List Signing Keys response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: List Signing Keys
      tags:
        - Cloudflare Images Keys
      x-api-token-group:
        - Images Read
        - Images Write
  /accounts/{account_id}/images/v1/keys/{signing_key_name}:
    put:
      description: >-
        Create a new signing key with specified name. Returns all keys
        available.
      operationId: cloudflare-images-keys-add-signing-key
      parameters:
        - in: path
          name: signing_key_name
          required: true
          schema:
            $ref: '#/components/schemas/images_signing_key_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/images_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/images_image_key_response_collection'
          description: Add Signing Key response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/images_image_key_response_collection'
                  - $ref: '#/components/schemas/images_api-response-common-failure'
          description: Add Signing Key response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Create a new Signing Key
      tags:
        - Cloudflare Images Keys
    delete:
      description: |
        Delete signing key with specified name. Returns all keys available.
        When last key is removed, a new default signing key will be generated.
      operationId: cloudflare-images-keys-delete-signing-key
      parameters:
        - in: path
          name: signing_key_name
          required: true
          schema:
            $ref: '#/components/schemas/images_signing_key_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/images_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/images_image_key_response_collection'
          description: Delete Signing Key response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/images_image_key_response_collection'
                  - $ref: '#/components/schemas/images_api-response-common-failure'
          description: Delete Signing Key response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Delete Signing Key
      tags:
        - Cloudflare Images Keys
components:
  schemas:
    images_account_identifier:
      description: Account identifier tag.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
    images_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/images_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/images_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
          x-auditable: true
      required:
        - success
        - errors
        - messages
        - result
      type: object
    images_image_key_response_collection:
      allOf:
        - $ref: '#/components/schemas/images_api-response-common'
        - properties:
            result:
              $ref: '#/components/schemas/images_image_keys_response'
    images_signing_key_identifier:
      example: someKey
      maxLength: 20
      pattern: ^[a-zA-Z0-9]$
      type: string
      x-auditable: true
