openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/content-upload-scan/disable:
    post:
      description: Disable Content Scanning.
      operationId: waf-content-scanning-disable
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-product-api-bundle_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/waf-product-api-bundle_schemas-api-response-common
          description: Disable Content Scanning response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/waf-product-api-bundle_schemas-api-response-common-failure
          description: Disable Content Scanning failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Disable Content Scanning
      tags:
        - Content Scanning
      x-api-token-group:
        - Zone WAF Write
        - Account WAF Write
  /zones/{zone_id}/content-upload-scan/enable:
    post:
      description: Enable Content Scanning.
      operationId: waf-content-scanning-enable
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-product-api-bundle_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/waf-product-api-bundle_schemas-api-response-common
          description: Enable Content Scanning response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/waf-product-api-bundle_schemas-api-response-common-failure
          description: Enable Content Scanning failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Enable Content Scanning
      tags:
        - Content Scanning
      x-api-token-group:
        - Zone WAF Write
        - Account WAF Write
  /zones/{zone_id}/content-upload-scan/payloads:
    get:
      description: Get a list of existing custom scan expressions for Content Scanning.
      operationId: waf-content-scanning-list-custom-scan-expressions
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-product-api-bundle_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/waf-product-api-bundle_response-custom-scan-collection
          description: List existing Content Scan custom scan expressions response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/waf-product-api-bundle_response-custom-scan-collection
                  - $ref: >-
                      #/components/schemas/waf-product-api-bundle_schemas-api-response-common-failure
          description: List existing Content Scan custom scan expressions failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List Existing Custom Scan Expressions
      tags:
        - Content Scanning
      x-api-token-group:
        - Zone WAF Write
        - Zone WAF Read
        - Account WAF Write
        - Account WAF Read
    post:
      description: Add custom scan expressions for Content Scanning.
      operationId: waf-content-scanning-add-custom-scan-expressions
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-product-api-bundle_identifier'
      requestBody:
        content:
          application/json:
            schema:
              items:
                properties:
                  payload:
                    $ref: >-
                      #/components/schemas/waf-product-api-bundle_custom-scan-payload
                required:
                  - payload
                type: object
              type: array
        description: Array of custom scan expressions to add.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/waf-product-api-bundle_response-custom-scan-collection
          description: Add custom scan expressions for Content Scanning.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/waf-product-api-bundle_response-custom-scan-collection
                  - $ref: >-
                      #/components/schemas/waf-product-api-bundle_schemas-api-response-common-failure
          description: List existing Content Scan custom scan expressions failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Add Custom Scan Expressions
      tags:
        - Content Scanning
      x-api-token-group:
        - Zone WAF Write
        - Account WAF Write
  /zones/{zone_id}/content-upload-scan/payloads/{expression_id}:
    delete:
      description: Delete a Content Scan Custom Expression.
      operationId: waf-content-scanning-delete-custom-scan-expressions
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-product-api-bundle_identifier'
        - in: path
          name: expression_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-product-api-bundle_custom-scan-id'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/waf-product-api-bundle_response-custom-scan-collection
          description: Delete Content Scan custom scan expressions response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/waf-product-api-bundle_response-custom-scan-collection
                  - $ref: >-
                      #/components/schemas/waf-product-api-bundle_schemas-api-response-common-failure
          description: Delete Content Scan custom scan expressions failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete a Custom Scan Expression
      tags:
        - Content Scanning
      x-api-token-group:
        - Zone WAF Write
        - Account WAF Write
  /zones/{zone_id}/content-upload-scan/settings:
    get:
      description: Retrieve the current status of Content Scanning.
      operationId: waf-content-scanning-get-status
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-product-api-bundle_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/waf-product-api-bundle_schemas-response-status
          description: Get Content Scanning status response.
        4XX:
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/waf-product-api-bundle_schemas-api-response-common-failure
          description: Get Content Scanning status failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get Content Scanning Status
      tags:
        - Content Scanning
      x-api-token-group:
        - Zone WAF Write
        - Zone WAF Read
        - Account WAF Write
        - Account WAF Read
components:
  schemas:
    waf-product-api-bundle_custom-scan-id:
      allOf:
        - $ref: '#/components/schemas/waf-product-api-bundle_identifier'
      description: defines the unique ID for this custom scan expression.
      example: a350a054caa840c9becd89c3b4f0195b
    waf-product-api-bundle_custom-scan-payload:
      description: Defines the ruleset expression to use in matching content objects.
      example: lookup_json_string(http.request.body.raw, "file")
      type: string
      x-auditable: true
    waf-product-api-bundle_identifier:
      description: Defines an identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
    waf-product-api-bundle_response-custom-scan-collection:
      allOf:
        - $ref: >-
            #/components/schemas/waf-product-api-bundle_schemas-api-response-collection
        - properties:
            result:
              items:
                $ref: '#/components/schemas/waf-product-api-bundle_custom-scan'
              type: array
          type: object
    waf-product-api-bundle_schemas-api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/waf-product-api-bundle_messages'
        messages:
          $ref: '#/components/schemas/waf-product-api-bundle_messages'
        result:
          anyOf:
            - type: object
            - items:
                type: object
              type: array
            - nullable: true
              type: string
        success:
          description: Whether the API call was successful.
          enum:
            - true
          example: true
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    waf-product-api-bundle_schemas-api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/waf-product-api-bundle_messages'
          example:
            - code: 10000
              message: Authentication error
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/waf-product-api-bundle_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    waf-product-api-bundle_schemas-response-status:
      allOf:
        - $ref: >-
            #/components/schemas/waf-product-api-bundle_schemas-api-response-single
        - properties:
            result:
              $ref: '#/components/schemas/waf-product-api-bundle_schemas-status'
          type: object
