openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_identifier}/custom_pages:
    get:
      description: Fetches all the custom pages at the zone level.
      operationId: custom-pages-for-a-zone-list-custom-pages
      parameters:
        - in: path
          name: zone_identifier
          required: true
          schema:
            $ref: '#/components/schemas/custom-pages_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/custom-pages_custom_page_result_list'
          description: List custom pages response
        4xx:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/custom-pages_custom_page_result_list'
                  - $ref: >-
                      #/components/schemas/custom-pages_api-response-common-failure
          description: List custom pages response failure
      security:
        - api_email: []
          api_key: []
      summary: List custom pages
      tags:
        - Custom pages for a zone
      x-api-token-group:
        - Custom Pages Write
        - Custom Pages Read
        - Zone Settings Write
        - Zone Settings Read
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: true
  /zones/{zone_identifier}/custom_pages/{identifier}:
    get:
      description: Fetches the details of a custom page.
      operationId: custom-pages-for-a-zone-get-a-custom-page
      parameters:
        - in: path
          name: identifier
          required: true
          schema:
            $ref: '#/components/schemas/custom-pages_error_page_type'
        - in: path
          name: zone_identifier
          required: true
          schema:
            $ref: '#/components/schemas/custom-pages_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/custom-pages_custom_page'
          description: Get a custom page response
        4xx:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/custom-pages_custom_page_result'
                  - $ref: >-
                      #/components/schemas/custom-pages_api-response-common-failure
          description: Get a custom page response failure
      security:
        - api_email: []
          api_key: []
      summary: Get a custom page
      tags:
        - Custom pages for a zone
      x-api-token-group:
        - Custom Pages Write
        - Custom Pages Read
        - Zone Settings Write
        - Zone Settings Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: true
    put:
      description: Updates the configuration of an existing custom page.
      operationId: custom-pages-for-a-zone-update-a-custom-page
      parameters:
        - in: path
          name: identifier
          required: true
          schema:
            $ref: '#/components/schemas/custom-pages_error_page_type'
        - in: path
          name: zone_identifier
          required: true
          schema:
            $ref: '#/components/schemas/custom-pages_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                state:
                  $ref: '#/components/schemas/custom-pages_state'
                url:
                  $ref: '#/components/schemas/custom-pages_url'
              required:
                - url
                - state
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/custom-pages_custom_page_result'
          description: Update a custom page response
        4xx:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/custom-pages_custom_page_result'
                  - $ref: >-
                      #/components/schemas/custom-pages_api-response-common-failure
          description: Update a custom page response failure
      security:
        - api_email: []
          api_key: []
      summary: Update a custom page
      tags:
        - Custom pages for a zone
      x-api-token-group:
        - Custom Pages Write
        - Zone Settings Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: true
components:
  schemas:
    custom-pages_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/custom-pages_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/custom-pages_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    custom-pages_custom_page:
      properties:
        created_on:
          $ref: '#/components/schemas/custom-pages_timestamp'
        description:
          example: Basic Challenge
          type: string
          x-auditable: true
        id:
          example: basic_challenge
          type: string
          x-auditable: true
        modified_on:
          $ref: '#/components/schemas/custom-pages_timestamp'
        preview_target:
          example: block:basic-sec-captcha
          type: string
          x-auditable: true
        required_tokens:
          example:
            - '::CAPTCHA_BOX::'
          items:
            type: string
          type: array
          x-auditable: true
        state:
          $ref: '#/components/schemas/custom-pages_state'
        url:
          $ref: '#/components/schemas/custom-pages_url'
      type: object
    custom-pages_custom_page_result:
      allOf:
        - $ref: '#/components/schemas/custom-pages_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/custom-pages_custom_page'
    custom-pages_custom_page_result_list:
      allOf:
        - $ref: '#/components/schemas/custom-pages_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/custom-pages_custom_page'
              type: array
    custom-pages_error_page_type:
      description: Error Page Types
      enum:
        - waf_block
        - ip_block
        - country_challenge
        - 500_errors
        - 1000_errors
        - managed_challenge
        - ratelimit_block
      example: ratelimit_block
      type: string
      x-auditable: true
    custom-pages_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
    custom-pages_state:
      description: The custom page state.
      enum:
        - default
        - customized
      example: default
      type: string
      x-auditable: true
    custom-pages_url:
      default: ''
      description: The URL associated with the custom page.
      example: http://www.example.com
      format: uri
      type: string
      x-auditable: true
