openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/dex/devices/dex_tests:
    get:
      description: Fetch all DEX tests
      operationId: device-dex-test-details
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: >-
              #/components/schemas/digital-experience-monitoring_account_identifier
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/digital-experience-monitoring_dex-response_collection
          description: Device DEX test details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/digital-experience-monitoring_dex-single_response
                  - $ref: >-
                      #/components/schemas/digital-experience-monitoring_api-response-common-failure
          description: Device DEX test response failure
      security:
        - api_email: []
          api_key: []
      summary: List Device DEX tests
      tags:
        - Device DEX Tests
      x-api-token-group:
        - Cloudflare DEX Write
        - Cloudflare DEX Read
        - Zero Trust Report
        - Zero Trust Read
    post:
      description: Create a DEX test.
      operationId: device-dex-test-create-device-dex-test
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: >-
              #/components/schemas/digital-experience-monitoring_account_identifier
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/digital-experience-monitoring_device-dex-test-schemas-http
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/digital-experience-monitoring_dex-single_response
          description: Update Dex test response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/digital-experience-monitoring_dex-single_response
                  - $ref: >-
                      #/components/schemas/digital-experience-monitoring_api-response-common-failure
          description: Update Dex test response failure
      security:
        - api_email: []
          api_key: []
      summary: Create Device DEX test
      tags:
        - Device DEX Tests
      x-api-token-group:
        - Cloudflare DEX Write
  /accounts/{account_id}/dex/devices/dex_tests/{dex_test_id}:
    get:
      description: Fetch a single DEX test.
      operationId: device-dex-test-get-device-dex-test
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: >-
              #/components/schemas/digital-experience-monitoring_account_identifier
        - in: path
          name: dex_test_id
          required: true
          schema:
            $ref: '#/components/schemas/digital-experience-monitoring_schemas-test-id'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/digital-experience-monitoring_dex-single_response
          description: Device DEX test details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/digital-experience-monitoring_dex-single_response
                  - $ref: >-
                      #/components/schemas/digital-experience-monitoring_api-response-common-failure
          description: Device DEX test response failure
      security:
        - api_email: []
          api_key: []
      summary: Get Device DEX test
      tags:
        - Device DEX Tests
      x-api-token-group:
        - Cloudflare DEX Write
        - Cloudflare DEX Read
        - Zero Trust Report
        - Zero Trust Read
    put:
      description: Update a DEX test.
      operationId: device-dex-test-update-device-dex-test
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: >-
              #/components/schemas/digital-experience-monitoring_account_identifier
        - in: path
          name: dex_test_id
          required: true
          schema:
            $ref: '#/components/schemas/digital-experience-monitoring_uuid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/digital-experience-monitoring_device-dex-test-schemas-http
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/digital-experience-monitoring_dex-single_response
          description: Update Dex test response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/digital-experience-monitoring_dex-single_response
                  - $ref: >-
                      #/components/schemas/digital-experience-monitoring_api-response-common-failure
          description: Update Dex test response failure
      security:
        - api_email: []
          api_key: []
      summary: Update Device DEX test
      tags:
        - Device DEX Tests
      x-api-token-group:
        - Cloudflare DEX Write
    delete:
      description: >-
        Delete a Device DEX test. Returns the remaining device dex tests for the
        account.
      operationId: device-dex-test-delete-device-dex-test
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: >-
              #/components/schemas/digital-experience-monitoring_account_identifier
        - in: path
          name: dex_test_id
          required: true
          schema:
            $ref: '#/components/schemas/digital-experience-monitoring_uuid'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/digital-experience-monitoring_dex-delete-response-collection
          description: Delete Device DEX test response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/digital-experience-monitoring_dex-response_collection
                  - $ref: >-
                      #/components/schemas/digital-experience-monitoring_api-response-common-failure
          description: Delete DEX test response failure
      security:
        - api_email: []
          api_key: []
      summary: Delete Device DEX test
      tags:
        - Device DEX Tests
      x-api-token-group:
        - Cloudflare DEX Write
components:
  schemas:
    digital-experience-monitoring_account_identifier:
      example: 01a7362d577a6c3019a474fd6f485823
      maxLength: 32
      readOnly: true
      type: string
    digital-experience-monitoring_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/digital-experience-monitoring_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/digital-experience-monitoring_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    digital-experience-monitoring_device-dex-test-schemas-http:
      properties:
        data:
          $ref: >-
            #/components/schemas/digital-experience-monitoring_device-dex-test-schemas-data
        description:
          $ref: >-
            #/components/schemas/digital-experience-monitoring_device-dex-test-schemas-description
        enabled:
          $ref: >-
            #/components/schemas/digital-experience-monitoring_device-dex-test-schemas-enabled
        interval:
          $ref: >-
            #/components/schemas/digital-experience-monitoring_device-dex-test-schemas-interval
        name:
          $ref: >-
            #/components/schemas/digital-experience-monitoring_device-dex-test-schemas-name
        target_policies:
          $ref: >-
            #/components/schemas/digital-experience-monitoring_device-dex-test-target-policies
        targeted:
          type: boolean
        test_id:
          $ref: '#/components/schemas/digital-experience-monitoring_schemas-test-id'
      required:
        - name
        - interval
        - enabled
        - data
      type: object
    digital-experience-monitoring_dex-delete-response-collection:
      allOf:
        - $ref: >-
            #/components/schemas/digital-experience-monitoring_api-response-common
        - properties:
            result:
              properties:
                dex_tests:
                  items:
                    $ref: >-
                      #/components/schemas/digital-experience-monitoring_device-dex-test-schemas-http
                  type: array
              type: object
    digital-experience-monitoring_dex-response_collection:
      allOf:
        - $ref: >-
            #/components/schemas/digital-experience-monitoring_api-response-collection-common
        - properties:
            result:
              items:
                $ref: >-
                  #/components/schemas/digital-experience-monitoring_device-dex-test-schemas-http
              type: array
    digital-experience-monitoring_dex-single_response:
      allOf:
        - $ref: >-
            #/components/schemas/digital-experience-monitoring_api-response-single
        - properties:
            result:
              $ref: >-
                #/components/schemas/digital-experience-monitoring_device-dex-test-schemas-http
    digital-experience-monitoring_schemas-test-id:
      description: The unique identifier for the test.
      example: 372e67954025e0ba6aaa6d586b9e0b59
      maxLength: 32
      readOnly: true
      type: string
    digital-experience-monitoring_uuid:
      description: API Resource UUID tag.
      example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      maxLength: 36
      type: string
