openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/devices/posture:
    get:
      description: Fetches device posture rules for a Zero Trust account.
      operationId: device-posture-rules-list-device-posture-rules
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/teams-devices_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/teams-devices_response_collection'
          description: List device posture rules response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/teams-devices_response_collection'
                  - $ref: >-
                      #/components/schemas/teams-devices_api-response-common-failure
          description: List device posture rules response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List device posture rules
      tags:
        - Device posture rules
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
    post:
      description: Creates a new device posture rule.
      operationId: device-posture-rules-create-device-posture-rule
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/teams-devices_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                description:
                  $ref: '#/components/schemas/teams-devices_description'
                expiration:
                  $ref: '#/components/schemas/teams-devices_expiration'
                input:
                  $ref: '#/components/schemas/teams-devices_input'
                match:
                  $ref: '#/components/schemas/teams-devices_match'
                name:
                  $ref: '#/components/schemas/teams-devices_name'
                schedule:
                  $ref: '#/components/schemas/teams-devices_schedule'
                type:
                  $ref: '#/components/schemas/teams-devices_type'
              required:
                - name
                - type
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/teams-devices_single_response'
          description: Create device posture rule response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/teams-devices_single_response'
                  - $ref: >-
                      #/components/schemas/teams-devices_api-response-common-failure
          description: Create device posture rule response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create a device posture rule
      tags:
        - Device posture rules
      x-api-token-group:
        - Zero Trust Write
  /accounts/{account_id}/devices/posture/{rule_id}:
    get:
      description: Fetches a single device posture rule.
      operationId: device-posture-rules-device-posture-rules-details
      parameters:
        - in: path
          name: rule_id
          required: true
          schema:
            $ref: '#/components/schemas/teams-devices_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/teams-devices_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/teams-devices_single_response'
          description: Get device posture rule details response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/teams-devices_single_response'
                  - $ref: >-
                      #/components/schemas/teams-devices_api-response-common-failure
          description: Get device posture rule details response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get device posture rule details
      tags:
        - Device posture rules
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
    put:
      description: Updates a device posture rule.
      operationId: device-posture-rules-update-device-posture-rule
      parameters:
        - in: path
          name: rule_id
          required: true
          schema:
            $ref: '#/components/schemas/teams-devices_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/teams-devices_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                description:
                  $ref: '#/components/schemas/teams-devices_description'
                expiration:
                  $ref: '#/components/schemas/teams-devices_expiration'
                input:
                  $ref: '#/components/schemas/teams-devices_input'
                match:
                  $ref: '#/components/schemas/teams-devices_match'
                name:
                  $ref: '#/components/schemas/teams-devices_name'
                schedule:
                  $ref: '#/components/schemas/teams-devices_schedule'
                type:
                  $ref: '#/components/schemas/teams-devices_type'
              required:
                - name
                - type
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/teams-devices_single_response'
          description: Update a device posture rule response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/teams-devices_single_response'
                  - $ref: >-
                      #/components/schemas/teams-devices_api-response-common-failure
          description: Update a device posture rule response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update a device posture rule
      tags:
        - Device posture rules
      x-api-token-group:
        - Zero Trust Write
    delete:
      description: Deletes a device posture rule.
      operationId: device-posture-rules-delete-device-posture-rule
      parameters:
        - in: path
          name: rule_id
          required: true
          schema:
            $ref: '#/components/schemas/teams-devices_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/teams-devices_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/teams-devices_id_response'
          description: Delete a device posture rule response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/teams-devices_id_response'
                  - $ref: >-
                      #/components/schemas/teams-devices_api-response-common-failure
          description: Delete a device posture rule response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete a device posture rule
      tags:
        - Device posture rules
      x-api-token-group:
        - Zero Trust Write
components:
  schemas:
    teams-devices_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/teams-devices_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/teams-devices_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    teams-devices_description:
      default: ''
      description: The description of the device posture rule.
      example: The rule for admin serial numbers
      type: string
      x-auditable: true
    teams-devices_expiration:
      description: >-
        Sets the expiration time for a posture check result. If empty, the
        result remains valid until it is overwritten by new data from the WARP
        client.
      example: 1h
      type: string
    teams-devices_id_response:
      allOf:
        - $ref: '#/components/schemas/teams-devices_api-response-single'
        - properties:
            result:
              properties:
                id:
                  $ref: '#/components/schemas/teams-devices_uuid'
              type: object
          type: object
    teams-devices_identifier:
      example: 699d98642c564d2e855e9661899b7252
    teams-devices_input:
      description: The value to be checked against.
      example:
        operating_system: linux
        path: /bin/cat
        thumbprint: 0aabab210bdb998e9cf45da2c9ce352977ab531c681b74cf1e487be1bbe9fe6e
      oneOf:
        - $ref: '#/components/schemas/teams-devices_file_input_request'
        - $ref: '#/components/schemas/teams-devices_unique_client_id_input_request'
        - $ref: '#/components/schemas/teams-devices_domain_joined_input_request'
        - $ref: '#/components/schemas/teams-devices_os_version_input_request'
        - $ref: '#/components/schemas/teams-devices_firewall_input_request'
        - $ref: '#/components/schemas/teams-devices_sentinelone_input_request'
        - $ref: '#/components/schemas/teams-devices_carbonblack_input_request'
        - $ref: >-
            #/components/schemas/teams-devices_access_serial_number_list_input_request
        - $ref: '#/components/schemas/teams-devices_disk_encryption_input_request'
        - $ref: '#/components/schemas/teams-devices_application_input_request'
        - $ref: '#/components/schemas/teams-devices_client_certificate_input_request'
        - $ref: >-
            #/components/schemas/teams-devices_client_certificate_v2_input_request
        - $ref: '#/components/schemas/teams-devices_workspace_one_input_request'
        - $ref: '#/components/schemas/teams-devices_crowdstrike_input_request'
        - $ref: '#/components/schemas/teams-devices_intune_input_request'
        - $ref: '#/components/schemas/teams-devices_kolide_input_request'
        - $ref: '#/components/schemas/teams-devices_tanium_input_request'
        - $ref: '#/components/schemas/teams-devices_sentinelone_s2s_input_request'
        - $ref: '#/components/schemas/teams-devices_custom_s2s_input_request'
      type: object
    teams-devices_match:
      description: The conditions that the client must match to run the rule.
      items:
        $ref: '#/components/schemas/teams-devices_match_item'
      type: array
    teams-devices_name:
      description: The name of the device posture rule.
      example: Admin Serial Numbers
      type: string
      x-auditable: true
    teams-devices_response_collection:
      allOf:
        - $ref: '#/components/schemas/teams-devices_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/teams-devices_device-posture-rules'
              type: array
          type: object
    teams-devices_schedule:
      description: >-
        Polling frequency for the WARP client posture check. Default: `5m` (poll
        every five minutes). Minimum: `1m`.
      example: 1h
      type: string
      x-auditable: true
    teams-devices_single_response:
      allOf:
        - $ref: '#/components/schemas/teams-devices_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/teams-devices_device-posture-rules'
          type: object
    teams-devices_type:
      description: The type of device posture rule.
      enum:
        - file
        - application
        - tanium
        - gateway
        - warp
        - disk_encryption
        - serial_number
        - sentinelone
        - carbonblack
        - firewall
        - os_version
        - domain_joined
        - client_certificate
        - client_certificate_v2
        - unique_client_id
        - kolide
        - tanium_s2s
        - crowdstrike_s2s
        - intune
        - workspace_one
        - sentinelone_s2s
        - custom_s2s
      example: file
      type: string
      x-auditable: true
    teams-devices_uuid:
      description: API UUID.
      example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      maxLength: 36
      type: string
      x-auditable: true
