openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/devices/networks:
    get:
      description: Fetches a list of managed networks for an account.
      operationId: device-managed-networks-list-device-managed-networks
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/teams-devices_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/teams-devices_components-schemas-response_collection
          description: List your device managed networks response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/teams-devices_components-schemas-response_collection
                  - $ref: >-
                      #/components/schemas/teams-devices_api-response-common-failure
          description: List your device managed networks response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List your device managed networks
      tags:
        - Device Managed Networks
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
    post:
      description: Creates a new device managed network.
      operationId: device-managed-networks-create-device-managed-network
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/teams-devices_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                config:
                  $ref: '#/components/schemas/teams-devices_schemas-config_request'
                name:
                  $ref: >-
                    #/components/schemas/teams-devices_device-managed-networks_components-schemas-name
                type:
                  $ref: '#/components/schemas/teams-devices_components-schemas-type'
              required:
                - name
                - type
                - config
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/teams-devices_components-schemas-single_response
          description: Create a device managed networks response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/teams-devices_components-schemas-single_response
                  - $ref: >-
                      #/components/schemas/teams-devices_api-response-common-failure
          description: Create a device managed networks response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create a device managed network
      tags:
        - Device Managed Networks
      x-api-token-group:
        - Zero Trust Write
  /accounts/{account_id}/devices/networks/{network_id}:
    get:
      description: Fetches details for a single managed network.
      operationId: device-managed-networks-device-managed-network-details
      parameters:
        - in: path
          name: network_id
          required: true
          schema:
            $ref: '#/components/schemas/teams-devices_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/teams-devices_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/teams-devices_components-schemas-single_response
          description: Get device managed network details response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/teams-devices_components-schemas-single_response
                  - $ref: >-
                      #/components/schemas/teams-devices_api-response-common-failure
          description: Get device managed network details response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get device managed network details
      tags:
        - Device Managed Networks
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
    put:
      description: Updates a configured device managed network.
      operationId: device-managed-networks-update-device-managed-network
      parameters:
        - in: path
          name: network_id
          required: true
          schema:
            $ref: '#/components/schemas/teams-devices_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/teams-devices_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                config:
                  $ref: '#/components/schemas/teams-devices_schemas-config_request'
                name:
                  $ref: >-
                    #/components/schemas/teams-devices_device-managed-networks_components-schemas-name
                type:
                  $ref: '#/components/schemas/teams-devices_components-schemas-type'
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/teams-devices_components-schemas-single_response
          description: Update a device managed network response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/teams-devices_components-schemas-single_response
                  - $ref: >-
                      #/components/schemas/teams-devices_api-response-common-failure
          description: Update a device managed network response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update a device managed network
      tags:
        - Device Managed Networks
      x-api-token-group:
        - Zero Trust Write
    delete:
      description: >-
        Deletes a device managed network and fetches a list of the remaining
        device managed networks for an account.
      operationId: device-managed-networks-delete-device-managed-network
      parameters:
        - in: path
          name: network_id
          required: true
          schema:
            $ref: '#/components/schemas/teams-devices_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/teams-devices_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/teams-devices_components-schemas-response_collection
          description: Delete a device managed network response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/teams-devices_components-schemas-response_collection
                  - $ref: >-
                      #/components/schemas/teams-devices_api-response-common-failure
          description: Delete a device managed network response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete a device managed network
      tags:
        - Device Managed Networks
      x-api-token-group:
        - Zero Trust Write
components:
  schemas:
    teams-devices_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/teams-devices_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/teams-devices_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    teams-devices_components-schemas-response_collection:
      allOf:
        - $ref: '#/components/schemas/teams-devices_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/teams-devices_device-managed-networks'
              type: array
          type: object
    teams-devices_components-schemas-single_response:
      allOf:
        - $ref: '#/components/schemas/teams-devices_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/teams-devices_device-managed-networks'
          type: object
    teams-devices_components-schemas-type:
      description: The type of device managed network.
      enum:
        - tls
      example: tls
      type: string
      x-auditable: true
    teams-devices_device-managed-networks_components-schemas-name:
      description: The name of the device managed network. This name must be unique.
      example: managed-network-1
      type: string
      x-auditable: true
    teams-devices_identifier:
      example: 699d98642c564d2e855e9661899b7252
    teams-devices_schemas-config_request:
      description: >-
        The configuration object containing information for the WARP client to
        detect the managed network.
      example:
        sha256: b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
        tls_sockaddr: foo.bar:1234
      oneOf:
        - $ref: '#/components/schemas/teams-devices_tls_config_request'
      type: object
    teams-devices_uuid:
      description: API UUID.
      example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      maxLength: 36
      type: string
      x-auditable: true
