openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/dlp/document_fingerprints:
    get:
      operationId: dlp-document-fingerprints-read-all
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_DocumentFingerprintArray'
                    type: object
          description: Document fingerprint read was successful.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Document fingerprint read failed.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Retrieve data about all document fingerprints.
      tags:
        - DLP Document Fingerprints
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
    post:
      operationId: dlp-document-fingerprints-create
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dlp_NewDocumentFingerprint'
        description: Attributes of the new document fingerprint.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_DocumentFingerprint'
                    type: object
          description: Document fingerprint created successfully.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Document fingerprint creation failed.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Creates a new document fingerprint.
      tags:
        - DLP Document Fingerprints
      x-api-token-group:
        - Zero Trust Write
  /accounts/{account_id}/dlp/document_fingerprints/{document_fingerprint_id}:
    get:
      operationId: dlp-document-fingerprints-read
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
        - in: path
          name: document_fingerprint_id
          required: true
          schema:
            format: uuid
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_DocumentFingerprint'
                    type: object
          description: Document fingerprint read was successful.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Document fingerprint read failed.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Retrieve data about a specific document fingerprint.
      tags:
        - DLP Document Fingerprints
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
    post:
      operationId: dlp-document-fingerprints-update
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
        - in: path
          name: document_fingerprint_id
          required: true
          schema:
            format: uuid
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dlp_UpdateDocumentFingerprint'
        description: Attributes of the document fingerprint to update.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_DocumentFingerprint'
                    type: object
          description: Document fingerprint read was successful.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Document fingerprint read failed.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update the attributes of a single document fingerprint.
      tags:
        - DLP Document Fingerprints
      x-api-token-group:
        - Zero Trust Write
    put:
      operationId: dlp-document-fingerprints-upload
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
        - in: path
          name: document_fingerprint_id
          required: true
          schema:
            format: uuid
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  format: binary
                  type: string
              required:
                - file
              type: object
        description: File used for document fingerprinting.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_DocumentFingerprintUpload'
                    type: object
          description: File uploaded successfully.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Failed to upload file.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Uploads a new version for a document fingerprint.
      tags:
        - DLP Document Fingerprints
      x-api-token-group:
        - Zero Trust Write
    delete:
      operationId: dlp-document-fingerprints-delete
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
        - in: path
          name: document_fingerprint_id
          required: true
          schema:
            format: uuid
            type: string
      responses:
        '200':
          description: Document fingerprint delete was successful.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Document fingerprint delete failed.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete a single document fingerprint.
      tags:
        - DLP Document Fingerprints
      x-api-token-group:
        - Zero Trust Write
components:
  schemas:
    dlp_DocumentFingerprint:
      properties:
        created_at:
          format: date-time
          type: string
        description:
          default: ''
          type: string
        entry_id:
          format: uuid
          type: string
        file_name:
          nullable: true
          type: string
        id:
          format: uuid
          type: string
        match_percent:
          format: int32
          type: integer
        name:
          type: string
        status:
          $ref: '#/components/schemas/dlp_DatasetUploadStatus'
        updated_at:
          format: date-time
          type: string
        version:
          format: int64
          nullable: true
          type: integer
      required:
        - id
        - entry_id
        - name
        - description
        - match_percent
        - status
        - created_at
        - updated_at
      type: object
    dlp_DocumentFingerprintArray:
      items:
        $ref: '#/components/schemas/dlp_DocumentFingerprint'
      type: array
    dlp_DocumentFingerprintUpload:
      properties:
        created_at:
          format: date-time
          type: string
        description:
          type: string
        entry_id:
          format: uuid
          type: string
        file_name:
          type: string
        id:
          format: uuid
          type: string
        match_percent:
          format: int32
          type: integer
        name:
          type: string
        status:
          $ref: '#/components/schemas/dlp_DatasetUploadStatus'
        updated_at:
          format: date-time
          type: string
        version:
          format: int64
          type: integer
      required:
        - id
        - entry_id
        - name
        - description
        - match_percent
        - version
        - file_name
        - status
        - created_at
        - updated_at
      type: object
    dlp_NewDocumentFingerprint:
      properties:
        description:
          default: ''
          type: string
        match_percent:
          format: int32
          type: integer
        name:
          type: string
      required:
        - name
        - match_percent
      type: object
    dlp_UpdateDocumentFingerprint:
      properties:
        description:
          nullable: true
          type: string
        match_percent:
          format: int32
          nullable: true
          type: integer
        name:
          nullable: true
          type: string
      type: object
    dlp_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/dlp_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/dlp_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    dlp_api-response-single:
      allOf:
        - $ref: '#/components/schemas/dlp_api-response-common'
      type: object
