openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/dlp/email/account_mapping:
    get:
      operationId: dlp-email-scanner-get-account-mapping
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_AddinAccountMapping'
                    type: object
          description: Get Email Scanner Account Mapping response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Get Email Scanner Account Mapping failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get mapping
      tags:
        - DLP Email
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
    post:
      operationId: dlp-email-scanner-create-account-mapping
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dlp_UpdateAddinAccountMapping'
        description: Account mapping.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_AddinAccountMapping'
                    type: object
          description: New Email Scanner Account Mapping response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: New Email Scanner Account Mapping failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create mapping
      tags:
        - DLP Email
      x-api-token-group:
        - Zero Trust Write
  /accounts/{account_id}/dlp/email/rules:
    get:
      description: Lists all email scanner rules for an account.
      operationId: dlp-email-scanner-list-all-rules
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_EmailRuleArray'
                    type: object
          description: List all email scanner rules response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: List all email scanner rules failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List all email scanner rules
      tags:
        - DLP Email
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
    post:
      operationId: dlp-email-scanner-create-rule
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dlp_CreateEmailRule'
        description: Rule description.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_EmailRule'
                    type: object
          description: New Email Scanner Rule response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: New Email Scanner Rule failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create email scanner rule
      tags:
        - DLP Email
      x-api-token-group:
        - Zero Trust Write
    patch:
      operationId: dlp-email-scanner-update-rule-priorities
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dlp_UpdateEmailRulePriorities'
        description: Rule priorities.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_EmailRule'
                    type: object
          description: Update Email Scanner Rule priorities response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Update Email Scanner Rule priorities failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update email scanner rule priorities
      tags:
        - DLP Email
      x-api-token-group:
        - Zero Trust Write
  /accounts/{account_id}/dlp/email/rules/{rule_id}:
    get:
      operationId: dlp-email-scanner-get-rule
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
        - in: path
          name: rule_id
          required: true
          schema:
            format: uuid
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_EmailRule'
                    type: object
          description: Get Email Scanner Rule response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Get Email Scanner Rule failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get an email scanner rule
      tags:
        - DLP Email
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
    put:
      operationId: dlp-email-scanner-update-rule
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
        - in: path
          name: rule_id
          required: true
          schema:
            format: uuid
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dlp_CreateEmailRule'
        description: Rule description.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_EmailRule'
                    type: object
          description: Update Email Scanner Rule response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Update Email Scanner Rule failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update email scanner rule
      tags:
        - DLP Email
      x-api-token-group:
        - Zero Trust Write
    delete:
      operationId: dlp-email-scanner-delete-rule
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
        - in: path
          name: rule_id
          required: true
          schema:
            format: uuid
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_EmailRule'
                    type: object
          description: Delete Email Scanner Rule response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Delete Email Scanner Rule failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete email scanner rule
      tags:
        - DLP Email
      x-api-token-group:
        - Zero Trust Write
components:
  schemas:
    dlp_AddinAccountMapping:
      properties:
        addin_identifier_token:
          format: uuid
          type: string
        auth_requirements:
          $ref: '#/components/schemas/dlp_AddinAuth'
      required:
        - auth_requirements
        - addin_identifier_token
      type: object
    dlp_CreateEmailRule:
      properties:
        action:
          $ref: '#/components/schemas/dlp_EmailRuleAction'
        conditions:
          description: Rule is triggered if all conditions match.
          items:
            $ref: '#/components/schemas/dlp_EmailRuleCondition'
          type: array
        description:
          nullable: true
          type: string
        enabled:
          type: boolean
        name:
          type: string
      required:
        - name
        - enabled
        - conditions
        - action
      type: object
    dlp_EmailRule:
      properties:
        action:
          $ref: '#/components/schemas/dlp_EmailRuleAction'
        conditions:
          description: Rule is triggered if all conditions match.
          items:
            $ref: '#/components/schemas/dlp_EmailRuleCondition'
          type: array
        created_at:
          format: date-time
          type: string
        description:
          nullable: true
          type: string
        enabled:
          type: boolean
        name:
          type: string
        priority:
          format: int32
          minimum: 0
          type: integer
        rule_id:
          format: uuid
          type: string
        updated_at:
          format: date-time
          type: string
      required:
        - rule_id
        - name
        - priority
        - enabled
        - conditions
        - action
        - created_at
        - updated_at
      type: object
    dlp_EmailRuleArray:
      items:
        $ref: '#/components/schemas/dlp_EmailRule'
      type: array
    dlp_UpdateAddinAccountMapping:
      properties:
        auth_requirements:
          $ref: '#/components/schemas/dlp_AddinAuth'
      required:
        - auth_requirements
      type: object
    dlp_UpdateEmailRulePriorities:
      description: |-
        Used to update multiple email rule priorities as an atomic action,
        to support patterns such as swapping the priorities of two email rules.
      properties:
        new_priorities:
          additionalProperties:
            format: int32
            minimum: 0
            type: integer
          type: object
      required:
        - new_priorities
      type: object
    dlp_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/dlp_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/dlp_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    dlp_api-response-single:
      allOf:
        - $ref: '#/components/schemas/dlp_api-response-common'
      type: object
