openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/addressing/regional_hostnames/regions:
    get:
      description: List all Regional Services regions available for use by this account.
      operationId: dls-account-regional-hostnames-account-list-regions
      parameters:
        - $ref: '#/components/parameters/dls_account_id'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dls_api-response-collection'
                  - properties:
                      result:
                        items:
                          properties:
                            key:
                              $ref: '#/components/schemas/dls_region_key'
                            label:
                              description: Human-readable text label for the region
                              example: Canada
                              type: string
                          type: object
                        type: array
          description: List regions response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dls_api-response-common-failure'
          description: Failure to list regions
      security:
        - api_email: []
          api_key: []
        - api_token: []
      summary: List Regions
      tags:
        - DLS Regional Services
      x-api-token-group:
        - DNS Read
        - DNS Write
  /zones/{zone_id}/addressing/regional_hostnames:
    get:
      description: List all Regional Hostnames within a zone.
      operationId: dls-account-regional-hostnames-account-list-hostnames
      parameters:
        - $ref: '#/components/parameters/dls_zone_id'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dls_api-response-collection'
                  - properties:
                      result:
                        items:
                          $ref: '#/components/schemas/dls_regional_hostname_response'
                        type: array
          description: List hostnames response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dls_api-response-common-failure'
          description: Failure to list hostnames
      security:
        - api_email: []
          api_key: []
        - api_token: []
      summary: List Regional Hostnames
      tags:
        - DLS Regional Services
      x-api-token-group:
        - DNS Read
        - DNS Write
    post:
      description: >-
        Create a new Regional Hostname entry. Cloudflare will only use data
        centers that are physically located within the chosen region to decrypt
        and service HTTPS traffic. Learn more about [Regional
        Services](https://developers.cloudflare.com/data-localization/regional-services/get-started/).
      operationId: dls-account-regional-hostnames-account-create-hostname
      parameters:
        - $ref: '#/components/parameters/dls_zone_id'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                hostname:
                  $ref: '#/components/schemas/dls_hostname'
                region_key:
                  $ref: '#/components/schemas/dls_region_key'
                routing:
                  $ref: '#/components/schemas/dls_routing'
              required:
                - hostname
                - region_key
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dls_api-response-common'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dls_regional_hostname_response'
                    type: object
          description: Create hostname response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dls_api-response-common-failure'
          description: Failure to create hostname
      security:
        - api_email: []
          api_key: []
        - api_token: []
      summary: Create Regional Hostname
      tags:
        - DLS Regional Services
      x-api-token-group:
        - DNS Write
  /zones/{zone_id}/addressing/regional_hostnames/{hostname}:
    get:
      description: Fetch the configuration for a specific Regional Hostname, within a zone.
      operationId: dls-account-regional-hostnames-account-fetch-hostname
      parameters:
        - $ref: '#/components/parameters/dls_zone_id'
        - $ref: '#/components/parameters/dls_hostname'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: '#/components/schemas/dls_api-response-common'
                    type: object
                  - properties:
                      result:
                        $ref: '#/components/schemas/dls_regional_hostname_response'
                    type: object
          description: Fetch hostname response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dls_api-response-common-failure'
          description: Failure to fetch hostname
      security:
        - api_email: []
          api_key: []
        - api_token: []
      summary: Fetch Regional Hostname
      tags:
        - DLS Regional Services
      x-api-token-group:
        - DNS Read
        - DNS Write
    patch:
      description: >-
        Update the configuration for a specific Regional Hostname. Only the
        region_key of a hostname is mutable.
      operationId: dls-account-regional-hostnames-account-patch-hostname
      parameters:
        - $ref: '#/components/parameters/dls_zone_id'
        - $ref: '#/components/parameters/dls_hostname'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                region_key:
                  $ref: '#/components/schemas/dls_region_key'
              required:
                - region_key
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dls_api-response-common'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dls_regional_hostname_response'
                    type: object
          description: Update hostname response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dls_api-response-common-failure'
          description: Failure to update hostname
      security:
        - api_email: []
          api_key: []
        - api_token: []
      summary: Update Regional Hostname
      tags:
        - DLS Regional Services
      x-api-token-group:
        - DNS Write
    delete:
      description: Delete the region configuration for a specific Regional Hostname.
      operationId: dls-account-regional-hostnames-account-delete-hostname
      parameters:
        - $ref: '#/components/parameters/dls_zone_id'
        - $ref: '#/components/parameters/dls_hostname'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dls_api-response-common'
          description: Delete hostname response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dls_api-response-common-failure'
          description: Failure to delete hostname
      security:
        - api_email: []
          api_key: []
        - api_token: []
      summary: Delete Regional Hostname
      tags:
        - DLS Regional Services
      x-api-token-group:
        - DNS Write
components:
  schemas:
    dls_api-response-collection:
      allOf:
        - $ref: '#/components/schemas/dls_api-response-common'
        - properties:
            result_info:
              $ref: '#/components/schemas/dls_result_info'
      type: object
    dls_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/dls_messages'
        messages:
          $ref: '#/components/schemas/dls_messages'
        success:
          description: Whether the API call was successful.
          enum:
            - true
          example: true
          type: boolean
      required:
        - success
        - errors
        - messages
      type: object
    dls_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/dls_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/dls_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    dls_hostname:
      description: >-
        DNS hostname to be regionalized, must be a subdomain of the zone.
        Wildcards are supported for one level, e.g `*.example.com`
      example: foo.example.com
      type: string
    dls_region_key:
      description: Identifying key for the region
      example: ca
      type: string
    dls_regional_hostname_response:
      properties:
        created_on:
          allOf:
            - $ref: '#/components/schemas/dls_timestamp'
            - description: When the regional hostname was created
            - example: '2014-01-01T05:20:00.12345Z'
        hostname:
          $ref: '#/components/schemas/dls_hostname'
        region_key:
          $ref: '#/components/schemas/dls_region_key'
        routing:
          $ref: '#/components/schemas/dls_routing'
      required:
        - hostname
        - region_key
        - created_on
      type: object
    dls_routing:
      description: Configure which routing method to use for the regional hostname
      type: string
  parameters:
    dls_account_id:
      in: path
      name: account_id
      required: true
      schema:
        $ref: '#/components/schemas/dls_identifier'
    dls_hostname:
      in: path
      name: hostname
      required: true
      schema:
        $ref: '#/components/schemas/dls_hostname'
    dls_zone_id:
      in: path
      name: zone_id
      required: true
      schema:
        $ref: '#/components/schemas/dls_identifier'
