openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/dns_firewall:
    get:
      description: List DNS Firewall clusters for an account
      operationId: dns-firewall-list-dns-firewall-clusters
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-firewall_identifier'
        - in: query
          name: page
          schema:
            default: 1
            description: Page number of paginated results
            minimum: 1
            type: number
        - in: query
          name: per_page
          schema:
            default: 20
            description: Number of clusters per page
            maximum: 100
            minimum: 1
            type: number
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/dns-firewall_dns_firewall_response_collection
          description: List DNS Firewall Clusters response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/dns-firewall_dns_firewall_response_collection
                  - $ref: >-
                      #/components/schemas/dns-firewall_api-response-common-failure
          description: List DNS Firewall Clusters response failure
      security:
        - api_email: []
          api_key: []
      summary: List DNS Firewall Clusters
      tags:
        - DNS Firewall
      x-api-token-group:
        - DNS Firewall Write
        - DNS Firewall Read
      x-cfPermissionsRequired:
        enum:
          - '#dns_records:read'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    post:
      description: Create a DNS Firewall cluster
      operationId: dns-firewall-create-dns-firewall-cluster
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-firewall_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dns-firewall_dns-firewall-cluster-post'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dns-firewall_dns_firewall_single_response'
          description: Create DNS Firewall Cluster response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/dns-firewall_dns_firewall_single_response
                  - $ref: >-
                      #/components/schemas/dns-firewall_api-response-common-failure
          description: Create DNS Firewall Cluster response failure
      security:
        - api_email: []
          api_key: []
      summary: Create DNS Firewall Cluster
      tags:
        - DNS Firewall
      x-api-token-group:
        - DNS Firewall Write
      x-cfPermissionsRequired:
        enum:
          - '#dns_records:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/dns_firewall/{dns_firewall_id}:
    get:
      description: Show a single DNS Firewall cluster for an account
      operationId: dns-firewall-dns-firewall-cluster-details
      parameters:
        - in: path
          name: dns_firewall_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-firewall_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-firewall_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dns-firewall_dns_firewall_single_response'
          description: DNS Firewall Cluster Details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/dns-firewall_dns_firewall_single_response
                  - $ref: >-
                      #/components/schemas/dns-firewall_api-response-common-failure
          description: DNS Firewall Cluster Details response failure
      security:
        - api_email: []
          api_key: []
      summary: DNS Firewall Cluster Details
      tags:
        - DNS Firewall
      x-api-token-group:
        - DNS Firewall Write
        - DNS Firewall Read
      x-cfPermissionsRequired:
        enum:
          - '#dns_records:read'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    patch:
      description: Modify the configuration of a DNS Firewall cluster
      operationId: dns-firewall-update-dns-firewall-cluster
      parameters:
        - in: path
          name: dns_firewall_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-firewall_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-firewall_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dns-firewall_dns-firewall-cluster-patch'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dns-firewall_dns_firewall_single_response'
          description: Update DNS Firewall Cluster response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/dns-firewall_dns_firewall_single_response
                  - $ref: >-
                      #/components/schemas/dns-firewall_api-response-common-failure
          description: Update DNS Firewall Cluster response failure
      security:
        - api_email: []
          api_key: []
      summary: Update DNS Firewall Cluster
      tags:
        - DNS Firewall
      x-api-token-group:
        - DNS Firewall Write
      x-cfPermissionsRequired:
        enum:
          - '#dns_records:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    delete:
      description: Delete a DNS Firewall cluster
      operationId: dns-firewall-delete-dns-firewall-cluster
      parameters:
        - in: path
          name: dns_firewall_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-firewall_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-firewall_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dns-firewall_api-response-single'
                  - properties:
                      result:
                        properties:
                          id:
                            $ref: '#/components/schemas/dns-firewall_identifier'
          description: Delete DNS Firewall Cluster response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: '#/components/schemas/dns-firewall_api-response-single'
                      - properties:
                          result:
                            properties:
                              id:
                                $ref: '#/components/schemas/dns-firewall_identifier'
                  - $ref: >-
                      #/components/schemas/dns-firewall_api-response-common-failure
          description: Delete DNS Firewall Cluster response failure
      security:
        - api_email: []
          api_key: []
      summary: Delete DNS Firewall Cluster
      tags:
        - DNS Firewall
      x-api-token-group:
        - DNS Firewall Write
      x-cfPermissionsRequired:
        enum:
          - '#dns_records:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/dns_firewall/{dns_firewall_id}/reverse_dns:
    get:
      description: Show reverse DNS configuration (PTR records) for a DNS Firewall cluster
      operationId: dns-firewall-show-dns-firewall-cluster-reverse-dns
      parameters:
        - in: path
          name: dns_firewall_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-firewall_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-firewall_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/dns-firewall_dns_firewall_reverse_dns_response
          description: Show DNS Firewall Cluster Reverse DNS response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/dns-firewall_dns_firewall_reverse_dns_response
                  - $ref: >-
                      #/components/schemas/dns-firewall_api-response-common-failure
          description: Show DNS Firewall Cluster Reverse DNS response failure
      security:
        - api_email: []
          api_key: []
      summary: Show DNS Firewall Cluster Reverse DNS
      tags:
        - DNS Firewall
      x-api-token-group:
        - DNS Firewall Write
        - DNS Firewall Read
      x-cfPermissionsRequired:
        enum:
          - '#dns_records:read'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    patch:
      description: >-
        Update reverse DNS configuration (PTR records) for a DNS Firewall
        cluster
      operationId: dns-firewall-update-dns-firewall-cluster-reverse-dns
      parameters:
        - in: path
          name: dns_firewall_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-firewall_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-firewall_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dns-firewall_dns-firewall-reverse-dns-patch'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/dns-firewall_dns_firewall_reverse_dns_response
          description: Update DNS Firewall Cluster Reverse DNS response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/dns-firewall_dns_firewall_reverse_dns_response
                  - $ref: >-
                      #/components/schemas/dns-firewall_api-response-common-failure
          description: Update DNS Firewall Cluster Reverse DNS response failure
      security:
        - api_email: []
          api_key: []
      summary: Update DNS Firewall Cluster Reverse DNS
      tags:
        - DNS Firewall
      x-api-token-group:
        - DNS Firewall Write
      x-cfPermissionsRequired:
        enum:
          - '#dns_records:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    dns-firewall_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/dns-firewall_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/dns-firewall_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    dns-firewall_api-response-single:
      allOf:
        - $ref: '#/components/schemas/dns-firewall_api-response-common'
      type: object
    dns-firewall_dns-firewall-cluster-patch:
      allOf:
        - $ref: '#/components/schemas/dns-firewall_dns-firewall-cluster'
      type: object
    dns-firewall_dns-firewall-cluster-post:
      allOf:
        - $ref: '#/components/schemas/dns-firewall_dns-firewall-cluster'
      required:
        - name
        - upstream_ips
      type: object
    dns-firewall_dns-firewall-reverse-dns-patch:
      allOf:
        - $ref: '#/components/schemas/dns-firewall_dns-firewall-reverse-dns'
      type: object
    dns-firewall_dns_firewall_response_collection:
      allOf:
        - $ref: '#/components/schemas/dns-firewall_api-response-collection'
        - properties:
            result:
              items:
                $ref: >-
                  #/components/schemas/dns-firewall_dns-firewall-cluster-response
              type: array
    dns-firewall_dns_firewall_reverse_dns_response:
      allOf:
        - $ref: '#/components/schemas/dns-firewall_api-response-single'
        - properties:
            result:
              $ref: >-
                #/components/schemas/dns-firewall_dns-firewall-reverse-dns-response
    dns-firewall_dns_firewall_single_response:
      allOf:
        - $ref: '#/components/schemas/dns-firewall_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/dns-firewall_dns-firewall-cluster-response'
    dns-firewall_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
