openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/dns_settings:
    get:
      description: Show DNS settings for a zone
      operationId: dns-settings-for-a-zone-list-dns-settings
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-settings_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dns-settings_schemas-dns_response_single'
          description: Show DNS Settings response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/dns-settings_schemas-dns_response_single
                  - $ref: >-
                      #/components/schemas/dns-settings_api-response-common-failure
          description: Show DNS Settings response failure
      security:
        - api_email: []
          api_key: []
      summary: Show DNS Settings
      tags:
        - DNS Settings for a Zone
      x-api-token-group:
        - Zone DNS Settings Write
        - Zone DNS Settings Read
        - DNS Read
        - DNS Write
      x-cfPermissionsRequired:
        enum:
          - '#dns_records:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    patch:
      description: Update DNS settings for a zone
      operationId: dns-settings-for-a-zone-update-dns-settings
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-settings_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dns-settings_dns-settings-zone'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dns-settings_schemas-dns_response_single'
          description: Show DNS Settings response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/dns-settings_schemas-dns_response_single
                  - $ref: >-
                      #/components/schemas/dns-settings_api-response-common-failure
          description: Show DNS Settings response failure
      security:
        - api_email: []
          api_key: []
      summary: Update DNS Settings
      tags:
        - DNS Settings for a Zone
      x-api-token-group:
        - Zone DNS Settings Write
        - DNS Write
      x-cfPermissionsRequired:
        enum:
          - '#dns_records:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    dns-settings_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/dns-settings_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/dns-settings_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    dns-settings_dns-settings-zone:
      allOf:
        - $ref: '#/components/schemas/dns-settings_dns-settings'
        - properties:
            nameservers:
              description: >-
                Settings determining the nameservers through which the zone
                should be available.
              properties:
                ns_set:
                  description: Configured nameserver set to be used for this zone
                  example: 1
                  maximum: 5
                  minimum: 1
                  type: integer
                  x-auditable: true
                type:
                  description: Nameserver type
                  enum:
                    - cloudflare.standard
                    - custom.account
                    - custom.tenant
                    - custom.zone
                  example: cloudflare.standard
                  type: string
                  x-auditable: true
              required:
                - type
              type: object
          type: object
    dns-settings_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
    dns-settings_schemas-dns_response_single:
      allOf:
        - $ref: '#/components/schemas/dns-settings_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/dns-settings_dns-settings-zone'
          type: object
