openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/dns_settings/views:
    get:
      description: List DNS Internal Views for an Account
      operationId: dns-views-for-an-account-list-internal-dns-views
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-settings_identifier'
        - in: query
          name: name
          schema:
            description: >
              Exact value of the DNS view name. This is a convenience alias for
              `name.exact`.
            example: my view
            type: string
        - in: query
          name: name.exact
          schema:
            description: |
              Exact value of the DNS view name.
            example: my view
            type: string
        - in: query
          name: name.contains
          schema:
            description: |
              Substring of the DNS view name.
            example: view
            type: string
        - in: query
          name: name.startswith
          schema:
            description: |
              Prefix of the DNS view name.
            example: my
            type: string
        - in: query
          name: name.endswith
          schema:
            description: |
              Suffix of the DNS view name.
            example: ew
            type: string
        - in: query
          name: zone_id
          schema:
            description: |
              A zone ID that exists in the zones list for the view.
            example: ae29bea30e2e427ba9cd8d78b628177b
            type: string
        - in: query
          name: zone_name
          schema:
            description: |
              A zone name that exists in the zones list for the view.
            example: www.example.com
            type: string
        - in: query
          name: match
          schema:
            $ref: '#/components/schemas/dns-settings_match'
        - in: query
          name: page
          schema:
            $ref: '#/components/schemas/dns-settings_page'
        - in: query
          name: per_page
          schema:
            $ref: '#/components/schemas/dns-settings_per_page'
        - in: query
          name: order
          schema:
            $ref: '#/components/schemas/dns-settings_order'
        - in: query
          name: direction
          schema:
            $ref: '#/components/schemas/dns-settings_direction'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dns-settings_dns_view_response_collection'
          description: List Internal DNS Views response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/dns-settings_dns_view_response_collection
                  - $ref: >-
                      #/components/schemas/dns-settings_api-response-common-failure
          description: List Internal DNS Views response failure
      security:
        - api_email: []
          api_key: []
      summary: List Internal DNS Views
      tags:
        - DNS Internal Views for an Account
      x-api-token-group:
        - DNS View Write
        - DNS View Read
      x-cfPermissionsRequired:
        enum:
          - '#dns.view:list'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    post:
      description: Create Internal DNS View for an account
      operationId: dns-views-for-an-account-create-internal-dns-views
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-settings_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dns-settings_dns-view-post'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dns-settings_dns_view_response_single'
          description: Create Internal DNS View response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dns-settings_dns_view_response_single'
                  - $ref: >-
                      #/components/schemas/dns-settings_api-response-common-failure
          description: Create Internal DNS View response failure
      security:
        - api_email: []
          api_key: []
      summary: Create Internal DNS View
      tags:
        - DNS Internal Views for an Account
      x-api-token-group:
        - DNS View Write
      x-cfPermissionsRequired:
        enum:
          - '#dns.view:create'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/dns_settings/views/{view_id}:
    get:
      description: Get DNS Internal View
      operationId: dns-views-for-an-account-get-internal-dns-view
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-settings_identifier'
        - in: path
          name: view_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-settings_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dns-settings_dns_view_response_single'
          description: Get DNS Internal View response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dns-settings_dns_view_response_single'
                  - $ref: >-
                      #/components/schemas/dns-settings_api-response-common-failure
          description: List Internal DNS Views response failure
      security:
        - api_email: []
          api_key: []
      summary: DNS Internal View Details
      tags:
        - DNS Internal Views for an Account
      x-api-token-group:
        - DNS View Write
        - DNS View Read
      x-cfPermissionsRequired:
        enum:
          - '#dns.view:read'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    patch:
      description: Update an existing Internal DNS View
      operationId: dns-views-for-an-account-update-internal-dns-view
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-settings_identifier'
        - in: path
          name: view_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-settings_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dns-settings_dns-view-patch'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dns-settings_dns_view_response_single'
          description: Update Internal DNS View response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dns-settings_dns_view_response_single'
                  - $ref: >-
                      #/components/schemas/dns-settings_api-response-common-failure
          description: Update Internal DNS View response failure
      security:
        - api_email: []
          api_key: []
      summary: Update Internal DNS View
      tags:
        - DNS Internal Views for an Account
      x-api-token-group:
        - DNS View Write
      x-cfPermissionsRequired:
        enum:
          - '#dns.view:update'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    delete:
      description: Delete an existing Internal DNS View
      operationId: dns-views-for-an-account-delete-internal-dns-view
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-settings_identifier'
        - in: path
          name: view_id
          required: true
          schema:
            $ref: '#/components/schemas/dns-settings_identifier'
      requestBody:
        content:
          application/json: {}
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  result:
                    properties:
                      id:
                        $ref: '#/components/schemas/dns-settings_identifier'
                type: object
          description: Delete Internal DNS View response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      result:
                        properties:
                          id:
                            $ref: '#/components/schemas/dns-settings_identifier'
                    type: object
                  - $ref: >-
                      #/components/schemas/dns-settings_api-response-common-failure
          description: Update Internal DNS View response failure
      security:
        - api_email: []
          api_key: []
      summary: Delete Internal DNS View
      tags:
        - DNS Internal Views for an Account
      x-api-token-group:
        - DNS View Write
      x-cfPermissionsRequired:
        enum:
          - '#dns.view:delete'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    dns-settings_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/dns-settings_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/dns-settings_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    dns-settings_direction:
      default: asc
      description: Direction to order DNS views in.
      enum:
        - asc
        - desc
      type: string
    dns-settings_dns-view-patch:
      allOf:
        - $ref: '#/components/schemas/dns-settings_dns-view'
      type: object
    dns-settings_dns-view-post:
      allOf:
        - $ref: '#/components/schemas/dns-settings_dns-view'
      required:
        - name
        - zones
      type: object
    dns-settings_dns_view_response_collection:
      allOf:
        - $ref: '#/components/schemas/dns-settings_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/dns-settings_dns-view-response'
              type: array
          type: object
    dns-settings_dns_view_response_single:
      allOf:
        - $ref: '#/components/schemas/dns-settings_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/dns-settings_dns-view-response'
          type: object
    dns-settings_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
    dns-settings_match:
      default: all
      description: >
        Whether to match all search requirements or at least one (any). If set
        to `all`, acts like a logical AND between filters. If set to `any`, acts
        like a logical OR instead.
      enum:
        - any
        - all
      example: any
      type: string
    dns-settings_order:
      default: type
      description: Field to order DNS views by.
      enum:
        - name
        - created_on
        - modified_on
      type: string
    dns-settings_page:
      default: 1
      description: Page number of paginated results.
      minimum: 1
      type: number
    dns-settings_per_page:
      default: 100
      description: Number of DNS views per page.
      example: 5
      maximum: 5000000
      minimum: 1
      type: number
