openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/intel/domain:
    get:
      description: Gets security details and statistics about a domain.
      operationId: domain-intelligence-get-domain-details
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/intel_identifier'
        - in: query
          name: domain
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/intel_single_response'
          description: Get Domain Details response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/intel_single_response'
                  - $ref: '#/components/schemas/intel_api-response-common-failure'
          description: Get Domain Details response failure.
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get Domain Details
      tags:
        - Domain Intelligence
      x-api-token-group:
        - Intel Write
        - Intel Read
  /accounts/{account_id}/intel/domain/bulk:
    get:
      description: Same as summary.
      operationId: domain-intelligence-get-multiple-domain-details
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/intel_identifier'
        - description: >-
            Accepts multiple values like
            `?domain=cloudflare.com&domain=example.com`.
          explode: true
          in: query
          name: domain
          schema:
            items:
              type: string
            type: array
          style: form
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/intel_collection_response'
          description: Get Multiple Domain Details response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/intel_collection_response'
                  - $ref: '#/components/schemas/intel_api-response-common-failure'
          description: Get Multiple Domain Details response failure.
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get Multiple Domain Details
      tags:
        - Domain Intelligence
      x-api-token-group:
        - Intel Write
        - Intel Read
components:
  schemas:
    intel_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/intel_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/intel_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    intel_collection_response:
      allOf:
        - $ref: '#/components/schemas/intel_api-response-collection'
        - properties:
            result:
              items:
                properties:
                  additional_information:
                    $ref: '#/components/schemas/intel_additional_information'
                  application:
                    $ref: '#/components/schemas/intel_application'
                  content_categories:
                    $ref: '#/components/schemas/intel_content_categories'
                  domain:
                    $ref: '#/components/schemas/intel_domain_name'
                  inherited_content_categories:
                    $ref: '#/components/schemas/intel_inherited_content_categories'
                  inherited_from:
                    $ref: '#/components/schemas/intel_inherited_from'
                  inherited_risk_types:
                    $ref: '#/components/schemas/intel_inherited_risk_types'
                  popularity_rank:
                    $ref: '#/components/schemas/intel_popularity_rank'
                  risk_score:
                    $ref: '#/components/schemas/intel_risk_score'
                  risk_types:
                    $ref: '#/components/schemas/intel_risk_types'
                type: object
              type: array
          type: object
      type: object
    intel_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
    intel_single_response:
      allOf:
        - $ref: '#/components/schemas/intel_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/intel_domain'
          type: object
      type: object
