openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/brand-protection/matches:
    get:
      description: Return matches for string queries based on ID
      parameters:
        - in: query
          name: id
          schema:
            type: string
        - in: query
          name: offset
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
        - in: query
          name: include_domain_id
          schema:
            type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/brand-protection-api_QueryMatch'
          description: OK
        '422':
          $ref: '#/components/responses/brand-protection-api_UNPROCESSABLE_CONTENT'
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Read matches for string queries by ID
      tags:
        - domain_search
      x-api-token-group:
        - Intel Write
        - Intel Read
  /accounts/{account_id}/brand-protection/matches/download:
    get:
      description: Return matches as CSV for string queries based on ID
      parameters:
        - in: query
          name: id
          schema:
            type: string
        - in: query
          name: offset
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
        - in: query
          name: include_domain_id
          schema:
            type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/brand-protection-api_QueryMatch'
          description: OK
        '422':
          $ref: '#/components/responses/brand-protection-api_UNPROCESSABLE_CONTENT'
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Download matches for string queries by ID
      tags:
        - domain_search
      x-api-token-group:
        - Intel Write
        - Intel Read
  /accounts/{account_id}/brand-protection/queries:
    get:
      description: Return string queries based on ID
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Read string queries by ID
      tags:
        - domain_search
      x-api-token-group:
        - Intel Write
        - Intel Read
    post:
      description: Return a success message after creating new saved string queries
      parameters:
        - in: query
          name: id
          schema:
            type: string
        - in: query
          name: tag
          schema:
            type: string
        - in: query
          name: scan
          schema:
            type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/brand-protection-api_Query'
        required: true
      responses:
        '204':
          description: No Content
        '422':
          $ref: '#/components/responses/brand-protection-api_UNPROCESSABLE_CONTENT'
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Create new saved string queries
      tags:
        - domain_search
      x-api-token-group:
        - Intel Write
    patch:
      description: Return a success message after updating saved string queries by ID
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Update saved string queries by ID
      tags:
        - domain_search
      x-api-token-group:
        - Intel Write
    delete:
      description: Return a success message after deleting saved string queries by ID
      parameters:
        - in: query
          name: id
          schema:
            type: string
        - in: query
          name: tag
          schema:
            type: string
        - in: query
          name: scan
          schema:
            type: boolean
      responses:
        '204':
          description: No Content
        '422':
          $ref: '#/components/responses/brand-protection-api_UNPROCESSABLE_CONTENT'
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Delete saved string queries by ID
      tags:
        - domain_search
      x-api-token-group:
        - Intel Write
  /accounts/{account_id}/brand-protection/search:
    post:
      description: Return new string queries
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Create new string queries
      tags:
        - domain_search
      x-api-token-group:
        - Intel Write
  /accounts/{account_id}/brand-protection/total-queries:
    get:
      description: Return the total number of saved string queries
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Read the total number of saved string queries
      tags:
        - domain_search
      x-api-token-group:
        - Intel Write
        - Intel Read
components:
  schemas:
    brand-protection-api_Query:
      properties:
        max_time:
          format: date-time
          nullable: true
          type: string
        min_time:
          format: date-time
          nullable: true
          type: string
        scan:
          type: boolean
        string_matches: {}
        tag:
          type: string
      type: object
    brand-protection-api_QueryMatch:
      properties:
        matches:
          items:
            additionalProperties: {}
            type: object
          type: array
        total:
          type: integer
      type: object
  responses:
    brand-protection-api_DEFAULT_ERROR:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/brand-protection-api_Error'
      description: Default error response
    brand-protection-api_UNPROCESSABLE_CONTENT:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/brand-protection-api_Error'
      description: Unprocessable Content
