openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/email/routing:
    get:
      description: Get information about the settings for your Email Routing zone.
      operationId: email-routing-settings-get-email-routing-settings
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/email_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/email_email_settings_response_single'
          description: Get Email Routing settings response
      security:
        - api_email: []
          api_key: []
      summary: Get Email Routing settings
      tags:
        - Email Routing settings
      x-api-token-group:
        - Zone Settings Write
        - Zone Settings Read
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.api.account.zone.email.routing.config.read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /zones/{zone_id}/email/routing/disable:
    post:
      deprecated: true
      description: >-
        Disable your Email Routing zone. Also removes additional MX records
        previously required for Email Routing to work.
      operationId: email-routing-settings-disable-email-routing
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/email_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/email_email_settings_response_single'
          description: Disable Email Routing response
      security:
        - api_email: []
          api_key: []
      summary: Disable Email Routing
      tags:
        - Email Routing settings
      x-api-token-group:
        - Zone Settings Write
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.api.account.zone.email.routing.config.update
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /zones/{zone_id}/email/routing/dns:
    get:
      description: Show the DNS records needed to configure your Email Routing zone.
      operationId: email-routing-settings-email-routing-dns-settings
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/email_identifier'
        - in: query
          name: subdomain
          schema:
            $ref: '#/components/schemas/email_email_setting_name'
      responses:
        '200':
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: >-
                      #/components/schemas/email_email_routing_dns_query_response
                  - $ref: >-
                      #/components/schemas/email_dns_settings_response_collection
          description: Email Routing - DNS settings response
      security:
        - api_email: []
          api_key: []
      summary: Email Routing - DNS settings
      tags:
        - Email Routing settings
      x-api-token-group:
        - Zone Settings Write
        - Zone Settings Read
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.api.account.zone.email.routing.config.read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    post:
      description: >-
        Enable you Email Routing zone. Add and lock the necessary MX and SPF
        records.
      operationId: email-routing-settings-enable-email-routing-dns
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/email_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/email_email_setting_dns_request_body'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/email_email_settings_response_single'
          description: Enable Email Routing response
      security:
        - api_email: []
          api_key: []
      summary: Enable Email Routing
      tags:
        - Email Routing settings
      x-api-token-group:
        - Zone Settings Write
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.api.account.zone.email.routing.config.update
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    patch:
      description: Unlock MX Records previously locked by Email Routing.
      operationId: email-routing-settings-unlock-email-routing-dns
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/email_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/email_email_setting_dns_request_body'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/email_email_settings_response_single'
          description: Unlock Email Routing MX records
      security:
        - api_email: []
          api_key: []
      summary: Unlock Email Routing
      tags:
        - Email Routing settings
      x-api-token-group:
        - Zone Settings Write
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.api.account.zone.email.routing.config.update
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    delete:
      description: >-
        Disable your Email Routing zone. Also removes additional MX records
        previously required for Email Routing to work.
      operationId: email-routing-settings-disable-email-routing-dns
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/email_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/email_email_setting_dns_request_body'
      responses:
        '200':
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/email_api-response-single'
                  - $ref: >-
                      #/components/schemas/email_dns_settings_response_collection
          description: Disable Email Routing response
      security:
        - api_email: []
          api_key: []
      summary: Disable Email Routing
      tags:
        - Email Routing settings
      x-api-token-group:
        - Zone Settings Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /zones/{zone_id}/email/routing/enable:
    post:
      deprecated: true
      description: >-
        Enable you Email Routing zone. Add and lock the necessary MX and SPF
        records.
      operationId: email-routing-settings-enable-email-routing
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/email_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/email_email_settings_response_single'
          description: Enable Email Routing response
      security:
        - api_email: []
          api_key: []
      summary: Enable Email Routing
      tags:
        - Email Routing settings
      x-api-token-group:
        - Zone Settings Write
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.api.account.zone.email.routing.config.update
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    email_api-response-single:
      allOf:
        - $ref: '#/components/schemas/email_api-response-common'
      type: object
    email_dns_settings_response_collection:
      allOf:
        - $ref: '#/components/schemas/email_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/email_dns_record'
              type: array
    email_email_routing_dns_query_response:
      allOf:
        - $ref: '#/components/schemas/email_api-response-collection'
        - properties:
            result:
              properties:
                errors:
                  $ref: >-
                    #/components/schemas/email_email_routing_get_response_dns_errors
                record:
                  items:
                    $ref: '#/components/schemas/email_dns_record'
                  type: array
              type: object
      type: object
    email_email_setting_dns_request_body:
      nullable: true
      properties:
        name:
          $ref: '#/components/schemas/email_email_setting_name'
      required:
        - name
      type: object
    email_email_setting_name:
      description: Domain of your zone.
      example: example.net
      type: string
      x-auditable: true
    email_email_settings_response_single:
      allOf:
        - $ref: '#/components/schemas/email_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/email_settings'
    email_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
