openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/diagnostics/endpoint-healthchecks:
    get:
      description: List Endpoint Health Checks.
      operationId: diagnostics-endpoint-healthcheck-list
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-transit_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/magic-transit_endpoint_health_check_response_single
          description: Endpoint Health Checks for account.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/magic-transit_api-response-common-failure
          description: Endpoint Health Check response failure.
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: List Endpoint Health Checks
      tags:
        - Endpoint Health Checks
      x-api-token-group:
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    post:
      description: Create Endpoint Health Check.
      operationId: diagnostics-endpoint-healthcheck-create
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-transit_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic-transit_endpoint_health_check'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/magic-transit_endpoint_health_check_response_single
          description: Endpoint Health Check response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/magic-transit_api-response-common-failure
          description: Endpoint Health Check response failure.
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Endpoint Health Check
      tags:
        - Endpoint Health Checks
      x-api-token-group:
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/diagnostics/endpoint-healthchecks/{id}:
    get:
      description: Get a single Endpoint Health Check.
      operationId: diagnostics-endpoint-healthcheck-get
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-transit_identifier'
        - in: path
          name: id
          required: true
          schema:
            $ref: '#/components/schemas/magic-transit_uuid'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/magic-transit_endpoint_health_check_response_single
          description: Endpoint Health Checks response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/magic-transit_traceroute_response_collection
                  - $ref: >-
                      #/components/schemas/magic-transit_api-response-common-failure
          description: Endpoint Health Check failure.
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get Endpoint Health Check
      tags:
        - Endpoint Health Checks
      x-api-token-group:
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    put:
      description: Update a Endpoint Health Check.
      operationId: diagnostics-endpoint-healthcheck-update
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-transit_identifier'
        - in: path
          name: id
          required: true
          schema:
            $ref: '#/components/schemas/magic-transit_uuid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic-transit_endpoint_health_check'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/magic-transit_endpoint_health_check_response_single
          description: Endpoint Health Checks response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/magic-transit_api-response-common-failure
          description: Endpoint Health Check failure.
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Update Endpoint Health Check
      tags:
        - Endpoint Health Checks
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    delete:
      description: Delete Endpoint Health Check.
      operationId: diagnostics-endpoint-healthcheck-delete
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-transit_identifier'
        - in: path
          name: id
          required: true
          schema:
            $ref: '#/components/schemas/magic-transit_uuid'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic-transit_api-response-common'
          description: Endpoint Health Checks response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/magic-transit_api-response-common-failure
          description: Endpoint Health Check failure.
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Delete Endpoint Health Check
      tags:
        - Endpoint Health Checks
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    magic-transit_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/magic-transit_messages'
        messages:
          $ref: '#/components/schemas/magic-transit_messages'
        success:
          description: Whether the API call was successful.
          enum:
            - true
          example: true
          type: boolean
      required:
        - success
        - errors
        - messages
      type: object
    magic-transit_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/magic-transit_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/magic-transit_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    magic-transit_endpoint_health_check:
      properties:
        check_type:
          $ref: '#/components/schemas/magic-transit_check_type'
        endpoint:
          description: the IP address of the host to perform checks against
          example: 203.0.113.1
          type: string
        name:
          description: Optional name associated with this check
          example: My Endpoint
          type: string
      required:
        - check_type
        - endpoint
      type: object
    magic-transit_endpoint_health_check_response_single:
      allOf:
        - $ref: '#/components/schemas/magic-transit_api-response-common'
        - properties:
            result:
              $ref: >-
                #/components/schemas/magic-transit_endpoint_health_check_response
    magic-transit_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    magic-transit_traceroute_response_collection:
      allOf:
        - $ref: '#/components/schemas/magic-transit_api-response-common'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/magic-transit_target_result'
              type: array
    magic-transit_uuid:
      description: UUID.
      example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      maxLength: 36
      type: string
