openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/addressing/prefixes/{prefix_id}/bgp/status:
    get:
      deprecated: true
      description: >
        View the current advertisement state for a prefix.


        **Deprecated:** Prefer the BGP Prefixes endpoints, which additionally
        allow for advertising and withdrawing 

        subnets of an IP prefix.
      operationId: ip-address-management-dynamic-advertisement-get-advertisement-status
      parameters:
        - in: path
          name: prefix_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_prefix_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_advertised_response'
          description: Get Advertisement Status response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/addressing_advertised_response'
                  - $ref: >-
                      #/components/schemas/addressing_api-response-common-failure
          description: Get Advertisement Status response failure
      security:
        - api_email: []
          api_key: []
      summary: Get Advertisement Status
      tags:
        - IP Address Management Dynamic Advertisement
      x-api-token-group:
        - Magic Transit Read
        - Magic Transit Write
        - 'IP Prefixes: Write'
        - 'IP Prefixes: Read'
        - 'IP Prefixes: BGP On Demand Write'
        - 'IP Prefixes: BGP On Demand Read'
    patch:
      deprecated: true
      description: >
        Advertise or withdraw the BGP route for a prefix.


        **Deprecated:** Prefer the BGP Prefixes endpoints, which additionally
        allow for advertising and withdrawing 

        subnets of an IP prefix.
      operationId: >-
        ip-address-management-dynamic-advertisement-update-prefix-dynamic-advertisement-status
      parameters:
        - in: path
          name: prefix_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_prefix_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                advertised:
                  $ref: '#/components/schemas/addressing_schemas-advertised'
              required:
                - advertised
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_advertised_response'
          description: Update Prefix Dynamic Advertisement Status response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/addressing_advertised_response'
                  - $ref: >-
                      #/components/schemas/addressing_api-response-common-failure
          description: Update Prefix Dynamic Advertisement Status response failure
      security:
        - api_email: []
          api_key: []
      summary: Update Prefix Dynamic Advertisement Status
      tags:
        - IP Address Management Dynamic Advertisement
      x-api-token-group:
        - Magic Transit Write
        - 'IP Prefixes: Write'
        - 'IP Prefixes: BGP On Demand Write'
components:
  schemas:
    addressing_account_identifier:
      description: Identifier of a Cloudflare account.
      example: 258def64c72dae45f3e4c8516e2111f2
      maxLength: 32
      type: string
      x-auditable: true
    addressing_advertised_response:
      allOf:
        - $ref: '#/components/schemas/addressing_api-response-single'
        - properties:
            result:
              properties:
                advertised:
                  $ref: '#/components/schemas/addressing_schemas-advertised'
                advertised_modified_at:
                  $ref: '#/components/schemas/addressing_modified_at_nullable'
              type: object
    addressing_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/addressing_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/addressing_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    addressing_prefix_identifier:
      description: Identifier of an IP Prefix.
      example: 2af39739cc4e3b5910c918468bb89828
      maxLength: 32
      type: string
      x-auditable: true
    addressing_schemas-advertised:
      description: >
        Advertisement status of the prefix. If `true`, the BGP route for the
        prefix is advertised to the Internet. If 

        `false`, the BGP route is withdrawn.
      example: true
      type: boolean
      x-auditable: true
