openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/addressing/loa_documents:
    post:
      description: Submit LOA document (pdf format) under the account.
      operationId: ip-address-management-prefixes-upload-loa-document
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_account_identifier'
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                loa_document:
                  description: LOA document to upload.
                  example: '@document.pdf'
                  type: string
              required:
                - loa_document
              type: object
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_loa_upload_response'
          description: Upload LOA Document response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/addressing_loa_upload_response'
                  - $ref: >-
                      #/components/schemas/addressing_api-response-common-failure
          description: Upload LOA Document response failure
      security:
        - api_email: []
          api_key: []
      summary: Upload LOA Document
      tags:
        - IP Address Management Prefixes
      x-api-token-group:
        - Magic Transit Write
  /accounts/{account_id}/addressing/loa_documents/{loa_document_id}/download:
    get:
      description: Download specified LOA document under the account.
      operationId: ip-address-management-prefixes-download-loa-document
      parameters:
        - in: path
          name: loa_document_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_loa_document_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_account_identifier'
      responses:
        '200':
          content:
            application/pdf:
              schema:
                format: binary
                type: string
          description: Download LOA Document response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - {}
                  - $ref: >-
                      #/components/schemas/addressing_api-response-common-failure
          description: Download LOA Document response failure
      security:
        - api_email: []
          api_key: []
      summary: Download LOA Document
      tags:
        - IP Address Management Prefixes
      x-api-token-group:
        - Magic Transit Read
        - Magic Transit Write
  /accounts/{account_id}/addressing/prefixes:
    get:
      description: List all prefixes owned by the account.
      operationId: ip-address-management-prefixes-list-prefixes
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_response_collection'
          description: List Prefixes response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/addressing_response_collection'
                  - $ref: >-
                      #/components/schemas/addressing_api-response-common-failure
          description: List Prefixes response failure
      security:
        - api_email: []
          api_key: []
      summary: List Prefixes
      tags:
        - IP Address Management Prefixes
      x-api-token-group:
        - Magic Transit Read
        - Magic Transit Write
        - 'IP Prefixes: Write'
        - 'IP Prefixes: Read'
        - 'IP Prefixes: BGP On Demand Write'
        - 'IP Prefixes: BGP On Demand Read'
    post:
      description: Add a new prefix under the account.
      operationId: ip-address-management-prefixes-add-prefix
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                asn:
                  $ref: '#/components/schemas/addressing_asn'
                cidr:
                  $ref: '#/components/schemas/addressing_cidr'
                loa_document_id:
                  $ref: '#/components/schemas/addressing_loa_document_identifier'
              required:
                - cidr
                - loa_document_id
                - asn
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_single_response'
          description: Add Prefix response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/addressing_single_response'
                  - $ref: >-
                      #/components/schemas/addressing_api-response-common-failure
          description: Add Prefix response failure
      security:
        - api_email: []
          api_key: []
      summary: Add Prefix
      tags:
        - IP Address Management Prefixes
      x-api-token-group: null
  /accounts/{account_id}/addressing/prefixes/{prefix_id}:
    get:
      description: List a particular prefix owned by the account.
      operationId: ip-address-management-prefixes-prefix-details
      parameters:
        - in: path
          name: prefix_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_prefix_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_single_response'
          description: Prefix Details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/addressing_single_response'
                  - $ref: >-
                      #/components/schemas/addressing_api-response-common-failure
          description: Prefix Details response failure
      security:
        - api_email: []
          api_key: []
      summary: Prefix Details
      tags:
        - IP Address Management Prefixes
      x-api-token-group:
        - Magic Transit Read
        - Magic Transit Write
        - 'IP Prefixes: Write'
        - 'IP Prefixes: Read'
        - 'IP Prefixes: BGP On Demand Write'
        - 'IP Prefixes: BGP On Demand Read'
    patch:
      description: Modify the description for a prefix owned by the account.
      operationId: ip-address-management-prefixes-update-prefix-description
      parameters:
        - in: path
          name: prefix_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_prefix_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                description:
                  $ref: '#/components/schemas/addressing_description'
              required:
                - description
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_single_response'
          description: Update Prefix Description response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/addressing_single_response'
                  - $ref: >-
                      #/components/schemas/addressing_api-response-common-failure
          description: Update Prefix Description response failure
      security:
        - api_email: []
          api_key: []
      summary: Update Prefix Description
      tags:
        - IP Address Management Prefixes
      x-api-token-group:
        - Magic Transit Write
        - 'IP Prefixes: Write'
    delete:
      description: Delete an unapproved prefix owned by the account.
      operationId: ip-address-management-prefixes-delete-prefix
      parameters:
        - in: path
          name: prefix_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_prefix_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_account_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_api-response-collection'
          description: Delete Prefix response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/addressing_api-response-collection'
                  - $ref: >-
                      #/components/schemas/addressing_api-response-common-failure
          description: Delete Prefix response failure
      security:
        - api_email: []
          api_key: []
      summary: Delete Prefix
      tags:
        - IP Address Management Prefixes
      x-api-token-group:
        - Magic Transit Write
components:
  schemas:
    addressing_account_identifier:
      description: Identifier of a Cloudflare account.
      example: 258def64c72dae45f3e4c8516e2111f2
      maxLength: 32
      type: string
      x-auditable: true
    addressing_api-response-collection:
      allOf:
        - $ref: '#/components/schemas/addressing_api-response-common'
        - properties:
            result_info:
              properties:
                count:
                  description: Total number of results for the requested service.
                  example: 1
                  type: number
                page:
                  description: Current page within paginated list of results.
                  example: 1
                  type: number
                per_page:
                  description: Number of results per page of results.
                  example: 20
                  type: number
                total_count:
                  description: Total results available without any search parameters.
                  example: 2000
                  type: number
              type: object
          type: object
      type: object
    addressing_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/addressing_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/addressing_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    addressing_asn:
      description: Autonomous System Number (ASN) the prefix will be advertised under.
      example: 209242
      nullable: true
      type: integer
      x-auditable: true
    addressing_cidr:
      description: IP Prefix in Classless Inter-Domain Routing format.
      example: 192.0.2.0/24
      type: string
      x-auditable: true
    addressing_description:
      description: Description of the prefix.
      example: Internal test prefix
      maxLength: 1000
      type: string
      x-auditable: true
    addressing_loa_document_identifier:
      description: Identifier for the uploaded LOA document.
      example: d933b1530bc56c9953cf8ce166da8004
      maxLength: 32
      nullable: true
      type: string
      x-auditable: true
    addressing_loa_upload_response:
      allOf:
        - $ref: '#/components/schemas/addressing_api-response-single'
        - properties:
            result:
              properties:
                account_id:
                  $ref: '#/components/schemas/addressing_account_identifier'
                created:
                  $ref: '#/components/schemas/addressing_timestamp'
                filename:
                  $ref: '#/components/schemas/addressing_filename'
                id:
                  $ref: '#/components/schemas/addressing_loa_document_identifier'
                size_bytes:
                  $ref: '#/components/schemas/addressing_size_bytes'
                verified:
                  $ref: '#/components/schemas/addressing_verified'
                verified_at:
                  $ref: '#/components/schemas/addressing_verified_at'
              type: object
    addressing_prefix_identifier:
      description: Identifier of an IP Prefix.
      example: 2af39739cc4e3b5910c918468bb89828
      maxLength: 32
      type: string
      x-auditable: true
    addressing_response_collection:
      allOf:
        - $ref: '#/components/schemas/addressing_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/addressing_ipam-prefixes'
              type: array
    addressing_single_response:
      allOf:
        - $ref: '#/components/schemas/addressing_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/addressing_ipam-prefixes'
