openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/addressing/prefixes/{prefix_id}/bindings:
    get:
      description: >
        List the Cloudflare services this prefix is currently bound to. Traffic
        sent to an address within an IP prefix will be routed to the Cloudflare
        service of the most-specific Service Binding matching the address.

        **Example:** binding `192.0.2.0/24` to Cloudflare Magic Transit and
        `192.0.2.1/32` to the Cloudflare CDN would route traffic for `192.0.2.1`
        to the CDN, and traffic for all other IPs in the prefix to Cloudflare
        Magic Transit.
      operationId: ip-address-management-service-bindings-list-service-bindings
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_account_identifier'
        - in: path
          name: prefix_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_prefix_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/addressing_api-response-common'
                  - properties:
                      result:
                        items:
                          $ref: '#/components/schemas/addressing_service_binding'
                        type: array
          description: Service Bindings attached to the Prefix
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_api-response-common-failure'
          description: List Service Bindings response failure
      security:
        - api_email: []
          api_key: []
      summary: List Service Bindings
      tags:
        - IP Address Management Service Bindings
      x-api-token-group:
        - 'IP Prefixes: Write'
        - 'IP Prefixes: Read'
    post:
      description: >
        Creates a new Service Binding, routing traffic to IPs within the given
        CIDR to a service running on Cloudflare's network.

        **Note:** This API may only be used on prefixes currently configured
        with a Magic Transit/Cloudflare CDN/Cloudflare Spectrum service binding,
        and only allows creating upgrade service bindings for the Cloudflare CDN
        or Cloudflare Spectrum.
      operationId: ip-address-management-service-bindings-create-service-binding
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_account_identifier'
        - in: path
          name: prefix_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_prefix_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addressing_create_binding_request'
      responses:
        '201':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/addressing_api-response-common'
                  - properties:
                      result:
                        $ref: '#/components/schemas/addressing_service_binding'
          description: The created Service Binding
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_api-response-common-failure'
          description: Create Service Binding response failure
      security:
        - api_email: []
          api_key: []
      summary: Create Service Binding
      tags:
        - IP Address Management Service Bindings
      x-api-token-group:
        - 'IP Prefixes: Write'
  /accounts/{account_id}/addressing/prefixes/{prefix_id}/bindings/{binding_id}:
    get:
      description: Fetch a single Service Binding
      operationId: ip-address-management-service-bindings-get-service-binding
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_account_identifier'
        - in: path
          name: prefix_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_prefix_identifier'
        - in: path
          name: binding_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_service_binding_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/addressing_api-response-common'
                  - properties:
                      result:
                        $ref: '#/components/schemas/addressing_service_binding'
          description: The Service Binding with the requested ID
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_api-response-common-failure'
          description: Get Service Binding response failure
      security:
        - api_email: []
          api_key: []
      summary: Get Service Binding
      tags:
        - IP Address Management Service Bindings
      x-api-token-group:
        - 'IP Prefixes: Write'
        - 'IP Prefixes: Read'
    delete:
      description: Delete a Service Binding
      operationId: ip-address-management-service-bindings-delete-service-binding
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_account_identifier'
        - in: path
          name: prefix_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_prefix_identifier'
        - in: path
          name: binding_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_service_binding_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_api-response-common'
          description: Service Binding deleted
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_api-response-common-failure'
          description: Delete Service Binding response failure
      security:
        - api_email: []
          api_key: []
      summary: Delete Service Binding
      tags:
        - IP Address Management Service Bindings
      x-api-token-group:
        - 'IP Prefixes: Write'
  /accounts/{account_id}/addressing/services:
    get:
      description: >
        Bring-Your-Own IP (BYOIP) prefixes onboarded to Cloudflare must be bound
        to a service running on the Cloudflare network to enable a Cloudflare
        product on the IP addresses. This endpoint can be used as a reference of
        available services on the Cloudflare network, and their service IDs.
      operationId: ip-address-management-service-bindings-list-services
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/addressing_api-response-common'
                  - properties:
                      result:
                        items:
                          properties:
                            id:
                              $ref: >-
                                #/components/schemas/addressing_service_identifier
                            name:
                              $ref: '#/components/schemas/addressing_service_name'
                        type: array
          description: Service names and IDs
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_api-response-common-failure'
          description: List Services response failure
      security:
        - api_email: []
          api_key: []
      summary: List Services
      tags:
        - IP Address Management Service Bindings
      x-api-token-group:
        - 'IP Prefixes: Write'
        - 'IP Prefixes: Read'
components:
  schemas:
    addressing_account_identifier:
      description: Identifier of a Cloudflare account.
      example: 258def64c72dae45f3e4c8516e2111f2
      maxLength: 32
      type: string
      x-auditable: true
    addressing_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/addressing_messages'
        messages:
          $ref: '#/components/schemas/addressing_messages'
        success:
          description: Whether the API call was successful.
          enum:
            - true
          example: true
          type: boolean
      required:
        - success
        - errors
        - messages
      type: object
    addressing_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/addressing_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/addressing_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    addressing_create_binding_request:
      properties:
        cidr:
          $ref: '#/components/schemas/addressing_cidr'
        service_id:
          $ref: '#/components/schemas/addressing_service_identifier'
      type: object
    addressing_prefix_identifier:
      description: Identifier of an IP Prefix.
      example: 2af39739cc4e3b5910c918468bb89828
      maxLength: 32
      type: string
      x-auditable: true
    addressing_service_binding:
      properties:
        cidr:
          $ref: '#/components/schemas/addressing_cidr'
        id:
          $ref: '#/components/schemas/addressing_service_binding_identifier'
        provisioning:
          $ref: '#/components/schemas/addressing_provisioning'
        service_id:
          $ref: '#/components/schemas/addressing_service_identifier'
        service_name:
          $ref: '#/components/schemas/addressing_service_name'
      type: object
    addressing_service_binding_identifier:
      description: Identifier of a Service Binding.
      example: 0429b49b6a5155297b78e75a44b09e14
      maxLength: 32
      type: string
      x-auditable: true
    addressing_service_identifier:
      description: >
        Identifier of a Service on the Cloudflare network. Available services
        and their IDs may be found in the

        **List Services** endpoint.
      example: 2db684ee7ca04e159946fd05b99e1bcd
      maxLength: 32
      type: string
      x-auditable: true
    addressing_service_name:
      description: Name of a service running on the Cloudflare network
      example: Magic Transit
      type: string
      x-auditable: true
