openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/addressing/prefixes/{prefix_id}/bgp/prefixes:
    get:
      description: >-
        List all BGP Prefixes within the specified IP Prefix. BGP Prefixes are
        used to control which specific subnets are advertised to the Internet.
        It is possible to advertise subnets more specific than an IP Prefix by
        creating more specific BGP Prefixes.
      operationId: ip-address-management-prefixes-list-bgp-prefixes
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_account_identifier'
        - in: path
          name: prefix_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_prefix_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_response_collection_bgp'
          description: List BGP Prefixes response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/addressing_response_collection_bgp'
                  - $ref: >-
                      #/components/schemas/addressing_api-response-common-failure
          description: List BGP Prefixes response failure
      security:
        - api_email: []
          api_key: []
      summary: List BGP Prefixes
      tags:
        - IP Address Management BGP Prefixes
      x-api-token-group:
        - Magic Transit Read
        - Magic Transit Write
        - 'IP Prefixes: Write'
        - 'IP Prefixes: Read'
        - 'IP Prefixes: BGP On Demand Write'
        - 'IP Prefixes: BGP On Demand Read'
    post:
      description: >-
        Create a BGP prefix, controlling the BGP advertisement status of a
        specific subnet. When created, BGP prefixes are initially withdrawn, and
        can be advertised with the Update BGP Prefix API.
      operationId: ip-address-management-prefixes-create-bgp-prefix
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_account_identifier'
        - in: path
          name: prefix_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_prefix_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addressing_bgp_prefix_create'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_single_response_bgp'
          description: Create BGP Prefix response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/addressing_single_response_bgp'
                  - $ref: >-
                      #/components/schemas/addressing_api-response-common-failure
          description: Create BGP Prefix response failure
      security:
        - api_email: []
          api_key: []
      summary: Create BGP Prefix
      tags:
        - IP Address Management BGP Prefixes
  /accounts/{account_id}/addressing/prefixes/{prefix_id}/bgp/prefixes/{bgp_prefix_id}:
    get:
      description: Retrieve a single BGP Prefix according to its identifier
      operationId: ip-address-management-prefixes-fetch-bgp-prefix
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_account_identifier'
        - in: path
          name: prefix_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_prefix_identifier'
        - in: path
          name: bgp_prefix_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_bgp_prefix_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_single_response_bgp'
          description: Fetch BGP Prefix response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/addressing_single_response_bgp'
                  - $ref: >-
                      #/components/schemas/addressing_api-response-common-failure
          description: Fetch BGP Prefix response failure
      security:
        - api_email: []
          api_key: []
      summary: Fetch BGP Prefix
      tags:
        - IP Address Management BGP Prefixes
      x-api-token-group:
        - Magic Transit Read
        - Magic Transit Write
        - 'IP Prefixes: Write'
        - 'IP Prefixes: Read'
        - 'IP Prefixes: BGP On Demand Write'
        - 'IP Prefixes: BGP On Demand Read'
    patch:
      description: >-
        Update the properties of a BGP Prefix, such as the on demand
        advertisement status (advertised or withdrawn).
      operationId: ip-address-management-prefixes-update-bgp-prefix
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_account_identifier'
        - in: path
          name: prefix_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_prefix_identifier'
        - in: path
          name: bgp_prefix_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_bgp_prefix_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addressing_bgp_prefix_update_advertisement'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_single_response_bgp'
          description: Update BGP Prefix response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/addressing_single_response_bgp'
                  - $ref: >-
                      #/components/schemas/addressing_api-response-common-failure
          description: Update BGP Prefix response failure
      security:
        - api_email: []
          api_key: []
      summary: Update BGP Prefix
      tags:
        - IP Address Management BGP Prefixes
      x-api-token-group:
        - Magic Transit Write
        - 'IP Prefixes: Write'
        - 'IP Prefixes: BGP On Demand Write'
components:
  schemas:
    addressing_account_identifier:
      description: Identifier of a Cloudflare account.
      example: 258def64c72dae45f3e4c8516e2111f2
      maxLength: 32
      type: string
      x-auditable: true
    addressing_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/addressing_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/addressing_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    addressing_bgp_prefix_create:
      properties:
        cidr:
          $ref: '#/components/schemas/addressing_cidr'
      type: object
    addressing_bgp_prefix_identifier:
      description: Identifier of BGP Prefix.
      example: 7009ba364c7a5760798ceb430e603b74
      maxLength: 32
      type: string
      x-auditable: true
    addressing_bgp_prefix_update_advertisement:
      properties:
        asn_prepend_count:
          $ref: '#/components/schemas/addressing_asn_prepend_count'
        auto_advertise_withdraw:
          $ref: '#/components/schemas/addressing_auto_advertise_withdraw'
        on_demand:
          properties:
            advertised:
              type: boolean
          type: object
      type: object
    addressing_prefix_identifier:
      description: Identifier of an IP Prefix.
      example: 2af39739cc4e3b5910c918468bb89828
      maxLength: 32
      type: string
      x-auditable: true
    addressing_response_collection_bgp:
      allOf:
        - $ref: '#/components/schemas/addressing_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/addressing_ipam-bgp-prefixes'
              type: array
    addressing_single_response_bgp:
      allOf:
        - $ref: '#/components/schemas/addressing_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/addressing_ipam-bgp-prefixes'
