openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/addressing/prefixes/{prefix_id}/delegations:
    get:
      description: List all delegations for a given account IP prefix.
      operationId: ip-address-management-prefix-delegation-list-prefix-delegations
      parameters:
        - in: path
          name: prefix_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_prefix_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_schemas-response_collection'
          description: List Prefix Delegations response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/addressing_schemas-response_collection
                  - $ref: >-
                      #/components/schemas/addressing_api-response-common-failure
          description: List Prefix Delegations response failure
      security:
        - api_email: []
          api_key: []
      summary: List Prefix Delegations
      tags:
        - IP Address Management Prefix Delegation
    post:
      description: Create a new account delegation for a given IP prefix.
      operationId: ip-address-management-prefix-delegation-create-prefix-delegation
      parameters:
        - in: path
          name: prefix_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_prefix_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                cidr:
                  $ref: '#/components/schemas/addressing_cidr'
                delegated_account_id:
                  $ref: '#/components/schemas/addressing_delegated_account_identifier'
              required:
                - cidr
                - delegated_account_id
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_schemas-single_response'
          description: Create Prefix Delegation response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/addressing_schemas-single_response'
                  - $ref: >-
                      #/components/schemas/addressing_api-response-common-failure
          description: Create Prefix Delegation response failure
      security:
        - api_email: []
          api_key: []
      summary: Create Prefix Delegation
      tags:
        - IP Address Management Prefix Delegation
      x-api-token-group:
        - 'IP Prefixes: Write'
  /accounts/{account_id}/addressing/prefixes/{prefix_id}/delegations/{delegation_id}:
    delete:
      description: Delete an account delegation for a given IP prefix.
      operationId: ip-address-management-prefix-delegation-delete-prefix-delegation
      parameters:
        - in: path
          name: delegation_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_delegation_identifier'
        - in: path
          name: prefix_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_prefix_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/addressing_account_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_id_response'
          description: Delete Prefix Delegation response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/addressing_id_response'
                  - $ref: >-
                      #/components/schemas/addressing_api-response-common-failure
          description: Delete Prefix Delegation response failure
      security:
        - api_email: []
          api_key: []
      summary: Delete Prefix Delegation
      tags:
        - IP Address Management Prefix Delegation
      x-api-token-group:
        - 'IP Prefixes: Write'
components:
  schemas:
    addressing_account_identifier:
      description: Identifier of a Cloudflare account.
      example: 258def64c72dae45f3e4c8516e2111f2
      maxLength: 32
      type: string
      x-auditable: true
    addressing_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/addressing_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/addressing_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    addressing_cidr:
      description: IP Prefix in Classless Inter-Domain Routing format.
      example: 192.0.2.0/24
      type: string
      x-auditable: true
    addressing_delegated_account_identifier:
      description: Account identifier for the account to which prefix is being delegated.
      example: b1946ac92492d2347c6235b4d2611184
      maxLength: 32
      type: string
      x-auditable: true
    addressing_delegation_identifier:
      description: Identifier of a Delegation.
      example: d933b1530bc56c9953cf8ce166da8004
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
    addressing_id_response:
      allOf:
        - $ref: '#/components/schemas/addressing_api-response-single'
        - properties:
            result:
              properties:
                id:
                  $ref: '#/components/schemas/addressing_delegation_identifier'
              type: object
    addressing_prefix_identifier:
      description: Identifier of an IP Prefix.
      example: 2af39739cc4e3b5910c918468bb89828
      maxLength: 32
      type: string
      x-auditable: true
    addressing_schemas-response_collection:
      allOf:
        - $ref: '#/components/schemas/addressing_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/addressing_ipam-delegations'
              type: array
    addressing_schemas-single_response:
      allOf:
        - $ref: '#/components/schemas/addressing_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/addressing_ipam-delegations'
