openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/leaked-credential-checks:
    get:
      description: Retrieves the current status of Leaked Credential Checks.
      operationId: waf-product-api-leaked-credentials-get-status
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-product-api-bundle_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/waf-product-api-bundle_response-status'
          description: Get Leaked Credential Checks status response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/waf-product-api-bundle_response-status
                  - $ref: >-
                      #/components/schemas/waf-product-api-bundle_api-response-common-failure
          description: Get Leaked Credential Checks status failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get Leaked Credential Checks Status
      tags:
        - Leaked Credential Checks
      x-api-token-group:
        - Zone WAF Write
        - Zone WAF Read
        - Account WAF Write
        - Account WAF Read
    post:
      description: Updates the current status of Leaked Credential Checks.
      operationId: waf-product-api-leaked-credentials-set-status
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-product-api-bundle_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/waf-product-api-bundle_status'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/waf-product-api-bundle_response-status'
          description: Set Leaked Credential Checks status response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/waf-product-api-bundle_response-status
                  - $ref: >-
                      #/components/schemas/waf-product-api-bundle_api-response-common-failure
          description: Set Leaked Credential Checks status failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Set Leaked Credential Checks Status
      tags:
        - Leaked Credential Checks
      x-api-token-group:
        - Zone WAF Write
        - Account WAF Write
  /zones/{zone_id}/leaked-credential-checks/detections:
    get:
      description: List user-defined detection patterns for Leaked Credential Checks.
      operationId: waf-product-api-leaked-credentials-list-detections
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-product-api-bundle_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/waf-product-api-bundle_response-custom-detection-collection
          description: List Leaked Credential Checks custom detections response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/waf-product-api-bundle_response-custom-detection-collection
                  - $ref: >-
                      #/components/schemas/waf-product-api-bundle_api-response-common-failure
          description: List Leaked Credential Checks custom detections failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List Leaked Credential Checks Custom Detections
      tags:
        - Leaked Credential Checks
      x-api-token-group:
        - Zone WAF Write
        - Zone WAF Read
        - Account WAF Write
        - Account WAF Read
    post:
      description: Create user-defined detection pattern for Leaked Credential Checks.
      operationId: waf-product-api-leaked-credentials-create-detection
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-product-api-bundle_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/waf-product-api-bundle_custom-detection'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/waf-product-api-bundle_response-custom-detection
          description: Create Leaked Credential Checks custom detection response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/waf-product-api-bundle_response-custom-detection
                  - $ref: >-
                      #/components/schemas/waf-product-api-bundle_api-response-common-failure
          description: Create Leaked Credential Checks custom detection failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create Leaked Credential Checks Custom Detection
      tags:
        - Leaked Credential Checks
      x-api-token-group:
        - Zone WAF Write
        - Account WAF Write
  /zones/{zone_id}/leaked-credential-checks/detections/{detection_id}:
    put:
      description: Update user-defined detection pattern for Leaked Credential Checks.
      operationId: waf-product-api-leaked-credentials-update-detection
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-product-api-bundle_identifier'
        - in: path
          name: detection_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-product-api-bundle_detection-id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/waf-product-api-bundle_custom-detection'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/waf-product-api-bundle_response-custom-detection
          description: Update Leaked Credential Checks custom detection response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/waf-product-api-bundle_response-custom-detection
                  - $ref: >-
                      #/components/schemas/waf-product-api-bundle_api-response-common-failure
          description: Update Leaked Credential Checks custom detection failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update Leaked Credential Checks Custom Detection
      tags:
        - Leaked Credential Checks
      x-api-token-group:
        - Zone WAF Write
        - Account WAF Write
    delete:
      description: Remove user-defined detection pattern for Leaked Credential Checks.
      operationId: waf-product-api-leaked-credentials-delete-detection
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-product-api-bundle_identifier'
        - in: path
          name: detection_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-product-api-bundle_detection-id'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/waf-product-api-bundle_api-response-common
          description: Delete Leaked Credential Checks custom detection response.
        4XX:
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/waf-product-api-bundle_api-response-common-failure
          description: Delete Leaked Credential Checks custom detection failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete Leaked Credential Checks Custom Detection
      tags:
        - Leaked Credential Checks
      x-api-token-group:
        - Zone WAF Write
        - Account WAF Write
components:
  schemas:
    waf-product-api-bundle_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/waf-product-api-bundle_messages'
        messages:
          $ref: '#/components/schemas/waf-product-api-bundle_messages'
        result:
          anyOf:
            - type: object
            - items:
                type: object
              type: array
            - type: string
        success:
          description: Defines whether the API call was successful.
          enum:
            - true
          example: true
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    waf-product-api-bundle_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/waf-product-api-bundle_messages'
          example:
            - code: 10100
              message: Unknown error occured, please try again
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/waf-product-api-bundle_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Defines whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    waf-product-api-bundle_custom-detection:
      description: >-
        Defines a custom set of username/password expressions to match Leaked
        Credential Checks on.
      properties:
        id:
          $ref: '#/components/schemas/waf-product-api-bundle_detection-id'
        password:
          description: >-
            Defines ehe ruleset expression to use in matching the password in a
            request.
          example: lookup_json_string(http.request.body.raw, "secret")
          type: string
          x-auditable: true
        username:
          description: >-
            Defines the ruleset expression to use in matching the username in a
            request.
          example: lookup_json_string(http.request.body.raw, "user")
          type: string
          x-auditable: true
      type: object
    waf-product-api-bundle_detection-id:
      allOf:
        - $ref: '#/components/schemas/waf-product-api-bundle_identifier'
      description: Defines the unique ID for this custom detection.
      example: 18a14bafaa8eb1df04ce683ec18c765e
      x-auditable: true
    waf-product-api-bundle_identifier:
      description: Defines an identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
    waf-product-api-bundle_response-custom-detection:
      allOf:
        - $ref: '#/components/schemas/waf-product-api-bundle_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/waf-product-api-bundle_custom-detection'
          type: object
    waf-product-api-bundle_response-custom-detection-collection:
      allOf:
        - $ref: '#/components/schemas/waf-product-api-bundle_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/waf-product-api-bundle_custom-detection'
              type: array
          type: object
    waf-product-api-bundle_response-status:
      allOf:
        - $ref: '#/components/schemas/waf-product-api-bundle_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/waf-product-api-bundle_status'
          type: object
    waf-product-api-bundle_status:
      description: Defines the overall status for Leaked Credential Checks.
      properties:
        enabled:
          description: Determines whether or not Leaked Credential Checks are enabled.
          example: true
          type: boolean
          x-auditable: true
      type: object
