openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/load_balancers/regions:
    get:
      description: List all region mappings.
      operationId: load-balancer-regions-list-regions
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
        - in: query
          name: subdivision_code
          schema:
            $ref: '#/components/schemas/load-balancing_subdivision_code_a2'
        - in: query
          name: subdivision_code_a2
          schema:
            $ref: '#/components/schemas/load-balancing_subdivision_code_a2'
        - in: query
          name: country_code_a2
          schema:
            description: Two-letter alpha-2 country code followed in ISO 3166-1.
            example: US
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/load-balancing_region_components-schemas-response_collection
          description: List Regions response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/load-balancing_region_components-schemas-response_collection
                  - $ref: >-
                      #/components/schemas/load-balancing_api-response-common-failure
          description: List Regions response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List Regions
      tags:
        - Load Balancer Regions
      x-api-token-group:
        - 'Load Balancing: Monitors and Pools Write'
        - 'Load Balancing: Monitors and Pools Read'
  /accounts/{account_id}/load_balancers/regions/{region_id}:
    get:
      description: Get a single region mapping.
      operationId: load-balancer-regions-get-region
      parameters:
        - in: path
          name: region_id
          required: true
          schema:
            $ref: '#/components/schemas/load-balancing_region_code'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/load-balancing_components-schemas-single_response
          description: Get Region response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/load-balancing_components-schemas-single_response
                  - $ref: >-
                      #/components/schemas/load-balancing_api-response-common-failure
          description: Get Region response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get Region
      tags:
        - Load Balancer Regions
      x-api-token-group:
        - 'Load Balancing: Monitors and Pools Write'
        - 'Load Balancing: Monitors and Pools Read'
components:
  schemas:
    load-balancing_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/load-balancing_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/load-balancing_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    load-balancing_components-schemas-identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
    load-balancing_components-schemas-single_response:
      allOf:
        - $ref: '#/components/schemas/load-balancing_api-response-single'
        - properties:
            result:
              description: A list of countries and subdivisions mapped to a region.
              example:
                iso_standard: >-
                  Country and subdivision codes follow ISO 3166-1 alpha-2 and
                  ISO 3166-2
                regions:
                  - countries:
                      - country_code_a2: CA
                        country_name: Canada
                        country_subdivisions:
                          - subdivision_code_a2: AB
                            subdivision_name: Alberta
                          - subdivision_code_a2: BC
                            subdivision_name: British Columbia
                      - country_code_a2: HT
                        country_name: Haiti
                      - country_code_a2: MX
                        country_name: Mexico
                      - country_code_a2: US
                        country_name: United States
                        country_subdivisions:
                          - subdivision_code_a2: AZ
                            subdivision_name: Arizona
                          - subdivision_code_a2: CA
                            subdivision_name: California
                          - subdivision_code_a2: CO
                            subdivision_name: Colorado
                          - subdivision_code_a2: HI
                            subdivision_name: Hawaii
                          - subdivision_code_a2: MN
                            subdivision_name: Minnesota
                          - subdivision_code_a2: MO
                            subdivision_name: Missouri
                          - subdivision_code_a2: NV
                            subdivision_name: Nevada
                          - subdivision_code_a2: OR
                            subdivision_name: Oregon
                          - subdivision_code_a2: TX
                            subdivision_name: Texas
                          - subdivision_code_a2: UT
                            subdivision_name: Utah
                          - subdivision_code_a2: WA
                            subdivision_name: Washington
                    region_code: WNAM
              type: object
    load-balancing_region_code:
      description: >-
        A list of Cloudflare regions. WNAM: Western North America, ENAM: Eastern
        North America, WEU: Western Europe, EEU: Eastern Europe, NSAM: Northern
        South America, SSAM: Southern South America, OC: Oceania, ME: Middle
        East, NAF: North Africa, SAF: South Africa, SAS: Southern Asia, SEAS:
        South East Asia, NEAS: North East Asia).
      enum:
        - WNAM
        - ENAM
        - WEU
        - EEU
        - NSAM
        - SSAM
        - OC
        - ME
        - NAF
        - SAF
        - SAS
        - SEAS
        - NEAS
      example: WNAM
      type: string
    load-balancing_region_components-schemas-response_collection:
      allOf:
        - $ref: '#/components/schemas/load-balancing_api-response-single'
        - properties:
            result:
              type: object
    load-balancing_subdivision_code_a2:
      description: Two-letter subdivision code followed in ISO 3166-2.
      example: CA
      type: string
      x-auditable: true
