openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /user/load_balancing_analytics/events:
    get:
      description: List origin health changes.
      operationId: load-balancer-healthcheck-events-list-healthcheck-events
      parameters:
        - in: query
          name: until
          schema:
            $ref: '#/components/schemas/load-balancing_until'
        - in: query
          name: pool_name
          schema:
            $ref: '#/components/schemas/load-balancing_pool_name'
        - in: query
          name: origin_healthy
          schema:
            $ref: '#/components/schemas/load-balancing_origin_healthy'
        - in: query
          name: pool_id
          schema:
            $ref: '#/components/schemas/load-balancing_schemas-identifier'
        - in: query
          name: since
          schema:
            description: >-
              Start date and time of requesting data period in the ISO8601
              format.
            example: '2016-11-11T12:00:00Z'
            format: date-time
            type: string
        - in: query
          name: origin_name
          schema:
            description: The name for the origin to filter.
            example: primary-dc-1
            type: string
        - in: query
          name: pool_healthy
          schema:
            default: true
            description: >-
              If true, filter events where the pool status is healthy. If false,
              filter events where the pool status is unhealthy.
            example: true
            type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/load-balancing_components-schemas-response_collection
          description: List Healthcheck Events response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/load-balancing_components-schemas-response_collection
                  - $ref: >-
                      #/components/schemas/load-balancing_api-response-common-failure
          description: List Healthcheck Events response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List Healthcheck Events
      tags:
        - Load Balancer Healthcheck Events
      x-api-token-group:
        - 'Load Balancing: Monitors and Pools Write'
        - 'Load Balancing: Monitors and Pools Read'
components:
  schemas:
    load-balancing_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/load-balancing_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/load-balancing_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    load-balancing_components-schemas-response_collection:
      allOf:
        - $ref: >-
            #/components/schemas/load-balancing_api-paginated-response-collection
        - properties:
            result:
              items:
                $ref: '#/components/schemas/load-balancing_analytics'
              type: array
    load-balancing_origin_healthy:
      default: true
      description: >-
        If true, filter events where the origin status is healthy. If false,
        filter events where the origin status is unhealthy.
      example: true
      type: boolean
      x-auditable: true
    load-balancing_pool_name:
      description: The name for the pool to filter.
      example: primary-dc
      type: string
      x-auditable: true
    load-balancing_schemas-identifier:
      example: 17b5962d775c646f3f9725cbc7a53df4
      type: string
      x-auditable: true
    load-balancing_until:
      description: End date and time of requesting data period in the ISO8601 format.
      example: '2016-11-11T13:00:00Z'
      format: date-time
      type: string
      x-auditable: true
