openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/logs/control/cmb/config:
    get:
      description: Gets CMB config.
      operationId: get-accounts-account_id-logs-control-cmb-config
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/logcontrol_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/logcontrol_cmb_config_response_single'
          description: Get CMB config response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/logcontrol_api-response-common-failure
          description: Get CMB config response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get CMB config
      tags:
        - Logcontrol CMB config for an account
      x-api-token-group:
        - Logs Write
        - Logs Read
      x-cfPermissionsRequired:
        enum:
          - '#logs:read'
          - '#analytics:read'
    post:
      description: Updates CMB config.
      operationId: post-accounts-account_id-logs-control-cmb-config
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/logcontrol_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/logcontrol_cmb_config'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/logcontrol_cmb_config_response_single'
          description: Update CMB config response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/logcontrol_api-response-common-failure
          description: Update CMB config response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update CMB config
      tags:
        - Logcontrol CMB config for an account
      x-api-token-group:
        - Logs Write
      x-cfPermissionsRequired:
        enum:
          - '#logs:edit'
    delete:
      description: Deletes CMB config.
      operationId: delete-accounts-account_id-logs-control-cmb-config
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/logcontrol_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/logcontrol_api-response-common'
                  - properties:
                      result:
                        enum:
                          - null
                        nullable: true
                        type: object
          description: Delete CMB config response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/logcontrol_api-response-common-failure
          description: Delete CMB config response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete CMB config
      tags:
        - Logcontrol CMB config for an account
      x-api-token-group:
        - Logs Write
      x-cfPermissionsRequired:
        enum:
          - '#logs:edit'
components:
  schemas:
    logcontrol_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/logcontrol_messages'
        messages:
          $ref: '#/components/schemas/logcontrol_messages'
        success:
          description: Whether the API call was successful.
          enum:
            - true
          example: true
          type: boolean
      required:
        - success
        - errors
        - messages
      type: object
    logcontrol_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/logcontrol_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/logcontrol_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    logcontrol_cmb_config:
      nullable: true
      properties:
        allow_out_of_region_access:
          $ref: '#/components/schemas/logcontrol_allow_out_of_region_access'
        regions:
          $ref: '#/components/schemas/logcontrol_regions'
      type: object
    logcontrol_cmb_config_response_single:
      allOf:
        - $ref: '#/components/schemas/logcontrol_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/logcontrol_cmb_config'
    logcontrol_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
