openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/brand-protection/logo-matches:
    get:
      description: Return matches for logo queries based on ID
      parameters:
        - explode: true
          in: query
          name: logo_id
          schema:
            items:
              type: string
            type: array
          style: form
        - in: query
          name: offset
          schema:
            type: string
        - in: query
          name: limit
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/brand-protection-api_LogoMatch'
          description: OK
        '422':
          $ref: '#/components/responses/brand-protection-api_UNPROCESSABLE_CONTENT'
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Read matches for logo queries by ID
      tags:
        - logo_match
      x-api-token-group:
        - Intel Write
        - Intel Read
  /accounts/{account_id}/brand-protection/logo-matches/download:
    get:
      description: Return matches as CSV for logo queries based on ID
      parameters:
        - explode: true
          in: query
          name: logo_id
          schema:
            items:
              type: string
            type: array
          style: form
        - in: query
          name: offset
          schema:
            type: string
        - in: query
          name: limit
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/brand-protection-api_LogoMatch'
          description: OK
        '422':
          $ref: '#/components/responses/brand-protection-api_UNPROCESSABLE_CONTENT'
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Download matches for logo queries by ID
      tags:
        - logo_match
      x-api-token-group:
        - Intel Write
        - Intel Read
  /accounts/{account_id}/brand-protection/logos:
    get:
      description: Return all saved logo queries
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Read all saved logo queries
      tags:
        - logo_match
      x-api-token-group:
        - Intel Write
        - Intel Read
    post:
      description: Return new saved logo queries created from image files
      parameters:
        - in: query
          name: tag
          schema:
            type: string
        - in: query
          name: match_type
          schema:
            type: string
        - in: query
          name: threshold
          schema:
            type: number
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/brand-protection-api_ImageFile'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/brand-protection-api_Logo'
          description: Created
        '422':
          $ref: '#/components/responses/brand-protection-api_UNPROCESSABLE_CONTENT'
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Create new saved logo queries from image files
      tags:
        - logo_match
      x-api-token-group:
        - Intel Write
  /accounts/{account_id}/brand-protection/logos/{logo_id}:
    get:
      description: Return saved logo queries based on ID
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Read saved logo queries by ID
      tags:
        - logo_match
      x-api-token-group:
        - Intel Write
        - Intel Read
    delete:
      description: Return a success message after deleting saved logo queries by ID
      responses:
        '204':
          description: No Content
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Delete saved logo queries by ID
      tags:
        - logo_match
      x-api-token-group:
        - Intel Write
  /accounts/{account_id}/brand-protection/scan-logo:
    post:
      description: Return new logo queries created from image files
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Create new logo queries from image files
      tags:
        - logo_match
      x-api-token-group:
        - Intel Write
  /accounts/{account_id}/brand-protection/scan-page:
    post:
      description: Return new logo queries created from URLs
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Create new logo queries from URLs
      tags:
        - logo_match
      x-api-token-group:
        - Intel Write
  /signed-url:
    get:
      responses:
        default:
          $ref: '#/components/responses/brand-protection-api_DEFAULT_ERROR'
      security:
        - api_token: []
      summary: Internal route for testing signed URLs
      tags:
        - logo_match
components:
  schemas:
    brand-protection-api_ImageFile:
      properties:
        image:
          format: binary
          type: string
      type: object
    brand-protection-api_Logo:
      properties:
        id:
          type: integer
        tag:
          type: string
        upload_path:
          type: string
      type: object
    brand-protection-api_LogoMatch:
      properties:
        matches:
          items:
            additionalProperties: {}
            type: object
          type: array
        total:
          type: integer
      type: object
  responses:
    brand-protection-api_DEFAULT_ERROR:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/brand-protection-api_Error'
      description: Default error response
    brand-protection-api_UNPROCESSABLE_CONTENT:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/brand-protection-api_Error'
      description: Unprocessable Content
