openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/magic/sites/{site_id}/app_configs:
    get:
      description: Lists App Configs associated with a site.
      operationId: magic-site-app-configs-list-app-configs
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - in: path
          name: site_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_app_configs_collection_response'
          description: List App Configs response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: List App Configs response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List App Configs
      tags:
        - Magic Site App Configs
      x-api-token-group:
        - Magic WAN Write
        - Magic WAN Read
        - Magic Transit Read
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    post:
      description: Creates a new App Config for a site
      operationId: magic-site-app-configs-add-app-config
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - in: path
          name: site_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_app_config_add_single_request'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_app_config_single_response'
          description: Create Site App Config response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Create Site App Config response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create a new App Config
      tags:
        - Magic Site App Configs
      x-api-token-group:
        - Magic WAN Write
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/magic/sites/{site_id}/app_configs/{app_config_id}:
    put:
      description: Updates an App Config for a site
      operationId: magic-site-app-configs-update-app-config
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - in: path
          name: site_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - in: path
          name: app_config_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_app_config_update_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_app_config_single_response'
          description: Update Site App Config response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Update Site App Config response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update an App Config
      tags:
        - Magic Site App Configs
      x-api-token-group:
        - Magic WAN Write
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    patch:
      description: Updates an App Config for a site
      operationId: magic-site-app-configs-patch-app-config
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - in: path
          name: site_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - in: path
          name: app_config_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_app_config_update_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_app_config_single_response'
          description: Update Site App Config response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Update Site App Config response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update an App Config
      tags:
        - Magic Site App Configs
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    delete:
      description: Deletes specific App Config associated with a site.
      operationId: magic-site-app-configs-delete-app-config
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - in: path
          name: site_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - in: path
          name: app_config_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_app_config_single_response'
          description: Delete App Config response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Delete App Config response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete App Config
      tags:
        - Magic Site App Configs
      x-api-token-group:
        - Magic WAN Write
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    magic_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/magic_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/magic_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    magic_app_config_add_single_request:
      allOf:
        - oneOf:
            - properties:
                account_app_id:
                  $ref: '#/components/schemas/magic_account_app_id'
              required:
                - account_app_id
              title: Account App
            - properties:
                managed_app_id:
                  $ref: '#/components/schemas/magic_managed_app_id'
              required:
                - managed_app_id
              title: Managed App
        - anyOf:
            - required:
                - breakout
              title: Breakout
            - required:
                - priority
              title: Prioritize
        - properties:
            breakout:
              $ref: '#/components/schemas/magic_app_breakout'
            priority:
              $ref: '#/components/schemas/magic_app_priority'
      type: object
    magic_app_config_single_response:
      allOf:
        - $ref: '#/components/schemas/magic_apps-response-object'
        - properties:
            result:
              $ref: '#/components/schemas/magic_app_config'
    magic_app_config_update_request:
      properties:
        account_app_id:
          $ref: '#/components/schemas/magic_account_app_id'
        breakout:
          $ref: '#/components/schemas/magic_app_breakout'
        managed_app_id:
          $ref: '#/components/schemas/magic_managed_app_id'
        priority:
          $ref: '#/components/schemas/magic_app_priority'
      type: object
    magic_app_configs_collection_response:
      allOf:
        - $ref: '#/components/schemas/magic_apps-response-object'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/magic_app_config'
              type: array
    magic_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
