openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/mnm/rules:
    get:
      description: Lists network monitoring rules for account.
      operationId: magic-network-monitoring-rules-list-rules
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-mnm_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/magic-visibility-mnm_mnm_rules_collection_response
          description: List rules response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/magic-visibility-mnm_mnm_rules_collection_response
                  - $ref: >-
                      #/components/schemas/magic-visibility-mnm_api-response-common-failure
          description: List rules response failure
      security:
        - api_email: []
          api_key: []
      summary: List rules
      tags:
        - Magic Network Monitoring Rules
      x-api-token-group:
        - Magic Network Monitoring Admin
        - Magic Network Monitoring Config Write
        - Magic Network Monitoring Config Read
    post:
      description: >-
        Create network monitoring rules for account. Currently only supports
        creating a single rule per API request.
      operationId: magic-network-monitoring-rules-create-rules
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-mnm_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                automatic_advertisement:
                  $ref: >-
                    #/components/schemas/magic-visibility-mnm_mnm_rule_automatic_advertisement
                bandwidth:
                  $ref: >-
                    #/components/schemas/magic-visibility-mnm_mnm_rule_bandwidth_threshold
                duration:
                  $ref: '#/components/schemas/magic-visibility-mnm_mnm_rule_duration'
                name:
                  $ref: '#/components/schemas/magic-visibility-mnm_mnm_rule_name'
                packet_threshold:
                  $ref: >-
                    #/components/schemas/magic-visibility-mnm_mnm_rule_packet_threshold
                prefixes:
                  $ref: >-
                    #/components/schemas/magic-visibility-mnm_mnm_rule_ip_prefixes
              required:
                - duration
                - name
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/magic-visibility-mnm_mnm_rules_single_response
          description: Create rules response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/magic-visibility-mnm_mnm_rules_single_response
                  - $ref: >-
                      #/components/schemas/magic-visibility-mnm_api-response-common-failure
          description: Create rules response failure
      security:
        - api_email: []
          api_key: []
      summary: Create rules
      tags:
        - Magic Network Monitoring Rules
      x-api-token-group:
        - Magic Network Monitoring Admin
    put:
      description: Update network monitoring rules for account.
      operationId: magic-network-monitoring-rules-update-rules
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-mnm_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                automatic_advertisement:
                  $ref: >-
                    #/components/schemas/magic-visibility-mnm_mnm_rule_automatic_advertisement
                bandwidth:
                  $ref: >-
                    #/components/schemas/magic-visibility-mnm_mnm_rule_bandwidth_threshold
                duration:
                  $ref: '#/components/schemas/magic-visibility-mnm_mnm_rule_duration'
                id:
                  $ref: '#/components/schemas/magic-visibility-mnm_rule_identifier'
                name:
                  $ref: '#/components/schemas/magic-visibility-mnm_mnm_rule_name'
                packet_threshold:
                  $ref: >-
                    #/components/schemas/magic-visibility-mnm_mnm_rule_packet_threshold
                prefixes:
                  $ref: >-
                    #/components/schemas/magic-visibility-mnm_mnm_rule_ip_prefixes
              required:
                - ID
                - duration
                - name
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/magic-visibility-mnm_mnm_rules_single_response
          description: Update rules response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/magic-visibility-mnm_mnm_rules_single_response
                  - $ref: >-
                      #/components/schemas/magic-visibility-mnm_api-response-common-failure
          description: Update rules response failure
      security:
        - api_email: []
          api_key: []
      summary: Update rules
      tags:
        - Magic Network Monitoring Rules
      x-api-token-group:
        - Magic Network Monitoring Admin
        - Magic Network Monitoring Config Write
  /accounts/{account_id}/mnm/rules/{rule_id}:
    get:
      description: List a single network monitoring rule for account.
      operationId: magic-network-monitoring-rules-get-rule
      parameters:
        - in: path
          name: rule_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-mnm_rule_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-mnm_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/magic-visibility-mnm_mnm_rules_single_response
          description: Get rule response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/magic-visibility-mnm_mnm_rules_single_response
                  - $ref: >-
                      #/components/schemas/magic-visibility-mnm_api-response-common-failure
          description: Get rule response failure
      security:
        - api_email: []
          api_key: []
      summary: Get rule
      tags:
        - Magic Network Monitoring Rules
      x-api-token-group:
        - Magic Network Monitoring Admin
        - Magic Network Monitoring Config Write
        - Magic Network Monitoring Config Read
    patch:
      description: Update a network monitoring rule for account.
      operationId: magic-network-monitoring-rules-update-rule
      parameters:
        - in: path
          name: rule_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-mnm_rule_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-mnm_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                automatic_advertisement:
                  $ref: >-
                    #/components/schemas/magic-visibility-mnm_mnm_rule_automatic_advertisement
                bandwidth:
                  $ref: >-
                    #/components/schemas/magic-visibility-mnm_mnm_rule_bandwidth_threshold
                duration:
                  $ref: '#/components/schemas/magic-visibility-mnm_mnm_rule_duration'
                name:
                  $ref: '#/components/schemas/magic-visibility-mnm_mnm_rule_name'
                packet_threshold:
                  $ref: >-
                    #/components/schemas/magic-visibility-mnm_mnm_rule_packet_threshold
                prefixes:
                  $ref: >-
                    #/components/schemas/magic-visibility-mnm_mnm_rule_ip_prefixes
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/magic-visibility-mnm_mnm_rules_single_response
          description: Update rule response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/magic-visibility-mnm_mnm_rules_single_response
                  - $ref: >-
                      #/components/schemas/magic-visibility-mnm_api-response-common-failure
          description: Update rule response failure
      security:
        - api_email: []
          api_key: []
      summary: Update rule
      tags:
        - Magic Network Monitoring Rules
      x-api-token-group:
        - Magic Network Monitoring Admin
        - Magic Network Monitoring Config Write
    delete:
      description: Delete a network monitoring rule for account.
      operationId: magic-network-monitoring-rules-delete-rule
      parameters:
        - in: path
          name: rule_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-mnm_rule_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-mnm_account_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/magic-visibility-mnm_mnm_rules_single_response
          description: Delete rule response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/magic-visibility-mnm_mnm_rules_single_response
                  - $ref: >-
                      #/components/schemas/magic-visibility-mnm_api-response-common-failure
          description: Delete rule response failure
      security:
        - api_email: []
          api_key: []
      summary: Delete rule
      tags:
        - Magic Network Monitoring Rules
      x-api-token-group:
        - Magic Network Monitoring Admin
  /accounts/{account_id}/mnm/rules/{rule_id}/advertisement:
    patch:
      description: Update advertisement for rule.
      operationId: magic-network-monitoring-rules-update-advertisement-for-rule
      parameters:
        - in: path
          name: rule_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-mnm_rule_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-mnm_account_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/magic-visibility-mnm_mnm_rule_advertisement_single_response
          description: Update advertisement for rule response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/magic-visibility-mnm_mnm_rule_advertisement_single_response
                  - $ref: >-
                      #/components/schemas/magic-visibility-mnm_api-response-common-failure
          description: Update advertisement for rule response failure
      security:
        - api_email: []
          api_key: []
      summary: Update advertisement for rule
      tags:
        - Magic Network Monitoring Rules
      x-api-token-group:
        - Magic Network Monitoring Admin
        - Magic Network Monitoring Config Write
components:
  schemas:
    magic-visibility-mnm_account_identifier:
      example: 6f91088a406011ed95aed352566e8d4c
      type: string
      x-auditable: true
    magic-visibility-mnm_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/magic-visibility-mnm_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/magic-visibility-mnm_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    magic-visibility-mnm_mnm_rule_advertisement_single_response:
      allOf:
        - $ref: '#/components/schemas/magic-visibility-mnm_api-response-single'
        - properties:
            result:
              $ref: >-
                #/components/schemas/magic-visibility-mnm_mnm_rule_advertisable_response
          type: object
    magic-visibility-mnm_mnm_rule_automatic_advertisement:
      description: >-
        Toggle on if you would like Cloudflare to automatically advertise the IP
        Prefixes within the rule via Magic Transit when the rule is triggered.
        Only available for users of Magic Transit.
      example: 'false'
      nullable: true
      type: boolean
      x-auditable: true
    magic-visibility-mnm_mnm_rule_bandwidth_threshold:
      description: >-
        The number of bits per second for the rule. When this value is exceeded
        for the set duration, an alert notification is sent. Minimum of 1 and no
        maximum.
      example: 1000
      minimum: 1
      type: number
      x-auditable: true
    magic-visibility-mnm_mnm_rule_duration:
      default: 1m
      description: >-
        The amount of time that the rule threshold must be exceeded to send an
        alert notification. The final value must be equivalent to one of the
        following 8 values ["1m","5m","10m","15m","20m","30m","45m","60m"].
      enum:
        - 1m
        - 5m
        - 10m
        - 15m
        - 20m
        - 30m
        - 45m
        - 60m
      example: 300s
      type: string
      x-auditable: true
    magic-visibility-mnm_mnm_rule_ip_prefixes:
      items:
        $ref: '#/components/schemas/magic-visibility-mnm_mnm_rule_ip_prefix'
      type: array
    magic-visibility-mnm_mnm_rule_name:
      description: >-
        The name of the rule. Must be unique. Supports characters A-Z, a-z, 0-9,
        underscore (_), dash (-), period (.), and tilde (~). You can’t have a
        space in the rule name. Max 256 characters.
      example: my_rule_1
      type: string
      x-auditable: true
    magic-visibility-mnm_mnm_rule_packet_threshold:
      description: >-
        The number of packets per second for the rule. When this value is
        exceeded for the set duration, an alert notification is sent. Minimum of
        1 and no maximum.
      example: 10000
      minimum: 1
      type: number
      x-auditable: true
    magic-visibility-mnm_mnm_rules_collection_response:
      allOf:
        - $ref: '#/components/schemas/magic-visibility-mnm_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/magic-visibility-mnm_mnm_rule'
              nullable: true
              type: array
    magic-visibility-mnm_mnm_rules_single_response:
      allOf:
        - $ref: '#/components/schemas/magic-visibility-mnm_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/magic-visibility-mnm_mnm_rule'
          type: object
    magic-visibility-mnm_rule_identifier:
      description: The id of the rule. Must be unique.
      example: 2890e6fa406311ed9b5a23f70f6fb8cf
      type: string
      x-auditable: true
