openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/pcaps:
    get:
      description: Lists all packet capture requests for an account.
      operationId: magic-pcap-collection-list-packet-capture-requests
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-pcaps_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/magic-visibility-pcaps_pcaps_collection_response
          description: List packet capture requests response
        default:
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: >-
                      #/components/schemas/magic-visibility-pcaps_pcaps_collection_response
                  - $ref: >-
                      #/components/schemas/magic-visibility-pcaps_api-response-common-failure
          description: List packet capture requests response failure
      security:
        - api_email: []
          api_key: []
      summary: List packet capture requests
      tags:
        - Magic PCAP collection
      x-api-token-group:
        - Magic Firewall Packet Captures - Write PCAPs API
        - Magic Firewall Packet Captures - Read PCAPs API
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    post:
      description: Create new PCAP request for account.
      operationId: magic-pcap-collection-create-pcap-request
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-pcaps_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic-visibility-pcaps_pcaps_request_pcap'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/magic-visibility-pcaps_pcaps_single_response
          description: Create PCAP request response
        default:
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: >-
                      #/components/schemas/magic-visibility-pcaps_pcaps_single_response
                  - $ref: >-
                      #/components/schemas/magic-visibility-pcaps_api-response-common-failure
          description: Create PCAP request response failure
      security:
        - api_email: []
          api_key: []
      summary: Create PCAP request
      tags:
        - Magic PCAP collection
      x-api-token-group:
        - Magic Firewall Packet Captures - Write PCAPs API
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/pcaps/ownership:
    get:
      description: List all buckets configured for use with PCAPs API.
      operationId: magic-pcap-collection-list-pca-ps-bucket-ownership
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-pcaps_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/magic-visibility-pcaps_pcaps_ownership_collection
          description: List PCAPs Bucket Ownership response
        default:
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: >-
                      #/components/schemas/magic-visibility-pcaps_pcaps_ownership_collection
                  - $ref: >-
                      #/components/schemas/magic-visibility-pcaps_api-response-common-failure
          description: List PCAPs Bucket Ownership response failure
      security:
        - api_email: []
          api_key: []
      summary: List PCAPs Bucket Ownership
      tags:
        - Magic PCAP collection
      x-api-token-group:
        - Magic Firewall Packet Captures - Write PCAPs API
        - Magic Firewall Packet Captures - Read PCAPs API
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    post:
      description: Adds an AWS or GCP bucket to use with full packet captures.
      operationId: magic-pcap-collection-add-buckets-for-full-packet-captures
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-pcaps_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/magic-visibility-pcaps_pcaps_ownership_request
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/magic-visibility-pcaps_pcaps_ownership_single_response
          description: Add buckets for full packet captures response
        default:
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: >-
                      #/components/schemas/magic-visibility-pcaps_pcaps_ownership_single_response
                  - $ref: >-
                      #/components/schemas/magic-visibility-pcaps_api-response-common-failure
          description: Add buckets for full packet captures response failure
      security:
        - api_email: []
          api_key: []
      summary: Add buckets for full packet captures
      tags:
        - Magic PCAP collection
      x-api-token-group:
        - Magic Firewall Packet Captures - Write PCAPs API
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/pcaps/ownership/validate:
    post:
      description: Validates buckets added to the packet captures API.
      operationId: magic-pcap-collection-validate-buckets-for-full-packet-captures
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-pcaps_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/magic-visibility-pcaps_pcaps_ownership_validate_request
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/magic-visibility-pcaps_pcaps_ownership_single_response
          description: Validate buckets for full packet captures response
        default:
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: >-
                      #/components/schemas/magic-visibility-pcaps_pcaps_ownership_single_response
                  - $ref: >-
                      #/components/schemas/magic-visibility-pcaps_api-response-common-failure
          description: Validate buckets for full packet captures response failure
      security:
        - api_email: []
          api_key: []
      summary: Validate buckets for full packet captures
      tags:
        - Magic PCAP collection
      x-api-token-group:
        - Magic Firewall Packet Captures - Write PCAPs API
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/pcaps/ownership/{ownership_id}:
    delete:
      description: Deletes buckets added to the packet captures API.
      operationId: magic-pcap-collection-delete-buckets-for-full-packet-captures
      parameters:
        - in: path
          name: ownership_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-pcaps_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-pcaps_identifier'
      responses:
        '204':
          description: Delete buckets for full packet captures response
        default:
          content:
            application/json: {}
          description: Delete buckets for full packet captures response failure
      security:
        - api_email: []
          api_key: []
      summary: Delete buckets for full packet captures
      tags:
        - Magic PCAP collection
      x-api-token-group:
        - Magic Firewall Packet Captures - Write PCAPs API
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/pcaps/{pcap_id}:
    get:
      description: Get information for a PCAP request by id.
      operationId: magic-pcap-collection-get-pcap-request
      parameters:
        - in: path
          name: pcap_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-pcaps_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-pcaps_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/magic-visibility-pcaps_pcaps_single_response
          description: Get PCAP request response
        default:
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: >-
                      #/components/schemas/magic-visibility-pcaps_pcaps_single_response
                  - $ref: >-
                      #/components/schemas/magic-visibility-pcaps_api-response-common-failure
          description: Get PCAP request response failure
      security:
        - api_email: []
          api_key: []
      summary: Get PCAP request
      tags:
        - Magic PCAP collection
      x-api-token-group:
        - Magic Firewall Packet Captures - Write PCAPs API
        - Magic Firewall Packet Captures - Read PCAPs API
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/pcaps/{pcap_id}/download:
    get:
      description: Download PCAP information into a file. Response is a binary PCAP file.
      operationId: magic-pcap-collection-download-simple-pcap
      parameters:
        - in: path
          name: pcap_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-pcaps_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-pcaps_identifier'
      responses:
        '200':
          content:
            application/vnd.tcpdump.pcap: {}
          description: Download Simple PCAP response
        default:
          content:
            application/json: {}
          description: Download Simple PCAP response failure
      security:
        - api_email: []
          api_key: []
      summary: Download Simple PCAP
      tags:
        - Magic PCAP collection
      x-api-token-group:
        - Magic Firewall Packet Captures - Write PCAPs API
        - Magic Firewall Packet Captures - Read PCAPs API
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/pcaps/{pcap_id}/stop:
    put:
      description: Stop full PCAP
      operationId: magic-pcap-collection-stop-full-pcap
      parameters:
        - in: path
          name: pcap_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-pcaps_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic-visibility-pcaps_identifier'
      responses:
        '204':
          description: Stop full PCAP response
        default:
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/magic-visibility-pcaps_api-response-common-failure
          description: Stop full PCAP response failure
      security:
        - api_email: []
          api_key: []
      summary: Stop full PCAP
      tags:
        - Magic PCAP collection
      x-api-token-group:
        - Magic Firewall Packet Captures - Write PCAPs API
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    magic-visibility-pcaps_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/magic-visibility-pcaps_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/magic-visibility-pcaps_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    magic-visibility-pcaps_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    magic-visibility-pcaps_pcaps_collection_response:
      allOf:
        - $ref: '#/components/schemas/magic-visibility-pcaps_api-response-collection'
        - properties:
            result:
              items:
                anyOf:
                  - $ref: >-
                      #/components/schemas/magic-visibility-pcaps_pcaps_response_simple
                  - $ref: >-
                      #/components/schemas/magic-visibility-pcaps_pcaps_response_full
              type: array
    magic-visibility-pcaps_pcaps_ownership_collection:
      allOf:
        - $ref: '#/components/schemas/magic-visibility-pcaps_api-response-collection'
        - properties:
            result:
              items:
                $ref: >-
                  #/components/schemas/magic-visibility-pcaps_pcaps_ownership_response
              nullable: true
              type: array
    magic-visibility-pcaps_pcaps_ownership_request:
      properties:
        destination_conf:
          $ref: '#/components/schemas/magic-visibility-pcaps_pcaps_destination_conf'
      required:
        - destination_conf
      type: object
    magic-visibility-pcaps_pcaps_ownership_single_response:
      allOf:
        - $ref: '#/components/schemas/magic-visibility-pcaps_api-response-common'
        - properties:
            result:
              $ref: >-
                #/components/schemas/magic-visibility-pcaps_pcaps_ownership_response
    magic-visibility-pcaps_pcaps_ownership_validate_request:
      properties:
        destination_conf:
          $ref: '#/components/schemas/magic-visibility-pcaps_pcaps_destination_conf'
        ownership_challenge:
          $ref: >-
            #/components/schemas/magic-visibility-pcaps_pcaps_ownership_challenge
      required:
        - destination_conf
        - ownership_challenge
      type: object
    magic-visibility-pcaps_pcaps_request_pcap:
      anyOf:
        - $ref: '#/components/schemas/magic-visibility-pcaps_pcaps_request_simple'
        - $ref: '#/components/schemas/magic-visibility-pcaps_pcaps_request_full'
    magic-visibility-pcaps_pcaps_single_response:
      allOf:
        - $ref: '#/components/schemas/magic-visibility-pcaps_api-response-single'
        - properties:
            result:
              anyOf:
                - $ref: >-
                    #/components/schemas/magic-visibility-pcaps_pcaps_response_simple
                - $ref: >-
                    #/components/schemas/magic-visibility-pcaps_pcaps_response_full
