openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/magic/ipsec_tunnels:
    get:
      description: Lists IPsec tunnels associated with an account.
      operationId: magic-ipsec-tunnels-list-ipsec-tunnels
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - description: >-
            If true, the health check target in the response body will be
            presented using the new object format. Defaults to false.
          in: header
          name: x-magic-new-hc-target
          schema:
            type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_schemas-tunnels_collection_response'
          description: List IPsec tunnels response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/magic_schemas-tunnels_collection_response
                  - $ref: '#/components/schemas/magic_api-response-common-failure'
          description: List IPsec tunnels response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List IPsec tunnels
      tags:
        - Magic IPsec tunnels
      x-api-token-group:
        - Magic WAN Write
        - Magic WAN Read
        - Magic Transit Read
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    post:
      description: >-
        Creates a new IPsec tunnel associated with an account. Use
        `?validate_only=true` as an optional query parameter to only run
        validation without persisting changes.
      operationId: magic-ipsec-tunnels-create-ipsec-tunnels
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - description: >-
            If true, the health check target in the request and response bodies
            will be presented using the new object format. Defaults to false.
          in: header
          name: x-magic-new-hc-target
          schema:
            type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_ipsec_tunnel_add_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/magic_schemas-create_ipsec_tunnel_response
          description: Create IPsec tunnels response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/magic_schemas-create_ipsec_tunnel_response
                  - $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Create IPsec tunnels response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create an IPsec tunnel
      tags:
        - Magic IPsec tunnels
      x-api-token-group:
        - Magic WAN Write
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    put:
      description: >-
        Update multiple IPsec tunnels associated with an account. Use
        `?validate_only=true` as an optional query parameter to only run
        validation without persisting changes.
      operationId: magic-ipsec-tunnels-update-multiple-ipsec-tunnels
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - description: >-
            If true, the health check target in the request and response bodies
            will be presented using the new object format. Defaults to false.
          in: header
          name: x-magic-new-hc-target
          schema:
            type: boolean
      requestBody:
        content:
          application/json:
            schema:
              required:
                - id
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/magic_schemas-modified_tunnels_collection_response
          description: Update multiple IPsec tunnels response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/magic_schemas-modified_tunnels_collection_response
                  - $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Update multiple IPsec tunnels response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update multiple IPsec tunnels
      tags:
        - Magic IPsec tunnels
      x-api-token-group:
        - Magic WAN Write
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/magic/ipsec_tunnels/{ipsec_tunnel_id}:
    get:
      description: Lists details for a specific IPsec tunnel.
      operationId: magic-ipsec-tunnels-list-ipsec-tunnel-details
      parameters:
        - in: path
          name: ipsec_tunnel_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - description: >-
            If true, the health check target in the response body will be
            presented using the new object format. Defaults to false.
          in: header
          name: x-magic-new-hc-target
          schema:
            type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_schemas-tunnel_single_response'
          description: List IPsec tunnel details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/magic_schemas-tunnel_single_response'
                  - $ref: '#/components/schemas/magic_api-response-common-failure'
          description: List IPsec tunnel details response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List IPsec tunnel details
      tags:
        - Magic IPsec tunnels
      x-api-token-group:
        - Magic WAN Write
        - Magic WAN Read
        - Magic Transit Read
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    put:
      description: >-
        Updates a specific IPsec tunnel associated with an account. Use
        `?validate_only=true` as an optional query parameter to only run
        validation without persisting changes.
      operationId: magic-ipsec-tunnels-update-ipsec-tunnel
      parameters:
        - in: path
          name: ipsec_tunnel_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - description: >-
            If true, the health check target in the request and response bodies
            will be presented using the new object format. Defaults to false.
          in: header
          name: x-magic-new-hc-target
          schema:
            type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_ipsec_tunnel_add_single_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_schemas-tunnel_modified_response'
          description: Update IPsec Tunnel response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/magic_schemas-tunnel_modified_response
                  - $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Update IPsec Tunnel response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update IPsec Tunnel
      tags:
        - Magic IPsec tunnels
      x-api-token-group:
        - Magic WAN Write
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    delete:
      description: >-
        Disables and removes a specific static IPsec Tunnel associated with an
        account. Use `?validate_only=true` as an optional query parameter to
        only run validation without persisting changes.
      operationId: magic-ipsec-tunnels-delete-ipsec-tunnel
      parameters:
        - in: path
          name: ipsec_tunnel_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - description: >-
            If true, the health check target in the response body will be
            presented using the new object format. Defaults to false.
          in: header
          name: x-magic-new-hc-target
          schema:
            type: boolean
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_schemas-tunnel_deleted_response'
          description: Delete IPsec Tunnel response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/magic_schemas-tunnel_deleted_response'
                  - $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Delete IPsec Tunnel response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete IPsec Tunnel
      tags:
        - Magic IPsec tunnels
      x-api-token-group:
        - Magic WAN Write
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/magic/ipsec_tunnels/{ipsec_tunnel_id}/psk_generate:
    post:
      description: >-
        Generates a Pre Shared Key for a specific IPsec tunnel used in the IKE
        session. Use `?validate_only=true` as an optional query parameter to
        only run validation without persisting changes. After a PSK is
        generated, the PSK is immediately persisted to Cloudflare's edge and
        cannot be retrieved later. Note the PSK in a safe place.
      operationId: magic-ipsec-tunnels-generate-pre-shared-key-(-psk)-for-ipsec-tunnels
      parameters:
        - in: path
          name: ipsec_tunnel_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_psk_generation_response'
          description: Generate Pre Shared Key (PSK) for IPsec tunnels response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/magic_psk_generation_response'
                  - $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Generate Pre Shared Key (PSK) for IPsec tunnels response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Generate Pre Shared Key (PSK) for IPsec tunnels
      tags:
        - Magic IPsec tunnels
      x-api-token-group:
        - Magic WAN Write
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    magic_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/magic_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/magic_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    magic_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    magic_ipsec_tunnel_add_request:
      allOf:
        - $ref: '#/components/schemas/magic_ipsec_tunnel_add_single_request'
    magic_ipsec_tunnel_add_single_request:
      properties:
        cloudflare_endpoint:
          $ref: '#/components/schemas/magic_cloudflare_ipsec_endpoint'
        customer_endpoint:
          $ref: '#/components/schemas/magic_customer_ipsec_endpoint'
        description:
          $ref: '#/components/schemas/magic_components-schemas-description'
        health_check:
          $ref: '#/components/schemas/magic_tunnel_health_check'
        interface_address:
          $ref: '#/components/schemas/magic_interface_address'
        interface_address6:
          $ref: '#/components/schemas/magic_interface_address6'
        name:
          $ref: '#/components/schemas/magic_ipsec_tunnel_name'
        psk:
          $ref: '#/components/schemas/magic_psk'
        replay_protection:
          $ref: '#/components/schemas/magic_replay_protection'
      required:
        - name
        - cloudflare_endpoint
        - interface_address
      type: object
    magic_psk_generation_response:
      allOf:
        - $ref: '#/components/schemas/magic_api-response-single'
        - properties:
            result:
              properties:
                ipsec_tunnel_id:
                  $ref: '#/components/schemas/magic_identifier'
                psk:
                  $ref: '#/components/schemas/magic_psk'
                psk_metadata:
                  $ref: '#/components/schemas/magic_psk_metadata'
    magic_schemas-create_ipsec_tunnel_response:
      allOf:
        - $ref: '#/components/schemas/magic_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/magic_ipsec-tunnel'
    magic_schemas-modified_tunnels_collection_response:
      allOf:
        - $ref: '#/components/schemas/magic_api-response-single'
        - properties:
            result:
              properties:
                modified:
                  example: true
                  type: boolean
                modified_ipsec_tunnels:
                  items:
                    $ref: '#/components/schemas/magic_ipsec-tunnel'
                  type: array
    magic_schemas-tunnel_deleted_response:
      allOf:
        - $ref: '#/components/schemas/magic_api-response-single'
        - properties:
            result:
              properties:
                deleted:
                  example: true
                  type: boolean
                deleted_ipsec_tunnel:
                  $ref: '#/components/schemas/magic_ipsec-tunnel'
              type: object
    magic_schemas-tunnel_modified_response:
      allOf:
        - $ref: '#/components/schemas/magic_api-response-single'
        - properties:
            result:
              properties:
                modified:
                  example: true
                  type: boolean
                modified_ipsec_tunnel:
                  $ref: '#/components/schemas/magic_ipsec-tunnel'
              type: object
    magic_schemas-tunnel_single_response:
      allOf:
        - $ref: '#/components/schemas/magic_api-response-single'
        - properties:
            result:
              properties:
                ipsec_tunnel:
                  $ref: '#/components/schemas/magic_ipsec-tunnel'
              type: object
    magic_schemas-tunnels_collection_response:
      allOf:
        - $ref: '#/components/schemas/magic_api-response-single'
        - properties:
            result:
              properties:
                ipsec_tunnels:
                  items:
                    $ref: '#/components/schemas/magic_ipsec-tunnel'
                  type: array
