openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/magic/gre_tunnels:
    get:
      description: Lists GRE tunnels associated with an account.
      operationId: magic-gre-tunnels-list-gre-tunnels
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - description: >-
            If true, the health check target in the response body will be
            presented using the new object format. Defaults to false.
          in: header
          name: x-magic-new-hc-target
          schema:
            type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_tunnels_collection_response'
          description: List GRE tunnels response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/magic_tunnels_collection_response'
                  - $ref: '#/components/schemas/magic_api-response-common-failure'
          description: List GRE tunnels response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List GRE tunnels
      tags:
        - Magic GRE tunnels
      x-api-token-group:
        - Magic WAN Write
        - Magic WAN Read
        - Magic Transit Read
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    post:
      description: >-
        Creates a new GRE tunnel. Use `?validate_only=true` as an optional query
        parameter to only run validation without persisting changes.
      operationId: magic-gre-tunnels-create-gre-tunnels
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - description: >-
            If true, the health check target in the request and response bodies
            will be presented using the new object format. Defaults to false.
          in: header
          name: x-magic-new-hc-target
          schema:
            type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_create_gre_tunnel_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_create_gre_tunnel_response'
          description: Create GRE tunnels response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/magic_tunnels_collection_response'
                  - $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Create GRE tunnels response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create a GRE tunnel
      tags:
        - Magic GRE tunnels
      x-api-token-group:
        - Magic WAN Write
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    put:
      description: >-
        Updates multiple GRE tunnels. Use `?validate_only=true` as an optional
        query parameter to only run validation without persisting changes.
      operationId: magic-gre-tunnels-update-multiple-gre-tunnels
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - description: >-
            If true, the health check target in the request and response bodies
            will be presented using the new object format. Defaults to false.
          in: header
          name: x-magic-new-hc-target
          schema:
            type: boolean
      requestBody:
        content:
          application/json:
            schema:
              required:
                - id
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/magic_modified_tunnels_collection_response
          description: Update multiple GRE tunnels response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/magic_modified_tunnels_collection_response
                  - $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Update multiple GRE tunnels response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update multiple GRE tunnels
      tags:
        - Magic GRE tunnels
      x-api-token-group:
        - Magic WAN Write
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/magic/gre_tunnels/{gre_tunnel_id}:
    get:
      description: Lists informtion for a specific GRE tunnel.
      operationId: magic-gre-tunnels-list-gre-tunnel-details
      parameters:
        - in: path
          name: gre_tunnel_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - description: >-
            If true, the health check target in the response body will be
            presented using the new object format. Defaults to false.
          in: header
          name: x-magic-new-hc-target
          schema:
            type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_tunnel_single_response'
          description: List GRE Tunnel Details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/magic_tunnel_single_response'
                  - $ref: '#/components/schemas/magic_api-response-common-failure'
          description: List GRE Tunnel Details response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List GRE Tunnel Details
      tags:
        - Magic GRE tunnels
      x-api-token-group:
        - Magic WAN Write
        - Magic WAN Read
        - Magic Transit Read
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    put:
      description: >-
        Updates a specific GRE tunnel. Use `?validate_only=true` as an optional
        query parameter to only run validation without persisting changes.
      operationId: magic-gre-tunnels-update-gre-tunnel
      parameters:
        - in: path
          name: gre_tunnel_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - description: >-
            If true, the health check target in the request and response bodies
            will be presented using the new object format. Defaults to false.
          in: header
          name: x-magic-new-hc-target
          schema:
            type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_gre_tunnel_update_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_tunnel_modified_response'
          description: Update GRE Tunnel response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/magic_tunnel_modified_response'
                  - $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Update GRE Tunnel response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update GRE Tunnel
      tags:
        - Magic GRE tunnels
      x-api-token-group:
        - Magic WAN Write
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    delete:
      description: >-
        Disables and removes a specific static GRE tunnel. Use
        `?validate_only=true` as an optional query parameter to only run
        validation without persisting changes.
      operationId: magic-gre-tunnels-delete-gre-tunnel
      parameters:
        - in: path
          name: gre_tunnel_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - description: >-
            If true, the health check target in the response body will be
            presented using the new object format. Defaults to false.
          in: header
          name: x-magic-new-hc-target
          schema:
            type: boolean
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_tunnel_deleted_response'
          description: Delete GRE Tunnel response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/magic_tunnel_deleted_response'
                  - $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Delete GRE Tunnel response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete GRE Tunnel
      tags:
        - Magic GRE tunnels
      x-api-token-group:
        - Magic WAN Write
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    magic_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/magic_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/magic_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    magic_create_gre_tunnel_request:
      properties:
        cloudflare_gre_endpoint:
          $ref: '#/components/schemas/magic_cloudflare_gre_endpoint'
        customer_gre_endpoint:
          $ref: '#/components/schemas/magic_customer_gre_endpoint'
        description:
          $ref: '#/components/schemas/magic_schemas-description'
        health_check:
          $ref: '#/components/schemas/magic_tunnel_health_check'
        interface_address:
          $ref: '#/components/schemas/magic_interface_address'
        interface_address6:
          $ref: '#/components/schemas/magic_interface_address6'
        mtu:
          $ref: '#/components/schemas/magic_mtu'
        name:
          $ref: '#/components/schemas/magic_gre_tunnel_name'
        ttl:
          $ref: '#/components/schemas/magic_ttl'
      required:
        - name
        - customer_gre_endpoint
        - cloudflare_gre_endpoint
        - interface_address
      type: object
    magic_create_gre_tunnel_response:
      allOf:
        - $ref: '#/components/schemas/magic_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/magic_gre-tunnel'
    magic_gre_tunnel_update_request:
      allOf:
        - $ref: '#/components/schemas/magic_gre_tunnel_add_single_request'
    magic_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    magic_modified_tunnels_collection_response:
      allOf:
        - $ref: '#/components/schemas/magic_api-response-single'
        - properties:
            result:
              properties:
                modified:
                  example: true
                  type: boolean
                modified_gre_tunnels:
                  items:
                    $ref: '#/components/schemas/magic_gre-tunnel'
                  type: array
    magic_tunnel_deleted_response:
      allOf:
        - $ref: '#/components/schemas/magic_api-response-single'
        - properties:
            result:
              properties:
                deleted:
                  example: true
                  type: boolean
                deleted_gre_tunnel:
                  $ref: '#/components/schemas/magic_gre-tunnel'
              type: object
    magic_tunnel_modified_response:
      allOf:
        - $ref: '#/components/schemas/magic_api-response-single'
        - properties:
            result:
              properties:
                modified:
                  example: true
                  type: boolean
                modified_gre_tunnel:
                  $ref: '#/components/schemas/magic_gre-tunnel'
              type: object
    magic_tunnel_single_response:
      allOf:
        - $ref: '#/components/schemas/magic_api-response-single'
        - properties:
            result:
              properties:
                gre_tunnel:
                  $ref: '#/components/schemas/magic_gre-tunnel'
              type: object
    magic_tunnels_collection_response:
      allOf:
        - $ref: '#/components/schemas/magic_api-response-single'
        - properties:
            result:
              properties:
                gre_tunnels:
                  items:
                    $ref: '#/components/schemas/magic_gre-tunnel'
                  type: array
