openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/magic/apps:
    get:
      description: Lists Apps associated with an account.
      operationId: magic-account-apps-list-apps
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_apps_collection_response'
          description: List Apps response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: List Apps response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List Apps
      tags:
        - Magic Account Apps
      x-api-token-group:
        - Magic WAN Write
        - Magic WAN Read
        - Magic Transit Read
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    post:
      description: Creates a new App for an account
      operationId: magic-account-apps-add-app
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_app_add_single_request'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_app_single_response'
          description: Create Account App response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Create Account App response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create a new App
      tags:
        - Magic Account Apps
      x-api-token-group:
        - Magic WAN Write
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/magic/apps/{account_app_id}:
    put:
      description: Updates an Account App
      operationId: magic-account-apps-update-app
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - in: path
          name: account_app_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_app_update_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_app_single_response'
          description: Update App response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Update App response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update an App
      tags:
        - Magic Account Apps
      x-api-token-group:
        - Magic WAN Write
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    patch:
      description: Updates an Account App
      operationId: magic-account-apps-patch-app
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - in: path
          name: account_app_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_app_update_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_app_single_response'
          description: Update App response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Update App response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update an App
      tags:
        - Magic Account Apps
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    delete:
      description: Deletes specific Account App.
      operationId: magic-account-apps-delete-app
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
        - in: path
          name: account_app_id
          required: true
          schema:
            $ref: '#/components/schemas/magic_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_app_single_response'
          description: Delete App response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Delete App response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete Account App
      tags:
        - Magic Account Apps
      x-api-token-group:
        - Magic WAN Write
        - Magic Transit Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    magic_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/magic_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/magic_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    magic_app_add_single_request:
      anyOf:
        - required:
            - hostnames
          title: Hostnames
        - required:
            - ip_subnets
          title: Subnets
      properties:
        hostnames:
          $ref: '#/components/schemas/magic_app_hostnames'
        ip_subnets:
          $ref: '#/components/schemas/magic_app_subnets'
        name:
          $ref: '#/components/schemas/magic_app_name'
        type:
          $ref: '#/components/schemas/magic_app_type'
      required:
        - name
        - type
      type: object
    magic_app_single_response:
      allOf:
        - $ref: '#/components/schemas/magic_apps-response-object'
        - properties:
            result:
              $ref: '#/components/schemas/magic_account_app'
    magic_app_update_request:
      anyOf:
        - required:
            - name
          title: Update App Name
        - required:
            - type
          title: Update App Type
        - required:
            - hostnames
          title: Update App Hostnames
        - required:
            - ip_subnets
          title: Update App Subnets
      properties:
        hostnames:
          $ref: '#/components/schemas/magic_app_hostnames'
        ip_subnets:
          $ref: '#/components/schemas/magic_app_subnets'
        name:
          $ref: '#/components/schemas/magic_app_name'
        type:
          $ref: '#/components/schemas/magic_app_type'
      type: object
    magic_apps_collection_response:
      allOf:
        - $ref: '#/components/schemas/magic_apps-response-array'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/magic_app'
              type: array
    magic_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
