openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/alerting/v3/destinations/eligible:
    get:
      description: >-
        Get a list of all delivery mechanism types for which an account is
        eligible.
      operationId: notification-mechanism-eligibility-get-delivery-mechanism-eligibility
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/aaa_account-id'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/aaa_schemas-response_collection'
          description: Get delivery mechanism eligibility response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/aaa_schemas-response_collection'
                  - $ref: >-
                      #/components/schemas/aaa_components-schemas-api-response-common-failure
          description: Get delivery mechanism eligibility response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get delivery mechanism eligibility
      tags:
        - Notification Mechanism Eligibility
components:
  schemas:
    aaa_account-id:
      description: The account id
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
    aaa_components-schemas-api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/aaa_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/aaa_messages'
          example: []
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
      type: object
    aaa_schemas-response_collection:
      allOf:
        - $ref: '#/components/schemas/aaa_api-response-collection'
        - properties:
            result:
              additionalProperties:
                items:
                  $ref: '#/components/schemas/aaa_eligibility'
                type: array
              example:
                email:
                  eligible: true
                  ready: true
                  type: email
              type: object
