openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/alerting/v3/destinations/webhooks:
    get:
      description: Gets a list of all configured webhook destinations.
      operationId: notification-webhooks-list-webhooks
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/aaa_account-id'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/aaa_webhooks_components-schemas-response_collection
          description: List webhooks response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/aaa_webhooks_components-schemas-response_collection
                  - $ref: >-
                      #/components/schemas/aaa_components-schemas-api-response-common-failure
          description: List webhooks response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: List webhooks
      tags:
        - Notification webhooks
      x-api-token-group:
        - 'Zero Trust: PII Read'
        - Notifications Write
        - Notifications Read
        - Account Settings Write
        - Account Settings Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: true
    post:
      description: Creates a new webhook destination.
      operationId: notification-webhooks-create-a-webhook
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/aaa_account-id'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  $ref: '#/components/schemas/aaa_components-schemas-name'
                secret:
                  $ref: '#/components/schemas/aaa_secret'
                url:
                  $ref: '#/components/schemas/aaa_url'
              required:
                - name
                - url
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/aaa_id_response'
          description: Create a webhook response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/aaa_id_response'
                  - $ref: >-
                      #/components/schemas/aaa_components-schemas-api-response-common-failure
          description: Create a webhook response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Create a webhook
      tags:
        - Notification webhooks
      x-api-token-group:
        - Notifications Write
        - Account Settings Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: true
  /accounts/{account_id}/alerting/v3/destinations/webhooks/{webhook_id}:
    get:
      description: Get details for a single webhooks destination.
      operationId: notification-webhooks-get-a-webhook
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/aaa_account-id'
        - in: path
          name: webhook_id
          required: true
          schema:
            $ref: '#/components/schemas/aaa_webhook-id'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/aaa_schemas-single_response'
          description: Get a webhook response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/aaa_schemas-single_response'
                  - $ref: >-
                      #/components/schemas/aaa_components-schemas-api-response-common-failure
          description: Get a webhook response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get a webhook
      tags:
        - Notification webhooks
      x-api-token-group:
        - 'Zero Trust: PII Read'
        - Notifications Write
        - Notifications Read
        - Account Settings Write
        - Account Settings Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: true
    put:
      description: Update a webhook destination.
      operationId: notification-webhooks-update-a-webhook
      parameters:
        - in: path
          name: webhook_id
          required: true
          schema:
            $ref: '#/components/schemas/aaa_webhook-id'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/aaa_account-id'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  $ref: '#/components/schemas/aaa_components-schemas-name'
                secret:
                  $ref: '#/components/schemas/aaa_secret'
                url:
                  $ref: '#/components/schemas/aaa_url'
              required:
                - name
                - url
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/aaa_id_response'
          description: Update a webhook response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/aaa_id_response'
                  - $ref: >-
                      #/components/schemas/aaa_components-schemas-api-response-common-failure
          description: Update a webhook response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Update a webhook
      tags:
        - Notification webhooks
      x-api-token-group:
        - Notifications Write
        - Account Settings Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: true
    delete:
      description: Delete a configured webhook destination.
      operationId: notification-webhooks-delete-a-webhook
      parameters:
        - in: path
          name: webhook_id
          required: true
          schema:
            $ref: '#/components/schemas/aaa_webhook-id'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/aaa_account-id'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/aaa_api-response-collection'
          description: Delete a webhook response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/aaa_api-response-collection'
                  - $ref: >-
                      #/components/schemas/aaa_components-schemas-api-response-common-failure
          description: Delete a webhook response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Delete a webhook
      tags:
        - Notification webhooks
      x-api-token-group:
        - Notifications Write
        - Account Settings Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: true
components:
  schemas:
    aaa_account-id:
      description: The account id
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
    aaa_api-response-collection:
      allOf:
        - $ref: '#/components/schemas/aaa_api-response-common'
        - properties:
            result_info:
              $ref: '#/components/schemas/aaa_schemas-result_info'
      type: object
    aaa_components-schemas-api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/aaa_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/aaa_messages'
          example: []
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
      type: object
    aaa_components-schemas-name:
      description: >-
        The name of the webhook destination. This will be included in the
        request body when you receive a webhook notification.
      example: Slack Webhook
      type: string
      x-auditable: true
    aaa_id_response:
      allOf:
        - $ref: '#/components/schemas/aaa_api-response-single'
        - properties:
            result:
              properties:
                id:
                  $ref: '#/components/schemas/aaa_uuid'
              type: object
    aaa_schemas-single_response:
      allOf:
        - $ref: '#/components/schemas/aaa_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/aaa_webhooks'
    aaa_secret:
      description: >-
        Optional secret that will be passed in the `cf-webhook-auth` header when
        dispatching generic webhook notifications or formatted for supported
        destinations. Secrets are not returned in any API response body.
      type: string
      writeOnly: true
      x-sensitive: true
    aaa_url:
      description: The POST endpoint to call when dispatching a notification.
      example: https://hooks.slack.com/services/Ds3fdBFbV/456464Gdd
      type: string
    aaa_webhook-id:
      description: The unique identifier of a webhook
      example: b115d5ec-15c6-41ee-8b76-92c449b5227b
      maxLength: 36
      type: string
      x-auditable: true
    aaa_webhooks_components-schemas-response_collection:
      allOf:
        - $ref: '#/components/schemas/aaa_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/aaa_webhooks'
              type: array
