openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/alerting/v3/history:
    get:
      description: >-
        Gets a list of history records for notifications sent to an account. The
        records are displayed for last `x` number of days based on the zone plan
        (free = 30, pro = 30, biz = 30, ent = 90).
      operationId: notification-history-list-history
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/aaa_account-id'
        - in: query
          name: per_page
          schema:
            $ref: '#/components/schemas/aaa_per_page'
        - in: query
          name: before
          schema:
            $ref: '#/components/schemas/aaa_before'
        - in: query
          name: page
          schema:
            default: 1
            description: Page number of paginated results.
            minimum: 1
            type: number
        - in: query
          name: since
          schema:
            description: >-
              Limit the returned results to history records newer than the
              specified date. This must be a timestamp that conforms to RFC3339.
            example: '2022-05-19T20:29:58.679897Z'
            format: date-time
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/aaa_history_components-schemas-response_collection
          description: List History response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/aaa_history_components-schemas-response_collection
                  - $ref: >-
                      #/components/schemas/aaa_components-schemas-api-response-common-failure
          description: List History response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: List History
      tags:
        - Notification History
      x-api-token-group:
        - 'Zero Trust: PII Read'
        - Notifications Write
        - Notifications Read
        - Account Settings Write
        - Account Settings Read
components:
  schemas:
    aaa_account-id:
      description: The account id
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
    aaa_before:
      description: >-
        Limit the returned results to history records older than the specified
        date. This must be a timestamp that conforms to RFC3339.
      example: '2022-05-20T20:29:58.679897Z'
      format: date-time
      type: string
    aaa_components-schemas-api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/aaa_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/aaa_messages'
          example: []
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
      type: object
    aaa_history_components-schemas-response_collection:
      allOf:
        - $ref: '#/components/schemas/aaa_api-response-collection'
        - properties:
            result:
              example:
                - alert_body:
                    data:
                      custom_csr_id: ''
                      expires_on: null
                      hosts: []
                      id: '11111111111'
                      issuer: ''
                      method: txt
                      serial_number: ''
                      settings: null
                      signature: ''
                      status: ''
                      type: ''
                      uploaded_on: null
                      validation_errors: []
                      validation_records:
                        - cname: ''
                          cname_target: ''
                          emails: []
                          http_body: ''
                          http_url: ''
                          txt_name: _acme-challenge.example.com
                          txt_value: '11111111111'
                    metadata:
                      account: null
                      event:
                        created_at: null
                        id: ''
                        type: ssl.certificate.validation.failed
                      zone:
                        id: '11111111111'
                  alert_type: universal_ssl_event_type
                  description: >-
                    Universal Certificate validation status, issuance, renewal,
                    and expiration notices.
                  id: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
                  mechanism: test@example.com
                  mechanism_type: email
                  name: SSL Notification Event Policy
                  policy_id: 35040955-3102-4710-938c-0f4eaf736e25
                  sent: '2021-10-08T17:52:17.571336Z'
              items:
                $ref: '#/components/schemas/aaa_history'
              type: array
            result_info:
              example:
                count: 1
                page: 1
                per_page: 20
              type: object
    aaa_per_page:
      default: 25
      description: Number of items per page.
      maximum: 1000
      minimum: 5
      type: number
