openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/alerting/v3/destinations/pagerduty:
    get:
      description: Get a list of all configured PagerDuty services.
      operationId: notification-destinations-with-pager-duty-list-pager-duty-services
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/aaa_account-id'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/aaa_components-schemas-response_collection
          description: List PagerDuty services response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/aaa_components-schemas-response_collection
                  - $ref: >-
                      #/components/schemas/aaa_components-schemas-api-response-common-failure
          description: List PagerDuty services response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: List PagerDuty services
      tags:
        - Notification destinations with PagerDuty
      x-api-token-group:
        - 'Zero Trust: PII Read'
        - Notifications Write
        - Notifications Read
        - Account Settings Write
        - Account Settings Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: false
    delete:
      description: Deletes all the PagerDuty Services connected to the account.
      operationId: notification-destinations-with-pager-duty-delete-pager-duty-services
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/aaa_account-id'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/aaa_api-response-collection'
          description: Delete PagerDuty Services response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/aaa_api-response-collection'
                  - $ref: >-
                      #/components/schemas/aaa_components-schemas-api-response-common-failure
          description: Delete PagerDuty Services response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Delete PagerDuty Services
      tags:
        - Notification destinations with PagerDuty
      x-api-token-group:
        - Notifications Write
        - Account Settings Write
  /accounts/{account_id}/alerting/v3/destinations/pagerduty/connect:
    post:
      description: Creates a new token for integrating with PagerDuty.
      operationId: notification-destinations-with-pager-duty-connect-pager-duty
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/aaa_account-id'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/aaa_sensitive_id_response'
          description: Token for PagerDuty integration
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/aaa_id_response'
                  - $ref: >-
                      #/components/schemas/aaa_components-schemas-api-response-common-failure
          description: Create a token for PagerDuty integration failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Create PagerDuty integration token
      tags:
        - Notification destinations with PagerDuty
      x-api-token-group:
        - Notifications Write
        - Account Settings Write
  /accounts/{account_id}/alerting/v3/destinations/pagerduty/connect/{token_id}:
    get:
      description: Links PagerDuty with the account using the integration token.
      operationId: notification-destinations-with-pager-duty-connect-pager-duty-token
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/aaa_account-id'
        - in: path
          name: token_id
          required: true
          schema:
            $ref: '#/components/schemas/aaa_integration-token'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/aaa_id_response'
          description: Create a Notification policy response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/aaa_id_response'
                  - $ref: >-
                      #/components/schemas/aaa_components-schemas-api-response-common-failure
          description: Create a Notification policy response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Connect PagerDuty
      tags:
        - Notification destinations with PagerDuty
      x-api-token-group:
        - Notifications Write
        - Account Settings Write
components:
  schemas:
    aaa_account-id:
      description: The account id
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
    aaa_api-response-collection:
      allOf:
        - $ref: '#/components/schemas/aaa_api-response-common'
        - properties:
            result_info:
              $ref: '#/components/schemas/aaa_schemas-result_info'
      type: object
    aaa_components-schemas-api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/aaa_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/aaa_messages'
          example: []
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
      type: object
    aaa_components-schemas-response_collection:
      allOf:
        - $ref: '#/components/schemas/aaa_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/aaa_pagerduty'
              type: array
    aaa_id_response:
      allOf:
        - $ref: '#/components/schemas/aaa_api-response-single'
        - properties:
            result:
              properties:
                id:
                  $ref: '#/components/schemas/aaa_uuid'
              type: object
    aaa_integration-token:
      description: The token integration key
      example: 8c71e667571b4f61b94d9e4b12158038
      maxLength: 32
      readOnly: true
      type: string
    aaa_sensitive_id_response:
      allOf:
        - $ref: '#/components/schemas/aaa_api-response-single'
        - properties:
            result:
              properties:
                id:
                  $ref: '#/components/schemas/aaa_token'
              type: object
