openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /certificates:
    get:
      description: >-
        List all existing Origin CA certificates for a given zone. You can use
        an Origin CA Key as your User Service Key or an API token when calling
        this endpoint ([see above](#requests)).
      operationId: origin-ca-list-certificates
      parameters:
        - in: query
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_identifier'
        - in: query
          name: page
          schema:
            default: 1
            description: Page number of paginated results.
            minimum: 1
            type: number
        - in: query
          name: per_page
          schema:
            default: 20
            description: Number of records per page.
            maximum: 50
            minimum: 5
            type: number
        - in: query
          name: limit
          schema:
            description: Limit to the number of records returned.
            example: 10
            type: integer
        - in: query
          name: offset
          schema:
            description: Offset the results
            example: 10
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_schemas-certificate_response_collection
          description: List Certificates response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_schemas-certificate_response_collection
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_api-response-common-failure
          description: List Certificates response failure
      security:
        - user_service_key: []
        - api_token: []
      summary: List Certificates
      tags:
        - Origin CA
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    post:
      description: >-
        Create an Origin CA certificate. You can use an Origin CA Key as your
        User Service Key or an API token when calling this endpoint ([see
        above](#requests)).
      operationId: origin-ca-create-certificate
      requestBody:
        content:
          application/json:
            schema:
              properties:
                csr:
                  $ref: '#/components/schemas/tls-certificates-and-hostnames_csr'
                hostnames:
                  $ref: >-
                    #/components/schemas/tls-certificates-and-hostnames_hostnames
                request_type:
                  $ref: >-
                    #/components/schemas/tls-certificates-and-hostnames_request_type
                requested_validity:
                  $ref: >-
                    #/components/schemas/tls-certificates-and-hostnames_requested_validity
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_schemas-certificate_response_single
          description: Create Certificate response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_schemas-certificate_response_single
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_api-response-common-failure
          description: Create Certificate response failure
      security:
        - user_service_key: []
        - api_token: []
      summary: Create Certificate
      tags:
        - Origin CA
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /certificates/{certificate_id}:
    get:
      description: >-
        Get an existing Origin CA certificate by its serial number. You can use
        an Origin CA Key as your User Service Key or an API token when calling
        this endpoint ([see above](#requests)).
      operationId: origin-ca-get-certificate
      parameters:
        - in: path
          name: certificate_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_schemas-certificate_response_single
          description: Get Certificate response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_schemas-certificate_response_single
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_api-response-common-failure
          description: Get Certificate response failure
      security:
        - user_service_key: []
        - api_token: []
      summary: Get Certificate
      tags:
        - Origin CA
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    delete:
      description: >-
        Revoke an existing Origin CA certificate by its serial number. You can
        use an Origin CA Key as your User Service Key or an API token when
        calling this endpoint ([see above](#requests)).
      operationId: origin-ca-revoke-certificate
      parameters:
        - in: path
          name: certificate_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_certificate_revoke_response
          description: Revoke Certificate response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_certificate_revoke_response
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_api-response-common-failure
          description: Revoke Certificate response failure
      security:
        - user_service_key: []
        - api_token: []
      summary: Revoke Certificate
      tags:
        - Origin CA
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    tls-certificates-and-hostnames_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/tls-certificates-and-hostnames_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/tls-certificates-and-hostnames_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    tls-certificates-and-hostnames_certificate_revoke_response:
      allOf:
        - properties:
            result:
              properties:
                id:
                  $ref: >-
                    #/components/schemas/tls-certificates-and-hostnames_identifier
                revoked_at:
                  $ref: >-
                    #/components/schemas/tls-certificates-and-hostnames_revoked_at
          type: object
    tls-certificates-and-hostnames_csr:
      description: The Certificate Signing Request (CSR). Must be newline-encoded.
      example: |-
        -----BEGIN CERTIFICATE REQUEST-----
        MIICxzCCAa8CAQAwSDELMAkGA1UEBhMCVVMxFjAUBgNVBAgTDVNhbiBGcmFuY2lz
        Y28xCzAJBgNVBAcTAkNBMRQwEgYDVQQDEwtleGFtcGxlLm5ldDCCASIwDQYJKoZI
        hvcNAQEBBQADggEPADCCAQoCggEBALxejtu4b+jPdFeFi6OUsye8TYJQBm3WfCvL
        Hu5EvijMO/4Z2TImwASbwUF7Ir8OLgH+mGlQZeqyNvGoSOMEaZVXcYfpR1hlVak8
        4GGVr+04IGfOCqaBokaBFIwzclGZbzKmLGwIQioNxGfqFm6RGYGA3be2Je2iseBc
        N8GV1wYmvYE0RR+yWweJCTJ157exyRzu7sVxaEW9F87zBQLyOnwXc64rflXslRqi
        g7F7w5IaQYOl8yvmk/jEPCAha7fkiUfEpj4N12+oPRiMvleJF98chxjD4MH39c5I
        uOslULhrWunfh7GB1jwWNA9y44H0snrf+xvoy2TcHmxvma9Eln8CAwEAAaA6MDgG
        CSqGSIb3DQEJDjErMCkwJwYDVR0RBCAwHoILZXhhbXBsZS5uZXSCD3d3dy5leGFt
        cGxlLm5ldDANBgkqhkiG9w0BAQsFAAOCAQEAcBaX6dOnI8ncARrI9ZSF2AJX+8mx
        pTHY2+Y2C0VvrVDGMtbBRH8R9yMbqWtlxeeNGf//LeMkSKSFa4kbpdx226lfui8/
        auRDBTJGx2R1ccUxmLZXx4my0W5iIMxunu+kez+BDlu7bTT2io0uXMRHue4i6quH
        yc5ibxvbJMjR7dqbcanVE10/34oprzXQsJ/VmSuZNXtjbtSKDlmcpw6To/eeAJ+J
        hXykcUihvHyG4A1m2R6qpANBjnA0pHexfwM/SgfzvpbvUg0T1ubmer8BgTwCKIWs
        dcWYTthM51JIqRBfNqy4QcBnX+GY05yltEEswQI55wdiS3CjTTA67sdbcQ==
        -----END CERTIFICATE REQUEST-----
      type: string
    tls-certificates-and-hostnames_hostnames:
      description: >-
        Array of hostnames or wildcard names (e.g., *.example.com) bound to the
        certificate.
      example:
        - example.com
        - '*.example.com'
      items:
        type: string
        x-auditable: true
      type: array
    tls-certificates-and-hostnames_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    tls-certificates-and-hostnames_request_type:
      description: >-
        Signature type desired on certificate ("origin-rsa" (rsa), "origin-ecc"
        (ecdsa), or "keyless-certificate" (for Keyless SSL servers).
      enum:
        - origin-rsa
        - origin-ecc
        - keyless-certificate
      example: origin-rsa
      type: string
      x-auditable: true
    tls-certificates-and-hostnames_requested_validity:
      default: 5475
      description: The number of days for which the certificate should be valid.
      enum:
        - 7
        - 30
        - 90
        - 365
        - 730
        - 1095
        - 5475
      example: 5475
      type: number
      x-auditable: true
    tls-certificates-and-hostnames_schemas-certificate_response_collection:
      allOf:
        - $ref: >-
            #/components/schemas/tls-certificates-and-hostnames_api-response-collection
        - properties:
            result:
              items:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_certificates
              type: array
          type: object
    tls-certificates-and-hostnames_schemas-certificate_response_single:
      allOf:
        - $ref: >-
            #/components/schemas/tls-certificates-and-hostnames_api-response-single
        - properties:
            result:
              $ref: '#/components/schemas/tls-certificates-and-hostnames_certificates'
          type: object
