openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/hostnames/settings/{setting_id}:
    get:
      description: List the requested TLS setting for the hostnames under this zone.
      operationId: per-hostname-tls-settings-list
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_identifier'
        - in: path
          name: setting_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_setting_id'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_per_hostname_settings_response_collection
          description: List per-hostname TLS settings response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_per_hostname_settings_response_collection
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_api-response-common-failure
          description: List per-hostname TLS settings response failure
      security:
        - api_email: []
          api_key: []
      summary: List TLS setting for hostnames
      tags:
        - Per-Hostname TLS Settings
      x-api-token-group:
        - SSL and Certificates Write
        - SSL and Certificates Read
      x-cfPermissionsRequired:
        enum:
          - '#ssl:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /zones/{zone_id}/hostnames/settings/{setting_id}/{hostname}:
    put:
      description: Update the tls setting value for the hostname.
      operationId: per-hostname-tls-settings-put
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_identifier'
        - in: path
          name: setting_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_setting_id'
        - in: path
          name: hostname
          required: true
          schema:
            $ref: >-
              #/components/schemas/tls-certificates-and-hostnames_components-schemas-hostname
      requestBody:
        content:
          application/json:
            schema:
              properties:
                value:
                  $ref: '#/components/schemas/tls-certificates-and-hostnames_value'
              required:
                - value
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_per_hostname_settings_response
          description: Edit TLS setting for hostname response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_per_hostname_settings_response
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_api-response-common-failure
          description: Edit TLS setting for hostname response failure
      security:
        - api_email: []
          api_key: []
      summary: Edit TLS setting for hostname
      tags:
        - Per-Hostname TLS Settings
      x-api-token-group:
        - SSL and Certificates Write
      x-cfPermissionsRequired:
        enum:
          - '#ssl:edit'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    delete:
      description: Delete the tls setting value for the hostname.
      operationId: per-hostname-tls-settings-delete
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_identifier'
        - in: path
          name: setting_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_setting_id'
        - in: path
          name: hostname
          required: true
          schema:
            $ref: >-
              #/components/schemas/tls-certificates-and-hostnames_components-schemas-hostname
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_per_hostname_settings_response_delete
          description: Delete TLS setting for hostname response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_per_hostname_settings_response_delete
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_api-response-common-failure
          description: Delete TLS setting for hostname response failure
      security:
        - api_email: []
          api_key: []
      summary: Delete TLS setting for hostname
      tags:
        - Per-Hostname TLS Settings
      x-api-token-group:
        - SSL and Certificates Write
      x-cfPermissionsRequired:
        enum:
          - '#ssl:edit'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    tls-certificates-and-hostnames_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/tls-certificates-and-hostnames_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/tls-certificates-and-hostnames_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    tls-certificates-and-hostnames_components-schemas-hostname:
      description: The hostname for which the tls settings are set.
      example: app.example.com
      type: string
      x-auditable: true
    tls-certificates-and-hostnames_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    tls-certificates-and-hostnames_per_hostname_settings_response:
      allOf:
        - $ref: >-
            #/components/schemas/tls-certificates-and-hostnames_api-response-single
        - properties:
            result:
              allOf:
                - $ref: >-
                    #/components/schemas/tls-certificates-and-hostnames_settingObject
              type: object
    tls-certificates-and-hostnames_per_hostname_settings_response_collection:
      allOf:
        - $ref: >-
            #/components/schemas/tls-certificates-and-hostnames_api-response-collection
        - properties:
            result:
              items:
                properties:
                  created_at:
                    $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_hostname-tls-settings_components-schemas-created_at
                  hostname:
                    $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_components-schemas-hostname
                  status:
                    $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_hostname-tls-settings_components-schemas-status
                  updated_at:
                    $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_hostname-tls-settings_components-schemas-updated_at
                  value:
                    $ref: '#/components/schemas/tls-certificates-and-hostnames_value'
              type: array
        - properties:
            result_info:
              properties:
                count:
                  example: 1
                page:
                  example: 1
                per_page:
                  example: 50
                total_count:
                  example: 1
                total_pages:
                  description: Total pages available of results
                  example: 1
                  type: number
              type: object
    tls-certificates-and-hostnames_per_hostname_settings_response_delete:
      allOf:
        - $ref: >-
            #/components/schemas/tls-certificates-and-hostnames_api-response-single
        - properties:
            result:
              allOf:
                - $ref: >-
                    #/components/schemas/tls-certificates-and-hostnames_settingObjectDelete
              type: object
    tls-certificates-and-hostnames_setting_id:
      description: The TLS Setting name.
      enum:
        - ciphers
        - min_tls_version
        - http2
      type: string
      x-auditable: true
    tls-certificates-and-hostnames_value:
      description: The tls setting value.
      example:
        - ECDHE-RSA-AES128-GCM-SHA256
        - AES128-GCM-SHA256
      oneOf:
        - type: number
          x-auditable: true
        - type: string
          x-auditable: true
        - items:
            type: string
            x-auditable: true
          type: array
