openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/devices/physical-devices:
    get:
      description: Lists WARP devices.
      operationId: list-devices
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
        - $ref: >-
            #/components/parameters/teams-devices_devices_list_devices_param_cursor
        - $ref: >-
            #/components/parameters/teams-devices_devices_list_devices_param_sort_by
        - $ref: >-
            #/components/parameters/teams-devices_devices_list_devices_param_sort_order
        - $ref: >-
            #/components/parameters/teams-devices_devices_list_devices_param_last_seen_user_email
        - $ref: >-
            #/components/parameters/teams-devices_devices_list_devices_param_seen_after
        - $ref: >-
            #/components/parameters/teams-devices_devices_list_devices_param_seen_before
        - $ref: >-
            #/components/parameters/teams-devices_devices_list_devices_param_per_page
        - $ref: >-
            #/components/parameters/teams-devices_devices_list_devices_param_search
        - $ref: >-
            #/components/parameters/teams-devices_devices_list_devices_param_active_registrations
        - $ref: '#/components/parameters/teams-devices_devices_list_devices_param_id'
        - $ref: >-
            #/components/parameters/teams-devices_devices_list_devices_param_include
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    example: []
                    items:
                      $ref: '#/components/schemas/teams-devices_v4_response_message'
                    type: array
                  messages:
                    example: []
                    items:
                      $ref: '#/components/schemas/teams-devices_v4_response_message'
                    type: array
                  result:
                    items:
                      $ref: '#/components/schemas/teams-devices_physical_device'
                    type: array
                  result_info:
                    $ref: '#/components/schemas/teams-devices_cursor_result_info'
                  success:
                    description: Whether the API call was successful.
                    type: boolean
                required:
                  - result
                  - success
                  - errors
                  - messages
                type: object
          description: Returns a list of Devices.
      security:
        - api_token: []
      summary: List devices
      tags:
        - Physical Devices
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
  /accounts/{account_id}/devices/physical-devices/{device_id}:
    get:
      description: Fetches a single WARP device.
      operationId: get-device
      parameters:
        - in: path
          name: device_id
          required: true
          schema:
            type: string
        - in: path
          name: account_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      $ref: '#/components/schemas/teams-devices_v4_response_message'
                    type: array
                  messages:
                    items:
                      $ref: '#/components/schemas/teams-devices_v4_response_message'
                    type: array
                  result:
                    $ref: '#/components/schemas/teams-devices_physical_device'
                  success:
                    description: Whether the API call was successful.
                    type: boolean
                required:
                  - result
                  - success
                  - errors
                  - messages
                type: object
          description: Returns a Device.
      security:
        - api_token: []
      summary: Get device
      tags:
        - Physical Devices
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
    delete:
      description: Deletes a WARP device.
      operationId: delete-device
      parameters:
        - in: path
          name: device_id
          required: true
          schema:
            type: string
        - in: path
          name: account_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      $ref: '#/components/schemas/teams-devices_v4_response_message'
                    type: array
                  messages:
                    items:
                      $ref: '#/components/schemas/teams-devices_v4_response_message'
                    type: array
                  result:
                    $ref: '#/components/schemas/teams-devices_empty_body'
                  success:
                    description: Whether the API call was successful.
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                type: object
          description: Device was successfully deleted.
      security:
        - api_token: []
      summary: Delete device
      tags:
        - Physical Devices
      x-api-token-group:
        - Zero Trust Write
  /accounts/{account_id}/devices/physical-devices/{device_id}/revoke:
    post:
      description: Revokes all WARP registrations associated with the specified device.
      operationId: revoke-device
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
        - in: path
          name: device_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      $ref: '#/components/schemas/teams-devices_v4_response_message'
                    type: array
                  messages:
                    items:
                      $ref: '#/components/schemas/teams-devices_v4_response_message'
                    type: array
                  result:
                    $ref: '#/components/schemas/teams-devices_empty_body'
                  success:
                    description: Whether the API call was successful.
                    type: boolean
                required:
                  - success
                  - errors
                  - messages
                type: object
          description: Revoke device registrations response.
      security:
        - api_token: []
      summary: Revoke device registrations
      tags:
        - Physical Devices
      x-api-token-group:
        - Zero Trust Write
  /accounts/{account_id}/devices/registrations:
    delete:
      description: Deletes a list of WARP registrations.
      operationId: delete-registrations
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
        - description: A list of registration IDs to delete.
          in: query
          name: id
          required: true
          schema:
            items:
              type: string
            type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      $ref: '#/components/schemas/teams-devices_v4_response_message'
                    type: array
                  messages:
                    items:
                      $ref: '#/components/schemas/teams-devices_v4_response_message'
                    type: array
                  result:
                    $ref: '#/components/schemas/teams-devices_empty_body'
                  result_info:
                    $ref: '#/components/schemas/teams-devices_cursor_result_info'
                  success:
                    description: Whether the API call was successful.
                    type: boolean
                required:
                  - result
                  - success
                  - errors
                  - messages
                type: object
          description: Delete a list of registrations response.
      security:
        - api_token: []
      summary: Delete registrations
      tags:
        - Physical Devices
      x-api-token-group:
        - Zero Trust Write
components:
  schemas:
    teams-devices_cursor_result_info:
      description: V4 public API Pagination/Cursor info.
      example:
        count: 1
        cursor: ais86dftf.asdf7ba8
        page: null
        per_page: 10
        total_count: null
      properties:
        count:
          description: Number of records in the response.
          type: integer
        cursor:
          description: Opaque token to request the next set of records.
          type: string
        per_page:
          description: The limit for the number of records in the response.
          type: integer
        total_count:
          description: Total number of records available.
          nullable: true
          type: integer
      required:
        - per_page
        - count
        - cursor
      type: object
    teams-devices_empty_body:
      nullable: true
      type: object
    teams-devices_physical_device:
      description: A WARP Device.
      properties:
        active_registrations:
          description: >-
            The number of active registrations for the device. Active
            registrations are those which haven't been revoked or deleted.
          example: 1
          type: integer
          x-auditable: true
        client_version:
          description: Version of the WARP client.
          example: 1.0.0
          nullable: true
          type: string
          x-auditable: true
        created_at:
          description: The RFC3339 timestamp when the device was created.
          example: '2025-02-14T13:17:00Z'
          type: string
          x-auditable: true
        deleted_at:
          description: The RFC3339 timestamp when the device was deleted.
          example: '2025-02-14T13:17:00Z'
          nullable: true
          type: string
          x-auditable: true
        device_type:
          description: The device operating system.
          example: linux
          nullable: true
          type: string
          x-auditable: true
        hardware_id:
          description: >-
            A string that uniquely identifies the hardware or virtual machine
            (VM).
          nullable: true
          type: string
          x-auditable: true
        id:
          description: The unique ID of the device.
          example: fc9ab6ab-3b94-4319-9941-459462b3d73e
          type: string
          x-auditable: true
        last_seen_at:
          description: The RFC3339 timestamp when the device was last seen.
          example: '2025-02-14T13:17:00Z'
          nullable: true
          type: string
          x-auditable: true
        last_seen_user:
          allOf:
            - $ref: '#/components/schemas/teams-devices_user'
          description: The last user to use the WARP device.
          nullable: true
          type: object
        mac_address:
          description: The device MAC address.
          example: f5:01:73:cf:12:23
          nullable: true
          type: string
          x-auditable: true
        manufacturer:
          description: The device manufacturer.
          example: ACME
          nullable: true
          type: string
          x-auditable: true
        model:
          description: The model name of the device.
          example: Mark VII
          nullable: true
          type: string
          x-auditable: true
        name:
          description: The name of the device.
          example: My Device
          type: string
          x-auditable: true
        os_version:
          description: The device operating system version number.
          nullable: true
          type: string
          x-auditable: true
        os_version_extra:
          description: >-
            Additional operating system version data. For macOS or iOS, the
            Product Version Extra. For Linux, the kernel release version.
          nullable: true
          type: string
          x-auditable: true
        public_ip:
          description: The public IP address of the WARP client.
          example: 1.1.1.1
          nullable: true
          type: string
          x-auditable: true
        serial_number:
          description: The device serial number.
          example: ABS765ASD8A
          nullable: true
          type: string
          x-auditable: true
        updated_at:
          description: The RFC3339 timestamp when the device was last updated.
          example: '2025-02-14T13:17:00Z'
          type: string
          x-auditable: true
      required:
        - id
        - name
        - created_at
        - updated_at
        - last_seen_at
        - active_registrations
      type: object
    teams-devices_v4_response_message:
      description: >-
        A message which can be returned in either the 'errors' or 'messages'
        fields in a v4 API response.
      properties:
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message
      type: object
  parameters:
    teams-devices_devices_list_devices_param_active_registrations:
      description: >-
        Include or exclude devices with active registrations. The default is
        "only" - return only devices with active registrations.
      explode: false
      in: query
      name: active_registrations
      schema:
        enum:
          - include
          - only
          - exclude
        type: string
    teams-devices_devices_list_devices_param_cursor:
      description: >-
        Opaque token indicating the starting position when requesting the next
        set of records. A cursor value can be obtained from the
        result_info.cursor field in the response.
      explode: false
      in: query
      name: cursor
      schema:
        type: string
    teams-devices_devices_list_devices_param_id:
      description: Filter by a one or more device IDs.
      explode: true
      in: query
      name: id
      schema:
        items:
          type: string
        type: array
    teams-devices_devices_list_devices_param_include:
      in: query
      name: include
      schema:
        type: string
    teams-devices_devices_list_devices_param_last_seen_user_email:
      description: Filter by the last seen user's email.
      explode: false
      in: query
      name: last_seen_user.email
      schema:
        type: string
    teams-devices_devices_list_devices_param_per_page:
      description: The maximum number of devices to return in a single response.
      explode: false
      in: query
      name: per_page
      schema:
        format: uint64
        type: integer
    teams-devices_devices_list_devices_param_search:
      description: Search by device details.
      explode: false
      in: query
      name: search
      schema:
        type: string
    teams-devices_devices_list_devices_param_seen_after:
      description: >-
        Filter by the last_seen timestamp - returns only devices last seen after
        this timestamp.
      explode: false
      in: query
      name: seen_after
      schema:
        type: string
    teams-devices_devices_list_devices_param_seen_before:
      description: >-
        Filter by the last_seen timestamp - returns only devices last seen
        before this timestamp.
      explode: false
      in: query
      name: seen_before
      schema:
        type: string
    teams-devices_devices_list_devices_param_sort_by:
      description: The device field to order results by.
      explode: false
      in: query
      name: sort_by
      schema:
        enum:
          - name
          - id
          - client_version
          - last_seen_user.email
          - last_seen_at
          - active_registrations
          - created_at
        type: string
    teams-devices_devices_list_devices_param_sort_order:
      description: Sort direction.
      explode: false
      in: query
      name: sort_order
      schema:
        enum:
          - asc
          - desc
        type: string
