openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /radar/traffic_anomalies:
    get:
      description: >-
        Retrieves the latest Internet traffic anomalies, which are signals that
        might indicate an outage. These alerts are automatically detected by
        Radar and manually verified by our team.
      operationId: radar-get-traffic-anomalies
      parameters:
        - description: Limits the number of objects returned in the response.
          in: query
          name: limit
          schema:
            description: Limits the number of objects returned in the response.
            example: 5
            type: integer
        - description: Skips the specified number of objects before fetching the results.
          in: query
          name: offset
          schema:
            description: Skips the specified number of objects before fetching the results.
            type: integer
        - description: Filters results by date range.
          in: query
          name: dateRange
          schema:
            description: Filters results by date range.
            example: 7d
            pattern: >-
              ^((([1-9]|[1-9][0-9]|[1-2][0-9][0-9]|3[0-5][0-9]|36[0-4])[d](control)?)|(([1-9]|[1-4][0-9]|5[0-2])[w](control)?))$
            type: string
        - description: Start of the date range (inclusive).
          in: query
          name: dateStart
          schema:
            description: Start of the date range (inclusive).
            example: '2023-09-01T11:41:33.782Z'
            format: date-time
            type: string
        - description: End of the date range (inclusive).
          in: query
          name: dateEnd
          schema:
            description: End of the date range (inclusive).
            example: '2023-09-01T11:41:33.782Z'
            format: date-time
            type: string
        - in: query
          name: status
          schema:
            enum:
              - VERIFIED
              - UNVERIFIED
            type: string
        - description: >-
            Filters results by Autonomous System. Specify a single Autonomous
            System Number (ASN) as integer.
          in: query
          name: asn
          schema:
            description: >-
              Filters results by Autonomous System. Specify a single Autonomous
              System Number (ASN) as integer.
            example: 174
            type: integer
        - description: Filters results by location. Specify an alpha-2 location code.
          in: query
          name: location
          schema:
            description: Filters results by location. Specify an alpha-2 location code.
            example: US
            type: string
        - description: Format in which results will be returned.
          in: query
          name: format
          schema:
            description: Format in which results will be returned.
            enum:
              - JSON
              - CSV
            example: json
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  result:
                    properties:
                      trafficAnomalies:
                        items:
                          properties:
                            asnDetails:
                              properties:
                                asn:
                                  example: '189'
                                  type: string
                                locations:
                                  properties:
                                    code:
                                      example: US
                                      type: string
                                    name:
                                      example: United States
                                      type: string
                                  required:
                                    - code
                                    - name
                                  type: object
                                name:
                                  example: LUMEN-LEGACY-L3-PARTITION
                                  type: string
                              required:
                                - asn
                                - name
                              type: object
                            endDate:
                              format: date-time
                              type: string
                            locationDetails:
                              properties:
                                code:
                                  example: US
                                  type: string
                                name:
                                  example: United States
                                  type: string
                              required:
                                - code
                                - name
                              type: object
                            startDate:
                              example: '2023-08-02T23:15:00Z'
                              type: string
                            status:
                              example: UNVERIFIED
                              type: string
                            type:
                              example: LOCATION
                              type: string
                            uuid:
                              example: 55a57f33-8bc0-4984-b4df-fdaff72df39d
                              type: string
                            visibleInDataSources:
                              items:
                                type: string
                              type: array
                          required:
                            - uuid
                            - type
                            - status
                            - startDate
                          type: object
                        type: array
                    required:
                      - trafficAnomalies
                    type: object
                  success:
                    example: true
                    type: boolean
                required:
                  - result
                  - success
                type: object
          description: List of Internet traffic anomalies.
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  result:
                    type: object
                  success:
                    example: false
                    type: boolean
                required:
                  - result
                  - success
                  - errors
                type: object
          description: Bad request.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get latest Internet traffic anomalies
      tags:
        - Radar Traffic Anomalies
      x-api-token-group:
        - User Details Write
        - User Details Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /radar/traffic_anomalies/locations:
    get:
      description: >-
        Retrieves the sum of Internet traffic anomalies, grouped by location.
        These anomalies are signals that might indicate an outage, automatically
        detected by Radar and manually verified by our team.
      operationId: radar-get-traffic-anomalies-top
      parameters:
        - description: Limits the number of objects returned in the response.
          in: query
          name: limit
          schema:
            description: Limits the number of objects returned in the response.
            example: 5
            type: integer
        - description: Filters results by date range.
          in: query
          name: dateRange
          schema:
            description: Filters results by date range.
            example: 7d
            pattern: >-
              ^((([1-9]|[1-9][0-9]|[1-2][0-9][0-9]|3[0-5][0-9]|36[0-4])[d](control)?)|(([1-9]|[1-4][0-9]|5[0-2])[w](control)?))$
            type: string
        - description: Start of the date range (inclusive).
          in: query
          name: dateStart
          schema:
            description: Start of the date range (inclusive).
            example: '2023-09-01T11:41:33.782Z'
            format: date-time
            type: string
        - description: End of the date range (inclusive).
          in: query
          name: dateEnd
          schema:
            description: End of the date range (inclusive).
            example: '2023-09-01T11:41:33.782Z'
            format: date-time
            type: string
        - in: query
          name: status
          schema:
            enum:
              - VERIFIED
              - UNVERIFIED
            type: string
        - description: Format in which results will be returned.
          in: query
          name: format
          schema:
            description: Format in which results will be returned.
            enum:
              - JSON
              - CSV
            example: json
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  result:
                    properties:
                      trafficAnomalies:
                        items:
                          properties:
                            clientCountryAlpha2:
                              example: PT
                              type: string
                            clientCountryName:
                              example: Portugal
                              type: string
                            value:
                              description: A numeric string.
                              example: '10'
                              pattern: ^\d+$
                              type: string
                          required:
                            - clientCountryAlpha2
                            - clientCountryName
                            - value
                          type: object
                        type: array
                    required:
                      - trafficAnomalies
                    type: object
                  success:
                    example: true
                    type: boolean
                required:
                  - result
                  - success
                type: object
          description: List of locations with number of traffic anomalies.
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          type: string
                      required:
                        - message
                      type: object
                    type: array
                  result:
                    type: object
                  success:
                    example: false
                    type: boolean
                required:
                  - result
                  - success
                  - errors
                type: object
          description: Bad request.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get top locations by total traffic anomalies
      tags:
        - Radar Traffic Anomalies
      x-api-token-group:
        - User Details Write
        - User Details Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
