openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/rate_limits:
    get:
      deprecated: true
      description: Fetches the rate limits for a zone.
      operationId: rate-limits-for-a-zone-list-rate-limits
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/firewall_identifier'
        - in: query
          name: page
          schema:
            default: 1
            description: Defines the page number of paginated results.
            minimum: 1
            type: number
        - in: query
          name: per_page
          schema:
            default: 20
            description: >-
              Defines the maximum number of results per page. You can only set
              the value to `1` or to a multiple of 5 such as `5`, `10`, `15`, or
              `20`.
            maximum: 1000
            minimum: 1
            type: number
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/firewall_ratelimit_response_collection'
          description: List rate limits response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/firewall_ratelimit_response_collection
                  - $ref: '#/components/schemas/firewall_api-response-common-failure'
          description: List rate limits response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List rate limits
      tags:
        - Rate limits for a zone
      x-api-token-group:
        - Firewall Services Write
        - Firewall Services Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    post:
      deprecated: true
      description: >-
        Creates a new rate limit for a zone. Refer to the object definition for
        a list of required attributes.
      operationId: rate-limits-for-a-zone-create-a-rate-limit
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/firewall_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                action:
                  $ref: '#/components/schemas/firewall_action'
                match:
                  $ref: '#/components/schemas/firewall_match'
                period:
                  $ref: '#/components/schemas/firewall_period'
                threshold:
                  $ref: '#/components/schemas/firewall_threshold'
              required:
                - match
                - threshold
                - period
                - action
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/firewall_ratelimit_response_single'
          description: Create a rate limit response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/firewall_ratelimit_response_single'
                  - $ref: '#/components/schemas/firewall_api-response-common-failure'
          description: Create a rate limit response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create a rate limit
      tags:
        - Rate limits for a zone
      x-api-token-group:
        - Firewall Services Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /zones/{zone_id}/rate_limits/{rate_limit_id}:
    get:
      deprecated: true
      description: Fetches the details of a rate limit.
      operationId: rate-limits-for-a-zone-get-a-rate-limit
      parameters:
        - in: path
          name: rate_limit_id
          required: true
          schema:
            $ref: '#/components/schemas/firewall_rate_limit_id'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/firewall_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/firewall_ratelimit_response_single'
          description: Get a rate limit response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/firewall_ratelimit_response_single'
                  - $ref: '#/components/schemas/firewall_api-response-common-failure'
          description: Get a rate limit response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get a rate limit
      tags:
        - Rate limits for a zone
      x-api-token-group:
        - Firewall Services Write
        - Firewall Services Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    put:
      deprecated: true
      description: Updates an existing rate limit.
      operationId: rate-limits-for-a-zone-update-a-rate-limit
      parameters:
        - in: path
          name: rate_limit_id
          required: true
          schema:
            $ref: '#/components/schemas/firewall_rate_limit_id'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/firewall_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                action:
                  $ref: '#/components/schemas/firewall_action'
                match:
                  $ref: '#/components/schemas/firewall_match'
                period:
                  $ref: '#/components/schemas/firewall_period'
                threshold:
                  $ref: '#/components/schemas/firewall_threshold'
              required:
                - match
                - threshold
                - period
                - action
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/firewall_ratelimit_response_single'
          description: Update a rate limit response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/firewall_ratelimit_response_single'
                  - $ref: '#/components/schemas/firewall_api-response-common-failure'
          description: Update a rate limit response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update a rate limit
      tags:
        - Rate limits for a zone
      x-api-token-group:
        - Firewall Services Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    delete:
      deprecated: true
      description: Deletes an existing rate limit.
      operationId: rate-limits-for-a-zone-delete-a-rate-limit
      parameters:
        - in: path
          name: rate_limit_id
          required: true
          schema:
            $ref: '#/components/schemas/firewall_rate_limit_id'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/firewall_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/firewall_ratelimit_response_single'
                  - properties:
                      result:
                        properties:
                          id:
                            $ref: '#/components/schemas/firewall_id'
                        type: object
                    type: object
          description: Delete a rate limit response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: >-
                          #/components/schemas/firewall_ratelimit_response_single
                      - properties:
                          result:
                            properties:
                              id:
                                $ref: '#/components/schemas/firewall_id'
                            type: object
                        type: object
                  - $ref: '#/components/schemas/firewall_api-response-common-failure'
          description: Delete a rate limit response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete a rate limit
      tags:
        - Rate limits for a zone
      x-api-token-group:
        - Firewall Services Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    firewall_action:
      anyOf:
        - properties:
            mode:
              $ref: '#/components/schemas/firewall_mode'
            response:
              $ref: '#/components/schemas/firewall_custom_response'
            timeout:
              $ref: '#/components/schemas/firewall_timeout'
          type: object
      description: >-
        The action to perform when the threshold of matched traffic within the
        configured period is exceeded.
      type: object
    firewall_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/firewall_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/firewall_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Defines whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    firewall_id:
      description: The unique identifier of the rate limit.
      example: 372e67954025e0ba6aaa6d586b9e0b59
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
    firewall_identifier:
      description: Defines an identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    firewall_match:
      description: Determines which traffic the rate limit counts towards the threshold.
      oneOf:
        - properties:
            headers:
              items:
                properties:
                  name:
                    $ref: '#/components/schemas/firewall_header_name'
                  op:
                    $ref: '#/components/schemas/firewall_header_op'
                  value:
                    $ref: '#/components/schemas/firewall_header_value'
                type: object
              type: array
            request:
              properties:
                methods:
                  $ref: '#/components/schemas/firewall_methods'
                schemes:
                  $ref: '#/components/schemas/firewall_schemes'
                url:
                  $ref: '#/components/schemas/firewall_url'
              type: object
            response:
              properties:
                origin_traffic:
                  $ref: '#/components/schemas/firewall_origin_traffic'
              type: object
          type: object
      type: object
    firewall_period:
      description: >-
        The time in seconds (an integer value) to count matching traffic. If the
        count exceeds the configured threshold within this period, Cloudflare
        will perform the configured action.
      example: 900
      maximum: 86400
      minimum: 10
      type: number
      x-auditable: true
    firewall_rate_limit_id:
      description: Defines the unique identifier of the rate limit.
      example: 372e67954025e0ba6aaa6d586b9e0b59
      maxLength: 32
      readOnly: true
      type: string
    firewall_ratelimit_response_collection:
      allOf:
        - $ref: '#/components/schemas/firewall_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/firewall_rate-limits'
              type: array
          type: object
    firewall_ratelimit_response_single:
      allOf:
        - $ref: '#/components/schemas/firewall_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/firewall_rate-limits'
          type: object
    firewall_threshold:
      description: >-
        The threshold that will trigger the configured mitigation action.
        Configure this value along with the `period` property to establish a
        threshold per period.
      example: 60
      minimum: 1
      type: number
      x-auditable: true
