openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/registrar/domains:
    get:
      description: List domains handled by Registrar.
      operationId: registrar-domains-list-domains
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/registrar-api_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/registrar-api_domain_response_collection'
          description: List domains response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/registrar-api_domain_response_collection
                  - $ref: >-
                      #/components/schemas/registrar-api_api-response-common-failure
          description: List domains response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List domains
      tags:
        - Registrar Domains
      x-api-token-group: null
  /accounts/{account_id}/registrar/domains/{domain_name}:
    get:
      description: Show individual domain.
      operationId: registrar-domains-get-domain
      parameters:
        - in: path
          name: domain_name
          required: true
          schema:
            $ref: '#/components/schemas/registrar-api_domain_name'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/registrar-api_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/registrar-api_domain_response_single'
          description: Get domain response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/registrar-api_domain_response_single'
                  - $ref: >-
                      #/components/schemas/registrar-api_api-response-common-failure
          description: Get domain response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get domain
      tags:
        - Registrar Domains
      x-api-token-group: null
    put:
      description: Update individual domain.
      operationId: registrar-domains-update-domain
      parameters:
        - in: path
          name: domain_name
          required: true
          schema:
            $ref: '#/components/schemas/registrar-api_domain_name'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/registrar-api_identifier'
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/registrar-api_domain_update_properties'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/registrar-api_domain_response_single'
          description: Update domain response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/registrar-api_domain_response_single'
                  - $ref: >-
                      #/components/schemas/registrar-api_api-response-common-failure
          description: Update domain response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update domain
      tags:
        - Registrar Domains
      x-api-token-group: null
components:
  schemas:
    registrar-api_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/registrar-api_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/registrar-api_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    registrar-api_domain_name:
      description: Domain name.
      example: cloudflare.com
      type: string
    registrar-api_domain_response_collection:
      allOf:
        - $ref: '#/components/schemas/registrar-api_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/registrar-api_domains'
              type: array
    registrar-api_domain_response_single:
      allOf:
        - $ref: '#/components/schemas/registrar-api_api-response-single'
        - properties:
            result:
              type: object
    registrar-api_domain_update_properties:
      properties:
        auto_renew:
          $ref: '#/components/schemas/registrar-api_auto_renew'
        locked:
          $ref: '#/components/schemas/registrar-api_locked'
        privacy:
          $ref: '#/components/schemas/registrar-api_privacy'
      type: object
    registrar-api_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
