openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/magic/cloud/resources:
    get:
      description: List resources in the Resource Catalog (Closed Beta).
      operationId: resources-catalog-list
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/mcn_account_id'
        - in: query
          name: provider_id
          schema:
            type: string
        - in: query
          name: resource_type
          schema:
            items:
              $ref: '#/components/schemas/mcn_resource_type'
            type: array
        - in: query
          name: resource_id
          schema:
            items:
              $ref: '#/components/schemas/mcn_resource_id'
            type: array
        - in: query
          name: region
          schema:
            type: string
        - in: query
          name: resource_group
          schema:
            type: string
        - in: query
          name: managed
          schema:
            type: boolean
        - in: query
          name: search
          schema:
            items:
              type: string
            type: array
        - description: One of ["id", "resource_type", "region"].
          in: query
          name: order_by
          schema:
            type: string
        - in: query
          name: desc
          schema:
            type: boolean
        - in: query
          name: per_page
          schema:
            minimum: 1
            type: integer
        - in: query
          name: page
          schema:
            minimum: 1
            type: integer
        - in: query
          name: cloudflare
          schema:
            type: boolean
        - in: query
          name: v2
          schema:
            type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_read_account_resources_response'
          description: OK.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_bad_response'
          description: Bad Request.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_bad_response'
          description: Invalid Credentials.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_bad_response'
          description: Forbidden.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_bad_response'
          description: Not Found.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_bad_response'
          description: Internal Server Error.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List Resources
      tags:
        - Resources
      x-api-token-group:
        - Magic WAN Write
        - Magic WAN Read
  /accounts/{account_id}/magic/cloud/resources/export:
    get:
      description: Export resources in the Resource Catalog as a JSON file (Closed Beta).
      operationId: resources-catalog-export
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/mcn_account_id'
        - in: query
          name: provider_id
          schema:
            type: string
        - in: query
          name: resource_type
          schema:
            items:
              $ref: '#/components/schemas/mcn_resource_type'
            type: array
        - in: query
          name: resource_id
          schema:
            items:
              $ref: '#/components/schemas/mcn_resource_id'
            type: array
        - in: query
          name: region
          schema:
            type: string
        - in: query
          name: resource_group
          schema:
            type: string
        - in: query
          name: search
          schema:
            items:
              type: string
            type: array
        - description: One of ["id", "resource_type", "region"].
          in: query
          name: order_by
          schema:
            type: string
        - in: query
          name: desc
          schema:
            type: boolean
        - in: query
          name: v2
          schema:
            type: boolean
      responses:
        '200':
          content:
            application/octet-stream:
              schema:
                format: binary
                type: string
          description: Exported file.
          headers:
            Content-Disposition:
              schema:
                example: attachment; filename="exported_resources.zip"
                type: string
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_bad_response'
          description: Bad Request.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_bad_response'
          description: Invalid Credentials.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_bad_response'
          description: Forbidden.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_bad_response'
          description: Not Found.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_bad_response'
          description: Internal Server Error.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Export Resources
      tags:
        - Resources
      x-api-token-group:
        - Magic WAN Write
        - Magic WAN Read
  /accounts/{account_id}/magic/cloud/resources/policy-preview:
    post:
      description: >-
        Preview Rego query result against the latest resource catalog (Closed
        Beta).
      operationId: resources-catalog-policy-preview
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/mcn_account_id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/mcn_resources_catalog_policy_preview_request
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/mcn_resources_catalog_policy_preview_response
          description: OK.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_bad_response'
          description: Bad Request.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_bad_response'
          description: Invalid Credentials.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_bad_response'
          description: Forbidden.
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_bad_response'
          description: Unprocessable Entity.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_bad_response'
          description: Internal Server Error.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Preview Rego Query
      tags:
        - Resources
  /accounts/{account_id}/magic/cloud/resources/{resource_id}:
    get:
      description: Read an resource from the Resource Catalog (Closed Beta).
      operationId: resources-catalog-read
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/mcn_account_id'
        - in: path
          name: resource_id
          required: true
          schema:
            $ref: '#/components/schemas/mcn_resource_id'
        - in: query
          name: v2
          schema:
            type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_read_account_resource_response'
          description: OK.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_bad_response'
          description: Bad Request.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_bad_response'
          description: Invalid Credentials.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_bad_response'
          description: Forbidden.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_bad_response'
          description: Not Found.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mcn_bad_response'
          description: Internal Server Error.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Read Resource
      tags:
        - Resources
      x-api-token-group:
        - Magic WAN Write
        - Magic WAN Read
components:
  schemas:
    mcn_account_id:
      type: string
      x-auditable: true
    mcn_bad_response:
      allOf:
        - $ref: '#/components/schemas/mcn_response'
        - properties:
            errors:
              items:
                $ref: '#/components/schemas/mcn_error'
              minLength: 1
              type: array
            result:
              enum:
                - null
              nullable: true
              type: object
          type: object
      type: object
    mcn_read_account_resource_response:
      allOf:
        - $ref: '#/components/schemas/mcn_good_response'
        - properties:
            result:
              $ref: '#/components/schemas/mcn_resource_details'
          type: object
      type: object
    mcn_read_account_resources_response:
      allOf:
        - $ref: '#/components/schemas/mcn_good_response_collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/mcn_resource_details'
              type: array
            result_info:
              $ref: '#/components/schemas/mcn_result_info'
          type: object
      type: object
    mcn_resource_id:
      format: uuid
      type: string
      x-auditable: true
    mcn_resource_type:
      enum:
        - aws_customer_gateway
        - aws_egress_only_internet_gateway
        - aws_internet_gateway
        - aws_instance
        - aws_network_interface
        - aws_route
        - aws_route_table
        - aws_route_table_association
        - aws_subnet
        - aws_vpc
        - aws_vpc_ipv4_cidr_block_association
        - aws_vpn_connection
        - aws_vpn_connection_route
        - aws_vpn_gateway
        - aws_security_group
        - aws_vpc_security_group_ingress_rule
        - aws_vpc_security_group_egress_rule
        - aws_ec2_managed_prefix_list
        - aws_ec2_transit_gateway
        - aws_ec2_transit_gateway_prefix_list_reference
        - aws_ec2_transit_gateway_vpc_attachment
        - azurerm_application_security_group
        - azurerm_lb
        - azurerm_lb_backend_address_pool
        - azurerm_lb_nat_pool
        - azurerm_lb_nat_rule
        - azurerm_lb_rule
        - azurerm_local_network_gateway
        - azurerm_network_interface
        - azurerm_network_interface_application_security_group_association
        - azurerm_network_interface_backend_address_pool_association
        - azurerm_network_interface_security_group_association
        - azurerm_network_security_group
        - azurerm_public_ip
        - azurerm_route
        - azurerm_route_table
        - azurerm_subnet
        - azurerm_subnet_route_table_association
        - azurerm_virtual_machine
        - azurerm_virtual_network_gateway_connection
        - azurerm_virtual_network
        - azurerm_virtual_network_gateway
        - google_compute_network
        - google_compute_subnetwork
        - google_compute_vpn_gateway
        - google_compute_vpn_tunnel
        - google_compute_route
        - google_compute_address
        - google_compute_global_address
        - google_compute_router
        - google_compute_interconnect_attachment
        - google_compute_ha_vpn_gateway
        - google_compute_forwarding_rule
        - google_compute_network_firewall_policy
        - google_compute_network_firewall_policy_rule
        - cloudflare_static_route
        - cloudflare_ipsec_tunnel
      type: string
      x-auditable: true
    mcn_resources_catalog_policy_preview_request:
      properties:
        policy:
          type: string
      required:
        - policy
      type: object
    mcn_resources_catalog_policy_preview_response:
      allOf:
        - $ref: '#/components/schemas/mcn_good_response'
        - properties:
            result:
              $ref: '#/components/schemas/mcn_resources_catalog_policy_preview'
          type: object
      type: object
