openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/secondary_dns/peers:
    get:
      description: List Peers.
      operationId: secondary-dns-(-peer)-list-peers
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_schemas-response_collection'
          description: List Peers response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/secondary-dns_schemas-response_collection
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: List Peers response failure
      security:
        - api_email: []
          api_key: []
      summary: List Peers
      tags:
        - Secondary DNS (Peer)
      x-api-token-group:
        - Account Settings Write
        - Account Settings Read
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    post:
      description: Create Peer.
      operationId: secondary-dns-(-peer)-create-peer
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  $ref: '#/components/schemas/secondary-dns_components-schemas-name'
              required:
                - name
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_schemas-single_response'
          description: Create Peer response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/secondary-dns_schemas-single_response'
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: Create Peer response failure
      security:
        - api_email: []
          api_key: []
      summary: Create Peer
      tags:
        - Secondary DNS (Peer)
      x-api-token-group:
        - Account Settings Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/secondary_dns/peers/{peer_id}:
    get:
      description: Get Peer.
      operationId: secondary-dns-(-peer)-peer-details
      parameters:
        - in: path
          name: peer_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_components-schemas-identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_schemas-single_response'
          description: Peer Details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/secondary-dns_schemas-single_response'
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: Peer Details response failure
      security:
        - api_email: []
          api_key: []
      summary: Peer Details
      tags:
        - Secondary DNS (Peer)
      x-api-token-group:
        - Account Settings Write
        - Account Settings Read
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    put:
      description: Modify Peer.
      operationId: secondary-dns-(-peer)-update-peer
      parameters:
        - in: path
          name: peer_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_components-schemas-identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/secondary-dns_peer'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_schemas-single_response'
          description: Update Peer response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/secondary-dns_schemas-single_response'
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: Update Peer response failure
      security:
        - api_email: []
          api_key: []
      summary: Update Peer
      tags:
        - Secondary DNS (Peer)
      x-api-token-group:
        - Account Settings Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    delete:
      description: Delete Peer.
      operationId: secondary-dns-(-peer)-delete-peer
      parameters:
        - in: path
          name: peer_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_components-schemas-identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_account_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/secondary-dns_components-schemas-id_response
          description: Delete Peer response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/secondary-dns_components-schemas-id_response
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: Delete Peer response failure
      security:
        - api_email: []
          api_key: []
      summary: Delete Peer
      tags:
        - Secondary DNS (Peer)
      x-api-token-group:
        - Account Settings Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    secondary-dns_account_identifier:
      example: 01a7362d577a6c3019a474fd6f485823
      readOnly: true
      type: string
      x-auditable: true
    secondary-dns_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/secondary-dns_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/secondary-dns_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    secondary-dns_components-schemas-id_response:
      allOf:
        - $ref: '#/components/schemas/secondary-dns_api-response-single'
        - properties:
            result:
              properties:
                id:
                  $ref: >-
                    #/components/schemas/secondary-dns_components-schemas-identifier
              type: object
    secondary-dns_components-schemas-identifier:
      example: 23ff594956f20c2a721606e94745a8aa
      readOnly: true
      type: string
      x-auditable: true
    secondary-dns_components-schemas-name:
      description: The name of the peer.
      example: my-peer-1
      type: string
      x-auditable: true
    secondary-dns_peer:
      properties:
        id:
          $ref: '#/components/schemas/secondary-dns_components-schemas-identifier'
        ip:
          $ref: '#/components/schemas/secondary-dns_ip'
        ixfr_enable:
          $ref: '#/components/schemas/secondary-dns_ixfr_enable'
        name:
          $ref: '#/components/schemas/secondary-dns_components-schemas-name'
        port:
          $ref: '#/components/schemas/secondary-dns_port'
        tsig_id:
          $ref: '#/components/schemas/secondary-dns_tsig_id'
      required:
        - id
        - name
      type: object
    secondary-dns_schemas-response_collection:
      allOf:
        - $ref: '#/components/schemas/secondary-dns_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/secondary-dns_peer'
              type: array
    secondary-dns_schemas-single_response:
      allOf:
        - $ref: '#/components/schemas/secondary-dns_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/secondary-dns_peer'
