openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/secondary_dns/tsigs:
    get:
      description: List TSIGs.
      operationId: secondary-dns-(-tsig)-list-tsi-gs
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_response_collection'
          description: List TSIGs response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/secondary-dns_response_collection'
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: List TSIGs response failure
      security:
        - api_email: []
          api_key: []
      summary: List TSIGs
      tags:
        - Secondary DNS (TSIG)
      x-api-token-group:
        - Account Settings Write
        - Account Settings Read
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    post:
      description: Create TSIG.
      operationId: secondary-dns-(-tsig)-create-tsig
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/secondary-dns_tsig'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_single_response'
          description: Create TSIG response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/secondary-dns_single_response'
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: Create TSIG response failure
      security:
        - api_email: []
          api_key: []
      summary: Create TSIG
      tags:
        - Secondary DNS (TSIG)
      x-api-token-group:
        - Account Settings Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/secondary_dns/tsigs/{tsig_id}:
    get:
      description: Get TSIG.
      operationId: secondary-dns-(-tsig)-tsig-details
      parameters:
        - in: path
          name: tsig_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_schemas-identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_single_response'
          description: TSIG Details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/secondary-dns_single_response'
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: TSIG Details response failure
      security:
        - api_email: []
          api_key: []
      summary: TSIG Details
      tags:
        - Secondary DNS (TSIG)
      x-api-token-group:
        - Account Settings Write
        - Account Settings Read
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    put:
      description: Modify TSIG.
      operationId: secondary-dns-(-tsig)-update-tsig
      parameters:
        - in: path
          name: tsig_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_schemas-identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/secondary-dns_tsig'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_single_response'
          description: Update TSIG response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/secondary-dns_single_response'
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: Update TSIG response failure
      security:
        - api_email: []
          api_key: []
      summary: Update TSIG
      tags:
        - Secondary DNS (TSIG)
      x-api-token-group:
        - Account Settings Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    delete:
      description: Delete TSIG.
      operationId: secondary-dns-(-tsig)-delete-tsig
      parameters:
        - in: path
          name: tsig_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_schemas-identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_account_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_schemas-id_response'
          description: Delete TSIG response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/secondary-dns_schemas-id_response'
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: Delete TSIG response failure
      security:
        - api_email: []
          api_key: []
      summary: Delete TSIG
      tags:
        - Secondary DNS (TSIG)
      x-api-token-group:
        - Account Settings Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    secondary-dns_account_identifier:
      example: 01a7362d577a6c3019a474fd6f485823
      readOnly: true
      type: string
      x-auditable: true
    secondary-dns_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/secondary-dns_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/secondary-dns_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    secondary-dns_response_collection:
      allOf:
        - $ref: '#/components/schemas/secondary-dns_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/secondary-dns_tsig'
              type: array
    secondary-dns_schemas-id_response:
      allOf:
        - $ref: '#/components/schemas/secondary-dns_api-response-single'
        - properties:
            result:
              properties:
                id:
                  $ref: '#/components/schemas/secondary-dns_schemas-identifier'
              type: object
    secondary-dns_schemas-identifier:
      example: 69cd1e104af3e6ed3cb344f263fd0d5a
      readOnly: true
      type: string
      x-auditable: true
    secondary-dns_single_response:
      allOf:
        - $ref: '#/components/schemas/secondary-dns_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/secondary-dns_tsig'
    secondary-dns_tsig:
      properties:
        algo:
          $ref: '#/components/schemas/secondary-dns_algo'
        id:
          $ref: '#/components/schemas/secondary-dns_schemas-identifier'
        name:
          $ref: '#/components/schemas/secondary-dns_schemas-name'
        secret:
          $ref: '#/components/schemas/secondary-dns_secret'
      required:
        - id
        - name
        - secret
        - algo
      type: object
