openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/secondary_dns/acls:
    get:
      description: List ACLs.
      operationId: secondary-dns-(-acl)-list-ac-ls
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/secondary-dns_components-schemas-response_collection
          description: List ACLs response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/secondary-dns_components-schemas-response_collection
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: List ACLs response failure
      security:
        - api_email: []
          api_key: []
      summary: List ACLs
      tags:
        - Secondary DNS (ACL)
      x-api-token-group:
        - Account Settings Write
        - Account Settings Read
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    post:
      description: Create ACL.
      operationId: secondary-dns-(-acl)-create-acl
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                ip_range:
                  $ref: '#/components/schemas/secondary-dns_ip_range'
                name:
                  $ref: >-
                    #/components/schemas/secondary-dns_acl_components-schemas-name
              required:
                - name
                - ip_range
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/secondary-dns_components-schemas-single_response
          description: Create ACL response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/secondary-dns_components-schemas-single_response
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: Create ACL response failure
      security:
        - api_email: []
          api_key: []
      summary: Create ACL
      tags:
        - Secondary DNS (ACL)
      x-api-token-group:
        - Account Settings Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/secondary_dns/acls/{acl_id}:
    get:
      description: Get ACL.
      operationId: secondary-dns-(-acl)-acl-details
      parameters:
        - in: path
          name: acl_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_components-schemas-identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/secondary-dns_components-schemas-single_response
          description: ACL Details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/secondary-dns_components-schemas-single_response
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: ACL Details response failure
      security:
        - api_email: []
          api_key: []
      summary: ACL Details
      tags:
        - Secondary DNS (ACL)
      x-api-token-group:
        - Account Settings Write
        - Account Settings Read
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    put:
      description: Modify ACL.
      operationId: secondary-dns-(-acl)-update-acl
      parameters:
        - in: path
          name: acl_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_components-schemas-identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/secondary-dns_acl'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/secondary-dns_components-schemas-single_response
          description: Update ACL response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/secondary-dns_components-schemas-single_response
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: Update ACL response failure
      security:
        - api_email: []
          api_key: []
      summary: Update ACL
      tags:
        - Secondary DNS (ACL)
      x-api-token-group:
        - Account Settings Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    delete:
      description: Delete ACL.
      operationId: secondary-dns-(-acl)-delete-acl
      parameters:
        - in: path
          name: acl_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_components-schemas-identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_account_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/secondary-dns_components-schemas-id_response
          description: Delete ACL response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/secondary-dns_components-schemas-id_response
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: Delete ACL response failure
      security:
        - api_email: []
          api_key: []
      summary: Delete ACL
      tags:
        - Secondary DNS (ACL)
      x-api-token-group:
        - Account Settings Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    secondary-dns_account_identifier:
      example: 01a7362d577a6c3019a474fd6f485823
      readOnly: true
      type: string
      x-auditable: true
    secondary-dns_acl:
      properties:
        id:
          $ref: '#/components/schemas/secondary-dns_components-schemas-identifier'
        ip_range:
          $ref: '#/components/schemas/secondary-dns_ip_range'
        name:
          $ref: '#/components/schemas/secondary-dns_acl_components-schemas-name'
      required:
        - id
        - name
        - ip_range
      type: object
    secondary-dns_acl_components-schemas-name:
      description: The name of the acl.
      example: my-acl-1
      type: string
      x-auditable: true
    secondary-dns_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/secondary-dns_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/secondary-dns_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    secondary-dns_components-schemas-id_response:
      allOf:
        - $ref: '#/components/schemas/secondary-dns_api-response-single'
        - properties:
            result:
              properties:
                id:
                  $ref: >-
                    #/components/schemas/secondary-dns_components-schemas-identifier
              type: object
    secondary-dns_components-schemas-identifier:
      example: 23ff594956f20c2a721606e94745a8aa
      readOnly: true
      type: string
      x-auditable: true
    secondary-dns_components-schemas-response_collection:
      allOf:
        - $ref: '#/components/schemas/secondary-dns_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/secondary-dns_acl'
              type: array
    secondary-dns_components-schemas-single_response:
      allOf:
        - $ref: '#/components/schemas/secondary-dns_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/secondary-dns_acl'
    secondary-dns_ip_range:
      description: >-
        Allowed IPv4/IPv6 address range of primary or secondary nameservers.
        This will be applied for the entire account. The IP range is used to
        allow additional NOTIFY IPs for secondary zones and IPs Cloudflare
        allows AXFR/IXFR requests from for primary zones. CIDRs are limited to a
        maximum of /24 for IPv4 and /64 for IPv6 respectively.
      example: 192.0.2.53/28
      type: string
      x-auditable: true
