openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/secondary_dns/outgoing:
    get:
      description: Get primary zone configuration for outgoing zone transfers.
      operationId: secondary-dns-(-primary-zone)-primary-zone-configuration-details
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_single_response_outgoing'
          description: Primary Zone Configuration Details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/secondary-dns_single_response_outgoing
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: Primary Zone Configuration Details response failure
      security:
        - api_email: []
          api_key: []
      summary: Primary Zone Configuration Details
      tags:
        - Secondary DNS (Primary Zone)
      x-api-token-group:
        - Zone Settings Write
        - Zone Settings Read
        - DNS Read
        - Zone Write
        - DNS Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    post:
      description: Create primary zone configuration for outgoing zone transfers.
      operationId: secondary-dns-(-primary-zone)-create-primary-zone-configuration
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/secondary-dns_single_request_outgoing'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_single_response_outgoing'
          description: Create Primary Zone Configuration response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/secondary-dns_single_response_outgoing
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: Create Primary Zone Configuration response failure
      security:
        - api_email: []
          api_key: []
      summary: Create Primary Zone Configuration
      tags:
        - Secondary DNS (Primary Zone)
      x-api-token-group:
        - Zone Settings Write
        - Zone Write
        - DNS Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    put:
      description: Update primary zone configuration for outgoing zone transfers.
      operationId: secondary-dns-(-primary-zone)-update-primary-zone-configuration
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/secondary-dns_single_request_outgoing'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_single_response_outgoing'
          description: Update Primary Zone Configuration response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/secondary-dns_single_response_outgoing
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: Update Primary Zone Configuration response failure
      security:
        - api_email: []
          api_key: []
      summary: Update Primary Zone Configuration
      tags:
        - Secondary DNS (Primary Zone)
      x-api-token-group:
        - Zone Settings Write
        - Zone Write
        - DNS Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    delete:
      description: Delete primary zone configuration for outgoing zone transfers.
      operationId: secondary-dns-(-primary-zone)-delete-primary-zone-configuration
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_id_response'
          description: Delete Primary Zone Configuration response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/secondary-dns_id_response'
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: Delete Primary Zone Configuration response failure
      security:
        - api_email: []
          api_key: []
      summary: Delete Primary Zone Configuration
      tags:
        - Secondary DNS (Primary Zone)
      x-api-token-group:
        - Zone Settings Write
        - Zone Write
        - DNS Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /zones/{zone_id}/secondary_dns/outgoing/disable:
    post:
      description: >-
        Disable outgoing zone transfers for primary zone and clears IXFR backlog
        of primary zone.
      operationId: secondary-dns-(-primary-zone)-disable-outgoing-zone-transfers
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_disable_transfer_response'
          description: Disable Outgoing Zone Transfers response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/secondary-dns_disable_transfer_response
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: Disable Outgoing Zone Transfers response failure
      security:
        - api_email: []
          api_key: []
      summary: Disable Outgoing Zone Transfers
      tags:
        - Secondary DNS (Primary Zone)
      x-api-token-group:
        - Zone Settings Write
        - Zone Write
        - DNS Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /zones/{zone_id}/secondary_dns/outgoing/enable:
    post:
      description: Enable outgoing zone transfers for primary zone.
      operationId: secondary-dns-(-primary-zone)-enable-outgoing-zone-transfers
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_enable_transfer_response'
          description: Enable Outgoing Zone Transfers response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/secondary-dns_enable_transfer_response
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: Enable Outgoing Zone Transfers response failure
      security:
        - api_email: []
          api_key: []
      summary: Enable Outgoing Zone Transfers
      tags:
        - Secondary DNS (Primary Zone)
      x-api-token-group:
        - Zone Settings Write
        - Zone Write
        - DNS Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /zones/{zone_id}/secondary_dns/outgoing/force_notify:
    post:
      description: >-
        Notifies the secondary nameserver(s) and clears IXFR backlog of primary
        zone.
      operationId: secondary-dns-(-primary-zone)-force-dns-notify
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_schemas-force_response'
          description: Force DNS NOTIFY response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/secondary-dns_schemas-force_response'
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: Force DNS NOTIFY response failure
      security:
        - api_email: []
          api_key: []
      summary: Force DNS NOTIFY
      tags:
        - Secondary DNS (Primary Zone)
      x-api-token-group:
        - Zone Settings Write
        - Zone Write
        - DNS Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /zones/{zone_id}/secondary_dns/outgoing/status:
    get:
      description: Get primary zone transfer status.
      operationId: secondary-dns-(-primary-zone)-get-outgoing-zone-transfer-status
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/secondary-dns_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_enable_transfer_response'
          description: Get Outgoing Zone Transfer Status response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/secondary-dns_enable_transfer_response
                  - $ref: >-
                      #/components/schemas/secondary-dns_api-response-common-failure
          description: Get Outgoing Zone Transfer Status response failure
      security:
        - api_email: []
          api_key: []
      summary: Get Outgoing Zone Transfer Status
      tags:
        - Secondary DNS (Primary Zone)
      x-api-token-group:
        - Zone Settings Write
        - Zone Settings Read
        - DNS Read
        - Zone Write
        - DNS Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    secondary-dns_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/secondary-dns_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/secondary-dns_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    secondary-dns_disable_transfer_response:
      allOf:
        - $ref: '#/components/schemas/secondary-dns_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/secondary-dns_disable_transfer_result'
    secondary-dns_enable_transfer_response:
      allOf:
        - $ref: '#/components/schemas/secondary-dns_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/secondary-dns_enable_transfer_result'
    secondary-dns_id_response:
      allOf:
        - $ref: '#/components/schemas/secondary-dns_api-response-single'
        - properties:
            result:
              properties:
                id:
                  $ref: '#/components/schemas/secondary-dns_identifier'
              type: object
    secondary-dns_identifier:
      example: 269d8f4853475ca241c4e730be286b20
      readOnly: true
      type: string
      x-auditable: true
    secondary-dns_schemas-force_response:
      allOf:
        - $ref: '#/components/schemas/secondary-dns_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/secondary-dns_schemas-force_result'
    secondary-dns_single_request_outgoing:
      properties:
        id:
          $ref: '#/components/schemas/secondary-dns_identifier'
        name:
          $ref: '#/components/schemas/secondary-dns_name'
        peers:
          $ref: '#/components/schemas/secondary-dns_peers'
      required:
        - id
        - name
        - peers
    secondary-dns_single_response_outgoing:
      allOf:
        - $ref: '#/components/schemas/secondary-dns_api-response-single'
        - properties:
            result:
              properties:
                checked_time:
                  $ref: '#/components/schemas/secondary-dns_time'
                created_time:
                  $ref: '#/components/schemas/secondary-dns_time'
                id:
                  $ref: '#/components/schemas/secondary-dns_identifier'
                last_transferred_time:
                  $ref: '#/components/schemas/secondary-dns_time'
                name:
                  $ref: '#/components/schemas/secondary-dns_name'
                peers:
                  $ref: '#/components/schemas/secondary-dns_peers'
                soa_serial:
                  $ref: '#/components/schemas/secondary-dns_soa_serial'
              type: object
