openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/security-center/securitytxt:
    get:
      operationId: get-security-txt
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/security-center_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/security-center_api-response-common'
                  - properties:
                      result:
                        anyOf:
                          - $ref: '#/components/schemas/security-center_securityTxt'
          description: OK
        4XX:
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/security-center_api-response-common-failure
          description: Client Error
      security:
        - api_email: []
          api_key: []
        - api_token: []
      summary: Get security.txt
      tags:
        - security.txt
      x-api-token-group:
        - Zone Settings Write
        - Zone Settings Read
    put:
      operationId: update-security-txt
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/security-center_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/security-center_securityTxt'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/security-center_api-response-single'
          description: OK
        4XX:
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/security-center_api-response-common-failure
          description: Client Error
      security:
        - api_email: []
          api_key: []
        - api_token: []
      summary: Update security.txt
      tags:
        - security.txt
      x-api-token-group:
        - Zone Settings Write
    delete:
      operationId: delete-security-txt
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/security-center_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/security-center_api-response-single'
          description: OK
        4XX:
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/security-center_api-response-common-failure
          description: Client Error
      security:
        - api_email: []
          api_key: []
        - api_token: []
      summary: Delete security.txt
      tags:
        - security.txt
      x-api-token-group:
        - Zone Settings Write
components:
  schemas:
    security-center_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/security-center_messages'
        messages:
          $ref: '#/components/schemas/security-center_messages'
        success:
          description: Whether the API call was successful.
          enum:
            - true
          example: true
          type: boolean
      required:
        - success
        - errors
        - messages
      type: object
    security-center_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/security-center_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/security-center_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    security-center_api-response-single:
      allOf:
        - $ref: '#/components/schemas/security-center_api-response-common'
      type: object
    security-center_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
    security-center_securityTxt:
      properties:
        acknowledgments:
          example:
            - https://example.com/hall-of-fame.html
          items:
            format: uri
            type: string
            x-auditable: true
          type: array
        canonical:
          example:
            - https://www.example.com/.well-known/security.txt
          items:
            format: uri
            type: string
            x-auditable: true
          type: array
        contact:
          example:
            - mailto:security@example.com
            - tel:+1-201-555-0123
            - https://example.com/security-contact.html
          items:
            format: uri
            type: string
            x-auditable: true
          type: array
        enabled:
          example: true
          type: boolean
          x-auditable: true
        encryption:
          example:
            - https://example.com/pgp-key.txt
            - dns:5d2d37ab76d47d36._openpgpkey.example.com?type=OPENPGPKEY
            - openpgp4fpr:5f2de5521c63a801ab59ccb603d49de44b29100f
          items:
            format: uri
            type: string
          type: array
        expires:
          format: date-time
          type: string
          x-auditable: true
        hiring:
          example:
            - https://example.com/jobs.html
          items:
            format: uri
            type: string
            x-auditable: true
          type: array
        policy:
          example:
            - https://example.com/disclosure-policy.html
          items:
            format: uri
            type: string
            x-auditable: true
          type: array
        preferredLanguages:
          example: en, es, fr
          type: string
          x-auditable: true
      type: object
