openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/spectrum/apps:
    get:
      description: >-
        Retrieves a list of currently existing Spectrum applications inside a
        zone.
      operationId: spectrum-applications-list-spectrum-applications
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/spectrum-config_zone_identifier'
        - in: query
          name: page
          schema:
            description: >-
              Page number of paginated results. This parameter is required in
              order to use other pagination parameters. If included in the
              query, `result_info` will be present in the response.
            example: 1
            minimum: 1
            type: number
        - in: query
          name: per_page
          schema:
            default: 20
            description: Sets the maximum number of results per page.
            maximum: 100
            minimum: 1
            type: number
        - in: query
          name: direction
          schema:
            default: asc
            description: Sets the direction by which results are ordered.
            enum:
              - asc
              - desc
            example: desc
            type: string
        - in: query
          name: order
          schema:
            default: dns
            description: Application field by which results are ordered.
            enum:
              - protocol
              - app_id
              - created_on
              - modified_on
              - dns
            example: protocol
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/spectrum-config_app_config_collection'
          description: List Spectrum applications response
        4XX:
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/spectrum-config_api-response-common-failure
          description: List Spectrum applications response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: List Spectrum applications
      tags:
        - Spectrum Applications
      x-api-token-group:
        - Zone Settings Write
        - Zone Settings Read
    post:
      description: >-
        Creates a new Spectrum application from a configuration using a name for
        the origin.
      operationId: >-
        spectrum-applications-create-spectrum-application-using-a-name-for-the-origin
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/spectrum-config_zone_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/spectrum-config_update_app_config'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/spectrum-config_app_config_single'
          description: Create Spectrum application using a name for the origin response
        4XX:
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/spectrum-config_api-response-common-failure
          description: >-
            Create Spectrum application using a name for the origin response
            failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Create Spectrum application using a name for the origin
      tags:
        - Spectrum Applications
      x-api-token-group:
        - Zone Settings Write
  /zones/{zone_id}/spectrum/apps/{app_id}:
    get:
      description: >-
        Gets the application configuration of a specific application inside a
        zone.
      operationId: spectrum-applications-get-spectrum-application-configuration
      parameters:
        - in: path
          name: app_id
          required: true
          schema:
            $ref: '#/components/schemas/spectrum-config_app_identifier'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/spectrum-config_zone_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/spectrum-config_app_config_single'
          description: Get Spectrum application configuration response
        4XX:
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/spectrum-config_api-response-common-failure
          description: Get Spectrum application configuration response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get Spectrum application configuration
      tags:
        - Spectrum Applications
      x-api-token-group:
        - Zone Settings Write
        - Zone Settings Read
    put:
      description: >-
        Updates a previously existing application's configuration that uses a
        name for the origin.
      operationId: >-
        spectrum-applications-update-spectrum-application-configuration-using-a-name-for-the-origin
      parameters:
        - in: path
          name: app_id
          required: true
          schema:
            $ref: '#/components/schemas/spectrum-config_app_identifier'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/spectrum-config_zone_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/spectrum-config_update_app_config'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/spectrum-config_app_config_single'
          description: >-
            Update Spectrum application configuration using a name for the
            origin response
        4XX:
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/spectrum-config_api-response-common-failure
          description: >-
            Update Spectrum application configuration using a name for the
            origin response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Update Spectrum application configuration using a name for the origin
      tags:
        - Spectrum Applications
      x-api-token-group:
        - Zone Settings Write
    delete:
      description: Deletes a previously existing application.
      operationId: spectrum-applications-delete-spectrum-application
      parameters:
        - in: path
          name: app_id
          required: true
          schema:
            $ref: '#/components/schemas/spectrum-config_app_identifier'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/spectrum-config_zone_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/spectrum-config_api-response-single-id'
          description: Delete Spectrum application response
        4XX:
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/spectrum-config_api-response-common-failure
          description: Delete Spectrum application response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Delete Spectrum application
      tags:
        - Spectrum Applications
      x-api-token-group:
        - Zone Settings Write
components:
  schemas:
    spectrum-config_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/spectrum-config_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/spectrum-config_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    spectrum-config_api-response-single-id:
      allOf:
        - $ref: '#/components/schemas/spectrum-config_api-response-common'
        - properties:
            result:
              nullable: true
              properties:
                id:
                  $ref: '#/components/schemas/spectrum-config_identifier'
              required:
                - id
              type: object
      type: object
    spectrum-config_app_config_collection:
      allOf:
        - $ref: '#/components/schemas/spectrum-config_api-response-collection'
        - properties:
            result:
              oneOf:
                - items:
                    $ref: '#/components/schemas/spectrum-config_app_config'
                  type: array
                - items:
                    $ref: '#/components/schemas/spectrum-config_paygo_app_config'
                  type: array
    spectrum-config_app_config_single:
      allOf:
        - $ref: '#/components/schemas/spectrum-config_api-response-single'
        - properties:
            result:
              oneOf:
                - $ref: '#/components/schemas/spectrum-config_app_config'
                - $ref: '#/components/schemas/spectrum-config_paygo_app_config'
    spectrum-config_app_identifier:
      allOf:
        - description: App identifier.
        - readOnly: true
        - $ref: '#/components/schemas/spectrum-config_identifier'
    spectrum-config_update_app_config:
      oneOf:
        - $ref: '#/components/schemas/spectrum-config_app_config'
        - $ref: '#/components/schemas/spectrum-config_paygo_app_config'
    spectrum-config_zone_identifier:
      allOf:
        - description: Zone identifier.
        - readOnly: true
        - $ref: '#/components/schemas/spectrum-config_identifier'
