openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/ssl/verification:
    get:
      description: Get SSL Verification Info for a Zone.
      operationId: ssl-verification-ssl-verification-details
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_identifier'
        - in: query
          name: retry
          schema:
            description: Immediately retry SSL Verification.
            enum:
              - true
            example: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_ssl_verification_response_collection
          description: SSL Verification Details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_ssl_verification_response_collection
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_api-response-common-failure
          description: SSL Verification Details response failure
      security:
        - api_email: []
          api_key: []
      summary: SSL Verification Details
      tags:
        - SSL Verification
      x-api-token-group:
        - 'Access: Mutual TLS Certificates Write'
        - 'Access: Mutual TLS Certificates Read'
        - SSL and Certificates Write
        - SSL and Certificates Read
      x-cfPermissionsRequired:
        enum:
          - '#ssl:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /zones/{zone_id}/ssl/verification/{certificate_pack_id}:
    patch:
      description: >-
        Edit SSL validation method for a certificate pack. A PATCH request will
        request an immediate validation check on any certificate, and return the
        updated status. If a validation method is provided, the validation will
        be immediately attempted using that method.
      operationId: ssl-verification-edit-ssl-certificate-pack-validation-method
      parameters:
        - in: path
          name: certificate_pack_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_cert_pack_uuid'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/tls-certificates-and-hostnames_components-schemas-validation_method
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_ssl_validation_method_response_collection
          description: Edit SSL Certificate Pack Validation Method response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_ssl_validation_method_response_collection
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_api-response-common-failure
          description: Edit SSL Certificate Pack Validation Method response failure
      security:
        - api_email: []
          api_key: []
      summary: Edit SSL Certificate Pack Validation Method
      tags:
        - SSL Verification
      x-api-token-group:
        - 'Access: Mutual TLS Certificates Write'
        - 'Access: Mutual TLS Certificates Read'
        - SSL and Certificates Write
        - SSL and Certificates Read
      x-cfPermissionsRequired:
        enum:
          - '#ssl:read'
          - '#ssl:edit'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    tls-certificates-and-hostnames_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/tls-certificates-and-hostnames_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/tls-certificates-and-hostnames_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    tls-certificates-and-hostnames_cert_pack_uuid:
      description: Certificate Pack UUID.
      example: a77f8bd7-3b47-46b4-a6f1-75cf98109948
      type: string
      x-auditable: true
    tls-certificates-and-hostnames_components-schemas-validation_method:
      properties:
        validation_method:
          $ref: >-
            #/components/schemas/tls-certificates-and-hostnames_validation_method_definition
      required:
        - validation_method
      type: object
    tls-certificates-and-hostnames_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    tls-certificates-and-hostnames_ssl_validation_method_response_collection:
      allOf:
        - $ref: >-
            #/components/schemas/tls-certificates-and-hostnames_api-response-single
        - properties:
            result:
              properties:
                status:
                  $ref: >-
                    #/components/schemas/tls-certificates-and-hostnames_validation_method_components-schemas-status
                validation_method:
                  $ref: >-
                    #/components/schemas/tls-certificates-and-hostnames_validation_method_definition
    tls-certificates-and-hostnames_ssl_verification_response_collection:
      allOf:
        - properties:
            result:
              items:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_verification
              type: array
