openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/stream/{identifier}/captions:
    get:
      description: Lists the available captions or subtitles for a specific video.
      operationId: stream-subtitles/-captions-list-captions-or-subtitles
      parameters:
        - in: path
          name: identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_language_response_collection'
          description: List captions or subtitles response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: List captions or subtitles response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List captions or subtitles
      tags:
        - Stream Subtitles/Captions
      x-api-token-group:
        - Stream Write
        - Stream Read
  /accounts/{account_id}/stream/{identifier}/captions/{language}:
    get:
      description: Lists the captions or subtitles for provided language.
      operationId: stream-subtitles/-captions-get-caption-or-subtitle-for-language
      parameters:
        - in: path
          name: language
          required: true
          schema:
            $ref: '#/components/schemas/stream_language'
        - in: path
          name: identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_language_response_single'
          description: List captions or subtitles response for a provided language.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: List captions or subtitles response for a provided language.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List captions or subtitles for a provided language
      tags:
        - Stream Subtitles/Captions
      x-api-token-group:
        - Stream Write
        - Stream Read
    put:
      description: >-
        Uploads the caption or subtitle file to the endpoint for a specific
        BCP47 language. One caption or subtitle file per language is allowed.
      operationId: stream-subtitles/-captions-upload-captions-or-subtitles
      parameters:
        - in: path
          name: language
          required: true
          schema:
            $ref: '#/components/schemas/stream_language'
        - in: path
          name: identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_schemas-identifier'
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/stream_caption_basic_upload'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_language_response_single'
          description: Upload captions or subtitles response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: Upload captions or subtitles response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Upload captions or subtitles
      tags:
        - Stream Subtitles/Captions
      x-api-token-group:
        - Stream Write
    delete:
      description: Removes the captions or subtitles from a video.
      operationId: stream-subtitles/-captions-delete-captions-or-subtitles
      parameters:
        - in: path
          name: language
          required: true
          schema:
            $ref: '#/components/schemas/stream_language'
        - in: path
          name: identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_schemas-identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/stream_api-response-common'
                  - properties:
                      result:
                        example: ''
                        type: string
                        x-auditable: true
                    type: object
          description: Delete captions or subtitles response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: Delete captions or subtitles response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete captions or subtitles
      tags:
        - Stream Subtitles/Captions
      x-api-token-group:
        - Stream Write
  /accounts/{account_id}/stream/{identifier}/captions/{language}/generate:
    post:
      description: Generate captions or subtitles for provided language via AI.
      operationId: stream-subtitles/-captions-generate-caption-or-subtitle-for-language
      parameters:
        - in: path
          name: language
          required: true
          schema:
            $ref: '#/components/schemas/stream_language'
        - in: path
          name: identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_language_response_single'
          description: Generate captions or subtitles response for a provided language.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: Generate captions or subtitles response for a provided language.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Generate captions or subtitles for a provided language via AI
      tags:
        - Stream Subtitles/Captions
  /accounts/{account_id}/stream/{identifier}/captions/{language}/vtt:
    get:
      description: Return WebVTT captions for a provided language.
      operationId: stream-subtitles/-captions-get-vtt-caption-or-subtitle
      parameters:
        - in: path
          name: language
          required: true
          schema:
            $ref: '#/components/schemas/stream_language'
        - in: path
          name: identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_schemas-identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            text/vtt:
              schema:
                example: |
                  'WEBVTT
                   00:00:00.000 --> 00:00:02.480
                   This is example response'
                type: string
          description: Return WebVTT caption or subtitle response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: Return WebVTT caption or subtitle response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Return WebVTT captions for a provided language
      tags:
        - Stream Subtitles/Captions
      x-api-token-group:
        - Stream Write
        - Stream Read
components:
  schemas:
    stream_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/stream_messages'
        messages:
          $ref: '#/components/schemas/stream_messages'
        success:
          description: Whether the API call was successful.
          enum:
            - true
          example: true
          type: boolean
      required:
        - success
        - errors
        - messages
      type: object
    stream_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/stream_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/stream_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    stream_caption_basic_upload:
      properties:
        file:
          description: The WebVTT file containing the caption or subtitle content.
          example: '@/Users/kyle/Desktop/tr.vtt'
          type: string
          x-auditable: true
      required:
        - file
      type: object
    stream_identifier:
      description: A Cloudflare-generated unique identifier for a media item.
      example: ea95132c15732412d22c1476fa83f27a
      maxLength: 32
      type: string
      x-auditable: true
    stream_language:
      description: The language tag in BCP 47 format.
      example: tr
      type: string
      x-auditable: true
    stream_language_response_collection:
      allOf:
        - $ref: '#/components/schemas/stream_api-response-common'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/stream_captions'
              type: array
          type: object
    stream_language_response_single:
      allOf:
        - $ref: '#/components/schemas/stream_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/stream_captions'
          type: object
    stream_schemas-identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
