openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/stream/live_inputs:
    get:
      description: >-
        Lists the live inputs created for an account. To get the credentials
        needed to stream to a specific live input, request a single live input.
      operationId: stream-live-inputs-list-live-inputs
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_schemas-identifier'
        - in: query
          name: include_counts
          schema:
            $ref: '#/components/schemas/stream_include_counts'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_live_input_response_collection'
          description: List live inputs response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: List live inputs response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List live inputs
      tags:
        - Stream Live Inputs
      x-api-token-group:
        - Stream Write
        - Stream Read
    post:
      description: >-
        Creates a live input, and returns credentials that you or your users can
        use to stream live video to Cloudflare Stream.
      operationId: stream-live-inputs-create-a-live-input
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/stream_create_input_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_live_input_response_single'
          description: Create a live input response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: Create a live input response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create a live input
      tags:
        - Stream Live Inputs
      x-api-token-group:
        - Stream Write
  /accounts/{account_id}/stream/live_inputs/{live_input_identifier}:
    get:
      description: Retrieves details of an existing live input.
      operationId: stream-live-inputs-retrieve-a-live-input
      parameters:
        - in: path
          name: live_input_identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_live_input_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_live_input_response_single'
          description: Retrieve a live input response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: Retrieve a live input response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Retrieve a live input
      tags:
        - Stream Live Inputs
      x-api-token-group:
        - Stream Write
        - Stream Read
    put:
      description: Updates a specified live input.
      operationId: stream-live-inputs-update-a-live-input
      parameters:
        - in: path
          name: live_input_identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_live_input_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/stream_update_input_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_live_input_response_single'
          description: Update a live input response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: Update a live input response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update a live input
      tags:
        - Stream Live Inputs
      x-api-token-group:
        - Stream Write
    delete:
      description: >-
        Prevents a live input from being streamed to and makes the live input
        inaccessible to any future API calls.
      operationId: stream-live-inputs-delete-a-live-input
      parameters:
        - in: path
          name: live_input_identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_live_input_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_schemas-identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json: {}
          description: Delete a live input response.
        4XX:
          content:
            application/json: {}
          description: Delete a live input response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete a live input
      tags:
        - Stream Live Inputs
      x-api-token-group:
        - Stream Write
  /accounts/{account_id}/stream/live_inputs/{live_input_identifier}/outputs:
    get:
      description: Retrieves all outputs associated with a specified live input.
      operationId: >-
        stream-live-inputs-list-all-outputs-associated-with-a-specified-live-input
      parameters:
        - in: path
          name: live_input_identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_live_input_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_output_response_collection'
          description: List all outputs associated with a specified live input response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: >-
            List all outputs associated with a specified live input response
            failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List all outputs associated with a specified live input
      tags:
        - Stream Live Inputs
      x-api-token-group:
        - Stream Write
        - Stream Read
    post:
      description: "Creates a new output that can be used to simulcast or restream live video to other RTMP or SRT destinations. Outputs are always linked to a specific live input —\_one live input can have many outputs."
      operationId: stream-live-inputs-create-a-new-output,-connected-to-a-live-input
      parameters:
        - in: path
          name: live_input_identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_live_input_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/stream_create_output_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_output_response_single'
          description: Create a new output, connected to a live input response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: Create a new output, connected to a live input response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create a new output, connected to a live input
      tags:
        - Stream Live Inputs
  /accounts/{account_id}/stream/live_inputs/{live_input_identifier}/outputs/{output_identifier}:
    put:
      description: Updates the state of an output.
      operationId: stream-live-inputs-update-an-output
      parameters:
        - in: path
          name: output_identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_output_identifier'
        - in: path
          name: live_input_identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_live_input_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/stream_update_output_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_output_response_single'
          description: Update an output response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: Update an output response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update an output
      tags:
        - Stream Live Inputs
      x-api-token-group:
        - Stream Write
    delete:
      description: Deletes an output and removes it from the associated live input.
      operationId: stream-live-inputs-delete-an-output
      parameters:
        - in: path
          name: output_identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_output_identifier'
        - in: path
          name: live_input_identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_live_input_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_schemas-identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json: {}
          description: Delete an output response.
        4XX:
          content:
            application/json: {}
          description: Delete an output response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete an output
      tags:
        - Stream Live Inputs
      x-api-token-group:
        - Stream Write
components:
  schemas:
    stream_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/stream_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/stream_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    stream_create_input_request:
      properties:
        defaultCreator:
          $ref: '#/components/schemas/stream_live_input_default_creator'
        deleteRecordingAfterDays:
          $ref: '#/components/schemas/stream_live_input_recording_deletion'
        meta:
          $ref: '#/components/schemas/stream_live_input_metadata'
        recording:
          $ref: '#/components/schemas/stream_live_input_recording_settings'
    stream_create_output_request:
      properties:
        enabled:
          $ref: '#/components/schemas/stream_output_enabled'
        streamKey:
          $ref: '#/components/schemas/stream_output_streamKey'
        url:
          $ref: '#/components/schemas/stream_output_url'
      required:
        - url
        - streamKey
    stream_include_counts:
      default: false
      description: >-
        Includes the total number of videos associated with the submitted query
        parameters.
      example: true
      type: boolean
    stream_live_input_identifier:
      description: A unique identifier for a live input.
      example: 66be4bf738797e01e1fca35a7bdecdcd
      maxLength: 32
      type: string
      x-auditable: true
    stream_live_input_response_collection:
      allOf:
        - $ref: '#/components/schemas/stream_api-response-common'
        - properties:
            result:
              properties:
                liveInputs:
                  items:
                    $ref: '#/components/schemas/stream_live_input_object_without_url'
                  type: array
                range:
                  description: >-
                    The total number of remaining live inputs based on cursor
                    position.
                  example: 1000
                  type: integer
                total:
                  description: >-
                    The total number of live inputs that match the provided
                    filters.
                  example: 35586
                  type: integer
              type: object
          type: object
    stream_live_input_response_single:
      allOf:
        - $ref: '#/components/schemas/stream_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/stream_live_input'
          type: object
    stream_output_identifier:
      description: A unique identifier for the output.
      example: baea4d9c515887b80289d5c33cf01145
      maxLength: 32
      type: string
      x-auditable: true
    stream_output_response_collection:
      allOf:
        - $ref: '#/components/schemas/stream_api-response-common'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/stream_output'
              type: array
          type: object
    stream_output_response_single:
      allOf:
        - $ref: '#/components/schemas/stream_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/stream_output'
          type: object
    stream_schemas-identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
    stream_update_input_request:
      properties:
        defaultCreator:
          $ref: '#/components/schemas/stream_live_input_default_creator'
        deleteRecordingAfterDays:
          $ref: '#/components/schemas/stream_live_input_recording_deletion'
        meta:
          $ref: '#/components/schemas/stream_live_input_metadata'
        recording:
          $ref: '#/components/schemas/stream_live_input_recording_settings'
    stream_update_output_request:
      properties:
        enabled:
          $ref: '#/components/schemas/stream_output_enabled'
      required:
        - enabled
