openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/stream/watermarks:
    get:
      description: Lists all watermark profiles for an account.
      operationId: stream-watermark-profile-list-watermark-profiles
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_watermark_response_collection'
          description: List watermark profiles response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: List watermark profiles response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List watermark profiles
      tags:
        - Stream Watermark Profile
      x-api-token-group:
        - Stream Write
        - Stream Read
    post:
      description: >-
        Creates watermark profiles using a single `HTTP POST
        multipart/form-data` request.
      operationId: stream-watermark-profile-create-watermark-profiles-via-basic-upload
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_account_identifier'
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/stream_watermark_basic_upload'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_watermark_response_single'
          description: Create watermark profiles via basic upload response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: Create watermark profiles via basic upload response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create watermark profiles via basic upload
      tags:
        - Stream Watermark Profile
      x-api-token-group:
        - Stream Write
  /accounts/{account_id}/stream/watermarks/{identifier}:
    get:
      description: Retrieves details for a single watermark profile.
      operationId: stream-watermark-profile-watermark-profile-details
      parameters:
        - in: path
          name: identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_watermark_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_account_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_watermark_response_single'
          description: Watermark profile details response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: Watermark profile details response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Watermark profile details
      tags:
        - Stream Watermark Profile
      x-api-token-group:
        - Stream Write
        - Stream Read
    delete:
      description: Deletes a watermark profile.
      operationId: stream-watermark-profile-delete-watermark-profiles
      parameters:
        - in: path
          name: identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_watermark_identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_account_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/stream_api-response-single'
                  - properties:
                      result:
                        example: ''
                        type: string
                        x-auditable: true
                    type: object
          description: Delete watermark profiles response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: Delete watermark profiles response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete watermark profiles
      tags:
        - Stream Watermark Profile
      x-api-token-group:
        - Stream Write
components:
  schemas:
    stream_account_identifier:
      description: The account identifier tag.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
    stream_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/stream_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/stream_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    stream_api-response-single:
      allOf:
        - $ref: '#/components/schemas/stream_api-response-common'
      type: object
    stream_watermark_basic_upload:
      properties:
        file:
          description: The image file to upload.
          example: '@/Users/rchen/Downloads/watermark.png'
          type: string
          x-auditable: true
        name:
          $ref: '#/components/schemas/stream_name'
        opacity:
          $ref: '#/components/schemas/stream_opacity'
        padding:
          $ref: '#/components/schemas/stream_padding'
        position:
          $ref: '#/components/schemas/stream_position'
        scale:
          $ref: '#/components/schemas/stream_scale'
      required:
        - file
      type: object
    stream_watermark_identifier:
      description: The unique identifier for a watermark profile.
      example: ea95132c15732412d22c1476fa83f27a
      maxLength: 32
      type: string
      x-auditable: true
    stream_watermark_response_collection:
      allOf:
        - $ref: '#/components/schemas/stream_api-response-common'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/stream_watermarks'
              type: array
          type: object
    stream_watermark_response_single:
      allOf:
        - $ref: '#/components/schemas/stream_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/stream_watermarks'
          type: object
