openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/stream/{identifier}/audio:
    get:
      description: >-
        Lists additional audio tracks on a video. Note this API will not return
        information for audio attached to the video upload.
      operationId: list-audio-tracks
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_account_identifier'
        - in: path
          name: identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_listAudioTrackResponse'
          description: Lists additional audio tracks on a video.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: Lists additional audio tracks on a video response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List additional audio tracks on a video
      tags:
        - Stream Audio Tracks
      x-api-token-group:
        - Stream Write
        - Stream Read
  /accounts/{account_id}/stream/{identifier}/audio/copy:
    post:
      description: >-
        Adds an additional audio track to a video using the provided audio track
        URL.
      operationId: add-audio-track
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_account_identifier'
        - in: path
          name: identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/stream_copyAudioTrack'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_addAudioTrackResponse'
          description: Add audio tracks to a video.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: Add audio tracks to a video response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Add audio tracks to a video
      tags:
        - Stream Audio Tracks
  /accounts/{account_id}/stream/{identifier}/audio/{audio_identifier}:
    patch:
      description: >-
        Edits additional audio tracks on a video. Editing the default status of
        an audio track to `true` will mark all other audio tracks on the video
        default status to `false`.
      operationId: edit-audio-tracks
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_account_identifier'
        - in: path
          name: identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_identifier'
        - in: path
          name: audio_identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_audio_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/stream_editAudioTrack'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_addAudioTrackResponse'
          description: Edits additional audio tracks on a video.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: Edits additional audio tracks on a video response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Edit additional audio tracks on a video
      tags:
        - Stream Audio Tracks
      x-api-token-group:
        - Stream Write
    delete:
      description: >-
        Deletes additional audio tracks on a video. Deleting a default audio
        track is not allowed. You must assign another audio track as default
        prior to deletion.
      operationId: delete-audio-tracks
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/stream_account_identifier'
        - in: path
          name: identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_identifier'
        - in: path
          name: audio_identifier
          required: true
          schema:
            $ref: '#/components/schemas/stream_audio_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_deleted_response'
          description: Deletes additional audio tracks on a video.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_deleted_response'
          description: Deletes additional audio tracks on a video response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete additional audio tracks on a video
      tags:
        - Stream Audio Tracks
      x-api-token-group:
        - Stream Write
components:
  schemas:
    stream_account_identifier:
      description: The account identifier tag.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
    stream_addAudioTrackResponse:
      allOf:
        - $ref: '#/components/schemas/stream_api-response-common'
        - properties:
            result:
              $ref: '#/components/schemas/stream_additionalAudio'
          type: object
    stream_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/stream_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/stream_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    stream_audio_identifier:
      description: The unique identifier for an additional audio track.
      example: ea95132c15732412d22c1476fa83f27a
      maxLength: 32
      type: string
      x-auditable: true
    stream_copyAudioTrack:
      properties:
        label:
          $ref: '#/components/schemas/stream_audio_label'
        url:
          description: >-
            An audio track URL. The server must be publicly routable and support
            `HTTP HEAD` requests and `HTTP GET` range requests. The server
            should respond to `HTTP HEAD` requests with a `content-range` header
            that includes the size of the file.
          example: https://www.examplestorage.com/audio_file.mp3
          format: uri
          type: string
          x-auditable: true
      required:
        - label
      type: object
    stream_deleted_response:
      allOf:
        - $ref: '#/components/schemas/stream_api-response-single'
        - properties:
            result:
              example: ok
              type: string
          type: object
    stream_editAudioTrack:
      properties:
        default:
          $ref: '#/components/schemas/stream_audio_default'
        label:
          $ref: '#/components/schemas/stream_audio_label'
      type: object
    stream_identifier:
      description: A Cloudflare-generated unique identifier for a media item.
      example: ea95132c15732412d22c1476fa83f27a
      maxLength: 32
      type: string
      x-auditable: true
    stream_listAudioTrackResponse:
      allOf:
        - $ref: '#/components/schemas/stream_api-response-common'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/stream_additionalAudio'
              type: array
          type: object
