openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/acm/total_tls:
    get:
      description: Get Total TLS Settings for a Zone.
      operationId: total-tls-total-tls-settings-details
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_total_tls_settings_response
          description: Total TLS Settings Details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_total_tls_settings_response
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_api-response-common-failure
          description: Total TLS Settings Details response failure
      security:
        - api_email: []
          api_key: []
      summary: Total TLS Settings Details
      tags:
        - Total TLS
      x-api-token-group:
        - SSL and Certificates Write
        - SSL and Certificates Read
      x-cfPermissionsRequired:
        enum:
          - '#ssl:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    post:
      description: Set Total TLS Settings or disable the feature for a Zone.
      operationId: total-tls-enable-or-disable-total-tls
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/tls-certificates-and-hostnames_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                certificate_authority:
                  $ref: >-
                    #/components/schemas/tls-certificates-and-hostnames_components-schemas-certificate_authority
                enabled:
                  $ref: >-
                    #/components/schemas/tls-certificates-and-hostnames_components-schemas-enabled
              required:
                - enabled
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tls-certificates-and-hostnames_total_tls_settings_response
          description: Enable or Disable Total TLS response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_total_tls_settings_response
                  - $ref: >-
                      #/components/schemas/tls-certificates-and-hostnames_api-response-common-failure
          description: Enable or Disable Total TLS response failure
      security:
        - api_email: []
          api_key: []
      summary: Enable or Disable Total TLS
      tags:
        - Total TLS
      x-api-token-group:
        - SSL and Certificates Write
      x-cfPermissionsRequired:
        enum:
          - '#ssl:read'
          - '#ssl:edit'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    tls-certificates-and-hostnames_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/tls-certificates-and-hostnames_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/tls-certificates-and-hostnames_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    tls-certificates-and-hostnames_components-schemas-certificate_authority:
      description: >-
        The Certificate Authority that Total TLS certificates will be issued
        through.
      enum:
        - google
        - lets_encrypt
        - ssl_com
      example: google
      type: string
      x-auditable: true
    tls-certificates-and-hostnames_components-schemas-enabled:
      description: >-
        If enabled, Total TLS will order a hostname specific TLS certificate for
        any proxied A, AAAA, or CNAME record in your zone.
      example: true
      type: boolean
      x-auditable: true
    tls-certificates-and-hostnames_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    tls-certificates-and-hostnames_total_tls_settings_response:
      allOf:
        - $ref: >-
            #/components/schemas/tls-certificates-and-hostnames_api-response-single
        - properties:
            result:
              properties:
                certificate_authority:
                  $ref: >-
                    #/components/schemas/tls-certificates-and-hostnames_components-schemas-certificate_authority
                enabled:
                  $ref: >-
                    #/components/schemas/tls-certificates-and-hostnames_components-schemas-enabled
                validity_period:
                  $ref: >-
                    #/components/schemas/tls-certificates-and-hostnames_validity_period
