openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/abuse-reports/{report_type}:
    post:
      operationId: SubmitAbuseReport
      parameters:
        - description: The account ID of the submitter.
          in: path
          name: account_id
          required: true
          schema:
            example: 023e105f4ecef8ad9ca31a8372d0c353
            maxLength: 32
            type: string
        - description: 'The report type to be submitted. Example: abuse_general'
          in: path
          name: report_type
          required: true
          schema:
            $ref: '#/components/schemas/abuse-reports_ReportType'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/abuse-reports_SubmitReportRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/abuse-reports_SubmitReportResponse'
          description: Report submitted successfully
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/abuse-reports_SubmitErrorResponse'
          description: Report submitted with an error
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/abuse-reports_SubmitErrorResponse'
          description: Report submitted with an error
      security:
        - api_token: []
      summary: Submit the Abuse Report of a particular type
      tags:
        - tseng-abuse-complaint-processor_other
      x-api-token-group:
        - Trust and Safety Write
components:
  schemas:
    abuse-reports_ReportType:
      description: The abuse report type.
      type: string
    abuse-reports_SubmitErrorResponse:
      properties:
        error_code:
          $ref: '#/components/schemas/abuse-reports_ErrorCode'
        msg:
          description: The error message for the error
          type: string
        request:
          properties:
            act:
              $ref: '#/components/schemas/abuse-reports_ReportType'
          required:
            - act
          type: object
        result:
          description: The result should be 'error' for successful response
          type: string
      required:
        - request
        - result
        - msg
        - error_code
      type: object
    abuse-reports_SubmitReportRequest:
      discriminator:
        mapping:
          abuse_children: '#/components/schemas/abuse-reports_CSAMReport'
          abuse_dmca: '#/components/schemas/abuse-reports_DMCAReport'
          abuse_general: '#/components/schemas/abuse-reports_GeneralReport'
          abuse_ncsei: '#/components/schemas/abuse-reports_NCSEIReport'
          abuse_phishing: '#/components/schemas/abuse-reports_PhishingReport'
          abuse_registrar_whois: '#/components/schemas/abuse-reports_RegistrarWhoisReport'
          abuse_threat: '#/components/schemas/abuse-reports_ThreatReport'
          abuse_trademark: '#/components/schemas/abuse-reports_TrademarkReport'
        propertyName: act
      oneOf:
        - $ref: '#/components/schemas/abuse-reports_DMCAReport'
        - $ref: '#/components/schemas/abuse-reports_TrademarkReport'
        - $ref: '#/components/schemas/abuse-reports_GeneralReport'
        - $ref: '#/components/schemas/abuse-reports_PhishingReport'
        - $ref: '#/components/schemas/abuse-reports_CSAMReport'
        - $ref: '#/components/schemas/abuse-reports_ThreatReport'
        - $ref: '#/components/schemas/abuse-reports_RegistrarWhoisReport'
        - $ref: '#/components/schemas/abuse-reports_NCSEIReport'
    abuse-reports_SubmitReportResponse:
      properties:
        abuse_rand:
          description: The identifier for the submitted abuse report.
          type: string
        request:
          properties:
            act:
              $ref: '#/components/schemas/abuse-reports_ReportType'
          required:
            - act
          type: object
        result:
          description: The result should be 'success' for successful response
          type: string
      required:
        - request
        - result
        - abuse_rand
      type: object
