openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/teamnet/virtual_networks:
    get:
      description: Lists and filters virtual networks in an account.
      operationId: tunnel-virtual-network-list-virtual-networks
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/tunnel_account_id'
        - in: query
          name: id
          schema:
            $ref: '#/components/schemas/tunnel_virtual_network_id'
        - in: query
          name: name
          schema:
            $ref: '#/components/schemas/tunnel_virtual_network_name'
        - in: query
          name: is_default
          schema:
            description: >-
              If `true`, only include the default virtual network. If `false`,
              exclude the default virtual network. If empty, all virtual
              networks will be included.
            type: boolean
        - in: query
          name: is_deleted
          schema:
            description: >-
              If `true`, only include deleted virtual networks. If `false`,
              exclude deleted virtual networks. If empty, all virtual networks
              will be included.
            type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tunnel_vnet_response_collection'
          description: List virtual networks response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/tunnel_vnet_response_collection'
                  - $ref: '#/components/schemas/tunnel_api-response-common-failure'
          description: List virtual networks response failure
      security:
        - api_email: []
          api_key: []
        - api_token: []
        - user_service_key: []
      summary: List virtual networks
      tags:
        - Tunnel Virtual Network
      x-api-token-group:
        - Cloudflare One Networks Write
        - Cloudflare One Networks Read
        - Cloudflare Tunnel Write
        - Cloudflare Tunnel Read
    post:
      description: Adds a new virtual network to an account.
      operationId: tunnel-virtual-network-create-a-virtual-network
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/tunnel_account_id'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                comment:
                  $ref: '#/components/schemas/tunnel_virtual_network_comment'
                is_default:
                  deprecated: true
                  description: >-
                    If `true`, this virtual network is the default for the
                    account.
                  example: true
                  type: boolean
                  x-auditable: true
                  x-stainless-deprecation-message: Use the is_default_network property instead.
                  x-stainless-ignore: true
                is_default_network:
                  $ref: '#/components/schemas/tunnel_is_default_network_optional'
                name:
                  $ref: '#/components/schemas/tunnel_virtual_network_name'
              required:
                - name
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tunnel_vnet_response_single'
          description: Create a virtual network response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/tunnel_vnet_response_single'
                  - $ref: '#/components/schemas/tunnel_api-response-common-failure'
          description: Create a virtual network response failure
      security:
        - api_email: []
          api_key: []
        - api_token: []
        - user_service_key: []
      summary: Create a virtual network
      tags:
        - Tunnel Virtual Network
      x-api-token-group:
        - Cloudflare One Networks Write
        - Cloudflare Tunnel Write
  /accounts/{account_id}/teamnet/virtual_networks/{virtual_network_id}:
    get:
      description: Get a virtual network.
      operationId: tunnel-virtual-network-get
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/tunnel_account_id'
        - in: path
          name: virtual_network_id
          required: true
          schema:
            $ref: '#/components/schemas/tunnel_virtual_network_id'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                comment:
                  $ref: '#/components/schemas/tunnel_virtual_network_comment'
                is_default_network:
                  $ref: '#/components/schemas/tunnel_is_default_network'
                name:
                  $ref: '#/components/schemas/tunnel_virtual_network_name'
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tunnel_vnet_response_single'
          description: A virtual network response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/tunnel_vnet_response_single'
                  - $ref: '#/components/schemas/tunnel_api-response-common-failure'
          description: A virtual network response failure
      security:
        - api_email: []
          api_key: []
        - api_token: []
        - user_service_key: []
      summary: Get a virtual network
      tags:
        - Tunnel Virtual Network
    patch:
      description: Updates an existing virtual network.
      operationId: tunnel-virtual-network-update
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/tunnel_account_id'
        - in: path
          name: virtual_network_id
          required: true
          schema:
            $ref: '#/components/schemas/tunnel_virtual_network_id'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                comment:
                  $ref: '#/components/schemas/tunnel_virtual_network_comment'
                is_default_network:
                  $ref: '#/components/schemas/tunnel_is_default_network_optional'
                name:
                  $ref: '#/components/schemas/tunnel_virtual_network_name'
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tunnel_vnet_response_single'
          description: Update a virtual network response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/tunnel_vnet_response_single'
                  - $ref: '#/components/schemas/tunnel_api-response-common-failure'
          description: Update a virtual network response failure
      security:
        - api_email: []
          api_key: []
        - api_token: []
        - user_service_key: []
      summary: Update a virtual network
      tags:
        - Tunnel Virtual Network
      x-api-token-group:
        - Cloudflare One Networks Write
        - Cloudflare Tunnel Write
    delete:
      description: Deletes an existing virtual network.
      operationId: tunnel-virtual-network-delete
      parameters:
        - in: path
          name: virtual_network_id
          required: true
          schema:
            $ref: '#/components/schemas/tunnel_virtual_network_id'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/tunnel_account_id'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tunnel_vnet_response_single'
          description: Delete a virtual network response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/tunnel_vnet_response_single'
                  - $ref: '#/components/schemas/tunnel_api-response-common-failure'
          description: Delete a virtual network response failure
      security:
        - api_email: []
          api_key: []
        - api_token: []
        - user_service_key: []
      summary: Delete a virtual network
      tags:
        - Tunnel Virtual Network
      x-api-token-group:
        - Cloudflare One Networks Write
        - Cloudflare Tunnel Write
components:
  schemas:
    tunnel_account_id:
      description: Cloudflare account ID
      example: 699d98642c564d2e855e9661899b7252
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
    tunnel_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/tunnel_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/tunnel_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    tunnel_is_default_network:
      description: If `true`, this virtual network is the default for the account.
      example: true
      type: boolean
      x-auditable: true
      x-stainless-terraform-configurability: computed_optional
    tunnel_is_default_network_optional:
      default: false
      description: If `true`, this virtual network is the default for the account.
      example: false
      type: boolean
      x-auditable: true
      x-stainless-terraform-configurability: computed_optional
    tunnel_virtual_network_comment:
      description: Optional remark describing the virtual network.
      example: Staging VPC for data science
      maxLength: 256
      type: string
      x-auditable: true
    tunnel_virtual_network_id:
      description: UUID of the virtual network.
      example: f70ff985-a4ef-4643-bbbc-4a0ed4fc8415
      format: uuid
      type: string
      x-auditable: true
    tunnel_virtual_network_name:
      description: A user-friendly name for the virtual network.
      example: us-east-1-vpc
      maxLength: 256
      type: string
      x-auditable: true
    tunnel_vnet_response_collection:
      allOf:
        - $ref: '#/components/schemas/tunnel_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/tunnel_virtual-network'
              type: array
          type: object
    tunnel_vnet_response_single:
      allOf:
        - $ref: '#/components/schemas/tunnel_api-response-common'
        - properties:
            result:
              $ref: '#/components/schemas/tunnel_virtual-network'
          type: object
