openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/challenges/widgets:
    get:
      description: Lists all turnstile widgets of an account.
      operationId: accounts-turnstile-widgets-list
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/turnstile_api-response-common'
                  - properties:
                      result_info:
                        $ref: '#/components/schemas/turnstile_result_info'
                    type: object
                  - properties:
                      result:
                        items:
                          $ref: '#/components/schemas/turnstile_widget_list'
                        type: array
                    type: object
                type: object
          description: List Turnstile Widgets
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/turnstile_api-response-common-failure'
          description: List Turnstile Widgets Error
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: List Turnstile Widgets
      tags:
        - Turnstile
      x-api-token-group:
        - Turnstile Sites Write
        - Turnstile Sites Read
        - Account Settings Write
        - Account Settings Read
    post:
      description: Lists challenge widgets.
      operationId: accounts-turnstile-widget-create
      requestBody:
        content:
          application/json:
            schema:
              properties:
                bot_fight_mode:
                  $ref: '#/components/schemas/turnstile_bot_fight_mode'
                clearance_level:
                  $ref: '#/components/schemas/turnstile_clearance_level'
                domains:
                  $ref: '#/components/schemas/turnstile_domains'
                ephemeral_id:
                  $ref: '#/components/schemas/turnstile_ephemeral_id'
                mode:
                  $ref: '#/components/schemas/turnstile_widget_mode'
                name:
                  $ref: '#/components/schemas/turnstile_name'
                offlabel:
                  $ref: '#/components/schemas/turnstile_offlabel'
                region:
                  $ref: '#/components/schemas/turnstile_region'
              required:
                - name
                - mode
                - domains
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/turnstile_api-response-common'
                  - properties:
                      result_info:
                        $ref: '#/components/schemas/turnstile_result_info'
                    type: object
                  - properties:
                      result:
                        $ref: '#/components/schemas/turnstile_widget_detail'
                    type: object
                type: object
          description: Create Turnstile Widget Response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/turnstile_api-response-common-failure'
          description: Create Turnstile Widget Response Error
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Create a Turnstile Widget
      tags:
        - Turnstile
      x-api-token-group:
        - Turnstile Sites Write
        - Account Settings Write
  /accounts/{account_id}/challenges/widgets/{sitekey}:
    get:
      description: Show a single challenge widget configuration.
      operationId: accounts-turnstile-widget-get
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/turnstile_api-response-common'
                  - properties:
                      result:
                        $ref: '#/components/schemas/turnstile_widget_detail'
                    type: object
                type: object
          description: Turnstile Widget Details Response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/turnstile_api-response-common-failure'
          description: Turnstile Widget Details Response Error
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Turnstile Widget Details
      tags:
        - Turnstile
      x-api-token-group:
        - Turnstile Sites Write
        - Turnstile Sites Read
        - Account Settings Write
        - Account Settings Read
    put:
      description: Update the configuration of a widget.
      operationId: accounts-turnstile-widget-update
      requestBody:
        content:
          application/json:
            schema:
              properties:
                bot_fight_mode:
                  $ref: '#/components/schemas/turnstile_bot_fight_mode'
                clearance_level:
                  $ref: '#/components/schemas/turnstile_clearance_level'
                domains:
                  $ref: '#/components/schemas/turnstile_domains'
                ephemeral_id:
                  $ref: '#/components/schemas/turnstile_ephemeral_id'
                mode:
                  $ref: '#/components/schemas/turnstile_widget_mode'
                name:
                  $ref: '#/components/schemas/turnstile_name'
                offlabel:
                  $ref: '#/components/schemas/turnstile_offlabel'
                region:
                  $ref: '#/components/schemas/turnstile_region'
              required:
                - name
                - mode
                - domains
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/turnstile_api-response-common'
                  - properties:
                      result:
                        $ref: '#/components/schemas/turnstile_widget_detail'
                    type: object
                type: object
          description: Update Turnstile Widget Response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/turnstile_api-response-common-failure'
          description: Update Turnstile Widget Response Error
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Update a Turnstile Widget
      tags:
        - Turnstile
      x-api-token-group:
        - Turnstile Sites Write
        - Account Settings Write
    delete:
      description: Destroy a Turnstile Widget.
      operationId: accounts-turnstile-widget-delete
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/turnstile_api-response-common'
                  - properties:
                      result:
                        $ref: '#/components/schemas/turnstile_widget_detail'
                    type: object
                type: object
          description: Delete Turnstile Widget Response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/turnstile_api-response-common-failure'
          description: Delete Turnstile Widget Response Error
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Delete a Turnstile Widget
      tags:
        - Turnstile
      x-api-token-group:
        - Turnstile Sites Write
        - Account Settings Write
  /accounts/{account_id}/challenges/widgets/{sitekey}/rotate_secret:
    post:
      description: |
        Generate a new secret key for this widget. If `invalidate_immediately`
        is set to `false`, the previous secret remains valid for 2 hours.

        Note that secrets cannot be rotated again during the grace period.
      operationId: accounts-turnstile-widget-rotate-secret
      requestBody:
        content:
          application/json:
            schema:
              properties:
                invalidate_immediately:
                  $ref: '#/components/schemas/turnstile_invalidate_immediately'
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/turnstile_api-response-common'
                  - properties:
                      result:
                        $ref: '#/components/schemas/turnstile_widget_detail'
                    type: object
                type: object
          description: Rotate Secret Response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/turnstile_api-response-common-failure'
          description: Rotate Secret Response Error
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Rotate Secret for a Turnstile Widget
      tags:
        - Turnstile
      x-api-token-group:
        - Turnstile Sites Write
        - Account Settings Write
components:
  schemas:
    turnstile_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/turnstile_messages'
        messages:
          $ref: '#/components/schemas/turnstile_messages'
        success:
          description: Whether the API call was successful
          example: true
          type: boolean
      required:
        - success
        - errors
        - messages
      type: object
    turnstile_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/turnstile_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/turnstile_messages'
          example: []
        result:
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    turnstile_bot_fight_mode:
      description: |
        If bot_fight_mode is set to `true`, Cloudflare issues computationally
        expensive challenges in response to malicious bots (ENT only).
      example: false
      type: boolean
      x-auditable: true
    turnstile_clearance_level:
      description: >
        If Turnstile is embedded on a Cloudflare site and the widget should
        grant challenge clearance,

        this setting can determine the clearance level to be set
      enum:
        - no_clearance
        - jschallenge
        - managed
        - interactive
      example: interactive
      type: string
      x-auditable: true
    turnstile_domains:
      example:
        - 203.0.113.1
        - cloudflare.com
        - blog.example.com
      items:
        description: |
          Hosts as a hostname or IPv4/IPv6 address represented by strings. The
          widget will only work on these domains, and their subdomains.
        example: 203.0.113.1
        type: string
        x-auditable: true
      maxLength: 10
      type: array
    turnstile_ephemeral_id:
      description: |
        Return the Ephemeral ID in /siteverify (ENT only).
      example: false
      type: boolean
      x-auditable: true
    turnstile_invalidate_immediately:
      default: false
      description: |
        If `invalidate_immediately` is set to `false`, the previous secret will
        remain valid for two hours. Otherwise, the secret is immediately
        invalidated, and requests using it will be rejected.
      type: boolean
      x-auditable: true
    turnstile_name:
      description: |
        Human readable widget name. Not unique. Cloudflare suggests that you
        set this to a meaningful string to make it easier to identify your
        widget, and where it is used.
      example: blog.cloudflare.com login form
      maxLength: 254
      minLength: 1
      type: string
      x-auditable: true
    turnstile_offlabel:
      description: |
        Do not show any Cloudflare branding on the widget (ENT only).
      example: false
      type: boolean
      x-auditable: true
    turnstile_region:
      default: world
      description: >
        Region where this widget can be used. This cannot be changed after
        creation.
      enum:
        - world
        - china
      type: string
      x-auditable: true
    turnstile_result_info:
      properties:
        count:
          description: Total number of results for the requested service
          example: 1
          type: number
        page:
          description: Current page within paginated list of results
          example: 1
          type: number
        per_page:
          description: Number of results per page of results
          example: 20
          type: number
        total_count:
          description: Total results available without any search parameters
          example: 2000
          type: number
      required:
        - page
        - per_page
        - count
        - total_count
      type: object
    turnstile_widget_detail:
      description: A Turnstile widget's detailed configuration
      properties:
        bot_fight_mode:
          $ref: '#/components/schemas/turnstile_bot_fight_mode'
        clearance_level:
          $ref: '#/components/schemas/turnstile_clearance_level'
        created_on:
          $ref: '#/components/schemas/turnstile_created_on'
        domains:
          $ref: '#/components/schemas/turnstile_domains'
        ephemeral_id:
          $ref: '#/components/schemas/turnstile_ephemeral_id'
        mode:
          $ref: '#/components/schemas/turnstile_widget_mode'
        modified_on:
          $ref: '#/components/schemas/turnstile_modified_on'
        name:
          $ref: '#/components/schemas/turnstile_name'
        offlabel:
          $ref: '#/components/schemas/turnstile_offlabel'
        region:
          $ref: '#/components/schemas/turnstile_region'
        secret:
          $ref: '#/components/schemas/turnstile_secret'
        sitekey:
          $ref: '#/components/schemas/turnstile_sitekey'
      required:
        - sitekey
        - secret
        - created_on
        - modified_on
        - name
        - domains
        - mode
        - region
        - bot_fight_mode
        - offlabel
        - clearance_level
        - ephemeral_id
      type: object
    turnstile_widget_list:
      description: A Turnstile Widgets configuration as it appears in listings
      properties:
        bot_fight_mode:
          $ref: '#/components/schemas/turnstile_bot_fight_mode'
        clearance_level:
          $ref: '#/components/schemas/turnstile_clearance_level'
        created_on:
          $ref: '#/components/schemas/turnstile_created_on'
        domains:
          $ref: '#/components/schemas/turnstile_domains'
        ephemeral_id:
          $ref: '#/components/schemas/turnstile_ephemeral_id'
        mode:
          $ref: '#/components/schemas/turnstile_widget_mode'
        modified_on:
          $ref: '#/components/schemas/turnstile_modified_on'
        name:
          $ref: '#/components/schemas/turnstile_name'
        offlabel:
          $ref: '#/components/schemas/turnstile_offlabel'
        region:
          $ref: '#/components/schemas/turnstile_region'
        sitekey:
          $ref: '#/components/schemas/turnstile_sitekey'
      required:
        - sitekey
        - created_on
        - modified_on
        - name
        - domains
        - mode
        - region
        - bot_fight_mode
        - offlabel
        - clearance_level
        - ephemeral_id
      type: object
    turnstile_widget_mode:
      description: Widget Mode
      enum:
        - non-interactive
        - invisible
        - managed
      example: invisible
      type: string
      x-auditable: true
