openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /user/billing/profile:
    get:
      deprecated: true
      description: Accesses your billing profile object.
      operationId: user-billing-profile-(-deprecated)-billing-profile-details
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bill-subs-api_billing_response_single'
          description: Billing Profile Details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/bill-subs-api_billing_response_single'
                  - $ref: >-
                      #/components/schemas/bill-subs-api_api-response-common-failure
          description: Billing Profile Details response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Billing Profile Details
      tags:
        - User Billing Profile
      x-api-token-group:
        - Billing Write
        - Billing Read
      x-cfPermissionsRequired:
        enum:
          - '#billing:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    bill-subs-api_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/bill-subs-api_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/bill-subs-api_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    bill-subs-api_billing_response_single:
      allOf:
        - $ref: '#/components/schemas/bill-subs-api_api-response-single'
        - properties:
            result:
              properties:
                account_type:
                  example: type
                  type: string
                address:
                  example: 123 Main Street
                  type: string
                address2:
                  example: Apt 1
                  type: string
                balance:
                  example: 0
                  type: string
                card_expiry_month:
                  example: 12
                  type: integer
                card_expiry_year:
                  example: 2099
                  type: integer
                card_number:
                  example: 4242424242424242
                  type: string
                city:
                  example: Anytown
                  type: string
                company:
                  example: Company
                  type: string
                country:
                  example: Anycountry
                  type: string
                created_on:
                  example: '2014-03-01T12:21:59.3456Z'
                  format: date-time
                  type: string
                device_data:
                  example: sample_data
                  type: string
                edited_on:
                  example: '2014-03-01T12:21:59.3456Z'
                  format: date-time
                  type: string
                enterprise_billing_email:
                  example: johndoe@gmail.com
                  type: string
                enterprise_primary_email:
                  example: johndoe@gmail.com
                  type: string
                first_name:
                  example: John
                  type: string
                id:
                  $ref: >-
                    #/components/schemas/bill-subs-api_components-schemas-identifier
                is_partner:
                  example: false
                  type: boolean
                last_name:
                  example: Doe
                  type: string
                next_bill_date:
                  example: '2014-03-01T12:21:59.3456Z'
                  format: date-time
                  type: string
                payment_address:
                  example: 123 Main Street
                  type: string
                payment_address2:
                  example: Apt 1
                  type: string
                payment_city:
                  example: Anytown
                  type: string
                payment_country:
                  example: Anycountry
                  type: string
                payment_email:
                  example: johndoe@gmail.com
                  type: string
                payment_first_name:
                  example: John
                  type: string
                payment_gateway:
                  example: gateway
                  type: string
                payment_last_name:
                  example: Doe
                  type: string
                payment_nonce:
                  example: abc123
                  type: string
                payment_state:
                  example: state
                  type: string
                payment_zipcode:
                  example: 12345
                  type: string
                primary_email:
                  example: johndoe@gmail.com
                  type: string
                state:
                  example: AnyState
                  type: string
                tax_id_type:
                  example: type
                  type: string
                telephone:
                  example: 1234567899
                  type: string
                use_legacy:
                  example: false
                  type: boolean
                validation_code:
                  example: 1111
                  type: string
                vat:
                  example: GB123456789
                  type: string
                zipcode:
                  example: 12345
                  type: string
              type: object
          type: object
