openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /user/invites:
    get:
      description: Lists all invitations associated with my user.
      operationId: user'-s-invites-list-invitations
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_schemas-collection_invite_response'
          description: List Invitations response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: List Invitations response failure
      security:
        - api_email: []
          api_key: []
      summary: List Invitations
      tags:
        - User's Invites
      x-api-token-group:
        - Memberships Write
        - Memberships Read
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /user/invites/{invite_id}:
    get:
      description: Gets the details of an invitation.
      operationId: user'-s-invites-invitation-details
      parameters:
        - in: path
          name: invite_id
          required: true
          schema:
            $ref: '#/components/schemas/iam_invite_components-schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_single_invite_response'
          description: Invitation Details response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: Invitation Details response failure
      security:
        - api_email: []
          api_key: []
      summary: Invitation Details
      tags:
        - User's Invites
      x-api-token-group:
        - Memberships Write
        - Memberships Read
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    patch:
      description: Responds to an invitation.
      operationId: user'-s-invites-respond-to-invitation
      parameters:
        - in: path
          name: invite_id
          required: true
          schema:
            $ref: '#/components/schemas/iam_invite_components-schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                status:
                  description: >-
                    Status of your response to the invitation (rejected or
                    accepted).
                  enum:
                    - accepted
                    - rejected
                  example: accepted
              required:
                - status
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_single_invite_response'
          description: Respond to Invitation response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: Respond to Invitation response failure
      security:
        - api_email: []
          api_key: []
      summary: Respond to Invitation
      tags:
        - User's Invites
      x-api-token-group:
        - Memberships Write
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    iam_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/iam_schemas-messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/iam_schemas-messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    iam_invite_components-schemas-identifier:
      description: Invite identifier tag.
      example: 4f5f0c14a2a41d5063dd301b2f829f04
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
    iam_schemas-collection_invite_response:
      allOf:
        - $ref: '#/components/schemas/iam_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/iam_user_invite'
              type: array
          type: object
    iam_single_invite_response:
      allOf:
        - $ref: '#/components/schemas/iam_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/iam_user_invite'
          type: object
