openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /user/billing/history:
    get:
      deprecated: true
      description: Accesses your billing history object.
      operationId: user-billing-history-(-deprecated)-billing-history-details
      parameters:
        - in: query
          name: page
          schema:
            default: 1
            description: Page number of paginated results.
            minimum: 1
            type: number
        - in: query
          name: per_page
          schema:
            default: 20
            description: Number of items per page.
            maximum: 50
            minimum: 5
            type: number
        - in: query
          name: order
          schema:
            description: Field to order billing history by.
            enum:
              - type
              - occurred_at
              - action
            example: occurred_at
            type: string
        - in: query
          name: occurred_at
          schema:
            $ref: '#/components/schemas/bill-subs-api_occurred_at'
        - in: query
          name: type
          schema:
            description: The billing item type.
            example: charge
            maxLength: 30
            readOnly: true
            type: string
        - in: query
          name: action
          schema:
            description: The billing item action.
            example: subscription
            maxLength: 30
            readOnly: true
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bill-subs-api_billing_history_collection'
          description: Billing History Details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/bill-subs-api_billing_history_collection
                  - $ref: >-
                      #/components/schemas/bill-subs-api_api-response-common-failure
          description: Billing History Details response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Billing History Details
      tags:
        - User Billing History
      x-api-token-group:
        - Billing Write
        - Billing Read
      x-cfPermissionsRequired:
        enum:
          - '#billing:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    bill-subs-api_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/bill-subs-api_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/bill-subs-api_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    bill-subs-api_billing_history_collection:
      allOf:
        - $ref: '#/components/schemas/bill-subs-api_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/bill-subs-api_billing-history'
              type: array
    bill-subs-api_occurred_at:
      description: When the billing item was created.
      example: '2014-03-01T12:21:59.3456Z'
      format: date-time
      readOnly: true
      type: string
