openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/firewall/waf/packages:
    get:
      deprecated: true
      description: >-
        Fetches WAF packages for a zone.


        **Note:** Applies only to the [previous version of WAF managed
        rules](https://developers.cloudflare.com/support/firewall/managed-rules-web-application-firewall-waf/understanding-waf-managed-rules-web-application-firewall/).
      operationId: waf-packages-list-waf-packages
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/firewall_identifier'
        - in: query
          name: page
          schema:
            default: 1
            description: The page number of paginated results.
            minimum: 1
            type: number
        - in: query
          name: per_page
          schema:
            default: 50
            description: The number of packages per page.
            maximum: 100
            minimum: 5
            type: number
        - in: query
          name: order
          schema:
            description: The field used to sort returned packages.
            enum:
              - name
            example: name
            type: string
        - in: query
          name: direction
          schema:
            description: The direction used to sort returned packages.
            enum:
              - asc
              - desc
            example: desc
            type: string
        - in: query
          name: match
          schema:
            default: all
            description: >-
              When set to `all`, all the search requirements must match. When
              set to `any`, only one of the search requirements has to match.
            enum:
              - any
              - all
            type: string
        - in: query
          name: name
          schema:
            description: The name of the WAF package.
            example: USER
            readOnly: true
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/firewall_package_response_collection'
          description: List WAF packages response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/firewall_package_response_collection'
                  - $ref: '#/components/schemas/firewall_api-response-common-failure'
          description: List WAF packages response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List WAF packages
      tags:
        - WAF packages
      x-api-token-group:
        - Firewall Services Write
        - Firewall Services Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: true
  /zones/{zone_id}/firewall/waf/packages/{package_id}:
    get:
      deprecated: true
      description: >-
        Fetches the details of a WAF package.


        **Note:** Applies only to the [previous version of WAF managed
        rules](https://developers.cloudflare.com/support/firewall/managed-rules-web-application-firewall-waf/understanding-waf-managed-rules-web-application-firewall/).
      operationId: waf-packages-get-a-waf-package
      parameters:
        - in: path
          name: package_id
          required: true
          schema:
            $ref: '#/components/schemas/firewall_package_id'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/firewall_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/firewall_package_response_single'
          description: Get a WAF package response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/firewall_package_response_single'
                  - $ref: '#/components/schemas/firewall_api-response-common-failure'
          description: Get a WAF package response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get a WAF package
      tags:
        - WAF packages
      x-api-token-group:
        - Firewall Services Write
        - Firewall Services Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: true
    patch:
      deprecated: true
      description: >-
        Updates a WAF package. You can update the sensitivity and the action of
        an anomaly detection WAF package.


        **Note:** Applies only to the [previous version of WAF managed
        rules](https://developers.cloudflare.com/support/firewall/managed-rules-web-application-firewall-waf/understanding-waf-managed-rules-web-application-firewall/).
      operationId: waf-packages-update-a-waf-package
      parameters:
        - in: path
          name: package_id
          required: true
          schema:
            $ref: '#/components/schemas/firewall_package_id'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/firewall_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                action_mode:
                  $ref: '#/components/schemas/firewall_action_mode'
                sensitivity:
                  $ref: '#/components/schemas/firewall_sensitivity'
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/firewall_package_response_single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/firewall_anomaly_package'
                    type: object
          description: Update a WAF package response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: '#/components/schemas/firewall_package_response_single'
                      - properties:
                          result:
                            $ref: '#/components/schemas/firewall_anomaly_package'
                        type: object
                  - $ref: '#/components/schemas/firewall_api-response-common-failure'
          description: Update a WAF package response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update a WAF package
      tags:
        - WAF packages
      x-api-token-group:
        - Firewall Services Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: true
components:
  schemas:
    firewall_action_mode:
      default: challenge
      description: The default action performed by the rules in the WAF package.
      enum:
        - simulate
        - block
        - challenge
      type: string
    firewall_anomaly_package:
      allOf:
        - $ref: '#/components/schemas/firewall_package_definition'
        - properties:
            action_mode:
              $ref: '#/components/schemas/firewall_action_mode'
            description:
              $ref: '#/components/schemas/firewall_anomaly_description'
            detection_mode:
              $ref: '#/components/schemas/firewall_anomaly_detection_mode'
            name:
              $ref: '#/components/schemas/firewall_anomaly_name'
            sensitivity:
              $ref: '#/components/schemas/firewall_sensitivity'
          type: object
      required:
        - id
        - name
        - description
        - zone_id
        - detection_mode
        - sensitivity
        - action_mode
      title: Anomaly detection WAF package (OWASP)
    firewall_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/firewall_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/firewall_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Defines whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    firewall_identifier:
      description: Defines an identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    firewall_package_id:
      description: Defines a package identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    firewall_package_response_collection:
      anyOf:
        - $ref: '#/components/schemas/firewall_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/firewall_package'
              type: array
          type: object
    firewall_package_response_single:
      oneOf:
        - $ref: '#/components/schemas/firewall_api-response-single'
        - properties:
            result:
              type: object
          type: object
    firewall_sensitivity:
      default: high
      description: The sensitivity of the WAF package.
      enum:
        - high
        - medium
        - low
        - 'off'
      type: string
