openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/firewall/waf/packages/{package_id}/groups:
    get:
      deprecated: true
      description: >-
        Fetches the WAF rule groups in a WAF package.


        **Note:** Applies only to the [previous version of WAF managed
        rules](https://developers.cloudflare.com/support/firewall/managed-rules-web-application-firewall-waf/understanding-waf-managed-rules-web-application-firewall/).
      operationId: waf-rule-groups-list-waf-rule-groups
      parameters:
        - in: path
          name: package_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-managed-rules_identifier'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-managed-rules_schemas-identifier'
        - in: query
          name: mode
          schema:
            allOf:
              - $ref: '#/components/schemas/waf-managed-rules_mode'
        - in: query
          name: page
          schema:
            default: 1
            description: Defines the page number of paginated results.
            minimum: 1
            type: number
        - in: query
          name: per_page
          schema:
            default: 50
            description: Defines the number of rule groups per page.
            maximum: 100
            minimum: 5
            type: number
        - in: query
          name: order
          schema:
            description: Defines the field used to sort returned rule groups.
            enum:
              - mode
              - rules_count
            example: mode
            type: string
        - in: query
          name: direction
          schema:
            description: Defines the direction used to sort returned rule groups.
            enum:
              - asc
              - desc
            example: desc
            type: string
        - in: query
          name: match
          schema:
            default: all
            description: >-
              Defines the condition for search requirements. When set to `all`,
              all the search requirements must match. When set to `any`, only
              one of the search requirements has to match.
            enum:
              - any
              - all
            type: string
        - in: query
          name: name
          schema:
            description: Defines the name of the rule group.
            example: Project Honey Pot
            readOnly: true
            type: string
        - in: query
          name: rules_count
          schema:
            default: 0
            description: Defines the number of rules in the current rule group.
            example: 10
            readOnly: true
            type: number
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/waf-managed-rules_rule_group_response_collection
          description: Defines the list WAF rule groups response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/waf-managed-rules_rule_group_response_collection
                  - $ref: >-
                      #/components/schemas/waf-managed-rules_api-response-common-failure
          description: Defines the list WAF rule groups response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List WAF rule groups
      tags:
        - WAF rule groups
      x-api-token-group:
        - Firewall Services Write
        - Firewall Services Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: true
  /zones/{zone_id}/firewall/waf/packages/{package_id}/groups/{group_id}:
    get:
      deprecated: true
      description: >-
        Fetches the details of a WAF rule group.


        **Note:** Applies only to the [previous version of WAF managed
        rules](https://developers.cloudflare.com/support/firewall/managed-rules-web-application-firewall-waf/understanding-waf-managed-rules-web-application-firewall/).
      operationId: waf-rule-groups-get-a-waf-rule-group
      parameters:
        - in: path
          name: group_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-managed-rules_identifier'
        - in: path
          name: package_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-managed-rules_identifier'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-managed-rules_schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/waf-managed-rules_rule_group_response_single
          description: Get a WAF rule group response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/waf-managed-rules_rule_group_response_single
                  - $ref: >-
                      #/components/schemas/waf-managed-rules_api-response-common-failure
          description: Get a WAF rule group response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get a WAF rule group
      tags:
        - WAF rule groups
      x-api-token-group:
        - Firewall Services Write
        - Firewall Services Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: true
    patch:
      deprecated: true
      description: >-
        Updates a WAF rule group. You can update the state (`mode` parameter) of
        a rule group.


        **Note:** Applies only to the [previous version of WAF managed
        rules](https://developers.cloudflare.com/support/firewall/managed-rules-web-application-firewall-waf/understanding-waf-managed-rules-web-application-firewall/).
      operationId: waf-rule-groups-update-a-waf-rule-group
      parameters:
        - in: path
          name: group_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-managed-rules_identifier'
        - in: path
          name: package_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-managed-rules_identifier'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/waf-managed-rules_schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                mode:
                  $ref: '#/components/schemas/waf-managed-rules_mode'
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/waf-managed-rules_rule_group_response_single
          description: Update a WAF rule group response.
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/waf-managed-rules_rule_group_response_single
                  - $ref: >-
                      #/components/schemas/waf-managed-rules_api-response-common-failure
          description: Update a WAF rule group response failure.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update a WAF rule group
      tags:
        - WAF rule groups
      x-api-token-group:
        - Firewall Services Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: true
components:
  schemas:
    waf-managed-rules_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/waf-managed-rules_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/waf-managed-rules_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Defines whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    waf-managed-rules_identifier:
      description: Defines the unique identifier of a WAF package.
      example: a25a9a7e9c00afc1fb2e0245519d725b
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
    waf-managed-rules_mode:
      default: 'on'
      description: >-
        Defines the state of the rules contained in the rule group. When `on`,
        the rules in the group are configurable/usable.
      enum:
        - 'on'
        - 'off'
      type: string
      x-auditable: true
    waf-managed-rules_rule_group_response_collection:
      allOf:
        - $ref: '#/components/schemas/waf-managed-rules_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/waf-managed-rules_schemas-group'
              type: array
          type: object
    waf-managed-rules_rule_group_response_single:
      allOf:
        - $ref: '#/components/schemas/waf-managed-rules_api-response-single'
        - properties:
            result:
              type: object
          type: object
    waf-managed-rules_schemas-identifier:
      description: Defines an identifier of a schema.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
