openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/gateway/categories:
    get:
      description: Fetches a list of all categories.
      operationId: zero-trust-gateway-categories-list-categories
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: >-
              #/components/schemas/zero-trust-gateway_components-schemas-identifier
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/zero-trust-gateway_categories_components-schemas-response_collection
          description: List categories response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_categories_components-schemas-response_collection
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_api-response-common-failure
                type: object
          description: List categories response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List categories
      tags:
        - Zero Trust Gateway categories
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
components:
  schemas:
    zero-trust-gateway_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/zero-trust-gateway_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
          type: object
        messages:
          allOf:
            - $ref: '#/components/schemas/zero-trust-gateway_messages'
          example: []
          type: object
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    zero-trust-gateway_categories_components-schemas-response_collection:
      allOf:
        - $ref: '#/components/schemas/zero-trust-gateway_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/zero-trust-gateway_categories'
              type: array
      type: object
    zero-trust-gateway_components-schemas-identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
