openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/gateway/lists:
    get:
      description: Fetches all Zero Trust lists for an account.
      operationId: zero-trust-lists-list-zero-trust-lists
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-identifier'
        - in: query
          name: type
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-type'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/zero-trust-gateway_schemas-response_collection
          description: List Zero Trust lists response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_schemas-response_collection
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_api-response-common-failure
                type: object
          description: List Zero Trust lists response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List Zero Trust lists
      tags:
        - Zero Trust lists
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
    post:
      description: Creates a new Zero Trust list.
      operationId: zero-trust-lists-create-zero-trust-list
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                description:
                  $ref: '#/components/schemas/zero-trust-gateway_description'
                items:
                  $ref: '#/components/schemas/zero-trust-gateway_items-input'
                name:
                  $ref: '#/components/schemas/zero-trust-gateway_name'
                type:
                  $ref: '#/components/schemas/zero-trust-gateway_schemas-type'
              required:
                - name
                - type
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/zero-trust-gateway_single_response_with_list_items
          description: Create Zero Trust list response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_single_response_with_list_items
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_api-response-common-failure
                type: object
          description: Create Zero Trust list response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create Zero Trust list
      tags:
        - Zero Trust lists
      x-api-token-group:
        - Zero Trust Write
  /accounts/{account_id}/gateway/lists/{list_id}:
    get:
      description: Fetches a single Zero Trust list.
      operationId: zero-trust-lists-zero-trust-list-details
      parameters:
        - in: path
          name: list_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_list_single_response'
          description: Get Zero Trust list details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_list_single_response
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_api-response-common-failure
                type: object
          description: Get Zero Trust list details response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get Zero Trust list details
      tags:
        - Zero Trust lists
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
    put:
      description: >-
        Updates a configured Zero Trust list. Skips updating list items if not
        included in the payload.
      operationId: zero-trust-lists-update-zero-trust-list
      parameters:
        - in: path
          name: list_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                description:
                  $ref: '#/components/schemas/zero-trust-gateway_description'
                items:
                  $ref: '#/components/schemas/zero-trust-gateway_items-input'
                name:
                  $ref: '#/components/schemas/zero-trust-gateway_name'
              required:
                - name
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_list_single_response'
          description: Update Zero Trust list response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_list_single_response
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_api-response-common-failure
                type: object
          description: Update Zero Trust list response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update Zero Trust list
      tags:
        - Zero Trust lists
      x-api-token-group:
        - Zero Trust Write
    patch:
      description: Appends or removes an item from a configured Zero Trust list.
      operationId: zero-trust-lists-patch-zero-trust-list
      parameters:
        - in: path
          name: list_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                append:
                  $ref: '#/components/schemas/zero-trust-gateway_items-input'
                remove:
                  description: A list of the item values you want to remove.
                  items:
                    $ref: '#/components/schemas/zero-trust-gateway_value'
                  type: array
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_list_single_response'
          description: Patch Zero Trust list response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_list_single_response
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_api-response-common-failure
                type: object
          description: Patch Zero Trust list response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Patch Zero Trust list
      tags:
        - Zero Trust lists
      x-api-token-group:
        - Zero Trust Write
    delete:
      description: Deletes a Zero Trust list.
      operationId: zero-trust-lists-delete-zero-trust-list
      parameters:
        - in: path
          name: list_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_empty_response'
          description: Delete Zero Trust list response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/zero-trust-gateway_empty_response'
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_api-response-common-failure
                type: object
          description: Delete Zero Trust list response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete Zero Trust list
      tags:
        - Zero Trust lists
      x-api-token-group:
        - Zero Trust Write
  /accounts/{account_id}/gateway/lists/{list_id}/items:
    get:
      description: Fetches all items in a single Zero Trust list.
      operationId: zero-trust-lists-zero-trust-list-items
      parameters:
        - in: path
          name: list_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/zero-trust-gateway_list_item_response_collection
          description: Get Zero Trust list items response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_list_item_response_collection
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_api-response-common-failure
                type: object
          description: Get Zero Trust list items response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get Zero Trust list items
      tags:
        - Zero Trust lists
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
components:
  schemas:
    zero-trust-gateway_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/zero-trust-gateway_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
          type: object
        messages:
          allOf:
            - $ref: '#/components/schemas/zero-trust-gateway_messages'
          example: []
          type: object
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    zero-trust-gateway_description:
      description: The description of the list.
      example: The serial numbers for administrators
      type: string
      x-auditable: true
    zero-trust-gateway_empty_response:
      allOf:
        - $ref: '#/components/schemas/zero-trust-gateway_api-response-single'
        - properties:
            result:
              type: object
      type: object
    zero-trust-gateway_items-input:
      description: items to add to the list.
      items:
        properties:
          description:
            $ref: '#/components/schemas/zero-trust-gateway_description_item'
          value:
            $ref: '#/components/schemas/zero-trust-gateway_value'
        type: object
      type: array
      x-stainless-collection-type: set
    zero-trust-gateway_list_item_response_collection:
      allOf:
        - $ref: '#/components/schemas/zero-trust-gateway_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/zero-trust-gateway_items'
              type: array
        - properties:
            result_info:
              properties:
                count:
                  description: Total results returned based on your search parameters.
                  example: 1
                  type: number
                page:
                  description: Current page within paginated list of results.
                  example: 1
                  type: number
                per_page:
                  description: Number of results per page of results.
                  example: 20
                  type: number
                total_count:
                  description: Total results available without any search parameters.
                  example: 2000
                  type: number
              type: object
      type: object
    zero-trust-gateway_list_single_response:
      allOf:
        - $ref: '#/components/schemas/zero-trust-gateway_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/zero-trust-gateway_lists'
      type: object
      x-auditable: true
    zero-trust-gateway_name:
      description: The name of the list.
      example: Admin Serial Numbers
      type: string
      x-auditable: true
    zero-trust-gateway_schemas-identifier:
      example: 699d98642c564d2e855e9661899b7252
      type: string
      x-auditable: true
    zero-trust-gateway_schemas-response_collection:
      allOf:
        - $ref: '#/components/schemas/zero-trust-gateway_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/zero-trust-gateway_lists'
              type: array
      type: object
    zero-trust-gateway_schemas-type:
      description: The type of list.
      enum:
        - SERIAL
        - URL
        - DOMAIN
        - EMAIL
        - IP
      example: SERIAL
      type: string
      x-auditable: true
    zero-trust-gateway_schemas-uuid:
      description: API Resource UUID tag.
      example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      maxLength: 36
      type: string
      x-auditable: true
    zero-trust-gateway_single_response_with_list_items:
      allOf:
        - $ref: '#/components/schemas/zero-trust-gateway_api-response-single'
        - properties:
            result:
              properties:
                created_at:
                  $ref: '#/components/schemas/zero-trust-gateway_read_only_timestamp'
                description:
                  $ref: '#/components/schemas/zero-trust-gateway_description'
                id:
                  $ref: '#/components/schemas/zero-trust-gateway_schemas-uuid'
                items:
                  $ref: '#/components/schemas/zero-trust-gateway_items'
                name:
                  $ref: '#/components/schemas/zero-trust-gateway_name'
                type:
                  $ref: '#/components/schemas/zero-trust-gateway_schemas-type'
                updated_at:
                  $ref: '#/components/schemas/zero-trust-gateway_read_only_timestamp'
      type: object
    zero-trust-gateway_value:
      description: The value of the item in a list.
      example: 8GE8721REF
      type: string
      x-auditable: true
