openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/zerotrust/connectivity_settings:
    get:
      description: Gets the Zero Trust Connectivity Settings for the given account.
      operationId: zero-trust-accounts-get-connectivity-settings
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/tunnel_account_id'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tunnel_zero_trust_connectivity_settings_response
          description: Get Zero Trust Connectivity Settings response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tunnel_api-response-common-failure'
          description: Get Zero Trust Connectivity Settings response failure
      security:
        - api_email: []
          api_key: []
        - api_token: []
        - user_service_key: []
      summary: Get Zero Trust Connectivity Settings
      tags:
        - Zero Trust Connectivity Settings
      x-api-token-group:
        - Zero Trust Report
        - Zero Trust Read
        - Zero Trust Write
    patch:
      description: Updates the Zero Trust Connectivity Settings for the given account.
      operationId: zero-trust-accounts-patch-connectivity-settings
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/tunnel_account_id'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                icmp_proxy_enabled:
                  $ref: '#/components/schemas/tunnel_icmp_proxy_enabled'
                offramp_warp_enabled:
                  $ref: '#/components/schemas/tunnel_offramp_warp_enabled'
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tunnel_zero_trust_connectivity_settings_response
          description: Update Zero Trust Connectivity Settings response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tunnel_api-response-common-failure'
          description: Update Zero Trust Connectivity Settings response failure
      security:
        - api_email: []
          api_key: []
        - api_token: []
        - user_service_key: []
      summary: Updates the Zero Trust Connectivity Settings
      tags:
        - Zero Trust Connectivity Settings
      x-api-token-group:
        - Zero Trust Write
components:
  schemas:
    tunnel_account_id:
      description: Cloudflare account ID
      example: 699d98642c564d2e855e9661899b7252
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
    tunnel_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/tunnel_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/tunnel_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    tunnel_icmp_proxy_enabled:
      description: A flag to enable the ICMP proxy for the account network.
      example: true
      type: boolean
      x-auditable: true
    tunnel_offramp_warp_enabled:
      description: A flag to enable WARP to WARP traffic.
      example: true
      type: boolean
      x-auditable: true
    tunnel_zero_trust_connectivity_settings_response:
      allOf:
        - $ref: '#/components/schemas/tunnel_api-response-common'
        - properties:
            result:
              properties:
                icmp_proxy_enabled:
                  $ref: '#/components/schemas/tunnel_icmp_proxy_enabled'
                offramp_warp_enabled:
                  $ref: '#/components/schemas/tunnel_offramp_warp_enabled'
              type: object
          type: object
