openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/access/users:
    get:
      description: Gets a list of users for an account.
      operationId: zero-trust-users-get-users
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
        - in: query
          name: name
          schema:
            description: The name of the user.
            type: string
        - in: query
          name: email
          schema:
            description: The email of the user.
            type: string
        - in: query
          name: search
          schema:
            description: Search for users by other listed query parameters.
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/access_users_components-schemas-response_collection
          description: Get users response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Get users response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get users
      tags:
        - Zero Trust users
      x-api-token-group:
        - 'Access: Audit Logs Read'
  /accounts/{account_id}/access/users/{user_id}/active_sessions:
    get:
      description: Get active sessions for a single user.
      operationId: zero-trust-users-get-active-sessions
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_active_sessions_response'
          description: Get active sessions response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Get active sessions response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get active sessions
      tags:
        - Zero Trust users
      x-api-token-group:
        - 'Access: Audit Logs Read'
  /accounts/{account_id}/access/users/{user_id}/active_sessions/{nonce}:
    get:
      description: Get an active session for a single user.
      operationId: zero-trust-users-get-active-session
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
        - in: path
          name: nonce
          required: true
          schema:
            $ref: '#/components/schemas/access_nonce'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_active_session_response'
          description: Get active session response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Get active session response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get single active session
      tags:
        - Zero Trust users
      x-api-token-group:
        - 'Access: Audit Logs Read'
  /accounts/{account_id}/access/users/{user_id}/failed_logins:
    get:
      description: Get all failed login attempts for a single user.
      operationId: zero-trust-users-get-failed-logins
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_failed_login_response'
          description: Get failed logins response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Get failed logins response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get failed logins
      tags:
        - Zero Trust users
      x-api-token-group:
        - 'Access: Audit Logs Read'
  /accounts/{account_id}/access/users/{user_id}/last_seen_identity:
    get:
      description: Get last seen identity for a single user.
      operationId: zero-trust-users-get-last-seen-identity
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_last_seen_identity_response'
          description: Get active session response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Get active session response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get last seen identity
      tags:
        - Zero Trust users
      x-api-token-group:
        - 'Access: Audit Logs Read'
components:
  schemas:
    access_active_session_response:
      allOf:
        - $ref: '#/components/schemas/access_api-response-single'
        - properties:
            result:
              allOf:
                - $ref: '#/components/schemas/access_identity'
                - properties:
                    isActive:
                      example: true
                      type: boolean
                  type: object
              type: object
      type: object
    access_active_sessions_response:
      allOf:
        - $ref: '#/components/schemas/access_api-response-collection'
        - properties:
            result:
              items:
                properties:
                  expiration:
                    example: 1694813506
                    type: integer
                  metadata:
                    properties:
                      apps:
                        additionalProperties:
                          properties:
                            hostname:
                              example: test.example.com
                              type: string
                            name:
                              example: app name
                              type: string
                            type:
                              example: self_hosted
                              type: string
                            uid:
                              example: cc2a8145-0128-4429-87f3-872c4d380c4e
                              type: string
                          type: object
                        type: object
                      expires:
                        example: 1694813506
                        type: integer
                      iat:
                        example: 1694791905
                        type: integer
                      nonce:
                        example: X1aXj1lFVcqqyoXF
                        type: string
                      ttl:
                        example: 21600
                        type: integer
                    type: object
                  name:
                    type: string
                type: object
              type: array
      type: object
    access_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/access_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/access_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    access_failed_login_response:
      allOf:
        - $ref: '#/components/schemas/access_api-response-collection'
        - properties:
            result:
              items:
                properties:
                  expiration:
                    type: integer
                  metadata:
                    example:
                      app_name: Test App
                      aud: >-
                        39691c1480a2352a18ece567debc2b32552686cbd38eec0887aa18d5d3f00c04
                      datetime: '2022-02-02T21:54:34.914Z'
                      ray_id: 6d76a8a42ead4133
                      user_email: test@cloudflare.com
                      user_uuid: 57171132-e453-4ee8-b2a5-8cbaad333207
                    type: object
                type: object
              type: array
      type: object
    access_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
    access_last_seen_identity_response:
      allOf:
        - $ref: '#/components/schemas/access_api-response-single'
        - properties:
            result:
              allOf:
                - $ref: '#/components/schemas/access_identity'
              type: object
      type: object
    access_nonce:
      example: X1aXj1lFVcqqyoXF
      type: string
    access_users_components-schemas-response_collection:
      allOf:
        - $ref: '#/components/schemas/access_api-response-collection'
        - properties:
            result_info:
              properties:
                count:
                  example: 1
                page:
                  example: 1
                per_page:
                  example: 100
                total_count:
                  example: 1
              type: object
        - properties:
            result:
              items:
                $ref: '#/components/schemas/access_schemas-users'
              type: array
      type: object
    access_uuid:
      description: UUID.
      example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      maxLength: 36
      type: string
      x-auditable: true
