openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/zt_risk_scoring/behaviors:
    get:
      operationId: dlp-risk-score-behaviors-get
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_Behaviors'
                    type: object
          description: Risk scoring behaviors.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Failed to get risk scoring behaviors.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get all behaviors and associated configuration
      tags:
        - Zero Trust Risk Scoring
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
    put:
      operationId: dlp-risk-score-behaviors-put
      parameters:
        - description: Account ID.
          in: path
          name: account_id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dlp_UpdateBehaviors'
        description: Behaviors.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_UpdateBehaviors'
                    type: object
          description: Dataset created successfully.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Dataset creation failed.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update configuration for risk behaviors
      tags:
        - Zero Trust Risk Scoring
      x-api-token-group:
        - Zero Trust Write
  /accounts/{account_id}/zt_risk_scoring/summary:
    get:
      operationId: dlp-risk-score-summary-get
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-collection'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_RiskSummary'
                    type: object
          description: Risk score for all users in the account.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Failed to get risk scores.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get risk score info for all users in the account
      tags:
        - Zero Trust Risk Scoring
      x-api-token-group:
        - 'Zero Trust: PII Read'
  /accounts/{account_id}/zt_risk_scoring/{user_id}:
    get:
      operationId: dlp-risk-score-summary-get-for-user
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
        - in: path
          name: user_id
          required: true
          schema:
            format: uuid
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-collection'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_RiskEvents'
                    type: object
          description: Risk events.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Failed to get risk events.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get risk event/score information for a specific user
      tags:
        - Zero Trust Risk Scoring
      x-api-token-group:
        - 'Zero Trust: PII Read'
  /accounts/{account_id}/zt_risk_scoring/{user_id}/reset:
    post:
      operationId: dlp-risk-score-reset-post
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
        - in: path
          name: user_id
          required: true
          schema:
            format: uuid
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_Empty'
                    type: object
          description: Dataset created successfully.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Dataset creation failed.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Clear the risk score for a particular user
      tags:
        - Zero Trust Risk Scoring
      x-api-token-group:
        - Zero Trust Write
components:
  schemas:
    dlp_Behaviors:
      properties:
        behaviors:
          additionalProperties:
            $ref: '#/components/schemas/dlp_Behavior'
          type: object
      required:
        - behaviors
      type: object
    dlp_Empty:
      nullable: true
      type: object
    dlp_RiskEvents:
      properties:
        email:
          type: string
        events:
          items:
            $ref: '#/components/schemas/dlp_RiskEvent'
          type: array
        last_reset_time:
          format: date-time
          nullable: true
          type: string
        name:
          type: string
        risk_level:
          allOf:
            - $ref: '#/components/schemas/dlp_RiskLevel'
      required:
        - name
        - email
        - events
      type: object
    dlp_RiskSummary:
      properties:
        users:
          items:
            $ref: '#/components/schemas/dlp_UserRiskInfo'
          type: array
      required:
        - users
      type: object
    dlp_UpdateBehaviors:
      properties:
        behaviors:
          additionalProperties:
            $ref: '#/components/schemas/dlp_UpdateBehavior'
          type: object
      required:
        - behaviors
      type: object
    dlp_api-response-collection:
      allOf:
        - $ref: '#/components/schemas/dlp_api-response-common'
        - properties:
            result_info:
              properties:
                count:
                  description: Total number of results for the requested service.
                  example: 1
                  type: number
                page:
                  description: Current page within paginated list of results.
                  example: 1
                  type: number
                per_page:
                  description: Number of results per page of results.
                  example: 20
                  type: number
                total_count:
                  description: Total results available without any search parameters.
                  example: 2000
                  type: number
              type: object
          type: object
      type: object
    dlp_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/dlp_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/dlp_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    dlp_api-response-single:
      allOf:
        - $ref: '#/components/schemas/dlp_api-response-common'
      type: object
