openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/gateway/locations:
    get:
      description: Fetches Zero Trust Gateway locations for an account.
      operationId: zero-trust-gateway-locations-list-zero-trust-gateway-locations
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/zero-trust-gateway_components-schemas-response_collection
          description: List Zero Trust Gateway locations response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_components-schemas-response_collection
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_api-response-common-failure
                type: object
          description: List Zero Trust Gateway locations response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List Zero Trust Gateway locations
      tags:
        - Zero Trust Gateway locations
      x-api-token-group:
        - Cloudflare Zero Trust Secure DNS Locations Write
        - Zero Trust Read
        - Zero Trust Write
    post:
      description: Creates a new Zero Trust Gateway location.
      operationId: zero-trust-gateway-locations-create-zero-trust-gateway-location
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                client_default:
                  $ref: '#/components/schemas/zero-trust-gateway_client-default'
                dns_destination_ips_id:
                  $ref: >-
                    #/components/schemas/zero-trust-gateway_dns-destination-ips-id-write
                ecs_support:
                  $ref: '#/components/schemas/zero-trust-gateway_ecs-support'
                endpoints:
                  $ref: '#/components/schemas/zero-trust-gateway_endpoints'
                name:
                  $ref: '#/components/schemas/zero-trust-gateway_schemas-name'
                networks:
                  $ref: '#/components/schemas/zero-trust-gateway_ipv4_networks'
              required:
                - name
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/zero-trust-gateway_schemas-single_response
          description: Create a Zero Trust Gateway location response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_schemas-single_response
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_api-response-common-failure
                type: object
          description: Create a Zero Trust Gateway location response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create a Zero Trust Gateway location
      tags:
        - Zero Trust Gateway locations
      x-api-token-group:
        - Cloudflare Zero Trust Secure DNS Locations Write
        - Zero Trust Write
  /accounts/{account_id}/gateway/locations/{location_id}:
    get:
      description: Fetches a single Zero Trust Gateway location.
      operationId: zero-trust-gateway-locations-zero-trust-gateway-location-details
      parameters:
        - in: path
          name: location_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_components-schemas-uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/zero-trust-gateway_schemas-single_response
          description: Get Zero Trust Gateway location details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_schemas-single_response
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_api-response-common-failure
                type: object
          description: Get Zero Trust Gateway location details response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get Zero Trust Gateway location details
      tags:
        - Zero Trust Gateway locations
      x-api-token-group:
        - Cloudflare Zero Trust Secure DNS Locations Write
        - Zero Trust Read
        - Zero Trust Write
    put:
      description: Updates a configured Zero Trust Gateway location.
      operationId: zero-trust-gateway-locations-update-zero-trust-gateway-location
      parameters:
        - in: path
          name: location_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_components-schemas-uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                client_default:
                  $ref: '#/components/schemas/zero-trust-gateway_client-default'
                dns_destination_ips_id:
                  $ref: >-
                    #/components/schemas/zero-trust-gateway_dns-destination-ips-id-write
                ecs_support:
                  $ref: '#/components/schemas/zero-trust-gateway_ecs-support'
                endpoints:
                  $ref: '#/components/schemas/zero-trust-gateway_endpoints'
                name:
                  $ref: '#/components/schemas/zero-trust-gateway_schemas-name'
                networks:
                  $ref: '#/components/schemas/zero-trust-gateway_ipv4_networks'
              required:
                - name
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/zero-trust-gateway_schemas-single_response
          description: Update a Zero Trust Gateway location response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_schemas-single_response
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_api-response-common-failure
                type: object
          description: Update a Zero Trust Gateway location response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update a Zero Trust Gateway location
      tags:
        - Zero Trust Gateway locations
      x-api-token-group:
        - Cloudflare Zero Trust Secure DNS Locations Write
        - Zero Trust Write
    delete:
      description: Deletes a configured Zero Trust Gateway location.
      operationId: zero-trust-gateway-locations-delete-zero-trust-gateway-location
      parameters:
        - in: path
          name: location_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_components-schemas-uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_empty_response'
          description: Delete a Zero Trust Gateway location response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/zero-trust-gateway_empty_response'
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_api-response-common-failure
                type: object
          description: Delete a Zero Trust Gateway location response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete a Zero Trust Gateway location
      tags:
        - Zero Trust Gateway locations
      x-api-token-group:
        - Cloudflare Zero Trust Secure DNS Locations Write
        - Zero Trust Write
components:
  schemas:
    zero-trust-gateway_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/zero-trust-gateway_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
          type: object
        messages:
          allOf:
            - $ref: '#/components/schemas/zero-trust-gateway_messages'
          example: []
          type: object
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    zero-trust-gateway_client-default:
      default: false
      description: True if the location is the default location.
      example: false
      type: boolean
      x-auditable: true
    zero-trust-gateway_components-schemas-response_collection:
      allOf:
        - $ref: '#/components/schemas/zero-trust-gateway_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/zero-trust-gateway_locations'
              type: array
      type: object
    zero-trust-gateway_components-schemas-uuid:
      example: ed35569b41ce4d1facfe683550f54086
      type: string
      x-auditable: true
    zero-trust-gateway_dns-destination-ips-id-write:
      description: >-
        The identifier of the pair of IPv4 addresses assigned to this location.
        When creating a location, if this field is absent or set with null, the
        pair of shared IPv4 addresses (0e4a32c6-6fb8-4858-9296-98f51631e8e6) is
        auto-assigned. When updating a location, if the field is absent or set
        with null, the pre-assigned pair remains unchanged.
      example: 0e4a32c6-6fb8-4858-9296-98f51631e8e6
      type: string
      x-auditable: true
      x-stainless-terraform-configurability: computed_optional
    zero-trust-gateway_ecs-support:
      default: false
      description: True if the location needs to resolve EDNS queries.
      example: false
      type: boolean
      x-auditable: true
    zero-trust-gateway_empty_response:
      allOf:
        - $ref: '#/components/schemas/zero-trust-gateway_api-response-single'
        - properties:
            result:
              type: object
      type: object
    zero-trust-gateway_endpoints:
      description: >-
        The destination endpoints configured for this location. When updating a
        location, if this field is absent or set with null, the endpoints
        configuration remains unchanged.
      nullable: true
      properties:
        doh:
          $ref: '#/components/schemas/zero-trust-gateway_doh_endpoint'
        dot:
          $ref: '#/components/schemas/zero-trust-gateway_dot_endpoint'
        ipv4:
          $ref: '#/components/schemas/zero-trust-gateway_ipv4_endpoint'
        ipv6:
          $ref: '#/components/schemas/zero-trust-gateway_ipv6_endpoint'
      required:
        - ipv4
        - ipv6
        - doh
        - dot
      type: object
      x-stainless-terraform-configurability: optional
    zero-trust-gateway_ipv4_networks:
      description: >-
        A list of network ranges that requests from this location would
        originate from. A non-empty list is only effective if the ipv4 endpoint
        is enabled for this location.
      items:
        $ref: '#/components/schemas/zero-trust-gateway_ipv4_network'
      nullable: true
      type: array
      x-stainless-terraform-configurability: computed_optional
    zero-trust-gateway_schemas-identifier:
      example: 699d98642c564d2e855e9661899b7252
      type: string
      x-auditable: true
    zero-trust-gateway_schemas-name:
      description: The name of the location.
      example: Austin Office Location
      type: string
      x-auditable: true
    zero-trust-gateway_schemas-single_response:
      allOf:
        - $ref: '#/components/schemas/zero-trust-gateway_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/zero-trust-gateway_locations'
      type: object
