openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/gateway/certificates:
    get:
      description: Fetches all Zero Trust certificates for an account.
      operationId: zero-trust-certificates-list-zero-trust-certificates
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_response_collection'
          description: List Zero Trust certificates response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_response_collection
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_api-response-common-failure
                type: object
          description: List Zero Trust certificates response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List Zero Trust certificates
      tags:
        - Zero Trust certificates
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
    post:
      description: Creates a new Zero Trust certificate.
      operationId: zero-trust-certificates-create-zero-trust-certificate
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/zero-trust-gateway_generate-cert-request'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_single_response'
          description: Create Zero Trust certificate response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/zero-trust-gateway_single_response'
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_api-response-common-failure
                type: object
          description: Create Zero Trust certificate response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create Zero Trust certificate
      tags:
        - Zero Trust certificates
      x-api-token-group:
        - Zero Trust Write
  /accounts/{account_id}/gateway/certificates/{certificate_id}:
    get:
      description: Fetches a single Zero Trust certificate.
      operationId: zero-trust-certificates-zero-trust-certificate-details
      parameters:
        - in: path
          name: certificate_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_single_response'
          description: Get Zero Trust certificate details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/zero-trust-gateway_single_response'
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_api-response-common-failure
                type: object
          description: Get Zero Trust certificate details response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get Zero Trust certificate details
      tags:
        - Zero Trust certificates
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
    delete:
      description: >-
        Deletes a gateway-managed Zero Trust certificate. A certificate must be
        deactivated from the edge (inactive) before it is deleted.
      operationId: zero-trust-certificates-delete-zero-trust-certificate
      parameters:
        - in: path
          name: certificate_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_single_response'
          description: Delete Zero Trust certificate response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/zero-trust-gateway_single_response'
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_api-response-common-failure
          description: Delete Zero Trust certificate response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete Zero Trust certificate
      tags:
        - Zero Trust certificates
      x-api-token-group:
        - Zero Trust Write
  /accounts/{account_id}/gateway/certificates/{certificate_id}/activate:
    post:
      description: Binds a single Zero Trust certificate to the edge.
      operationId: zero-trust-certificates-activate-zero-trust-certificate
      parameters:
        - in: path
          name: certificate_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_single_response'
          description: Activate Zero Trust certificate details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/zero-trust-gateway_single_response'
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_api-response-common-failure
          description: Activate Zero Trust certificate details response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Activate a Zero Trust certificate
      tags:
        - Zero Trust certificates
      x-api-token-group:
        - Zero Trust Write
  /accounts/{account_id}/gateway/certificates/{certificate_id}/deactivate:
    post:
      description: Unbinds a single Zero Trust certificate from the edge
      operationId: zero-trust-certificates-deactivate-zero-trust-certificate
      parameters:
        - in: path
          name: certificate_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_uuid'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/zero-trust-gateway_schemas-identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_single_response'
          description: Deactivate Zero Trust certificate details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/zero-trust-gateway_single_response'
                  - $ref: >-
                      #/components/schemas/zero-trust-gateway_api-response-common-failure
                type: object
          description: Deactivate Zero Trust certificate details response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Deactivate a Zero Trust certificate
      tags:
        - Zero Trust certificates
      x-api-token-group:
        - Zero Trust Write
components:
  schemas:
    zero-trust-gateway_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/zero-trust-gateway_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
          type: object
        messages:
          allOf:
            - $ref: '#/components/schemas/zero-trust-gateway_messages'
          example: []
          type: object
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    zero-trust-gateway_generate-cert-request:
      properties:
        validity_period_days:
          description: >-
            Number of days the generated certificate will be valid, minimum 1
            day and maximum 30 years. Defaults to 5 years. In terraform,
            validity_period_days can only be used while creating a certificate,
            and this CAN NOT be used to extend the validity of an already
            generated certificate.
          example: 1826
          type: integer
          x-auditable: true
      type: object
    zero-trust-gateway_response_collection:
      allOf:
        - $ref: '#/components/schemas/zero-trust-gateway_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/zero-trust-gateway_certificates'
              type: array
      type: object
    zero-trust-gateway_schemas-identifier:
      example: 699d98642c564d2e855e9661899b7252
      type: string
      x-auditable: true
    zero-trust-gateway_single_response:
      allOf:
        - $ref: '#/components/schemas/zero-trust-gateway_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/zero-trust-gateway_certificates'
      type: object
    zero-trust-gateway_uuid:
      description: Certificate UUID tag.
      example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      maxLength: 36
      type: string
      x-auditable: true
