openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/zt_risk_scoring/integrations:
    get:
      operationId: dlp-zt-risk-score-integration-list
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_RiskScoreIntegrationArray'
                    type: object
          description: List response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: List failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List all risk score integrations for the account.
      tags:
        - Zero Trust Risk Scoring Integrations
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
    post:
      operationId: dlp-zt-risk-score-integration-create
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dlp_CreateIntegrationBody'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_RiskScoreIntegration'
                    type: object
          description: Create response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Create failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create new risk score integration.
      tags:
        - Zero Trust Risk Scoring Integrations
      x-api-token-group:
        - Zero Trust Write
  /accounts/{account_id}/zt_risk_scoring/integrations/reference_id/{reference_id}:
    get:
      operationId: dlp-zt-risk-score-integration-get-by-reference-id
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
        - in: path
          name: reference_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_RiskScoreIntegration'
                    type: object
          description: Get response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Get failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get risk score integration by reference id.
      tags:
        - Zero Trust Risk Scoring Integrations
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
  /accounts/{account_id}/zt_risk_scoring/integrations/{integration_id}:
    get:
      operationId: dlp-zt-risk-score-integration-get
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
        - in: path
          name: integration_id
          required: true
          schema:
            format: uuid
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_RiskScoreIntegration'
                    type: object
          description: Get response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Get failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get risk score integration by id.
      tags:
        - Zero Trust Risk Scoring Integrations
      x-api-token-group:
        - Zero Trust Read
        - Zero Trust Write
    put:
      description: >-
        Overwrite the reference_id, tenant_url, and active values with the ones
        provided.
      operationId: dlp-zt-risk-score-integration-update
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
        - in: path
          name: integration_id
          required: true
          schema:
            format: uuid
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dlp_UpdateIntegrationBody'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_RiskScoreIntegration'
                    type: object
          description: Update response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Update failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update a risk score integration.
      tags:
        - Zero Trust Risk Scoring Integrations
      x-api-token-group:
        - Zero Trust Write
    delete:
      operationId: dlp-zt-risk-score-integration-delete
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
        - in: path
          name: integration_id
          required: true
          schema:
            format: uuid
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/dlp_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/dlp_Empty'
                    type: object
          description: Delete response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Delete failure response.
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete a risk score integration.
      tags:
        - Zero Trust Risk Scoring Integrations
      x-api-token-group:
        - Zero Trust Write
components:
  schemas:
    dlp_CreateIntegrationBody:
      properties:
        integration_type:
          $ref: '#/components/schemas/dlp_RiskScoreIntegrationType'
        reference_id:
          description: >-
            A reference id that can be supplied by the client. Currently this
            should be set to the Access-Okta IDP ID (a UUIDv4).

            https://developers.cloudflare.com/api/operations/access-identity-providers-get-an-access-identity-provider
          nullable: true
          type: string
        tenant_url:
          description: The base url of the tenant, e.g. "https://tenant.okta.com".
          format: uri
          type: string
      required:
        - integration_type
        - tenant_url
      type: object
    dlp_Empty:
      nullable: true
      type: object
    dlp_RiskScoreIntegration:
      properties:
        account_tag:
          description: The Cloudflare account tag.
          type: string
        active:
          description: >-
            Whether this integration is enabled and should export changes in
            risk score.
          type: boolean
        created_at:
          description: When the integration was created in RFC3339 format.
          format: date-time
          type: string
        id:
          description: The id of the integration, a UUIDv4.
          format: uuid
          type: string
        integration_type:
          $ref: '#/components/schemas/dlp_RiskScoreIntegrationType'
        reference_id:
          description: >-
            A reference ID defined by the client.

            Should be set to the Access-Okta IDP integration ID.

            Useful when the risk-score integration needs to be associated with a
            secondary asset and recalled using that ID.
          type: string
        tenant_url:
          description: The base URL for the tenant. E.g. "https://tenant.okta.com".
          type: string
        well_known_url:
          description: >-
            The URL for the Shared Signals Framework configuration, e.g.
            "/.well-known/sse-configuration/{integration_uuid}/".
            https://openid.net/specs/openid-sse-framework-1_0.html#rfc.section.6.2.1.
          type: string
      required:
        - id
        - account_tag
        - integration_type
        - reference_id
        - tenant_url
        - well_known_url
        - active
        - created_at
      type: object
    dlp_RiskScoreIntegrationArray:
      items:
        $ref: '#/components/schemas/dlp_RiskScoreIntegration'
      type: array
    dlp_UpdateIntegrationBody:
      properties:
        active:
          description: >-
            Whether this integration is enabled. If disabled, no risk changes
            will be exported to the third-party.
          type: boolean
        reference_id:
          description: >-
            A reference id that can be supplied by the client. Currently this
            should be set to the Access-Okta IDP ID (a UUIDv4).

            https://developers.cloudflare.com/api/operations/access-identity-providers-get-an-access-identity-provider
          nullable: true
          type: string
        tenant_url:
          description: The base url of the tenant, e.g. "https://tenant.okta.com".
          format: uri
          type: string
      required:
        - tenant_url
        - active
      type: object
    dlp_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/dlp_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/dlp_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    dlp_api-response-single:
      allOf:
        - $ref: '#/components/schemas/dlp_api-response-common'
      type: object
