openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/available_plans:
    get:
      description: Lists available plans the zone can subscribe to.
      operationId: zone-rate-plan-list-available-plans
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/bill-subs-api_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/bill-subs-api_api-response-collection'
                  - properties:
                      result:
                        items:
                          $ref: >-
                            #/components/schemas/bill-subs-api_available-rate-plan
                        type: array
          description: List Available Plans response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: >-
                          #/components/schemas/bill-subs-api_api-response-collection
                      - properties:
                          result:
                            items:
                              $ref: >-
                                #/components/schemas/bill-subs-api_available-rate-plan
                            type: array
                  - $ref: >-
                      #/components/schemas/bill-subs-api_api-response-common-failure
          description: List Available Plans response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List Available Plans
      tags:
        - Zone Rate Plan
      x-api-token-group:
        - Billing Write
        - Billing Read
      x-cfPermissionsRequired:
        enum:
          - '#billing:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /zones/{zone_id}/available_plans/{plan_identifier}:
    get:
      description: Details of the available plan that the zone can subscribe to.
      operationId: zone-rate-plan-available-plan-details
      parameters:
        - in: path
          name: plan_identifier
          required: true
          schema:
            $ref: '#/components/schemas/bill-subs-api_identifier'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/bill-subs-api_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/bill-subs-api_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/bill-subs-api_available-rate-plan'
          description: Available Plan Details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: '#/components/schemas/bill-subs-api_api-response-single'
                      - properties:
                          result:
                            $ref: >-
                              #/components/schemas/bill-subs-api_available-rate-plan
                  - $ref: >-
                      #/components/schemas/bill-subs-api_api-response-common-failure
          description: Available Plan Details response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Available Plan Details
      tags:
        - Zone Rate Plan
      x-api-token-group:
        - Billing Write
        - Billing Read
      x-cfPermissionsRequired:
        enum:
          - '#billing:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /zones/{zone_id}/available_rate_plans:
    get:
      description: Lists all rate plans the zone can subscribe to.
      operationId: zone-rate-plan-list-available-rate-plans
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/bill-subs-api_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bill-subs-api_plan_response_collection'
          description: List Available Rate Plans response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/bill-subs-api_plan_response_collection
                  - $ref: >-
                      #/components/schemas/bill-subs-api_api-response-common-failure
          description: List Available Rate Plans response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List Available Rate Plans
      tags:
        - Zone Rate Plan
      x-api-token-group:
        - Billing Write
        - Billing Read
      x-cfPermissionsRequired:
        enum:
          - '#billing:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    bill-subs-api_api-response-collection:
      allOf:
        - $ref: '#/components/schemas/bill-subs-api_api-response-common'
        - properties:
            result:
              items: {}
              nullable: true
              type: array
            result_info:
              $ref: '#/components/schemas/bill-subs-api_result_info'
      type: object
    bill-subs-api_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/bill-subs-api_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/bill-subs-api_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    bill-subs-api_api-response-single:
      allOf:
        - $ref: '#/components/schemas/bill-subs-api_api-response-common'
        - properties:
            result:
              anyOf:
                - nullable: true
                  type: object
                - nullable: true
                  type: string
      type: object
    bill-subs-api_available-rate-plan:
      properties:
        can_subscribe:
          $ref: '#/components/schemas/bill-subs-api_can_subscribe'
        currency:
          $ref: '#/components/schemas/bill-subs-api_currency'
        externally_managed:
          $ref: '#/components/schemas/bill-subs-api_externally_managed'
        frequency:
          $ref: '#/components/schemas/bill-subs-api_schemas-frequency'
        id:
          $ref: '#/components/schemas/bill-subs-api_identifier'
        is_subscribed:
          $ref: '#/components/schemas/bill-subs-api_is_subscribed'
        legacy_discount:
          $ref: '#/components/schemas/bill-subs-api_legacy_discount'
        legacy_id:
          $ref: '#/components/schemas/bill-subs-api_legacy_id'
        name:
          $ref: '#/components/schemas/bill-subs-api_schemas-name'
        price:
          $ref: '#/components/schemas/bill-subs-api_schemas-price'
      type: object
    bill-subs-api_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    bill-subs-api_plan_response_collection:
      allOf:
        - $ref: '#/components/schemas/bill-subs-api_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/bill-subs-api_schemas-rate-plan'
              type: array
          type: object
