openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/cloud_connector/rules:
    put:
      operationId: zone-cloud-conenctor-rules-put
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/cloud-connector_identifier'
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/cloud-connector_rule'
              type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/cloud-connector_api-response-common'
                  - properties:
                      result:
                        $ref: '#/components/schemas/cloud-connector_rules'
                    type: object
                type: object
          description: Cloud Connector rules response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/cloud-connector_api-response-common-failure
          description: Cloud Connector response failure
        5XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/cloud-connector_api-response-common-failure
          description: Cloud Connector response failure
      security:
        - api_email: []
          api_key: []
      summary: Put Rules
      tags:
        - Zone Cloud Connector Rules PUT
      x-api-token-group:
        - Cloud Connector Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    cloud-connector_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/cloud-connector_messages'
        messages:
          $ref: '#/components/schemas/cloud-connector_messages'
        success:
          description: Whether the API call was successful.
          enum:
            - true
          example: true
          type: boolean
      required:
        - success
        - errors
        - messages
      type: object
    cloud-connector_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/cloud-connector_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/cloud-connector_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    cloud-connector_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
    cloud-connector_rule:
      properties:
        description:
          example: Rule description
          type: string
          x-auditable: true
        enabled:
          example: true
          type: boolean
          x-auditable: true
        expression:
          example: http.cookie eq "a=b"
          type: string
          x-auditable: true
        id:
          example: 95c365e17e1b46599cd99e5b231fac4e
          type: string
          x-auditable: true
        parameters:
          description: Parameters of Cloud Connector Rule
          properties:
            host:
              description: Host to perform Cloud Connection to
              example: examplebucket.s3.eu-north-1.amazonaws.com
              type: string
              x-auditable: true
          type: object
        provider:
          $ref: '#/components/schemas/cloud-connector_provider'
      type: object
    cloud-connector_rules:
      description: List of Cloud Connector rules
      items:
        $ref: '#/components/schemas/cloud-connector_rule'
      type: array
