openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/access/certificates:
    get:
      description: Lists all mTLS certificates.
      operationId: zone-level-access-mtls-authentication-list-mtls-certificates
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/access_certificates_components-schemas-response_collection-2
          description: List mTLS certificates response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: List mTLS certificates response failure
      security:
        - api_email: []
          api_key: []
      summary: List mTLS certificates
      tags:
        - Zone-Level Access mTLS authentication
      x-api-token-group:
        - 'Access: Mutual TLS Certificates Write'
        - 'Access: Mutual TLS Certificates Read'
    post:
      description: Adds a new mTLS root certificate to Access.
      operationId: zone-level-access-mtls-authentication-add-an-mtls-certificate
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                associated_hostnames:
                  $ref: '#/components/schemas/access_schemas-associated_hostnames'
                certificate:
                  description: The certificate content.
                  example: >-
                    -----BEGIN CERTIFICATE-----

                    MIIGAjCCA+qgAwIBAgIJAI7kymlF7CWT...N4RI7KKB7nikiuUf8vhULKy5IX10

                    DrUtmu/B

                    -----END CERTIFICATE-----
                  type: string
                name:
                  $ref: >-
                    #/components/schemas/access_certificates_components-schemas-name-2
              required:
                - name
                - certificate
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/access_certificates_components-schemas-single_response-2
          description: Add an mTLS certificate response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Add an mTLS certificate response failure
      security:
        - api_email: []
          api_key: []
      summary: Add an mTLS certificate
      tags:
        - Zone-Level Access mTLS authentication
      x-api-token-group:
        - 'Access: Mutual TLS Certificates Write'
  /zones/{zone_id}/access/certificates/settings:
    get:
      description: List all mTLS hostname settings for this zone.
      operationId: >-
        zone-level-access-mtls-authentication-list-mtls-certificates-hostname-settings
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/access_schemas-response_collection_hostnames
          description: List mTLS hostname settings response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: List mTLS hostname settings response failure
      security:
        - api_email: []
          api_key: []
      summary: List all mTLS hostname settings
      tags:
        - Zone-Level Access mTLS authentication
      x-api-token-group:
        - 'Access: Mutual TLS Certificates Write'
        - 'Access: Mutual TLS Certificates Read'
    put:
      description: Updates an mTLS certificate's hostname settings.
      operationId: >-
        zone-level-access-mtls-authentication-update-an-mtls-certificate-settings
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                settings:
                  items:
                    $ref: '#/components/schemas/access_schemas-settings'
                  type: array
              required:
                - settings
              type: object
        required: true
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/access_schemas-response_collection_hostnames
          description: Update an mTLS certificates hostname settings response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Update an mTLS certificates hostname settings failure
      security:
        - api_email: []
          api_key: []
      summary: Update an mTLS certificate's hostname settings
      tags:
        - Zone-Level Access mTLS authentication
      x-api-token-group:
        - 'Access: Mutual TLS Certificates Write'
  /zones/{zone_id}/access/certificates/{certificate_id}:
    get:
      description: Fetches a single mTLS certificate.
      operationId: zone-level-access-mtls-authentication-get-an-mtls-certificate
      parameters:
        - in: path
          name: certificate_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/access_certificates_components-schemas-single_response-2
          description: Get an mTLS certificate response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Get an mTLS certificate response failure
      security:
        - api_email: []
          api_key: []
      summary: Get an mTLS certificate
      tags:
        - Zone-Level Access mTLS authentication
      x-api-token-group:
        - 'Access: Mutual TLS Certificates Write'
        - 'Access: Mutual TLS Certificates Read'
    put:
      description: Updates a configured mTLS certificate.
      operationId: zone-level-access-mtls-authentication-update-an-mtls-certificate
      parameters:
        - in: path
          name: certificate_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                associated_hostnames:
                  $ref: '#/components/schemas/access_schemas-associated_hostnames'
                name:
                  $ref: >-
                    #/components/schemas/access_certificates_components-schemas-name-2
              required:
                - associated_hostnames
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/access_certificates_components-schemas-single_response-2
          description: Update an mTLS certificate response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Update an mTLS certificate response failure
      security:
        - api_email: []
          api_key: []
      summary: Update an mTLS certificate
      tags:
        - Zone-Level Access mTLS authentication
      x-api-token-group:
        - 'Access: Mutual TLS Certificates Write'
    delete:
      description: Deletes an mTLS certificate.
      operationId: zone-level-access-mtls-authentication-delete-an-mtls-certificate
      parameters:
        - in: path
          name: certificate_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_components-schemas-id_response'
          description: Delete an mTLS certificate response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Delete an mTLS certificate response failure
      security:
        - api_email: []
          api_key: []
      summary: Delete an mTLS certificate
      tags:
        - Zone-Level Access mTLS authentication
      x-api-token-group:
        - 'Access: Mutual TLS Certificates Write'
components:
  schemas:
    access_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/access_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/access_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    access_certificates_components-schemas-name-2:
      description: The name of the certificate.
      example: Allow devs
      type: string
    access_certificates_components-schemas-response_collection-2:
      allOf:
        - $ref: '#/components/schemas/access_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/access_components-schemas-certificates'
              type: array
      type: object
    access_certificates_components-schemas-single_response-2:
      allOf:
        - $ref: '#/components/schemas/access_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/access_components-schemas-certificates'
      type: object
    access_components-schemas-id_response:
      allOf:
        - $ref: '#/components/schemas/access_api-response-common'
        - properties:
            result:
              properties:
                id:
                  $ref: '#/components/schemas/access_uuid'
              type: object
      type: object
    access_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
    access_schemas-associated_hostnames:
      description: The hostnames of the applications that will use this certificate.
      items:
        description: A fully-qualified domain name (FQDN).
        example: admin.example.com
        type: string
      type: array
    access_schemas-response_collection_hostnames:
      allOf:
        - $ref: '#/components/schemas/access_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/access_schemas-settings'
              type: array
      type: object
    access_schemas-settings:
      additionalProperties: false
      properties:
        china_network:
          description: >-
            Request client certificates for this hostname in China. Can only be
            set to true if this zone is china network enabled.
          example: false
          type: boolean
        client_certificate_forwarding:
          description: >-
            Client Certificate Forwarding is a feature that takes the client
            cert provided by the eyeball to the edge, and forwards it to the
            origin as a HTTP header to allow logging on the origin.
          example: true
          type: boolean
        hostname:
          description: The hostname that these settings apply to.
          example: admin.example.com
          type: string
      required:
        - hostname
        - china_network
        - client_certificate_forwarding
      title: Hostname Settings
      type: object
    access_uuid:
      description: UUID.
      example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      maxLength: 36
      type: string
      x-auditable: true
