openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/subscription:
    get:
      description: Lists zone subscription details.
      operationId: zone-subscription-zone-subscription-details
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/bill-subs-api_schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/bill-subs-api_zone_subscription_response_single
          description: Zone Subscription Details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/bill-subs-api_zone_subscription_response_single
                  - $ref: >-
                      #/components/schemas/bill-subs-api_api-response-common-failure
          description: Zone Subscription Details response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Zone Subscription Details
      tags:
        - Zone Subscription
      x-api-token-group:
        - Billing Write
        - Billing Read
      x-cfPermissionsRequired:
        enum:
          - '#billing:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    post:
      description: Create a zone subscription, either plan or add-ons.
      operationId: zone-subscription-create-zone-subscription
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/bill-subs-api_schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bill-subs-api_subscription-v2'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/bill-subs-api_zone_subscription_response_single
          description: Create Zone Subscription response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/bill-subs-api_zone_subscription_response_single
                  - $ref: >-
                      #/components/schemas/bill-subs-api_api-response-common-failure
          description: Create Zone Subscription response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create Zone Subscription
      tags:
        - Zone Subscription
      x-api-token-group:
        - Billing Write
      x-cfPermissionsRequired:
        enum:
          - '#billing:read'
          - '#billing:edit'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    put:
      description: Updates zone subscriptions, either plan or add-ons.
      operationId: zone-subscription-update-zone-subscription
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/bill-subs-api_schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bill-subs-api_subscription-v2'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/bill-subs-api_zone_subscription_response_single
          description: Update Zone Subscription response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/bill-subs-api_zone_subscription_response_single
                  - $ref: >-
                      #/components/schemas/bill-subs-api_api-response-common-failure
          description: Update Zone Subscription response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update Zone Subscription
      tags:
        - Zone Subscription
      x-api-token-group:
        - Billing Write
      x-cfPermissionsRequired:
        enum:
          - '#billing:read'
          - '#billing:edit'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    bill-subs-api_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/bill-subs-api_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/bill-subs-api_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    bill-subs-api_schemas-identifier:
      description: Subscription identifier tag.
      example: 506e3185e9c882d175a2d0cb0093d9f2
      maxLength: 32
      readOnly: true
      type: string
    bill-subs-api_subscription-v2:
      properties:
        app:
          properties:
            install_id:
              $ref: '#/components/schemas/bill-subs-api_install_id'
        component_values:
          $ref: '#/components/schemas/bill-subs-api_component_values'
        currency:
          $ref: '#/components/schemas/bill-subs-api_currency'
        current_period_end:
          $ref: '#/components/schemas/bill-subs-api_current_period_end'
        current_period_start:
          $ref: '#/components/schemas/bill-subs-api_current_period_start'
        frequency:
          $ref: '#/components/schemas/bill-subs-api_frequency'
        id:
          $ref: '#/components/schemas/bill-subs-api_schemas-identifier'
        price:
          $ref: '#/components/schemas/bill-subs-api_price'
        rate_plan:
          $ref: '#/components/schemas/bill-subs-api_rate_plan'
        state:
          $ref: '#/components/schemas/bill-subs-api_state'
        zone:
          $ref: '#/components/schemas/bill-subs-api_zone'
      type: object
    bill-subs-api_zone_subscription_response_single:
      allOf:
        - $ref: '#/components/schemas/bill-subs-api_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/bill-subs-api_subscription'
          type: object
