openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/access/organizations:
    get:
      description: Returns the configuration for your Zero Trust organization.
      operationId: zone-level-zero-trust-organization-get-your-zero-trust-organization
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: >-
              #/components/schemas/access_organizations_components-schemas-identifier
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/access_organizations_components-schemas-single_response
          description: Get your Zero Trust organization response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Get your Zero Trust organization response failure
      security:
        - api_email: []
          api_key: []
      summary: Get your Zero Trust organization
      tags:
        - Zone-Level Zero Trust organization
      x-api-token-group:
        - 'Access: Organizations, Identity Providers, and Groups Revoke'
        - 'Access: Organizations, Identity Providers, and Groups Write'
        - 'Access: Organizations, Identity Providers, and Groups Read'
    post:
      description: Sets up a Zero Trust organization for your account.
      operationId: zone-level-zero-trust-organization-create-your-zero-trust-organization
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: >-
              #/components/schemas/access_organizations_components-schemas-identifier
      requestBody:
        content:
          application/json:
            schema:
              properties:
                auth_domain:
                  $ref: '#/components/schemas/access_schemas-auth_domain'
                is_ui_read_only:
                  $ref: '#/components/schemas/access_schemas-is_ui_read_only'
                login_design:
                  $ref: '#/components/schemas/access_schemas-login_design'
                name:
                  $ref: >-
                    #/components/schemas/access_organizations_components-schemas-name
                ui_read_only_toggle_reason:
                  $ref: '#/components/schemas/access_ui_read_only_toggle_reason'
                user_seat_expiration_inactive_time:
                  $ref: >-
                    #/components/schemas/access_schemas-user_seat_expiration_inactive_time
              required:
                - name
                - auth_domain
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/access_organizations_components-schemas-single_response
          description: Create your Zero Trust organization response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Create your Zero Trust organization response failure
      security:
        - api_email: []
          api_key: []
      summary: Create your Zero Trust organization
      tags:
        - Zone-Level Zero Trust organization
      x-api-token-group:
        - 'Access: Organizations, Identity Providers, and Groups Write'
    put:
      description: Updates the configuration for your Zero Trust organization.
      operationId: zone-level-zero-trust-organization-update-your-zero-trust-organization
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: >-
              #/components/schemas/access_organizations_components-schemas-identifier
      requestBody:
        content:
          application/json:
            schema:
              properties:
                auth_domain:
                  $ref: '#/components/schemas/access_schemas-auth_domain'
                is_ui_read_only:
                  $ref: '#/components/schemas/access_schemas-is_ui_read_only'
                login_design:
                  $ref: '#/components/schemas/access_schemas-login_design'
                name:
                  $ref: >-
                    #/components/schemas/access_organizations_components-schemas-name
                ui_read_only_toggle_reason:
                  $ref: '#/components/schemas/access_ui_read_only_toggle_reason'
                user_seat_expiration_inactive_time:
                  $ref: >-
                    #/components/schemas/access_schemas-user_seat_expiration_inactive_time
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/access_organizations_components-schemas-single_response
          description: Update your Zero Trust organization response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Update your Zero Trust organization response failure
      security:
        - api_email: []
          api_key: []
      summary: Update your Zero Trust organization
      tags:
        - Zone-Level Zero Trust organization
      x-api-token-group:
        - 'Access: Organizations, Identity Providers, and Groups Write'
  /zones/{zone_id}/access/organizations/revoke_user:
    post:
      description: Revokes a user's access across all applications.
      operationId: zone-level-zero-trust-organization-revoke-all-access-tokens-for-a-user
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: >-
              #/components/schemas/access_organizations_components-schemas-identifier
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  description: The email of the user to revoke.
                  example: test@example.com
                  type: string
              required:
                - email
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_empty_response'
          description: Revoke all Access tokens for a user response
        4xx:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Revoke all Access tokens for a user response failure
      security:
        - api_email: []
          api_key: []
      summary: Revoke all Access tokens for a user
      tags:
        - Zone-Level Zero Trust organization
      x-api-token-group:
        - 'Access: Organizations, Identity Providers, and Groups Write'
components:
  schemas:
    access_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/access_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/access_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    access_empty_response:
      allOf:
        - properties:
            result:
              enum:
                - true
                - false
              example: true
              type: boolean
            success:
              enum:
                - true
                - false
              example: true
              type: boolean
      type: object
    access_organizations_components-schemas-identifier:
      example: 699d98642c564d2e855e9661899b7252
    access_organizations_components-schemas-name:
      description: The name of your Zero Trust organization.
      example: Widget Corps Internal Applications
      type: string
    access_organizations_components-schemas-single_response:
      allOf:
        - $ref: '#/components/schemas/access_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/access_schemas-organizations'
      type: object
    access_schemas-auth_domain:
      description: The unique subdomain assigned to your Zero Trust organization.
      example: test.cloudflareaccess.com
      type: string
    access_schemas-is_ui_read_only:
      description: >-
        Lock all settings as Read-Only in the Dashboard, regardless of user
        permission. Updates may only be made via the API or Terraform for this
        account when enabled.
      example: 'false'
      type: boolean
    access_schemas-login_design:
      properties:
        background_color:
          description: The background color on your login page.
          example: '#c5ed1b'
          type: string
        footer_text:
          description: The text at the bottom of your login page.
          example: This is an example description.
          type: string
        header_text:
          description: The text at the top of your login page.
          example: This is an example description.
          type: string
        logo_path:
          description: The URL of the logo on your login page.
          example: https://example.com/logo.png
          type: string
        text_color:
          description: The text color on your login page.
          example: '#c5ed1b'
          type: string
    access_schemas-user_seat_expiration_inactive_time:
      description: >-
        The amount of time a user seat is inactive before it expires. When the
        user seat exceeds the set time of inactivity, the user is removed as an
        active seat and no longer counts against your Teams seat count. Must be
        in the format `300ms` or `2h45m`. Valid time units are: `ns`, `us` (or
        `µs`), `ms`, `s`, `m`, `h`.
      example: 720h
      type: string
    access_ui_read_only_toggle_reason:
      description: A description of the reason why the UI read only field is being toggled.
      example: Temporarily turn off the UI read only lock to make a change via the UI
      type: string
