openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/firewall/lockdowns:
    get:
      description: >-
        Fetches Zone Lockdown rules. You can filter the results using several
        optional parameters.
      operationId: zone-lockdown-list-zone-lockdown-rules
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/firewall_identifier'
        - in: query
          name: page
          schema:
            default: 1
            description: Page number of paginated results.
            minimum: 1
            type: number
        - in: query
          name: description
          schema:
            allOf:
              - $ref: '#/components/schemas/firewall_schemas-description_search'
        - in: query
          name: modified_on
          schema:
            allOf:
              - $ref: '#/components/schemas/firewall_modified_on'
        - in: query
          name: ip
          schema:
            allOf:
              - $ref: '#/components/schemas/firewall_ip_search'
        - in: query
          name: priority
          schema:
            allOf:
              - $ref: '#/components/schemas/firewall_schemas-priority'
        - in: query
          name: uri_search
          schema:
            allOf:
              - $ref: '#/components/schemas/firewall_uri_search'
        - in: query
          name: ip_range_search
          schema:
            allOf:
              - $ref: '#/components/schemas/firewall_ip_range_search'
        - in: query
          name: per_page
          schema:
            default: 20
            description: >-
              The maximum number of results per page. You can only set the value
              to `1` or to a multiple of 5 such as `5`, `10`, `15`, or `20`.
            maximum: 1000
            minimum: 1
            type: number
        - in: query
          name: created_on
          schema:
            description: The timestamp of when the rule was created.
            example: '2014-01-01T05:20:00.12345Z'
            format: date-time
            readOnly: true
            type: string
        - in: query
          name: description_search
          schema:
            description: A string to search for in the description of existing rules.
            example: endpoints
            type: string
        - in: query
          name: ip_search
          schema:
            description: A single IP address to search for in existing rules.
            example: 1.2.3.4
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/firewall_zonelockdown_response_collection'
          description: List Zone Lockdown rules response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/firewall_zonelockdown_response_collection
                  - $ref: '#/components/schemas/firewall_api-response-common-failure'
          description: List Zone Lockdown rules response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List Zone Lockdown rules
      tags:
        - Zone Lockdown
      x-api-token-group:
        - Firewall Services Write
        - Firewall Services Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: true
    post:
      description: Creates a new Zone Lockdown rule.
      operationId: zone-lockdown-create-a-zone-lockdown-rule
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/firewall_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                configurations:
                  $ref: '#/components/schemas/firewall_configurations'
                description:
                  $ref: '#/components/schemas/firewall_description'
                paused:
                  $ref: '#/components/schemas/firewall_schemas-paused'
                priority:
                  $ref: '#/components/schemas/firewall_schemas-priority'
                urls:
                  $ref: '#/components/schemas/firewall_urls'
              required:
                - urls
                - configurations
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/firewall_zonelockdown_response_single'
          description: Create a Zone Lockdown rule response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/firewall_zonelockdown_response_single'
                  - $ref: '#/components/schemas/firewall_api-response-common-failure'
          description: Create a Zone Lockdown rule response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create a Zone Lockdown rule
      tags:
        - Zone Lockdown
      x-api-token-group:
        - Firewall Services Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: true
  /zones/{zone_id}/firewall/lockdowns/{lock_downs_id}:
    get:
      description: Fetches the details of a Zone Lockdown rule.
      operationId: zone-lockdown-get-a-zone-lockdown-rule
      parameters:
        - in: path
          name: lock_downs_id
          required: true
          schema:
            $ref: '#/components/schemas/firewall_lockdowns_components-schemas-id'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/firewall_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/firewall_zonelockdown_response_single'
          description: Get a Zone Lockdown rule response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/firewall_zonelockdown_response_single'
                  - $ref: '#/components/schemas/firewall_api-response-common-failure'
          description: Get a Zone Lockdown rule response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Get a Zone Lockdown rule
      tags:
        - Zone Lockdown
      x-api-token-group:
        - Firewall Services Write
        - Firewall Services Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: true
    put:
      description: Updates an existing Zone Lockdown rule.
      operationId: zone-lockdown-update-a-zone-lockdown-rule
      parameters:
        - in: path
          name: lock_downs_id
          required: true
          schema:
            $ref: '#/components/schemas/firewall_lockdowns_components-schemas-id'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/firewall_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                configurations:
                  $ref: '#/components/schemas/firewall_configurations'
                urls:
                  $ref: '#/components/schemas/firewall_urls'
              required:
                - urls
                - configurations
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/firewall_zonelockdown_response_single'
          description: Update a Zone Lockdown rule response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/firewall_zonelockdown_response_single'
                  - $ref: '#/components/schemas/firewall_api-response-common-failure'
          description: Update a Zone Lockdown rule response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update a Zone Lockdown rule
      tags:
        - Zone Lockdown
      x-api-token-group:
        - Firewall Services Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: true
    delete:
      description: Deletes an existing Zone Lockdown rule.
      operationId: zone-lockdown-delete-a-zone-lockdown-rule
      parameters:
        - in: path
          name: lock_downs_id
          required: true
          schema:
            $ref: '#/components/schemas/firewall_lockdowns_components-schemas-id'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/firewall_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  result:
                    properties:
                      id:
                        $ref: >-
                          #/components/schemas/firewall_lockdowns_components-schemas-id
                    type: object
                type: object
          description: Delete a Zone Lockdown rule response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      result:
                        properties:
                          id:
                            $ref: >-
                              #/components/schemas/firewall_lockdowns_components-schemas-id
                        type: object
                    type: object
                  - $ref: '#/components/schemas/firewall_api-response-common-failure'
          description: Delete a Zone Lockdown rule response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete a Zone Lockdown rule
      tags:
        - Zone Lockdown
      x-api-token-group:
        - Firewall Services Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: true
components:
  schemas:
    firewall_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/firewall_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/firewall_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Defines whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    firewall_configurations:
      description: >-
        A list of IP addresses or CIDR ranges that will be allowed to access the
        URLs specified in the Zone Lockdown rule. You can include any number of
        `ip` or `ip_range` configurations.
      items:
        anyOf:
          - $ref: '#/components/schemas/firewall_schemas-ip_configuration'
          - $ref: '#/components/schemas/firewall_schemas-cidr_configuration'
      type: array
    firewall_description:
      description: >-
        An informative summary of the rule. This value is sanitized and any tags
        will be removed.
      example: Prevent multiple login failures to mitigate brute force attacks
      maxLength: 1024
      type: string
      x-auditable: true
    firewall_identifier:
      description: Defines an identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    firewall_ip_range_search:
      description: A single IP address range to search for in existing rules.
      example: 1.2.3.0/16
      type: string
      x-auditable: true
    firewall_ip_search:
      description: A single IP address to search for in existing rules.
      example: 1.2.3.4
      type: string
    firewall_lockdowns_components-schemas-id:
      description: The unique identifier of the Zone Lockdown rule.
      example: 372e67954025e0ba6aaa6d586b9e0b59
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
    firewall_modified_on:
      description: The timestamp of when the rule was last modified.
      example: '2014-01-01T05:20:00.12345Z'
      format: date-time
      readOnly: true
      type: string
      x-auditable: true
    firewall_schemas-description_search:
      description: A string to search for in the description of existing rules.
      example: endpoints
      type: string
      x-auditable: true
    firewall_schemas-paused:
      description: When true, indicates that the rule is currently paused.
      example: false
      type: boolean
      x-auditable: true
    firewall_schemas-priority:
      description: >-
        The priority of the rule to control the processing order. A lower number
        indicates higher priority. If not provided, any rules with a configured
        priority will be processed before rules without a priority.
      example: 5
      type: number
      x-auditable: true
    firewall_uri_search:
      description: A single URI to search for in the list of URLs of existing rules.
      example: /some/path
      type: string
      x-auditable: true
    firewall_urls:
      description: >-
        The URLs to include in the current WAF override. You can use wildcards.
        Each entered URL will be escaped before use, which means you can only
        use simple wildcard patterns.
      items:
        example: shop.example.com/*
        type: string
        x-auditable: true
      type: array
    firewall_zonelockdown_response_collection:
      allOf:
        - $ref: '#/components/schemas/firewall_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/firewall_zonelockdown'
              type: array
          required:
            - result
          type: object
    firewall_zonelockdown_response_single:
      allOf:
        - $ref: '#/components/schemas/firewall_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/firewall_zonelockdown'
          required:
            - result
          type: object
