openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/access/apps/ca:
    get:
      description: Lists short-lived certificate CAs and their public keys.
      operationId: >-
        zone-level-access-short-lived-certificate-c-as-list-short-lived-certificate-c-as
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/access_ca_components-schemas-response_collection-2
          description: List short-lived certificate CAs response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: List short-lived certificate CAs response failure
      security:
        - api_email: []
          api_key: []
      summary: List short-lived certificate CAs
      tags:
        - Zone-Level Access short-lived certificate CAs
      x-api-token-group:
        - 'Access: Apps and Policies Write'
        - 'Access: Apps and Policies Read'
        - 'Access: Apps and Policies Write'
        - 'Access: Apps and Policies Read'
  /zones/{zone_id}/access/apps/{app_id}/ca:
    get:
      description: Fetches a short-lived certificate CA and its public key.
      operationId: >-
        zone-level-access-short-lived-certificate-c-as-get-a-short-lived-certificate-ca
      parameters:
        - in: path
          name: app_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/access_ca_components-schemas-single_response-2
          description: Get a short-lived certificate CA response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Get a short-lived certificate CA response failure
      security:
        - api_email: []
          api_key: []
      summary: Get a short-lived certificate CA
      tags:
        - Zone-Level Access short-lived certificate CAs
      x-api-token-group:
        - 'Access: Apps and Policies Write'
        - 'Access: Apps and Policies Read'
        - 'Access: Apps and Policies Write'
        - 'Access: Apps and Policies Read'
    post:
      description: Generates a new short-lived certificate CA and public key.
      operationId: >-
        zone-level-access-short-lived-certificate-c-as-create-a-short-lived-certificate-ca
      parameters:
        - in: path
          name: app_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/access_ca_components-schemas-single_response-2
          description: Create a short-lived certificate CA response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Create a short-lived certificate CA response failure
      security:
        - api_email: []
          api_key: []
      summary: Create a short-lived certificate CA
      tags:
        - Zone-Level Access short-lived certificate CAs
      x-api-token-group:
        - 'Access: Apps and Policies Write'
        - 'Access: Apps and Policies Write'
    delete:
      description: Deletes a short-lived certificate CA.
      operationId: >-
        zone-level-access-short-lived-certificate-c-as-delete-a-short-lived-certificate-ca
      parameters:
        - in: path
          name: app_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_ca_components-schemas-id_response'
          description: Delete a short-lived certificate CA response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Delete a short-lived certificate CA response failure
      security:
        - api_email: []
          api_key: []
      summary: Delete a short-lived certificate CA
      tags:
        - Zone-Level Access short-lived certificate CAs
      x-api-token-group:
        - 'Access: Apps and Policies Write'
        - 'Access: Apps and Policies Write'
components:
  schemas:
    access_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/access_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/access_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    access_ca_components-schemas-id_response:
      allOf:
        - $ref: '#/components/schemas/access_api-response-single'
        - properties:
            result:
              properties:
                id:
                  $ref: '#/components/schemas/access_components-schemas-id'
              type: object
      type: object
    access_ca_components-schemas-response_collection-2:
      allOf:
        - $ref: '#/components/schemas/access_api-response-collection'
        - properties:
            result:
              items:
                $ref: '#/components/schemas/access_schemas-ca'
              type: array
      type: object
    access_ca_components-schemas-single_response-2:
      allOf:
        - $ref: '#/components/schemas/access_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/access_schemas-ca'
      type: object
    access_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
    access_uuid:
      description: UUID.
      example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      maxLength: 36
      type: string
      x-auditable: true
