openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/snippets:
    get:
      description: Fetches all snippets belonging to the zone.
      operationId: listZoneSnippets
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/snippets_ZoneId'
        - in: query
          name: page
          schema:
            $ref: '#/components/schemas/snippets_Page'
        - in: query
          name: per_page
          schema:
            $ref: '#/components/schemas/snippets_PerPage'
      responses:
        '200':
          $ref: '#/components/responses/snippets_Snippets'
        4XX:
          $ref: '#/components/responses/snippets_Failure'
        5XX:
          $ref: '#/components/responses/snippets_Failure'
      security:
        - api_token: []
        - api_email: []
          api_key: []
        - api_email: []
          api_key: []
      summary: List zone snippets
      tags:
        - Zone Snippets
      x-api-token-group:
        - Snippets Write
        - Snippets Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /zones/{zone_id}/snippets/snippet_rules:
    get:
      description: Fetches all snippet rules belonging to the zone.
      operationId: listZoneSnippetRules
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/snippets_ZoneId'
      responses:
        '200':
          $ref: '#/components/responses/snippets_SnippetRules'
        4XX:
          $ref: '#/components/responses/snippets_Failure'
        5XX:
          $ref: '#/components/responses/snippets_Failure'
      security:
        - api_token: []
        - api_email: []
          api_key: []
        - api_email: []
          api_key: []
      summary: List zone snippet rules
      tags:
        - Zone Snippets
      x-api-token-group:
        - Snippets Write
        - Snippets Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    put:
      description: Updates all snippet rules belonging to the zone.
      operationId: updateZoneSnippetRules
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/snippets_ZoneId'
      requestBody:
        $ref: '#/components/requestBodies/snippets_SnippetRules'
      responses:
        '200':
          $ref: '#/components/responses/snippets_SnippetRules'
        4XX:
          $ref: '#/components/responses/snippets_Failure'
        5XX:
          $ref: '#/components/responses/snippets_Failure'
      security:
        - api_token: []
        - api_email: []
          api_key: []
        - api_email: []
          api_key: []
      summary: Update zone snippet rules
      tags:
        - Zone Snippets
      x-api-token-group:
        - Snippets Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    delete:
      description: Deletes all snippet rules belonging to the zone.
      operationId: deleteZoneSnippetRules
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/snippets_ZoneId'
      responses:
        '200':
          $ref: '#/components/responses/snippets_SnippetRules'
        4XX:
          $ref: '#/components/responses/snippets_Failure'
        5XX:
          $ref: '#/components/responses/snippets_Failure'
      security:
        - api_token: []
        - api_email: []
          api_key: []
        - api_email: []
          api_key: []
      summary: Delete zone snippet rules
      tags:
        - Zone Snippets
      x-api-token-group:
        - Snippets Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /zones/{zone_id}/snippets/{snippet_name}:
    get:
      description: Fetches a snippet belonging to the zone.
      operationId: getZoneSnippet
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/snippets_ZoneId'
        - in: path
          name: snippet_name
          required: true
          schema:
            $ref: '#/components/schemas/snippets_SnippetName'
      responses:
        '200':
          $ref: '#/components/responses/snippets_Snippet'
        4XX:
          $ref: '#/components/responses/snippets_Failure'
        5XX:
          $ref: '#/components/responses/snippets_Failure'
      security:
        - api_token: []
        - api_email: []
          api_key: []
        - api_email: []
          api_key: []
      summary: Get a zone snippet
      tags:
        - Zone Snippets
      x-api-token-group:
        - Snippets Write
        - Snippets Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    put:
      description: Creates or updates a snippet belonging to the zone.
      operationId: updateZoneSnippet
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/snippets_ZoneId'
        - in: path
          name: snippet_name
          required: true
          schema:
            $ref: '#/components/schemas/snippets_SnippetName'
      requestBody:
        $ref: '#/components/requestBodies/snippets_Snippet'
      responses:
        '200':
          $ref: '#/components/responses/snippets_Snippet'
        4XX:
          $ref: '#/components/responses/snippets_Failure'
        5XX:
          $ref: '#/components/responses/snippets_Failure'
      security:
        - api_token: []
        - api_email: []
          api_key: []
        - api_email: []
          api_key: []
      summary: Update a zone snippet
      tags:
        - Zone Snippets
      x-api-token-group:
        - Snippets Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    delete:
      description: Deletes a snippet belonging to the zone.
      operationId: deleteZoneSnippet
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/snippets_ZoneId'
        - in: path
          name: snippet_name
          required: true
          schema:
            $ref: '#/components/schemas/snippets_SnippetName'
      responses:
        '200':
          $ref: '#/components/responses/snippets_Null'
        4XX:
          $ref: '#/components/responses/snippets_Failure'
        5XX:
          $ref: '#/components/responses/snippets_Failure'
      security:
        - api_token: []
        - api_email: []
          api_key: []
        - api_email: []
          api_key: []
      summary: Delete a zone snippet
      tags:
        - Zone Snippets
      x-api-token-group:
        - Snippets Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /zones/{zone_id}/snippets/{snippet_name}/content:
    get:
      description: Fetches the content of a snippet belonging to the zone.
      operationId: getZoneSnippetContent
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/snippets_ZoneId'
        - in: path
          name: snippet_name
          required: true
          schema:
            $ref: '#/components/schemas/snippets_SnippetName'
      responses:
        '200':
          $ref: '#/components/responses/snippets_SnippetContent'
        4XX:
          $ref: '#/components/responses/snippets_Failure'
        5XX:
          $ref: '#/components/responses/snippets_Failure'
      security:
        - api_token: []
        - api_email: []
          api_key: []
        - api_email: []
          api_key: []
      summary: Get a zone snippet content
      tags:
        - Zone Snippets
      x-api-token-group:
        - Snippets Write
        - Snippets Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    snippets_Page:
      default: 1
      description: The current page number.
      example: 1
      minimum: 1
      title: Page
      type: integer
      x-auditable: true
    snippets_PerPage:
      default: 25
      description: The number of results to return per page.
      example: 25
      minimum: 1
      title: Per Page
      type: integer
      x-auditable: true
    snippets_SnippetName:
      description: The identifying name of the snippet.
      example: my_snippet
      pattern: ^[A-Za-z0-9_]+$
      title: Snippet Name
      type: string
      x-auditable: true
    snippets_ZoneId:
      description: The unique ID of the zone.
      example: 9f1839b6152d298aca64c4e906b6d074
      pattern: ^[0-9a-f]{32}$
      title: Zone ID
      type: string
      x-auditable: true
  responses:
    snippets_Failure:
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/snippets_Response'
              - properties:
                  result:
                    enum:
                      - null
                    x-auditable: true
                  success:
                    enum:
                      - false
      description: A failure response.
    snippets_Null:
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/snippets_Response'
              - properties:
                  errors:
                    enum:
                      - []
                  result:
                    enum:
                      - null
                    x-auditable: true
                  success:
                    enum:
                      - true
      description: A null response.
    snippets_Snippet:
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/snippets_Response'
              - properties:
                  errors:
                    enum:
                      - []
                  result:
                    $ref: '#/components/schemas/snippets_Snippet'
                  success:
                    enum:
                      - true
      description: A snippet response.
    snippets_SnippetContent:
      content:
        multipart/form-data:
          schema:
            description: A snippet content response object.
            properties:
              files:
                $ref: '#/components/schemas/snippets_SnippetFiles'
            required:
              - files
            title: Snippet Content Response
            type: object
      description: A snippet content response.
      headers:
        cf-entrypoint:
          schema:
            $ref: '#/components/schemas/snippets_SnippetMainModule'
    snippets_SnippetRules:
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/snippets_Response'
              - properties:
                  errors:
                    enum:
                      - []
                  result:
                    $ref: '#/components/schemas/snippets_SnippetRules'
                  success:
                    enum:
                      - true
      description: A snippet rules response.
    snippets_Snippets:
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/snippets_Response'
              - properties:
                  errors:
                    enum:
                      - []
                  result:
                    description: A list of snippets.
                    items:
                      $ref: '#/components/schemas/snippets_Snippet'
                    title: Snippets
                    type: array
                  result_info:
                    $ref: '#/components/schemas/snippets_ResultInfo'
                  success:
                    enum:
                      - true
      description: A snippets response.
  requestBodies:
    snippets_Snippet:
      content:
        multipart/form-data:
          schema:
            description: A snippet object.
            properties:
              files:
                $ref: '#/components/schemas/snippets_SnippetFiles'
              metadata:
                description: Metadata about the snippet.
                properties:
                  main_module:
                    $ref: '#/components/schemas/snippets_SnippetMainModule'
                required:
                  - main_module
                title: Metadata
                type: object
            required:
              - metadata
              - files
            title: Snippet
            type: object
      required: true
    snippets_SnippetRules:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/snippets_SnippetRules'
      required: true
