openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/hold:
    get:
      description: >-
        Retrieve whether the zone is subject to a zone hold, and metadata about
        the hold.
      operationId: zones-0-hold-get
      parameters:
        - description: Zone ID
          in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/zones_schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/zones_schemas-api-response-single'
                  - properties:
                      result:
                        properties:
                          hold:
                            example: true
                            type: boolean
                          hold_after:
                            example: '2023-01-31T15:56:36+00:00'
                            type: string
                          include_subdomains:
                            example: false
                            type: string
                        type: object
                    type: object
          description: Successful Response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/zones_schemas-api-response-common-failure
          description: Client Error
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get Zone Hold
      tags:
        - Zone Holds
      x-api-token-group:
        - Trust and Safety Write
        - Trust and Safety Read
        - 'Zero Trust: PII Read'
        - Zaraz Edit
        - Zaraz Read
        - Zaraz Admin
        - 'Access: Apps and Policies Revoke'
        - 'Access: Apps and Policies Write'
        - 'Access: Apps and Policies Read'
        - 'Access: Apps and Policies Revoke'
        - 'Access: Mutual TLS Certificates Write'
        - 'Access: Organizations, Identity Providers, and Groups Write'
        - Zone Settings Write
        - Zone Settings Read
        - Zone Read
        - DNS Read
        - Workers Scripts Write
        - Workers Scripts Read
        - Zone Write
        - Workers Routes Write
        - Workers Routes Read
        - Stream Write
        - Stream Read
        - SSL and Certificates Write
        - SSL and Certificates Read
        - Logs Write
        - Logs Read
        - Cache Purge
        - Page Rules Write
        - Page Rules Read
        - Load Balancers Write
        - Load Balancers Read
        - Firewall Services Write
        - Firewall Services Read
        - DNS Write
        - Apps Write
        - Analytics Read
        - 'Access: Apps and Policies Write'
        - 'Access: Apps and Policies Read'
    post:
      description: >-
        Enforce a zone hold on the zone, blocking the creation and activation of
        zones with this zone's hostname.
      operationId: zones-0-hold-post
      parameters:
        - description: Zone ID
          in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/zones_schemas-identifier'
        - description: >-
            If provided, the zone hold will extend to block any subdomain of the
            given zone, as well

            as SSL4SaaS Custom Hostnames. For example, a zone hold on a zone
            with the hostname

            'example.com' and include_subdomains=true will block 'example.com',

            'staging.example.com', 'api.staging.example.com', etc.
          example: true
          in: query
          name: include_subdomains
          schema:
            type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/zones_schemas-api-response-single'
                  - properties:
                      result:
                        properties:
                          hold:
                            example: true
                            type: boolean
                          hold_after:
                            example: '2023-01-31T15:56:36+00:00'
                            type: string
                          include_subdomains:
                            example: true
                            type: string
                        type: object
                    type: object
          description: Successful Response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/zones_schemas-api-response-common-failure
          description: Client Error
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Create Zone Hold
      tags:
        - Zone Holds
      x-api-token-group:
        - Zone Write
    patch:
      description: >-
        Update the `hold_after` and/or `include_subdomains` values on an
        existing zone hold.

        The hold is enabled if the `hold_after` date-time value is in the past.
      operationId: zones-0-hold-patch
      parameters:
        - description: Zone ID
          in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/zones_schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                hold_after:
                  default: ''
                  description: >-
                    If `hold_after` is provided and future-dated, the hold will
                    be temporarily disabled,

                    then automatically re-enabled by the system at the time
                    specified

                    in this RFC3339-formatted timestamp. A past-dated
                    `hold_after` value will have

                    no effect on an existing, enabled hold. Providing an empty
                    string will set its value

                    to the current time.
                  example: '2023-01-31T15:56:36+00:00'
                  type: string
                include_subdomains:
                  default: false
                  description: >-
                    If `true`, the zone hold will extend to block any subdomain
                    of the given zone, as well

                    as SSL4SaaS Custom Hostnames. For example, a zone hold on a
                    zone with the hostname

                    'example.com' and include_subdomains=true will block
                    'example.com',

                    'staging.example.com', 'api.staging.example.com', etc.
                  example: true
                  type: boolean
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/zones_schemas-api-response-single'
                  - properties:
                      result:
                        properties:
                          hold:
                            example: false
                            type: boolean
                          hold_after:
                            type: string
                          include_subdomains:
                            example: false
                            type: string
                        type: object
                    type: object
          description: Successful Response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/zones_schemas-api-response-common-failure
          description: Client Error
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Update Zone Hold
      tags:
        - Zone Holds
      x-api-token-group:
        - Zone Write
    delete:
      description: >-
        Stop enforcement of a zone hold on the zone, permanently or temporarily,
        allowing the

        creation and activation of zones with this zone's hostname.
      operationId: zones-0-hold-delete
      parameters:
        - description: Zone ID
          in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/zones_schemas-identifier'
        - description: |-
            If `hold_after` is provided, the hold will be temporarily disabled,
            then automatically re-enabled by the system at the time specified
            in this RFC3339-formatted timestamp. Otherwise, the hold will be
            disabled indefinitely.
          example: '2023-01-31T15:56:36+00:00'
          in: query
          name: hold_after
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/zones_schemas-api-response-single'
                  - properties:
                      result:
                        properties:
                          hold:
                            example: false
                            type: boolean
                          hold_after:
                            type: string
                          include_subdomains:
                            example: false
                            type: string
                        type: object
                    type: object
          description: Successful Response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/zones_schemas-api-response-common-failure
          description: Client Error
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Remove Zone Hold
      tags:
        - Zone Holds
      x-api-token-group:
        - Zone Write
components:
  schemas:
    zones_schemas-api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/zones_schemas-messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/zones_schemas-messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    zones_schemas-api-response-single:
      allOf:
        - $ref: '#/components/schemas/zones_components-schemas-api-response-common'
        - properties:
            result:
              anyOf:
                - type: object
                - type: string
      type: object
    zones_schemas-identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
