openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/access/identity_providers:
    get:
      description: Lists all configured identity providers.
      operationId: zone-level-access-identity-providers-list-access-identity-providers
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/access_identity-providers_components-schemas-response_collection
          description: List Access identity providers response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: List Access identity providers response failure
      security:
        - api_email: []
          api_key: []
      summary: List Access identity providers
      tags:
        - Zone-Level Access identity providers
      x-api-token-group:
        - 'Access: Organizations, Identity Providers, and Groups Write'
        - 'Access: Organizations, Identity Providers, and Groups Read'
    post:
      description: Adds a new identity provider to Access.
      operationId: zone-level-access-identity-providers-add-an-access-identity-provider
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/access_schemas-identity-providers'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/access_identity-providers_components-schemas-single_response
          description: Add an Access identity provider response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Add an Access identity provider response failure
      security:
        - api_email: []
          api_key: []
      summary: Add an Access identity provider
      tags:
        - Zone-Level Access identity providers
      x-api-token-group:
        - 'Access: Organizations, Identity Providers, and Groups Write'
  /zones/{zone_id}/access/identity_providers/{identity_provider_id}:
    get:
      description: Fetches a configured identity provider.
      operationId: zone-level-access-identity-providers-get-an-access-identity-provider
      parameters:
        - in: path
          name: identity_provider_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/access_identity-providers_components-schemas-single_response
          description: Get an Access identity provider response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Get an Access identity provider response failure
      security:
        - api_email: []
          api_key: []
      summary: Get an Access identity provider
      tags:
        - Zone-Level Access identity providers
      x-api-token-group:
        - 'Access: Organizations, Identity Providers, and Groups Write'
        - 'Access: Organizations, Identity Providers, and Groups Read'
    put:
      description: Updates a configured identity provider.
      operationId: zone-level-access-identity-providers-update-an-access-identity-provider
      parameters:
        - in: path
          name: identity_provider_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/access_schemas-identity-providers'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/access_identity-providers_components-schemas-single_response
          description: Update an Access identity provider response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Update an Access identity provider response failure
      security:
        - api_email: []
          api_key: []
      summary: Update an Access identity provider
      tags:
        - Zone-Level Access identity providers
      x-api-token-group:
        - 'Access: Organizations, Identity Providers, and Groups Write'
    delete:
      description: Deletes an identity provider from Access.
      operationId: zone-level-access-identity-providers-delete-an-access-identity-provider
      parameters:
        - in: path
          name: identity_provider_id
          required: true
          schema:
            $ref: '#/components/schemas/access_uuid'
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/access_identifier'
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_id_response'
          description: Delete an Access identity provider response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Delete an Access identity provider response failure
      security:
        - api_email: []
          api_key: []
      summary: Delete an Access identity provider
      tags:
        - Zone-Level Access identity providers
      x-api-token-group:
        - 'Access: Organizations, Identity Providers, and Groups Write'
components:
  schemas:
    access_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/access_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/access_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    access_id_response:
      allOf:
        - $ref: '#/components/schemas/access_api-response-single'
        - properties:
            result:
              properties:
                id:
                  $ref: '#/components/schemas/access_uuid'
              type: object
      type: object
    access_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
    access_identity-providers_components-schemas-response_collection:
      allOf:
        - $ref: '#/components/schemas/access_api-response-collection'
        - properties:
            result:
              items:
                anyOf:
                  - $ref: '#/components/schemas/access_schemas-azureAD'
                  - $ref: '#/components/schemas/access_schemas-centrify'
                  - $ref: '#/components/schemas/access_schemas-facebook'
                  - $ref: '#/components/schemas/access_schemas-github'
                  - $ref: '#/components/schemas/access_schemas-google'
                  - $ref: '#/components/schemas/access_schemas-google-apps'
                  - $ref: '#/components/schemas/access_schemas-linkedin'
                  - $ref: '#/components/schemas/access_schemas-oidc'
                  - $ref: '#/components/schemas/access_schemas-okta'
                  - $ref: '#/components/schemas/access_schemas-onelogin'
                  - $ref: '#/components/schemas/access_schemas-pingone'
                  - $ref: '#/components/schemas/access_schemas-saml'
                  - $ref: '#/components/schemas/access_schemas-yandex'
                  - $ref: '#/components/schemas/access_schemas-onetimepin'
              type: array
          type: object
      type: object
    access_identity-providers_components-schemas-single_response:
      allOf:
        - $ref: '#/components/schemas/access_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/access_schemas-identity-providers'
      type: object
    access_schemas-identity-providers:
      anyOf:
        - $ref: '#/components/schemas/access_schemas-azureAD'
        - $ref: '#/components/schemas/access_schemas-centrify'
        - $ref: '#/components/schemas/access_schemas-facebook'
        - $ref: '#/components/schemas/access_schemas-github'
        - $ref: '#/components/schemas/access_schemas-google'
        - $ref: '#/components/schemas/access_schemas-google-apps'
        - $ref: '#/components/schemas/access_schemas-linkedin'
        - $ref: '#/components/schemas/access_schemas-oidc'
        - $ref: '#/components/schemas/access_schemas-okta'
        - $ref: '#/components/schemas/access_schemas-onelogin'
        - $ref: '#/components/schemas/access_schemas-pingone'
        - $ref: '#/components/schemas/access_schemas-saml'
        - $ref: '#/components/schemas/access_schemas-yandex'
    access_uuid:
      description: UUID.
      example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      maxLength: 36
      type: string
      x-auditable: true
